### ISSUE TITLE
Trimming text

### ISSUE THREAD

**Issue by pleaseking** [Microsoft/Win2D#100]
Hi,

How do I make Win2D output text trimmed to fit the defined layout size with the ellipsis at the end? I can see the Trimming options in CanvasTextLayout but they only define granularity and delimiter, not the real trimming sign. This results in no ellipsis being drawn at the moment - or am I missing something?

This D2D doc shows a way to specify the trimming sign if I am not mistaken:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd316684(v=vs.85).aspx

**Comment by clandrew** [comment]
At this time, Win2D does not have exposure for different trimming signs.

But rest assured, there is a plan for it- it's on our backlog, under the item "Expose DWrite built-in ellipsis trimming sign". 

As a workaround in the meantime, if your app is in C++, native interop with DWrite could be used to directly to set the trimming sign.

**Comment by pleaseking** [comment]
Just if this is quick - maybe you could post an example? The problem is that it does not seem trivial - DWrite wants IDWriteInlineObject, not just a character or string..

**Comment by clandrew** [comment]
Sure- you create the IDWriteInlineObject using this [IDWriteFactory::CreateEllipsesTrimmingSign](https://msdn.microsoft.com/en-us/library/windows/desktop/dd368194(v=vs.85).aspx).

The code looks something like

<code>
ComPtr&lt;IDWriteInlineObject&gt; inlineObject;
</code>
<code>
dwriteFactory-&gt;CreateEllipsisTrimmingSign(
  textLayout,
  &inlineObject);
</code>
<code>
DWRITE_TRIMMING trimming = 
  {DWRITE_TRIMMING_GRANULARITY_CHARACTER, 0, 0};
</code>
<code>
textLayout->SetTrimming(&trimming, inlineObject);
</code>

**Comment by pleaseking** [comment]
Thanks for the tip, sorry for asking noob questions - but do I create an IDWriteFactory properly? I am trying the following code now, it runs fine but results in no trimming at all no matter what - even if I specify `CanvasTrimmingGranularity::Word` later either for CanvasTextFormat or CanvasTextLayout:

    auto hr = DWriteCreateFactory(
		DWRITE_FACTORY_TYPE_SHARED,
		__uuidof(IDWriteFactory),
		&dwriteFactory
		);

	if (SUCCEEDED(hr))
	{
		hr = dwriteFactory->CreateEllipsisTrimmingSign(
			nativeTextFormat.Get(),
			&inlineObject);

		if (SUCCEEDED(hr))
		{

			DWRITE_TRIMMING trimming =
			{ DWRITE_TRIMMING_GRANULARITY_WORD, 0, 0 };

			nativeTextFormat->SetTrimming(&trimming, inlineObject.Get());

			pFormat = GetOrCreate<CanvasTextFormat>(nativeTextFormat.Get());
		}
	}

**Comment by clandrew** [comment]
No worries, these definitely aren't newbie questions- your code sample as far as creating the factory and trimming sign looks right to me. 

Did you verify that the text you are trying to trim actually overflows the requestedWidth/requestedHeight of the CanvasTextLayout? 

If you are using horizontal text, and want trimming on the left or right side of the layout box, did you verify that word wrapping is disabled? Otherwise, the text will be word-wrapped instead of trimmed.

Here's a fuller code sample of how to set up the trimming, with an example of what it looks like:

```
CanvasTextLayout^ defaultTextLayout;
CanvasTextLayout^ ellipsisTextLayout;
void TrimmingSign::MainPage::m_canvas_CreateResources(CanvasControl^ sender, CanvasCreateResourcesEventArgs^ args)
{
    auto textFormat = ref new CanvasTextFormat();

    ellipsisTextLayout = ref new CanvasTextLayout(sender, L"The quick brown fox jumped over the lazy dog", textFormat, 100, 100);

    ComPtr<IDWriteTextFormat> nativeTextFormat = GetWrappedResource<IDWriteTextFormat>(ellipsisTextLayout);

    ComPtr<IDWriteInlineObject> inlineObject;
    ComPtr<IDWriteFactory> dwriteFactory;
    VERIFY(DWriteCreateFactory(DWRITE_FACTORY_TYPE_SHARED, __uuidof(IDWriteFactory), &dwriteFactory));

    VERIFY(dwriteFactory->CreateEllipsisTrimmingSign(nativeTextFormat.Get(), &inlineObject));

    DWRITE_TRIMMING trimming =
    { DWRITE_TRIMMING_GRANULARITY_WORD, 0, 0 };

    nativeTextFormat->SetTrimming(&trimming, inlineObject.Get());
}

void TrimmingSign::MainPage::m_canvas_Draw(CanvasControl^ sender, CanvasDrawEventArgs^ args)
{
    args->DrawingSession->DrawTextLayout(ellipsisTextLayout, 100.0f, 100.0f, Windows::UI::Colors::Black);
    args->DrawingSession->DrawRectangle(100.0f, 100.0f, 100.0f, 100.0f, Windows::UI::Colors::Black);
}
```

![image](https://cloud.githubusercontent.com/assets/8118775/8018652/3e548d34-0bdc-11e5-82b3-5227b84134e1.png)

**Comment by pleaseking** [comment]
Thanks a lot - I got it working! For some reason my changes to `CanvasTextFormat` that are done after `CanvasTextLayout` gets created are not applied (in your example you seem to be doing that just fine) - and I need this as I need to know text width and height to decide whether I need trimming or not - but I am just re-creating `CanvasTextLayout` if needed as a workaround.

**Comment by clandrew** [comment]
Glad it worked!

**Comment by shawnhar** [comment]
Note that Win2D 1.6.0 (which we'll be pushing later this morning) adds a CanvasTextFormat.TrimmingSign property to do this more easily.
