### ISSUE TITLE
CanvasTextFormat::FontWeight and CanvasAnimatedControl game loop

### ISSUE THREAD

**Issue by pleaseking** [Microsoft/Win2D#102]
When I am trying to create a `CanvasTextFormat` and assign its `FontWeight` property in the game loop of `CanvasAnimatedControl`, the app crashes because 'interface used from the wrong thread'. Other `CanvasTextFormat` properties work just fine.

**Comment by clandrew** [comment]
Is this while using FontWeight's static properties? 

If so, this is a known issue (internally). XAML is imposing a thread restriction on these- they can only be accessed from the control's UI thread. For all other threads, including the game loop thread, accessing the property fails. But there's no real reason this restriction should exist. 

I don't know the status of the internal issue today, but if this is indeed it, I can follow up with you. Maybe we can look forward to a fix.

One possible workaround, in the meantime, is to set up the font weight without using any of the static properties. For example:

````
        private void animatedControl_Draw(ICanvasAnimatedControl sender, CanvasAnimatedDrawEventArgs args)
        {
            CanvasTextLayout t = new CanvasTextLayout(sender, "some text", new CanvasTextFormat(), 1000, 1000);

            //t.SetFontWeight(0, 1, FontWeights.Medium); // Doesn't work

            FontWeight w = new FontWeight();
            w.Weight = 500;
            t.SetFontWeight(0, 1, w);
        }
````
The reference for the static properties is [here](https://www.microsoft.com/typography/otspec/os2.htm#wtc).

**Comment by pleaseking** [comment]
Yes, this is about using static properties. Well, the workaround is more than fine, so no need to fix in a rush, thanks!

**Comment by clandrew** [comment]
Sure, no problem.

**Comment by shawnhar** [comment]
fyi, this issue is fixed in Windows 10.
