### ISSUE TITLE
Suggestion: deferral idiom for TrackAsyncActions

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/Win2D#104]
Currently the idiom for TrackAsyncAction is kind of idiosyncratic...
```cs
void CreateResources(CanvasControl sender, CanvasCreateResourcesEventArgs e)
{
    Task task = MyLoadAsync(); // start doing the initialization work
    e.TrackAsyncAction(task.AsAsyncAction());
}
```

I think it'd be more conventional to use the "deferral" pattern from WinRT, like we're familiar with from App.OnSuspending:
```cs
async void CreateResources(CanvasControl sender, CanvasCreateResourcesEventArgs e)
{
    var deferral = e.SuspendingOperation.GetDeferral();
    bitmap = await CanvasBitmap.LoadAsync(canvas1, "explosion.png");
    deferral.Complete();
}
```

I can sort of work around it and get the deferral pattern even in the current Win2D API, but it's not as cross-language-nice as if you had the deferral pattern directly:
```cs
async void CreateResources(CanvasControl sender, CanvasCreateResourcesEventArgs e)
{
    var tcs = new TaskCompletionSource<bool>();
    e.TrackAsyncAction(tcs.Task.AsAsyncAction());

    bitmap = await CanvasBitmap.LoadAsync(canvas1, "explosion.png");
    tcs.SetResult(true);
}
```

In all, I think that this "imperative await" style of coding is than the "callback" style that's currently used in the sample gallery. And I think the "deferral" pattern (where you provide your own deferral object) is nicer, because having to call AsAsyncAction in our own code is a bit ugly.

What happens to exceptions? Notionally we should wrap it up as shown below. But I personally wouldn't bother, since (1) I don't actually even know whether your deferral method TrackAsyncActions handles exceptions properly, and (2) if I'm unable to load resources then I'm happy for my application to crash.
```cs
async void CreateResources(CanvasControl sender, CanvasCreateResourcesEventArgs e)
{
    var tcs = new TaskCompletionSource<bool>();
    e.TrackAsyncAction(tcs.Task.AsAsyncAction());

    try
    {
        bitmap = await CanvasBitmap.LoadAsync(canvas1, "explosion.png");
        tcs.TrySetResult(true);
    }
    catch (Exception ex)
    {
        tcs.TrySetException(ex);
    }
}
```

**Comment by damyanp** [comment]
This series of blog posts, starting from http://blogs.msdn.com/b/win2d/archive/2014/12/01/handling-lost-devices-in-win2d.aspx, explains the motivation for the TrackAsyncAction design - it is explicitly there in order to handle exceptions, in particular the device lost exception.

I notice that the documentation for TrackAsyncAction does not explain this very well.  I've added an item to the backlog to improve the documentation here.

**Comment by ljw1004** [comment]
@damyanp I think you've misunderstood. The deferral pattern vs TrackAsyncAction both handle device loss exceptions the same.

The only differences are:

(1) TrackAsyncAction enforces that all exceptions get caught, while the deferral pattern requires the caller to put in a try/catch block explicitly

(2) TrackAsyncAction forces you down an unpleasant code pattern with callbacks

(3) TrackAsyncAction is unconventional and unfamiliar.

Here's how the deferral pattern would handle exceptions:
```cs
async void CreateResources(CanvasControl sender, CanvasCreateResourcesEventArgs e)
{
    var deferral = e.SuspendingOperation.GetDeferral();

    try
    {
        bitmap = await CanvasBitmap.LoadAsync(canvas1, "explosion.png");
        deferral.Complete();
    }
    catch (Exception ex)
    {
        deferral.Failed(ex);
    }
}
```

Again, device-loss situations are handled exactly the same between this and TrackAsyncAction. But here I've been able to write my code in a familiar imperative/await style, and re-use what I've learned from the rest of WinRT.

**Comment by shawnhar** [comment]
> TrackAsyncAction enforces that all exceptions get caught, while the deferral pattern requires the caller to put in a try/catch block explicitly

Exactly.  Our experience is that most developer are not aware of device lost, so will not think to add this catch block.  The design goal here was to construct an API such that device lost would "just work" without requiring the developer to do anything special for it.

**Comment by ljw1004** [comment]
Okay, fair enough. In my quest to remove layers of indirection, this is what I've ended up with:

```vb
Private Sub CreateResources(sender As CanvasControl, e As CanvasCreateResourcesEventArgs)
    Dim loadTask =
        Async Function()
            bitmap = Await CanvasBitmap.LoadAsync(sender, "explosion.png")
        End Function

    e.TrackAsyncAction(loadTask().AsAsyncAction)
End Sub
```
