### ISSUE TITLE
Inputting text in other languages

### ISSUE THREAD

**Issue by zhakopian** [Microsoft/Win2D#113]
I'm trying to add the possibility to use any language as keyboard input into my program. I don't think I have a good understanding of what this entails in Win2D

I'm converting the input from CharacterReceived into a string and inserting it into my CanvasTextLayout and also manually setting the locale of the Format and Layout objects for testing purposes. This all works fine for English characters, but if I try to use another languages keyboard (which I've downloaded so that I can test through the on-screen keyboard), it'll get their keycode which is usually way above anything I see for the english keycodes and generate a symbol from what I'm guessing is the extended ascii table. It's definitely not from the language that I'm trying.

Copy and pasting other languages text into my program works and hard-coding it into my program works to render it. I just can't get it from the keyboard

Any thoughts?

**Comment by shawnhar** [comment]
Inputting text in arbitrary languages is outside the scope of Win2D.  The Win2D text APIs can draw Unicode strings of any language (or combinations of languages) but for the input part you will need to rely on other non-Win2D Windows API surface.

I don't know a lot about this area, but this thread seems relevant:  https://social.msdn.microsoft.com/forums/windowsapps/en-us/7a8e92dc-d2b9-4b46-b71c-f5366e82ddbf/how-to-use-corewindowcharacterreceived

Note that text input for all languages is a REALLY hard problem!  Some languages are like English where every physical key maps to either a single character or a couple of different characters depending on the shift state.  But others require more complicated contextual mappings, and in some cases even specialized text entry UI (called an IME).

By far the easiest way to handle all this complexity is to let XAML do it for you and use their existing text input controls...

**Comment by shawnhar** [comment]
Closing issue as there is no work in Win2D to be tracked here.
