### ISSUE TITLE
Win2D 0.0.22 is not compatible with .NETCore,Version=v5.0 (win10-x64-aot).

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/Win2D#115]
I'm trying to use Win2D against the latest Windows 10 build 10166 and corresponding Windows 10 SDK.  Do you need to update something on your end to make this compatible?  Doesn't seem like that should be the case.

**Comment by shawnhar** [comment]
For Windows 10 development, Win2D currently supports the Visual Studio 2015 Release Candidate (RC) build which was released earlier this year.

We will update it to Visual Studio 2015 RTM once that is released with UWP support on July 29 (http://blogs.windows.com/buildingapps/2015/06/29/release-dates-and-compatibility-visual-studio-2015-and-windows-10-sdk/)

Unfortunately we don't have the bandwidth to support other intermediate releases of Visual Studio or the Windows 10 SDK.  Sometimes you may get lucky and this will work ok, but it usually doesn't :-(

**Comment by rkeithhill** [comment]
No problem at all.  I can wait.

**Comment by adammarks** [comment]
As a temporary workaround until 7/29 Windows SDK drop occurs you can add a reference to the Win2D winmd file.

**Comment by shawnhar** [comment]
Win2D 1.0.0, released today, has full support for Windows 10 UWP and Visual Studio 2015 RTM.
