### ISSUE TITLE
Clarify meaning of "For asynchronous resource loading, controls are encouraged to use TrackAsyncAction(IAsyncAction) with CreateResources to ensure correct behavior."

### ISSUE THREAD

**Issue by sandersaares** [Microsoft/Win2D#120]
The following statement in the documentation chapter "Loading resources outside of CreateResources" is unclear.

> For asynchronous resource loading, controls are encouraged to use TrackAsyncAction(IAsyncAction) with CreateResources to ensure correct behavior.

What is "correct behavior"? As far as I can tell in some quick experiments, TrackAsyncAction() appears to delay drawing until the "tracked" action is complete. Why is this correct or desirable? At the moment, I am deliberately not calling this method because I want to construct some nontrivial amount of geometry in the background, when other things are already being drawn.

It may be that I am doing something wrong but the main point here is that the documentation rather leaves the motivation unclear on this point. Some clarification would be very useful.

**Comment by shawnhar** [comment]
The doc for TrackAsyncAction:

http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_UI_CanvasCreateResourcesEventArgs_TrackAsyncAction.htm

go into detail about exactly what this method does, and link to a series of blog posts that explain the background of this design in more detail.
