### ISSUE TITLE
Guidance requested for properly testing CreateResources implementation in lost device scenario

### ISSUE THREAD

**Issue by sandersaares** [Microsoft/Win2D#121]
It would be helpful if the documentation outlined how a CreateResources implementation can be properly tested, to ensure that it functions in all the situations beyond the first load. There is talk of "lost devices" but as a plain Joe app developer, I have no idea what that means or how to cause such a situation for testing out my loading logic.

**Comment by shawnhar** [comment]
Thanks for the suggestion - I've added this to our backlog and it will be prioritized during our next sprint planning (on Monday).

**Comment by shawnhar** [comment]
I'm working on adding a proper doc about this to Win2D, but short answer to get you unblocked:

- To simulate a lost device, bring up Device Manager while your app is running, open Display Adapters, and disable the driver for your GPU.  This will switch the system to software rendering mode, causing Win2D (and anything else that is drawing graphics) to lose their graphics device and then recreate a new one.

- To test DPI change, open Display Settings while the app is running, and "Change the size of text, app, and other items" to a different value.  Apply, but no need to bother logging out and back in like it will prompt you to.

Both of these are much easier to do on Win10 than 8.1.

**Comment by shawnhar** [comment]
Improved documentation now online:  http://microsoft.github.io/Win2D/html/HandlingDeviceLost.htm
