### ISSUE TITLE
RadialGradientBrush reuse when changing color of a CanvasGradientStop?

### ISSUE THREAD

**Issue by pret83** [Microsoft/Win2D#123]
I discovered, that I can't change color of a CanvasGradientStop in a RadialGradientBrush, so I have to recreate Brushes (dispose, then instantiate new ones) in every drawing cycle during ColorAnimation in my UserControl. Is this causing some performance drawback? What's the best practice in this situation? Can I somehow recycle the existing RadialGradientBrush objects?
Thank's in advance.

**Comment by shawnhar** [comment]
You are correct, it is not possible to change the gradient of an existing brush so the only way to do this is to dispose the old brush and then create a new one.

Creating new gradient brushes is more expensive than reusing an existing brush, but not horrendously so unless you have very many of them, and that's just the cost you have to pay if you need to animate the gradient information.
