### ISSUE TITLE
ObjectDisposedException in CanvasBitmap.LoadAsync

### ISSUE THREAD

**Issue by stefanolson** [Microsoft/Win2D#124]
I have some code where I want to load multiple bitmaps, however once I've loaded one bitmap to the device it gives me an exception:
System.ObjectDisposedException was unhandled by user code
  HResult=-2147483629
  Message=The object has been closed. (Exception from HRESULT: 0x80000013)
  ObjectName=""
  Source=mscorlib
  StackTrace:
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at MyApp.TileGenerator.<CreateWideTile>d__2.MoveNext()
  InnerException: 

The code is pretty simple:
var uriFileName = string.Format("ms-appx:///MyApp/Icons/iconname{0}.png", i);
using (CanvasBitmap image = await CanvasBitmap.LoadAsync(device, new Uri(uriFileName, UriKind.Absolute)))

Device is here:
using (var device = new CanvasDevice())
and used like this:
using (CanvasRenderTarget offscreen = new CanvasRenderTarget(device, 310, 150, 96))
and then:
using (CanvasDrawingSession ds = offscreen.CreateDrawingSession())

I am rendering offscreen to create a live tile.

As I say, it works perfectly the first time, but the second time around the loop it gives me that exception (and the device still appears to be functioning, as the image that I working on outputs correctly).  Any ideas what I am doing wrong?

Other than that have found Win2D to work really well, it's nice to have a good C# layer.

Stefan

**Comment by shawnhar** [comment]
Can you share a more complete piece of code, including some from either side of the line this exception is coming from?  (and show us which line that is)

This exception means you are trying to use an object that has been disposed.  Possibly due to an end of scope of one of the using blocks, but I can't tell enough about how it all fits together from the snippets you posted above.

Also please share what platform and Win2D version you are targetting.

**Comment by stefanolson** [comment]
Thanks, re-wrote the code and realised that there was a missing await, which has solved the problem.  No idea how I missed that.

Thanks,
Stefan
