### ISSUE TITLE
Are gradients broken in Windows 10 UWP apps for C++?

### ISSUE THREAD

**Issue by Escovado** [Microsoft/Win2D#126]
I've been using Win2D for a while under Windows 8.1. Converted my project over to Windows 10 UWP in Visual; Studio 2015. Tried using gradients to fill a rectangle, but all I'm getting is a solid color that is a combo of the given stop colors.

To make sure something wasn't messed up in my original project, I had Visual Studio create a new, blank, C++ UWP app for Windows 10. I then added the latest nuget package for Win2D, then implemented the simple demo program from the Introduction page in C++.  Everything works perfectly.

I then added one line of a FillRectangle call using the rainbow gradient provided by the system:

void TestWin2D::MainPage::CanvasControl_Draw(Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl^ sender, Microsoft::Graphics::Canvas::UI::Xaml::CanvasDrawEventArgs^ args)
{
    args->DrawingSession->DrawEllipse(155, 115, 80, 30, Colors::Black, 3);
    args->DrawingSession->DrawText("Hello, world!", 100, 100, Colors::Yellow);
    args->DrawingSession->FillRectangle(Windows::Foundation::Rect(200, 200, 200, 200), Microsoft::Graphics::Canvas::Brushes::CanvasLinearGradientBrush::CreateRainbow(TheCanvas, 0.5f));
}

The gradient is just a solid color no matter what I set the float to. Am I doing something wrong here? Thanks.

**Comment by shawnhar** [comment]
You need to set the brush StartPoint and EndPoint properties to define how the gradient is mapped onto your scene.  By default these are both 0,0, so the entire gradient is completed within the top left pixel of the screen, leaving only its end color to be extended over any other areas that get filled.

For instance to map the gradient diagonally across your rectangle:

            brush.StartPoint = new Vector2(200, 200);
            brush.EndPoint = new Vector2(400, 400);

Different EndPoint values could map it horizontally, or vertically, etc.

**Comment by Escovado** [comment]
Thank you for your quick response. I'm glad it is something simple. In C# the StartPoint and EndPoint properties can be set. There does not seem to be a set method for the these properties in C++. At least I can't find it. The IDE reveals only "get" and the compiler won't accept the assignment operator for it. This is part of the reason why I'm a little confused about this.

**Comment by shawnhar** [comment]
Great, glad you got it working!
