### ISSUE TITLE
Issues with CanvasLayer and transparency on Nokia 630

### ISSUE THREAD

**Issue by pleaseking** [Microsoft/Win2D#127]
I can see some weird behavior on Nokia 630. I need to draw a number of text strings over background, and the way I am doing it is the following (simplified):
 - create a layer to clip text to specific region
 - draw text
 - dispose layer

It all works just fine except on Nokia 630 where it produces graphical artifacts - like arbitrary lines and boxes, text not visible, etc - it seems it is related to background being completely transparent but I am not 100% sure. 

The workaround I found is to use `CreateLayer` with `CanvasLayerOptions::InitializeFromBackground` - this makes code work on Nokia 630 too. However, this leads to problems when the background is not opaque - alpha gets doubled when layer is blended back to canvas.

So two questions: 
 - are there any known issues with Nokia 630?
 - is there any way to improve my workaround to support non-opaque backgrounds?

**Comment by shawnhar** [comment]
This is a known issue (#50).  The root cause is a graphics driver bug, but Windows 10 includes a workaround for the problem.  Unfortunately I could not find any way to work around it while still running Windows 8.1 OS.

**Comment by pleaseking** [comment]
Any way to solve a restricted problem - I just need to clip text to a specific rectangle.. Do not really need full layer functionality..

**Comment by shawnhar** [comment]
Clipping to a rectangle (using the CreateLayer overload that takes a rect rather than a CanvasGeometry, and specifying alpha = 1) ends up calling the D2D PushAxisAlignedClip API, as opposed to the full PushLayer.

Are you seeing the same rendering issues when using that overload?   I don't expect PushAxisAlignedClip to hit this driver bug.

**Comment by pleaseking** [comment]
You mean alpha = 255? Let me try this, thanks!

**Comment by shawnhar** [comment]
CreateLayer takes alpha as a float, so 1.0f is fully opaque.

**Comment by pleaseking** [comment]
Shawn, I am glad to report that the overload you mentioned helped. Actually I started with that but it did not work but I passed alpha = 255 - you might want to treat alpha > 1 as alpha == 1..

**Comment by pleaseking** [comment]
So with alpha = 1.0f it works. Thanks!

**Comment by shawnhar** [comment]
Glad to hear the workaround unblocked you!
