### ISSUE TITLE
Depth / projections with Transform3D

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/Win2D#128]
Hello guys,

I'm trying to create essentially what the XAML Plane Projection class does it regards to simple 3D transforms - in this case a Y Axis transformation to make it look as if the image was been tilted in 3D - but I'm not having much luck.

Going off this page for the D2D Transform 3D code ( https://msdn.microsoft.com/en-us/library/windows/desktop/dn441538(v=vs.85).aspx ), I'd assume the code below should be a re-creation of the source they provide on the page - yet no matter what I do no depth / rotation is ever applied

```
void CanvasAnimatedControl_Draw(ICanvasAnimatedControl sender, CanvasAnimatedDrawEventArgs args)
        {
            using (CanvasCommandList cl = new CanvasCommandList(sender))
            using (Transform3DEffect trans = new Transform3DEffect { Source = cl })
            {
                using (var cls = cl.CreateDrawingSession())
                {
                    cls.FillRectangle(new Rect(0, 0, 522, 392), Colors.Red);
                }

                trans.TransformMatrix =
                    Matrix4x4.CreateTranslation(0, -192f, 0) *
                    Matrix4x4.CreateRotationY(Maths.DegreesToRadians(30)) *
                    Matrix4x4.CreateTranslation(0, 192f, 0);

                args.DrawingSession.DrawImage(trans);
            }
        }
```

And I essentially end up with a flat image that I started with (albeit occasionally squished on the Y axis - but with no depth). I'm not quite sure what I'm doing wrong here, any ideas?

(Also, was there any reason the Perspective Transform Effect was not implemented? https://msdn.microsoft.com/en-us/library/windows/desktop/hh706310(v=vs.85).aspx - granted it's still not as simple to use as a XAML Plane Projection, but it seems a bit more focused for this usecase )

**Comment by shawnhar** [comment]
To include perspective in the rendering, your matrix needs to include a perspective transform.  A full 3D rendering transform is typically set up something like:

    Matrix4x4 world = whatever is needed to position the object in 3D world space (if anything)
    Matrix4x4 view = Matrix4x4.CreateLookAt(camera settings);
    Matrix4x4 projection = Matrix4x4.CreatePerspectiveFieldOfView(projection settings);

    effect.TransformMatrix = world * view * projection;

Without the projection part, you're just getting rotation/scaling/translation in 2D screen space, without any perspective foreshortening.

Old but still true article explaining these three transforms and the three different coordinate spaces they represent:  xbox.create.msdn.com/downloads/?id=130

**Comment by shawnhar** [comment]
Oh yeah, missed this part of your question:  Win2D does not include a perspective transform effect separately from the general purpose Transform3D because the Matrix4x4 class already includes a rich set of CreatePerspective* methods, so we didn't see a need to duplicate that functionality by baking some subset of it directly into the effect.

**Comment by jonbprime** [comment]
Hey guys, I'm having a similar problem. I'm doing something like this:

 ```
using (CanvasDrawingSession clds = canvas_command_list.CreateDrawingSession())
{
  clds.DrawRectangle(10,10,200,200,Colors.Black);
  clds.DrawText("Hello", 100, 100, Colors.Black);
}
.
.
.
Matrix4x4 view = Matrix4x4.CreateLookAt(new Vector3(0,0,20), Vector3.Zero, Vector3.UnitY);
Matrix4x4 projection = Matrix4x4.CreatePerspectiveFieldOfView(.1f,1, .1f ,100f);
transform_effect_.TransformMatrix = view * projection;

args.DrawingSession.DrawImage(transform_effect_);
```
Which seems to work great. However, If I move the camera just 1 in Y, the output becomes very distorted. I would have thought I would have just seen a small shift in Y. What am I doing wrong?

**Comment by shawnhar** [comment]
I tried this code and it works like I would expect.  With a 3D perspective projection, moving the camera changes the angle at which surfaces are oriented relative to the eye.  Your field of view is extremely narrow, so even a small shift of angle causes a dramatic change in how the image is transformed.

It is easier to understand what is going on with this kind of transform if you animate changing the camera properties.

**Comment by jonbprime** [comment]
Thanks for the reply. I think my problem was that fact that I was moving the camera but keeping the look point the same. This produces a "view rotation" instead of the shift I was expecting. If I move the camera and the look point together, then I see the shift I was expecting.

-J

**Comment by JohnnyWestlake** [comment]
To add my two cents, I'd like to vote for getting the 3DPerspectiveTransform effect added to Win2D. It's a lot easier to work with for people coming from XAML & PlaneProjections - it's certainly possible to achieve the effect with out, but it's easier with the effect for an outsider. 

Same can be said for a lot of the effects like StraightenEffect, GreyscaleEffect, ContrastEffect etc - you can achieve what they do without their effects being projected in Win2D (ColorMatrix & Rotate & Scaling), but having defined effects makes life easier!
