### ISSUE TITLE
How to calculate geometry outline area?

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/Win2D#129]
I want to calculate an area of geometry outline with specified stroke thickness.
How to do this?

**Comment by clandrew** [comment]
You can use [CanvasGeometry.Stroke](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Geometry_CanvasGeometry_Stroke.htm) to obtain a new geometry with the specified stroke thickness.

Then, you can use [ComputeArea](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Geometry_CanvasGeometry_ComputeArea.htm) on the resulting geometry to get the area.

**Comment by damyanp** [comment]
Does [CanvsasGeometry.ComputeArea](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Geometry_CanvasGeometry_ComputeArea.htm) do what you require?

**Comment by xperiandri** [comment]
Actually I do this
```C#
    class RectangleRecognizer : IShapeRecognizer
    {
        float masterStrokeThickness = 20f;
        float drawStrokeThickness = 3f;

        public async Task<Tuple<float, FrameworkElement>> RecognizeAsync(IReadOnlyList<InkStroke> strokes, Rect boundingRect)
        {
            var device = App.Canvas; //new CanvasDevice();
            device.Draw += Device_Draw;

            CanvasPathBuilder pathBuilder = new CanvasPathBuilder(device);
            foreach (var stroke in strokes)
            {
                var segments = stroke.GetRenderingSegments();

                using (var enumerator = segments.GetEnumerator())
                {
                    if (!enumerator.MoveNext())
                        break;
                    var segment = enumerator.Current;
                    pathBuilder.BeginFigure(segment.Position.ToVector2());
                    while (enumerator.MoveNext())
                    {
                        segment = enumerator.Current;
                        pathBuilder.AddCubicBezier(segment.BezierControlPoint1.ToVector2(),
                                                   segment.BezierControlPoint2.ToVector2(),
                                                   segment.Position.ToVector2());
                    }
                    pathBuilder.EndFigure(CanvasFigureLoop.Closed);
                }
            }
            Rect rectangleRect;
            var probability = await Task.Run(() =>
            {
                double shift = masterStrokeThickness / 2f;
                rectangleRect = new Rect(new Point(boundingRect.Left + shift, boundingRect.Top + shift), new Point(boundingRect.Right - shift, boundingRect.Bottom - shift));
                rectangleGeometry = CanvasGeometry.CreateRectangle(device, rectangleRect).Stroke(drawStrokeThickness);

                drawingGeometry = CanvasGeometry.CreatePath(pathBuilder).Stroke(drawStrokeThickness);
                var combination = drawingGeometry.CombineWith(rectangleGeometry, Matrix3x2.Identity, CanvasGeometryCombine.Union);

                var masterArea = rectangleGeometry.Outline().ComputeArea();
                var area = combination.Outline().ComputeArea();
                return masterArea / area;
            });
            var rectangle = new Path { Data = new RectangleGeometry { Rect = rectangleRect } };
            return new Tuple<float, FrameworkElement>(probability, rectangle);
        }

        CanvasGeometry drawingGeometry;
        CanvasGeometry rectangleGeometry;
        private void Device_Draw(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args)
        {
            args.DrawingSession.DrawGeometry(rectangleGeometry, Colors.Red, masterStrokeThickness);
            args.DrawingSession.DrawGeometry(drawingGeometry, Colors.Blue, drawStrokeThickness);
        }
    }
```

![35](https://cloud.githubusercontent.com/assets/2365592/9314915/99f18af2-4534-11e5-8146-d89c4f67c97a.png)

But the area is different it 2 times.
What do I do wrong?

**Comment by xperiandri** [comment]
masterArea = 3980.077
area = 7166.808
How?

**Comment by clandrew** [comment]
masterArea is the area of the rectangle stroke (rectangleGeometry).

area includes more than that, doesn't it? It's the union of drawingGeometry and the rectangleGeometry. And drawingGeometry is created off a pathBuilder from some beziers, whose content we can't really know from this code sample.

**Comment by xperiandri** [comment]
area is an area of union of drawingGeomerty (blue one) and rectangleGeometry (red one).

**Comment by shawnhar** [comment]
> area is an area of union of drawingGeomerty (blue one) and rectangleGeometry (red one).

Not quite.

rectangleGeometry is a rectangle that has been stroked with drawStrokeThickness.

The red thing in the screenshot is that already stroked geometry, stroked a second time using the different value masterStrokeThickness.   If you want to display the same thing you are computing area and union against, use FillGeometry here instead of DrawGeometry.

**Comment by clandrew** [comment]
The illustration seems to be mixing up draws (of different stroke thicknesses) and fills.

**Comment by xperiandri** [comment]
Let me explain what I want to achieve to be sure that you understand me right.
I want to do Union of what is filled red and what is filled blue on the screenshot and compute its area.
Then I want to compare that area to area of red only.
If the difference is very small (maybe less that 5% or 10%) I will assume that user drew a rectangle (blue one).

**Comment by shawnhar** [comment]
You should change your draw calls from DrawGeometry to FillGeometry, and then change your geometry calculations until the drawing appears the way you want.

At the moment you are only stroking the actual geometry with a narrow width, but then stroking it again with a much larger width only when drawing it to the screen.

**Comment by xperiandri** [comment]
Thank you very much for help with this.
I got a mistake here
```C#
rectangleGeometry = CanvasGeometry.CreateRectangle(device, rectangleRect).Stroke(drawStrokeThickness);
```
I did `Stroke()` with `drawStrokeThickness` instead of `masterStrokeThickness`.
And because I did DrawGeometry instead of FillGeometry with correct thickness I couldn't see this mistake.

**Comment by shawnhar** [comment]
Closing issue as this seems to be resolved now - feel free to reactivate if you have further questions.
