### ISSUE TITLE
OrangeRed color is out of range

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/Win2D#131]
```C#
args.DrawingSession.FillGeometry(circleGeometry, Colors.OrangeRed);
```
<img width="848" alt="orangered" src="https://cloud.githubusercontent.com/assets/2365592/9316334/1cddc7ca-453d-11e5-9a9a-da7e5b8e6e5b.png">

**Comment by xperiandri** [comment]
Or I don't understand the problem.

**Comment by shawnhar** [comment]
The color is fine, but your circleGeometry field is null.

**Comment by xperiandri** [comment]
Really, thanks! :)

**Comment by xperiandri** [comment]
I should have to check for null before drawing
