### ISSUE TITLE
Usable Clipping

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/Win2D#134]
I wonder that in [Windows 10 API](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.media.geometry.aspx) UIElement.Clip can still only be a RectangleGeometry!

After I saw this circle clipped photos of users in Windows 10 I immediately thought that finally this clipping functionality is available to developers but it is not.
It looks like a scorn.

OK, I can create an Ellipse and fill it with ImageBrush but what is the problem with Clip?

Maybe I don't understand some important performance trick, do I?

**Comment by shawnhar** [comment]
Win2D can clip its rendering to any CanvasGeometry.   Use the CanvasDrawingSession.CreateLayer API to do this.
