### ISSUE TITLE
Win2D C++ basic sample shows rendering error in design window

### ISSUE THREAD

**Issue by jeromebjerome** [Microsoft/Win2D#139]
Hello,
I am new to Win2D/Universal App and trying to run the basic Win2D sample using C++ Universal App. 
I followed the instructions given for the c# sample and adapted them to C++ programming. I could have the sample running but when in Design mode, there is an error message and the window is not rendered properly (see image below).
Any hint about what's wrong ?

![design](https://cloud.githubusercontent.com/assets/13735023/9460513/09c7e146-4b07-11e5-8b08-877224eca4de.png)

**Comment by damyanp** [comment]
This is a known issue with the XAML designer that will be fixed in a future update to VS2015.  It affects any C++ XAML project consuming native XAML controls via NuGet.

**Comment by shawnhar** [comment]
Note that this issue only prevents the XAML designer from rendering correctly when using Win2D controls from C++/CX - actually building your app still works fine.  You can ignore the designer error, and successfully create C++/CX apps that use Win2D.

**Comment by damyanp** [comment]
I'm seeing this as working now in the most recent update to VS2015.
