### ISSUE TITLE
CanvasControl based UserControl possible?

### ISSUE THREAD

**Issue by t-sch** [Microsoft/Win2D#142]
Hi Guys,

I'd like to ask if it is somehow possible to create a UserControl for Universal Apps that 'derives' from CanvasControl and adds an own API interface and implements some drawing like a proprietary mapping control?
As CanvasControl (and each other RTC class) is sealed, the easy way is not possible.
Any ideas?
Thomas

**Comment by damyanp** [comment]
In XAML you tend to create user controls by composing other controls.  So you'd derive from UserControl and add the CanvasControl to that.

There's an example of this in ExampleGallery.  See [GlowTextSampleControl.cs](https://github.com/Microsoft/Win2D-Samples/blob/master/ExampleGallery/Shared/GlowTextCustomControl.cs).  You can see it in action in the Custom Control Example.
