### ISSUE TITLE
CanvasCachedGeometry has a 512*1024 coordinate value maximum?

### ISSUE THREAD

**Issue by t-sch** [Microsoft/Win2D#143]
Hi,
after changing my drawing routines from CanvasGeometry to CanvasCachedGeometry, all polygons are clipped at a 524000 (512*1024) coordinate values boundary.

![win2d](https://cloud.githubusercontent.com/assets/8858830/9520420/65b61fa6-4cc7-11e5-82a3-03df48b77286.png)
(Please ignore the weird lines (issue #137) and the head-over texts)

Regards,
Thomas

**Comment by clandrew** [comment]
Could you provide a bit more information about how you draw the cached geometry? Do you use a transform? Any layers?

**Comment by clandrew** [comment]
Another update: I investigated this a bit more. This is a Direct2D issue/behavior.

Direct2D does a clip for the types of primitives that CanvasCachedGeometry uses, to around 524287 in drawing space (after transforms), when you create the cached geometry. 

I'm talking to the D2D folks as to whether they might change this behavior in the future.

It clips other types of primitives to this boundary, too, although not necessarily the ones that correspond to CanvasGeometry, hence your not seeing the clipping behavior before.

A workaround is to create your cached geometry at a smaller size, and then use a transform to scale it up.

**Comment by clandrew** [comment]
We will be following up with a documentation change to help explain this behavior, and the workaround.

**Comment by shawnhar** [comment]
This range limitation is now explained in the CanvasCachedGeometry documentation:

http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Geometry_CanvasCachedGeometry.htm
