### ISSUE TITLE
where is the pen class?

### ISSUE THREAD

**Issue by yuthle** [Microsoft/Win2D#144]
I can't apply a pen object with radial gradient brush style to draw direct line. when I using your CanvasRadialGradientBrush I need to calculate the center point every time. it's not convenience. 
Can you add a pen class to support that?

**Comment by shawnhar** [comment]
Can you explain more about what you would want such a class to do?   I'm not understanding the concept.

Thanks,

**Comment by yuthle** [comment]
I want the pen class that do like the following picture. 
![line with gradient brush](https://cloud.githubusercontent.com/assets/13954149/9550671/e3315cb0-4dd6-11e5-9aa0-b86845583852.png)

The pen class can have the attributes like width, color, radius, alpha value and so on.
thank you

**Comment by shawnhar** [comment]
You can draw lines of any width and color directly using the DrawLine API.

To soften the edges of the resulting shape, the easiest approach would be to draw your lines into a CanvasCommandList, then filter that command list through a GaussianBlurEffect.

**Comment by shawnhar** [comment]
I'm closing this issue as we do not plan to add a pen class to Win2D.

Please let us know if the suggestion of using a regular stroked line plus blur does not achieve your goal here.
