### ISSUE TITLE
What's the DirectXPixelFormat

### ISSUE THREAD

**Issue by dumbledad** [Microsoft/Win2D#147]
To use [CanvasBitmap.CreateFromBytes](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasBitmap_CreateFromBytes.htm) I need to  specify the pixel format of the bitmap in the byte array. What is the equivalent in [Microsoft.Graphics.Canvas.DirectX.DirectXPixelFormat](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_DirectX_DirectXPixelFormat.htm) to [System.Drawing.Imaging.PixelFormat](https://msdn.microsoft.com/en-us/library/system.drawing.imaging.pixelformat(v=vs.110).aspx).Format24bppRgb? The available ones seem to all be four-component.

**Comment by shawnhar** [comment]
You're right, Win2D does not support a packed 24 bit format  (the full set of available formats for each purpose is documented here: http://microsoft.github.io/Win2D/html/PixelFormats.htm)

This is for the simple reason that Win2D is a hardware accelerated API, and D3D GPU rendering does not support that sort of packed format.  You will need to expand your data to one of the 32 bits per pixel format, inserting additional alpha bytes.
