### ISSUE TITLE
Adding / removing NuGet Win2D.win81 package

### ISSUE THREAD

**Issue by dumbledad** [Microsoft/Win2D#148]
If I add or remove the NuGet Win2D.win81 package from my project using Visual Studio 2015's "Manage NuGet packages ..." then Visual Studio crashes. The add or remove is successful, as I can see when Visual Studio restarts. My version info is Visual Studio Enterprise 2015 14.0.23107.0 D14REL and OS build 10538

**Comment by shawnhar** [comment]
What project type(s) are you using?

I don't see this problem using ExampleGallery.81.sln (from the Win2D samples repository) with VS 2015.

**Comment by dumbledad** [comment]
Windows Phone 8.1 Universal. I'll zip it up and send it to you (other similar projects seem fine, so it's just something screwy about this one.)

**Comment by shawnhar** [comment]
This appears to be a NuGet rather than Win2D bug.  Reported here:  https://github.com/NuGet/Home/issues/1332
