### ISSUE TITLE
Bug?: CanvasVirtualControl in ScrollViewer

### ISSUE THREAD

**Issue by SebastianStehle** [Microsoft/Win2D#149]
Hi,
I was playing around with CanvasVirtualControl  in a scrollviewer. When I enable zooming and zoom out I see constant refreshs of the different bounds. I used the code from the sample gallery so I can see that the background colors change often.

**Comment by shawnhar** [comment]
Please share repro steps.  I don't see anything like this running the virtual control demo in Example Gallery: zooming in and out just scales the existing image without redrawing anything, and my colors only change when new regions come into view and need to be rendered.

**Comment by shawnhar** [comment]
Closing issue due to lack of repro steps.
