### ISSUE TITLE
Please add support for loading and displaying SVG images

### ISSUE THREAD

**Issue by Emasoft** [Microsoft/Win2D#15]
Please add support for loading and displaying SVG images. The majority of 2D graphic assets (sprites, background, ui, animations, etc.) of games are made with Inkscape and Illustrator in SVG. Porting those games from the other platforms (web, mobile, etc.) using Win2D would be a breeze with SVG support.

**Comment by GeekyMonkey** [comment]
As a game and web developer I agree that SVG rasterizing support would be hugely useful. It IS used in many high quality 2D games where camera zoom effects are used. It's also helpful when delivering your game to different screen sizes.  At startup the SVGs are rasterized based on the screen size, and during the game re-rasterization can happen when the camera zoom changes.  You always get perfectly antialiased sprites.
