### ISSUE TITLE
Freeze after waking up from sleep on Windows Store App

### ISSUE THREAD

**Issue by omanuke** [Microsoft/Win2D#152]
I'm using Win2d on Windows Store App.and use CanvasControl ,CanvasImageSource ,CanvasBitmap.
This app always freeze after waking up from sleep.
Some unhandled exception seems to happen. Logged message says "Objects used together must be created from the same factory instance" or "There has been a presentation error that may be recoverable.The caller needs to recreate,rerender the entire frame, and reattempt present.(HRESULT:0x8899000C) at Microsoft.Graphics.Canvas.CanvasBitmap.CreateFromBytes".

I have to do something after waking up from sleep?

**Comment by shawnhar** [comment]
You are probably hitting a device lost error.  Win2D CanvasControl will recreate the graphics device in response, and re-raise the CreateResources event.  You will get that exception if your app continues to use no-longer-valid resources from the original (now lost) graphics device after the new device has been created.

More info:  http://microsoft.github.io/Win2D/html/HandlingDeviceLost.htm

**Comment by omanuke** [comment]
I left some CachedGeometry after waking up from sleep.
I dispose them on CreateResources,it works fine now! 
Thx for ur help!
