### ISSUE TITLE
rendering RichText

### ISSUE THREAD

**Issue by omanuke** [Microsoft/Win2D#155]
I may be wrong ,but current Win2d has no feature to render rich text like mixed font and color and some style like underline or strike and so on, right?.
If it's so, I wanna such features.
Now I'm using RichEditBox to render such rich text and convert to bitmap as cache, but to make bitmap for lots of text ,little bit costly...

**Comment by shawnhar** [comment]
This is exactly what the CanvasTextLayout class is for.

**Comment by omanuke** [comment]
I got it. It works fine.
From documentation or samples ,I couldn't find information about What CanvasTextLayout does.
Thxs.
