### ISSUE TITLE
Can Win2D be used with traditional resizable desktop windows in Windows 10?

### ISSUE THREAD

**Issue by bdpy** [Microsoft/Win2D#156]
Sorry for maybe silly question, but the main reason for me not to use Win2D was the fact that it run on Windows Runtime which was used only with fullscreen applications in Windows 8.1. But in Windows 10 there is UWP which again allows to use resizable windows for desktop applications. So can Win2D be used with those new UWP resizable windows for desktop?

**Comment by damyanp** [comment]
Yes, Win2D can be used for writing UWP applications in Windows 10.
