### ISSUE TITLE
Referencing Win2D from a library

### ISSUE THREAD

**Issue by pcyanide** [Microsoft/Win2D#157]
I wonder why Win2D is installed inside the project, rather than as a stand-alone package, making it possible to keep a single copy of Win2D rather than replicating it for each solution?

And another issue related to that. I want to create a common library based on Win2D as a separate project in the solution. The trouble is that I cannot add a reverence to Win2D from there. The Nuget package Manager does not lists the  library, and adding a reference  manually also fails. Is there a way to do that?

**Comment by shawnhar** [comment]
Win2D uses NuGet for packaging (we didn't try to invent our own packaging system from scratch!) so the install behavior is the same as how all NuGet packages work.   Prior to v3, NuGet packages were installed locally.  In NuGet v3  (which is used by VS2015 when building UWP projects) the packages are installed in a per-machine user folder.

Second question (btw: it's usually easier if you open a separate issue if you have more than one unrelated question!)

What type of Visual Studio project are you using for this library?  My first guess is it's probably something other than a Windows Runtime compatible project type...

**Comment by shawnhar** [comment]
Closing issue as I believe the question is addressed - please let us know if you hae further questions.
