### ISSUE TITLE
Referencing Win2D in a WPF application

### ISSUE THREAD

**Issue by Orangeyness** [Microsoft/Win2D#158]
I have an existing WPF application and I was hoping to use Win2D to improve rendering performance. However I get the following error when trying to install the Win2D.win81 Nuget package

>  Could not install package 'Win2D.win81 1.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework.

Is Win2D only usable from WinRT applications and incompatible with WPF?
(I am pretty unfamiliar with WinRT)

**Comment by shawnhar** [comment]
Win2D is a WinRT API, so can only be used by WinRT applications. That includes store apps for Windows 8.1, Windows Phone 8.1, and the new Windows 10 Universal Windows Platform.

You cannot use WinRT APIs from other environments such as classic Win32 desktop.
