### ISSUE TITLE
Support for spritesheets

### ISSUE THREAD

**Issue by Postlagerkarte** [Microsoft/Win2D#16]
What are your plans concerning spritesheets? I could not see anything in the backlog related to it.

**Comment by Odonno** [comment]
Really great !

Is there a plan to improve the documentation ? Like how to implement / bootstrap some type of projects : 

* 2D game (with spritesheets)
* specific effects (blur and more)
* 3D rendering
* etc..

**Comment by shawnhar** [comment]
We're always interested in feedback on how to improve the Win2D docs (the more detailed, the better!) but have to balance that against working on the API itself.

I'm not sure we'd ever want to build a full game example - that would be very time consuming to get right and is probably out of scope.

For blur effects, see the Quick Start in the Win2D docs, plus the effects demo in Example Gallery for a more complete set of how to use all the different effects.

3D rendering isn't a feature of Win2D so I'm not sure what we'd have to document there?  Example Gallery shows how to interop between Win2D and D3D, using D3D for 3D rendering.

**Comment by Odonno** [comment]
I clearly understand, I know it's very difficult to do two things at a time (code + doc). Currently, the doc looks great as a MSDN doc, to retrieve information on class, etc... 

But, I think it could be better if we had dedicated page of specific code like it is on menu page. Not a lot of code, but the minimal code that matters with good explanation (like you can see on the getbootstrap.com website for example). For sure, that's not a critical task and Win2D is young, it is only my own opinion for further versions.

Oh, I only see the Quickstart page just now, it's clearly what I had in mind.

I never told about a full game example. And you're right, it is useless. And if you're interested, I am currently making a game with Win2D hosted on GitHub, and it's amazing. You're doing a great job !

**Comment by shawnhar** [comment]
Win2D 1.10.0 added a CanvasSpriteBatch API, and Example Gallery shows how to implement sprite sheets using this: https://github.com/Microsoft/Win2D-Samples/tree/master/ExampleGallery/UAP/SpriteSheets
