### ISSUE TITLE
Poor performance at 4K

### ISSUE THREAD

**Issue by JohannesMoersch** [Microsoft/Win2D#162]
On my UHD monitor, I am getting really poor performance. I created a small app to test this, and simply drawing one image that is rotating stutters like crazy. If I draw it with Win2D without moving it and then use a storyboard and rotate transform to spin the entire canvas, the animation is totally smooth.

This is the only content in my XAML file (I also tried without IsFixedTimeStep="False"):
```xaml
<canvas:CanvasAnimatedControl IsFixedTimeStep="False" Draw="CanvasAnimatedControl_Draw" CreateResources="CanvasAnimatedControl_CreateResources" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" />
```
And this is my code behind:
```csharp
float _time;
CanvasBitmap _bitmap;
Transform2DEffect _transform;

private void CanvasAnimatedControl_CreateResources(Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
{
	args.TrackAsyncAction(Load(sender).AsAsyncAction());
}

private async Task Load(ICanvasResourceCreator canvas)
{
	_bitmap = await CanvasBitmap.LoadAsync(canvas, "Assets/TestImage.jpg");
	_transform = new Transform2DEffect() { Source = _bitmap };
}

private void CanvasAnimatedControl_Draw(Microsoft.Graphics.Canvas.UI.Xaml.ICanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedDrawEventArgs args)
{
	System.Diagnostics.Debug.WriteLine((1.0 / args.Timing.ElapsedTime.TotalSeconds).ToString("0.00 FPS"));
	float size = 1.0f;
	_transform.TransformMatrix = Matrix3x2.CreateTranslation(-_bitmap.SizeInPixels.Width * 0.5f, -_bitmap.SizeInPixels.Height * 0.5f) * Matrix3x2.CreateRotation((float)args.Timing.TotalTime.TotalSeconds * 4.0f) * Matrix3x2.CreateScale(1.0f / size) * Matrix3x2.CreateTranslation(_bitmap.SizeInPixels.Width * 0.5f, _bitmap.SizeInPixels.Height * 0.5f);
	args.DrawingSession.DrawImage(_transform, new Rect(new Point(-sender.Size.Width * (size - 1.0f) * 0.5f, -sender.Size.Height * (size - 1.0f) * 0.5f), new Size(sender.Size.Width * size, sender.Size.Height * size)), new Rect(new Point(0, 0), _bitmap.Size));
}
```

The size variable changes the size of the target region while maintaining the screen size of the image. Interestingly, a target region that is much larger than the screen runs better than one that is the same or smaller than the screen.

After changing IsFixedTimeStep to false, the frame times reported by the draw event args put my framerate as low as 10-15FPS with a small target region (and that feels somewhat optimistic). The image I am using is 3840x2160. 

Any idea what is going on?

Thanks

**Comment by shawnhar** [comment]
What GPU are you running this on?  This sounds to me like you are simply running into the limits of what your HW can handle - in particular that fact that changing scale factor affects perf makes me think you are saturating HW memory bandwidth such that more cache friendly workload runs faster.

First thing to try is just set the transform on your drawing session rather than using a transform image effect.  There's no need to be using effects if all you want to do is move a bitmap around - keeping this to a simple bitmap copy operation should run much faster.

**Comment by JohannesMoersch** [comment]
I'm doing my development and testing on a Thinpad W540. My UHD monitor is connected to a digital port controlled by the Nvidia Quadro K1100M. I've posted a snapshot from GPU-Z below showing both GPUs. In this case, the Intel is doing the rendering. Switching over to the Nvidia (which I confirmed worked by looking at the GPU usage in the chart) did improve performance, but it still wasn't smooth. Also, for the bit I mentioned about the scaling factor, larger was faster, and at some threshold of smaller, it got sluggish. However, after a reboot I have been unable to reproduce this particular effect.
![gpuz](https://cloud.githubusercontent.com/assets/4315756/10104944/88344dec-6369-11e5-8ccf-7e66eefc54f5.jpg)
I tried what you mentioned about using the transform on the drawing session, but even then (while using the Nvidia Quadro), the framerate would dip a lot at 4K. Based on the elapsed time reported by Win2D, at 1080p I would get 60FPS, but at 4K I would get 20-30FPS (with the occasional 60FPS time reported). Regardless, transforming the drawing session isn't really an option because for my actual development work, I will do doing more complex effects. The moving bitmap was just to test performance.

**Comment by shawnhar** [comment]
This looks to me like you're just doing too much work at too high a resolution for the GPU to keep up with.

One option to consider is using the DpiScale property to rasterize at something lower than the full resolution of your output display.  We added that mostly for lower powered phone devices, but the same scaling ability could be useful at the other end of the spectrum for more capable HW driving high resolution displays.


> for the bit I mentioned about the scaling factor, larger was faster, and at some threshold of smaller, it got sluggish

That's what I'd expect if you were memory bound and thrashing the GPU texture cache.

**Comment by JohannesMoersch** [comment]
I've done some additional testing, and I think there is more to it than that. I tried rotating 10 copies of the image (at Opacity="0.1") using render transforms and it was totally smooth both at 4K and at 1080p. Then I tried rotating 10 copies of the image in Win2D (I tried both 1 transform effect with 10 different matrices and draw calls, and 10 transform effects each drawn once per frame), and even at way less than 1080p, the performance was awful (well under 10FPS). Then I tried changing the image I was drawing from one at 3840x2160 to a really low resolution image and suddenly there were no performance issues. The size of the source image did not seem to have a significant effect on the performance using render transforms.

**Comment by shawnhar** [comment]
This isn't an apples-to-apples comparison because your Win2D rendering is using image effects rather than a straightforward textured quad.

**Comment by JohannesMoersch** [comment]
What is actually going on behind the scenes? Does every effect draw to a rendertarget which is then the input into the next effect (or the draw image call)? If so, then I understand why this is slow. Will it ever be possible in Win2D to write a custom shader and just draw straight from the source image onto a quad (or maybe even a custom mesh)? If not, do you have any guidance on how to accomplish this within a universal app? I would be perfectly happy writing my own vertex and pixel shaders (and generating my own meshes).

**Comment by shawnhar** [comment]
In Windows 8.1, effects always operated on intermediate rendertargets.  In Win10, shader linking allows many intermediates to be flattened which can give a dramatic performance boost, but this isn't always possible - it depends on the details of the effect graph being used.

We are planning on adding custom effects to Win2D, which will allow using your own pixel shaders but only within the existing effect system.  To go beyond that, you can always interop down to the D3D level.

**Comment by JohannesMoersch** [comment]
Oh, cool! Any chance of drawing on a custom mesh as well (so I can create transition effects where a screen disintegrates, for instance)? 

Did you see my edit up above: "Also, even just drawing the bitmap directly with no image effects in between is slow (based on the reported elapsed time). Shouldn't this operation be akin to drawing a textured quad?"

**Comment by shawnhar** [comment]
> Any chance of drawing on a custom mesh as well 

That's not part of our current roadmap.  Underlying D2D image effects do support custom vertex shaders, but these are complex to use correctly (in particular declaring the input <-> output rect mappings that the effect system requires can be incredibly tricky) so my feeling is this probably isn't something we can successfully make any easier to use in Win2D.

You can do this in native D2D, or native D3D for that matter.  Or, depending on complexity of the mesh, splitting pieces of it across multiple Win2D draw calls might work ok.


> Also, even just drawing the bitmap directly with no image effects in between is slow (based on the reported elapsed time). Shouldn't this operation be akin to drawing a textured quad?

It is approximately the same, but there is an extra full copy of the image involved when you draw to a swapchain.

RenderTransform path:

- Image is already drawn into the output CanvasSwapChain or CanvasImageSource
- XAML compositor picks this up and draws it to the final location as a textured quad
- total: 1 copy

DrawImage path:

- Win2D clears the output surface
- Win2D draws the rotated image to the output surface
- XAML compositor picks this up and merges the final Win2D content into its scene
- total: 1 clear + 2 copies

On phones and tablets, that final composition cost can usually be avoided by using hardware overlay planes (which happens automatically in the compositor wherever possible), but this optimization is not available on desktop GPU HW like you are using.

**Comment by JohannesMoersch** [comment]
Kay, thanks for the info. Does it make sense that if I use both render transforms and Win2D at the same time, the render transforms continue to perform well, even when the contents of the Win2D canvas are stuttering? Maybe the solution for me is to use the two in combinations (render transforms for all transforms, and Win2D for effects like hue/brightness changes and blur and stuff).

**Comment by shawnhar** [comment]
Closing issue as we don't see any reason for Win2D changes here.
