### ISSUE TITLE
[Win2D - Sample] Crash on Resume in VirtualControlExample

### ISSUE THREAD

**Issue by Datoh** [Microsoft/Win2D#163]
Hi,

On last Win2D Sample [c34472c1e7e91b44b5799a0ed0f90608c9c0c006].
I open Virtual Control sample.
In Visual Studio, I trigger a Suspend event (using Debug Location toolbar), then a Resume Event.
Then, I have a crash in VirtualControlExample.xaml.cs [line 83] :
`using (var session = sender.CreateDrawingSession(region))`

Regards,
Datoh.

**Comment by damyanp** [comment]
Hi Datoh,

Thanks for reporting this issue.  Unfortunately, I've not been able to reproduce this on my machine yet.

Can you let me know:

* which sln file you're using
* which version of Visual Studio you're using
* which version of Windows (or Windows Phone) you're running
* which configuration (debug / release)
* which platform (Win32, Win64 etc.)
* any other information that might help me reproduce this

Thank you!

**Comment by Datoh** [comment]
HI,

* ExempleGallery.81.sln
* Visual Studio 2013 Community Edition or Visual studio 2015 Entreprise
* Windows 10 Professional
* Debug / x64 / ExampleGallery.Windows (Windows 8.1)

Regards,
Cédric.

**Comment by damyanp** [comment]
I'm afraid we must still be missing a step here.

Here's what I'm doing (VS 2015, x64, ExampleGallery.Windows (Windows 8.1):

* F5 to start app with debugger attached
* select "Virtual Control" example
* click back on Visual Studio
* select "Suspend" from Lifecycle Events
* Wait a few seconds
* select "Resume" from Lifecycle Events
* Example Gallery automatically comes back to the foreground, still showing the Virtual Control example
* I can click and pan around the example with no problems

Does this match what you are doing?

**Comment by Datoh** [comment]
Here is an animated gif of the scenario
![crash_win2d](https://cloud.githubusercontent.com/assets/2086938/10149375/89e0844e-6639-11e5-94be-10c2919d0a24.gif)

**Comment by shawnhar** [comment]
From the exception callstack, you are hitting a device lost immediate after resume.

What HW and what OS build is this on?

Like Damyan, I also cannot reproduce this on either of my two machines.

**Comment by damyanp** [comment]
If you press F5 to continue after this happens, does it recover?

Alternatively, if you uncheck the "Break when this exception type is user-unhandled" box and then continue running does it still repro?

**Comment by Datoh** [comment]
Hi,

damyanp are rigth, It's just a managed exception.

Sorry to waste your time and great job!

Cédric.

**Comment by damyanp** [comment]
No worries.  This shows that the lost-device recovery feature of CanvasVirtualControl is working.  The lost device exception bubbles up through your event handler and is then caught by CanvasVirtualControl where it recreates the device, triggers resource recreation and then redraws the control.
