### ISSUE TITLE
Crash when 3D transform is behind camera

### ISSUE THREAD

**Issue by JohannesMoersch** [Microsoft/Win2D#164]
If the result of any 3D transform involving a CreatePerspective call that places part or all of the image I am drawing behind the camera, I get this exception:

The graph could not be rendered with the context's current tiling settings. (Exception from HRESULT: 0x88990027)

For instance, if I try to call draw image on a 3D transform that has this matrix: 
Matrix4x4.CreatePerspective(0.001333f, 0.001333f, 1.0f, 1500.0f)
It will immediately crash. If I add a translate before the create perspective that moves to any negative value on Z, no problem. Then, after doing this transform, if I add a rotate before the translate that rotates the image towards the camera until the top is behind the camera, it will crash with this same exception.

Any idea what's up?

**Comment by damyanp** [comment]
Hi - I'm having some trouble reproducing this issue.  Can you share some code that demonstrates the problem please?

Thanks.

**Comment by JohannesMoersch** [comment]
Sorry for the delayed response. The following produces the error for me. This is a Windows 10 Universal Application.

MainPage.xaml
```xaml
<Page x:Class="TestUniversalApp.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:canvas="using:Microsoft.Graphics.Canvas.UI.Xaml">

	<canvas:CanvasAnimatedControl Draw="CanvasAnimatedControl_Draw" CreateResources="CanvasAnimatedControl_CreateResources" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" />

</Page>
```

MainPage.xaml.cs
```C#
using System;
using System.Numerics;
using System.Threading.Tasks;
using Microsoft.Graphics.Canvas;
using Microsoft.Graphics.Canvas.Effects;
using Windows.Foundation;
using Windows.UI.Xaml.Controls;

namespace TestUniversalApp
{
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            InitializeComponent();
        }

		CanvasBitmap _bitmap;
		Transform3DEffect _transform;

		private void CanvasAnimatedControl_CreateResources(Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
		{
            args.TrackAsyncAction(Load(sender).AsAsyncAction());
		}

		private async Task Load(ICanvasResourceCreator canvas)
		{
			_bitmap = await CanvasBitmap.LoadAsync(canvas, "Assets/TestImage.jpg");
			_transform = new Transform3DEffect() { Source = _bitmap };
		}

		private void CanvasAnimatedControl_Draw(Microsoft.Graphics.Canvas.UI.Xaml.ICanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedDrawEventArgs args)
		{
			_transform.TransformMatrix = Matrix4x4.CreatePerspective(0.001333f, 0.001333f, 1.0f, 1500.0f);
            args.DrawingSession.DrawImage(_transform, new Rect(new Point(0, 0), sender.Size), new Rect(new Point(0, 0), _bitmap.Size));
        }
	}
}

```

**Comment by damyanp** [comment]
Can you share TestImage.jpg (or maybe just the size of this image)  As it is, I'm not seeing a repro.

Can you tell me some more about what machine you are seeing this on?  PC or mobile?

**Comment by JohannesMoersch** [comment]
Image size seems to contribute because a smaller image did not cause the problem. TestImage.jpg is 3840x2160 and I'm testing this on a Thinkpad W540 with an Nvidia Quadro K1100M. Changing the preferred graphics processor in the nvidia drivers doesn't fix the issue (and earlier testing indicated that this option actually does change which processor is doing the rendering - I watched GPU-Z load graphs to check this).

**Comment by damyanp** [comment]
Still not luck reproducing this I'm afraid.  Would you be able to share a complete project that reproduces this please?  Thanks!

**Comment by damyanp** [comment]
Ah! I thought I'd try one last thing before moving on.  The missing piece here is that the display needs to be set to high DPI.  So I can now repro if I set the scaling to 125%.  I've enough to start digging more on our end.  Thanks!

**Comment by JohannesMoersch** [comment]
Awesome! Didn't think to mention DPI. I have my displays at 150%.

**Comment by damyanp** [comment]
This is an issue on the platform when the 3D transform causes the image to be clipped by the near plane.

As this fix for this will be done in the OS (rather than in Win2D) I'm going to close this issue.  

In the meantime, I'm afraid the best advice here is to take steps in your app to avoid this situation arising.

Thanks for bringing this to our attention!

**Comment by 13thsymphony** [comment]
For a little more detail, this issue gets hit when two conditions are true:
1. Near plane clipping as a result of your 3D transform
2. Direct2D internally attempting to render to a very large intermediate texture (i.e. larger than the Direct3D maximum texture size, which for Windows 10 is generally at least 4096*4096)

#2 is an internal implementation detail, so it's hard to guarantee that it won't be hit. You can mitigate by using smaller inputs (i.e. your 4K image) or by ensuring that the output of any specific effect, such as the 3D transform, would not result in a rendered image that is greater than 4096*4096.

The OS platform team is investigating this bug for resolution in a future release of Windows.
