### ISSUE TITLE
Windows Store certifications kit error - The Direct3D Trim after Suspend test (or how to call "IDXGIDevice3::Trim" in C# app?)

### ISSUE THREAD

**Issue by sevenate** [Microsoft/Win2D#165]
When I run certification kit test tool for universal windows app that use Win2D - one of the Direct3D tests fails:

### Direct3D Feature Test

**PASSED**  Direct3D feature level support
**FAILED**    Direct3D trim after suspend

* Error Found: The Direct3D Trim after Suspend test detected the following errors:
* Impact if not fixed:  If the app does not call Trim on its Direct3D device, the app will not release memory allocated for its earlier 3D work. This increases the risk of apps being terminated due to system memory pressure. 
* How to fix: The app should call the Trim API on its IDXGIDevice3 interface anytime it is about to be suspended.

[More Information](http://go.microsoft.com/fwlink/?LinkId=294561)

----

I've [found some tips ](https://social.msdn.microsoft.com/Forums/en-US/a6301dba-5af8-41ee-9e46-9f914e5c6b19/direct3d-trim-after-suspend-windows-certifications-kit-error-how-do-i-call-trim-if-using-c?forum=winappswithcsharp) about how this requirement could be satisfied using C++ component, but would rather prefer to have everything in C#. I've searched in the [documentation](http://microsoft.github.io/Win2D/html/Introduction.htm) but, didn't managed to find the exact recommendation about calling the Trim(), so I've dig into the Win2D source code a bit and what I've come up so far was the following, which I've added to App.xaml.cs/OnSuspending() handler:

```
CanvasDevice canvasDevice = CanvasDevice.GetSharedDevice();
canvasDevice.Trim();
```

Although it's not crashing in the debug since the returned shared CanvasDevice is not null and the Trip() call seems executes without any exceptions - the certification test still failing with the same error, so apparently IDXGIDevice3::Trim was not called properly under the hood.

So here comes the question - what is the proper way to make the call to IDXGIDevice3::Trim in the OnSuspending() handler?

**Comment by shawnhar** [comment]
The Win2D controls (CanvasControl, CanvasAnimatedControl, and CanvasVirtualControl) automatically handle this requirement, calling Trim on their devices when the app is suspended.

I think your app must be using some other device that you created yourself rather than through one of these controls?

**Comment by sevenate** [comment]
That's exactly how I expected it should be. There is only one CanvasAnimatedControl on single XAML page, and this page  implement recommended "cleaning" procedure in OnUnloaded() handler (I've checked the console for output from page's finalizer as [recommended](http://microsoft.github.io/Win2D/html/RefCycles.htm)):

```
canvas.RemoveFromVisualTree();
canvas = null;
```

The thing is that page is not the default one which will be opened when the app is started, so I guess when the certification test tool launch the app to check that "Direct3D trim after suspend" test - it never switch to this page and the CanvasAnimatedControl will be never be created and, thus, the "Trim" method will never be called.

**Comment by shawnhar** [comment]
The certification tool looks at all the active devices in the process, and makes sure that Trim was called on each one.  If your page isn't loaded yet, any devices that it creates when loaded will not be included in that check.

You don't need to hook Suspending at all when using Canvas*Control, as these will do it for you.

Your app must include some other D3D device that is created by your startup code or initial page.  Perhaps some other use of Win2D, or some non-Win2D component that also creates a D3D device?

**Comment by sevenate** [comment]
OK, it seems like this issue is not related with Win2D since it is not reproduced with another sample project that use Win2D in a similar way. Sorry for misleading.
