### ISSUE TITLE
PrintTaskOptionsChanged event is not fired for custom options

### ISSUE THREAD

**Issue by RobMc1964** [Microsoft/Win2D#166]
Using the snippet below from your samples if you create a custom option the PrintDocument_PrintTaskOptionsChanged method is never.  Instead it is only called when an OOTB option is changed.

thanks,

rob     

private void PrintingExample_PrintTaskRequested(PrintManager sender, PrintTaskRequestedEventArgs args)
        {
            var printTask = args.Request.CreatePrintTask("Win2D Printing Example", (createPrintTaskArgs) =>
            {
                createPrintTaskArgs.SetSource(printDocument);
            });

            var detailedOptions = PrintTaskOptionDetails.GetFromPrintTaskOptions(printTask.Options);
            var pageRange = detailedOptions.CreateItemListOption("PageRange", "Page Range");
            pageRange.AddItem("PrintAll", "Print All");
            pageRange.AddItem("PrintFirstPage", "Print Only First Page");

            var displayedOptions = printTask.Options.DisplayedOptions;
            displayedOptions.Clear();

            displayedOptions.Add(StandardPrintTaskOptions.MediaSize);
            displayedOptions.Add(StandardPrintTaskOptions.Orientation);
            displayedOptions.Add("PageRange");
        }

        private async void PrintDocument_PrintTaskOptionsChanged(CanvasPrintDocument sender, CanvasPrintTaskOptionsChangedEventArgs args)
        {
            var deferral = args.GetDeferral();

        }

**Comment by damyanp** [comment]
This is expected - custom options are added through [PrintTaskOptionDetails](https://msdn.microsoft.com/en-us/library/windows/apps/windows.graphics.printing.optiondetails.printtaskoptiondetails.aspx) which has its own [OptionChanged](https://msdn.microsoft.com/en-us/library/windows/apps/windows.graphics.printing.optiondetails.printtaskoptiondetails.optionchanged.aspx) event for reporting when these options have changed.

Much of the interaction with print options etc. is a part of the Windows platform, so much of the information on MSDN's [Print from your app](https://msdn.microsoft.com/en-us/library/windows/apps/mt204545.aspx) pages is relevant to Win2D.
