### ISSUE TITLE
How do given PrintMediaSize to physical paper size?

### ISSUE THREAD

**Issue by RobMc1964** [Microsoft/Win2D#167]
I have a PrintMediaSize object in the preview event for printing.  I want to get to physical page size so for example PrintMediaSize is NorthAmericaLetter.  So how to get that down to 8.5"x11" which is the PaperSize?

thanks,

rob

**Comment by damyanp** [comment]
You can get the page size from the PrintTaskOptions via [GetPageDescription](https://msdn.microsoft.com/en-us/library/windows/apps/windows.graphics.printing.printtaskoptions.getpagedescription.aspx).  

This gives you a [PrintPageDescription](https://msdn.microsoft.com/en-us/library/windows/apps/windows.graphics.printing.printpagedescription.aspx) that has a PageSize field.  The size is in DIPS.  Note also that you can use the ImageableRect field to determine the region that the printer is able to actually print to.

See for example https://github.com/Microsoft/Win2D-Samples/blob/master/ExampleGallery/Shared/PrintingExample.xaml.cs#L135

**Comment by RobMc1964** [comment]
Here is my Preview method...

        private void Preview(CanvasPrintDocument sender, CanvasPreviewEventArgs args)
        {
            var ds = args.DrawingSession;
            var pageNumber = args.PageNumber;
            var dpi = args.PrintTaskOptions.GetPageDescription(args.PageNumber).DpiX;

            var paperSize = args.PrintTaskOptions.GetPageDescription(args.PageNumber).PageSize;
            var a1e = args.PrintTaskOptions.GetPageDescription(args.PageNumber).DpiX;
            var a2e = args.PrintTaskOptions.GetPageDescription(args.PageNumber).DpiY;

            var mediaSize = args.PrintTaskOptions.MediaSize;

            Debug.WriteLine("paperSize=" + paperSize.Width + "," + paperSize.Height);
            Debug.WriteLine("DpiX=" + a1e);
            Debug.WriteLine("DpiY=" + a2e);
            Debug.WriteLine("mediaSize=" + mediaSize);

            var detailedOptions = PrintTaskOptionDetails.GetFromPrintTaskOptions(args.PrintTaskOptions);
            var printColor = detailedOptions.Options["DrawingPrintColor.KEY"].Value.ToString();
            var printScale = detailedOptions.Options["DrawingPrintScale.KEY"].Value.ToString();

            _renderer.RenderPage(_viewModel, sender, ds, pageNumber, mediaSize, paperSize, printColor, printScale);
        }

and here is the output...

paperSize=1056,816.000061035156
DpiX=600
DpiY=600
mediaSize=NorthAmericaLetter

The problem is the northamericaletter is 8.5x11 in size.   Getting paperSize is 1056x816 yet DPI =600.0 which means this paper would be 1.76"x1.36" which is clearly not correct.

So my question is I know the mediasize is NorthAmericaLetter and I need the physical size of the paper ( which is 8.5x11 ).  Is there a way to do this or do I have to build my own mapping because clearly using dpi and dividing by papersize isn't correct?

thanks for your help in advance.

regards,

rob

**Comment by damyanp** [comment]
PaperSize is in DIPS, so it'll return the same value independently of the DPI.  [This page](http://microsoft.github.io/Win2D/html/DPI.htm) has some more information about DIPS and DPI.

When targeting something that has real physical size associated to it (like a printer) then 96 DIPS = 1 inch.  So 1056 / 96 = 11" and 816 / 96 = 8.5".

**Comment by GrahamDWardle** [comment]
Hi this getting the Paper Size at Preview time.
But is there a way to get the Paper Size information before the print is started?

**Comment by damyanp** [comment]
I don't believe there is.  Note that the paper size is chosen from the print dialog, which is displayed after ShowPrintUIAsync() is called, so I'm not sure what it would mean to get the paper size information before that.

**Comment by GrahamDWardle** [comment]
The reason for wanting to know what paper size has been set is that I wish to generate a print that has exact pixel positions for the print out so that shrinking to fit does not work.  If there was someway to generate the image at print preview but I had based my code on coloringbook sample, where the image is created then printed by shrink.
