### ISSUE TITLE
Release build crashes, but works fine in a debug build. 

### ISSUE THREAD

**Issue by axorth** [Microsoft/Win2D#172]
I was able to narrow it down to the adding of the canvas control 
canvas:CanvasControl x:Name="gridCanvas"  Grid.Row="1" Grid.Column="0" 

When that one line is added, a release mode build crashes with the attached exception.

![2015-10-04_14-43-10](https://cloud.githubusercontent.com/assets/12735890/10269819/a2e5aeee-6aa6-11e5-819e-4b3e37765d76.png)

**Comment by axorth** [comment]
Sorry, I mean to add I am using the UWP version

**Comment by shawnhar** [comment]
SimpleSample works for me, so we will need more details:

- What version of Win2D/SimpleSample?
- What version of Windows?
- What version of Visual Studio?
- Can you repro this literally just running SimpleSample.uap.sln from the Win2D samples repository, or are more steps involved?

**Comment by axorth** [comment]
Thanks for the reply:
I pulled the latest version of SimpleSample down from git today, it appears to be on the latest 1.5 release. On my own app, I pulled the latest copy of Win2d from nuget today as well. To reproduce this, I opened the SimpleSample.uap solution in Visual Studio 2015. I changed the build to Release x64 and ran the application. It succeeded in rendering some graphics and then crashed. My own solution did not even get to the constructor of the App. 

I am using Windows 10 Professional with all of the latest updates, and the system is otherwise completely stable.

Not sure if this helps, but I changed the debug mode to capture native and this is the stack trace.

![2015-10-04_21-29-31](https://cloud.githubusercontent.com/assets/12735890/10272039/41681ea2-6adf-11e5-9b14-7c440009b6c4.png)

**Comment by axorth** [comment]
Here is the exception from SimpleSample which I assume is the same error I am facing in my app.

![2015-10-04_21-28-25](https://cloud.githubusercontent.com/assets/12735890/10272083/c78e305c-6adf-11e5-8f27-29fa9ded4c76.png)

**Comment by axorth** [comment]
------------------
System Information
------------------
      Time of this report: 10/4/2015, 21:35:50
             Machine name: MARCIE
         Operating System: Windows 10 Pro 64-bit (10.0, Build 10240) (10240.th1.150916-2039)
                 Language: English (Regional Setting: English)
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: Z87X-HD3
                     BIOS: BIOS Date: 08/25/14 15:46:14 Ver: 04.06.05
                Processor: Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 CPUs), ~3.1GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16270MB RAM
                Page File: 9226MB used, 23427MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: 12
      DX Setup Parameters: Not found
         User DPI Setting: 120 DPI (125 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.10240.16384 64bit Unicode

**Comment by shawnhar** [comment]
This is very strange - I don't see this failure on any of my machines.  Not sure what we can do about this without some way to repro the crash...

![untitled](https://cloud.githubusercontent.com/assets/8118468/10283329/00a80daa-6b34-11e5-8d7d-b031c3d48d24.png)

**Comment by damyanp** [comment]
It would also help to confirm the exact version of Visual Studio and the "Visual Studio Tools for Universal Windows Apps" version.

You can find these in the Help->About menu.  eg:
![image](https://cloud.githubusercontent.com/assets/8118402/10288295/d3a15e38-6b4c-11e5-84d5-988e8b075566.png)

**Comment by axorth** [comment]
Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA698
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-80000-00000-AA698
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA698
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA698
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-80000-00000-AA698
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   14.0.20711.0
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GhostDoc   4.9.15086.0
GhostDoc automatically generates XML documentation comments.

JetBrains ReSharper Ultimate 2015.1.3   Build 102.0.20150724.141603
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2015 JetBrains, Inc.

Microsoft Azure HDInsight HQL Service   2.0.2200.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2200.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30713.1601

Microsoft Code Digger   0.9
Microsoft Code Digger

Microsoft.Pex.VisualStudio   1.0
Pex

NCrunch   
Continuous Testing Tool for .NET
Copyright © 2010-2015 Remco Software Ltd

NuGet Package Manager   3.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

Visual Studio Tools for Universal Windows Apps   14.0.23121.00 D14OOB
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Xamarin   3.11.1443.0 (39031d3)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   5.1.6.7 (58099c5358da3488b0e7fb0bb4af47aca7cc61d6)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.Forms Intellisense   1.0
Provides intellisense for Xamarin.Forms in the XML editor.

Xamarin.iOS   9.0.1.0 (7eaf3bc2053ad0d4f720422bb3dc13504d61f7b5)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS Unified Migration   1.0
Automated migration for Xamarin iOS Classic projects to Unified

Xamarin.TestCloud.Integration   1.0
Early preview of Xamarin Test Cloud integration

**Comment by yuthle** [comment]
I have this problem also with windows.ui.xaml on windows 10.
I just only have  STOWED_EXCEPTION_88000fa8_Windows.UI.Xaml.dll error message.

**Comment by shawnhar** [comment]
I'm not sure what to suggest next.  I'm running the same version of Visual Studio and the Visual Studio Tools for Universal Windows Apps, but do not see any crashes like this.

**Comment by axorth** [comment]
I was able to compile it and run it on a different machine. I wonder if the issue is perhaps related to Xamarin.

**Comment by shawnhar** [comment]
I'm going to close this out due to lack of any way to repro, and since it seems to occur only on a single machine.

Please reactivate if anyone is able to figure out a way we can repro this crash, or if it is observed on any other machines.
