### ISSUE TITLE
"Access is denied" while loading resource

### ISSUE THREAD

**Issue by CosmicBoris** [Microsoft/Win2D#173]
Hello, getting exception Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)
when colling:
private async Task LoadResourcesAsync(CanvasControl sender)
        {
            try{
                image = await CanvasBitmap.LoadAsync(sender, "X:\\frame.jpg");
            }
            catch (Exception ex){ 
                throw new Exception(ex.Message);
            }
        }

Project x86 
Archive on OneDrive http://1drv.ms/1L4LfDf
![img](https://cloud.githubusercontent.com/assets/14877609/10410812/74d43102-6f55-11e5-972e-2face0f519fc.jpg)
Running  on Windows 10 10240
Microsoft Visual Studio Community 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA083
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA083
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA083
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA083
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   14.0.20626.0
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   3.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual Studio Tools for Unity   2.1.0.0
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   14.0.23309.00 d14oob
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

**Comment by shawnhar** [comment]
Before loading this file you need to do something to get access to the x:\ folder.

See https://msdn.microsoft.com/en-us/library/windows/apps/mt188700.aspx

**Comment by CosmicBoris** [comment]
shawnhar thanks a lot!
