### ISSUE TITLE
Transform error: Cannot convert source type 'System.Numerics.Matrix3x2' to target type 'Windows.Foundation.Numerics.Matrix3x2'

### ISSUE THREAD

**Issue by bdpy** [Microsoft/Win2D#174]
I have the following error and do not know how to resolve it:
Based on this guide http://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_CanvasDrawingSession_Transform.htm I write the following code:
![transformerror](https://cloud.githubusercontent.com/assets/10549729/10435223/39a9f6ce-7127-11e5-9962-c7dcd4574f7d.png)

using System.Numerics;
private void CanvasControl_Draw(CanvasControl sender, CanvasDrawEventArgs args)
        {
            var ds = args.DrawingSession;
            ds.Transform = Matrix3x2.CreateTranslation(new Vector2(10, 10));
            ds.DrawText("Hello, world!", 200, 200, Colors.Yellow);
        }

and have the following error hovering above line on "ds.Transform...": Cannot convert source type 'System.Numerics.Matrix3x2' to target type 'Windows.Foundation.Numerics.Matrix3x2'

**Comment by damyanp** [comment]
Does this code compile successfully?  (ie, is it just an intellisense issue?).

Could this be the same as #145?

**Comment by bdpy** [comment]
Wow! It actually compiles! It didn't occur to me to compile it despite Intellisense. Then everything is ok.

**Comment by bdpy** [comment]
By the way, actually it is a Resharper issue, not Intellisense...
