### ISSUE TITLE
Anti aliasing is not correct on H/V lines

### ISSUE THREAD

**Issue by jeromebjerome** [Microsoft/Win2D#176]
10/15/2015

Hello,

What are the rules of application of Anti aliasing on lines?
The very basic sample below draws an horizontal line that will look better when not anti-aliased.
Win2D/Direct2D should be able to optimize rendering for horizontal and vertical lines.
When drawing a large number of H/V lines (a grid), it even appears that some lines are rendered correctly and others are not.

	Windows::UI::Color couleur;
	couleur.A = 255;
	couleur.R = 0;
	couleur.G = 0;
	couleur.B = 0;
	//args->DrawingSession->Antialiasing = CanvasAntialiasing::Antialiased;
	args->DrawingSession->Antialiasing = CanvasAntialiasing::Aliased;
	args->DrawingSession->DrawLine(0, 100, 120, 100, couleur, 1);

**Comment by shawnhar** [comment]
Antialiasing does not automatically snap to the pixel grid, so you will get different softening depending on whether your shapes are pixel aligned.

To get exactly single pixel lines regardless of scaling, DPI, etc, you can specify CanvasStrokeStyle.TransformBehavior = CanvasStrokeTransformBehavior.Hairline.

**Comment by damyanp** [comment]
I'm closing this issue at it seems to have been addressed.
