### ISSUE TITLE
ScrollView moving to top left corner when zooming in with canvas control

### ISSUE THREAD

**Issue by axorth** [Microsoft/Win2D#179]
Sorry, I am somewhat new to WPF and Universal Apps. I have a page with a couple of ScrollViews on it. The first is a menu and it works just fine. But the ScrollView with a canvas control in it always moves to the top left corner soon as I release my finger. 

            <ScrollViewer Grid.Row="1" Grid.Column="0" ZoomMode="Enabled" MaxZoomFactor="30" IsDoubleTapEnabled="False" x:Name="scrollView" HorizontalScrollMode="Enabled" VerticalScrollMode="Enabled"  >
                <canvas:CanvasControl x:Name="gridCanvas"  Draw="canvas_Draw" Width="{Binding ActualWidth, ElementName=canvasColumn}" Height="{Binding ActualWidth, ElementName=canvasRow}" ScrollViewer.VerticalScrollMode="Enabled" ScrollViewer.HorizontalScrollMode="Enabled"/>
            </ScrollViewer>

**Comment by axorth** [comment]
Here is the broader Grid control that it is a member of:
        <Grid Grid.Row="1" Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
            <Grid.ColumnDefinitions>
                <ColumnDefinition x:Name="canvasColumn" Width="*" />
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition Height="50"></RowDefinition>
                <RowDefinition x:Name="canvasRow" Height="*" />
            </Grid.RowDefinitions>
            <StackPanel x:Name="layerPanel" Padding="10" Orientation="Horizontal" Grid.Row="0" Grid.Column="0" Visibility="Collapsed">
                <TextBlock Text="Select Layer:"></TextBlock>
                <ComboBox x:Name="layerCombo" Margin="10,0,0,0" Width="100" ItemsSource="{Binding LayerList}" SelectionChanged="Layer_OnSelectionChanged" ></ComboBox>
            </StackPanel>
            <ScrollViewer Grid.Row="1" Grid.Column="0" ZoomMode="Enabled" MaxZoomFactor="30" IsDoubleTapEnabled="False" x:Name="scrollView" HorizontalScrollMode="Enabled" VerticalScrollMode="Enabled"  >
                <canvas:CanvasControl x:Name="gridCanvas"  Draw="canvas_Draw" Width="{Binding ActualWidth, ElementName=canvasColumn}" Height="{Binding ActualWidth, ElementName=canvasRow}" ScrollViewer.VerticalScrollMode="Enabled" ScrollViewer.HorizontalScrollMode="Enabled"/>
            </ScrollViewer>
        </Grid>

**Comment by damyanp** [comment]
Hi - I'm afraid that isn't really enough to allow me to easily reproduce what you're seeing.  

However, have you tried this using a non-Win2D control - say a rectangle, or a textblock?  If you find that this is not Win2D related then you may find you'll get better help asking somewhere where more XAML experts hang out (eg stackoverflow)?

**Comment by damyanp** [comment]
I'm closing this issue as it is inactive and doesn't seem to be directly Win2D related.  Please feel free to reopen if there's more we can do here from the Win2D side.
