### ISSUE TITLE
Look of InkStrokes drawn to CanvasRenderTarget look different depending on Windows UI scale

### ISSUE THREAD

**Issue by Trasteby** [Microsoft/Win2D#180]
When drawing on a standard InkCanvas, the ink looks the same regardless of Windows UI scaling settings (it looks the same on 100% versus say 125%). When drawing ink on a CanvasRenderTarget, however, the scaling settings change the look of the ink stroke. It looks like it does antialiasing differently on different UI scale settings.

These two images show how the same ink stroke is rendered on 100% UI scale versus 175% UI scale. On a standard InkCanvas, they both look like the 100%-version.

![100](https://cloud.githubusercontent.com/assets/3896403/10635087/7b16ac62-77f6-11e5-840c-71096214ad87.png)
The 100% version

![175](https://cloud.githubusercontent.com/assets/3896403/10635088/7b1a16ae-77f6-11e5-988d-8955434e6f38.png)
The 175% version

just to be clear, the UI scale settings I'm talking about are the ones you see if you go to Start Menu -> Settings -> System -> Display -> "Change the size of text, apps and other items". I'm running Windows 10.

**Comment by damyanp** [comment]
Is it possible that you're creating your CanvasRenderTarget with the DPI explicitly set to 96?  You can query the Dpi property on the render target to confirm this.

In the case that the UI is scaled 175% I expect the DPI should be 168.

If you construct the CanvasRenderTarget passing it something that implements ICanvasResourceCreatorWithDpi (for example, a CanvasControl or CanvasAnimatedControl) then the CanvasRenderTarget can pick up the dpi from the control, which ultimately picks the dpi up from the environment.
