### ISSUE TITLE
draw ink stokes on a rendred image 

### ISSUE THREAD

**Issue by thorizer** [Microsoft/Win2D#182]
I learned a lot from this project !  

But I can't figure out how to draw stokes on an image (picked from a file and rendered on screen) using Direct2D and save it back to the file (with the strokes) .

[c#] [windows universal app 10 ]

**Comment by clandrew** [comment]
I'm glad you found it useful. For your app, did looking at the Ink sample in ExampleGallery help? Our samples in ExampleGallery include loading images from files, and saving out ink strokes, and our docs contain sample code for interop with Direct2D. 

If your strokes need to be drawn using Direct2D, you can interop a CanvasDrawingSession to an ID2D1DeviceContext, and draw ink to it using [IInkD2DRenderer](https://msdn.microsoft.com/en-us/library/mt147263%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396). The drawing session can be created off of a CanvasRenderTarget, which supports saving image data back to a file.

**Comment by clandrew** [comment]
I'll close this, since there isn't any more action for us, but definitely feel free to re-open if you need more help.
