### ISSUE TITLE
Raw bitmap (byte array) manipulation and performance of Win2D.

### ISSUE THREAD

**Issue by Gavin-Williams** [Microsoft/Win2D#185]
Hi, 
I've been learning some old-school Win32 from the amazing stream by Casey Muratori, see here: https://handmadehero.org/  He is building a game in C (with some C++) and using StretchDIBits to push a void* array to the window's device context.

But I'm coming from C#, and although I have been following the stream with classic C (mostly) and old Win32 code. I want to work with WinRT (UWP) for the platform code. I have explored using the WriteableBitmap Xaml control, and mostly, it works really well. BUT I've noticed some subtle frame jitter. And so I started doing a survey of game-loops and technology combinations for basic game setups in order to measure frame-times and consistency. Some early results along with msdn documentation show that some of the available controls have performance issues which are unacceptable for games. Also, the Xaml stack itself seems not to be fine-tuned for games. Here's a comparison between Win32 StretchDIBits and WriteableBitmap:

setup .................................................... render cycle .. Frametimes ...................... slow/fast frames

Win32 Cpp WNDCLASSW .................. sleep+burn .... 16.668 +/- 0.41 (debug!) ... 0 / 8
WinRT Cpp Xaml - WriteableBitmap ... Xaml .............. 16.667 +/- 0.61 (release) .. 77 / 76

Now the reason AFAIK for these results, is that although the Xaml rendering cycle is on average spot on 60fps, it has no guarantee for dead-accurate frame-times and at least under Windows 8.1 it would even call OnRendering more than once in a frame (this can be checked for and escaped), But also I think it can drop frames and run at 33fps (but that's from memory, and I'm not 100% sure now). And in any case, if that's message related, CoreIndependentInputSource can unload some work to a back-thread. But I don't think it's going to fix the issue with swinging frame-times.

You'll notice that the frame time standard deviation is wider for the Xaml implementation and looking at slow / fast frames, which I defined as being outside of the range { ave +/- 0.05ms), it's obvious that the Xaml loop has poor consistency. 

I'm now setting up a Win2D test, and DirectX test after this, which I expect will perform better than Xaml, as I'm using the CoreWindow style application without Xaml and the swapchain also operates using an independent render cycle (the monitor refresh rate, and perhaps a gpu driven clock ?)

So to go further, I have some questions:

1) Does Win2d provide byte-array style bitmap mapping / streaming to the rendertarget, so that I can work with just the byte array each frame, setting the 0xAARRGGBB values and simply throw it at Win2D to render. If it does have this capability, what's the performance ? As in, am I going to get 1920x1080 bitmaps uploaded to the gpu each frame ? (I would consider using compression if required and feasible to minimize the upload data size)

2) Do gpu swapchains and particularly the Win2D implementation actually render to the window independently of Xaml (if I use that approach) or does the render-target/resource need to go through the Xaml composition stage, and therefore, it would be subject to the jittery frame-times of the Xaml rendering cycle. That's if I use Xaml.

3) If I use the CoreWindow technique, like that used in the VS2015 DirectX 11 template, am I going to see the higher frame rate consistency that I'm after, and that I would expect ? Something more similar to the Win32 results above.

**Comment by pleaseking** [comment]
Gavin,

I am not part of Win2D team or MS by any means, but we have a working product using Win2D to show bitmaps in a way you describe. Take a look at CanvasRenderTarget and CanvasAnimatedControl. Performance is not brilliant but OK if you just need to show graphics - i.e. it gets much worse if you need to combine graphics that you render yourself with text rendered by Win2D etc.

**Comment by damyanp** [comment]
1) You can create a CanvasBitmap from bytes using [CanvasBitmap.CreateFromBytes](http://microsoft.github.io/Win2D/html/Overload_Microsoft_Graphics_Canvas_CanvasBitmap_CreateFromBytes.htm).  Performance for this sort of thing is never going to be as good as using the GPU to hardware accelerate rendering your scene.

2) CanvasAnimatedControl (which is built on CanvasSwapChain and XAML's SwapChainPanel) presents on its own thread, so it is independent of XAML's normal UI work.

3) I'm not entirely sure what you're measuring in your definition of frame rate consistency.  Without sharing your benchmark code it's not really possible to comment on what you will or won't see.  If you look at ExampleGallery's animated control example you should be able to see that it runs pretty consistently at 60FPS.

I'm not sure how much success you'll have an manually rendering bitmaps on the CPU in C#.  If you want to do this in C++ then you'd probably be better of using Direct3D directly.

**Comment by Gavin-Williams** [comment]
Thank you both for the info. I've just setup a Win2D project tonight in C++ and created a drawing session on the swapchain, but it's very late here now. So I'll take a look tomorrow at the controls you've mentioned.

I don't need to mix any other features at this stage. The goal is just to work with the bitmap. So if it can handle that within the frame budget, it's all good.

**Comment by Gavin-Williams** [comment]
So I've had some success - getting a byte array to the swapchain. But I must be doing it wrong because the cost is too large. I think there is too much array copying going on. I'm not familiar with C++CX much and to me it looks like I have to 
1) render the visuals into the byte[]
2) copy the byte array into Platform::Array
3) copy the platform::array into the CanvasBitmap
4) copy the Canvas bitmap to the gpu with DrawImage

But I don't see a more direct way to get a byte[] to the gpu. I will continue to look into this. 

But there is another issue which I think I should sort out first. I have an empty render method with just present :

[code]
    bool Game::Render()
    {
	    if (m_timer.GetFrameCount() == 0) return false;
	    bitmapRenderer->Render(m_timer);
	    return true;
    }

bool BitmapRenderer::Render(DX::StepTimer m_timer)
{
	swapChain->Present(0);
	return true;
}
[/code]

And this produces frame-times in an approximate pattern : 0.5ms  - 0.5ms - 15ms 
Here is a sample of the frame times:
15.809
0.739
0.542
15.472
0.461
0.536
15.703
0.597
0.401

This looks like an issue with Win2d to me because when I remove the swapChain->Present(0); call I get the following sample of frame times:

0.118
0.106
0.110
0.097
0.097
0.104
0.110
0.102
0.095

**Comment by damyanp** [comment]
[This discussion](https://social.msdn.microsoft.com/Forums/en-US/75765329-b4f9-46e6-9380-37c4dfb977a9/swapchainpresent0-0-blocking?forum=wingameswithdirectx) talks about why passing 0 to Present() may still cause it to wait for a vsync.

I think that if you really want to deal with large byte arrays (rather than hardware accelerated rendering) then you should look into working directly with Direct3D rather than the Win2D.

Think of it this way: Win2D is built on top of Direct2D which is built on top of Direct3D.  You're adding two extra layers of abstraction (Win2D & Direct2D) that you're now trying to find ways to bypass.

**Comment by Gavin-Williams** [comment]
Right, ok. I have started looking at Direct3d as a solution for this. And just to re-state the goal - I want to provide the ability to work directly with a bitmap buffer for 1920x1080 rendering, with dead accurate frame-times to reduce stutter as much as is possible. Certainly I want frame times to be more reliable than is possible in Xaml, and approaching what is possible with GDI.

Another solution I'm considering, but haven't looked into it yet, is wrapping the GDI functionality inside a Windows Runtime Component or DLL.

**Comment by damyanp** [comment]
Ok - I'm closing this issue since we're straying out of Win2D territory now.

Best of luck with your adventures!

**Comment by 13thsymphony** [comment]
Note that you can't use GDI in store applications.

**Comment by Gavin-Williams** [comment]
@13thsymphony Oh ok. Thanks for the warning.

**Comment by Gavin-Williams** [comment]
I just wanted to add that after looking at C++ / DirectX frametimes, I'm now almost convinced that the Holy Grail of project types (in terms of frametime consistency) does not exist. WinRT takes away the capacity to manage frametimes in software, so we are stuck with slightly inaccurate frametimes, because we either have to go through the xaml timing mechanism or go through the vsync timing mechanism, both of which have inaccuracies. GDI and immediate presentation allowed the cpu to handle timing with thread sleeping and cpu burning steps. That era appears to be gone. But the standard deviation for frame-times is very low for DirectX +/- 0.1ms. So I can hardly complain, that is very good. And even in software where i only got 8 frames out of 255 that were slow/fast, the rare spikes were more significant and pushed the sd out to 0.41.

Haha, maybe this is something not many people care about.

**Comment by 13thsymphony** [comment]
@Gavin-Williams, you are aren't going to get microsecond-accurate timing intervals for any display output in Windows. Everything going to the display including GDI is gated behind DWM and VSync. Windows is not a realtime OS. In addition, things like GSync and power-reducing refresh modes make it impossible guarantee Vsync timing.

Can you give more info about why you need this kind of timing accuracy?

**Comment by Gavin-Williams** [comment]
I just noticed that gdi is very fast at pushing a 1920x1080 texture ... and just using a game loop that burns the remainder of the frame gives very accurate frametimes, most frames are 16.668 / 16.669 ms (although the standard deviation was 0.4ms). I wanted to match that kind of consistency with WinRT for a good fixed frametime experience and most importantly to remove jitter that was noticeable. But even in my latest test with DirectX (using update subresource on a default texture) I'm just not getting close to gdi's accuracy, and DirectX is struggling to push the data over. At 1920x1080, DirectX (vsync) is producing frames with a standard deviation of 2.3ms, with some big spikes - as high as 30ms frames. That's actually quite bad.

I'm going to look at using a dynamic texture. But IIRC update subresources is faster (in contradiction to what some people say), but i will recheck, as that might be specific to the scenario.

I *want* this accuracy because that's the kind of accuracy and speed i can get out of win32. And i would expect that DirectX (and Xaml) provide such a past path for transferring bitmap data. If gdi can do it, then surely DirectX can !

**Comment by CAMOBAP795** [comment]
For working with plain C arrays use `Platform::ArrayReference`http://stackoverflow.com/questions/23979832/convert-byte-to-arraybyte
