### ISSUE TITLE
Create geometry from path data string

### ISSUE THREAD

**Issue by bgulrich** [Microsoft/Win2D#186]
In Xaml you can declare a path geometry using a move and draw command syntax string like this:

<Path x:Name="Arrow" Fill="White" Height="11" Width="9.67"
  Data="M4.12,0 L9.67,5.47 L4.12,10.94 L0,10.88 L5.56,5.47 L0,0.06" />

I can't find any way to create a geometry from a string in this manner in Win2D.  There are lots of tools out there that produce geometries represented in this string format and it would be great to be able to simply drop the string in and create a geometry from it.

**Comment by clandrew** [comment]
Yes- unfortunately, this isn't a feature that exists in Win2D. 

This feels reminiscent of some questions we've had before about supporting SVG and SVG-like syntax to define content (#15). As mentioned there, we couldn't commit to making an investment for the immediate short term.

This path-building syntax used by Xaml/SVG is a more narrow, scoped feature compared to the bigger problem of SVG as a whole. So although it's hard to say for certain we can make investment on this either, I think this will make a worthwhile backlog suggestion for us to talk about, and suggestions like these are valuable in how we prioritize things. 

In the meantime, other options are to use a different component to transcode the string, or- funny as it sounds- to use a fancy regex to turn the string into Win2D code, if the string is too long to do it manually.

Thanks for bringing this to our attention.

**Comment by JohnnyWestlake** [comment]
A more limited workaround for anyone who wants a relatively simple way to render "vectors" in Win2D without a massive hassle is to import the paths into a font file beforehand. (Quite a few free on-line solutions for this, or some very good desktop apps like HighLogic FontCreator).

Obviously it means you can't dynamically create your arbitrary paths at runtime, changing the stroke width is no longer as straightforward and the path format for font's isn't as advanced as you'd find inside an AI file, but if you need icons or simple re-sizeable vector components it may be worth looking at. Just becomes as simple as loading the font and calling DrawText

**Comment by bgulrich** [comment]
Thanks for the quick responses, guys!

Part of what I was I am trying to do is to create a dropshadow effect since these are not available in UWP apps.  I was going to layout the few elements I needed this effect on in Win2d with a shadow included (many included the string paths I was asking about, hence my trouble).  I've since diverted to a more generic method.  I'm using RenderTargetBitmap to get a bitmap of the control to which the shadow is to be applied, then creating the shadow behind the control by using Win2d to apply the shadow effect to this bitmap.

If you've got any better suggestions for how to implement this, I'd love to hear them.

**Comment by shawnhar** [comment]
The Win2D team discussed this suggestion in sprint planning this morning, and feel that this feature is out of scope for belonging in Win2D itself.  If anyone is interested in pursuing the idea, we'd encourage creation of a separate project for parsing these strings and converting them to Win2D geometry objects.  There's no technical reason for that work to be done inside Win2D rather than as a helper library, and we don't think knowledge of specific declarative formats such as XAML or SVG belongs in the core Win2D library.
