### ISSUE TITLE
Win2D vs. SDL2

### ISSUE THREAD

**Issue by SneWs** [Microsoft/Win2D#187]
Looking through and using Win2D have given me a nice first impression, I do however miss two specific things that are currently present in SDL2, but not in Win2D.

1) Rotation by angle, being able to set a rotation angle on a Draw call for a image and
2) Flipping the pixels horizontally and/or vertically in the Draw call.

The two items above are both provided in SDL2 when doing a SDL_RenderCopyEx, see https://wiki.libsdl.org/SDL_RenderCopyEx. 

It would be great for me and most likely others trying to migrate code from SDL2 into Win2D if there where a encompassing version of this draw call API.

Cheers
// Mac

**Comment by shawnhar** [comment]
Hi Mac,

In Win2D, arbitrary transforms can be applied to any draw operations by setting the CanvasDrawingSession.Transform property before calling DrawImage.

To rotate: drawingSession.Transform = Matrix3x2.CreateRotation(angleInRadians);

To flip vertically: drawingSession.Transform = Matrix3x2.CreateScale(1, -1);

**Comment by SneWs** [comment]
Nice. That was perhaps a bit too easy. Thanks! :)
