### ISSUE TITLE
Spritesheets and/or Sprites on quads

### ISSUE THREAD

**Issue by seriousGeorgeFX** [Microsoft/Win2D#189]
Referring to https://github.com/Microsoft/Win2D/issues/16 I always took a close look to the backlog. Since the last update spritesheet support suddenly dropped out of the backlog completley? 
Don't you have any further plans to support spritesheets?

Well a spritesheet parser would be one thing (could be more or less easily be imlpemented by any user himself). But I would also love to see fast sprites with high performance, e.g. on quads.

Backstory: I wrote a own little particle engine with win2d/c# to get used to it. I tried with fillcircle which worked great and then with bitmapimages. But performance with bitmapimages was rather bad - even slower than use vanilla xaml with images. I thought bitmapimages would be drawn on quads automatically - or I did something completley wrong,

Summary: So here my re-reqeust for spritesheetssupport but more importantly to have sprites/textures drawn on quads and maybe even spritebatching.

Edit: I wanted to add the "backlog suggestion" label but I'm afraid I do not know how

**Comment by 13thsymphony** [comment]
@seriousGeorgeFX, sharp eyes - we indeed did remove sprite sheets from the backlog. We are preparing a Win2D update which coincides with the Win10 1511 update (build 10586). Hint: you can get a preview of what's coming here :):
https://msdn.microsoft.com/en-us/library/windows/desktop/mt619833(v=vs.85).aspx
(That API is new as of 1511...we'll get the docs updated to specify the version requirements)

**Comment by seriousGeorgeFX** [comment]
Oh... that's great news. Can't wait to hear more :)
Thanks for sharing and all your great work

**Comment by 13thsymphony** [comment]
FYI we're waiting for the public release of the 10586 SDK (you can get it now as part of the Windows insider program). Until then, we will only be pushing out Win10 "RTM" (build 10240) features.
