### ISSUE TITLE
invalidate, update and redraw specific area / region

### ISSUE THREAD

**Issue by bdpy** [Microsoft/Win2D#190]
If there is need to frequently invalidate and update specific areas, what is the best approach to do this? What are the differences in terms of performance, or any other differences among these options?

1) CanvasControl (or CanvasAnimatedControl): draw to CanvasRenderTarget, update specific area of CanvasRenderTarget, draw entire CanvasRenderTarget by CanvasDrawingSession.DrawImage.
2) CanvasVirtualControl: update region by RegionsInvalidated event. (Other than being able to update region, for me there are no additional needs - i.e, image is not very large - to use CanvasVirtualControl)
3) Any Control: Invalidate and redraw entire control.
4)  CanvasImageSource: As far as I understand it's possible to update region in CanvasImageSource, but in this case I need to totally reimplement all policies which I receive for free when use CanvasControl. I have difficulties doing it on my own. Where can I see an example how to implement those policies in C#?

**Comment by shawnhar** [comment]
First, how sure are you that you really need to update specific areas?  Have you tried just invalidating an entire CanvasControl whenever anything changes to see if that is fast enough?  GPU performance can be surprising, and partial redraws aren't always a performance win...

If you definitely do need partial redraws, CanvasVirtualControl is by far the most straightforward way to do that.

We don't have a C# example of how to reimplement something like CanvasControl on top of CanvasImageSource.  You can of course look at the CanvasControl source code to see everything it does, but it's pretty complicated (took us a lot of time to get right :-)  I don't recommend trying to recreate all that.

**Comment by bdpy** [comment]
I'm writing a real-time charting application (and Win2D is the best for fast 2D graphics, second to Direct2D itself), usually only one tiny area should be updated, but it should be updated frequently when new data arrives. There also could be long periods of no updates at all, because the data which arrives is high frequency data but irregular in time intervals. I think, I should follow your advice to use CanvasVirtualControl, or just CanvasControl and make entire control redraws.

Nevertheless, can you, please, give the last piece of advice on the whole which control may be better suited for real-time charting?:

- SwapChain based control, like CanvasAnimatedControl: But there is a problem that application requires many (20-50) charting windows to be open at the same time, and in MSDN as well as your documentation it is not recommended to have more than 2-4 swapchains present at one time on screen? Also there is a minor issue here (since Win2D is intended mainly for games), that CanvasAnimatedControl is run on a game loop and updates / draws 60 times per sec, while I need to update it and draw just whenever needed. I tried to change IsFixedTimeStep to false, but it seems only to affect Update, Draws are still done 60 times/sec.

- ImageSource based control, like CanvasControl and CanvasVirtualControl: But they lack smooth animation in comparison to SwapChain. I wonder if reduced smoothness, if any, of animation would be noticable at all?

**Comment by shawnhar** [comment]
I would certainly not recommend using a swapchain if you have up to 50 of these things at the same time. CanvasControl or CanvasVirtualControl is the way to go for that.

Also your behavior of periodic updates and animation mixed with periods of no change, indicates that you should be looking at CanvasControl or CanvasVirtualControl over CanvasAnimatedControl.

Swapchains are really only suitable if you have very small number (typically just 1) of large (typically fullscreen) surfaces that continually animate, like a game.

**Comment by bdpy** [comment]
Thank you for help, now I have a clear picture, but the last question: Is there any significant performance difference in CanvasControl vs CanvasVirtualControl (given they are used in identical circumstances of up to 50 windows on screen)? Before asking this question I googled and searched your documentation but couldn't find any info...

**Comment by shawnhar** [comment]
CanvasControl and CanvasVirtualControl should be approximately equivalent in performance.
