### ISSUE TITLE
Exception when using x:Bind to ViewModel for CreateResources and Draw

### ISSUE THREAD

**Issue by TimVinkemeier** [Microsoft/Win2D#192]
Hi,

I have the following issue while playing with Win2D for developing a small game.
I want to use MVVM as far as possible, therefore I moved the event handlers for `CreateResources` and `Draw` to my viewmodel and use `x:Bind` to bind to them.
In my page, this looks like:
```XAML
<xaml:CanvasAnimatedControl CreateResources="{x:Bind ViewModel.CreateResources}"
                            Draw="{x:Bind ViewModel.Render}"
                            PointerMoved="{x:Bind ViewModel.CanvasControl_PointerMoved}" />
```
In the code-behind, I simply do:
```csharp
public GameViewModel ViewModel => DataContext as GameViewModel;

public GamePage()
{
    this.InitializeComponent();
    DataContext = new GameViewModel();
}
```
And finally, in the ViewModel, these are my event handlers:
```csharp
public void CreateResources(CanvasAnimatedControl sender, CanvasCreateResourcesEventArgs args)
{
     args.TrackAsyncAction(LoadResourcesAsync(sender).AsAsyncAction());
}

public void Render(ICanvasAnimatedControl sender, CanvasAnimatedDrawEventArgs args)
{
    args.DrawingSession.Transform = Matrix3x2.CreateTranslation((float)sender.Size.Width * 0.5f, (float)sender.Size.Height * 0.5f);

    for (var x = 0; x < 10; x++)
    {
        for (var y = 0; y < 10; y++)
        {
            var position = MapToScreen(new Vector2(x, y));
            args.DrawingSession.DrawImage(_test, new Rect(position.X, position.Y, TILE_WIDTH, TILE_HEIGHT), new Rect(0, 0, TILE_WIDTH, TILE_HEIGHT));
        }
    }
}

private async Task LoadResourcesAsync(ICanvasResourceCreator canvasControl)
{
    _test = await CanvasBitmap.LoadAsync(canvasControl, "Resources/Textures/default.png");
}
```

Now the problem. When I start the game, the `CreateResources` is executed fine, but before I get a call to `Draw`, I receive the following exception from the ViewModel getter in the code-behind:
```
An exception of type 'System.Exception' occurred in DeepMiningInc.App.exe but was not handled in user code.

Additional information: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))
```

I understand that this is a threading problem, but I am not sure why it occurs.
Can you help me with this or tell me what I am doing wrong?
Thanks,
Tim

**Comment by damyanp** [comment]
The problem here is with the definition of the ViewModel property.  This accesses DataContext, which can only be accessed from the UI thread.  Recall that Draw is raised from the game loop thread. When CanvasAnimatedControl raises the Draw event, {x:Bind} ends up querying ViewModel which queries DataContext - which fails because it's running on the game loop thread and not the UI thread.

If you modify ViewModel to be something like:

    public ViewModel ViewModel { get; set; }

And then in your constructor do:

    ViewModel = new GameViewModel();
    DataContext = ViewModel;

Then you should find that it works again.

I'm not terribly familiar with {x:Bind}, but my quick reading of it suggests that if you use {x:Bind} exclusively then you don't need to set DataContext at all.

**Comment by TimVinkemeier** [comment]
That was indeed the issue, your suggestion fixed it.
I never recognized that `DataContext` may only be accessed from the UI thread - I likely never tried :smiley:.

Thank you for your help and keep up the good work :+1:
