### ISSUE TITLE
Add symbol download instructions to the wiki

### ISSUE THREAD

**Issue by XinliZ** [Microsoft/Win2D#200]
It's great to have this opensource project. I am currently hitting a crash in the Microsoft.Graphics.Canvas.dll, but not able to find the right symbol for it. 

Please add the symbol installation instructions to the WIKI, and also how to build the project if that is the only way to debug it.

**Comment by damyanp** [comment]
[README.md](https://github.com/Microsoft/Win2D/blob/master/README.md) contains instructions on how to build your own nuget package.

**Comment by XinliZ** [comment]
Thanks. Is there a way to download the symbol without build? That's a easier way to investigate bugs.

**Comment by shawnhar** [comment]
We don't ship symbols for prebuilt Win2D binaries, sorry.

If you need to debug inside Win2D, you will need to compile it yourself.
