### ISSUE TITLE
Error with R8UIntNormalized The bitmap pixel format is unsupported

### ISSUE THREAD

**Issue by PatrickSCLin** [Microsoft/Win2D#201]
IsPixelFormatSupported(DirectXPixelFormat) return true when I check format R8UIntNormalized by the device which I created,

but get error "The bitmap pixel format is unsupported" when I create a CanvasBitmap by createFromBytes

**Comment by PatrickSCLin** [comment]
namespace Test
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainPage : Page
    {
        byte[] y_data = new byte[4000 * 3000];

        CanvasBitmap y_bitmap;

        public MainPage()
        {
            this.InitializeComponent();
        }

        private void CanvasControl_Draw(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args)
        {
            using (var session = args.DrawingSession)
            {
                if (y_bitmap != null)
                {
                    session.DrawImage(y_bitmap);
                }
            }
        }

        private void CanvasControl_CreateResources(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
        {
            DirectXPixelFormat format = DirectXPixelFormat.R8UIntNormalized;

            if (sender.Device.IsPixelFormatSupported(format) == true)
            {
                y_bitmap = CanvasBitmap.CreateFromBytes(sender, y_data, 4000, 3000, format);
            }
        }
    }
}

**Comment by shawnhar** [comment]
Thanks for the report - I understand what is causing this and think I know how to fix it.

As a workaround, this should work if you use the overload of CreateFromBytes that lets you specify a CanvasAlphaMode, and set this to CanvasAlphaMode.Ignore.

**Comment by PatrickSCLin** [comment]
I can create the CanvasBitmap with R8 format by overload function,

but still get not support error when using drawImage

**Comment by shawnhar** [comment]
Ok, short answer is Direct2D does not support R8 format for drawing bitmaps.  We'll be updating Win2D docs (and maybe also the IsPixelFormatSupported implementation) to better explain this.

Long answer is this format is supported in a few very specific cases, such as when using it as input to the YCbCr effect in native Direct2D.  But it's not suitable for general purpose use as a bitmap.

**Comment by shawnhar** [comment]
Win2D 1.11.0 (released today) has more accurate documentation about these formats: http://microsoft.github.io/Win2D/html/PixelFormats.htm
