### ISSUE TITLE
Unable to render rgba strokes into transparent offscreen 

### ISSUE THREAD

**Issue by Sebosek** [Microsoft/Win2D#202]
Hi,

when I want to render strokes with transparency (argb(100, 255, 255, 0) in my case) into transparen offset screen; final picture is empty in photoshop, Office Picture Manager and black in system explorer. But when I use classic color, like Colors.Black as pen it work like a charm or when I use Colors.White as background and pen with color argb(100, 255, 255, 0) I works. Am I missing something? I'm using Win2D.uwp in Windows Universal App.

    private async Task SaveToImage(string id, InkStroke stroke, float width, float height)
    {
        CanvasDevice device = CanvasDevice.GetSharedDevice();
        var dpi = DisplayInformation.GetForCurrentView();

        using (CanvasRenderTarget offscreen = new CanvasRenderTarget(device, width, height, dpi.LogicalDpi))
        {
            using (CanvasDrawingSession ds = offscreen.CreateDrawingSession())
            {
                ds.Clear(Colors.Transparent);
                ds.DrawInk(new InkStroke[] { stroke });
            }

            StorageFolder folder = await GetNotesFolder();
            StorageFile file = await folder.CreateFileAsync(id + ".png", CreationCollisionOption.ReplaceExisting);

            using (var output = await file.OpenAsync(FileAccessMode.ReadWrite))
            {
                await offscreen.SaveAsync(output, CanvasBitmapFileFormat.Png);
                await output.FlushAsync();
            }
        }
    }

**Comment by shawnhar** [comment]
I don't see where you are specifying the color of the ink stroke?   It would help if you could post a complete repro app that I can compile and run.

I just tried a simple app that draws a partially transparent line over a fully transparent background, and that saves out to .png as I would expect...

**Comment by Sebosek** [comment]
Here link to repo https://github.com/Sebosek/Sebastian.WebInk - main code is in MainPage.xaml.cs. If you try to run application, just wait few moments and after page load try to draw/write with highlight and then save...

**Comment by shawnhar** [comment]
Thanks for the repro, that helped me understand what is going on.

Turns out this behavior is actually by design!  It is because you are drawing the ink using the DrawAsHighlighter attribute, which causes the ink system to use a "min" blend mode.   Min of transparent and anything is still transparent, so nothing ever gets drawn...

The solution is either don't draw over a transparent background, or if you want the ink to be "solid" so it will show up even on such a background, don't use the DrawAsHighlighter attribute.

**Comment by shawnhar** [comment]
Note you can see the same thing if you use DrawAsHighlighter mode over a black background - nothing shows up because the min of black and anything is still black.

DrawAsHighlighter mode only really works over a white (or pale) background.

**Comment by Sebosek** [comment]
Ahh; I didn't realize, thank you for clarification! :+1:
