### ISSUE TITLE
Assign Effects to User Controls (Backlog Feature Request)

### ISSUE THREAD

**Issue by stonstad** [Microsoft/Win2D#203]
Win2D is fantastic -- thank you for providing such a well thoughout API.  

I would name my first born after you or the dev team if a feature were added to allow effects to be added to non-canvas visual tree controls.  It is nice to work with a canvas but nothing has matched the sheer beauty of applying effects to text in the way that was achieved with Silverlight.  Thank you for your consideration of this backlog request. 

Thanks,
Shaun

**Comment by shawnhar** [comment]
I don't think "Win2D" would make such a good name for a firstborn, but thanks for the praise :-)

Regarding applying effects to XAML tree elements, I have a mix of good and bad news:

1. Bad: Win2D rendering is entirely immediate mode, so it's not really feasible to integrate into a retained mode system like the XAML visual tree (other than through specific immediate mode surfaces like CanvasControl)
2. But good: the Win2D effects description API is shared with the new Windows.UI.Composition APIs, which ARE retained mode, and support a subset of the same effects as Win2D
3. But bad: Windows.UI.Composition only supports applying effects to composition visuals, not to arbitrary XAML content
4. But good: you aren't the first person to ask about that (eg. https://social.msdn.microsoft.com/Forums/en-US/8db68550-254f-4f79-919c-a2445f893096/uwp-applying-effects-on-xaml-element-using-windowsuicomposition?forum=wpdevelop)

So you can't do this today, but in that thread the composition team answered "further integration between XAML and Windows.UI.Composition, including effects, is something we’re actively looking at for a future release".

**Comment by shawnhar** [comment]
I'm going to close this issue as (should it ever happen) effects + XAML would be a composition feature rather than an addition to Win2D.

**Comment by stonstad** [comment]
Hi Shawn --

I was wondering if you might know whether any of the recent updates to the Composition UI API via Creator's Update might bring us closer to being able to apply effects to arbitrary XAML?

**Comment by sohchatt** [comment]
In the Creator's Update, we added a new XAML Brush type, [XamlCompositionBrushBase](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.xamlcompositionbrushbase), that allows you to paint a XAML UIElement with a CompositionBrush (including an EffectBrush). We're in the process of adding more extensive documentation on msdn and samples in [WindowsUIDevLabs ](https://github.com/Microsoft/WindowsUIDevLabs/)that demonstrates usage, so do stay tuned. Here's a code snippet of how you could paint a XAML Grid with an image that has a GaussianBlurEffect applied to it:

Your brush class:
       
             class ImageEffectBrush : XamlCompositionBrushBase
             {
                    private LoadedImageSurface _surface;
                    
                    protected override void OnConnected()
                    {
                         var compositor = Window.Current.Compositor;
     
                         // Load image onto SurfaceBrush
                         _surface = LoadedImageSurface.StartLoadFromUri(new Uri("ms-appx:///Assets/Photos/myImage.jpg"));
                         var surfaceBrush = compositor.CreateSurfaceBrush(_surface);
                         surfaceBrush.Stretch = CompositionStretch.UniformToFill;'

                         // Effect description
                         IGraphicsEffect graphicsEffect = new GaussianBlurEffect{
                             Name = "Blur",
                             BlurAmount = 20,
                             Source = new CompositionEffectSourceParameter("image"),
                         };

                         // Create EffectFactory and EffectBrush
                         var effectFactory = compositor.CreateEffectFactory(graphicsEffect);
                         var effectBrush = effectFactory.CreateBrush();
                         effectBrush.SetSourceParameter("image", surfaceBrush);

                         // Set XCBB to paint Grid with EffectBrush
                         this.CompositionBrush = effectBrush;
                    }
                    
                    protected override void OnDisconnected()
                    {
                         if (_surface != null)
                         {
                              _surface.Dispose();
                              _surface = null;
                         }
                         if (this.CompositionBrush != null)
                         {
                              this.CompositionBrush.Dispose();
                              this.CompositionBrush = null;
                         }
                    }
               }

          
Use in markup:

        <Grid Name="ImageEffect" Grid.Column="0" Grid.Row="0" Margin="5">
             <Grid.Background>
                  <local:ImageEffectBrush/>
             </Grid.Background>
        </Grid>

Hope this helps. Feel free to ask any questions on the [WindowsUIDevLabs ](https://github.com/Microsoft/WindowsUIDevLabs)repository regarding the XAML/Composition APIs as well.
