### ISSUE TITLE
Problem with CreateResources event

### ISSUE THREAD

**Issue by MSAUCTO** [Microsoft/Win2D#205]
I have a problem where I'm using CreateResources on an AnimatedControl to create a grid.  The event fires and it should draw a grid.  The code executes but doesn't show a grid within the application.  Other code within a Draw event does execute showing a hundred circles plotted, but the grid doesn't appear.

Any idea what's happening?

//  draw the circles
private void CanvasAnimatedControl_Draw(ICanvasAnimatedControl sender, CanvasAnimatedDrawEventArgs args)
        {
            // Draw the ants
            foreach (Ant ant in colony.Ants)
            {
                args.DrawingSession.DrawCircle(100 + (5 * ant.X), 100 + (5 * ant.Y), 2.5F, Colors.Black);
            }
        }

// draw the grid
private void canvas_CreateResources(CanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
        {
            CanvasCommandList cl = new CanvasCommandList(sender);
            using (CanvasDrawingSession clds = cl.CreateDrawingSession())
            {
                //Create the ant grid
                for (int x = 0; x <= 100; x++)
                {
                    // Draw the vertical line of a grid
                    clds.DrawLine(100 + (x * 5), 100, 100 + (x * 5), 600, Colors.White);

                    for (int y = 0; y <= 100; y++)
                    {
                        // Draw the horizontal line of a grid
                        clds.DrawLine(100, 100 + (y * 5), 600, 100 + (y * 5), Colors.White);
                    }
                } 
            }
        }

**Comment by shawnhar** [comment]
This CreateResources handler draws some lines into a command list, but it doesn't look like you then do anything with that command list?

What are you expecting this code to do?

**Comment by MSAUCTO** [comment]
I expected this to draw the grid by placing the instructions into a command list.  How do I trigger  the command list being executed?

**Comment by shawnhar** [comment]
A command list is just a stored list of drawing commands.  This won't display anything until you draw that command list to somewhere that's actually visible - typically using DrawImage in your Draw event handler.
