### ISSUE TITLE
Is there any way to turn a xaml image into a CanvasBitmap?

### ISSUE THREAD

**Issue by zhakopian** [Microsoft/Win2D#206]
I've been given an icon to place into my program. The icon is a xaml file. I haven't been able to find a way to do this using Win2D. From what I can tell, I have to draw images using DrawBitmap. Is there any way to use a  CanvasBitmap with a xaml image?

**Comment by shawnhar** [comment]
You could use XAML RenderTargetBitmap to render out the vector graphics into bitmap form, then CanvasBitmap.CreateFromBytes to turn that into a Win2D bitmap.

I don't really recommend that path except for very specific corner case scenarios, though.  If this image is just a static graphic that ships as part of your app, I suggest going back to whoever created it and asking it if they can give you the graphic in a standard bitmap format like .png instead.

**Comment by zhakopian** [comment]
I wasn't able to get this down as the intermediary steps ended up being just as confusing, but I have gotten new instructions for implementation that I'm going to figure out now.

Thank you for the guidance.
