### ISSUE TITLE
what is the good strategy for drawing a mount of images at once

### ISSUE THREAD

**Issue by PatrickSCLin** [Microsoft/Win2D#210]
assume I have to redraw a mount of images which have different sizes, different sub positions in same CanvasSwapChianPanel

like 64 images sperate in CnavasSwapChainPanel, and each of them will redraw themselves in 30fps

I should set 64 CanvasRenderTargets to do this, or I should draw all of them in one CanvasRenderTarget ?

**Comment by shawnhar** [comment]
For best performance you generally want to use the smallest possible number of objects and drawing operations.  So fewer rendertargets will be preferable to many.

But I don't understand why you need rendertargets at all here.  What does "image" mean - are these CanvasBitmap objects?   Why can't you just draw these all directly to the swapchain - how/why does a rendertarget enter the picture at all?

**Comment by PatrickSCLin** [comment]
for a example: 4 channel videos in one screen, each of video will redraw when the decode data is available.

when swapchain create the session, it will clear a color, I don't other video be cleared when I just want redraw video which is on part of the screen

so in this case I should draw all of them in one rendertarget ?

**Comment by shawnhar** [comment]
This really depends on the details of your scenario - how big are the videos, what are their framerates, whether you can update them in lockstep or if they all need to advance independently, etc.

In general, drawing from many different bitmaps will be much faster than drawing to many different rendertargets.  So if you usually need to update many videos at the same time, caching that into a rendertarget would probably hurt.  But if your updates are typically only one of the videos at a time, caching could be a benefit.

My instinct is that the cost of decoding so many videos at the same time will dwarf that of drawing the decoded data, so it may not matter much at all how you do that drawing...

**Comment by shawnhar** [comment]
Closing issue as I believe this has been answered.
