### ISSUE TITLE
Create a CanvasFontSet from a URI

### ISSUE THREAD

**Issue by labtox** [Microsoft/Win2D#211]
Is it possible to implement the backlog item 'Create a CanvasFontSet from a URI' on a short notice?

It is the only thing that prevents us from using this library in our company. The rest looks awesome :-)

**Comment by shawnhar** [comment]
Thanks for the input - we will discuss in our next sprint planning.  Heads up this certainly won't be super short notice as the team is pretty much all on vacation until early January :-)

A few questions to clarify your requirements:

1. Where are the fonts you are wanting to use?  Packaged with the app?  Downloaded from a website?  (i.e. what sort of URIs do you want this to work with)

2. Which APIs do you want to use with these custom fonts?  Just drawing them?  Querying metrics?  Do you also need all the recently added custom layout and glyph analysis stuff?

Thanks!

Note that a short term option would be to load your custom fonts using native DWrite APIs, then interop and use Win2D for the rest of your app.  Using interop you can wrap a CanvasFontSet around an IDWriteFontCollection, or a CanvasFontFace around an IDWriteFont2.  Handling custom fonts in DWrite is kindof a pain, but should be possible to get just about anything working that way.

**Comment by labtox** [comment]
Thanks for the quick respronse! Vacation around this time of year is totally understandable ;-)

The context is PDF parsing/rendering, so we have:
- Default fonts which are not embedded, so i want to get them from the system font set
- Embedded fonts in the PDF, which we extract to the LocalState folder
- Packaged fonts in the Assets folder

1.  So about some kind of loading interface... the windows.ui.xaml.media.fontfamily constructor behaviour would be fine for most of the part, but that implementation lacks feedback about whether the loading succeeded or not.
It would be super nice if you could just load a font from a Stream object. That would make it pretty much universal.

2.  We only use the fonts for drawing operations, all the metric information is provided by the PDF file. So pretty much one way requests.


I think the interesting part willl be about which font types are actually supported (Type 0, 1, 3 or composite), but thats something for later.


Merry Christmas and thanks again for the awesome work.

**Comment by shawnhar** [comment]
CanvasTextFormat and CanvasTextLayout actually already support the same FontFamilyName syntax as XAML, which can load fonts from the ms-appx:// or ms-appdata:// protocols.  Sounds like that might be sufficient for your purpose?

The main things we are currently missing are:
1. Going straight from such a URI to a CanvasFontFace or CanvasFontSet
2. Loading from URIs other than app local data

We're not entirely sure that the second is a good idea, though, as it would introduce surprisingly delays and error paths into low level text rendering.  Curious your opinion on that - is "make font from arbitrary URI/stream" worthwhile, or would it be a better model for apps to always download whatever font data they need to local storage before handing it across to the rendering API?

Loading completion notification is tricky because DWrite itself (which Win2D builds on) doesn't really have such a thing.  The font system is highly asynchronous and has many levels of caching, so there's not really any single moment at which it "loads" a font - it tries to lazily pull in just the minimum of data needed to render whatever text it is given.

**Comment by labtox** [comment]
The 'ms-appx://' format does indeed work, but not exactly the same as in XAML. In XAML i could specify fallback fonts with a comma. I need either a way of retrieving if the requested font is valid (preferable), or just the way the XAML fontfamily string works. 


I'll try to elucidate our scenario a little more, because I think we might be diving to deep in this specific scenario otherwise.

As I mentioned before, we parse and render PDF's. So the data that we parse and render is all determined at runtime. That means:
- I don't know when an embedded font will actually work, so i want to be able to fall back to a metric equivalent somehow
- We don't display sentences and words, but we have CID's and kernings with which we want do draw glyphs. So a lot of the features that CanvasTextLayout and CanvasTextFormat offer are just overhead. Thats why I started looking into 'DrawingSession,DrawGlyphRun' and thats why I thought it was a good idea to have a CanvasFontFace from an URI. 

Performance is important in our application. It is not uncommon for a full text PDF page to have 500-600 words on it. 

I hope that it gives you a little more insight in our wishes. It's too bad I don't have any experience with programming to DirectX directly, so I don't know how much about how it works internally.


To return to the 'Font loading from URI/stream'... I think it's okay to just limit font loading to the local storage if that makes life easier for you. I also think loading from arbitrary URI's is a bad idea, or might at least introduce some complex situations. Loading from streams... I'm not sure, it could potentially avoid overhead of copying data from Memory to Storage, only to load it back into Memory again, But I don't know enough about the DWrite font loader to say anything about that.

**Comment by labtox** [comment]
In addition to my last comment: When i talked about loading font from streams, I mean just MemoryStream. The other streams would not make much sense to me.

**Comment by labtox** [comment]
Any sight on an ETA of this feature?

**Comment by shawnhar** [comment]
This will be in our next release.

**Comment by shawnhar** [comment]
This is implemented in Win2D 1.15.0 (released today)
