### ISSUE TITLE
Question: Creating a CanvasBitmap from an existing image and drawing with it

### ISSUE THREAD

**Issue by spyros1973** [Microsoft/Win2D#213]
I just recently found out about Win2D and I'm trying to get to grips with it.

I'm trying to load an image file, process it somehow (e.g. draw some text on it) and use it to draw on screen. I asynchronously load my image, alter it using the prepareBitmap function and assign in to a simple object (Win2DButton) that just uses that image to draw on a given DrawingSession. Obviously the approach is wrong, because when I use the newly prepared image (at the `_b2.draw(args.DrawingSession);` below) , I get an error message obviously related to threading: "Objects used together must be created from the same factory instance.".

So, the main question is: If I wanted to load an image and create CanvasBitmap objects by altering it somehow (e.g. load an empty Scrabble board tile and draw letters on them), what would the correct approach be?

Regards,
Spyros

        private async Task CreateResources(Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedControl sender)
        {
            this._image = await Microsoft.Graphics.Canvas.CanvasBitmap.LoadAsync(sender, "Images/numtile.png");
            _b1 = new Win2DButton(_image, 50, _height - _image.Size.Height);
            _image1 = prepareBitmap(_image);
            _b2 = new Win2DButton(_image1, 300, _height - _image.Size.Height);
        }

    private void canvas_DrawAnimated(Microsoft.Graphics.Canvas.UI.Xaml.ICanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedDrawEventArgs args)
        {
            args.DrawingSession.FillRectangle (new Rect(0, 0, sender.Size.Width, _height/2), Windows.UI.Color.FromArgb(200,0,0,0));
            args.DrawingSession.FillRectangle(new Rect(0, _height/2, sender.Size.Width, _height / 2), Windows.UI.Color.FromArgb(200, 150, 150, 0));
                     _b1.draw(args.DrawingSession);
            _b2.draw(args.DrawingSession);
        }

        private  void canvas_CreateResources(Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
        {
            args.TrackAsyncAction(CreateResources(sender).AsAsyncAction());
        }

        private CanvasBitmap prepareBitmap(CanvasBitmap bitmap)
        {
            var device = new CanvasDevice();
            var renderer = new CanvasRenderTarget(device, bitmap.SizeInPixels.Width, bitmap.SizeInPixels.Height, bitmap.Dpi);

            using (var ds = renderer.CreateDrawingSession())
            {
                ds.DrawText("50", new System.Numerics.Vector2(0, 0), Windows.UI.Colors.White);
            }
            return renderer;
        }

**Comment by spyros1973** [comment]
Posting questions online triggers the few remaining gray cells.
Apparently the problem was in creating a new `CanvasDevice` in the `prepareBitmap` function. It works if I just pass the `sender.device` from the `private async Task CreateResources(Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedControl sender)` function.

**Comment by shawnhar** [comment]
Glad you figured this out!
