### ISSUE TITLE
Question: Anybody made a game with this yet?

### ISSUE THREAD

**Issue by BubblegumYeti** [Microsoft/Win2D#218]
I am converting my old stuff to Win2D and it is going rather well TBH but I was just wondering if anybody already made a game with this as an example with source code? Would be good to look up some things... how they are done in Win2D because my old code contains a lot of roll-your-own legacy stuff that could probably be replaced by better, faster code.

**Comment by damyanp** [comment]
You could have a look at https://github.com/coopp/Harry.

**Comment by SneWs** [comment]
I used Win2D for a GameJam. The code is quite unpolished but perhaps it can help you somewhat. See https://github.com/SneWs/HeartLightHD

**Comment by shawnhar** [comment]
Closing issue as I think this has been answered - please feel free to reactivate if you disagree!
