### ISSUE TITLE
Please add Highpass effect

### ISSUE THREAD

**Issue by Nukepayload2** [Microsoft/Win2D#219]
The High-pass effect is widely used in the Photoshop and After Effect.
Unlucky, if I want to use High-pass in win2d, I have to write a custom effect. It's very inconvenient.

**Comment by 13thsymphony** [comment]
There are a few ways to achieve a high-pass filter in Win2D.

If you are targeting Win10, you can use the Sharpen effect:
http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Effects_SharpenEffect.htm

If you are targeting Win81, you can use the ConvolveMatrix effect:
http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Effects_ConvolveMatrixEffect.htm
And supply a sharpening kernel, such as the "sharpen" and "unsharp mask" examples on Wikipedia:
https://en.wikipedia.org/wiki/Kernel_(image_processing)#Edge_Handling

**Comment by shawnhar** [comment]
Another approach for implementing high pass filter is to take the difference between the original image and a blurred version of itself:

```
var highpass = new ArithmeticCompositeEffect
{
    Source1 = sourceImage,

    Source2 = new GaussianBlurEffect
    {
        Source = sourceImage,
        BlurAmount = filterThreshold,
        BorderMode = EffectBorderMode.Hard,
    },

    Source1Amount = 1,
    Source2Amount = -1,
    MultiplyAmount = 0,
    Offset = 0.5f,
};
```

**Comment by shawnhar** [comment]
Closing issue because we do not plan to implement a dedicated high pass filter effect in Win2D.
