### ISSUE TITLE
is something like orthogonal projection in Win2D ?

### ISSUE THREAD

**Issue by PatrickSCLin** [Microsoft/Win2D#222]
is something like orthogonal projection in Win2D ?

in OpenGLES, I can set a texture is from 0 to 1 and put a lots sub textures inside,

then using  orthogonal projection to implement a scrollable multi layout for videos.

I try the draw method with rect of destination and rect of source, the image is very blur.

ex: I have a content the height is 64 times of CanvasSwapChainPanel

and the height is over the MaximumBitmapSizeInPixels, how do I do something like 2d projection, camrea ?

**Comment by shawnhar** [comment]
You can display part of a larger image by passing a source rectangle to DrawImage, or using AtlasEffect.

The source bitmap is limited to the maximum GPU texture size, the same as in other hardware accelerated graphics APIs like OpenGL ES.
