### ISSUE TITLE
How to group Sprites together?

### ISSUE THREAD

**Issue by seriousGeorgeFX** [Microsoft/Win2D#226]
Hi there,

how can we group sprites together... or moreover, can we add another sprite as children to a existing sprite? Right now I'm working with separate sprites and the one acting as parent is dictating parameters like position, rotation etc. to its fake-children.

This would be fine, but I guess I'm getting into trouble somewhere when it comes down to collision detection or adding effects, because then I'll have to manage that for the parent and each children separatley - which would also be ok if that is the desired effect. But maybe there are scenarios where you would like them to behave like on sprite.

Edit:
Ah, I'm referencing to the "DrawFromSpriteSheet" Mehtod btw.

Also here's a little modification I made, called DrawRect which is more flexible for Spritesheets with many different Spritesizes (like from Texturepacket for example):
```JavaScript
public void DrawRect(CanvasSpriteBatch spriteBatch, Rect spriteRect, Vector2 position, Vector2 origin, float rotation, Vector2 scale, Vector4 tint)
        {
            spriteBatch.DrawFromSpriteSheet(bitmap, position, spriteRect, tint, origin, rotation, scale, CanvasSpriteFlip.None);
        }
```

**Comment by damyanp** [comment]
Win2D deals with just the drawing aspect of sprites.  Higher level constructs, such as a hierarchy of sprites with collision detection, are beyond the scope of Win2D.

One way you may want to build this system would be to have your sprites/entities in one data structure.  This can be traversed in various ways depending on if you are doing collision detection, drawing, updating audio etc.  In the drawing case this would call CanvasSpriteBatch.Draw as appropriate.

**Comment by seriousGeorgeFX** [comment]
Ok, that's what I suspected. Just wanted to be sure not to miss something here.
Thanks for clarification.

**Comment by damyanp** [comment]
I'm closing this as I feel this question has been answered.  Feel free to reopen if this isn't the case!
