### ISSUE TITLE
Question : Best / Fastest way to draw pixels

### ISSUE THREAD

**Issue by BubblegumYeti** [Microsoft/Win2D#227]
Hi... what would be the recommended way to draw pixels since there is no ds.DrawPixel(...)

Right now I am drawing tiny rects... or I guess I could draw tiny circles. This is ok, since I am scaling them from time to time (explosions etc), but what if I really need them to stay just one pixel? Is the rect drawing smart enough to optimize speed when just one pixel size?

**Comment by shawnhar** [comment]
Small rects (using FillRect) is a reasonable approach, or you could use SpriteBatch with a 1x1 bitmap.

Drawing many single pixels isn't a very efficient way to drive GPU hardware, though, so you likely won't get the best perf out of Win2D using this kind of approach.  It would be much more efficient if you could change your algorithms to draw a smaller number of more complex shapes (bitmaps, sprites, etc.)

**Comment by BubblegumYeti** [comment]
Well I have a particle engine in action that spawns pixels like mad :) It is a bit the charm of the whole thing. Anyway... I will see what kind of performance I can get out of it. I don't expect any trouble on PCs ofc... but on mobile it could be trickier.

**Comment by shawnhar** [comment]
Closing issue as I think this question has been answered.  Feel free to reactivate if you have further questions.
