### ISSUE TITLE
CanvasDrawingSession.DrawGlyphRun crashes with an AccessViolationException when brush is null

### ISSUE THREAD

**Issue by paulbartrum** [Microsoft/Win2D#229]
Passing null as the brush parameter to CanvasDrawingSession.DrawGlyphRun should throw an ArgumentNullException but instead throws a AccessViolationException ("attempt to read or write protected memory").

My scenario:

I'm using a ICanvasTextRenderer, and passing the supplied parameters through to DrawGlyphRun.  This is straight from the last paragraph of the doc page for [ICanvasTextRenderer](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Text_ICanvasTextRenderer.htm) (except that the doc page seems to link to the wrong method).

`null` gets passed through to ICanvasTextRenderer.DrawGlyphRun as the brush parameter, which makes sense since I didn't set any brush, custom or otherwise.  Passing that to CanvasDrawingSession.DrawGlyphRun is what fails, with no indication as to what went wrong.  Given that method has 12 parameters it took me a while to figure out what was going on!

**Comment by paulbartrum** [comment]
For illustrative purposes, my code looks like this:

```
using (var textFormat = new CanvasTextFormat())
using (var textLayout = new CanvasTextLayout(args.DrawingSession, "Test", textFormat, 100, 100))
{
  textLayout.DrawToTextRenderer(new CustomTextRenderer(args.DrawingSession), 0, 0);
}

private class CustomTextRenderer : ICanvasTextRenderer
{
  ... <snip constructor and other ICanvasTextRenderer methods> ...

  public void DrawGlyphRun(Vector2 point, CanvasFontFace fontFace, float fontSize, CanvasGlyph[] glyphs, bool isSideways, uint bidiLevel, object brush, CanvasTextMeasuringMode measuringMode, string localeName, string textString, int[] clusterMapIndices, uint characterIndex, CanvasGlyphOrientation glyphOrientation)
  {
    this.drawingSession.DrawGlyphRun(point, fontFace, fontSize, glyphs, isSideways, bidiLevel, brush as ICanvasBrush, measuringMode, localeName, textString, clusterMapIndices, characterIndex);
  }
}
```

**Comment by shawnhar** [comment]
Thanks for the report, we'll take a look.

Are you unblocked to get your app working by passing a non-null brush?

(we should certainly fix this to not throw AccessViolationException, just want to make sure you can move ahead in the interim)

**Comment by paulbartrum** [comment]
Yep, I'm unblocked now; no rush.

**Comment by shawnhar** [comment]
As of Win2D 1.14.0 (released today), passing null to CanvasDrawingSession.DrawGlyphRun now fails with a more suitable exception.

Thanks for the report!
