### ISSUE TITLE
Print to PDF doesn't write file until app is exited

### ISSUE THREAD

**Issue by jpobst** [Microsoft/Win2D#230]
When printing using Win2D using Windows 10's built in "Microsoft Print to PDF" or "Microsoft XPS Document Writer" the file is created but contains zero bytes until the printing app is closed.

Repro:
- Run Win2D Gallery from Windows Store
- Select Printing
- Press the Print button
- Choose PDF or XPS and hit Print
- Provide a filename
- Hit Save
- When it's done printing, try to open the file, it is zero bytes
- After closing the Win2D Gallery app, the file will get correctly written and can be viewed

This does not happen when using the regular UWP printing classes:
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Printing/cs

**Comment by shawnhar** [comment]
Thanks for the report!

What hardware, OS, and version of Example Gallery are you seeing this on?

On my Win10 laptop running the UWP version, I don't even get the UI to enter an output filename, which is definitely wrong but also curiously different from what you describe...

**Comment by jpobst** [comment]
Windows 10 Pro 64 bit
Core i7-2600K, 16 GB ram
I assume this is the UWP version, I downloaded it from the Windows Store after installing Windows 10.

My app, which has the same issue, is definitely UWP.

**Comment by damyanp** [comment]
Can you confirm the exact version number (eg version reported by Start->winver) please?  On my machine for example it is Version 1511 (OS Build 10586.29).

Thanks!

**Comment by shawnhar** [comment]
I can sort of repro this, although with slightly different symptoms:

1. The output files I see are not zero bytes while in the bad state, just not valid to open in other apps
2. I don't have to close Example Gallery to make the output good - the pdf becomes ok after the first GC after printing completes (GC can be triggered by viewing other examples, or using the Developer Tools menu)

**Comment by damyanp** [comment]
Yup, looks like I forgot to dispose or flush something.  I'll take a look.

**Comment by jpobst** [comment]
Version 1511 (OS Build 10586.36)

**Comment by shawnhar** [comment]
This is fixed in Win2D 1.14.0 (released today).  Thanks for the report!

**Comment by jpobst** [comment]
Confirmed fixed, thanks!
