### ISSUE TITLE
CanvasVirtualControl Threading

### ISSUE THREAD

**Issue by SebastianStehle** [Microsoft/Win2D#231]
Hi,
you mention in the documentation, that CanvasVirtualControl uses background rendering? Does it use an extra thread for rendering or is it always the UI Thread?

I've checked the thread id, and it is the same like the UI Thread, so I am not sure, if I need to think about concurrency issues.

**Comment by shawnhar** [comment]
CanvasAnimatedControl runs its game loop on a dedicated thread.  CanvasVirtualControl does not.

Where did you see this in the documentation?

**Comment by SebastianStehle** [comment]
I saw it here: http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_UI_Xaml_CanvasVirtualControl.htm

Under remarks. I just was not sure for 100%, thanks you for your answer, this makes live easy for me.

**Comment by shawnhar** [comment]
Ah, ok.  That text is trying to say that you /can/ do threaded rendering if you want to, not that this will happen by default.   We'll update that wording to make things more clear.

**Comment by shawnhar** [comment]
Win2D 1.14.0 (released today) improves the wording of these docs, and [adds more detail about how to do threaded rendering with CanvasVirtualControl](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_UI_Xaml_CanvasVirtualControl_CreateDrawingSession.htm).
