### ISSUE TITLE
angled gradient, possible?

### ISSUE THREAD

**Issue by tomzorz** [Microsoft/Win2D#233]
Hey

I'm trying to create an angled gradient brush (see attachment 1). Is this possible? I haven't managed to do it yet by transforming the current linear/radial brushes.

![angled gradient](https://cloud.githubusercontent.com/assets/6363312/12209605/6663a7ec-b654-11e5-976f-ffe8c8691a3f.png)

Thanks!

**Comment by clandrew** [comment]
I don't know how to accomplish this in Win2D using gradient brushes, it reminds me a bit of a freeform path gradient. 

You can get something similar, but not exactly like this, if you use a radial gradient brush with an OriginOffset that lies outside of the {Center, RadiusX, RadiusY) of the brush. Is that close enough?

Aside from that, an app could implement this itself using a custom pixel shader effect, but it would be significantly more work.

**Comment by tomzorz** [comment]
This is what I want to achieve with it:
![target](https://cloud.githubusercontent.com/assets/6363312/12210689/185f4242-b65c-11e5-87a1-c56fd4e0f946.png)

Right now I'm thinking about drawing the 2 halves separately and using 1-1 linear gradients to colorize OR pre-creating this as an image and using it as a mask. (Although I want to avoid using images if at all possible.)

**Comment by clandrew** [comment]
Using a pre-made image would definitely work, although I understand that it's preferable to have something generated at run-time.

There's another option, if your app is targeting Windows 10. 

You can use the GradientMesh feature to draw a wide variety of different types of gradients, including something very approximate to this. You can see what these look like in the GradientMesh example in Win2D Example Gallery. 

After a little futzing with it, I used it to produce this (below). Something generated programmatically would have a more regular shape.
![gradientmesh](https://cloud.githubusercontent.com/assets/8118775/12211819/c447d1ee-b618-11e5-981b-da5aa8fe2450.png)

**Comment by shawnhar** [comment]
I like the gradient mesh idea!

I think a precreated image mask could be a good solution for this.  You could load a single static bitmap with this gradient shape drawn from black to white, and run that through a ColorMatrixEffect to get arbitrary colors without needing a separate bitmap for each one.

Thanks to linear interpolation, the image could be quite low resolution, and scaled up to whatever size is needed  (smooth gradients scale extremely well).   I bet even just a 16x16 mask would look pretty good.

**Comment by tomzorz** [comment]
I'm not sure about the 16*16 mask, as I need a very sharp edge between the visible and the invisible side. But I'll try the gradient mesh idea, thanks! :)

**Comment by clandrew** [comment]
Glad this helped! I'll close this, feel free to get in touch if you have any other questions.

**Comment by 13thsymphony** [comment]
I think what Shawn is suggesting is that you use the upscaled gradient image (+ color matrix effect) as the source to an image brush, and then use that to fill in circle geometry of your choice. The sharp edges are preserved (since you are using regular geometry), but the actual colors that are used to fill them in will still look good because of the nature of the gradient and linear interpolation.

**Comment by tomzorz** [comment]
I managed to do it with the gradient mesh, and it turned out quite cool! :)

Inspiration: http://gfycat.com/AptClassicHake
Win2D version: https://gfycat.com/YoungPlainGrub

In case someone's interested I uploaded the source here: https://github.com/tomzorz/Win2D_fun/blob/master/Win2d_circling/Win2d_circling/MainPage.xaml.cs

**Comment by shawnhar** [comment]
What a cool looking effect!

I'm glad to see you got this working.

**Comment by clandrew** [comment]
Awesome, this is really neat!

**Comment by JohnnyWestlake** [comment]
Nice effect! Just random musings, but given CanvasPathBuilder and CanvasGeometry are disposable, it might be worth using them inside a using statement in your draw event? CreateLayer is also pretty performance intensive and really hammers performance on the phone / underpowered devices, so it might be interesting to see if there's another way of replicating the effect?

**Comment by tomzorz** [comment]
Thanks for the suggestions! The first two I'll try definitely, but I don't see a way around the 3rd thing right now - if someone does please enlighten me :)
