### ISSUE TITLE
Threshold / falloff effect?

### ISSUE THREAD

**Issue by tomzorz** [Microsoft/Win2D#234]
Hi again,

I'm looking for a way to produce a threshold / falloff effect with combining the built-in ones. I tried doing it with the linear/table transform ones but I haven't succeeded so far. (I want to render 2D metaballs without manually calculating / drawing each pixel.)

Thanks!

**Comment by shawnhar** [comment]
Can you please give more detail about what you are wanting this effect to do? 'threshold' is a heavily overloaded term that can mean quite different things...
________________________________

**Comment by tomzorz** [comment]
Sure :)

I tried to follow this article describing how to do it in xna: http://nullcandy.com/2d-metaballs-in-xna/

Quoting the relevant parts: 

> To produce metaballs, you create a function, f(x, y), that becomes smaller as you get further from the metaball.  This is your falloff function.  It determines how strong the influence of the metaball is at any given point.  Next, you sum all the falloff functions from all the metaballs.  Any point that has a value greater than some threshold is part of the metaballs.

This description above assumes that I calculate this manually for every pixel - instead I tried to mimic this by drawing circles filled with radial gradients (transparent at the edge) and than applying an effect. Question is: what effect(s) can I use to replicate this?

**Comment by shawnhar** [comment]
There are several steps involved in rendering metaballs - I'm not clear which part you are stuck on?

Once you have the combined image produced using additive blending, TableTransferEffect would be a good way to keep only the brighter areas while sending lower values all the way down to zero.  It remaps color values through an arbitrary lookup table, so can apply any function you desire.

**Comment by tomzorz** [comment]
Ok I think I figured out where I went wrong: I had the TTE table look like this instead of a hard 0 -> 1 transition:
![ttt](https://cloud.githubusercontent.com/assets/6363312/12221437/15640b46-b79b-11e5-8662-0a66b2fc3001.png)
