### ISSUE TITLE
Maximum text lines

### ISSUE THREAD

**Issue by Opiumtm** [Microsoft/Win2D#235]
How to limit maximum drawn lines in CanvasTextLayout?
Not clipping rect, but limit maximum lines of text in text wrapping mode.

**Comment by shawnhar** [comment]
There is no direct feature to do that in CanvasTextLayout.

You could create a layout, look at LineMetrics to see how much text fit into the lines you wanted, then create another layout including only that portion of the text.

**Comment by clandrew** [comment]
+1. 
If you wanted to avoid creating a second layout, you could adjust the RequestedSize to have only have enough height for a certain number of lines. An app can work out what this height is, through the LineMetrics field.

**Comment by shawnhar** [comment]
Closing issue as I believe this question has been answered.  Feel free to reactivate if you need further info!
