### ISSUE TITLE
Subscript and superscript text

### ISSUE THREAD

**Issue by Opiumtm** [Microsoft/Win2D#236]
How to draw a subscript and superscript text in CanvasTextLayout?
There is FontiSize, but no option to place text above or below baseline

**Comment by clandrew** [comment]
One way is to apply a superscript or subscript typography option to the text using SetTypography.

For example, to set the first character:
```
            var typography = new CanvasTypography();
            typography.AddFeature(CanvasTypographyFeatureName.Superscript, 1);
            textLayout.SetTypography(0, 1, typography);
```

The one caveat of this is that the font needs to support superscript/subscript OpenType features.

For example, Segoe UI supports numeric subscripts and superscripts. Cambria Math supports superscripts.

Another option, if you don't want to know about whether the font supports subscript or superscript OpenType features, is to use Unicode superscript/subscript glyphs, and Win2D's font-fallback will pick a font that can draw them.

**Comment by Opiumtm** [comment]
No, I need arbitrary character subscript/superscript support for a Segoe UI font, not just mumeric ones. It's because social app I'm working, social service support subscripts/superscripts in the text markup. When it rendered on HTML - It's OK, but when it comet to XAML mobile application, method to correct draw this social service text markup is needed.

**Comment by clandrew** [comment]
Unfortunately, because arbitrary superscripting/subscripting aren't a built-in feature of DirectWrite, they are not a feature of Win2D. DirectWrite doesn't contain everything you need for full HTML text support. It gives you the building blocks with which to do it.

To accomplish totally arbitrary subscript/superscript, regardless of whether the font+glyph combo supports that OpenType feature, an app can use a custom text renderer. To do it, implement ICanvasTextRenderer and draw text to that. In the DrawGlyphRun handler, adjust the values of fontSize and point, and pass everything else as-is along to DrawingSession.DrawGlyphRun.

**Comment by clandrew** [comment]
Since there isn't an action for us to take, I'll close this issue, but definitely feel free to re-open if you need anything else.

**Comment by hcoona** [comment]
This is quite a common requirement. Why leave it to our users although there are no built-in support in Direct2D/DirectWrite?
I suggest implement this feature for arbitrary fonts. Otherwise, the users have to implement it again and again.

**Comment by clandrew** [comment]
In general, we try hard to avoid adding things that aren't in the underlying Direct2D/DirectWrite API set- keeping Win2D as much of a *thin wrapper* as possible, but I definitely see where you're coming from that this seems like an odd limitation- indeed I was pretty surprised when I found that out about DWrite too, at first.

Thanks for your suggestion. It does help to know how many people are hitting limitations in Win2D. When something is hit often enough, it becomes more likely that we'll be okay with violating the '*thin wrapper*' idea, and adding something supplemental to help. For now, if we do something like this, it's more likely something we'll add as a sample. 

I'll re-open this issue and tag it to indicate there's something to do here.

**Comment by shawnhar** [comment]
We added a sample showing one way to implement general purpose superscript and subscript rendering:

https://github.com/Microsoft/Win2D-Samples/blob/master/ExampleGallery/Shared/SubscriptSuperscript.xaml.cs

**Comment by hcoona** [comment]
This helps a lot, thank you!
