### ISSUE TITLE
How to reload some resource asynchronously

### ISSUE THREAD

**Issue by zumicts** [Microsoft/Win2D#239]
Perhaps there should be a reload resource method in the control?

In my scenario I need to reload some resource asynchronously and that is impossible in the draw method alone.

**Comment by SebastianStehle** [comment]
The purpose of the CreateResource method is to load as much resources as possible at the startup and to handle device lost events, I dont understand why you want to call it multiple times.

To load resources asynchronously I use something like the following pattern:

	class Win2DIcon
	{
		public CanvasBitmap Bitmap;
		
		public Win2DIcon(CanvasControl control, string url)
		{
			LoadAsync(control);
		}

		private async Task LoadAsync(CanvasControl control, string url)
		{
			 Stream stream = await DownloadImage(url);
			 
			 Bitmap = await CanvasBitmap.LoadAsync(device, ));
			 
			 control.Invalidate();
		}	
	}

	class Win2DIconCache
	{
		private Dictionary<string, Win2DIcon> icons = ...;
		
		public Win2DIcon GetIcon(CanvasControl control, string url)
		{
			return icons.GetOrAdd(url, () => new Win2DIcon(control, url));
		}
	}


	// Render

	Win2DIcon icon = cache.GetIcon(control, url);

	if (icon.Bitmap != null)
	{
	   // Draw Bitmap
	}

It caches all resources and loads them asynchronously. When they are loaded I render the scene again. When the device is lost I dispose all bitmaps and clear the cache, with the next call all icons get loaded again.

**Comment by zumicts** [comment]
I'm using the canvascontrol to create an iOS live blur effect. Everytime the layout is updated I would like to render the target element.

**Comment by shawnhar** [comment]
You might find these docs useful:  http://microsoft.github.io/Win2D/html/LoadingResourcesOutsideCreateResources.htm

**Comment by zumicts** [comment]
Yeah.. trying to call LoadAsync anywhere besides in the Draw and CreateResource events throws an exception.

Even then, I would really just like to only render the elements when the Draw method is called. Any way to make Draw asynchronous or add a TrackAsyncAction to the event args?

**Comment by shawnhar** [comment]
Note however that if by "render the target element again" you mean using a XAML RenderTargetBitmap, you don't actually need anything involving asynchronous Win2D resource creation to achieve that.  Use standard async operations (not touching Win2D at all) to do your XAML rendering and read back the pixel bytes, then call Invalidate on your Win2D control only once you have this data ready to draw.

**Comment by zumicts** [comment]
That was what I originally implemented but debugging I found out how draw isn't called all the time (uses the refresh rate) and wanted to avoid rendering more times than needed.

**Comment by shawnhar** [comment]
Closing issue as I believe the question has been answered.  Feel free to reactivate if you have further questions after reading the Win2D docs linked above.
