### ISSUE TITLE
Add support for opacity mask effect

### ISSUE THREAD

**Issue by dajbych** [Microsoft/Win2D#24]
Please add support for Opacity Mask effect.

**Comment by JohnnyWestlake** [comment]
I'd personally request putting Layers infront of Geometry (though that's only because I have a pressing need to use Opacity Masking  soon)

**Comment by shawnhar** [comment]
We're planning to start work on layers in our current sprint, so should have something for you approximately 2 weeks from now.

**Comment by shawnhar** [comment]
This feature is available in the latest version.

**Comment by venetasoft** [comment]
@shawnhar where can I find the mask feature...? I cannot see it :S... Thanks

**Comment by damyanp** [comment]
This is exposed through [CreateLayer](http://microsoft.github.io/Win2D/html/Overload_Microsoft_Graphics_Canvas_CanvasDrawingSession_CreateLayer.htm).

**Comment by shawnhar** [comment]
There are also overloads of FillRectangle and FillGeometry that use an opacity mask:

http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasDrawingSession_FillRectangle_4.htm

http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasDrawingSession_FillGeometry_1.htm

**Comment by venetasoft** [comment]
Lots of ways indeed, thank you very much to all :) !!!
