### ISSUE TITLE
How to clear pixels in a rectangle like HTML5 canvas's function clearRect()?

### ISSUE THREAD

**Issue by Neilxzn** [Microsoft/Win2D#240]
I've tried this function  to clear rectangular pixels,
" args.DrawingSession.FillRectangle(20, 20, 200, 200, Colors.Transparent);"But it doesn't work?

**Comment by clandrew** [comment]
When using a transparent brush to fill geometry, it works differently than that. 

It will blend the transparent brush, using a "source-over" operation against the background, and that has no effect. Source-over is a very good default for a wide variety of cases, but it won't "subtract" transparency like that. A Copy blend mode will do it.

To 'clear out' pixels of your rendertarget to transparent, you can set the drawing session's Blend property to Copy. Then, fill using your transparent brush.

**Comment by Neilxzn** [comment]
It works!! thank you for your answer.

**Comment by clandrew** [comment]
No problem!
