### ISSUE TITLE
Text ending with ellipsis

### ISSUE THREAD

**Issue by dajbych** [Microsoft/Win2D#241]
Can the *Microsoft.Graphics.Canvas.CanvasDrawingSession.DrawText* method render a text ending with the ellipsis (three dots) when the text is clipped? I want to achieve the same behavior like the *System.Windows.Controls.TextBlock* when the *TextTrimming* property is set to *System.Windows.TextTrimming.WordEllipsis* or *System.Windows.TextTrimming.CharacterEllipsis*.

**Comment by clandrew** [comment]
Yes, it can do that. To enable it, draw the text with a CanvasTextFormat with its [TrimmingSign](http://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_Text_CanvasTextFormat_TrimmingSign.htm) property set to Ellipsis.

**Comment by dajbych** [comment]
Thank you. I misunderstood *TrimmingDelimiter*.

**Comment by clandrew** [comment]
Glad this helped.
