### ISSUE TITLE
Win10 desktop version

### ISSUE THREAD

**Issue by patsv** [Microsoft/Win2D#242]
Hi, I am developing some map software using Open Streetmap data an render tiles using Win2D on the phone as an Universal App..
I have also a tile rendering factory on a 64bit windows WPF appliaction using WPF, I would like to use the same Win2D rendering code in the factory but I could not find any version of Win2D that works on Win10 desktop 64 bit, the Win8.1 is too old.
Is this something that you considering to fix?
// Patrik

**Comment by clandrew** [comment]
Thanks for this question.

Win2D is implemented as a Windows Runtime component, and it's for apps that use the Windows Runtime platform. For example: Windows 8.1 store apps, Windows 8.1 phone apps, and apps using the Windows 10 Universal App platform. This design is really fundamental to how Win2D works, as well as how the API gets exposed in .NET and C++. 

Both the Win8.1 version and the Win10 version of Win2D are Windows Runtime components. 

So, Win2D isn't available for desktop apps today; changing that isn't part of our roadmap.

**Comment by patsv** [comment]
OK, sorry to hear about that.
It would have been nice to have the same code, I have to use 64 bit (OSM get's very big) and in another related project I use an SQL database which is not supported in UWP.
But I understand that you want to  keep it together.
Keep up the good work.

**Comment by clandrew** [comment]
Yeah, although Win2D can certainly be used to build 64-bit apps, it does require the Windows Runtime platform. 
Thank you for your understanding, and will do!

**Comment by fobrs** [comment]
See issue #734
