### ISSUE TITLE
Load resources on the fly

### ISSUE THREAD

**Issue by FredericColin** [Microsoft/Win2D#245]
Hello Win2D team,

I'm a little bit stuck on this subject. I wonder what's the best way to dynamically load resources on the fly when needed.

Indeed "CreateResources" event is loaded once at the very beginning before the draw, but I can't use it since I need to load about 600 MB of images. I would prefer load them only when needed and when I invalidate the canvas control.

What's the best way to  achieve it?

Thanks for your feedback.

Fred

**Comment by shawnhar** [comment]
This article may be useful:  http://microsoft.github.io/Win2D/html/LoadingResourcesOutsideCreateResources.htm

**Comment by shawnhar** [comment]
Closing as I think this has been answered.  Feel free to reactivate if you have further questions.
