### ISSUE TITLE
Offscreen render on Windows 10 mobile renders empty image

### ISSUE THREAD

**Issue by Sebosek** [Microsoft/Win2D#246]
Hello,

I'm trying to render image into file by offscreen render with transparent background, but final image is empty - in Windows explorer black, in Photoshop transparent; but code what I'm using works on Windows 10 like a charm. Can you give me some suggestions where would be an error?

    /// <summary>
    /// Save note into image
    /// </summary>
    private async Task SaveToImage(string id, InkStroke stroke, float width, float height)
    {
        CanvasDevice device = CanvasDevice.GetSharedDevice();
        var dpi = DisplayInformation.GetForCurrentView();

        // compute boundaries
        var strokeX = stroke.BoundingRect.X < 0 ? 0 : stroke.BoundingRect.X;
        var strokeY = stroke.BoundingRect.Y < 0 ? 0 : stroke.BoundingRect.Y;

        var strokeW = stroke.BoundingRect.X < 0 ?
            Math.Ceiling(stroke.BoundingRect.Width - stroke.BoundingRect.X) + OffsetAntialise :
            Math.Ceiling(stroke.BoundingRect.Width) + OffsetAntialise;
        var strokeH = stroke.BoundingRect.Y < 0 ?
            Math.Ceiling(stroke.BoundingRect.Height - stroke.BoundingRect.Y) + OffsetAntialise :
            Math.Ceiling(stroke.BoundingRect.Height) + OffsetAntialise;

        // Check for overflow on width and height
        if (stroke.BoundingRect.X + strokeW > width)
        {
            var x = (strokeX + strokeW) - width;
            strokeW = strokeW - x;
        }

        if (stroke.BoundingRect.Y + strokeH > height)
        {
            var y = (strokeY + strokeH) - height;
            strokeH = strokeH - y;
        }

        using (CanvasRenderTarget offscreen = new CanvasRenderTarget(device, width, height, dpi.LogicalDpi))
        {
            using (CanvasDrawingSession ds = offscreen.CreateDrawingSession())
            {
                ds.Clear(Colors.Transparent);
                ds.DrawInk(new InkStroke[] { stroke });
            }

            StorageFolder folder = await GetNotesFolder();
            StorageFile file = await folder.CreateFileAsync(id + ".png", CreationCollisionOption.ReplaceExisting);

            using (IRandomAccessStream output = new InMemoryRandomAccessStream())
            {
                await offscreen.SaveAsync(output, CanvasBitmapFileFormat.Png);
                var cropped = await ImageManipulator.GetCroppedBitmapAsync(output, new Point(strokeX, strokeY), new Size(strokeW, strokeH), 1);
                BitmapDecoder decoder = await BitmapDecoder.CreateAsync(output);

                using (IRandomAccessStream stream = new InMemoryRandomAccessStream()) // await file.OpenAsync(FileAccessMode.ReadWrite)
                {
                    BitmapEncoder encoder = await BitmapEncoder.CreateAsync(BitmapEncoder.PngEncoderId, stream);
                    Stream pixelStream = cropped.PixelBuffer.AsStream();
                    byte[] pixels = new byte[pixelStream.Length];
                    await pixelStream.ReadAsync(pixels, 0, pixels.Length);

                    encoder.SetPixelData(
                        BitmapPixelFormat.Bgra8,
                        BitmapAlphaMode.Straight,
                        (uint)cropped.PixelWidth,
                        (uint)cropped.PixelHeight,
                        decoder.DpiX,
                        decoder.DpiY,
                        pixels);
                    await encoder.FlushAsync();

                    stream.Seek(0);
                    var b = new byte[stream.Size];

                    using (var dr = new DataReader(stream))
                    {
                        await dr.LoadAsync((uint)stream.Size);
                        dr.ReadBytes(b);
                    }

                    // save image into file
                    await StorageUtils.WriteProtectedData(folder, id + ".png", b);
                }
            }
        }
    }

**Comment by damyanp** [comment]
It looks like this code saves to a stream using CanvasRenderTarget.SaveAsync, and then does some further manipulation by loading this stream and saving it using BitmapEncoder.

Is that correct?

Have you isolated which part of this is going wrong?  Is it the CanvasRenderTarget save that is failing you, or the BitmapEncoder save?

**Comment by clandrew** [comment]
Thanks for this report.
Could you clarify what you mean by 
"but code what I'm using works on Windows 10 like a charm"

Does this work correctly on Windows 10, but fail (draw transparent) on Windows 8.1?  Or just fail regardless?

**Comment by shawnhar** [comment]
How is this different from your earlier issue #202?

**Comment by shawnhar** [comment]
Closing issue as it's been a week and we have not heard back with the requested information.
