### ISSUE TITLE
CanvasGeometry.ComputePointOnPath overloads

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/Win2D#248]
Hey folks,

So I'm implementing this sample in Win2D:
https://code.msdn.microsoft.com/windowsapps/Animating-Text-on-a-Path-883382a0

Going somewhat well (just a small bit confused between mapping D2D/DW types to Win2D - curious as to why GlyphRun isn't a Win2D type?)

There's a particular block of code that's important (from what I can work out) to help rotate / layout the text properly (PathTextRenderer.cpp, line 124)
```
              DX::ThrowIfFailed(
                dc->geometry->ComputePointAtLength(
                    midpoint,
                    D2D1::IdentityMatrix(),
                    &offset,
                    &tangent
                    )
                );
```

But the "offset" property is never exposed in Win2D's corresponding CanvasGeometry.ComputePointOnPath overloads - perhaps I'm being daft and there's a good reason for this so, is there a reason for this / will this offset get exposed at any point, or should I go about this in a different way? (I can easily add the offset property myself but ideally I don't always want to be maintaining my own fork)

Thanks,

**Comment by shawnhar** [comment]
CanvasGeometry.ComputePointOnPath directly returns the computed point, which is why you aren’t seeing this as an out parameter.

**Comment by JohnnyWestlake** [comment]
Thanks! Knew I was probably missing something obvious! It now ends up that my glyphs are oddly spaced, but probably something up with my code rather than Win2D - I'll poke around a bit trying to fix that. Thanks!

 ![Image](http://i.imgur.com/C5VDznh.png)
