### ISSUE TITLE
Crash when using multiple CanvasControls inside Panel/ItemsControl

### ISSUE THREAD

**Issue by r2d2rigo** [Microsoft/Win2D#249]
Hello,

I'm having problems with a very specific issue using `CanvasControl`; I'm using it inside the `ItemTemplate` of a `GridView`, so I end having between 20 and 30 of them on the same page (however, I reproduced the crash too by having the same amount of individual `CanvasControl`s inside a `StackPanel`). The problem is that it triggers an application crash under really specific conditions that make it really difficult to debug.

Specific conditions:
-The page containing the `CanvasControl`s must have `NavigationCacheMode = NavigationCacheMode.Required` (`Enabled` should make it fail too under the correct circumstances?).
-The app must be run without the debugger attached.
-The app must be run on phone or tablet mode.

Things that make no difference:
-Changing the value of `UseSharedDevice` doesn't fix it.
-Specifying a callback for `CreateResources`/`Draw` doesn't affect it.

How to reproduce:
-Compile attached project (Release makes it fail more commonly, but enabling .NET Native is not necessary).
-Deploy it to a phone device or a tablet one that is capable of running on tablet mode.
-Run the app and tap on one of the `GridView` items.
-You will be taken to another page, tap on the button for opening a external web browser.
-Wait a bit (sometimes even 5-10 seconds is enough).
-Return to the app.
-Try returning to the main page of the app.
-The app will crash.
-Looking at Event Viewer  says that the app indeed crashed, and the problem happened in Windows.UI.Xaml.dll.

I have been experiencing this since 1.3.0 and thought that maybe it was fixed in a later update - still happens on 1.14.0. The worst thing is that it never happens with a debugger attached, so trying to trace it is really difficult.

Please see the attached file for a repro project.

[Win2DGridViewCrash.zip](https://github.com/Microsoft/Win2D/files/103472/Win2DGridViewCrash.zip)

**Comment by damyanp** [comment]
Thanks for the minimal repro - as there's pretty much no code behind here one would expect this to work!

I have managed to repro this once on a 640 running 10586.36, but it took me many attempts to do so and I haven't managed to since.  Is that consistent with what you're seeing?  Or are you able to make this happen 100% of the time?  I want to be sure that I'm looking at exactly the same thing that you are.

Some more questions:

* Can you clarify the mechanism by which you "Return to the app".  Do you mean "After going to the web browser press the back button".  Or some other way?
* Have you seen this with Win2D version 1.2.0?  ie are you suggesting that some change between 1.2.0 and 1.3.0 introduced this issue?
* Does replacing the CanvasControls with a XAML Image (with an image loaded) make the problem go away?

Thanks!

**Comment by r2d2rigo** [comment]
@damyanp thanks for the quick reply! Here is some insight:

-No, in my case it crashes almost always - >75% of the times.
-Yeah, by "return to the app" I meant to use the back button to go back to the previous app from the recently opened internet browser.
-Project used 1.3.0 from the start, haven't used previous versions of the library.
-Problem only happens with `CanvasControl` inside the `GridViewItem`s.

In my case it happens very frequently on a Lumia 930 running 10240 and a Linx 8 running 10586. Another user reported that he was unable to reproduce it on a Lumia 950 running 10586.63 but happened at random intervals on a Surface Pro on 10586.63.

**Comment by KooKiz** [comment]
[win2dcrash.zip](https://github.com/Microsoft/Win2D/files/103690/win2dcrash.zip)

I have a crash dump (reproduced on a Surface Pro 4, with build 10586.63, after a few tries)

The callstack seems to show the crash is related to Direct2D:

045c8844 04ee22d3 windows_ui_xaml!CSurfaceImageSource::BeginDrawWithD2D+0x8c
045c8848 050d969d windows_ui_xaml!DirectUI::SurfaceImageSource::BeginDrawWithD2D+0x7d
045c884c 050d9608 windows_ui_xaml!DirectUI::SurfaceImageSource::SurfaceImageSourceWithD2D::BeginDraw+0x38
045c8850 0a5419ad microsoft_graphics_canvas+0x419ad

Not sure if microsoft_graphics_canvas is Win2D. In any case, I'm missing the symbols for that part.

Hope that helps.

**Comment by damyanp** [comment]
@KooKiz - awesome, thank you!  I'll take a look at this.

**Comment by damyanp** [comment]
Thanks, that crash dump is very useful.  XAML is reporting E_SURFACE_CONTENTS_LOST (error code is 0x802b0020). I suspect it is incorrectly reporting this - we ran into a case where it would do this with VirtualSurfaceImageSource.  We have a workaround for this (43b1ef5afcfd27825ad20ee055c7047641370fd3) but it seems that we need to do a similar workaround for SurfaceImageSource.

**Comment by damyanp** [comment]
A fix for this should be in 1.15.  Thanks for bringing it to our attention!

**Comment by shawnhar** [comment]
This is fixed in Win2D 1.15.0 (which was released today)
