### ISSUE TITLE
[question] Can I use Win2D in pure C++?

### ISSUE THREAD

**Issue by petke** [Microsoft/Win2D#250]
Hi. 

Do you support C++, or only C++/CX?

I believe most C++ programmers will not accept a non standard extension to C++ like C++/CX.

If I understand correctly this library: "http://moderncpp.com/" is an attempt to allow access to the  Windows Runtime from a pure C++ library. Maybe one can use it somehow with Win2D? Has anyone tried, or got some advice on this topic?

Thanks /Petke

**Comment by damyanp** [comment]
Win2D is a WinRT API and can be used from native C++.  Currently, the easiest way to use a WinRT API is via C++/CX.  However, you can also use WRL which is a template library that makes some of the WinRT housekeeping easier.  Win2D is actually implemented using WRL, but beware that using WinRT APIs via WinRT is significantly more verbose than via C++/CX.

**Comment by shawnhar** [comment]
Closing as I think this has been answered.  Feel free to reactivate if you have further questions.
