### ISSUE TITLE
How to control CanvasControl width dynamically?

### ISSUE THREAD

**Issue by hholhjem** [Microsoft/Win2D#251]
I have tried to set width of my XAML CanvasControl dynamically in a UWP app by setting Width to "Auto" or "*" using Width or ColumnDefinition.

No matter what i try CanvasControl.ActualWidth and CanvasControl.Size.Width is always zero and I reckon that is why nothing is being drawn up.

If I set width to a defined pixel value, like 320 everything runs okay and images is getting drawn as expected. But when trying the app on different screens I see that I need to find out how this can be controlled dynamically based on the actual screen width of the device.

How can I control the width dynamically?

Tips appreciated! Thanks!

**Comment by shawnhar** [comment]
You need to put the CanvasControl inside one of the XAML layout controls (Grid, StackPanel, etc) which will provide whatever dynamic sizing behavior you configure the layout control for.

More info about layout in XAML: https://msdn.microsoft.com/en-us/library/windows/apps/mt228350.aspx?f=255&MSPPError=-2147217396

And see Example Gallery code for many concrete examples.

**Comment by hholhjem** [comment]
Solved! :) The problem was my HorizontalAlignment="Center" attribute. When I removed the attribute, the width was supplied correctly.

Old code

	<Grid Width="Auto">
		<canvas:CanvasControl Draw="CanvasControl_Draw" 
							  CreateResources="CanvasControl_CreateResources"  
							  ClearColor="White"
							  Margin="0,0,0,0"
							  HorizontalAlignment="Center"/>
	</Grid>

**Comment by shawnhar** [comment]
Hurrah!
