### ISSUE TITLE
How can I create bitmap from memory buffer

### ISSUE THREAD

**Issue by Dylan-H** [Microsoft/Win2D#253]
thanks

**Comment by shawnhar** [comment]
Depending on what you mean by memory buffer, try one of:

http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasBitmap_CreateFromBytes.htm

http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasBitmap_CreateFromBytes_3.htm

http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasBitmap_CreateFromColors.htm

**Comment by Dylan-H** [comment]
@shawnhar  hello， I'm get a  char*  buff  in c++ ,  and the buff is  jpeg fromat. I want to paint with win2d.

**Comment by shawnhar** [comment]
If your data is encoded in an image format such as .jpg, you will need to use CanvasBitmap.LoadAsync to decode it.  Wrap a memory stream around your buffer, and then call one of the LoadAsync overloads that takes a stream parameter.

**Comment by shawnhar** [comment]
Closing as I believe this has been answered - feel free to reactivate if you have further questions.

**Comment by ngobk15** [comment]
Hello shawnhar,
I am newbie with window component runtime development and found several new things.
As I am now has a char* buffer from native C++ and want to display this buffer on Win2D/ CanvasControl (with DrawImage API), please help to give me the guide to do that.
Thank you very much~

**Comment by Dylan-H** [comment]
@ngobk15 Hello
`InMemoryRandomAccessStream^ memoryStream = ref new InMemoryRandomAccessStream();
			DataWriter^ datawriter = ref new DataWriter(memoryStream->GetOutputStreamAt(0));
			datawriter->WriteBytes(ref new Platform::Array<unsigned char>((unsigned char*)data, len));
			auto rw = create_task(memoryStream->WriteAsync(datawriter->DetachBuffer()));
			.then([memoryStream](){

			 return create_task(BitmapDecoder::CreateAsync(memoryStream));
}).then([](BitmapDecoder^ bd)
			{
				return create_task(bd->GetSoftwareBitmapAsync(BitmapPixelFormat::Bgra8, BitmapAlphaMode::Premultiplied));
			}).then([](SoftwareBitmap^ sb){
CanvasBitmap^ cbmp = CanvasBitmap::CreateFromSoftwareBitmap(g,sb);
g->DrawImage(cbmp, rect, Rect(0, 0, cbmp->SizeInPixels.Width, cbmp->SizeInPixels.Height));
});`

**Comment by ngobk15** [comment]
Hello @Dylan-H,
Is there any method that can use the native array directly? As I saw, your code need to copy the native array to Stream (doesn't it?), which can cause performance problem with large array as I think

**Comment by Dylan-H** [comment]
@ngobk15  I'm sorry, my English is not very good
the performance problem   I also considered，but I can't find other ways to draw char*   use win2d

**Comment by shawnhar** [comment]
The approach Dylan-H shared is suitable if your data is some image file format (.png or .jpg) that needs to be decoded.  It could be simplified a bit by passing the stream directly into CanvasBitmap.LoadAsync - there's no need for a BitmapDecoder or SoftwareBitmap in here.

If your data is already decoded into raw pixel values (eg. an array of colors) you can use CanvasBitmap.CreateFromBytes (or CanvasBitmap.SetPixelBytes to change the contents of an existing bitmap).  You can use Platform::ArrayReference to call these methods without any extra data copying.

**Comment by Dylan-H** [comment]
@ngobk15       shawnhar  give me an idea  , you can use the native function  to decode the  char*  and 
use the  CanvasBitmap.CreateFromBytes  to create a CanvasBitmap

**Comment by ngobk15** [comment]
Hello,
Yesterday, I tried to use this API. But our buffer is "unsigned char*"
type, and the API needs "System.Byte[]" type. I search from google, and
found that, the only way to make the Byte[] from unsigned char* is copy
pixel-to-pixel. Do you have any tips for me in this case?
Vào 12-03-2016 09:14, "Dylan-H" <notifications@github.com> đã viết:

**Comment by pleaseking** [comment]
Just stepping in here - the way we did it was to use a custom IBuffer implementation (C++, WRL) around our own char* buffer. This means zero copying and no overhead. I can post the code if needed.. I think ArrayReference does the copying - but not sure.

**Comment by shawnhar** [comment]
For passing array data from C++/CX into a WinRT API, Platform::ArrayReference is your friend.  IBuffer works too, but ArrayReference is usually simpler.

When returning array data from WinRT to C++/CX, IBuffer is the most efficient approach.

**Comment by ngobk15** [comment]
Thanks for help me alot,
Follow your guide, I changed my code to :
Platform::ArrayReference blobArray((unsigned char*)mNativeBitmap>GetBuffer(), mBitmapWidth * mBitmapHeight * 4);
IBuffer^ ibuffer = CryptographicBuffer::CreateFromByteArray(blobArray);
mCanvasBitmap = CanvasBitmap::CreateFromBytes(mCanvasControl, ibuffer, mBitmapWidth, mBitmapHeight, DirectXPixelFormat::A8UIntNormalized);
