### ISSUE TITLE
"Geometry" dry ink crashes the Win2D Example Gallery

### ISSUE THREAD

**Issue by rick-man** [Microsoft/Win2D#254]
Looks like there might be an issue with the "geometry" ink drying code in the Win2D Example Gallery. (I'm running a development build of Win10.)

Repro steps:
1. Launch Win2D Example Gallery.
2. Choose the Ink example, and set the "Dry Ink Rendering" drop-down to "Geometry".
3. Draw a stroke.

Result: The app crashes. I could repro this on several different devices.

**Comment by shawnhar** [comment]
I don't see this.  What version of Win2D and Example Gallery are you using?

**Comment by rick-man** [comment]
I'm using the Win2D Example Gallery that I just downloaded from the Windows Store. I'm running on build 14254.

**Comment by 13thsymphony** [comment]
I also see the crash on my system, build 11104 on public Example Gallery in the store.

**Comment by damyanp** [comment]
I see it on 10586.63...

**Comment by shawnhar** [comment]
Interesting – it only crashes in release builds.  Something about passing the result of a Linq groupby query directly into CanvasGeometry.CreateInk.  If I call ToList() on the Linq IEnumerable first, there is no crash.

Thanks for the report!

**Comment by shawnhar** [comment]
This is fixed in Win2D 1.15.0
