### ISSUE TITLE
Retained mode

### ISSUE THREAD

**Issue by Bortxx** [Microsoft/Win2D#277]
Is there a retained mode in Win2D like in WPF? If not what is the equivalent in UWP? For example how to render a XAML DrawingGroup.

**Comment by clandrew** [comment]
Thanks for this question. Win2D is designed to be an immediate-mode API. It doesn't have a retained mode.

In some cases, grouping together commands in a [CanvasCommandList](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasCommandList.htm) may do the trick.

**Comment by Bortxx** [comment]
Does UWP have a good performing retained mode? WPF does.

**Comment by shawnhar** [comment]
Win2D team are far from being experts in XAML, but I'm not aware of any direct equivalent of the WPF DrawingGroup.  XAML provides retained mode drawing via the Windows.UI.Xaml.Shapes namespace, or as clandrew points out, you could build your own high performance retained mode system on top of the immediate mode Win2D drawing APIs.
