### ISSUE TITLE
CanvasVirtualControl has a limit size ?

### ISSUE THREAD

**Issue by ErwanJes** [Microsoft/Win2D#281]
When we set a new height to ~16K (including dpi) to a CanvasVirtualControl, the application crash in `CanvasSwapChain::ResizeBuffersWithWidthAndHeightAndDpi` :

```
ThrowIfFailed(swapChain->ResizeBuffers(
            bufferCount, 
            widthInPixels,
            heightInPixels,
            static_cast<DXGI_FORMAT>(newFormat), 
            0));
```

I tried it with the VirtualControlExample in ExampleGallery, the height can be set to a much higher value without any issues, but I don't see why there is a difference.

Is there a limit size for the CanvasVirtualControl ? Is there anything which can impact the limits ?

I have seen this link : https://msdn.microsoft.com/en-us/library/windows/apps/hh702054.aspx but 17M pixels should be more than enough.

**Comment by shawnhar** [comment]
Something odd is going on here because CanvasVirtualControl does not use a swapchain.  If you are seeing a crash in CanvasSwapChain, you must not actually be using a CanvasVirtualControl.  Or maybe you inadvertently create multiple controls of different types?

**Comment by ErwanJes** [comment]
We have several CanvasVirtualControl and 1 CanvasAnimatedControl which seems to cause the issue.
Thanks !
