### ISSUE TITLE
Exception in building package

### ISSUE THREAD

**Issue by Xatrix31** [Microsoft/Win2D#283]
Hello.
I got an exception when I tried to build this package. How to solve it? I have VS 2015 Update 1. 

> Merging intellisense for Microsoft.Graphics.Canvas
EXEC : error : Failed to find a part of the path "c:\Users\xatri\Surce\Repos\Win2D\obj\docs\docsrc\Transform3DEffect.xml". [c
:\Users\xatri\Source\Repos\Win2D\tools\docs\BuildDocs.proj]
>   System.IO.DirectoryNotFoundException:
>      in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>      in System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>      in System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
>      in System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
>      in System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
>      in System.Xml.XmlTextReaderImpl.FinishInitUriString()
>      in System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
>      in System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
>      in System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings, XmlParserContext inputContext)
>      in System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
>      in System.Xml.Linq.XDocument.Load(String uri)
>      in System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
>      in System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>      in System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>      in MergeIntellisense.Program.Run(CommandLineOptions options) in c:\Users\xatri\Source\Repos\Win2D\tools\docs\MergeIntellisense\Program.cs:line 49
>      in MergeIntellisense.Program.Main(String[] args) in c:\Users\xatri\Source\Repos\Win2D\tools\docs\MergeIntellisense\Program.cs:line 32

**Comment by shawnhar** [comment]
Interesting - I just tried a clean build now and cannot repro this error.

Could you please share a complete log showing all the output from your build?  (what command you typed, and everything this output before it got to the error)

Also please check whether the file c:\Users\xatri\Surce\Repos\Win2D\obj\docs\docsrc\Transform3DEffect.xml exists, and if not, what portion of that path does exist (for instance, do you have obj\docs folder, and does that contain docsrc?)

**Comment by Xatrix31** [comment]
[log.zip](https://github.com/Microsoft/Win2D/files/141258/log.zip)
This is complete log file.
> c:\Users\xatri\Surce\Repos\Win2D\obj\docs\docsrc\Transform3DEffect.xml
Yes, this folder contains file Transform3DEffect.xml. Folder "obj\docs" is created and contains 2 folders "docsrc" and "topics".
Maybe it because of russian version of Visual Studio, but I don't think that it's a problem.

**Comment by shawnhar** [comment]
Thanks for the log.  This is a very strange failure - your output is exactly the same as mine from a build that succeeds, except for your root folder name being different.  All the paths seem correct.

The really strange thing is that MergeIntellisense.exe reads all the XML files passed on its commandline in order, and Transform3DEffect.xml comes in the middle of that last.  So earlier files that were passed using the same relative path format loaded successfully, but this particular one which is being loaded from a sensible looking filename string and which exists in that folder, is failing to load!

I'm not really sure what to try next.  Try opening the file c:\Users\xatri\Surce\Repos\Win2D\obj\docs\docsrc\Transform3DEffect.xml into notepad, to make sure other programs can read it?

Also try deleting the entire obj folder and then run build.cmd again - this will identify if it is consistently failing on the same file.

**Comment by Xatrix31** [comment]
I can open, read, edit and save this file using notepad. I deleted folder OBJ and built again. Command line wrote exception on the same file.
I don't know why, but when I moved this repository to disk D: "d:\Win2D" and started building - everything finished successfully without exceptions...

**Comment by damyanp** [comment]
I'm glad to hear that this is working for you now.

There's definitely something strange going on.  From the log file, it looks like your repo is "c:\users\xatri\source\repos\win2d" - however the file that fails is in "c:\users\xatri\surce\repos\win2d..." - note the missing "o" in "source".

Also the call stack for the error contains:

`     in MergeIntellisense.Program.Run(CommandLineOptions options) in c:\Users\xatri\Source\Repos\Win2D\tools\docs\MergeIntellisense\Program.cs:áâà®ª  49
     in MergeIntellisense.Program.Main(String[] args) in c:\Users\xatri\Source\Repos\Win2D\tools\docs\MergeIntellisense\Program.cs:áâà®ª  32
`
Note the "áâà®ª" method names.

Very strange.

**Comment by Xatrix31** [comment]
> Note the "áâà®ª" method names.
It's "line:". :) I thought that I translated these words...

**Comment by damyanp** [comment]
It may be moot now since you've found a workaround...however, if you want to keep digging into what's going on here could you send an un-edited log file showing exactly what was output please?  I'm wondering if there's something getting confused by non-latin characters.  Thanks!

**Comment by Xatrix31** [comment]
Of course we have to find the problem... :)
[original.zip](https://github.com/Microsoft/Win2D/files/143117/original.zip)
This is the original log without any editing.

**Comment by shawnhar** [comment]
We can repro this when using the same folder name as you.  Very odd!

Thanks for the report - we will fix this at some point, but aren't going to treat it as high urgency since you have a workaround.

**Comment by shawnhar** [comment]
This is fixed in Win2D 1.17.0
