### ISSUE TITLE
NuGet package won't install with latest NETCore UWP

### ISSUE THREAD

**Issue by limefrogyank** [Microsoft/Win2D#286]
The .NETCore package released today (v5.1) prevents one from installing Win2D via NuGet.  I had to downgrade back to v5.0 in order to install Win2D.

**Comment by damyanp** [comment]
Thanks for the report. I'm following up with the .NETCore team to try and figure out what's going on.

**Comment by damyanp** [comment]
Can you try now?

The missing https://www.nuget.org/packages/runtime.win8-arm.Microsoft.NETCore.Runtime.CoreCLR/1.0.1 has now been pushed. I've been able to install .NETCore v5.1 and Win2D.uwp in the same project now.

Thanks for reporting this!

**Comment by limefrogyank** [comment]
Hmmm, for some reason, I don't see the update for .NETCore at all anymore.  And the link you put down shows the package as unlisted.

**Comment by shawnhar** [comment]
Indeed, it looks like the .NET team has unlisted that package.

I'm going to close this issue as there doesn't appear to be any problem with Win2D here - the .NET update just hasn't been fully published yet.

Thanks!
