### ISSUE TITLE
How can I simulate a DeviceLost event?

### ISSUE THREAD

**Issue by OvestLabs** [Microsoft/Win2D#287]
Hello. I have a question on Stackoverflow regarding simulating a DeviceLost event. Please take a look at it here:

http://stackoverflow.com/questions/35615922/how-can-i-simulate-a-devicelost-event-with-win2d

Essentially, I would like to know how I can programmatically raise the DeviceLost event on a CanvasControl. Is there a technique for this where I don't need to physically disable GPU/monitor/etc?

Regards,
Laith

**Comment by 13thsymphony** [comment]
Hi Laith,

I posted a response to your question on Stackoverflow. Hope it works! Unfortunately I'm not aware of an easier method to trigger device lost on Win8.1, etc.

**Comment by shawnhar** [comment]
Closing as I believe this question is answered - feel free to reactivate if you need further information.
