### ISSUE TITLE
Question regarding CanvasImageBrush

### ISSUE THREAD

**Issue by mglogan** [Microsoft/Win2D#288]
I've started to explore the Win2D library for a Windows 10 UAP app.

I am drawing an ellipse and filling it using a previously defined CanvasImageBrush. It appears the coordinates being used as fill are based on the screen coordinates where the ellipse is drawn.

In other words, an ellipse in the top left corner looks fine, but elsewhere on the page, the ellipse is filled with black. I set the ExtendX and ExtendY properties "Wrap" to test my hypothesis, and the ellipse is drawn as if it was exposing the tiled image used by the brush.

I've attached a screenshot to show the behaviour. The image used to create the CanvasImageBrush is a 162x148 rectangle containing the triangles.

![screenshot](https://cloud.githubusercontent.com/assets/10199936/13437752/e300f362-dfb3-11e5-8f27-74f68dd865af.png)

Here is the code behind:

```
public sealed partial class MainPage : Page
    {
        CanvasImageBrush fillBrush;
        List<Vector2> selectedPoints = new List<Vector2>();

        public MainPage()
        {
            this.InitializeComponent();
        }

        async Task CreateBrushes( CanvasControl sender )
        {
            CanvasBitmap cb = await CanvasBitmap.LoadAsync(sender, "Assets\\bitmapBrush.png");
            fillBrush = new CanvasImageBrush(sender, cb );
            fillBrush.ExtendX = CanvasEdgeBehavior.Wrap;
            fillBrush.ExtendY = CanvasEdgeBehavior.Wrap;
        }

        private void CanvasControl_CreateResources(CanvasControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
        {
            args.TrackAsyncAction(CreateBrushes(sender).AsAsyncAction());
        }

        private void CanvasControl_Draw(CanvasControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args)
        {
            foreach( Vector2 v in selectedPoints )
            {
                args.DrawingSession.FillEllipse( v, 25, 25, fillBrush );
            }
        }

        private void MainCanvas_PointerPressed(object sender, PointerRoutedEventArgs e)
        {
            PointerPoint p = e.GetCurrentPoint((CanvasControl)sender);
            Vector2 v = new Vector2((float)p.Position.X, (float)p.Position.Y);

            selectedPoints.Add(v);

            MainCanvas.Invalidate();
        }
    }

```

**Comment by damyanp** [comment]
Yes, you are correct, this is how image brush works.

You can use the [CanvasImageBrush.Tansform](http://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_Brushes_CanvasImageBrush_Transform.htm) property to move the image in the image brush if you wish it to be somewhere else.

**Comment by mglogan** [comment]
Thank you for the reply. 

So if I want to use  the brush to paint a consistent image, I need to translate the brush back to its origin each time I use it? Not onerous, but different than how my mind works.

Thanks again.

**Comment by shawnhar** [comment]
> So if I want to use the brush to paint a consistent image, I need to translate the brush back to its origin each time I use it?

That's correct.  Or you can use CanvasDrawingSession.Transform to move both the brush and shape together.
