### ISSUE TITLE
Exception when using StorageFile ImageProperties

### ISSUE THREAD

**Issue by kindasonic** [Microsoft/Win2D#289]
Hi,

I am attempting to draw the date taken property on a jpeg using Win2D, but am receiving the following error:

Unable to cast object of type 'System.__ComObject' to type Microsoft.Graphics.Canvas.Text.ICanvasTextLayoutFactory'.

I am retrieving the date taken value from StorageFile ImageProperties for the jpeg, as per the following code:

```
private async Task ProcessImageFileAsync(StorageFile sourceFile, StorageFolder destinationFolder, string fontFamily)
{
    var myDevice = new CanvasDevice();
    var image = await CanvasBitmap.LoadAsync(myDevice, sourceFile.Path);
    var originalWidth = image.SizeInPixels.Width;
    var originalHeight = image.SizeInPixels.Height;
    var target = new CanvasRenderTarget(myDevice, originalWidth, originalHeight, image.Dpi);
    var fontSize = originalHeight * 0.02f;
    var props = await sourceFile.Properties.GetImagePropertiesAsync();
    var dateTaken = props.DateTaken.ToString("f");
    var xLoc = 5;
    var yLoc = 5;

    var textFormat = new CanvasTextFormat
    {
        FontFamily = fontFamily,
        WordWrapping = CanvasWordWrapping.NoWrap,
        FontSize = fontSize
    };

    using (var session = target.CreateDrawingSession())
    {
        session.Clear(Colors.Black);
        session.DrawImage(image);                

        var dateTextLayout = new CanvasTextLayout(session, dateTaken, textFormat, 0.0f, 0.0f);
        var dateRectangle = new Rect(xLoc, yLoc, dateTextLayout.DrawBounds.Width + 10, dateTextLayout.DrawBounds.Height + 10);

        session.FillRoundedRectangle(dateRectangle, 10, 10, Color.FromArgb(255, 89, 88, 88));
        session.DrawTextLayout(dateTextLayout, xLoc, yLoc, Color.FromArgb(255, 255, 0, 0));
    }

    await target.SaveAsync(Path.Combine(destinationFolder.Path, sourceFile.Name)).AsTask();
}
```

The exception is thrown when creating CanvasTextLayout:
`var dateTextLayout = new CanvasTextLayout(session, dateTaken, textFormat, 0.0f, 0.0f);`

 If I replace the dateTaken parameter in the CanvasTextLayout constructor with an arbitrary string (for instance, "Hello, World!"), the error is still thrown:

```
var props = await sourceFile.Properties.GetImagePropertiesAsync();
    var dateTaken = props.DateTaken.ToString("f");
    var xLoc = 5;
    var yLoc = 5;

    var textFormat = new CanvasTextFormat
    {
        FontFamily = fontFamily,
        WordWrapping = CanvasWordWrapping.NoWrap,
        FontSize = fontSize
    };

    using (var session = target.CreateDrawingSession())
    {
        session.Clear(Colors.Black);
        session.DrawImage(image);                

        var dateTextLayout = new CanvasTextLayout(session, "Hello, World!", textFormat, 0.0f, 0.0f);
```

If I move the line `var props = await sourceFile.Properties.GetImagePropertiesAsync();` below the call to create CanvasTextLayout, the error is not thrown:

```
var dateTextLayout = new CanvasTextLayout(session, "Hello, World!", textFormat, 0.0f, 0.0f);
var props = await sourceFile.Properties.GetImagePropertiesAsync();
var dateTaken = props.DateTaken.ToString("f");

```

I really have no idea what is causing the error. Can you please help?

Thanks,
Nick

**Comment by 13thsymphony** [comment]
Hi Nick,

Can you send us a repro project?

**Comment by kindasonic** [comment]
Hi there. Sorry for the delay. Please find project attached. Thanks

[Stamponit.zip](https://github.com/Microsoft/Win2D/files/155773/Stamponit.zip)

**Comment by shawnhar** [comment]
Repro steps please - what am I supposed to do with this app to see your problem?

**Comment by kindasonic** [comment]
Hi, sorry. It's just a test app.

You need to pick an input folder using the input button.
Then pick an output folder, using the output button.
Then click process.

Thanks

**Comment by shawnhar** [comment]
After picking an arbitrary folder, clicking process pops up a completed message, but the app didn't appear to actually do anything.

**Comment by kindasonic** [comment]
The input folder needs to have at least one image to process. Thanks

**Comment by 13thsymphony** [comment]
I'm getting the following exception when I process a folder with images:
+		Exception	Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.ni.dll ("Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))")	System.UnauthorizedAccessException

That gets triggered on the following line:
await new ImageHelper().ProcessFolderAsync(SourceFolder, DestinationFolder, cmbFont.SelectedValue.ToString(), (int)sldScale.Value, progressIndicator);

**Comment by kindasonic** [comment]
I get the same error unless the input folder is in the installation directory. If you can please make an input file accessible to the app, you will see the original error I am querying. Thanks so much

**Comment by shawnhar** [comment]
Nick, please provide a modified repro app that we can run just pressing F5 in Visual Studio and immediately see the actual problem you are having, without us first needing to perform all these special and error prone setup operations.

**Comment by kindasonic** [comment]
never mind. thanks for the effort guys. cheers

**Comment by shawnhar** [comment]
Did you solve the problem, or just aren't able to provide a simple repro for us to look at?

If the latter, we'll be happy to help with the problem, but do need a not-too-complicated and clearly explained way to reproduce your issue first.  Feel free to reactivate if you can provide that.

Thanks!
