### ISSUE TITLE
Access Denied CanvasBitmap.LoadAsync

### ISSUE THREAD

**Issue by kindasonic** [Microsoft/Win2D#291]
I have created a Windows Universal app for testing.
I have selected 'Picture Library' in manifest Capabilities
I have added .jpg and .jpeg File Associations in manifest Declarations
I have added supported file types, .jpg and .jpeg to File Open Picker in manifest Declarations
I open a jpeg file using FileOpenPicker
I receive access denied error at CanvasBitmap.LoadAsync
I have attached a repro.
Please debug and pick a file to see error.
[App2.zip](https://github.com/Microsoft/Win2D/files/157659/App2.zip)

**Comment by damyanp** [comment]
In the provided app it attempts to load from a path.  However, this does not work for files that that application doesn't not normally have access to.  In these cases you need to use StorageFile to retrieve the contents of the file.

This updated version of ProcessImageFileAsync should do what you want:

        private async Task ProcessImageFileAsync(StorageFile file)
        {
            var stream = await file.OpenReadAsync();

            var myDevice = new CanvasDevice();
            
            var image = await CanvasBitmap.LoadAsync(myDevice, stream);
        }

I've been indecisive about whether or not this is a bug.  I think that it warrents further investigation - System.IO.File.ReadAllBytes(file.Path) succeeds - so it does seem that it is conceivably possible to have Win2D handle this case better.

In the meantime the above code should unblock any scenarios that rely on this.

**Comment by kindasonic** [comment]
Thank you for your help

**Comment by damyanp** [comment]
I'm closing this issue as I believe it has been addressed. Feel free to reopen if you have any further questions on this subject.

**Comment by SneWs** [comment]
I would argue that this is a bug (and that this ought to be re-opened.), especially when considering the new capability "broadFileSystemAccess" described here https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions.

I'm hitting the same "bug"/issue when trying to load in files from outside of the sandbox.
