### ISSUE TITLE
Need help on IBasicVideoEffect

### ISSUE THREAD

**Issue by 29nguyen** [Microsoft/Win2D#295]
Hello all,

I'm writing an Universal apps for realtime image processing purpose. I saw WIN2D has an example on accessing the pixel data through IBasicVideoEffect.

The problem is the example is written in C# and I already converted it to C++/CX but it complies error.

In C# example, the interface IBasicVideoEffect is added like this. Right click to this and select peek definition will lead me to metadata.

`public sealed class RotatedTilesEffect : IBasicVideoEffect`

But in my C++/CX, I can not do the same. If I delete Ibasicvideoeffect, there is no compile error. However, if it is there, there are a list of failing implement interface class

`public ref class AccessBuffer sealed: IBasicVideoEffect`

Also, if I call effects from C# project in my native code, it works successfully. 

```
task<void> Scenario1_PreviewSettings::CreatEffectAsync()
{
	Platform::String ^typeName = AccessBuffer::typeid->FullName;
	ShowStatusMessage(typeName);
	effectPropertySet = ref new PropertySet();
	// Create the definition, which will contain some initialization settings
	auto definition = ref new VideoEffectDefinition(typeName);
	
	// Add the effect to the preview stream
	return create_task(_mediaCapture1->AddVideoEffectAsync(definition, MediaStreamType::VideoPreview))
		.then([this](IMediaExtension^ extension)
	{
	});
}
```

Has anyone have idea on how to solve this?

I would appreciate any kind of your help.

Thank you.

Hieu Nguyen

**Comment by damyanp** [comment]
I expect that this is because the interface is not being inherited publically.  In C++, by default, interfaces are inherited privately.  You need to use public inheritance:

`public ref class AccessBuffer sealed: public IBasicVideoEffect `

If it is not this could you please provide a complete app that demonstrates the issue?

**Comment by 29nguyen** [comment]
Dear,
Thank you for your quick response. I already tried your suggest but it did not work too.

I have attached the file here. Basically, I want to process the pixel data of the preview Mediacapture API through addvideoeffectasync. In BufferAccess.h file, you can see the interface class error.

[CameraResolution.zip](https://github.com/Microsoft/Win2D/files/159476/CameraResolution.zip)

**Comment by damyanp** [comment]
That zip file seems to be corrupt and won't open for me.

Maybe you could create a GitHub repo containing a minimal project demonstrating the failure?

**Comment by 29nguyen** [comment]
Sorry that you can not download the zip file.

Here is the github link.

[https://github.com/29nguyen/CameraResolution]

**Comment by damyanp** [comment]
Thanks, that link works for me.

Most of the errors seem quite self-explanatory to me.  For example, around this bit of code:

		property IVector<VideoEncodingProperties^> ^SupportedEncodingProperties
		{
			IVector<VideoEncodingProperties^> ^get();
		}

There's an error and a warning.  The first:

    1>c:\temp\cameraresolution\cpp\bufferaccess_effects\BufferAccess.h(26): error C2553: 'Windows::Foundation::Collections::IVector<Windows::Media::MediaProperties::VideoEncodingProperties ^> ^BufferAccess_Effects::AccessBuffer::SupportedEncodingProperties::get(void)': overriding virtual function return type differs from 'Windows::Foundation::Collections::IVectorView<Windows::Media::MediaProperties::VideoEncodingProperties ^> ^Windows::Media::Effects::IBasicVideoEffect::SupportedEncodingProperties::get(void)'

Is fixed by replacing "IVector" with "IVectorView" in the code.

The one after that:

    1>c:\temp\cameraresolution\cpp\bufferaccess_effects\BufferAccess.h(31): warning C4488: 'BufferAccess_Effects::AccessBuffer::IsReadOnly::get': requires 'virtual' keyword to implement the interface method 'Windows::Media::Effects::IBasicVideoEffect::IsReadOnly::get'

Is fixed by adding "virtual" in front of the get.  Giving:

		property IVectorView<VideoEncodingProperties^> ^SupportedEncodingProperties
		{
			virtual IVectorView<VideoEncodingProperties^> ^get();
		}

Can you fix all of these error / warnings first and if there are further issues after that I can have a look.

**Comment by 29nguyen** [comment]
Mr. Damyan,

It is weird that I did not see any error when I compile the project in my computer. By the way, I already fix that error. 

If you delete "public IBasicVideoEffect", there will be no more error. But If I add the IBasicVideoEffect there, there is one error make me suspect.

`Error	C3612	'BufferAccess_Effects::AccessBuffer': a sealed class cannot have any pure virtual methods	BufferAccess_Effects	c:\users\andrew\desktop\cameraresolution\cpp\bufferaccess_effects\bufferaccess.h	17	
`

In C#, the interface come from metadata already. But I suspect in C++/CX we need to write our own interface class. Am I correct?

**Comment by damyanp** [comment]
You don't need to write your own interface class, in C++/CX this comes from the metadata.

However, there are bugs in your implementation of this interface, which is what all these errors are about.

I suggest you fix all these errors and warnings before continuing.

**Comment by 29nguyen** [comment]
Dear Mr. Damyanp,

Thank you so much for your help. You are right, when I solve all the problems of implementation interface, the compile errors disappear.

I dont need to change anything, only add "virtual" before each function in header file.
