### ISSUE TITLE
Drawing a normal image gets blurry? Dpi problem?

### ISSUE THREAD

**Issue by crystalblown** [Microsoft/Win2D#301]
Hello!

I have a window with a CanvasAnimatedControl.
When i draw an image it get kind of blurry. The quality is at least not as sharp as it could be.
Sometimes when i resize the app window, it gets sharp but for the most part it's just blurry.
In WPF there was a method called "PixelSnapping" which made the pixels in total alignment with the screen. I think that is the problem because in WPF, i got the same blur as here without pixelsnapping.

Is there any way to make all things rendered to the surface aligned with the screens pixels?

Thanks! :)

**Comment by clandrew** [comment]
Thanks for this report.

There is a way to align all the rendering with screen pixels- setting [CanvasDrawingSession.Units](http://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_CanvasDrawingSession_Units.htm) to Pixels does this.

Normally, however, the default unit mode of Dips will size the CanvasAnimatedControl's swap chain correctly. If you have a fuller repro to share, I can take a look.

**Comment by crystalblown** [comment]
Thanks for the reply!

Well, changing the units of the DrawingSession does not solve the issue for me. Here's my code:

    Private Sub RenderTarget_Draw(sender As ICanvasAnimatedControl, args As CanvasAnimatedDrawEventArgs) Handles RenderTarget.Draw
        args.DrawingSession.Antialiasing = CanvasAntialiasing.Aliased
        args.DrawingSession.Units = CanvasUnits.Pixels

        If ReadyToRender = True Then
            With args.DrawingSession
                If GameState.State = 0 Then
                    .FillRectangle(New Rect(0, 0, CrystalData.ClientSize.Width, CrystalData.ClientSize.Height), New CanvasSolidColorBrush(sender, Color.FromArgb(255, 24, 191, 239)))
                    .DrawImage(IntroScreen, New Rect((Me.ActualWidth - IntroScreen.Bounds.Width) / 2, (Me.ActualHeight - IntroScreen.Bounds.Height) / 2, IntroScreen.Bounds.Width, IntroScreen.Bounds.Height))
                End If
            End With
        End If
    End Sub

**Comment by crystalblown** [comment]
Hi!

I have but together a separate test application with the same image, so you can take a look. Here's a dropbox link to the vs project: [Dropbox Link](https://www.dropbox.com/s/c59sc8kf58xb1lf/AppTest.zip?dl=0)
Try to resize the window slowly, you will see patches of blurriness while the width and height is increasing. If it's super clear all the time, i suppose there's something with my display setup that is the issue.

**Comment by clandrew** [comment]
It looks sharp to me by default, but I reproed blurriness while resizing.

The cause of this blurriness is subpixel-positioning. The (X,Y) placement of the image can fall at half-pixel co-ordinates because of that division by 2. For most photos and such, that still looks okay. But due to the 'pixel art' look of this image it's important that it gets drawn on pixel boundaries.

To ensure this, one can use the code
```
New Rect(Math.Round((RenderTarget.Size.Width - IntroScreen.Bounds.Width) / 2), Math.Round((RenderTarget.Size.Height - IntroScreen.Bounds.Height) / 2)
```

On my end, if I change the code to do this I don't repro the blurriness anymore.

**Comment by crystalblown** [comment]
Oh! Now i understand! Well that fixed the problem.
Thank you very much and have a fantastic day!

**Comment by clandrew** [comment]
No problem! Glad this helped.
