### ISSUE TITLE
CanvasBitmap.LoadAsync() fails with 0x88982F5 when using stream from RenderTargetBitmap()

### ISSUE THREAD

**Issue by mscherotter** [Microsoft/Win2D#302]
I created a MemoryStream from rendering a MapControl but an exception gets thrown when creating a CanvasBitmap.  Any suggestions about what I should do?
var bitmap = new RenderTargetBitmap();

await bitmap.RenderAsync(this.MapControl);

var pixels = await bitmap.GetPixelsAsync();

var stream = pixels.AsStream();

var map = this.DataContext as Map;

var memoryStream = new MemoryStream();

await stream.CopyToAsync(memoryStream);

var imageStream = memoryStream;

imageStream.Position = 0;

_canvasBitmap = await CanvasBitmap.LoadAsync(control, imageStream.AsRandomAccessStream());

**Exception Details;**
System.Exception occurred
  HResult=-2003292336
  Message=The component cannot be found. (Exception from HRESULT: 0x88982F50)
  Source=mscorlib
  StackTrace:
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Journalist.Data.Map.<CreateResourcesAsync>d__5.MoveNext()
  InnerException:

**Comment by DanieleScipioni** [comment]
@mscherotter, I have the same exception. How do you resolved it?

Thanks in advance.

**Comment by mscherotter** [comment]
I changed my code to use an InMemoryRandomAccessStream instead of a MemoryStream.

**Comment by DanieleScipioni** [comment]
I already used a InMemoryRandomAccessStream, so there was something else probably related to bitmap encoding. Finally, the code below works for me:


 ```
var renderTargetBitmap = new RenderTargetBitmap();
await renderTargetBitmap.RenderAsync(image);
IBuffer buffer = await renderTargetBitmap.GetPixelsAsync();

CanvasBitmap canvasBitmap;
using (var stream = new InMemoryRandomAccessStream())
{
    DisplayInformation displayInformation = DisplayInformation.GetForCurrentView();

    BitmapEncoder encoder = await BitmapEncoder.CreateAsync(BitmapEncoder.BmpEncoderId, stream);
    encoder.SetPixelData(BitmapPixelFormat.Bgra8, BitmapAlphaMode.Ignore,
        (uint)renderTargetBitmap.PixelWidth,
        (uint)renderTargetBitmap.PixelHeight, displayInformation.LogicalDpi, displayInformation.LogicalDpi,
        buffer.ToArray());
    await encoder.FlushAsync();
    canvasBitmap = await CanvasBitmap.LoadAsync(_canvasDevice, stream);
}
```
