### ISSUE TITLE
How to call while hosted in a Windows 10 Service?

### ISSUE THREAD

**Issue by mms-** [Microsoft/Win2D#303]
Would like to call this API from a Windows Services (which still have no new replacement, but are essential for some uses). This makes System.Drawing the only platform API available.

How to call a UWP component from a Windows 10 win32 app (Windows Service) so the Win2D APIs can be used? Ideally it would be called in process, or is out of process the only way? Is out of process possible? Or is UWP limited to 'store apps' only?

**Comment by shawnhar** [comment]
UWP APIs such as Win2D are not available from a Windows service.

Depending on what you are using the service for, UWP background tasks may be a viable alternative: 
https://msdn.microsoft.com/en-us/windows/uwp/launch-resume/index
