### ISSUE TITLE
Create CanvasControl programatically

### ISSUE THREAD

**Issue by ngobk15** [Microsoft/Win2D#305]
Hello,
As I am customizing a Canvas on Window Runtime Component (C++/CX), I need to add CanvasControl programatically for drawing. 
+ Create CanvasControl :

mCanvasControl = ref new CanvasControl();
mCanvasControl->Draw += ref new TypedEventHandler<CanvasControl^, CanvasDrawEventArgs^>(canvasControl_Draw);
mView->Children->Append(mCanvasControl);
+ Create CanvasBitmap from unsigned char* : 

Platform::ArrayReference<unsigned char> blobArray((unsigned char*)mFloatingLayer->GetBuffer(), mBitmapWidth * mBitmapHeight * 4);
IBuffer^ ibuffer = CryptographicBuffer::CreateFromByteArray(blobArray);
mCanvasBitmap = CanvasBitmap::CreateFromBytes(mCanvasControl, ibuffer, mBitmapWidth, mBitmapHeight, DirectXPixelFormat::A8UIntNormalized);
mCanvasControl->Invalidate();
+ Draw on canvasControl_Draw:

args->DrawingSession->DrawImage(mCanvasBitmap, mCanvasRect);

but, when I run the sample, the error occured : 
WinRT information: The control does not currently have a CanvasDevice associated with it. Ensure that resources are created from a CreateResources or Draw event handler.

So, when creating CanvasControl programatically (out of XAML), how can set the CanvasDevice for CanvasControl?

**Comment by shawnhar** [comment]
Whether you create the control programmatically or through XAML does not affect its behavior at all.  You need to hook the CreateResources event, in the same way you already do for Draw, and put your resource creation code inside that event handler.

**Comment by ngobk15** [comment]
I added the CreateResources, too, but have the same error.
mCanvasControl->CreateResources += ref new TypedEventHandler<CanvasControl^, CanvasCreateResourcesEventArgs^>(canvasControl_CreateResources);

(canvasControl_CreateResources is just empty, because the canvasbitmap will be created in the different situation)

**Comment by shawnhar** [comment]
Adding an empty event handler will not help with anything :-)

You need to put your actual resource creation code (in this case, the CanvasBitmap.CreateFromBytes call) inside the CreateResources event handler, so that this will execute at the proper time.

**Comment by shawnhar** [comment]
Closing issue as I believe the question has been answered.  Feel free to reactivate if you need further info.
