### ISSUE TITLE
Sample code does not blur?

### ISSUE THREAD

**Issue by MikeSouthwark** [Microsoft/Win2D#306]
Computer is a standard Dell Precision T1700 desktop
fresh install of Windows 10 Enterprise ex MSDN
fresh install of Visual Studio 2015 Update 1 ex MSDN
using the Quick start tutorial from the Win2D documentation:-
Build the tutorial example - all the examples work AOK up to the GuassianBlurEffect step.
I entered the code exactly as QuickStart.htm BUT the lines, text, and circles remain clear and sharp, I do not get the expected blurry appearance.
Is this tutorial code known to work? What could I be doing wrong.

**Comment by damyanp** [comment]
This tutorial is expected to work.  Can you compare your code with the code shown under the "Animate your app with CanvasAnimatedControl" step 3 which shows what the canvas_Draw method is expected to look like?

**Comment by MikeSouthwark** [comment]
Hi Damyan Pepper,

 

My typing is pretty rough but I think it is the same as in QuickStart.htm?

 

Thanks,

 

Mike Southwark

15.03.2016

 

 

using System;

using System.Collections.Generic;

using System.IO;

using System.Linq;

using System.Runtime.InteropServices.WindowsRuntime;

using Windows.Foundation;

using Windows.Foundation.Collections;

using Windows.UI.Xaml;

using Windows.UI.Xaml.Controls;

using Windows.UI.Xaml.Controls.Primitives;

using Windows.UI.Xaml.Data;

using Windows.UI.Xaml.Input;

using Windows.UI.Xaml.Media;

using Windows.UI.Xaml.Navigation;

 

using Windows.UI;

using System.Numerics;

using Microsoft.Graphics.Canvas;

using Microsoft.Graphics.Canvas.Effects;

 

// The Blank Page item template is documented at http://go.microsoft.com/fwlink/?LinkId=402352&clcid=0x409

 

namespace App4

{

    /// <summary>

    /// An empty page that can be used on its own or navigated to within a Frame.

    /// </summary>

    public sealed partial class MainPage : Page

    {

        Random rnd = new Random();

 

        private Vector2 RndPosition()

        {

            double x = rnd.NextDouble() * 500f;

            double y = rnd.NextDouble() * 500f;

            return new Vector2((float)x, (float)y); 

        }

 

        private float RndRadius()

        {

            return (float)rnd.NextDouble() * 150f;

        }

 

        private byte RndByte()

        {

            return (byte)rnd.Next(256);

        }

        public MainPage()

        {

            this.InitializeComponent();

        }

 

/*        private void canvas_Draw(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender,

                                 Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args)

        {

            /* args.DrawingSession.DrawText("what, no pasta?", 100, 100, Colors.Black);

            args.DrawingSession.DrawCircle(125, 125, 100, Colors.Green);

            args.DrawingSession.DrawLine(0, 0, 50, 200, Colors.Red); */

/*            for (int i=0; i< 10; i++)

            {

                args.DrawingSession.DrawText("what, no pasta?", RndPosition(),Color.FromArgb(255,RndByte(), RndByte(), RndByte()));

                args.DrawingSession.DrawCircle(RndPosition(), RndRadius(), Color.FromArgb(255, RndByte(), RndByte(), RndByte()));

                args.DrawingSession.DrawLine(RndPosition(), RndPosition(), Color.FromArgb(255, RndByte(), RndByte(), RndByte()));

            }

        }

*/

 

        private void canvas_Draw(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender,

                                 Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args)

        {

            CanvasCommandList cl = new CanvasCommandList(sender);

            using (CanvasDrawingSession clds = cl.CreateDrawingSession())

            {

                for (int i = 0; i < 100; i++)

                {

                    args.DrawingSession.DrawText("What, no pasta?", RndPosition(), Color.FromArgb(255, RndByte(), RndByte(), RndByte()));

                    args.DrawingSession.DrawCircle(RndPosition(), RndRadius(), Color.FromArgb(255, RndByte(), RndByte(), RndByte()));

                    args.DrawingSession.DrawLine(RndPosition(), RndPosition(), Color.FromArgb(255, RndByte(), RndByte(), RndByte()));

                }

            }

 

            GaussianBlurEffect blur = new GaussianBlurEffect();

            blur.Source = cl;

            blur.BlurAmount = 10.0f;

            args.DrawingSession.DrawImage(blur);

        }

        void Page_Unloaded(object sender, RoutedEventArgs e)

        {

            this.canvas.RemoveFromVisualTree();

            this.canvas = null;

        }

    }

}

**Comment by MikeSouthwark** [comment]
Oops! The clds. Prefix ….

 

OK, I see it now. My eyes were/are not good enough.

 

Thanks for your email

 

 

From: Michael Rebay [mailto:mr@advinfo.co.uk] 
Sent: 15 March 2016 17:33
To: 'Microsoft/Win2D' <reply@reply.github.com>
Subject: RE: [Win2D] Sample code does not blur? (#306)

 

Hi Damyan Pepper,

 

My typing is pretty rough but I think it is the same as in QuickStart.htm?

 

Thanks,

 

Mike Southwark

15.03.2016

 

 

using System;

using System.Collections.Generic;

using System.IO;

using System.Linq;

using System.Runtime.InteropServices.WindowsRuntime;

using Windows.Foundation;

using Windows.Foundation.Collections;

using Windows.UI.Xaml;

using Windows.UI.Xaml.Controls;

using Windows.UI.Xaml.Controls.Primitives;

using Windows.UI.Xaml.Data;

using Windows.UI.Xaml.Input;

using Windows.UI.Xaml.Media;

using Windows.UI.Xaml.Navigation;

 

using Windows.UI;

using System.Numerics;

using Microsoft.Graphics.Canvas;

using Microsoft.Graphics.Canvas.Effects;

 

// The Blank Page item template is documented at http://go.microsoft.com/fwlink/?LinkId=402352 <http://go.microsoft.com/fwlink/?LinkId=402352&clcid=0x409> &clcid=0x409

 

namespace App4

{

    /// <summary>

    /// An empty page that can be used on its own or navigated to within a Frame.

    /// </summary>

    public sealed partial class MainPage : Page

    {

        Random rnd = new Random();

 

        private Vector2 RndPosition()

        {

            double x = rnd.NextDouble() * 500f;

            double y = rnd.NextDouble() * 500f;

            return new Vector2((float)x, (float)y); 

        }

 

        private float RndRadius()

        {

            return (float)rnd.NextDouble() * 150f;

        }

 

        private byte RndByte()

        {

            return (byte)rnd.Next(256);

        }

        public MainPage()

        {

            this.InitializeComponent();

        }

 

/*        private void canvas_Draw(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender,

                                 Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args)

        {

            /* args.DrawingSession.DrawText("what, no pasta?", 100, 100, Colors.Black);

            args.DrawingSession.DrawCircle(125, 125, 100, Colors.Green);

            args.DrawingSession.DrawLine(0, 0, 50, 200, Colors.Red); */

/*            for (int i=0; i< 10; i++)

            {

                args.DrawingSession.DrawText("what, no pasta?", RndPosition(),Color.FromArgb(255,RndByte(), RndByte(), RndByte()));

                args.DrawingSession.DrawCircle(RndPosition(), RndRadius(), Color.FromArgb(255, RndByte(), RndByte(), RndByte()));

                args.DrawingSession.DrawLine(RndPosition(), RndPosition(), Color.FromArgb(255, RndByte(), RndByte(), RndByte()));

            }

        }

*/

 

        private void canvas_Draw(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender,

                                 Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args)

        {

            CanvasCommandList cl = new CanvasCommandList(sender);

            using (CanvasDrawingSession clds = cl.CreateDrawingSession())

            {

                for (int i = 0; i < 100; i++)

                {

                    args.DrawingSession.DrawText("What, no pasta?", RndPosition(), Color.FromArgb(255, RndByte(), RndByte(), RndByte()));

                    args.DrawingSession.DrawCircle(RndPosition(), RndRadius(), Color.FromArgb(255, RndByte(), RndByte(), RndByte()));

                    args.DrawingSession.DrawLine(RndPosition(), RndPosition(), Color.FromArgb(255, RndByte(), RndByte(), RndByte()));

                }

            }

 

            GaussianBlurEffect blur = new GaussianBlurEffect();

            blur.Source = cl;

            blur.BlurAmount = 10.0f;

            args.DrawingSession.DrawImage(blur);

        }

        void Page_Unloaded(object sender, RoutedEventArgs e)

        {

            this.canvas.RemoveFromVisualTree();

            this.canvas = null;

        }

    }

}

**Comment by damyanp** [comment]
Glad to have helped: I'm closing this issue because I believe your question has been answered.  Feel free to reopen if this isn't the case!
