### ISSUE TITLE
Scaling issue when using Win2D?

### ISSUE THREAD

**Issue by hholhjem** [Microsoft/Win2D#307]
I have a Windows 10 Mobile UWP project where I am using two images fading the front profile image (rounded image with fading edges) onto the blurred larger image behind (same picture, but the copy behind is larger and blurred).

<b>I am using Win2D and I am struggling a bit, because Win2D does auto scale elements like I am used to with the XAML elements. Is there a good way to solve issues with different screen sizes and DPI when using Win2D?</b> I have uploaded an example where i have some issues adjusting especially the foreground image to different screen sizes and DPI.

The best solution I found for now is to use sender.ActualWidth and multiply with a factor, but it is far from good. <b>What is best practice on this issue (because what I am currently doing is probably as far from best practice as I can get)?</b>

Please take a look at a working example I uploaded:
https://github.com/hholhjem/win2d_scaletest and especially the main.xaml.cs in Views: https://github.com/hholhjem/win2d_scaletest/blob/master/GraphicsScaleTest/GraphicsTest/Views/Main.xaml.cs

When running this in the different W10M emulators you can easily see that this does not look good, e.g. on the right side of the foreground image when running in a 4" WVGA emulator.

Help appreciated, thanks!

**Comment by shawnhar** [comment]
You are making this more complicated than it needs to be.  Win2D operates in DIPs by default (the same as XAML) so it is almost never necessary to adjust for DisplayInformation.RawPixelsPerViewPixel.

This article explains more detail: http://microsoft.github.io/Win2D/html/DPI.htm

but in short you can take out all your RawPixelsPerViewPixel adjustment and always just operate in DIP units.

**Comment by shawnhar** [comment]
Closing issue as I believe the question has been answered.  Feel free to reactivate if you need further info.

**Comment by hholhjem** [comment]
Thanks for your last reply. I have now removed the adjust for DisplayInformation.RawPixelsPerViewPixel.

Link: https://github.com/hholhjem/win2d_scaletest/tree/master/GraphicsScaleTest
(Recomended W10M emulators for testing: WVGA 4inch: 144 DPI, QHD 5.2inch: 384 DPI, 1080p 6inch: 240 DPI)

Question 1: I am not happy with the simplicity of my solution to the scaling issue. Scaling works good now, but I still had to create som dynamic scaling based on the sender.Size values. Is this a good way to solve the scaling? Or am I missing something?

When experimenting with SourceRectangle values of the CanvasImageBrush holding the foreground image I experiened something strange. When populating the rectangle these values does not behave exactly as expected:

Question 2: Param x definition: top-left coordinate of rectange. Why do i have to write -300 to move the rectange to the left and not 300?

Question 3: Param width definition: the width of the rectangle. Why does the width option take width from 0 (left side) and not from point x, y (two first params)?


Any others tips on improving this? All feedback welcomed! Thanks!

**Comment by hholhjem** [comment]
@shawnhar: Looks like I don't have rights to reopen this issue since I have not closed it myself. Feel free to reopen if you see fit.

**Comment by shawnhar** [comment]
1)  Sorry, I don't understand what you are asking here.

2)  SourceRectangle specifies what part of the image the brush will read from, not where that image gets drawn to.  Translating source vs. dest rect moves the image in the opposite direction.  If you just want to change where an image is drawn, it's typically easier to change the draw destination position rather than altering your brush source rect.

3)  Windows.Foundation.Rect has constructors accepting both left+top+size and left+top+right+bottom formats.

**Comment by hholhjem** [comment]
Thank you!

About question 1: I was generally wondering if you had any tips how to improve my code with regards to the Win2D API? Or am I using the Win2D API the best way possible to get the layout that I want?
