### ISSUE TITLE
Access multiple data arrays in one effect

### ISSUE THREAD

**Issue by 29nguyen** [Microsoft/Win2D#308]
Dear Win2D API team,

Last time I have posted an issue here to ask about how to access the data arrays based on the IBasicVideoEffect example. I did it successfully with one camera. But now my application raises me another question. What happened if I need to access the data arrays of two cameras instead of one?

It seems like I can write one more effect with the Ibasicvideoeffect. However, two data arrays is in two different cpp files and even I do not know if they are running effect at the same time.

Does anyone have an idea how to access both camera data arrays just in one effect? Can I define 2 different CanvasDevice objects and how to run it with addvideoEffectAsync?

Thank you. I would appreciate any kind of your help.

Hieu Nguyen

**Comment by lilyfang** [comment]
IBasicVideoEffect is designed for one input and one output. To get two camera streams, you need to have two IBasicVideoEffect and insert them into different camera streams. One effect instance needs to save the buffer out, which could be later accessed by another effect instance.

**Comment by 29nguyen** [comment]
Thank you for your response.

Your answer is the same way with what I suspect. However, we are not guarantee that we can access to both data arrays at the same time. Addvideoeffectsync is inside the creat_task which I think one will run first and one run later. But I will try first and see what'll be happen. Any others ideas will be welcomed.

Hieu Nguyen.

**Comment by shawnhar** [comment]
> However, we are not guarantee that we can access to both data arrays at the same time

You will need to handle synchronization yourself, using locks to make sure both effects are not trying to access the same buffer at the same time, and dealing with startup races where one effect may start processing slightly before the other.

**Comment by 29nguyen** [comment]
Sorry for the late reply,

I did implement few days ago, it was successful when I tried the simple grayscale conversion on 2 streams. However, the preview frame rate on both streams is slow down (lagging). Is it the effect of calling two effects of the same time? Or I did not handle the tasks well.

**Comment by shawnhar** [comment]
Applying realtime effect processing to even one realtime video feed can be quite expensive.  I haven't tried two before (or seen any apps that do this with two) but I would expect performance to be challenging here.  Whether or not you can make this run smoothly will depend on how expensive the processing you are trying to apply is, and how well optimized your code is.

**Comment by 29nguyen** [comment]
Thank you for your explanation,

Do you have any idea whether we can do multiple threads inside the IBasicVideoEffect? Because right now it does something like sequential, one input in and give out 1 output. 

Or do you have any experience that we can have capture part and display part separately? I guess no because we only need one function addvideoeffectasync.

Please let me know if you have any idea.

**Comment by shawnhar** [comment]
IBasicVideoEffect is (as the name implies) designed to make basic video editing scenarios as easy as possible.  It provides a very straightforward programming model but not a lot of options to control threading or merge multiple input streams, etc.

If you are trying to do something more advanced, you may want to work directly with the underlying C++ Media Foundation APIs.  These are vastly more complex than IBasicVideoEffect, but also far richer in feature set.

**Comment by 29nguyen** [comment]
Again, thank you for your advise.

I work on the MF API before and also recognize that it is very complicated to write a custom effect sink. But at the same time, my advisor works on Media Foundation Capture Engine while I'm working on Universal Window Platform. I think this time I need to stop my adventure on UWP and switch back to my advisor's code
