### ISSUE TITLE
Drawing bitmap results in blurry image

### ISSUE THREAD

**Issue by chuckries** [Microsoft/Win2D#310]
I don't think this is a bug, I just can't figure out what I'm trying to do. The bitmap I'm rendering looks like this:
![image](https://cloud.githubusercontent.com/assets/6598594/13902672/4fa93dda-ee0f-11e5-88f4-13814c07d538.png)

Rendering the same bitmap in SDL looks like this:
![image](https://cloud.githubusercontent.com/assets/6598594/13902649/0583c2d0-ee0e-11e5-878f-d57ff8058ee0.png)

SDL's scaled bitmap is way sharper. 

Relevant Win2D code:
```C++
void MainPage::canvas_CreateResources(CanvasAnimatedControl^ sender, CanvasCreateResourcesEventArgs^ args)
{
...
    _bitmapBytes = ref new Array<byte>(256 * 240 * 4);
    _bitmap = CanvasBitmap::CreateFromBytes(sender->Device, _bitmapBytes, 256, 240, Windows::Graphics::DirectX::DirectXPixelFormat::R8G8B8A8UIntNormalized, sender->Dpi, Microsoft::Graphics::Canvas::CanvasAlphaMode::Ignore);
}

void MainPage::canvas_Update(ICanvasAnimatedControl^ sender, CanvasAnimatedDrawEventArgs^ args)
{
...
    _bitmap->SetPixelBytes(_bitmapBytes);
}

void MainPage::canvas_Draw(ICanvasAnimatedControl^ sender, CanvasAnimatedDrawEventArgs^ args)
{
    args->DrawingSession->DrawImage(_bitmap, Rect(0, 0, sender->Size.Width, sender->Size.Height));
}
```

Relevant SDL Code:
```C++
Create()
{
    _window = SDL_CreateWindow(
        "NES",
        SDL_WINDOWPOS_CENTERED,
        SDL_WINDOWPOS_CENTERED,
        SCREEN_WIDTH * scale,
        SCREEN_HEIGHT * scale,
        SDL_WINDOW_SHOWN | SDL_WINDOW_ALLOW_HIGHDPI
        );

    _renderer = SDL_CreateRenderer(
        _window,
        -1,
        SDL_RENDERER_ACCELERATED// | SDL_RENDERER_PRESENTVSYNC
        );

    _texture = SDL_CreateTexture(
        _renderer,
        SDL_PIXELFORMAT_RGB24,
        SDL_TEXTUREACCESS_STREAMING,
        SCREEN_WIDTH,
        SCREEN_HEIGHT
        );
}

Draw()
{
    SDL_UpdateTexture(_texture, NULL, (void*)screen_to_render, SCREEN_WIDTH * 3);
    SDL_RenderClear(_renderer);
    SDL_RenderCopy(_renderer, _texture, NULL, NULL);
    SDL_RenderPresent(_renderer);
}
```

UWP Project: https://github.com/chuckries/nes/tree/uwp_example
SDL Project: https://github.com/chuckries/nes/tree/master

**Comment by chuckries** [comment]
I should note that the SDL is in a windows desktop app, not a UWP app.

**Comment by 13thsymphony** [comment]
Hi chuckries, I'm not an expert in SDL, but from your attached screenshots it appears that it is rendering using nearest neighbor interpolation, while Win2D uses linear interpolation by default. If you want the same kind of scaling/interpolation behavior, you should use one of the DrawImage overloads that explicitly define CanvasImageInterpolation, e.g.:
http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasDrawingSession_DrawImage_8.htm

**Comment by chuckries** [comment]
Exactly what I needed! Thanks!
