### ISSUE TITLE
MS Store App Insights Issue between Win2D and UWP

### ISSUE THREAD

**Issue by eriadel** [Microsoft/Win2D#313]
1 combase RoOriginateError 0x54 
 2 combase RoGetMatchingRestrictedErrorInfo 0x4C 
 3 Windows_UI Microsoft::WRL::ErrorPropagationPolicyTraits_-1_::FireCompletionErrorPropagationPolicyFilter 0x11EBA 
 4 Windows_UI Windows::UI::Core::CCoreAsyncBase_Windows::Foundation::IAsyncAction,Windows::Foundation::IAsyncActionCompletedHandler,&Windows::UI::Core::AsyncActionName,&Windows::UI::Core::CoreAsyncActionName_::FireCompletion 0xEE 
 5 Windows_UI Windows::UI::Core::CCoreAsyncBase_Windows::Foundation::IAsyncAction,Windows::Foundation::IAsyncActionCompletedHandler,&Windows::UI::Core::AsyncActionName,&Windows::UI::Core::CoreAsyncActionName_::put_Completed 0x11F 
 6 Microsoft_Graphics_Canvas  0x588A5 
 7 Microsoft_Graphics_Canvas  0x58803 
 8 Microsoft_Graphics_Canvas  0x49468 
 9 Microsoft_Graphics_Canvas  0x4AD7E 
 10 Microsoft_Graphics_Canvas  0x50447 
 11 Microsoft_Graphics_Canvas  0x482DE 
 12 Microsoft_Graphics_Canvas  0x45155 
 13 Microsoft_Graphics_Canvas  0x480E8 
 14 Microsoft_Graphics_Canvas  0x490DB 
 15 Windows_UI Windows::UI::Core::CDispatcher::ProcessInvokeItem 0x585 
 16 Windows_UI Windows::UI::Core::CDispatcher::ProcessMessage 0x52B 
 17 Windows_UI Windows::UI::Core::CDispatcher::WaitAndProcessMessages 0xFA 
 18 Windows_UI Windows::UI::Core::CDispatcher::ProcessEvents 0xA8 
 19 Windows_UI_Xaml CJupiterWindow::RunCoreWindowMessageLoop 0x61 
 20 Windows_UI_Xaml DirectUI::DXamlCore::RunMessageLoop 0x47 
 21 twinapi_appcore Windows::ApplicationModel::Core::CoreApplicationView::Run 0x46 
 22 twinapi_appcore _lambda_0cd40d6028926591b968fa24dacfa2ba_::_helper_func_cdecl_ 0xDA 
 23 SHCore _WrapperThreadProc 0xF0 
 24 kernel32 BaseThreadInitThunk 0x22 
 25 ntdll RtlUserThreadStart 

Unfortunately we do not have Symbols for the Win2D lib, in the MS Store, even we've marked all symbols in the Visual Studio Options.

Win2D 1.16
UWP 5.0.0

Looks like an issue between Win2D and UWP framework..

What our App does in general : we add CanvasAnimatedControl to the Grid, Launch 

We use infrastructure similar to Your particle system, however, our code is more dynamic. Firstly we initialize shaders bitmaps with

bitmap = await CanvasBitmap.LoadAsync(resourceCreator, bitmapFilename);

then we Draw with:

using (drawingSession.CreateLayer(radialGradientBrush))
                        {
                            drawingSession.DrawImage(bitmap, 0, 0, bitmapBounds, alpha, CanvasImageInterpolation.Linear, new Matrix4x4(transform));
                        }

Then we remove CanvasAnimatedControl with:

                if (CAC != null)
                {
                    CAC.Draw -= canvas_DrawAnimated;
                    CAC.Update -= canvas_Update;
                    CAC.CreateResources -= canvas_CreateResources;
                    CAC.RemoveFromVisualTree();
                    CAC = null;
                }

For 99,9% of cases this works, problems like this we see only in the MS Store.
We didn't catch this problem when debugging localy.

Best Regards,
/K.

**Comment by shawnhar** [comment]
We'll need more information to be able to suggest anything useful here.  I see that you have no local repro for this issue - are you able to provide a crash dump?

**Comment by eriadel** [comment]
We have no dump for this, otherwise we would provide you more details :(

I'm not sure why AppInsights excluded Win2D symbols from analysis.. we should have them all included.. and it looks from trace only Win2D calls are not in the bundle.. I'm closing the case for now and I will try to provide you more information in the future..
