### ISSUE TITLE
How to get a *.pdb file for the Win2D 1.16 NuGet package ?

### ISSUE THREAD

**Issue by eriadel** [Microsoft/Win2D#314]
The reason we cannot deliver or include symbols in our application bundle is they are not included in the Win2D NuGetPackage and cannot by obtained by VS2015->Debug->Options->Debugging->Symbols-> Include all symbols for packages.

Then we could deliver you full stack details regarding issues we observe..

Could you help here ?

Best Regards,
/K.

**Comment by shawnhar** [comment]
We aren't currently publishing symbols for the Win2D NuGet packages.  The easiest way to get these is to compile it yourself from source.

**Comment by eriadel** [comment]
Why you're not publishing symbols for the Win2D NuGet packages ?

It looks Win2D is not yet very stable and this will help to debug many issues spotted on the field.
We've reported 2 tickets and the problem was we didn't get symbols to allow you to fix them.

**Comment by shawnhar** [comment]
We don't publish symbols just because this has never been a priority before now - actually you're the first person to ask about it!

I'm not familiar with the App Insights stuff that is giving you these callstacks, but just a callstack is not usually going to be enough to debug problems that are only occurring out in the wild.  Except for very rare cases where the callstack alone is enough to guess a problem, we really need some way to get a crash dump to do postmortem debugging.

**Comment by eriadel** [comment]
Thanks for the feedback Shaw, I will try to get answer from the MS Store if it is possible to get a crash dump.. (couldn't see this in the UWP MS Store API, I was looking for that for a long time..)

Yes, I ask for symbols, cause we care for our customers and we would like to help you to fix some problems.

Best Regards,
Karol

**Comment by shawnhar** [comment]
Request for pdbs is noted.

What would be the most useful way to provide these?  Should they be part of the nuget package, or shipped via some other mechanism?

**Comment by eriadel** [comment]
Thank you Shawn, any way is welcome. I believe best way would be, if they could be a part of the NuGet package.

Then we could see the call stack instead of the :

 6 Microsoft_Graphics_Canvas  0x588A5 
 7 Microsoft_Graphics_Canvas  0x58803 
 8 Microsoft_Graphics_Canvas  0x49468 
 9 Microsoft_Graphics_Canvas  0x4AD7E 
 10 Microsoft_Graphics_Canvas  0x50447 
 11 Microsoft_Graphics_Canvas  0x482DE 
 12 Microsoft_Graphics_Canvas  0x45155 
 13 Microsoft_Graphics_Canvas  0x480E8 
 14 Microsoft_Graphics_Canvas  0x490DB

Just posted question regarding crash dump for the MS Store. We'll see soon if this is possible to get one or not.

We've fixed all critical issues for our apps framework basing on the call stacks from the Store and I'm pretty sure they will help you at least to catch one or two issues.

**Comment by damyanp** [comment]
I think that the requirements are:

* P0 - callstacks from app insights are able to resolve the symbols
* P1 - Visual Studio is able to resolve the symbols (P1 - this can be worked around by building Win2D locally, but not ideal)
* P1 - The nuget package does not become unnecessarily bloated (including the symbols in the package will increase the size from about 2MB to about 150MB)

I'm not 100% sure that just including the pdbs in the nuget package will satisfy the app insights requirement.

**Comment by shawnhar** [comment]
Does App Insights require symbols to be available at runtime on the machine where the app is running?

**Comment by eriadel** [comment]
•P0 - callstacks from app insights are able to resolve the symbols
•P1 - Visual Studio is able to resolve the symbols ◦this can be worked around by building Win2D locally, but not ideal

Ok, so can I propose alternative solution? Any chance to add symbols to Microsoft's Symbol Server ?
Then user can choose to download them from there in VS Debug Options and Your package stays not bloated..

"Does App Insights require symbols to be available at runtime on the machine where the app is running?"

I'm not 100% sure, but I think it's required to have Application Bundle with Symbols in the MS Store.
My guess is App Insights delivers bunch of callstack addresses to MS Store and there they are resolved.

**Comment by eriadel** [comment]
Just compiled latest Win2D library, I needed to remove NuGet Packages (time!) and injected compiled lib. But I have problems with Visual Studio and generated PDB file. This I cannot explain.

Compiled library works ok.
Communicate is they do not match the lib..

I'm using library and pdb file from:
Win2D-master\bin\uapx86\debug\winrt.dll.uap

Microsoft.Graphics.Canvas.winmd	C:\Users\St\Documents\Visual Studio 2015\Projects\Precursors\App3\bin\x86\Debug\AppX\Microsoft.Graphics.Canvas.winmd	Yes	N/A	Binary was not built with debug information.		17		2016-03-24 08:56	0B840000-0B87E000	[8724] Precursors.exe	[1] CoreCLR_UWP_Domain

My approach was to run the project -> Debug -> Modules-> Search for lib above -> Load PDB file..

**Comment by damyanp** [comment]
I'm afraid I'm not following this.  What does "I need to remove NuGet Package (time!) mean"?  Or "inject compiled lib" mean?  
  
Can you step by step explain what you've done please - starting from how you built Win2D, how you ran your app, and exactly how you're trying to load PDB files.  Are you trying to load them into the Visual Studio 2015 debugger?  Or some other app?

**Comment by eriadel** [comment]
Sure, step by step: (Visual Studio Community 2015 Update 1 used)
1. Downloaded Win2D from GitHub.
2. Compiled Win2D with Visual Studio 2015 U1.
3. Got Win2D Succesfully compiled in Win2D-master\bin\uapx86\debug\winrt.dll.uap in debug mode (with symbols PDB file)
4. Uninstalled NuGetPackage Win2D 1.16. (to be in sync with compiled package)
5. Added Win2D as reference from previously compiled Win2D-master\bin\uapx86\debug\winrt.dll.uap
I was only able to select Microsoft.Graphics.Canvas.winmd not the DLL file, but that was 
Successful.
6. When compiled Win2D was running with my project(all was working ok), I selected Debug -> Windows -> Modules-> Found and Selected Microsoft.Graphics.Canvas.winmd -> (right click) Load PDB file

But regarding point 6 I was unable to load previously compiled PDB file with the library :(
Communicate was : A matching symbol file was not found in this folder.

Do you know better way how to proceed here ?
Thank you in advice.

Best Regards,
Karol

**Comment by shawnhar** [comment]
These steps are correct.  Symbols not matching means you must somehow be running with a different version of the Win2D DLL than the debug one you just built locally.  Could there be a stale DLL left behind in your bin folder from when you previously built this app using the Win2D NuGet package?

**Comment by damyanp** [comment]
I would recommend building the nuget package locally (using the "build" script) and then referencing that package in your app.  Follow the instructions in [README.md](https://github.com/Microsoft/Win2D/blob/master/README.md) under the "Building Win2D from source" for more details.

**Comment by eriadel** [comment]
To be sure the lib and pdb file is equal, I've copied compiled Win2D files into every directory where the Microsoft.Graphic.Canvas.dll was present, but still VS2015 U1 was unable to match them. So there's still something missing or there's a small bug in VS2015 U1. I will follow instructions from Damyan and let you know about output in next days. Thanks.

**Comment by eriadel** [comment]
To be sure the lib and pdb file is equal, I've copied compiled Win2D files into every directory where the Microsoft.Graphic.Canvas.dll was present, but still VS2015 U1 was unable to match them. So there's still something missing from my side(maybe dll is still overlapped, but I cannot see the change in file date or size after rebuild) or there's a small bug in VS2015 U1. I will follow instructions from Damyan and let you know about output in next days. Thanks.

**Comment by eriadel** [comment]
To be sure the lib and pdb file is equal, I've copied compiled Win2D files into every directory where the Microsoft.Graphic.Canvas.dll was present, but still VS2015 U1 was unable to match them. So there's still something missing from my side(maybe dll is still overlapped, but I cannot see the change in file date or size after rebuild) or there's a small bug in VS2015 U1. I will follow instructions from Damyan and let you know about output in next days. Thanks.

**Comment by eriadel** [comment]
Followed https://github.com/Microsoft/Win2D/blob/master/README.md 
1.) Cloned latest Git Repository.
2.) Run Visual Studio 2015 MSBuild Command Prompt and executed "build" script..

after 20 minutes of compilation spotted an error in
C:\GitRepositories\Win2D\Win2D.git\tools\docs\MergeIntellisense\Program.cs line 32/49..

exactly in Run() Function..

So far I do not want to waste more time for this topic. We hold next project related with Win2D until everything will be more user friendly. Thank you for the help.

If we will get crash dump, then we will open new ticket. I do not see the point to waste more time here.. both for you and us.

**Comment by damyanp** [comment]
Sounds like you've run into #283.

**Comment by shawnhar** [comment]
I'm sorry you were not able to get this working.

I'm actively in the middle of figuring out how to publish symbols to the Microsoft symbol server. This is likely to take a couple of days but is in progress. Fingers crossed that having them indexed on the server will be enough for App Insights to pick them up.

Got to say though that even with properly resolved symbols, just a callstack without actual crash dump isn't always the most useful thing for figuring out problems.  Sometimes that's enough to guess what the problem is, but often not - it very much depends on the nature of each issue.

I do think it's a little extreme to hold future projects on the basis of telemetry indicating crashes we have never managed to repro, though!  Overall I believe Win2D is stable and reliable, and at least so far we've been able to provide good turnaround times on fixing issues whenever someone has been able to show us how to repro them.

**Comment by eriadel** [comment]
Appreciate this Shawn and Damyan. I think publishing symbols to Windows Server it's the best way for all your customers. If you want my support and escalation this issue to UWP program manager, please let me know. I can directly ask him to help here.

And this is not your fault as developers, it's the process that requires improvements.

Win2D it's very stable for the development, cause as mentioned we cannot reproduce issues internally.
But in my opinion it requires a little bit more stability for the end-customers. (if the data from App Insights is valid)

The problem we hold next project is we see some problems in the field, but we have no way to properly react on them: (this creates a RISK)
1.) MS Store not always sends us the trace.
2.) MS Store doesn't generates crash dumps very often.
3.) 60% of current crashes from last 20 days(Fantasy Battlegrounds CCG) are from Win2D library.
4.) We have no reliable way to show you how to reproduce the problem or send you a crash, cause we also do not know how our customers crash Win2D. We do a lot of tests internally, but we cannot catch cases on our machines. (end users use 3 different platforms Arm, x86, x64, with different CPUs frequencies, while we use only x86 platforms for tests)
5.) I realize trace itself can be not enough, cause I develop still a lot by myself from 8 years and I had a chance to solve many issues for many big companies. (valid crash dump or 2 are the best way to solve the issues)

And this is potential risk. So, if you ask me, if I would like to invest seriously in another project. I say no. But we like Win2D and we're looking forward into the future.

We do not blame Win2D team, we're looking for a way we could help our end customers, you and ourselves. We do not have reliable tools to pass information from our customers to you.
And I'm crossing fingers you will be successful with publishing symbols on Microsoft's Server.

Please let me know in this thread, if you are ready with Win2D Symbols on the MS Server, then I will invest some time for new Win2D tests that will be emulating and stressing things we do in our games. I hope this will help to invoke some cases internally.

Cheers!

Software Architect,
Karol Sabat
www.artificialworlds.eu

**Comment by shawnhar** [comment]
Symbols for Win2D 1.16.0 are now indexed on the public Microsoft symbol server.

**Comment by eriadel** [comment]
Thanks Shawn, we still see this below every second day in MS Store, however I hope we will get a crash dump or more interesting call stack one day.. (hope I will not loose more than few hundreds customers, until this will happen..)

Microsoft_Graphics_Canvas!Microsoft::WRL::Details::InvokeHelper_Microsoft::WRL::Implements_Microsoft::WRL::RuntimeClassFlags_2_,ABI::Windows::Foundation::IAsyncActionCompletedHandler,Microsoft::WRL::FtmBase,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil_,_lambda_89ee3a9fd01778eb24854acb23b43cfc_,2_::Invoke 

We've tried to develop test suite to reproduce the problem. Guess what, instead of the crash in Win2D we've get the crash inside of the UWP.. It's creazy..

At this stage we cannot say everything is stable, as we've never get such problems with Silverlight and never get such bad reviews with that framework.
