### ISSUE TITLE
Win2d Introduction: The specified module could not be founnd.

### ISSUE THREAD

**Issue by thecobblersdaughter** [Microsoft/Win2D#315]
While working through the introduction, http://microsoft.github.io/Win2D/html/Introduction.htm, I cannot seem to add a CanvasControl inside the existing Grid control. It displays an exception, "The element "[CanvasControl]" could not be displayed because of a problem with Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl: Cannot create an instance of "CanvasControl".

Any ideas?

**Comment by damyanp** [comment]
Can you be more specific?  What is the "it" that displays an exception?  

Does it work if you type in the code as described on the page and then press F5 to run the app?

**Comment by thecobblersdaughter** [comment]
The "it" would be Visual Studio 2015. I copy/pasted the code directly to the XAML body:

<Page
    x:Class="App10.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App10"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:canvas="using:Microsoft.Graphics.Canvas.UI.Xaml"
    mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <canvas:CanvasControl Draw="CanvasControl_Draw" ClearColor="CornflowerBlue"/>
    </Grid>
</Page>

**Comment by damyanp** [comment]
Where in Visual Studio 2015 are you seeing the message?

Does it work if you press F5 to run the app?

**Comment by thecobblersdaughter** [comment]
It looks like I installed a depreciated version using the NuGet console. I reinstalled and it works. Thanks for the help.
