### ISSUE TITLE
How to trigger a drawing session

### ISSUE THREAD

**Issue by thecobblersdaughter** [Microsoft/Win2D#316]
I am looking for a good way to trigger a drawing session with the Draw event within my button_Click event. Any suggestions?

        public void button_Click(object sender, RoutedEventArgs e)
        {
            //Initialize parameters

            //Try to draw a line

            //TODO: Check int for synthax

        }

        void canvasControl_Draw(CanvasControl sender, CanvasDrawEventArgs args)
        {

            args.DrawingSession.DrawText("Hello, world!", 100, 100, Colors.Yellow);

        }

**Comment by damyanp** [comment]
[canvasControl.Invalidate](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_UI_Xaml_CanvasControl_Invalidate.htm) will cause the control to redraw itself.

**Comment by thecobblersdaughter** [comment]
I thought about that, but I think my hang up is getting my drawing session to open _only_ when my Click event for button happens. I want the commands in my drawing session to only occur once the button is pressed in my app. I am fairly new at this so it may be a simple problem of me not knowing what is going on.

**Comment by damyanp** [comment]
Maybe you could hide the control and only show it when the button has been clicked?

It may be worth taking a step back and trying to describe what effect you're trying to achieve.

**Comment by thecobblersdaughter** [comment]
Good idea. My app is a single page that takes parameters from the user and generates a geometric shape based on those parameters (like taking height and width and making a rectangle, but more complex). As my code is written now, the shapes are generated in my canvasControl_Draw session, but it runs every time I start the app. I want the shapes to be generated once my button_Click event is triggered.

**Comment by thecobblersdaughter** [comment]
My understanding is that the Draw methods are only available in the sessions, so you have to work under the canvasControl_Draw event. I tried nesting it under my button_Click event but it would not work.

**Comment by damyanp** [comment]
You could draw to an [offscreen render target](http://microsoft.github.io/Win2D/html/Offscreen.htm) and then have your control's draw handler just draw the render target.

Or, if you have other controls that specify the parameters for your geometric shapes then you could just hook call Invalidate() when these change and update accordingly.

**Comment by thecobblersdaughter** [comment]
Both of those seem like they may work for a solution. Is there a good C# compilable solution that uses those? I read the link you posted, but working examples I feel are easier to learn from.

**Comment by damyanp** [comment]
Have you looked at the [Win2D samples](https://github.com/Microsoft/Win2D-Samples)?  There's all sorts of techniques demonstrated within them.

**Comment by thecobblersdaughter** [comment]
I had but did not see an example of the off screen render target or invalid, but I did not look hard. Do you off hand  know of specific examples to look at?

**Comment by 13thsymphony** [comment]
You can find instances of Invalidate():
https://github.com/Microsoft/Win2D-Samples/search?utf8=%E2%9C%93&q=invalidate+language%3Ac%23&type=Code

and creating and rendering to a new offscreen CanvasRenderTarget:
https://github.com/Microsoft/Win2D-Samples/search?utf8=%E2%9C%93&q=new+CanvasRenderTarget+language%3Ac%23&type=Code

**Comment by thecobblersdaughter** [comment]
Thats a lot of good information. I tried going straight from the Offscreen Render Target documentation, but I seem to be having trouble issuing the commands to draw to the target.

        static CanvasDevice device = CanvasDevice.GetSharedDevice();
        CanvasRenderTarget offscreen = new CanvasRenderTarget(device, 100, 100, 96);
        using (CanvasDrawingSession ds = offscreen.CreateDrawingSession())
        {
            ds.Clear(Colors.Black);
            ds.DrawRectangle(100, 200, 5, 6, Colors.Red);
        }

Under the using keyword, VS doesn't recognize my offscreen object that was created on the prior line.

**Comment by damyanp** [comment]
This doesn't look like valid C# - you cannot have "static" local variables.  Can you provide an example more clearly showing the code you're having trouble with.

Also, please can you provided a clearer description of the error message that you are seeing, and where you see it.  "VS doesn't recognize" could mean many different things.

**Comment by thecobblersdaughter** [comment]
If I were to copy paste directly from the offscreen render target in the documentation,

        CanvasDevice device = CanvasDevice.GetSharedDevice();
        CanvasRenderTarget offscreen = new CanvasRenderTarget(device, width, height, 96);
        using (CanvasDrawingSession ds = offscreen.CreateDrawingSession())
        {
            ds.Clear(Colors.Black);
            ds.DrawRectangle(100, 200, 5, 6, Colors.Red);
        }

It gives the following errors:

Severity	Code	Description	Line
Error	CS1513	} expected	49
Error	CS1002	; expected	50
Error	CS1022	Type or namespace definition, or end-of-file expected	50
Error	CS1002	; expected	50
Error	CS1022	Type or namespace definition, or end-of-file expected	50
Error	CS0116	A namespace cannot directly contain members such as fields or methods	52
Error	CS1022	Type or namespace definition, or end-of-file expected	52
Error	CS0116	A namespace cannot directly contain members such as fields or methods	52
Error	CS1022	Type or namespace definition, or end-of-file expected	52
Error	CS0116	A namespace cannot directly contain members such as fields or methods	53
Error	CS1022	Type or namespace definition, or end-of-file expected	53
Error	CS0116	A namespace cannot directly contain members such as fields or methods	53
Error	CS1022	Type or namespace definition, or end-of-file expected	53
Error	CS1022	Type or namespace definition, or end-of-file expected	55
Error	CS1022	Type or namespace definition, or end-of-file expected	56
Error	CS0236	A field initializer cannot reference the non-static field, method, or property 'MainPage.device'	49
Error	CS0103	The name 'width' does not exist in the current context	49
Error	CS0103	The name 'height' does not exist in the current context	49
Error	CS0103	The name 'offscreen' does not exist in the current context	50
Error	CS1061	'MainPage' does not contain a definition for 'canvasControl_Draw' and no extension method 'canvasControl_Draw' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	12

**Comment by thecobblersdaughter** [comment]
I was assuming that adding a static keyword would be using the GetSharedDevice as a static method, without creating an instance of the CanvasDevice class. It seemed to clear up the CS0236 error.

**Comment by damyanp** [comment]
Here's some sample code to get you started.  I suggest you try and fully understand what this is doing before continuing.

In your .XAML file:

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <canvas:CanvasControl Draw="CanvasControl_Draw" CreateResources="CanvasControl_CreateResources" Name="canvasControl"/>
        <Button Content="Stuff" Click="Button_Click" />
    </Grid>

In your .XAML.CS file:

    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        Random rng = new Random();
        CanvasRenderTarget renderTarget;

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            var x = rng.NextDouble() * renderTarget.Size.Width;
            var y = rng.NextDouble() * renderTarget.Size.Height;

            using (var ds = renderTarget.CreateDrawingSession())
            {
                ds.DrawCircle((float)x, (float)y, 50, Colors.Red);
            }

            canvasControl.Invalidate();
        }

        private void CanvasControl_Draw(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args)
        {
            args.DrawingSession.DrawImage(renderTarget);
        }

        private void CanvasControl_CreateResources(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
        {
            renderTarget = new CanvasRenderTarget(sender, (float)sender.ActualWidth, (float)sender.ActualHeight);
        }
    }
