### ISSUE TITLE
DrawText doesn't correctly position translated text (+workaround)

### ISSUE THREAD

**Issue by crashd0wn** [Microsoft/Win2D#320]
When drawing text to 0,0 using a transformation matrix which contains translation values greater than 0, the text seems to be incorrectly aligned to an invisible grid and is wrongly positioned in the y dimension (e.g. it will be positioned correctly horizontally, but the vertical position moves "line by line" instead of using the exact value in the matrix). The problem disappears when a rotation is set in the matrix. So my workaround is to set the rotation to 0.0001f, and it will render the transformation correctly. Note that this problem also appears when the rotation in the matrix is dividable by PI/2.0f, in that case it will affect the x dimension. 
If necessary I will try to provide sample code to reproduce. Version used is latest stable for UWP (1.16.0).

**Comment by shawnhar** [comment]
This is an intentional behavior - by default, text rendering optimizes for clarity and readibility of the glyphs by snapping to whole pixel boundaries.

For text that is being animated, you can disable this snapping by specifying CanvasDrawTextOptions.NoPixelSnap (in your CanvasTextFormat).

**Comment by crashd0wn** [comment]
Thank you for clearing that up. Part of the problem was that I am using a scaled camera matrix on top of everything, so that multiplied the pixel snapping effect by a LOT. I was looking around the options, but wasn't sure what I was looking for, and didn't realize that DrawText uses pixel snapping by default. Sorry for the erroneus bug report in that case, seems to be indeed a feature! :-)
