### ISSUE TITLE
Question : XBox One

### ISSUE THREAD

**Issue by BubblegumYeti** [Microsoft/Win2D#321]
Hi!

Well since MS demoed developer mode on XBox One at Build yesterday... does Win2D work on XBox One?

**Comment by shawnhar** [comment]
Xbox One Dev Mode runs standard UWP apps, so any UWP technology (including Win2D) should work there.  That said, I'm not sure if anyone has actually tried running Win2D on the console yet.  If you're interested in using this, give it a whirl and please let us know what you find!

**Comment by shawnhar** [comment]
We just tried it this afternoon, and are happy to report that Win2D works great on Xbox!   Example Gallery has a few UI issues (as it was designed for touch and/or mouse+keyboard interaction rather than a console gamepad) but everything seems quite usable.

**Comment by BubblegumYeti** [comment]
Ok great... Thanx.
