### ISSUE TITLE
Clipping via CreateLayer

### ISSUE THREAD

**Issue by Petititi** [Microsoft/Win2D#322]
Following suggestions made by @shawnhar I replaced every 
```C#
var clip = session.CreateLayer(1.0F, CanvasGeometry.CreateRectangle(session, rectangle));
...DoDrawing...
clip.Dispose();
```
with:
```C#
var clip = session.CreateLayer(1.0F, rectangle);
...DoDrawing...
clip.Dispose();
```
But it seems that in release mode the clipping is not working properly. Sometime there is no clipping at all! Have you any idea of what I should do?

**Comment by shawnhar** [comment]
Please share a repro app (simplified as far as you can) that shows what you are trying to do and what is going wrong.

**Comment by shawnhar** [comment]
I'm going to close this issue because we don't have enough info to do anything useful with it.  Please reactivate if you are able to provide a repro app.

Thanks!
