### ISSUE TITLE
CanvasAnimatedControl sawteeth memory behavior

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Win2D#327]
I have created a Tiled Map reader and I paint several layers in the screen, I have optimized it the most I can. When I add the draw method to paint the layers like:

public static void Draw(CanvasSpriteBatch spritebatch, Layer[] layers)
        {
            var bitmap = Game.BitmapsSources[0];

            int width = layers[0].TilesWidth;
            int height = layers[0].TilesHeight;

            for (int i = 0; i < width; i++)
            {
                for (int j = 0; j < height; j++)
                {
                    int id = i + j * width;
                    for (int k = 0; k < layers.Length; k++)
                    {
                        if (layers[k].Data[id] > 0)
                        {
                            var pos = new Vector2(i * 16, j * 16);
                            var source = layers[k].Source[id];
                            spritebatch.DrawFromSpriteSheet(bitmap, pos, source);
                        }
                    }
                }
            }
        }

I have in the diagnostics memory session the following behavior:
It began to grow from 20 to 128 MB aprox  in about 20 secs, after that garbage collection happens and the cycle starts again, Is that the normal behavior? Should I force the GC every few seconds?

**Comment by shawnhar** [comment]
It is normal to see that kind of sawtooth memory usage graph when using a garbage collected runtime such as .NET.  The amplitude of the saws are determined by how much memory is available (GC will only run when this gets low), and frequency is determined by how much garbage your application creates.

This is only a problem if you are creating so much garbage that GC becomes a significant overhead, affecting performance of your app (there will almost always be some garbage when using .NET).

If this is a problem for your performance, the first step is to narrow down what part of the app is causing the garbage.  Binary search commenting out different parts of your code is a good first step for that.

It's almost never a good idea to force GC.  The system does a good job deciding when to run a collection - it won't benefit from you trying to override that.

**Comment by juanpaexpedite** [comment]
Ah ok so everything is fine, I tested on Mobile and the times is about 20secs and the GC acts with 100MB so thank you for the explanation, a thank you a lot for creating the CanvasAnimatedControl, in just few hours I made a parser for Tiled and painted in the Screen. so you can close this.

**Comment by shawnhar** [comment]
Glad to hear everything is working ok!
