### ISSUE TITLE
draw real-time data in a cartesian chart

### ISSUE THREAD

**Issue by gpunkt2016** [Microsoft/Win2D#328]
Hi all,
I have to draw real-time data as a line in a cartesian chart. I was recommended to use Win2D. Could anyone give a hint where I could find an example for this?

Regards
gpunkt2016

**Comment by shawnhar** [comment]
The Example Gallery app includes many examples of drawing different kinds of shape using Win2D.

Start with a CanvasControl, then use DrawLine for simple things, or CanvasPathBuilder+CanvasGeometry if you need to create more complex shapes.

**Comment by shawnhar** [comment]
Closing issue as I believe this question has been answered.  Feel free to reactivate if you need further information.
