### ISSUE TITLE
Question - Two CanvasAnimatedControls

### ISSUE THREAD

**Issue by S1gd** [Microsoft/Win2D#329]
Are there any potential problems with having two CanvasAnimatedControls on my application form (UWA/C#/XAML).  I hoping/assume they will run on separate dedicated threads independently?

I'm planning on one default (60fps) and one custom (~4fps), and I also have a CanvasControl occasionally being redrawn via Invalidate().

Many thanks for any help.

**Comment by shawnhar** [comment]
A couple of animated controls should be ok, but in general if things aren't running at interactive animated framerates my instinct would be to start with a regular CanvasControl for the one with low update frequency.  It'll likely work fine either way, though.

**Comment by shawnhar** [comment]
Closing issue as I believe this question has been answered.  Feel free to reactivate if you need further information.
