### ISSUE TITLE
Question: animating a CanvasVirtualControl?

### ISSUE THREAD

**Issue by robert-virkus** [Microsoft/Win2D#330]
Hi everyone,

what would be the best way to animate a CanvasVirtualControl? I can of course call Invalidate() repeatedly but that would not create a smooth animation.
I cannot extend the sealed class CanvasVirtualControl  and as such implement ICanvasAnimatedControl.

My use case is that I want to visualize user interactions on my CanvasVirtualControl, e.g. zoom into a specific element rather than just displaying the element details on another page.

Thanks in advance,
yours
    Robert

**Comment by shawnhar** [comment]
Calling Invalidate is indeed the best way to animate a virtual control (same as for the regular CanvasControl).

**Comment by robert-virkus** [comment]
Thanks for your feedback, Shawn! Could I maybe realize this the other way round, i.e.  virtualize a CanvasAnimatedControl?

**Comment by shawnhar** [comment]
> Could I maybe realize this the other way round, i.e. virtualize a CanvasAnimatedControl?

No.  CanvasAnimatedControl renders using a Direct3D swapchain, which is not a virtualized way of displaying graphics.   CanvasVirtualControl is built on top of the XAML/DComp VirtualSurfaceImageSource feature, which is a very different path designed for virtualizing large images.

The correct way to animate a CanvasVirtualControl is by calling Invalidate when you want to redraw with a different image.  What is your resistance to that approach?  Have you tried it?

**Comment by robert-virkus** [comment]
Hi Shawn, thanks again, I'll try to invalidate my way through this ;-) 

My resistance is that I want to achieve smooth animation like blending in images and I fear that this will be very hard to achieve using invalidate.

Thanks a lot for explaining the difficulties to me and keep up the good work!
Robert

**Comment by shawnhar** [comment]
Closing issue as I believe this has been addressed.  Feel free to reactivate if you have further questions.
