### ISSUE TITLE
Flickering in CanvasAnimatedControl

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Win2D#331]
I am trying to paint some layers then shadow rectangles and then more layers, the most accurate way I found is the following:

    private void Representation_Draw(ICanvasAnimatedControl sender, CanvasAnimatedDrawEventArgs args)
    {
    args.DrawingSession.Transform = Camera.Transform;

    using (var sb = args.DrawingSession.CreateSpriteBatch(CanvasSpriteSortMode.None, CanvasImageInterpolation.NearestNeighbor, CanvasSpriteOptions.None))
    {
        SpriteDraw(sb);
        CanvasDraw(args.DrawingSession); // Makes flickering 
        SpriteDraw(sb,false); //Would like to paint more tile  layers above the rectangles
       }
    CanvasDraw(args.DrawingSession); // Works fine here (above everyting)
    }
    public virtual void CanvasDraw(CanvasDrawingSession session)
    {
    session.FillRoundedRectangle(new Rect(2 * Game.TileWidth, 2 * Game.TileHeight + 4, 2 * Game.TileWidth + 8, 2 * Game.TileHeight + 8), 12f, 12f, Color.FromArgb(32, 0, 0, 0));
    }

Where SpriteDraw just uses spriteBatch.DrawFromSpriteSheet. 

Is it possible to split the draw in someway to achieve the different parts. Thanks

**Comment by damyanp** [comment]
If you want to draw some sprites, draw something else and then draw some more sprites then you'll need to use multiple sprite batches:

    using (var sb1 = args.DrawingSession.CreateSpriteBatch(...))
    {
        SpriteDraw(sb1);
    }

    CanvasDraw(...);

    using (var sb2 = args.DrawingSession.CreateSpriteBatch(...))
    {
        SpriteDraw(sb2);
    }

**Comment by juanpaexpedite** [comment]
I was trying to keep the SpriteBatch and I did not think about making several of them, thank you a lot.

**Comment by damyanp** [comment]
No problem!  I'm closing this issue as I think it has been answered, but feel free to reopen it if this isn't the case.
