### ISSUE TITLE
Blurry images when combined with Viewbox

### ISSUE THREAD

**Issue by klootas** [Microsoft/Win2D#333]
Hi there,
I got a XAML based game that renders inside a Viewbox for flexible scaling scenarios. XAML lets me show high resolution images in a lower than resolution size, allowing them to scale nicely on different screen sizes. Doing the same with Win2D results in blurry images.

I attached a small repro to this post (also avalable here): https://onedrive.live.com/redir?resid=F735600E1FBEFF6C!874831&authkey=!AEOxVG91Jc6c5fQ&ithint=file%2czip

Any help is greatly appreciated :)
[Win2DTest.zip](https://github.com/Microsoft/Win2D/files/235453/Win2DTest.zip)

**Comment by shawnhar** [comment]
This app is working exactly like I'd expect.

Your CanvasAnimatedControl is inside a Grid which is set to size 600x300.   The CanvasAnimatedControl inherits its size from the parent container, thus is also sized 600x300.  That's the resolution your Win2D graphics are drawn at.

Then you place this grid inside a Viewbox set to Stretch=Uniform.  So the Viewbox scales up its contents to fill whatever larger area the app window is sized to.   Scaling up bitmap graphics causes blurriness.

The solution is increase the size of your CanvasAnimatedControl to match the actual size at which its contents will eventually be displayed.  The most common way to do that is just not to use a Viewbox at all.  The purpose of Viewbox is to scale fixed size content to some other size, but in this case you actually want your Win2D content to be the same size as the window, which means you want the CanvasAnimatedControl to resize whenever the window does.  Placing it inside a Viewbox (and specifying a fixed size for your Grid) is preventing that.

**Comment by shawnhar** [comment]
Closing issue as I believe this has been answered.  Feel free to reactivate if you have further questions.
