### ISSUE TITLE
Drawings not complete

### ISSUE THREAD

**Issue by SebastianStehle** [Microsoft/Win2D#334]
Hi, I use the VirtualCanvasControl. I realized that sometime the drawings are not complete. For example:

![drawing](https://cloud.githubusercontent.com/assets/1236435/14825297/907230a0-0bd9-11e6-949c-bbf34be69c48.png)

The blue lines are bounding boxes for debugging purposes. After the next Invalidate it renders correctly. This also happens to other parts of the scene from time to time.

![drawing](https://cloud.githubusercontent.com/assets/1236435/14825353/d36e64d2-0bd9-11e6-9e5b-43c54df0ba92.png)

Do you have any idea?

**Comment by damyanp** [comment]
Is the problem that the bounding boxes aren't always being drawn?  It looks like it is just the bounding boxes that have a problem here - the actual non-debugging drawing looks correct. 

I suggest you try clearing to a different color so you can visualize each region that gets drawn to see if this could help explain what is happening.

**Comment by SebastianStehle** [comment]
You are right, this is the issue, very stupid. I do the following: Whenever a node is within the region, I render the node and the bounding box around the node and the parent. 

But for the other region, when the parent is inside but no the node I do not render the bounding box. Makes sense and is okay for debugging purposes. Sorry for being stupid :D

**Comment by damyanp** [comment]
I'm closing this as I think that this issue has been addressed.  Feel free to reopen if you have further questions!
