### ISSUE TITLE
Drawing filled figures produces visible borders regardless of CanvasBlend setting.

### ISSUE THREAD

**Issue by andriysavin** [Microsoft/Win2D#335]
My scenario is drawing simple shapes to a bitmap (RT) for later overlaying one over a map (2-steps rendering). I use CanvasDrawingSession.FillGeometry for that. While I don't use semitransparency in shape colors, I've noticed that edges are smoothed to blend with background nicely. This takes place **even if anti-aliasing is disabled**. This smoothing results in semitransparent pixels on the edges. My expectation for this effect was that these pixels should blend with the map (background), taking some value of its pixels using smoothed pixels' alpha. Knowing that a 2-steps blending is a tricky thing, I clear the render target with transparent color and set Blend to CanvasBlend.Copy before drawing. However, **the resulting edges look like if I used CanvasBlend.SourceOver - the edge pixels seem to be blended with black background** (which is the transparent color after premultiplication) - they look grey, while I shouldn't see them at all.
 
I should add that if I make the color of a shape semitransparent, the shape's body is rendered correctly (saving its values and becoming semitransparent over the map as expected), while its edges still don't.

Here is the result of such rendering:
![capture](https://cloud.githubusercontent.com/assets/12996633/14865686/6f1d9792-0cc8-11e6-9369-0548deb19b8c.PNG)

**Comment by damyanp** [comment]
Please share a repro app (simplified as far as you can) that shows what you are trying to do and what is going wrong.

**Comment by andriysavin** [comment]
I'll try to, probably in 1 day.

**Comment by andriysavin** [comment]
Investigated this deeply and I think its some bug in Maps Control which possibly does some textures compression or filtering, producing that strange transparency noise on edges. Win2D outputs perfect image, so false alarm, sorry!
