### ISSUE TITLE
VirtualCanvasControl Invalidate not working

### ISSUE THREAD

**Issue by BertschInnovation** [Microsoft/Win2D#336]
The VirtualCanvasControl ignores calling Invalidate(). The InvalidateRegions Event is only called ones at the beginning, but never after calling Invalidate().

Win2D 1.17 from nuget
Target: Win 10 UWP

**Comment by damyanp** [comment]
It seems to work for me.  Please share a repro app (simplified as far as you can) that shows what you are trying to do and what is going wrong.

**Comment by BertschInnovation** [comment]
I figured it out: The Handler is only called if the view is not collapsed.
