### ISSUE TITLE
Question: Recording Win2D games

### ISSUE THREAD

**Issue by BubblegumYeti** [Microsoft/Win2D#337]
I am looking for a way to record my gameplay so I can publish videos on website etc... Anybody has found a good way of doing that? I tried with XBox W10 app, but that one seems to think my window is not displaying anything.

**Comment by 13thsymphony** [comment]
What exactly do you see when you attempt to use the GameDVR feature to record your Win2D app? If I try it on the Win2D Example Gallery, I successfully get a recording. All UWPs should be fully compatible with GameDVR.


1. Launch app
2. Press Win+G
3. Select "Yes, this is a game"
4. Select the Record option

**Comment by BubblegumYeti** [comment]
Hmmm... i just get a popup that nothing is happening. Guess I will have a look at the Win2D gallery tomorrow.

**Comment by shawnhar** [comment]
Hi, I'm going to close this as we've not been able to reproduce the problem.  Feel free to reactivate if you have more details of your config or what the app is doing so we can understand why recording isn't working for you.
