### ISSUE TITLE
Why Win2D XAML elements reference counting is different to other WinRT controls?

### ISSUE THREAD

**Issue by andriysavin** [Microsoft/Win2D#339]
This is just a question, but probably also a suggestion for clarification in the docs. I've recently read [the article about memory leaks](http://microsoft.github.io/Win2D/html/RefCycles.htm) and now I'm curios why other WinRT XAML controls aren't subject for these problems? AFAIK they are unmanaged classes too, they get wrapped in RCWs, and these should somehow handle passing references to the methods - like in case with event subscription - and detect cycles. I don't have to explicitly unload such child controls and remove references to them. In other words, they _look_ susceptible to the same scenarios like described in the article, but they're not. How Win2D controls are different in this case?

**Comment by shawnhar** [comment]
XAML and the CLR have intimate knowledge of each other, so the CLR garbage collector is able to trace internal references through the native code XAML implementation.  Unfortunately the mechanism used to do that is not sufficiently general purpose to be reused by other frameworks like Win2D.

**Comment by andriysavin** [comment]
@shawnhar thank you for clarification!
