### ISSUE TITLE
Scaling image brush centered

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Win2D#340]
I want to create a grid with tile size of 128, 128 (I only paint the first rectangle to simplify).
(The source image is 34x34, I added pixel transparent around (32x32) to avoid the clamping lines).
Then I want to scale the sourceImage to make it grow

    private void BackgroundCanvas_Draw(ICanvasAnimatedControl sender, CanvasAnimatedDrawEventArgs args)
    {
        var size = new Rect(new Point(), sender.Size);
        var session = args.DrawingSession;

        session.Clear(Colors.Black);

        var tox = size.Width / tilesize;
        var toy = size.Width / tilesize;

        var rect = new Rect(0,0, 128, 128);
        session.FillRectangle(rect, backgroundBrush);
    }

Now in the update event I scale the source of the rectangle (the backgroundBrush):

    private void BackgroundCanvas_Update(ICanvasAnimatedControl sender, CanvasAnimatedUpdateEventArgs args)
    {
        if (!this.resourcesLoaded)
        {
            return;
        }

        scale += 0.001f;
        backgroundBrush.Transform = Matrix3x2.CreateTranslation(new Vector2(48,48)) * 
            Matrix3x2.CreateScale(scale,new Vector2(-scale*10,-scale*10));
    }

But I do not know how keep the image and scaled image centered in the Rectangle, I have tried several combinations but no success, any idea?

**Comment by shawnhar** [comment]
Matrix.CreateScale has an overload that lets you specify what point to scale around - and indeed you are calling that overload, but you are passing a strange value as the center.

If your image is 34x34, and you have first translated it by (48,48), it's center will now be (65,65), not (-scale*10,-scale*10).

**Comment by juanpaexpedite** [comment]
Thank you, yes I was trying to get by lucky the value.
And now is the following really strange, because it only fills the first rectangle with the brush not the rest (but all the red ones are painted) (even not applying any transform):

    private void BackgroundCanvas_Draw(ICanvasAnimatedControl sender, CanvasAnimatedDrawEventArgs args)
    {
        var size = new Rect(new Point(), sender.Size);
        var session = args.DrawingSession;

        session.Clear(Colors.Black);

        var tox = Math.Ceiling(size.Width / tilesize);

        for (int i = 0; i < tox; i++)
        {
            var rect = new Rect((tilesize + 6) * i, 0, tilesize, tilesize);
            session.FillRectangle(rect, Colors.Red);
            session.FillRectangle(rect, backgroundBrush);
        }
    }

**Comment by shawnhar** [comment]
You need to apply a brush transform to move your image to the same location as each tile (or change brush edge behavior from Clamp to Wrap).  As it stands, your brush has the image positioned near the origin, but you are drawing tiles far away from the origin, way past the edge of the image, so you get just the clamped transparent border of the image.

**Comment by juanpaexpedite** [comment]
Understood, thank you a lot for guiding, I though that is was something relative or like that. Now it is painting fine.

**Comment by shawnhar** [comment]
Glad to hear you got this working!
