### ISSUE TITLE
way to get the image uv and sampler2D in a hlsl custom effect?

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Win2D#342]
I do not know too much about shaders, so really sorry for that, this is my first attempt and what I understand from the example files is that are defined some input values that are used and at the end the processed value is returned.

I want to create a pixelation effect but I do not know how to get the image pixel in this case. I understand it is a bit different because I have to use D2D_PS_ENTRY instead of the comment:

    //float4 main(float2 uv : TEXCOORD) : COLOR
    D2D_PS_ENTRY(main)

So how I begin with that because then I have to use it to be able to create the effect:

    #define D2D_INPUT_COUNT 3
    #define D2D_INPUT0_SIMPLE
    #define D2D_INPUT1_SIMPLE
    //#define D2D_INPUT2_COMPLEX ? Do I need it or get from the method instead of the following line?
    //sampler2D implicitInputSampler : register(S0); this is from the original example

    #include "d2d1effecthelpers.hlsli"
    D2D_PS_ENTRY(main)
    {
    float HorizontalPixelCounts = D2DGetInput(0);
    float VerticalPixelCounts = D2DGetInput(1);
    //sampler2D implicitInputSampler = register(2);

    float2 brickCounts = { HorizontalPixelCounts, VerticalPixelCounts };
    float2 brickSize = 1.0 / brickCounts;
    
    float2 offsetuv = uv; //How do I get this from the code?
    bool oddRow = floor(offsetuv.y / brickSize.y) % 2.0 >= 1.0;
    if (oddRow)
    {
        offsetuv.x += brickSize.x / 2.0;
    }

    float2 brickNum = floor(offsetuv / brickSize);
    float2 centerOfBrick = brickNum * brickSize + brickSize / 2;

    //float4 color = tex2D(implicitInputSampler, centerOfBrick); 
    float4 color = tex2D(D2DGetInput(2).rgb, centerOfBrick);

    return color;
    }

I know it is not a complex effect and if I understand how to get this work then I would able to create any effect. Thank you in advance.

**Comment by shawnhar** [comment]
Start with these docs:

https://msdn.microsoft.com/en-us/library/windows/desktop/dn879811%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Effects_PixelShaderEffect__ctor.htm

**Comment by juanpaexpedite** [comment]
Those are really interesting documents, I have just made my first shader with onetoone and one parameter changing the red tone of each pixel (yes might sound dumb but it is really cool). 

Now I am using COMPLEX and D2DSampleInputAtPosition to get just the pixels I want, to test I am returning always the float4 at float2(0,0) (just to test)

    #define D2D_INPUT_COUNT 1
    #define D2D_INPUT0_COMPLEX

    #include "d2d1effecthelpers.hlsli"

    D2D_PS_ENTRY(main)
    {
        float2 inputScenePosition = float2(0,0);
        return D2DSampleInputAtPosition(0, inputScenePosition);
    }

But when I compile receive: error X3004: undeclared identifier '__d2dstatic_scenePos'

I am reading the example and they return that values without making any conversions because it is a float4 the value it returns, isn't it? what is wrong? Sorry.

**Comment by juanpaexpedite** [comment]
Thank you I really love that documentation and now I understand how they work, this is what I did for pixelation (apart other examples I test):

    #define D2D_INPUT_COUNT 1
    #define D2D_INPUT0_COMPLEX
    #define D2D_REQUIRES_SCENE_POSITION
    #include "d2d1effecthelpers.hlsli"

    int Level = 8;

    D2D_PS_ENTRY(main)
    {
        float2 pos = D2DGetScenePosition().xy;

        int x = pos[0]/Level;
        int y = pos[1]/Level;
        float2 inputScenePosition = float2(x * Level,y * Level);
        return D2DSampleInputAtPosition(0, inputScenePosition);
    }

And in case someone needs the C# part:

     public static ICanvasImage UsePixelation(CanvasRenderTarget rendertarget, int level)
        {
            var effect = new PixelShaderEffect(File.ReadAllBytes("pixelation.bin"))
            {
                Source1 = rendertarget,
                Source1Mapping = SamplerCoordinateMapping.Unknown
            };
            effect.Properties["Level"] = level;
            return effect;
        }

Works like a charm, thanks a lot.

**Comment by shawnhar** [comment]
Nice, glad to hear you got this working!
