### ISSUE TITLE
Replace Colors

### ISSUE THREAD

**Issue by HelgeKeck** [Microsoft/Win2D#344]
Hi,

i have a white colored Icon on a CanvasBitmap and i want to colorize it. what is the best way to do it?

Thanks

Helge

**Comment by shawnhar** [comment]
The most flexible approach is to feed the image through a ColorMatrixEffect (http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Effects_ColorMatrixEffect.htm).

Another option is to use CanvasSpriteBatch (http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasSpriteBatch.htm)

**Comment by HelgeKeck** [comment]
Thanks, i tried it with a ColorMatrixEffect but have Problems with the Edges of the Image, looks very pixelated. gogin to test it with a CanvasSpriteBatch

**Comment by shawnhar** [comment]
> have Problems with the Edges of the Image, looks very pixelated

That likely means your AlphaMode is set wrong, or the matrix you are using does not properly handle the chosen alpha format.

Feel free to post details here - we'd be happy to help.

**Comment by HelgeKeck** [comment]
thanks, this is what im using:

ColorMatrixEffect Color_Matrix;
CanvasBitmap myCanvasBitmap;
.....
Color_Matrix = new ColorMatrixEffect 
{
    Source = myCanvasBitmap,
    ColorMatrix = MakeColorMatrix(Color.Red)
};


        private Matrix5x4 MakeColorMatrix(Color color)
        {
            var m = new Matrix5x4()
            {
                M11 = color.R, M12 = 0, M13 = 0, M14 = 0,
                M21 = 0, M22 = color.G, M23 = 0, M24 = 0,
                M31 = 0, M32 = 0, M33 = color.B, M34 = 0,
                M41 = 0, M42 = 0, M43 = 0, M44 = color.A,
                M51 = 0, M52 = 0, M53 = 0, M54 = 0,
            };
            return m;
        }

**Comment by shawnhar** [comment]
The problem here is that you are unintentionally scaling up the color values by a factor of 255.

Windows.UI.Color fields (.R, .A, etc) range 0-255, but you are copying their values directly into a Matrix5x4 where they are used as floating point scale factors.  If the Windows.UI.Color value was 255, you probably want to leave that color channel alone, so you want a 1.0f in the Matrix5x4.

**Comment by HelgeKeck** [comment]
thanks, i think i understand whats the Problem, but im not sure where to put the 1.0f into my Matrix. could you help me?

**Comment by shawnhar** [comment]
To tint an image red for instance, your matrix should be:

    ( 1, 0, 0, 0,
      0, 0, 0, 0,
      0, 0, 0, 0,
      0, 0, 0, 1,
      0, 0, 0, 0 )

or to tint it green:

    ( 0, 0, 0, 0,
      0, 1, 0, 0,
      0, 0, 0, 0,
      0, 0, 0, 1,
      0, 0, 0, 0 )

**Comment by HelgeKeck** [comment]
ok, i got it now :)
 im using this now, to have the possibilty to use the Color i want. 

        private Matrix5x4 MakeColorMatrix(Color color)
        {
            var m = new Matrix5x4()
            {
                M11 = (float)(color.R / 255), M12 = 0, M13 = 0, M14 = 0,
                M21 = 0, M22 = (float)(color.G / 255), M23 = 0, M24 = 0,
                M31 = 0, M32 = 0, M33 = (float)(color.B / 255), M34 = 0,
                M41 = 0, M42 = 0, M43 = 0, M44 = 1.0f,
                M51 = 0, M52 = 0, M53 = 0, M54 = 0,
            };
            return m;
        }

i dont know if it is well done, but it works

thank you

**Comment by HelgeKeck** [comment]
ok, im stupid. just have seen this works only on full Colors. going to figure it ou

**Comment by shawnhar** [comment]
You are doing the division on integer values, then casting that integer result to a float.  But any integer less than 255, when divided by 255, will round down to zero.  You need to convert to float before dividing, not after.

Use (float)color.R / 255 instead, or color.R / 255.0f.

**Comment by HelgeKeck** [comment]
i have already realized it, thanks again for your help. it is working now

**Comment by shawnhar** [comment]
Glad to hear you got this working.
