### ISSUE TITLE
VirtualCanvasControl too much work in RegionsInvalidated?

### ISSUE THREAD

**Issue by BertschInnovation** [Microsoft/Win2D#347]
Hi,

I'm trying to render a zoomable PDF in ScrollViewer/VirtualCanvasControl.
I'm using the `CanvasRegionsInvalidatedEventArgs.VisibleRegion` to just render the part of the PDF that is visible to prevent blurred images. But everytime the ZoomFactor is 2 or higher, the RegionsInvalidated Event is looping.
In some test I figured that rendering the PDF inside the` OnRegionsInvalidated` Method seems to much work? How long can a DrawSession last?

**Comment by shawnhar** [comment]
Please give more detail of what your code is doing.

You don't have to draw directly inside the regions invalidated event.  That's just a notification - it will be raised any time there is a visibility change, informing you whatever region(s) are now visible and have not yet been draw to.

If you are moving drawing across different threads, see the notes here: http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_UI_Xaml_CanvasVirtualControl_CreateDrawingSession.htm

**Comment by BertschInnovation** [comment]
Here is my code:
		        private bool drawing = false;
			 private async void OnRegionInvalidated(CanvasVirtualControl sender, CanvasRegionsInvalidatedEventArgs args)
			                  {

            if (page == null) return;

            if (drawing) return;

            drawing = true;
 
            var ds = sender.CreateDrawingSession(args.VisibleRegion);
            sender.SuspendDrawingSession(ds);

            var image = await RenderPDF(args.VisibleRegion);

            sender.ResumeDrawingSession(ds);
            ds.DrawImage(image, args.VisibleRegion);

            ds.Dispose();

            drawing = false;
			}
		
			public Task<CanvasBitmap> RenderPDF(Rect rect)
			{
            return Task.Run(async () =>
            {
                PdfPageRenderOptions options = new PdfPageRenderOptions();
                options.DestinationHeight = (uint)rect.Height;
                options.DestinationWidth = (uint)rect.Width;
                options.SourceRect = rect;

                var output = new MemoryStream().AsRandomAccessStream();
                await page.RenderToStreamAsync(output, options);

                var image = await CanvasBitmap.LoadAsync(PdfCanvas, output);

                return image;
            });
			}

**Comment by shawnhar** [comment]
And what exactly is the problem you see when running this code?

Only issue I see is that you will discard invalidated regions if a second RegionsInvalidated event occurs while you are in the middle of processing the first one.

**Comment by BertschInnovation** [comment]
The problem is that the Canvas is inside a ScrollViewer, and if I zoom more than factor 2, the `OnRegionInvalidated` is called over and over.

**Comment by pellea** [comment]
You probably got this error because you are using the async/await pattern. Use the current page/frame/control `Dispatcher` to run  `ds.DrawImage(image, args.VisibleRegion);`

**Comment by BertschInnovation** [comment]
@pellea How would I do that? Can you provide a little code?

**Comment by BertschInnovation** [comment]
Okay, I managed to get rid of the "cannot create drawing session" error by getting rid of async await and running the `draw`-Methods via Dispatcher. 
But the looping of the RegionsInvalidated Event still persists.

**Comment by shawnhar** [comment]
The RegionsInvalidated event is a notification that the virtual control wants access to part of the image data that you have not yet drawn.  It's up to you whether to draw the requested regions directly inside that event handler, or defer drawing them until later, or even decide not to draw them at all for whatever reason, but if you don't draw all the requested regions, you will keep getting more RegionsInvalidated events every time the control does something that wants to use the still-not-available image data.

There are three reasons why your implementation will be getting multiple RegionsInvalidated events:

1. You defer actual drawing work until after the event handler has returned, which means you may get more events while the drawing is still in progress.  This is expected when you defer drawing, and a fine thing to happen, but when you choose to do this you need to make sure your implementation is robust against it happening.

2. You are discarding events that occur while a previous draw is in progress.  That's not correct, as the event is telling you that another region of the image needs to be drawn!  You can't draw more than one thing at the same time, so you'll need to queue up these requests and make sure you process them after the previous draw has completed.

3. You are drawing to args.VisibleRegion, but should be using args.InvalidatedRegions  (see eg. http://microsoft.github.io/Win2D/html/E_Microsoft_Graphics_Canvas_UI_Xaml_CanvasVirtualControl_RegionsInvalidated.htm)

**Comment by shawnhar** [comment]
Closing issue as I believe this has been answered.  Feel free to reactivate if you have further questions.
