### ISSUE TITLE
Render CanvasGeometry Path performance question

### ISSUE THREAD

**Issue by michael-spinelli** [Microsoft/Win2D#348]
I've been fiddling with a project here:  https://github.com/michael-spinelli/Renderer2525C-W10-UWP
I basically have a bunch of SVG data that I parse beforehand and create a bunch of canvasGeometires via CanvasPathBuilder and store them in a Dictionary.  I then render them on request.

I have a regular C# project and I use System.Drawing.GraphicsPath to do the same exact thing except it performs significantly better.  Is CanvasGeometry rendering performance not a strong suit for Win2D?

In my tester I have a toggle in the code where it will draw the same symbol 10,000 times.  Using win2D it takes about 6 second to render.  Using GraphicsPath it takes about 2.5 seconds.  For the most part, the rest of the code is the same or very similar.  I'll probably have to run against the Win2D code instead of just the libraries to figure this out but I was wondering if I was doing something blatantly wrong.

Key functions are 
[CanvasControl_Draw in 2525RendererTester/MainPage.xaml.cs](https://github.com/michael-spinelli/Renderer2525C-W10-UWP/blob/master/2525RendererTester/2525RendererTester/MainPage.xaml.cs#L151)
[RenderUnit in Renderer2525C/SinglePointRenderer.cs](https://github.com/michael-spinelli/Renderer2525C-W10-UWP/blob/master/Renderer2525C/SinglePointRenderer.cs#L471)
[SVGPath.Draw in Renderer2525C/SVGPath.cs](https://github.com/michael-spinelli/Renderer2525C-W10-UWP/blob/master/Renderer2525C/SVGPath.cs#L779)

To test I choose Space Station from the list on the right, set size to 50, click the "drawFE" button, then click somewhere on the form.

Thanks,
Mike

**Comment by shawnhar** [comment]
Have you tried using CanvasCachedGeometry?

**Comment by michael-spinelli** [comment]
I'll try that tonight.

**Comment by michael-spinelli** [comment]
That helped.  It's only a little slower than System.Drawing.GraphicsPath now.
