### ISSUE TITLE
Error while running Win2D Gallery on mobile

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/Win2D#350]
I installed the Win2d Gallery app on my Lumia 640 running the Windows 10 Mobile OS (Build 10.0.14332.1001).

When I ran the app and opened the camera effects example, in case of **No effects** selected, the camera preview is being shown correctly.

However, when I choose any of the effects, I get an error message
**MediaCapture failed: The parameter is incorrect**

Here is the screenshot of the same

**Comment by ratishphilip** [comment]
![mediacapture](https://cloud.githubusercontent.com/assets/7021835/15265055/cb72deb6-1930-11e6-8cb5-9368a0a819d0.png)

**Comment by shawnhar** [comment]
Thanks for the report, we'll take a look.

**Comment by 13thsymphony** [comment]
I just tried to repro this on a Lumia 640 (Dual SIM). On both 10586 and 14342, the Camera Effect and Media Effect examples run without any errors.

**Comment by ratishphilip** [comment]
@13thsymphony 
In 14332 it is giving me this error.

However, I recently upgraded to 14342  and  now it is running without any errors.

**Comment by shawnhar** [comment]
Great!  I'm going to close the issue since this has been fixed in the latest OS.

**Comment by riseupgames** [comment]
Hello, I am having the same issue on 10.0.14372.0 (Lumia 640XL) and 10.0.14393.0 (Lumia 950XL). It was working a week ago on both :(

**Comment by ratishphilip** [comment]
Yeah I am getting it now too!

I am on Build 10.0.14393.5 and SDK 14388.

I debugged the code and found out that the exception is raised after this line in **CameraEffectExample.xaml.cs** (**Line 222**)

```C#
await mediaCapture.AddVideoEffectAsync(new VideoEffectDefinition(typeName, effectPropertySet),
                MediaStreamType.VideoPreview);
```
