### ISSUE TITLE
CanvasAnimatedControl working in dynamic mode.

### ISSUE THREAD

**Issue by eriadel** [Microsoft/Win2D#351]
Hi guys, I bring bad news regarding #338 patch.

No more crash has been observed in Win2D, nothing has been found in tests, but when we've applied infrastructure to our game, we've observed big memory leakage, which didn't happen with Win2D 1.17

Profiler shows many unreleased "locks" on the heap.

We've had to go back to our CPU driven particle FXs.

We've been told to not use CAC in the dynamic mode. But could you consider this topic as an official improvement proposal to make CAC reliable as dynamic control this year ?

**Comment by shawnhar** [comment]
I think there are two separate questions here.

Regarding potential memory leak, please provide a repro app for us to look at.  We do not see this in our testing, but will be happy to take a look if you can provide a repro.

Regarding dynamic use of many animated controls, this is not a scenario we will ever spend time optimizing in Win2D.  CanvasAnimatedControl (like the XAML swapchain on top of which is built) is intended for only a small number of instances at one time.  It will not perform well if you have many such controls active at the same time.  We recommend changing your design to draw all your graphics to a small number (ideally just one) of swapchain based controls.

**Comment by eriadel** [comment]
a) We've retested once again with 1.17 and it looks it's also not working as intended.
It's most likely not connected with the last fix.
I need more time to figure out what's the nature of the leakage..

b) Good to know how you plan to proceed. We will probably prepare our own animation infrastructure on top of the Direct 2D next year.

Thanks!
