### ISSUE TITLE
CanvasVirtualControl: ComException raised on Invalidate() call when redraws are handled off the UI thread

### ISSUE THREAD

**Issue by mglogan** [Microsoft/Win2D#352]
G'day Folks, 

I have a weird problem that is more likely a failure to understand than a bug.

In an effort to move some work out of the UI thread, I create a BlockingCollection to hold refresh requests and a dedicated Task consumer to do the work refreshing invalidated regions.  

When an Invalidate is issued on the CanvasVirtualControl, A ComException is commonly raised somewhere outside my code.  

I'm following the first procedure found in the remarks at http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_UI_Xaml_CanvasVirtualControl_CreateDrawingSession.htm.

I'm struggling to understand  the condition that is raising the exception on the Invalidate and what I can do about it.   I'm hoping someone can point me in the right direction.  I've attached a demo page that emits the error.

Any help would be appreciated!

[MainPage.xaml.zip](https://github.com/Microsoft/Win2D/files/275913/MainPage.xaml.zip)

**Comment by shawnhar** [comment]
I took a look at the code you posted, but was not able to run it because this was not a complete project.  If you want debugging help, please provide something I can debug and see your issue without having to figure out any additional setup first.

One thing that jumps out at me is you are silently swallowing all exceptions in several places.  That seems suspect, and makes me wonder if there could be exceptions getting thrown that would give more info about whatever is going wrong?

**Comment by mglogan** [comment]
Thank you for the reply.
Attached is whole solution.
I don't normally swallow generic Exceptions; I was just trying to simplify the example when I put it together.  I ran it with breakpoints on the catches and they never trigger.
You may have to shake a blue piece to trigger the ComException.  It isn't always thrown, but it should trigger in a couple of seconds.

**Comment by shawnhar** [comment]
I don't see any attachment?

**Comment by mglogan** [comment]
D'oh!

Sorry about that.

**Comment by mglogan** [comment]
I don't know why the attachment didn't make it through; it was attached.  Here it is.

[ProblemDemo.zip](https://github.com/Microsoft/Win2D/files/284599/ProblemDemo.zip)

**Comment by shawnhar** [comment]
Thanks for the zip.

The problem is that you are calling Invalidate at the same time as a draw is in progress on the background thread.  You need to detect when that happens, and queue up the invalidate to happen after the drawing session has been closed.

**Comment by mglogan** [comment]
Thanks for that!

I probably will work to keep the drawing inside the UI thread.  I was looking for a clean and simple way of moving work out of the UI thread.  There are better candidates if drawing would entail a new synchronisation effort.
