### ISSUE TITLE
How do I create a CanvasAnimatedControl without XAML?

### ISSUE THREAD

**Issue by namelesswc** [Microsoft/Win2D#355]
How can I create a CanvasAnimatedControl in C# without XAML? Just creating it with the constructor is not enough. I probably need to add it to the page or the renderer?

**Comment by shawnhar** [comment]
https://arcanecode.com/2007/09/07/adding-wpf-controls-progrrammatically/

http://stackoverflow.com/questions/4990624/wpf-add-controls-from-code

https://github.com/Microsoft/Win2D/blob/master/samples/ExampleGallery/Shared/Infrastructure/ThumbnailGenerator.xaml.cs#L161

**Comment by shawnhar** [comment]
Closing issue as I believe this question has been answered.
