### ISSUE TITLE
How to Denoise CanvasImage

### ISSUE THREAD

**Issue by HelgeKeck** [Microsoft/Win2D#357]
Hi,

can i denoise an Image with Win2D?

Helge

**Comment by shawnhar** [comment]
Win2D does not provide any built-in noise reduction implementation.

This is most commonly done using a median filter (https://en.wikipedia.org/wiki/Median_filter, http://eeweb.poly.edu/~yao/EE3414/image_filtering.pdf) which could be implemented in Win2D using a PixelShaderEffect.

Alternatively, I think you could get some version of noise reduction (although this wouldn't be as good as a median filter) by inverting the result of a SharpenEffect  (use ArithmeticCompositeEffect to compute originalImage*2 - sharpenedImage).

**Comment by shawnhar** [comment]
Closing issue as I believe this question has been answered.

**Comment by HelgeKeck** [comment]
im very sorry, yes it is answered.
