### ISSUE TITLE
Win2d and x64

### ISSUE THREAD

**Issue by JranZu** [Microsoft/Win2D#359]
Running Win2d v1.18.0 (installed via NuGet) - Following the quick start guide (http://microsoft.github.io/Win2D/html/QuickStart.htm) and attempting to run as x64 throws the following error at `InitializeComponent()`:

> Exception thrown: 'System.TypeLoadException' in UWP_Win2D_Test.exe
> 
> Additional information: Requested Windows Runtime type 'Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl' is not registered.

Running as x86 I encounter no problems.

**Comment by shawnhar** [comment]
I cannot repro this issue.  Can you share detailed instructions on how to make it happen, or a project that shows the problem?

**Comment by JranZu** [comment]
Grr... Sorry. I started a new solution & project so I could submit it and I am not able to duplicate this issue. The original solution uses other items from NuGet but I didn't think those would cross contaminate a new project. In that solution I am able to duplicate the issues, but I am unable to duplicate it a new solution.  Lesson learned. This can be closed.
