### ISSUE TITLE
Push forward CustomFontLoading #backlog suggestion

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/Win2D#36]
I'd like to put forward a vote for pushing custom font loading forward. Win2D can already do a lot with text, and I can apply a lot of effects and transforms too it all - but it all comes a bit undone when I'm stuck with only using system fonts (which are quite limited on the phone)

Combined with SharpDX I can get the FontMetrics and what not without waiting for Win2D to implement it, but it would be very nice to have custom font loading pushed forward. (No idea if that relies upon implementing a *CanvasTextLayout* or similar requiring you to basically bring forward *all* of text updates)

**Comment by shawnhar** [comment]
Thanks for the suggestion!   I'm not actually sure whether it would be feasible to do custom font loading in advance of all the other more advanced text stuff, but your argument makes sense so we'll look into that.

**Comment by JohnnyWestlake** [comment]
Going to close this as I've implemented myself a temporary (in a completely horrific, hacky way) solution to this for now, though I'll jump straight over to your teams solution whenever it's ready!

**Comment by shawnhar** [comment]
Great to hear you got this working!

**Comment by damyanp** [comment]
We're looking at getting something working for custom fonts now.  Were you looking for more than just the ability to include a TTF file with your application and use that?

**Comment by JohnnyWestlake** [comment]
Loading a bunch of TTF / OTF files into a reusable FontCollection seems perfect enough for my uses.

I don't know whether it would be appropriate to have a function at the API level that loads all of the fonts in a folder into a collection or not - sounds like it might be useful, but then again it'd probably be trivial for the end-developer to implement anyway.

**Comment by sanyams** [comment]
Has this been implemented yet? I am on Win10 and can load custom .ttf font files in my app but .otf fonts don't seem to be working.

**Comment by damyanp** [comment]
Custom font loading has been implemented (and it sounds like you have this working).  If you're having trouble loading a particular font then please open a new issue.
