### ISSUE TITLE
New error after installing Build 14361

### ISSUE THREAD

**Issue by ericgrover** [Microsoft/Win2D#361]
I just installed Build 14361, and there appears to be a breaking change that has caused the backdrop control to stop working.  I know get the exception: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."  on line 48  ElementCompositionPreview.SetElementChildVisual(this as UIElement, m_blurVisual);

**Comment by shawnhar** [comment]
I'm missing some context to understand this issue.  What app or test are you running?  What is the backdrop control?

**Comment by ericgrover** [comment]
Sorry, wrong GIT repo for this issue.  It belongs in the Windows UI Dev labs repo.
