### ISSUE TITLE
Does Win2D expose the D3D layer for use?

### ISSUE THREAD

**Issue by tgckpg** [Microsoft/Win2D#365]
I just write a simple ParticleSystem with Win2D but realize that on the phone it gets hot quickly.

After some profiling I've found that simulating 100 particles can easily choke up 60% < of CPU resources.

So I think I am doing it wrong. I was using the CPU to do all the calculations.

After some duckduckgoing it leads me to this article:
http://www.rastertek.com/dx11tut39.html

If I understand correctly it was using the DirectX ( i.e. GPU? ) to do the calculation. I am wondering does Win2D provides such an API? Or is it even possible to do so in the D3D API provided by the UWP?

PS:
I am really new to graphical programming. But I am willing to learn more.

**Comment by shawnhar** [comment]
You can use Direct3D11 in a UWP application.  Start here if you are interested in learning this API:  https://msdn.microsoft.com/en-us/library/windows/desktop/ff476080(v=vs.85).aspx

You can also combine Direct3D with Win2D drawing, if you want to use both at the same time.  The Win2D Example Gallery includes a demo of how to do that.

I would start, though, by making sure your Win2D particle system is implemented as efficiently as possible.   As a starting point, have you looked at the particle system demo in Example Gallery?

**Comment by tgckpg** [comment]
Yes, I've looked through the the Particle System ( I am going to shorten it to PSys ) sample in the Example Gallery.

I've taken the idea of reusing the same particles with a stack from the example. Here's the code I was drafting. ( Would be grateful to have some advice ):
https://github.com/tgckpg/playground/blob/master/App1/wenku8/Effects/P2DFlow/PFSimulator.cs

( I understand that the example gallery uses CPU based computation is for the sake of demonstration. )

Currently I've learn that the generic way to achieve GPU based PSys is to abstract the calculation to HLSL. I am guessing I also need to somehow encode the dx / dy information to the RGBA channel to some kind of pixel buffer?

( Since I don't know where to start, so I am just gathering random fragment of information that seemed to be relative until I can realize the whole picture. )

**Comment by shawnhar** [comment]
Are you sure it was simulating rather than drawing your particles that was expensive?  DrawCircle is not an efficient API for particle system rendering - you should probably be using CanvasSpriteBatch instead.  And with just 100 particles, simulating on the CPU would only be slow if you are doing some crazy complicated physics on them.

**Comment by tgckpg** [comment]
Oh, I didn't know. Actually I am not sure... wait, how do I know? But I am planning to add some collision and add more force fields such as winds and vortex. Does that count as complicated?

PS:
I need some time to test if my phone gets hot quickly if I switch to SpriteBatch. Will update soon.

**Comment by tgckpg** [comment]
Sorry for the late update. I just tested using the CanvasSpriteBatch. And the result was quite remarkable when using `CanvasSpiteBatch`:

Here is the profiling result for using `DrawCircle`:
![2016-06-18 22_51_38-app1 - microsoft visual studio](https://cloud.githubusercontent.com/assets/5273654/16171669/69670ec0-35a7-11e6-9598-e219d05816cc.png)

And the result using `CanvasSpriteBatch`:
![2016-06-18 22_51_47-app1 - microsoft visual studio](https://cloud.githubusercontent.com/assets/5273654/16171674/7ce40e08-35a7-11e6-8583-eeb8405ea8e0.png)

The current result is acceptable but I am worried if I add more effects and fields. It looked like it could easily exceed 50% if I don't code carefully...

My phone still gets hot easily. I think this is because my Lumia 920 is old and not meant for running win10 ( The OS is lagging itself ! ). But considering many of my users are using even crappier phone then mine. I need to optimized my code really hard so I don't kill their battery easily:(

Thank you!

**Comment by shawnhar** [comment]
Nice, that looks like a worthy CPU usage improvement!  (which is what I'd expect from switching to SpriteBatch, and exactly why we added this feature to Direct2D and Win2D).

At this point it looks like you have quite a bit of headroom on both CPU and GPU.   If you later find yourself needing to improve GPU performance, a couple of things to consider are:

1. Make sure your particle bitmaps aren't being shrunk down by a large amount (which leads to inefficient memory bandwidth and cache utilization).  Ideally the source bitmaps should be approximately the same size that you are drawing the particles on the screen.

2. Consider reducing what resolution your app draws at, which reduces the number of pixels the GPU needs to draw to.  This can be done easily by altering the CanvasControl.DpiScale property.
