### ISSUE TITLE
Draw Text following a polyline?

### ISSUE THREAD

**Issue by TomQv** [Microsoft/Win2D#367]
How would one draw a text, which is alligned to a polyline?
Like a streetname in a map on a curvy road.

In System.Drawing we had to get letter by letter and calculate angle and position and draw each character seperatly.
Is there an easyer build-in way in Win2D?

Tom

**Comment by shawnhar** [comment]
There is nothing built-in to Win2D for this, but drawing character by character should work ok.

You may find the CanvasGeometry and CanvasPathBuilder APIs useful for calculating points and tangents along your polyline.

**Comment by shawnhar** [comment]
We have talked about making a sample showing how to do this (tracked by issue #256) but haven't yet got around to working on such a thing.  Would be delighted to accept a contribution to Example Gallery if this is something you'd be interested in helping with!

**Comment by TomQv** [comment]
ok, what is the fastes way to get an array of characterWidths for each letter of the text?

for example in Android there is a function:

float[] characterWidths = new float[text.Length];
_paint.GetTextWidths (text, characterWidths);

In system.drawing there is  graphics.MeasureString(), which I need to call for each letter

How to do this in Win2D? I find the Glyph-Examples very confusing..

**Comment by shawnhar** [comment]
CanvasTextLayout.ClusterMetrics should do what you need.

A lower level but probably more efficient approach would be to use CanvasTextLayout.DrawToTextRenderer, providing a custom implementation of ICanvasTextRenderer.DrawGlyphRun.

**Comment by TomQv** [comment]
Yepp. CanvasTextLayout.ClusterMetrics is exactly what I need.
Thanks
