### ISSUE TITLE
[Question] Larger image then screen resolution

### ISSUE THREAD

**Issue by Locknes** [Microsoft/Win2D#368]
Is there any way to canvas render the whole source if its larger than the actual screen resolution?
Now its crop the source to fit the screen.

Thanks in advance

**Comment by shawnhar** [comment]
Take a look at CanvasVirtualBitmap (for very large source images) and CanvasVirtualControl (for very large things that you can draw onto).

**Comment by Locknes** [comment]
Thanks.
