### ISSUE TITLE
CanvasActiveLayer documentation should explain how to close it from C++/CX

### ISSUE THREAD

**Issue by SimonRev** [Microsoft/Win2D#372]
In C++, I cannot use a CanvasActiveLayer because there appears to be no way to destroy the object, resulting in the eventual exception "After calling CanvasDrawingSession.CreateLayer,
 you must close the resulting CanvasActiveLayer before ending the CanvasDrawingSession"

Here is a short repro:
```
void App1::MainPage::canvasControl_Draw(Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl^ sender, Microsoft::Graphics::Canvas::UI::Xaml::CanvasDrawEventArgs^ args)
{
	auto ds = args->DrawingSession;
	auto layer=ds->CreateLayer(0.5f);	
	ds->FillCircle(70, 70, 40, Colors::Blue);
}
```

I would expect the C++/CX ref count of layer to go to zero at the end of the Draw function and thus return the canvas.  I tried calling Close and Dispose, but both functions appear to only exist in the C# projection.  This means that I cannot see how to return the CanvasActiveLayer.

Note that I originally raised the issue [here](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/6b775658-e46e-40b7-b1ff-47fe4e4bdbb2/uwpcwin2d-canvasactivelayer-problem?forum=wpdevelop)

**Comment by damyanp** [comment]
To call Dispose/Close from C++/CX you need to use the "delete" operator.  (Yes, I agree that this is a bit surprising, but it's one of the quirks of C++/CX).  So in your example, this should work:

`
void App1::MainPage::canvasControl_Draw(Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl^ sender, Microsoft::Graphics::Canvas::UI::Xaml::CanvasDrawEventArgs^ args) 
{
    auto ds = args->DrawingSession;
    auto layer=ds->CreateLayer(0.5f);
    ds->FillCircle(70, 70, 40, Colors::Blue); 
    delete layer;
}`

**Comment by SimonRev** [comment]
Thanks, I would never have thought of that in a million years (and yes I find that extremely surprising, as well as mostly defeating the purpose of C++/CX if I have to manually call delete on a ref class).  I know the docs are mostly geared for C#, but some kind of note for the few C++ devs out there would be helpful :).

Guess it is time to go write a wrapper class for ref classes that require explicit deletion.

**Comment by damyanp** [comment]
I've reopened this as a suggestion to improve the docs.

Thank you for the feedback!

**Comment by shawnhar** [comment]
This documentation is improved in Win2D 1.19.0.
