### ISSUE TITLE
UserControl an a ARM Device

### ISSUE THREAD

**Issue by mjeanrichard** [Microsoft/Win2D#373]
Hi,

I implemented a UserControl with a Canvas on it (running in a UWP-Application). It works fine on the desktop (x86) and on a mobile emulator. But when I deploy it to a actual ARM device it just does not render anything.
Your demo application (glow text) work perfectly on my device. To show the problem I implemented a demo:

```csharp
	public class RedControl : UserControl
	{
		public RedControl()
		{
			Loaded += OnLayerLoaded;
			Unloaded += OnLayerUnloaded;
		}

		public CanvasControl Canvas { get; private set; }

		protected virtual void OnLayerLoaded(object sender, RoutedEventArgs e)
		{
			Canvas = new CanvasControl();

			Canvas.Draw += OnDraw;
			Content = Canvas;
		}

		private void OnDraw(CanvasControl sender, CanvasDrawEventArgs args)
		{
			args.DrawingSession.Clear(Colors.Red);
		}

		private void OnLayerUnloaded(object sender, RoutedEventArgs e)
		{
			// Explicitly remove references to allow the Win2D controls to get garbage collected
			if (Canvas != null)
			{
				Canvas.RemoveFromVisualTree();
				Canvas = null;
			}
		}

		protected override Size MeasureOverride(Size availableSize)
		{
			// CanvasTextLayout cannot cope with infinite sizes, so we change
			// infinite to some-large-value.
			if (double.IsInfinity(availableSize.Width))
				availableSize.Width = 6000;

			if (double.IsInfinity(availableSize.Height))
				availableSize.Height = 6000;

			return availableSize;
		}
	}
}
```
If I include this control into an UWP-App it starts up and show a red background. If I run this on my device the background stays white. The debugger shows that the Clear line is executed, but has somehow no effect.

Can anybody tell me what the problem is? Can anybody reproduce this?

BTW: This happens with the current nuget (18) Package as well as with the current source.

Thanks for your help!

**Comment by shawnhar** [comment]
My first thought is to check how big your control is.  Perhaps layout is sizing it down to zero, or placing it somewhere other than you expect?

Otherwise, please share a full repro app that we can compile and run to see your issue.

**Comment by mjeanrichard** [comment]
I just noticed, that in the XML tree there is an Image within the canvas control. That image has an ActualWidth (and Actualheight) of 0 on my ARM device. On my PC it has the size of the control.

See attached Repro.
[App2.zip](https://github.com/Microsoft/Win2D/files/335422/App2.zip)

**Comment by shawnhar** [comment]
I'm far from expert on the nuances of XAML layout, but I think the problem is with your MeasureOverride implementation.

According to https://msdn.microsoft.com/en-us/library/system.windows.frameworkelement.measureoverride%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396, custom implementations of this method are supposed to call Measure on each child element.

Alternatively, it may be possible for MeasureOverride to just return whatever size it wants (which is what our glow sample does) - but in that case you actually need to compute a size.  I don't think it is ever correct for MeasureOverride to simply return a copy of its input parameter.

**Comment by mjeanrichard** [comment]
I thought that if I wanted my control to take all the available space I should return the availableSize parameter. But I can see that I might need to call the MeasureOverride for the Canvas (or even just remove the override). What I don't get is why this works on my desktop.

I'll try with a base / measure call on the Canvas to see if that helps...

**Comment by mjeanrichard** [comment]
Yes, as soon as I add the Canvas.Measure() call or remove the overload altogether it works fine. 
Thanks for your help!

Should I add the Measure call to the GlowText Example? I still don't know why that one work, but it might be less confusing if the example called measure as well.

**Comment by shawnhar** [comment]
Glad to hear that worked.

I agree, it seems like a good idea to call Measure from GlowTextCustomControl.   We'd be happy to accept a pull request for that if you fancy getting your name into the Win2D contributors :-)

I too don't entirely understand what this call does, or why GlowText works without it, but the docs make it pretty clear that MeasureOverride is /supposed/ to call Measure, so this definitely seems like the right thing to do.

**Comment by mjeanrichard** [comment]
Ok, i'll create a pull request as soon as I get around to it.
Thanks again for your help!
