### ISSUE TITLE
Cannot setup Win2D-Samples on Win10

### ISSUE THREAD

**Issue by NPatch** [Microsoft/Win2D#374]
Downloaded repository from github. There's 10.0.10586.212 already installed fully on my system and I have VS2015 Community with Update 2. I keep getting a message on solution loading that I need to Download an Update of the SDK with the above version. To be fair, in Add/Remove programs, the Version column has 10.**1**.10586.212, even though the name says 10.**0**.10586.212.

![sdk_win10_prob](https://cloud.githubusercontent.com/assets/6648226/16469460/c105f8b6-3e59-11e6-96d5-dfff0b4506c2.png)

**Comment by shawnhar** [comment]
Can you create/load other UWP projects targetting that SDK?

Sounds to me like something is wrong with your Visual Studio or SDK install.  Try reinstalling the SDK from the link [here](https://social.msdn.microsoft.com/Forums/en-US/627dc077-a134-414b-804f-e90ccf5a2547/known-issue-cannot-create-or-load-universal-windows-platform-projects-with-an-error-message-about?forum=Win10SDKToolsIssues)?

**Comment by NPatch** [comment]
A brief addition to the story, I had the win10 sdk for both 1506(10.0.26624.0) and 1511(10.0.10586.212), prior to cloning the samples repo. And I also know that I've created uwp projects before. After the Download Update message from VS, I uninstalled all win10 sdks and downloaded the version VS asks from Windows SDK and emulator archive. And I still got the message in VS afterwards.

I will try to create a UWP project later today but I've already reinstalled the sdk and still no dice. Also I looked in all links to the sdk installer and all point to the same resource so there's no chance I installed the wrong one(LinkId=698771).

**Comment by NPatch** [comment]
Set up a DirectX UWP project in C++ successfully.
![cpp_uwp_dx_success](https://cloud.githubusercontent.com/assets/6648226/16495201/0a82a926-3ef5-11e6-9a54-1f95211a458f.png)

**Comment by damyanp** [comment]
SimpleSample is a C# project.  Can you confirm that you can create a Visual C# / Windows / Universal / Blank App project?

**Comment by NPatch** [comment]
Yeah just did.
![csharp_uwp_blank_success](https://cloud.githubusercontent.com/assets/6648226/16499766/75072c3a-3f0a-11e6-9d9b-20ee5e9f3bc9.png)

**Comment by shawnhar** [comment]
Afraid you're going to have to debug this on your end, since it's apparently something unique to your machine or VS install.

I suggest starting by comparing the .csproj for this blank app project with the Win2D SimpleSample one, to identify what setting is different.

**Comment by NPatch** [comment]
Solved it. First I got curious about loading up the rest of the samples as I had only tried SimpleSample. The rest loaded up fine. So I opened up WinMerge and saw the diffs.
![resolution](https://cloud.githubusercontent.com/assets/6648226/16531928/8ebd258a-3fd7-11e6-9e76-b8438dd400ae.png)
As you can see SimpleSample includes the revision number in the TargetPlatformVersion.
As it happens some days ago, I was working with WiX Toolset and dealt with similar versioning issues. I guess , by including the revision number, you are setting that particular revision as the minimum revision but you might not be including that minimum value in the check. Therefore it doesn't accept the same revision which is already installed. That is purely a guess, so I could be wrong.
Anyway... as soon as I replaced the revision with 0, the solution loaded up fine.

**Comment by shawnhar** [comment]
Glad to hear you got this working.

I think you must have made some local modification to that sample, as the version on github does not specify a revision number:

https://github.com/Microsoft/Win2D-Samples/blob/master/SimpleSample/UAP/SimpleSample.uap.csproj#L24

**Comment by NPatch** [comment]
Well, I didn't manually modify it. Unless VS took liberties. For one though, there were multiple SDKs lying around and for another, there was also the TargetPlatformMinVersion installed. How could it fail to find two SDKs?!
