### ISSUE TITLE
Hardware Instancing equivalence

### ISSUE THREAD

**Issue by lpopovici** [Microsoft/Win2D#376]
Hi!

I'm interested in developing a desktop application that draws on screen many different shapes: Ex: circles, lines, polygons... There could be ~500000  graphical items drawn once. The application has Zoom In / Out functions.
Some years ago I studied Managed DirectX (obsolete now): it had a nice feature called "**Hardware Instancing**". This optimizes the drawing of many similar items (Ex: 10000 circles of different colors and dimensions could be drawn once, instead of drawing each circle with one draw call.).
Is there something similar in Win2D?

Thank you!

**Comment by clandrew** [comment]
That's a lot of geometry! There are a couple features in Win2D that can serve to optimize drawing the same geometry over and over- in some cases, using hardware instancing.

The most general one is [CanvasCachedGeometry](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Geometry_CanvasCachedGeometry.htm). Cached geometry is suitable for all geometric shapes, where you want to pay an upfront perf cost to cache the shape and then cheaply draw it thereafter. It's possible- but not guaranteed- that drawing the same cached geometry over and over will use actual hardware instancing. It depends on an internal heuristic. It may simply re-use vertex buffer data, or take other shortcuts. However, it's guaranteed to be faster than normal CanvasGeometry, when drawing the same shape a huge number of times.

The other one is [SpriteBatch](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasSpriteBatch.htm), available in Windows 10 November Update and later. Sprites are applicable if you're talking about drawing rectangular geometry, or geometry that can be thought of as textured quadrilaterals. Anything you'd normally draw with DrawImage. Like cached geometry, there's an internal policy that decides whether to apply actual hardware instancing, or use other shortcuts. Regardless, drawing sprite batches tends to be much faster than repeated calls to DrawImage.

**Comment by clandrew** [comment]
Hope this helped. Since I don't see additional action for us for this issue, I'll mark it closed- but feel free to re-open if you need anything else.
