### ISSUE TITLE
RenderTargetBitmap dumped visual tree does not include CanvasAnimatedControl.

### ISSUE THREAD

**Issue by rcosnita** [Microsoft/Win2D#379]
I try to dump the whole visual tree using RenderTargetBitmap but CanvasAnimatedControl does not appear. The workaround used at the moment is to introduce a new simple Canvas control which appears in the visual tree. Is there anyway we can include CanvasAnimatedControl into the visual tree?

**Comment by shawnhar** [comment]
Unfortunately not.  CanvasAnimatedControl renders via a DirectX swapchain, but RenderTargetBitmap is only able to capture content that is rendered directly by XAML itself.

https://msdn.microsoft.com/en-us/library/windows/apps/dn298556.aspx notes this restriction:

> Custom Microsoft DirectX content (your own swap chain) inside a SwapChainBackgroundPanel or SwapChainPanel can't be captured using RenderTargetBitmap.

**Comment by shawnhar** [comment]
Closing issue as I believe this has been answered.  Feel free to reactivate if you have further questions!

**Comment by enghch** [comment]
Is there a workaround for this? Is there a way to get the swapchain as an image?

**Comment by shawnhar** [comment]
There is no way to read back swapchain contents to the CPU, but you could intercept pixels earlier in the rendering, for example draw into a rendertarget which can then be accessed in other ways as well as copied onto the output swapchain.

Note that any such rendering approach that involves a CPU readback will be very expensive compared to normal CanvasControl or CanvasAnimatedControl output.

**Comment by enghch** [comment]
That's a good idea. I'll look at that. I just need to do it once upon user request to "snapshot" the scene. It doesn't need to be fast. The plan I was looking at was to pause the CanvasAnimatedControl, render the whole scene to a CanvasControl, snapshot it, then return to the CanvasAnimatedControl.
