### ISSUE TITLE
ObjectDisposedException when creating resources outside of CreateResources.

### ISSUE THREAD

**Issue by nezero** [Microsoft/Win2D#380]
I'm attempting to create a CanvasBitmap after CreateResources has been fired, but I keep getting a ObjectDisposedException when creating it. 

XAML
`<canvas:CanvasControl x:Name="MyCanvas" Draw="MyCanvas_Draw" CreateResources="MyCanvas_CreateResources" />`

Get a stream from a photo capture (exception thrown here).
`photoPreview = await CanvasBitmap.LoadAsync(MyCanvas, stream, 96);`

Is there a way to re-create or create more resources that can be added next time I invalidate MyCanvas?

**Comment by shawnhar** [comment]
You can create objects anywhere you like, as long as whatever other objects and state is used to do so are valid at the time.

CreateResources makes the most common use pattern easier, handling things like not drawing the control until async loading has completed, and recreating resources if a lost device occurs.  If you create your resources somewhere else, you'll need to handle those things yourself.

More info about that here: http://microsoft.github.io/Win2D/html/LoadingResourcesOutsideCreateResources.htm

In this case, my guess is either your MyCanvas or stream objects are not valid while you execute the LoadAsync call  (I assume that's what is throwing the exception?)

**Comment by nezero** [comment]
So I redesigned my code to mimic the example in the article you pointed me too, but the exception still gets thrown, but this time its thrown in `IsLoadInProgress`.

Why would my `CanvasControl` object not be valid? What could cause this?

**Comment by shawnhar** [comment]
Are you sure the control has been loaded (and not yet unloaded) while you run this code?

Also that your stream is valid?

**Comment by nezero** [comment]
I'm just doing an investigation. I've got a scratch project that I'll push to github in a bit if I cannot get to the bottom of what I doing wrong.

**Comment by nezero** [comment]
So i may be missing a trick here but I can't tell when breaking the code if an object has been disposed or not. I've created a branch on my scratch project that demonstrates the issue I'm seeing.

[https://github.com/nezero/WindowsScratch/tree/Win2d](url)

**Context**
I'm trying to take a photo and add a watermark to it then display it to the user using the `CanvasControl`.

**Repro**
- Build and run the Windows 8.1 project.
- Click the Take Photo button.
- Click the Capture Photo (camera icon) button.
- Observe watermarked photo gets displayed in the `Image` control but an exception gets thrown when `MakeJpgTest.xaml.cs line 155: cb = await CanvasBitmap.LoadAsync(CapturedImage2, oStream, CapturedImage2.Dpi);` ([155:](https://github.com/nezero/WindowsScratch/blob/Win2d/Scratch/Scratch.Shared/MakeJpgTest.xaml.cs#L155)) gets called, so the resulting `CanvasBitmap` does not get created and cannot be added to the `CanvasControl`.

**My Conclusion**
It must be that `CanvasControl` or a member of it that is throwing the `ObjectDisposedException`.

If you have the time to review my code and/or clone and run it, then I would greatly appreciate you're advice on what I'm doing wrong.

**Comment by shawnhar** [comment]
Your shared CanvasDevice is disposed because you dispose it at the end of CreateWaterMarkedStream:

> device.Dispose();

You don't need and shouldn't have that call.

**Comment by nezero** [comment]
Excellent. Thanks so much for that, I misunderstood the  docs. I assumed the device can be shared with multiple controls rather than it was by default.
