### ISSUE TITLE
GaussianBlurEffect visual bug

### ISSUE THREAD

**Issue by DaniilPros** [Microsoft/Win2D#382]
When I use GaussianBlurEffect with Optimization = EffectOptimization.Speed and CanvasAnimatedControl where I change BlurAmount I have some visual bugs:
![screenshot 7](https://cloud.githubusercontent.com/assets/15347593/16849232/36dfa8b2-4a02-11e6-96a6-17a73e5cbe08.png)
if I use GaussianBlurEffect with Optimization = EffectOptimization.Quality:
![screenshot 1](https://cloud.githubusercontent.com/assets/15347593/16849416/f9fd6b36-4a02-11e6-9e31-929114e3c77b.png)
Source 
[BlurApp.zip](https://github.com/Microsoft/Win2D/files/364457/BlurApp.zip)
Is it expected result or bug?

**Comment by shawnhar** [comment]
EffectOptimization.Speed makes various tradeoffs to prefer performance over visual quality.  It is expected that many visual artifacts will result from that.  If these are not acceptable for your scenario, use Balanced or Quality mode instead.

**Comment by shawnhar** [comment]
Closing issue as I believe this has been answered.  Feel free to reactivate if you have further questions!
