### ISSUE TITLE
Question: Converting to BitmapImage

### ISSUE THREAD

**Issue by BubblegumYeti** [Microsoft/Win2D#383]
Any easy way to convert CanvasBitmap to  Windows.UI.Xaml.Media.Imaging.BitmapImage?

**Comment by shawnhar** [comment]
The easiest way is call CanvasBitmap.SaveAsync to write a .png version of the bitmap into a memory stream, then set BitmapImage.StreamSource to read from that.

**Comment by shawnhar** [comment]
Closing issue as I believe this question has been answered.
