### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by Jesuo** [Microsoft/Win2D#386]
I tried to build Win2d from source and it throws these kind of errors:

c:\program files (x86)\windows kits\10\include\10.0.10586.0\winrt\wrl\module.h(1717): error C2220: advertencia tratada como error; ningún archivo 'object' generado [C:\Users\user\Source\Repos\Win2D\winrt\lib\winrt.lib.uap.vcxproj]
c:\program files (x86)\windows kits\10\include\10.0.10586.0\winrt\wrl\module.h(1717): warning C4467: 

Los atributos ATLestán en desuso [C:\Users\user\Source\Repos\Win2D\winrt\lib\winrt.lib.uap.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.10586.0\winrt\wrl\module.h(1717): note: para simplificar la migración, considere el uso temporal del marcador /Wv:18 con la versión del compilador con la que solía compilar sin advertencias.

All intents are "build failed, aborting"

Any hint about that?

**Comment by shawnhar** [comment]
What version of Visual Studio are you using?   And what steps exactly are you using to compile Win2D?

**Comment by shawnhar** [comment]
We figured this out - it's a compatibility issue due to Visual Studio 2015 Update 3 deprecating an attribute syntax that Win2D was using.

I just pushed a fix to github.

**Comment by Jesuo** [comment]
Thanks a lot!
