### ISSUE TITLE
CanvasDrawingSession.DrawLineString?

### ISSUE THREAD

**Issue by danzel** [Microsoft/Win2D#39]
I might be missing it, but is there a way to draw a line consisting of more than two points? (Other than calling DrawLine for each segment).

It looks like it has been thought of as CanvasStrokeStyle has a LineJoin property, but the DrawLine implementations all only take two points.

**Comment by shawnhar** [comment]
This is what path geometries are for.  These are not implemented in Win2D yet, but funnily enough it's the very next feature being worked on even as we speak...

**Comment by danzel** [comment]
<3 Awesome

**Comment by danzel** [comment]
I see "Geometry primitives" are mentioned in there too, does that include Polygon rendering?
I'm thinking GDI FillPolygon equivalent.

**Comment by clandrew** [comment]
Yes, it does. Path geometries work for all kinds of polygon rendering (both draws and fills).

**Comment by clandrew** [comment]
Hope this helps, danzel! I'll close this issue.

**Comment by danzel** [comment]
Yep thanks :) Looking forward to it.
