### ISSUE TITLE
Sandcastle cannot build Win2D docs using VS 2015 Update 3

### ISSUE THREAD

**Issue by Jesuo** [Microsoft/Win2D#390]
Ok, im here again with more issues, this time with build docs 1.19 version.

EXEC : error : Unknown extension .htm (html\APIReference.htm) [I:\Git\Repositorios\Win2D\tools\checkcode\RunCodeChecks.
proj]
EXEC : error : Unknown extension .gif (icons\CFW.gif) [I:\Git\Repositorios\Win2D\tools\checkcode\RunCodeChecks.proj]
EXEC : error : Unknown extension .js (scripts\branding-Website.js) [I:\Git\Repositorios\Win2D\tools\checkcode\RunCodeCh
ecks.proj]
EXEC : error : Unknown extension .css (styles\branding-cs-CZ.css) [I:\Git\Repositorios\Win2D\tools\checkcode\RunCodeChe
cks.proj]
EXEC : error : Wrong copyright: toc\APIReference.xml [I:\Git\Repositorios\Win2D\tools\checkcode\RunCodeChecks.proj]
EXEC : error : Wrong copyright: toc\Articles.xml [I:\Git\Repositorios\Win2D\tools\checkcode\RunCodeChecks.proj]
EXEC : error : Wrong copyright: toc\Events_T_Microsoft_Graphics_Canvas_CanvasDevice.xml [I:\Git\Repositorios\Win2D\tool
s\checkcode\RunCodeChecks.proj]
EXEC : error : Wrong copyright: toc\Events_T_Microsoft_Graphics_Canvas_Printing_CanvasPrintDocument.xml [I:\Git\Reposit
orios\Win2D\tools\checkcode\RunCodeChecks.proj]
EXEC : error : Wrong copyright: toc\Events_T_Microsoft_Graphics_Canvas_UI_Xaml_CanvasAnimatedControl.xml [I:\Git\Reposi
torios\Win2D\tools\checkcode\RunCodeChecks.proj]

and so on......

**Comment by shawnhar** [comment]
That sounds like you somehow got a copy of the output documentation placed in a non-standard location inside your Win2D source tree.  Did you copy a version of the HTML docs from somewhere else?

When you build the documentation locally (via tools\docs\builddocs.cmd) it places outputs in the bin\docs folder, and bin folder is excluded from RunCodeChekcs.proj.

**Comment by Jesuo** [comment]
Rare, rare, i download again the source, and now docs build with other errors..
`<?xml version="1.0" encoding="utf-8"?>
<shfbBuild product="Sandcastle Help File Builder and Tools" version="2015.10.10.0" projectFile="I:\Git\Repositorios\Win2D2\tools\docs\BuildDocs.shfbproj" started="20/07/2016 18.29.06">
<buildStep step="Initializing">
Finding tools...
The Sandcastle tools are located in &#39;I:\Git\Repositorios\Win2D2\packages\EWSoftware.SHFB.2015.10.10.0\Tools\&#39;
The SHFBROOT system environment variable was not found.  This variable is usually created during installation and may require a reboot.  It has been defined temporarily for this process as: SHFBROOT=I:\Git\Repositorios\Win2D2\packages\EWSoftware.SHFB.2015.10.10.0\Tools\
Locating components in the following folder(s):
    I:\Git\Repositorios\Win2D2\tools\docs\..\..\packages\EWSoftware.SHFB.UniversalWindows.1.0\
    I:\Git\Repositorios\Win2D2\tools\docs
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\
    I:\Git\Repositorios\Win2D2\packages\EWSoftware.SHFB.2015.10.10.0\Tools\
Framework reflection data location: I:\Git\Repositorios\Win2D2\tools\docs\..\..\packages\EWSoftware.SHFB.UniversalWindows.1.0\tools\Data\UniversalWindows
Using presentation style &#39;VS2013&#39; located in &#39;I:\Git\Repositorios\Win2D2\packages\EWSoftware.SHFB.2015.10.10.0\Tools\PresentationStyles\VS2013&#39;
Loading and initializing plug-ins...
Table of Contents Exclusion Version 2015.10.10.0
Copyright &#169; 2006-2015, Eric Woodruff, All Rights Reserved
Lightweight Website Style Version 2015.10.10.0
Copyright &#169; 2006-2015, Eric Woodruff, All Rights Reserved
Portions Copyright &#169; 2014, Sam Harwell, All Rights Reserved
-------------------------------
Clearing any prior web/markdown output...
</buildStep>
<buildStep step="ValidatingDocumentationSources">
Validating and copying documentation source information
Source: I:\Git\Repositorios\Win2D2\obj\docs\Microsoft.Graphics.Canvas.winmd
    Found assembly &#39;I:\Git\Repositorios\Win2D2\obj\docs\Microsoft.Graphics.Canvas.winmd&#39;
Source: I:\Git\Repositorios\Win2D2\obj\docs\docsrc\*.xml
Source: I:\Git\Repositorios\Win2D2\obj\docs\Microsoft.Graphics.Canvas.placeholders.xml
Source: I:\Git\Repositorios\Win2D2\obj\docs\PlaceholderNamespaces.xml

Copying XML comments files
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\ArithmeticCompositeEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\ArithmeticCompositeEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\AtlasEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\AtlasEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\BlendEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\BlendEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\BorderEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\BorderEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\BrightnessEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\BrightnessEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\Canvas.codegen.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\Canvas.codegen.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasActiveLayer.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasActiveLayer.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasAnimatedControl.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasAnimatedControl.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasBitmap.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasBitmap.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasBrush.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasBrush.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasCachedGeometry.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasCachedGeometry.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasCommandList.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasCommandList.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasComposition.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasComposition.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasControl.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasControl.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasDevice.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasDevice.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasDrawingSession.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasDrawingSession.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasFontFace.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasFontFace.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasFontSet.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasFontSet.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasGeometry.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasGeometry.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasGradientMesh.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasGradientMesh.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasImage.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasImage.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasImageSource.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasImageSource.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasInterfaces.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasInterfaces.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasPathBuilder.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasPathBuilder.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasPrintDocument.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasPrintDocument.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasRenderTarget.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasRenderTarget.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasSpriteBatch.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasSpriteBatch.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasStrokeStyle.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasStrokeStyle.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasSwapChain.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasSwapChain.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasSwapChainPanel.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasSwapChainPanel.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasTextAnalyzer.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasTextAnalyzer.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasTextFormat.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasTextFormat.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasTextInlineObject.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasTextInlineObject.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasTextLayout.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasTextLayout.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasTextRenderer.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasTextRenderer.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasTextRenderingParameters.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasTextRenderingParameters.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasTypography.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasTypography.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasVirtualBitmap.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasVirtualBitmap.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasVirtualControl.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasVirtualControl.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CanvasVirtualImageSource.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CanvasVirtualImageSource.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\ChromaKeyEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\ChromaKeyEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\ColorManagementEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\ColorManagementEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\ColorMatrixEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\ColorMatrixEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\ColorSourceEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\ColorSourceEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CompositeEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CompositeEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\ContrastEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\ContrastEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\ConvolveMatrixEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\ConvolveMatrixEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\CropEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\CropEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\DirectionalBlurEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\DirectionalBlurEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\DiscreteTransferEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\DiscreteTransferEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\DisplacementMapEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\DisplacementMapEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\DistantDiffuseEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\DistantDiffuseEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\DistantSpecularEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\DistantSpecularEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\DpiCompensationEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\DpiCompensationEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\EdgeDetectionEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\EdgeDetectionEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\Effects.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\Effects.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\EmbossEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\EmbossEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\ExposureEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\ExposureEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\GammaTransferEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\GammaTransferEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\GaussianBlurEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\GaussianBlurEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\GrayscaleEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\GrayscaleEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\HighlightsAndShadowsEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\HighlightsAndShadowsEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\HueRotationEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\HueRotationEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\HueToRgbEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\HueToRgbEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\InvertEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\InvertEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\LinearTransferEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\LinearTransferEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\LuminanceToAlphaEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\LuminanceToAlphaEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\MorphologyEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\MorphologyEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\Namespaces.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\Namespaces.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\OpacityMetadataEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\OpacityMetadataEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\PixelShaderEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\PixelShaderEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\PointDiffuseEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\PointDiffuseEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\PointSpecularEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\PointSpecularEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\PosterizeEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\PosterizeEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\PremultiplyEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\PremultiplyEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\RgbToHueEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\RgbToHueEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\SaturationEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\SaturationEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\ScaleEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\ScaleEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\SepiaEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\SepiaEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\ShadowEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\ShadowEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\SharpenEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\SharpenEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\SpotDiffuseEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\SpotDiffuseEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\SpotSpecularEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\SpotSpecularEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\StraightenEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\StraightenEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\TableTransfer3DEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\TableTransfer3DEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\TableTransferEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\TableTransferEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\TemperatureAndTintEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\TemperatureAndTintEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\TileEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\TileEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\Transform2DEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\Transform2DEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\Transform3DEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\Transform3DEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\TurbulenceEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\TurbulenceEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\UnPremultiplyEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\UnPremultiplyEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\docsrc\VignetteEffect.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\VignetteEffect.xml
    I:\Git\Repositorios\Win2D2\obj\docs\Microsoft.Graphics.Canvas.placeholders.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\Microsoft.Graphics.Canvas.placeholders.xml
    I:\Git\Repositorios\Win2D2\obj\docs\PlaceholderNamespaces.xml -&gt; I:\Git\Repositorios\Win2D2\bin\docs\Working\PlaceholderNamespaces.xml
</buildStep>
<buildStep step="GenerateSharedContent">
Generating shared content files (en-US, Ingl&#233;s (Estados Unidos))...
<plugIn name="Lightweight Website Style" behavior="After" priority="1000">
</plugIn>    Last step completed in 00:00:00,0150
</buildStep>
<buildStep step="GenerateApiFilter">
Generating API filter for MRefBuilder...
    Last step completed in 00:00:00,0280
</buildStep>
<buildStep step="GenerateReflectionInfo">
Generating reflection information...
[C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe - GenerateRefInfo.proj]
Compilaci&#243;n iniciada a las 20/07/2016 18.29.07.
Proyecto &quot;I:\Git\Repositorios\Win2D2\bin\docs\Working\GenerateRefInfo.proj&quot; en nodo 1 (destinos predeterminados).
PrepareForBuild:
  Creando directorio &quot;obj\Debug\&quot;.
GenerateRefInfo:
  MRefBuilder (v2015.10.10.0)
  Copyright &#169; 2006-2015, Microsoft Corporation, All Rights Reserved.
  Portions Copyright &#169; 2006-2015, Eric Woodruff, All Rights Reserved.
MRefBuilder : error : An unexpected error occurred trying to execute the MRefBuilder MSBuild task: System.InvalidOperationException: Unable to locate information for the framework version &#39;.NETCore 5.0&#39; or a suitable redirected version on this system [I:\Git\Repositorios\Win2D2\bin\docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    en System.Compiler.TargetPlatform.SetFrameworkInformation(String platformType, String version, IEnumerable`1 componentLocations) [I:\Git\Repositorios\Win2D2\bin\docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    en Microsoft.Ddue.Tools.MRefBuilderCore.Main(String[] args) [I:\Git\Repositorios\Win2D2\bin\docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    en Microsoft.Ddue.Tools.MSBuild.MRefBuilder.Execute() [I:\Git\Repositorios\Win2D2\bin\docs\Working\GenerateRefInfo.proj]
Compilaci&#243;n del proyecto terminada &quot;I:\Git\Repositorios\Win2D2\bin\docs\Working\GenerateRefInfo.proj&quot; (destinos predeterminados) -- ERROR.

ERROR al compilar.

Tiempo transcurrido 00:00:00.15
    Last step completed in 00:00:00,3060
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   en SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   en SandcastleBuilder.Utils.BuildEngine.TaskRunner.RunProject(String projectFile, Boolean minimalOutput)
   en SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
</shfbBuild>
`

**Comment by shawnhar** [comment]
Gah, looks like Sandcastle is not currently compatible with Visual Studio 2015 Update 3.

Until we can get this fixed, you will have to use Update 2 to build docs.

**Comment by Jesuo** [comment]
Ok, thanks....i celebrate thats not my fault ;).

**Comment by shawnhar** [comment]
I've been digging more into this - as far as I can tell the Sandcastle framework references that are packaged in EWSoftware.SHFB.UniversalWindows don't match the actual framework used by VS 2015 Update 3.

I've asked the Sandcastle team for help figuring out what is going wrong here (https://github.com/EWSoftware/SHFB/issues/322)

**Comment by shawnhar** [comment]
Sandcastle recently checked in a fix for this issue.  Now we're just waiting for them to release updated NuGet packages, which is how Win2D will pick up the fix.

**Comment by shawnhar** [comment]
fixed
