### ISSUE TITLE
CanvasBitmap LoadAsync from WriteableBitmap exception

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Win2D#392]
[Win2D 1.18, SDK 14388, Windows 1607 with updates]

I am creating a WriteableBitmap on memory:

var randomaccessstream = wb.PixelBuffer.AsStream().AsRandomAccessStream();
CanvasBitmap bitmap = await CanvasBitmap.LoadAsync(_canvasDevice, randomaccessstream);

An exception of type 'System.Exception' occurred in mscorlib.ni.dll but was not handled in user code
Additional information: The component cannot be found. (Exception from HRESULT: 0x88982F50)

Is that way correct to load a Writeablebitmap into a CanvasBitmap?

**Comment by 13thsymphony** [comment]
CanvasBitmap.LoadAsync is designed to take compressed image file formats like JPEG or PNG; meanwhile the WriteableBitmap.PixelBuffer is just the raw uncompressed pixel array in an IBuffer. You can initialize CanvasBitmap from such a pixel buffer using [CreateFromBytes](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasBitmap_CreateFromBytes_3.htm) or one of its overloads.

**Comment by juanpaexpedite** [comment]
Thank you for the info, I used:

    CanvasBitmap bitmap = CanvasBitmap.CreateFromBytes(_canvasDevice,wb.PixelBuffer, wb.PixelWidth, wb.PixelHeight, DirectXPixelFormat.B8G8R8A8UIntNormalized);

and worked like a charm,
