### ISSUE TITLE
No DrawText with CanvasFontFace overload

### ISSUE THREAD

**Issue by Cleverman87** [Microsoft/Win2D#393]
There is no overload for drawing test with CanvasFontFace.

I have a custom font (TTF file), and I want to use it for drawing text.
So I'm creating a CanvasFontSet which returns the loaded fonts as CanvasFontFace, then I need to use this font in drawing text.

**Comment by 13thsymphony** [comment]
Is there a reason why you can't use the technique demonstrated in the Win2D custom fonts sample:
https://github.com/Microsoft/Win2D-Samples/blob/master/ExampleGallery/Shared/CustomFonts.xaml.cs

Specifically, just setting the path to the font in the CanvasTextFormat:
http://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_Text_CanvasTextFormat_FontFamily.htm

If you need to load an arbitrary font from the user's filesystem, you should consider copying the file to your app's local data directory and then loading via ms-appdata://.

**Comment by Cleverman87** [comment]
Thank you.
