### ISSUE TITLE
How to handle unload of CanvasAnimatedControl or CanvasControl in flyout?

### ISSUE THREAD

**Issue by jeffboulanger** [Microsoft/Win2D#394]
When a flyout is shown and then dismissed, the Unloaded event gets called.   In order to avoid memory leaks, its recommended to call RemoveFromVisualTree on Canvas(Animated)Control.  The problem is the flyout can then become visible again.   In this case, Loaded and Unloaded are not called again, which causes an issue because the controls has been unloaded and no longer renders.   Any ideas?

**Comment by jeffboulanger** [comment]
Found a work around.   It appears Loaded and Unloaded are called multiple times,  so instead of adding the CanvasControl to the template.  I now add a container control for the CanvasControl to the template, and manually add the CanvasControl to the container OnApplyTemplate and Loaded if it doesnt already exist.   I null out all references and call RemoveFromVisualTree in Unload and this seems to work and no visible memory leaks.     It would be nice if there were a way around this, but this works for now.

Control Template
`<ControlTemplate>
                    <Grid>
                        <Grid x:Name="PART_CanvasContainer" />
                        <Grid>
                            <ContentPresenter x:Name="PART_ContentPresenter"
                                              Margin="{TemplateBinding Padding}"
                                              HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                                              VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
                                              Content="{TemplateBinding Content}"
                                              ContentTemplate="{TemplateBinding ContentTemplate}"
                                              ContentTransitions="{TemplateBinding ContentTransitions}" />
                        </Grid>
                    </Grid>
                </ControlTemplate>`

Template Code:
`
        public DropShadow()
        {
            DefaultStyleKey = typeof(DropShadow);
            Loading += onLoading;
        }

        protected override void OnApplyTemplate()
        {
            base.OnApplyTemplate();
            
            EnsureCanvasControlExists();

            _contentPresenter = GetTemplateChild(PART_ContentPresenterPartName) as ContentPresenter;
        }

        private void OnUnloaded(object sender, RoutedEventArgs routedEventArgs)
        {
            if (_canvasControl == null)
            {
                return;
            }

            _canvasControl.RemoveFromVisualTree();
            _canvasControl = null;
        }

        private void EnsureCanvasControlExists()
        {
            if(_canvasControl != null)
            {
                return;
            }

            var container = GetTemplateChild(PART_CanvasContainer) as Grid;

            if(container == null)
            {
                return;
            }

            var canvas = new CanvasControl();

            canvas.Draw += Draw;
            canvas.Margin = new Thickness(-35);
            canvas.IsHitTestVisible = false;

            container.Children.Add(canvas);

            _canvasControl = canvas;
        }`

**Comment by shawnhar** [comment]
Closing issue as it seems like you have a solution.

The need for these RemoveFromVisualTree shenanigans is far from ideal - unfortunately it's the best Win2D has been able to come up with given the awkward nature of cross-language mixed reference counting and garbage collection though :-(
