### ISSUE TITLE
Question: How to draw many points in a grid pattern quickly?

### ISSUE THREAD

**Issue by denisli** [Microsoft/Win2D#395]
I am currently working with a CanvasAnimatedControl and am drawing many points of various color on it. Currently this is implemented with FillCircle of radius 1, but the runtime is not as good as I would like. Is there a more efficient way to do this?

Edit:
To further elaborate on the situation (although somewhat exaggerated), imagine I am drawing points on the entire screen. Every 4 pixels (in x and in y), I would like to draw a point of some arbitrary color. The other pixels must be transparent.

Thanks.

**Comment by shawnhar** [comment]
A circle is quite a complex shape.  Small rectangles would be a lot faster.

**Comment by denisli** [comment]
Thank you! That is indeed a bit faster.
