### ISSUE TITLE
Add "VB" to the Introduction

### ISSUE THREAD

**Issue by Nukepayload2** [Microsoft/Win2D#396]
I'm developing a new 2D game in VB with Win2D, and I have proved that VB14 is compatible with Win2D.
So, please add "VB" to the Introduction at http://microsoft.github.io/Win2D/html/Introduction.htm.
Before:
Win2D is an easy-to-use Windows Runtime API for immediate mode 2D graphics rendering with GPU acceleration. It is available to C# and C++ developers writing Windows apps for Windows 8.1, Windows Phone 8.1 and Windows 10. It utilizes the power of Direct2D, and integrates seamlessly with XAML and CoreWindow. 
After:
Win2D is an easy-to-use Windows Runtime API for immediate mode 2D graphics rendering with GPU acceleration. It is available to C#, C++ and VB developers writing Windows apps for Windows 8.1, Windows Phone 8.1 and Windows 10. It utilizes the power of Direct2D, and integrates seamlessly with XAML and CoreWindow.

**Comment by shawnhar** [comment]
This seems like a sensible idea.  We'd be happy to accept a pull request if you're interested in getting a Win2D contributor credit?
