### ISSUE TITLE
DrawLine color drawn different from set color 

### ISSUE THREAD

**Issue by octav84** [Microsoft/Win2D#403]
Hi.
I use Win2D to draw a rectangle on a CanvasVirtualControl. I draw it's border using DrawLine function (I draw independently Left, Right, Top, Bottom borders). I set the color of the border to ARGB(256,217,217,217). The actually drawn border line has a checked ARGB value of  (256,236,236,236).

**Comment by shawnhar** [comment]
Please share a repro app so i can see exactly what you are doing.

Note that 256 is not a valid value if you are using an 8-bit byte-per-channel format to represent these colors.

**Comment by octav84** [comment]
I fixed it by disabling Antialising. DIP lines. It seems antialising changes colors with very thin lines, for some reason.
