### ISSUE TITLE
Possible to write Win2D desktop application?

### ISSUE THREAD

**Issue by RobJellinghaus** [Microsoft/Win2D#405]
I have a .NET desktop application that uses the desktop Kinect for Windows SDK and the Xbox One Kinect with the PC adapter: http://holofunk.com

For graphics, I am currently using a stale version of SharpDX and its now-obsolete XNA-like Toolkit package, which has SpriteBatch.  I do a lot of video texturing and SpriteBatch is just the ticket.

I would like to drop the stale dependency.  Win2D seems to be the best C#-based D2D API out there.  However, I am relatively new to the WinRT ecosystem, and so is Kinect for Windows; the K4W2 SDK does not yet support skeletal tracking with UWP apps.  https://blogs.msdn.microsoft.com/kinectforwindows/2016/05/13/kinect-and-uwp-new-options-in-the-windows-10-anniversary-update/

Additionally, my app also uses low-level desktop-only ASIO audio drivers, due to my non-negotiable audio latency requirements.

Is it the case that I cannot write a .NET desktop app that uses Win2D along with other desktop-only APIs (the current Kinect for Windows API, and the current ASIO API)?  In other words, is it the case that, on Windows 10, a Win2D app is necessarily a UWP app, and hence restricted by all the other UWP restrictions?

Or, perhaps, is there a way to write a Windows 8.1-style app that uses Win2D but is not UWP, but still runs on Windows 10?

I hope this question is sufficiently well formed as to be answerable.  Please advise if not.
Thanks very much,
Rob Jellinghaus

**Comment by shawnhar** [comment]
Win2D is a WinRT API, so can only be used by WinRT applications. That includes the Windows 10 Universal Windows Platform, and also store apps for Windows 8.1 or Windows Phone 8.1.

You cannot use WinRT APIs from other environments such as classic Win32 desktop.
