### ISSUE TITLE
Is Brush Conversion possible?

### ISSUE THREAD

**Issue by apollyonbob** [Microsoft/Win2D#408]
Hi, I'm trying to create a TextBlock for my app that has some ready-made options on it for things like drop shadow, outline, etc.

I'd like to be able to drop the control onto a page, and do stuff like specify the Foreground Brush or Background Brush on the control, and be able to use those values.

Is there anything I can do to try to get that kind of functionality?

Thanks!

**Comment by shawnhar** [comment]
In general, no.  Win2D and XAML are completely different rendering systems.  Although they both have the concept of a brush, these are different types of object with different capabilities and radically different underlying representation.

For simple things like solid color or linear gradient brushes, you could write some code to look at properties of a XAML brush and create an equivalent Win2D brush.  That won't work for interesting cases such as an image brush, though, where concept of 'image' means a completely different thing to XAML vs. Win2D.

**Comment by apollyonbob** [comment]
Fair enough. That's kind of what I figured the answer would be haha. Any thoughts on how I might make picking a brush easier for someone trying to use the control in XAML?

**Comment by shawnhar** [comment]
You could provide properties for selecting a color or perhaps an image file, then construct an appropriate brush internally.  I don't think it's really feasible to express the full power of a Win2D brush through XAML though (a brush could be defined by an image effect graph, or arbitrarily complex graphics that were previously drawn into a command list, for instance).

**Comment by apollyonbob** [comment]
Gotcha. Thanks for the help!
