### ISSUE TITLE
SpriteBatch memory management

### ISSUE THREAD

**Issue by CMay** [Microsoft/Win2D#415]
I've been experimenting with SpriteBatches and I'm seeing striking runaway memory allocation (up to 7GB of RAM before the next GC).  There are a couple factors at play:

- Trying to draw thousands of a single bitmap, so there's only a single bitmap involved which has no alpha channel and is fairly small at around 64x64.  The size of the image or whether it had transparency did not seem to matter.

- Running on a 120hz display with the desktop refresh rate also set to 120hz.

- Have 32GB of RAM which the GC may factor into how aggressive it's willing to be in collecting, but I'm not sure.  I did test it in the Mobile Emulator with 2GB of RAM and it eventually threw an Out of Memory exception, so the GC was not able to keep up.

**What I found:**

- On the Direct2D SpriteBatch page ( https://msdn.microsoft.com/en-us/library/windows/desktop/mt619833(v=vs.85).aspx ) it specifically suggests using it for thousands, so this isn't an unintended use.

- On the Direct2D SpriteBatch AddSprites method page ( https://msdn.microsoft.com/en-us/library/windows/desktop/mt619834(v=vs.85).aspx ) at the bottom it warns "_if any sprite in the batch has any value set for a property, then internally Direct2D must allocate space for that property array and assign every sprite a value for that property (even if it’s just the default value)._", so the recommendation is to pass in null as often as you can.

- Disregarding the arguable practicality of the scenario - 13,000 draws with SpriteBatch is ~4 draw calls, while with DrawImage it's ~158 draw calls with a frametime at least 3 times worse.  SpriteBatch efficiency is good enough in comparison that it's worth trying to tame the memory usage.  Unfortunately the difference is large considering SpriteBatch was causing many GB of allocations while with DrawImage the app stayed at 60MB.

- What seems like a reasonable amount of draws in a SpriteBatch can spiral out of control depending on the framerate

**What I tried or considered:**

- Made sure I left MaximumCacheSize at default (since I had changed it recently) just in case that might be involved in some way.

- Limiting inputs to CreateSpriteBatch, SpriteBatch.Draw and making sure I wasn't modifying any of the matrices or other inputs to see if I could avoid having it passed in to each sprite.

- I baked the SpriteBatch into a CommandList and just drew the CommandList instead.  The result is that it drew all of the sprites every frame with none of the extra memory allocation, so the app stayed at 60MB.  Unfortunately, it would be necessary to recreate the CommandList every time something moved.

- Depending on the scenario, it might be possible to simply draw the SpriteBatch into a CommandList at a lower update rate than the framerate, while other more dynamic objects get updated every frame.  This way the memory problem is not solved, but might be slowed down a bit allowing the GC to catch up.

- It might be possible to create a pool of CommandLists and only recreate them when something within them has been invalidated, with them being sorted by how likely the objects within them are to change.  This could be a terrible idea, I'm not sure.

- It occurred to me that maybe the GC was simply binning the allocations as large objects and ignoring them for extended periods of time, so I split the single SpriteBatch of 13,000 down into 13 of 1,000.  Doing this caused it to peak at 400MB instead of many GB before the GC kicked in, however it caused me to hit issue #407, though a workaround is provided there.  Adding in the workaround and further splitting it into batches of 500, it went down to 300MB, but that is still with a garbage collection every second and puts it at 30 draw calls instead of 4.  This might be an ok range for desktop, but for mobile even after cutting it down to 5000 split into 10 batches it still runs out of memory fairly quickly (runs fine otherwise).

- If there's nothing that can be done in Direct2D or in Win2D to help with these memory allocations, then it might require some combination of all of these in order to work around it.

I don't know how much is being allocated per sprite, but if I guess around 64 bytes, 13,000 times that is 832,000 bytes, then multiply that times 120 frames per second it ends up around ~95MB/s in memory allocation which is still considerably less than what I'm seeing allocated.  Even if you take a third of that many sprites, it's a lot of allocation.

- If those could be reused based on a predicted SpriteBatch size range and which properties are passed in, maybe that could keep from having to throw it away every time.

- I don't know if there's any way for Win2D to expose options that allow for a little more control over what gets allocated so at least you know why and when it's happening.  Maybe this wouldn't help at all, since it's possible these are just unavoidable allocations.

Apologies for the wall.  If anyone has further insight into this, I would appreciate it.

**Comment by shawnhar** [comment]
Please provide a repro app (simplified as far as possible) and instructions on how to reproduce the behavior you are seeing.

**Comment by CMay** [comment]
Here's a simple repro using your simple sample from the repo.

There are 2 sets of tests in the draw method, but one is commented out.

[github issue 415.zip](https://github.com/Microsoft/Win2D/files/435526/github.issue.415.zip)

**Comment by shawnhar** [comment]
I can't extract the contents of that zip file - can you double check it's a valid archive please?

**Comment by CMay** [comment]
I did double check that the intended contents were in it, but I hadn't tried to extract it myself.  It does seem broken if extracted with explorer, but works fine with 7zip.  Updated the comment with a new one that's hopefully less fancy.

**Comment by shawnhar** [comment]
Thanks, that version works.

The app runs fine for me.  What are you looking at to determine that there is a memory leak?

**Comment by CMay** [comment]
This is what I'm seeing:
![diagnostic-tools-screenshot](https://cloud.githubusercontent.com/assets/640851/17957804/505cac0e-6a5a-11e6-8f02-24680183c9dd.png)

**Comment by CMay** [comment]
Some more details in case they're relevant:
- Windows 10.0.14393
- Visual Studio Community 2015 (14.0.25425.01 Update 3)
- .NETCore UWP 5.2.2
- Win2D 1.19.0
- Intel 5820K @ 4.4Ghz
- 32GB of RAM

I also made another comment in that sample regarding TargetTimeElapsed.  The documentation gave the impression that Win2D will try to do an update and a draw within that timeframe, so if you set it to 8ms it would gear itself to make sure a draw happens at the next opportunity after every 8ms.  That's not what I was seeing, so I had to set the TargetTimeElapsed to 3ms in order to hit a frametime of 8.3333.  If it was set to anything above 3ms, the framerate wavered closer to 60-95.

I'm not sure how that effects IsRunningSlowly, but it would be good to verify that TargetTimeElapsed is working as intended.  It's not particularly related to this current issue as it presents even at defaults, but having a custom TargetTimeElapsed does amplify it.

**Comment by shawnhar** [comment]
Looking at the code I found one place that could release memory earlier, so we'll make that change.  I'm not seeing any actual leak here, though.  That kind of sawtooth memory allocation pattern is typical of garbage collected runtimes, and does not indicate a problem as long as the memory is properly reclaimed when a GC takes place.

**Comment by CMay** [comment]
Thanks for looking into it.  The pattern isn't what concerns me so much as the amount of memory allocated before the GC decides to clean it up and the fact that mobile devices are throwing out of memory exceptions before the GC even realizes it needs to clean up.

If you don't see anything out of order, then that gives me a bit more confidence that some combination of the workarounds I came up with earlier will be worth doing in order to keep the memory footprint within a range.

On smaller sprite batches I can force a quick generation 0 cleanup at some interval and maintain the footprint at 60-80MB instead of 400MB with it still being a net performance win over DrawImage, but for those larger sprite batches I have to call a gen 2 which can get unreasonable very quickly depending on what else is going on in the app.

Between dynamically sizing batches based on device performance, freezing batches into CommandLists, using pools of CommandLists and strategically forcing garbage collections, it should be manageable.

I do wish the diagnostics tools window would show different marker colors for garbage collection to indicate which generation was being collected, though.

Again, I appreciate your time and look forward to seeing if the memory release change lessens the effect, even if it's only a little bit.

**Comment by shawnhar** [comment]
I just pushed a fix that reduces SpriteBatch memory usage in between GC cycles.   This will be in the next Win2D NuGet refresh - in the meantime you can pick it up by cloning the source and compiling yourself.

**Comment by CMay** [comment]
Just wanted to add here that build 1.20.0 completely resolved the issue, so now I can draw a single SpriteBatch of 20,000 while maintaining a flat memory footprint without resorting to the previously mentioned workarounds.  It really makes a huge difference.

Thanks again!
