### ISSUE TITLE
[Question] Is there an example of calling RunOnGameLoopThreadAsync from C++?

### ISSUE THREAD

**Issue by chuckries** [Microsoft/Win2D#416]
I know in C# you can pass a regular lambda and things are fine. I tried to pass a C++ lambda and it won't build because the method takes a `DispatchedHandler^`. I am having trouble finding a decent example of C++ DispatchedHandlers. Are there any examples you can provide?

**Comment by damyanp** [comment]
It's not a Win2D sample, but there's an example here that shows creating a DispatchedHandler in C++/CX:

https://github.com/Microsoft/Windows-universal-samples/blob/e13cf5dca497ad661706d150a154830666913be4/Samples/WRLInProcessWinRTComponent/cpp/cpp/Scenario1_OvenClient.xaml.cpp#L59

**Comment by chuckries** [comment]
Thanks!
