### ISSUE TITLE
[Question] What would it take to make a CanvasBitmap support 16 bit pixel format?

### ISSUE THREAD

**Issue by chuckries** [Microsoft/Win2D#418]
Specifically B5G6R5UIntNormalized. What work would be required to support this format for a CanvasBitmap being drawn in a CanvasAnimatedControl.

**Comment by shawnhar** [comment]
The first step before Win2D could support this pixel format would be to add it to Direct2D, which Win2D is built on top of.

What is your reason for needing this support?

**Comment by chuckries** [comment]
I am generating a bitmap with 16 bit color data and I was hoping to avoid manually converting the depth. Does Direct 2D not support 16 bit colors at all?

**Comment by shawnhar** [comment]
> Does Direct 2D not support 16 bit colors at all?

No.  I think mostly because not every D3D hardware feature level supported by Direct2D guarantees the availability of these formats.

The set of available formats is documented here: http://microsoft.github.io/Win2D/html/PixelFormats.htm

**Comment by Gavin-Williams** [comment]
This will need to be addressed soon. Because when I was looking at widescreen displays today I noticed that 3 out of the 4 I looked at were sporting 8 + 2 bit (frc) color. It's probably a matter of 12 months or so before we see true HDR computer displays.

**Comment by shawnhar** [comment]
Win2D does support 16 bit per channel HDR format - see the doc page linked above.

I'm going to close this issue as we don't have plans to add B5G6R5UIntNormalized any time soon.
