### ISSUE TITLE
Fail to compile 0.0.13

### ISSUE THREAD

**Issue by rvaquette** [Microsoft/Win2D#42]
d:\win2d-master\winrt\lib\canvasbrush.h(51): error C2220: warning treated as er
ror - no 'object' file generated [D:\Win2D-master\winrt\lib\winrt.lib.WindowsPh
one.vcxproj]

**Comment by shawnhar** [comment]
Please share:

1) What version of Visual Studio are you using
2) How are you compiling Win2D?  Using build.cmd, or win2d.sln?
3) What is the actual warning message?  (the text you quoted here is just saying that the build failed because of a warning that was reported earlier)

thanks,

**Comment by rvaquette** [comment]
Thanks for your help.

Here are my answers:
1) Visual Studio 2013
2) With Visual Studio (.sln)
3) 
1>------ Build started: Project: winrt.lib.Windows, Configuration: Release x64 ------
1>  pch.cpp
1>d:\win2d-master\winrt\lib\canvasbrush.h(51): error C2220: warning treated as error - no 'object' file generated
1>d:\win2d-master\winrt\lib\canvasbrush.h(51): warning C4265: 'ABI::Microsoft::Graphics::Canvas::CanvasBrush' : class has virtual functions, but destructor is not virtual
1>           instances of this class may not be destructed correctly
1>d:\win2d-master\winrt\lib\canvasimagesource.h(151): warning C4265: 'ABI::Microsoft::Graphics::Canvas::CanvasImageSourceDrawingSessionFactory' : class has virtual functions, but destructor is not virtual
1>           instances of this class may not be destructed correctly
1>d:\win2d-master\winrt\lib\canvasswapchain.h(163): warning C4265: 'ABI::Microsoft::Graphics::Canvas::CanvasSwapChainManager' : class has virtual functions, but destructor is not virtual
1>           instances of this class may not be destructed correctly
2>------ Build started: Project: winrt.dll.Windows, Configuration: Release x64 ------

**Comment by shawnhar** [comment]
That looks very much as if you have only a partial sync of the changes in 0.0.13.  How did you pull this code?  Is there any chance you have local changes to some files that could have led to a bad merge?

Check line 39 of your CanvasBrush.h  (https://github.com/Microsoft/Win2D/blob/master/winrt/lib/brushes/CanvasBrush.h#L39) - this should be:

       virtual ~CanvasBrush() = default;

but I think you must not have that in your local enlistment to be getting this error?

**Comment by rvaquette** [comment]
I am really sorry: you're right, my mistake was to have unzipped the 0.0.13 in the same directory as the previous version, and without cleaning the solution, that caused all these errors!!!

Thanks you very much for your help, and a long life to Win2D :-) !!!

**Comment by shawnhar** [comment]
Yay!  Glad we were able to figure it out.
