### ISSUE TITLE
Xml schema doesn't recognize the new Name tag.

### ISSUE THREAD

**Issue by Gavin-Williams** [Microsoft/Win2D#420]
Win2D doesn't recognize the new Name tag for the CanvasControl, it still requires x:Name to be used.

**Comment by shawnhar** [comment]
Afraid I don't know what the new Name tag is?

**Comment by Gavin-Williams** [comment]
Actually .. I was about to explain and for some reason CanvasControl now accepts Name as expected. When I checked for the error message, everything was OK. So I guess it was just a false issue.
