### ISSUE TITLE
[Question] Is it possible to increase the resolution of a bitmap with a PixelShaderEffect?

### ISSUE THREAD

**Issue by chuckries** [Microsoft/Win2D#421]
I am trying to implement a pixel smoothing effect using shaders. The effect will increase the resolution of a bitmap by 2x, 3x, or 4x and smooth pixels. I have found hlsl implementations of the effect [here](https://github.com/Armada651/hqx-shader). The issue I'm seeing though is that these shaders also use a vertex shader, not just a pixel shader. Is it possible to increase the resolution of a bitmap using only a pixel shader? If not, is it possible to use a vertex shader as well with a CanvasBitmap as a source?

**Comment by shawnhar** [comment]
Scaling an image is just a matter of changing what texture coordinates you sample the source texture at.

**Comment by chuckries** [comment]
I'm a little confused. My understanding of a pixel shader is that you return a single color for each input pixel. The effect I would like to produce would need to output 4, 9, or 16 pixels per input pixel, as each input pixel is expanded to a block or 2x2, 3x3, or 4x4 pixels.

**Comment by shawnhar** [comment]
It's the opposite of what you are thinking.  Pixel shaders run once per /output/ pixel.  Your shader code can sample from whatever input or inputs it needs to compute the color of the current output.

**Comment by chuckries** [comment]
So, the number of pixels that run through the shader match the resolution of the render target, and has nothing to do with the input texture?
