### ISSUE TITLE
Cached Geometry vs Sprite Batch

### ISSUE THREAD

**Issue by kevinross100** [Microsoft/Win2D#424]
Hi,

I am writing a few custom controls to help in my application to control an audio mixing console. A lot of these controls use fixed objects that move for example a fader will be a fixed object that moves up and down a track. 

Is it more efficient to have these as cached geometries or as sprites? On one control (a spectrum analyser) I have 100 bars each with a peak indicator should I use a sprite batch to draw all the peak indicators or use cached geometry?

Thanks

**Comment by shawnhar** [comment]
Drawing a precreated bitmap will usually be much faster than even the best optimized geometry drawing.

**Comment by kevinross100** [comment]
Thank you for your response, I will now lean my development towards that approach.
