### ISSUE TITLE
CanvasComposition.CreateDrawingSession should allow specifying DPI

### ISSUE THREAD

**Issue by dtaylorus** [Microsoft/Win2D#425]
When I use a `CanvasControl` in my UWP XAML app, the value of `CanvasDrawingSession.Dpi` is 120 and the rendered output looks reasonably good (about the same quality as the XAML-rendered output).

When I use `CanvasComposition.CreateDrawingSession` from a `CompositionDrawingSurface` in the same app, the value of `CanvasDrawingSession.Dpi` is 96, and the rendered output looks pretty bad, especially the text.

How can I increase the DPI of the `CanvasDrawingSession` returned from `CanvasComposition.CreateDrawingSession`?

The article on [DPI and DIPs](http://microsoft.github.io/Win2D/html/DPI.htm) states that the DPI is inherited from the control it is drawing onto, but I don't see a way to change the DPI on the parent control, which is just a plain XAML control.

Thanks!

**Comment by shawnhar** [comment]
The Windows.UI.Composition APIs don't really have the concept of DPI in the same way that it works in XAML.   Composition surface sizes are always in pixels, so Win2D always draws to them in pixel units.  If you are seeing something other than a 1:1 source vs. dest pixel mapping, that probably means you have a non-identity scale transform at some point in your tree of composition elements.

**Comment by dtaylorus** [comment]
Thanks for the quick reply!

The size and scale of the rendered output exactly matches that of the `CanvasControl`, and I don't have any `ViewBox` controls or any other control that I can imagine would be scaling the XAML controls.

Regarding the composition elements, I'm using `ElementCompositionPreview.SetElementChildVisual` to set exactly one child `SpriteVisual`, so I'm not creating my own tree of composition elements.

I tried setting the size of the drawing surface to 2x the `SpriteVisual` size and found it interesting that the rendered drawing surface was automatically scaled down to the size of the `SpriteVisual`. The result was that the geometry rendered by `CanvasDrawingSession` looked smooth, and that could have been a solution except the text was rendered at half size.

**Comment by shawnhar** [comment]
> The size and scale of the rendered output exactly matches that of the CanvasControl

Size in dips, or size in pixels?  If you are on a 120 dpi display, these are not the same thing.  XAML (and hence CanvasControl) operate in dips, but Windows.UI.Composition operates in pixels.

**Comment by dtaylorus** [comment]
Sorry, what I meant to say is that when I look at a screenshot, the rendered output of the elements take the same amount of space on the screen whether I use `CanvasControl` or `CompositionDrawingSurface`. In other words, the screen looks exactly the same (not stretched or scaled) in either case with the single exception that it's pixelated and curves have jagged edges.

As far as the code goes, the only thing I'm changing is that, instead of creating a `CanvasControl`, I'm using a plain XAML `ContentControl`, adding a `SpriteVisual` as a child with a surface brush, and creating a `CanvasDrawingSession` from the drawing surface.

If I understand what you're saying, it sounds like I should be creating the drawing surface with pixel dimensions, i.e., take the RenderSize of the XAML control in DIPs and convert to pixels to get the matching drawing surface size.

If I change the size of the `SpriteVisual`, it takes too much space on the screen as compared to the `CanvasControl` version. So that size appears to be specified in DIPs, not pixels.

If I change only the size of the `CompositionDrawingSurface`, then the geometry looks good (e.g., `DrawEllipse`) but the text is rendered too small.

**Comment by shawnhar** [comment]
This is stretching up against the limits of what I know about the composition APIs (which is not very much, especially when using composition APIs alongside XAML).

It looks like you could use CompositionSurfaceBrush.Scale to adjust for DPI.  An alternative would be to size your SpriteVisual in dips, but size your CompositionSurfaceBrush in pixels, and then set CompositionSurfaceBrush.Stretch to CompositionStretch.Fill.

**Comment by dtaylorus** [comment]
Ah, thanks! I played with `CompositionSurfaceBrush.Scale` and `.Stretch`. In short, I can get the geometry to look smooth, but again, the text is not scaling.

As far as I can tell, `CanvasDrawingSession.DrawText` is simply not scaling the fonts per the 'CompositionSurfaceBrush.Scale' setting, while other methods like `DrawEllipse` scale as expected.

**Comment by shawnhar** [comment]
I can't imagine how text could be scaled differently from geometry, if both are drawn to the same surface.  

Can you share a repro app?  (simplified as far as possible)

Thanks,

**Comment by dtaylorus** [comment]
Yes, I'll put together a repro. Thanks!






On Thu, Sep 8, 2016 at 12:09 AM -0400, "Shawn Hargreaves" <notifications@github.com> wrote:





I can't imagine how text could be scaled differently from geometry, if both are drawn to the same surface.

Can you share a repro app?  (simplified as far as possible)

Thanks,

**Comment by dtaylorus** [comment]
Here's a demo of the DPI issue. I was actually able to get the scaling solution to work with text by setting `compositionSurfaceBrush.Stretch = CompositionStretch.None` (seems incorrect, but it works).

However, the text still doesn't look nearly as good at 96dpi scaled down as it does at 120dpi, especially at the small sizes I need.

Also, it turns out that the difference I was seeing in scaling in my real app is in `DrawImage` (not `DrawEllipse`) versus `DrawText`. I'll see if I can reproduce that in the demo app.

[CompositionSurfaceDemo.zip](https://github.com/Microsoft/Win2D/files/462127/CompositionSurfaceDemo.zip)

**Comment by dtaylorus** [comment]
Here's a repro with an image. You can play with `CompositionOwnerDrawControl._ScaleFactor`. Set it to 1.0f and the image and text sizes will match the `CanvasControl` on the left. Set it to a higher value, and the text will stay the same size as the CanvasControl, but the image will be larger. I would expect them to scale consistently.

Of course, I wouldn't need to do any scaling at all if the DPI matched the `CanvasControl` DPI of 120 instead of the arbitrary and apparently unchangeable 96.

[CompositionSurfaceImageDemo.zip](https://github.com/Microsoft/Win2D/files/462413/CompositionSurfaceImageDemo.zip)

**Comment by dtaylorus** [comment]
Here's a screenshot showing the difference between CanvasControl (green background) and the composition API (red background) at scale factors of 1.0 and 2.0.

Notice that the text size is consistent in all cases, but the image is scaled up at the scale factor of 2.0.

Also notice that the text doesn't look very good even after the scaling hack is applied.

![screenshot1](https://cloud.githubusercontent.com/assets/2476671/18362651/aa55ac4e-75d4-11e6-8213-a922c5d2c529.png)

**Comment by shawnhar** [comment]
The difference in text scaling vs. image scaling is because you draw the image specifying the full size of your surface as destination region (which includes your scaling factor) but do not scale the text or how the final image is presented by composition.

To emulate the kind of DPI behavior XAML provides by default while using composition APIs, you should:

1. Scale the size of drawing surface from dips into pixel units before calling CreateDrawingSurface
2. Specify CompositionStretch.Fill
3. Set your drawing visual size to the size in dips (not pixels!)
4. Set CanvasDrawingSession.Transform to a scaling matrix that converts dips into pixels
5. Specify all subsequent drawing in dips rather than pixel units

Alternatively, you can skip #4 and #5 and specify your drawing in pixel units.

Your repro app scales wrongly because it is missing steps #2, #4, and #5.

**Comment by dtaylorus** [comment]
Thanks, Shawn! I didn't know about #4, and I missed #5, so those were a big help.

I have to find a good place to calculate the screen DPI and make sure it stays current when the app moves to a different screen, for example, but I think that should be solvable.

I appreciate the workaround!

What are your thoughts on making the DPI match XAML in this scenario without requiring all of these workarounds?

**Comment by shawnhar** [comment]
I don't think it would be appropriate to automatically set DPI when using Win2D with composition APIs.   Windows.UI.Composition is a lower level set of functionality than XAML, and gives the developer far more control over policy decisions, so Win2D isn't in a place to automatically guess what choices any particular app might want.

Perhaps we should expose a way for the developer to explicitly set DPI, though?  That's basically the same thing I am recommending you do here, but we could perhaps make it a little easier.

**Comment by shawnhar** [comment]
I'm going to re-title this and change it from question to suggestion.

**Comment by shawnhar** [comment]
This is addressed in Win2D 1.21.0 (released today)
