### ISSUE TITLE
DataType Conversion and trasparency performance on mobile

### ISSUE THREAD

**Issue by PKangu** [Microsoft/Win2D#426]
I'm trying to porting a simple html5 js game to win2d for any windows device.
I have a `CanvasAnimatedControl` with `Update` and `Draw` events binded to `canvas_Update` and `canvas_Draw` functions.
In `canvas_Update`, I reduce the size of a square by time, in `canvas_Draw` i draw it changing color. °It is already layered so i have that layer having trasparency.
On my Computer, it have no performance problem, it almost don't use CPU and runs really smooth.
On my Lumia 650 I can see  low FPS animation, even if I run it with CTRL+F5.
What's the best way to do it?

I change color using `Color.FromARGB()` function and making parameter changing.
those parameters are calculated dinamically depending by long values, so i need to call `Convert.ToByte()`

that's the only code i use to draw:

```
using(args.DrawingSession.CreateLayer(0.2f))
{
    color = Color.FromArgb(255, R, G, B);
    args.DrawingSession.FillRectangle(0, 0, Width, Height, color);
}
```

**Comment by shawnhar** [comment]
Layers are quite expensive for the GPU to process.  Sounds like the relatively low powered GPU in this phone doesn't have the horsepower to do that while smoothly animating.

If your real code is as simple as what you show here, there's no need for a layer at all - just modify the color passed to FillRectangle to change its alpha as well as color.

If you are doing something more complicated that does require the full flexibility of  the CreateLayer API, consider adjusting your CanvasControl.DpiScale property to reduce the resolution that the graphics are drawn at.  This trades visual quality for performance, which can be useful especially on lower powered hardware.

**Comment by PKangu** [comment]
Thank you for quick reply.
I've done some tests with what you said, effectively, lowering resolution was the solution. I'm also trying to avoid layering problem (I'll need it for more sofisticated overlapping drawings).
