### ISSUE TITLE
Performance and Best Practices on Mobile

### ISSUE THREAD

**Issue by PKangu** [Microsoft/Win2D#431]
Hello, I am writing some tiled graphics code in my app using CanvasAnimatedControl with Stretch="fill" and horizontal and vertical alignements set to "Stretch". Could this affect performances? I'm drawing with 980x560 px canvas, and testing on a Lumia 650 with win 10 anniversary.
Actually I have some blurred Circles (Blur does not affect performances as i tested the app with or without it), a semitransparent square all over those circles and some Bitmap (the same bitmap, multiple drawings). Each time i draw that bitmap I rotate it with a Transform2dEffect and a Matrix3x2 as rotation matrix. 
I have kinda 25 bitmap of size 100x100 px, Bitmaps are preloaded and so matrices, but i need to reapply rotation effect each time I draw because they could be changed from user inputs.
All this things are running very slow on the phone, like 8-15 FPS. Am I doing something Wrong?
When I use effects like GaussianBlur or Transform2DEffect, do I need to create e new instance of CanvasCommandList and use it as a source for the effect? (if I do it Once on CreateResources I get NullPointer when I use it)
Thank you for help!

**Comment by shawnhar** [comment]
Tiling a bitmap is a near-free operation for GPU hardware, not significantly different to drawing something untiled.

One thing to check is whether you are scaling this bitmap very much.  Scaling down large bitmaps to a smaller size can be inefficient for GPU texture fetch cache coherency.

I'm suspicious of your statement that the blurs do not affect performance, though.  Blur is one of the most expensive image effects, and I would expect this to be a significant factor especially if you have many blurs active at the same time.

Remember that complete performance is the sum of everything you draw, so each element may be fine individually but too slow when you put them all together.  The simplest way to get an idea is try turning off different pieces to see how performance changes with and without different permutations of what is being drawn.

Also consider adjusting CanvasAnimatedControl.DpiScale - this can be an easy way trade off image resolution vs. performance.

> do I need to create e new instance of CanvasCommandList and use it as a source for the effect? (if I do it Once on CreateResources I get NullPointer when I use it)

You can reuse a command list multiple times.  Null reference exception suggests there is something wrong with your program logic that was supposed to initialize it.

**Comment by PKangu** [comment]
Thank you for your reply,

I checked how I initialize The `CommandList` and I do it in the `CreateResource `event of the Canvas.
The Error i get is not a `NullPointer`, probably I confused it with something I already solved, I got this:

`CanvasCommandList.CreateDrawingSession cannot be called after the CanvasCommandList has been used as an image.`

What's the right way to Having only a few things with a certain effect?
What I do is the folloiwng:
in CreateResources, I do

```
cl = new CanvasCommandList(canvas);
LastDraw = new GaussianBlurEffect();
```
in Draw:

```
ctx = cl.CreateDrawingSession();    //here's the error
//draw some circles, applying blur and finally
args.DrawingSession.DrawImage(cl);
```

the fact is that the position and the size of those mentioned circles may vary by the time, so i can't reuse a single image.

Anyway, over all this things, I have some tiles being rotated at certain conditions, the Size of the tiles is 100px, and they are drawn with a 1:1 scale, trying to disable those being drawn does not affect performances as you expected.
Canvas is undersized respect to screen resolution (that's why using the native resolution would make it run really slow)

I already noticed that I was drawing some elements with trasparency (`Colors.FromArgb(...)`), now I disabled those and gained some FPS, so now I have always over 30.

**Comment by shawnhar** [comment]
> CanvasCommandList.CreateDrawingSession cannot be called after the CanvasCommandList has been used as an image.

Ah, ok.  Once you have created a command list you can use it as a source (drawing it somewhere else) many times, but you cannot modify its contents.  This is a record-once, then use-many-times type.


> What's the right way to Having only a few things with a certain effect?

Drawing those things into either a command list or a rendertarget is the best way to do this.

**Comment by shawnhar** [comment]
Closing as I believe this has been answered.
