### ISSUE TITLE
Use XAML reference tracking protocol to avoid memory leaks when win2D is used from C# project

### ISSUE THREAD

**Issue by Opiumtm** [Microsoft/Win2D#432]
There is known limitation of Win2D library. Without some manual steps from C# developer, Win2D controls [would leak](https://microsoft.github.io/Win2D/html/RefCycles.htm).

Here is a documented protocol to avoid it.
[Protocol to avoid memory leaks when using C++ XAML controls from C# project](https://msdn.microsoft.com/en-us/library/windows/desktop/jj542495(v=vs.85).aspx)

**Comment by shawnhar** [comment]
We got pretty excited when we first discovered IReferenceTracker a few years ago.  Unfortunately, upon looking into more carefully we learned that this is not useful for Win2D.  IReferenceTracker is part of the mechanism used by XAML to overcome this problem, but there are other things needed for a complete solution which we were not able to find any way to do in Win2D.
