### ISSUE TITLE
ScrollViewer and CanvasControl

### ISSUE THREAD

**Issue by tanhuazh** [Microsoft/Win2D#433]
I put CanvasControl inside ScrollViewer so I can zoom and pan the CanvasControl.

But after zooming, the drawing becomes blurry.

I tried other WinRT controls like TextBlock, after zooming, text is crystal clear.
I tried CanvasVirtualControl, not working either.
I tried to find properties of ScrollViewer so I can make zooming virtual so transformations will be done by CanvasControl itself, cannot find such properties like CanContentScroll in WPF.

Eventually I came up with a hack that put CanvasControl outside ScrollViewer, and put a dummy control inside ScrollViewer, then transformations will be done by CanvasControl itself.

It works, but very ugly.

Can someone help to point out the right way of doing this?

Thanks in advance.

**Comment by shawnhar** [comment]
Win2D is a much lower level API than XAML, so you need to manage pixel resolution and control resizing yourself when doing this kind of zoom.

When you put a CanvasControl inside a ScrollViewer, that doesn't automatically change the size or pixel density of the control.  The Win2D control just draws to a bitmap surface.  Then XAML pans or scales that bitmap according to the ScrollViewer state, so when you zoom in you are just getting a scaled up version of that same bitmap.

If you want to redraw the bitmap at higher pixel density when the view zooms in, you can change the CanvasControl.DpiScale property in response to zoom level changes.  This can quickly lead to the control becoming very large at high zoom settings, so you probably also want to start using CanvasVirtualControl to avoid size limitations.  Check out the Mandelbrot demo in Example Gallery for an implementation of this approach.

> Eventually I came up with a hack that put CanvasControl outside ScrollViewer, and put a dummy control inside ScrollViewer, then transformations will be done by CanvasControl itself.

This is also a valid approach.

**Comment by tanhuazh** [comment]
Thank you so much.

Now I use CanvasVirtualControl and adjust DpiScale based on ZoomFactor, it works perfectly.

And controls like TextBlock adjusts Dpi automatically, right?

**Comment by tanhuazh** [comment]
Have to reopen this issue because of another problem.

I just found out that if I change DpiScale, CreateResources is raised again, that means I need to recreate all the resources, and it is slow.

I think there is probably valid reason to re-create resources once the DpiScale is changed.

But that sure makes smooth zooming not quite possible.

My questions are:

Do I have to re-create resources? Or maybe solid color brush is OK, maybe gradient brush is not?
Sure I can wait for zooming stabilize and change DpiScale after, then the zooming is not smooth anymore.

If I have to re-create all resources, then I might have to go back to hack solution.

Thanks in advance.

**Comment by shawnhar** [comment]
See https://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_UI_CanvasCreateResourcesEventArgs_Reason.htm
