### ISSUE TITLE
Draw in specified area

### ISSUE THREAD

**Issue by gaminn** [Microsoft/Win2D#434]
Is it possible to specify rectangular area somewhere in canvas (e.g. x = 100, y = 100, width = 200, height = 200) and then draw inside this area using relative coordinates (e.g. drawing point at x = 50, y = 50 in this area will draw point at absolute coordinates x = 150, y = 150 of the canvas)?

**Comment by shawnhar** [comment]
To change the coordinate system used for drawing, modify CanvasDrawingSession.Transform.

To clip drawing to a rectangular area, use CanvasDrawingSession.CreateLayer().

**Comment by gaminn** [comment]
Thanks!
