### ISSUE TITLE
CanvasAnimatedControl oddly clipped

### ISSUE THREAD

**Issue by andyphilpotts** [Microsoft/Win2D#438]
CanvasAnimatedControl will not fill the area it is in, this can be repro-ed on my machine with the Win2D samples, so this is not just in my code. CanvasControl is OK, it fills the area it is assigned, but CanvasAnimatedControl  only draws in about half the area, to the top left.

I can repro just by adding a ClearColor, so I can see where it is drawing

This was working, and I think this may have regressed with build 14942

**Comment by shawnhar** [comment]
Please share details of how to reproduce this.

**Comment by andyphilpotts** [comment]
All I have to do is build the samples, they show the same effect I see in my own application. Any of them that use the CanvasAnimatedControl 

Specifically I repro-ed with the burning text demo.

I used the nugget version of Win2D to repro, so currently I am trying to build Win2D locally, see if I can repro then too

**Comment by andyphilpotts** [comment]
I can no longer repro, several things have changed on my local machine, but I cannot isolate what exactly what resolved this.
