### ISSUE TITLE
Recieve Input events on AnimatedCanvasControl whilst paused?

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/Win2D#44]
Hey there,

So I'm looking at switching from CanvasControl to AnimatedCanvasControl - but in my application I only need to redraw the screen when the user is interacting with the canvas (which will be ~50% of the time), and I want the interactions to be as responsive as possible. 

From what I've *seen* the input events seem to get processed faster when using AnimatedCanvasControl - however for the sake of battery life and processor usage I don't want / need it's render thread running all the time. So, I could pause it when the user removes their finger, and then resume the render thread when they start directly interacting with the canvas again.

Sounds logical to me, but at the moment pausing the AnimatedCanvasControl also seems to pause processing input events. I could potentially use the XAML PointerDown/Pressed event to start up the render thread but I was wondering if there were plans for otherwise, or if it were even a sane idea to want to do things this way and that there isn't some specific technical reason why it's not a good idea to let us choose to always process the events.

EDIT: And of course, just after I've posted this I've seen this on the backlog. Well, +1 for this being done then! :P I'll close this for not reading properly

**Comment by shawnhar** [comment]
Thanks for bringing this up.   It's always useful to get confirmation that someone has actually run into an issue we put on the backlog in real life!

**Comment by JohnnyWestlake** [comment]
Just to add when you get around to this, would there be a way to stop the render thread using so much CPU usage whilst doing so?

My current solution was too add a Boolean to CanvasAnimatedControl that skips over calling update / draw if set (ergo just processing the input). Problem being is that keeping the render thread going uses a LOT of CPU usage just idling around even when it's not redrawing or updating, presumably because it's just infinitely spinning, which causes the fans on my Surface Pro 3 to spin up and presumably suck battery life like crazy.

**Comment by JohnnyWestlake** [comment]
Ideally I think in my case, it would be nice if there was an option to delay the render thread from running again until it's drawing has been presented. Obviously, not ideal for gaming usages, but I'm not really making a game anyway :P
