### ISSUE TITLE
CanvasAnimatedControl not working with x86

### ISSUE THREAD

**Issue by MagnusKieler** [Microsoft/Win2D#440]
I am having trouble using the CanvasAnimatedControl on Win2D, when it is set to x86. When it's set to x64 there is no problem. 

Here is the error message I get when trying to run my program in x86:

> An exception of type 'Windows.UI.Xaml.Markup.XamlParseException' occurred in JetBlock.exe but was not handled in user code
> 
> WinRT information: Cannot create instance of type 'Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedControl' [Line: 15 Position: 58]7

I first started having this issue after there were alternative versions to choose when creating a new project in Visual Studio. When I used the Build 10586, there was no problem, but when I am now using the Windows 10 Anniversary Edition Build 14393 as my Target Version this issue occurs.

**Comment by shawnhar** [comment]
This is usually a sign of having some stale intermediate files left over from an earlier configuration of your project.  Try doing a clean rebuild, and/or deleting all the obj and bin folders.

**Comment by shawnhar** [comment]
Closing issue due to lack of repro steps.
