### ISSUE TITLE
Smooth line between two points

### ISSUE THREAD

**Issue by sagi4422** [Microsoft/Win2D#441]
Hi,
I am using ChartRenderer class to draw a chart.
I was wondering if there's an option to smooth the line between two points on the graph?

Thanks.

**Comment by damyanp** [comment]
Win2D doesn't have a class called ChartRenderer.  I found that this project exists: https://github.com/xyzzer/Win2DChartSample, which does have a ChartRenderer class.  If this is what you are using then maybe this question would be best asked there?

**Comment by sagi4422** [comment]
You are right.
Thanks.
