### ISSUE TITLE
CanvasControl.Dpi doesn't equals to DisplayInformation.GetForCurrentView().RawDpiX

### ISSUE THREAD

**Issue by LinJianping** [Microsoft/Win2D#442]
My desktop is Thinkpad X1 Carbon with a resolution of 1920*1080. In my application, I found the return is different between CanvasControl.Dpi and DisplayInformation.GetForCurrentView().RawDpiX which the former returns 144 and the other returns 157.

**Comment by shawnhar** [comment]
CanvasControl.Dpi is determined by DisplayInformation.LogicalDpi, not RawDpiX.
