### ISSUE TITLE
draw lines thinner than 1 unit by CanvasDrawingSession.DrawLine 

### ISSUE THREAD

**Issue by LinJianping** [Microsoft/Win2D#443]
How can I draw lines thinner than 1 unit by CanvasDrawingSession.DrawLine()?

**Comment by shawnhar** [comment]
You can specify any width you like, including values less than 1.  If you try to draw something smaller than a single pixel in size, the result will depend on antialiasing.

**Comment by LinJianping** [comment]
I have solved this problem by the following manner:
`CanvasSolidColorBrush brush = new CanvasSolidColorBrush(ds.Device, Colors.Red);
CanvasStrokeStyle strokeStyle = new CanvasStrokeStyle();
ds.DrawLine(startPoint, endPoint, brush, (float)0.2, strokeStyle);`

**Comment by shawnhar** [comment]
You don't need to bother with a brush or stroke style for this.  Just pass what color and line width you want directly to the appropriate overload of the DrawLine method.

**Comment by LinJianping** [comment]
Thank you very much. @shawnhar 
I have made a mistake. Firstly I draw the line using `ds.DrawLine(lastPoint, point, color, 0.2);` and vs show error tip because 0.2 is a double not a float. After I modified it to `ds.DrawLine(lastPoint, point, color, 0.2f);` , it works.
