### ISSUE TITLE
How to draw the waveform without re-drawing the grid when using CanvasControl?

### ISSUE THREAD

**Issue by LinJianping** [Microsoft/Win2D#444]
In my application, I need to draw the real-time waveform in the grid. Now I'm using `CanvasControl` and draw the waveform and grid when the `Draw` event is fired. But the grid will not change when the window layout doesn't change, and I don't want to re-draw the grid every time(for performance consideration).  Is there any way to achieve such a purpose?

**Comment by shawnhar** [comment]
You could cache the grid image in a CanvasRenderTarget.   Depending on how complex your grid drawing is, though, just drawing it again from scratch every time might actually be faster than drawing the contents of a cached rendertarget.  Try it and see.

**Comment by LinJianping** [comment]
Thank you for your suggestion. @shawnhar
