### ISSUE TITLE
MediaCapture with GPU based IBasicVideoEffect issue still there

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/Win2D#446]
@shawnhar 
Hi,

This is regarding the issue reported in #350 and #397.

I am currently using a Lumia 640 with build 14951. Though this issue was fixed in an earlier build (14393), I believe it has returned again. I am still seeing the **Media Capture Failed: The parameter is incorrect** error message.

Also, whenever I add a new VideoEffect to the VideoPreview stream of MediaCapture, in my own sample application, the CaptureElement does not display any video (just a white screen). Removing the VideoEffect shows the preview normally. ( I have reported it [**here**](https://github.com/Microsoft/AppDevXbox/issues/4) )

Could you please look into this issue?

**Comment by 13thsymphony** [comment]
I tried to repro the "parameter is incorrect" issue on two Lumia 950's with 14959, and they both worked.

**Comment by ratishphilip** [comment]
@13thsymphony 

It is happening on my **Lumia 640** with 14951. Are any of the features in Win2d not supported in Lumia 640?

**Comment by 13thsymphony** [comment]
The previous issue (#350, #397) repro'ed on both the 640 and 950. We still need to investigate what you're seeing, but this suggests it is a new issue.

**Comment by ratishphilip** [comment]
As I have elaborated [**here**](https://github.com/Microsoft/AppDevXbox/issues/4), if I comment this line in my code, the preview works

```C#
var effect = await _mediaCapture.AddVideoEffectAsync(
                new VideoEffectDefinition(typeof(TheEffect).FullName),
                                            MediaStreamType.VideoPreview);
```

**Comment by ratishphilip** [comment]
If I add a IBasicVideoEffect to the VideoPreview, all I see is a white screen.

**Comment by 13thsymphony** [comment]
Can you try the camera effect demo in the Win2D Example Gallery?

**Comment by ratishphilip** [comment]
Yes I did. That's when I am getting the **Media Capture Failed: The parameter is incorrect** error message.

**Comment by ratishphilip** [comment]
Upon debugging I am getting a MediaCapture Failed event after this line

```C#
await mediaCapture.AddVideoEffectAsync(new VideoEffectDefinition(typeName, effectPropertySet),
                MediaStreamType.VideoPreview);

```
![win2d_example_error](https://cloud.githubusercontent.com/assets/7021835/19826358/d4c0b322-9d3c-11e6-8673-afe24b14b74b.png)

**Comment by ratishphilip** [comment]
@shawnhar @13thsymphony 
I updated my Lumia 640 to 14955 yesterday.
I am still seeing the same error.

**Comment by 13thsymphony** [comment]
I was finally able to get my hands on a Lumia 640 and upgrade the OS to 14955, and this does indeed repro. This appears to be another regression in the underlying OS; we are investigating more.

**Comment by ratishphilip** [comment]
@13thsymphony 
Thank you. Hope a solution is found soon.

**Comment by 13thsymphony** [comment]
For my reference, this is internal bug 9637471

**Comment by ratishphilip** [comment]
Does this error happen on devices older than Lumia 640? (Like Lumia 550)?

**Comment by 13thsymphony** [comment]
Our current hypothesis is that the issue hits devices using the Adreno 300 series of GPU (DX feature level 9_3). This includes the 550, but we haven't tried it explicitly. The Lumia 950, for example, uses a 400 series and is not affected (DX feature level 11_1).

**Comment by ratishphilip** [comment]
So to effectively use all the features of Win2d and the camera, the baseline device is Lumia 950?

**Comment by ratishphilip** [comment]
@shawnhar @13thsymphony 
any updates on this bug?

**Comment by ratishphilip** [comment]
@shawnhar @13thsymphony
any updates on this bug? 
Is it fixed in 14977 build?

**Comment by shawnhar** [comment]
No, this is not fixed yet.

**Comment by shawnhar** [comment]
This issue should be fixed in Windows OS builds from mid-Feb onwards.

**Comment by ratishphilip** [comment]
Yes it is. Just checked on my L640.

Thank you very much.
