### ISSUE TITLE
Is there a way to stop the GameLoop in CanvasAnimatedControl?

### ISSUE THREAD

**Issue by tgckpg** [Microsoft/Win2D#448]
Basically what I want is to stop the GameLoop and keep the last result drawn in the Canvas.

**Comment by shawnhar** [comment]
See https://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_UI_Xaml_CanvasAnimatedControl_Paused.htm

**Comment by tgckpg** [comment]
Oh I didn't noticed that ( sorry ), solved:)
