### ISSUE TITLE
The buffer allocated is insufficient.

### ISSUE THREAD

**Issue by Survivon** [Microsoft/Win2D#450]
Hi, I'm faced with problem to impose two layer, ink canvas and XAML layer by your libs in windows phone 550 and 435 
![screenshot_2](https://cloud.githubusercontent.com/assets/6324691/19854251/be1edcca-9f76-11e6-85bf-5fa24f50aec3.png)

in this code i get current issues, if i set smaller size of width and height it doesn't drop current issues but image set not correct .

Please, help me. Best regards, Dmitriy

**Comment by shawnhar** [comment]
Bgra8 format data takes up 4 bytes per pixel.

**Comment by Survivon** [comment]
I should to use other format?

**Comment by shawnhar** [comment]
Is your target bitmap actually in format Bgra8?

Is it's DPI actually the same as the logicalDpi value you pass here?

**Comment by shawnhar** [comment]
btw. I'm curious why you need BitmapEncoder at all, rather than just using the built-in CanvasBitmap save APIs?

**Comment by Survivon** [comment]
I'm curious why you need BitmapEncoder at all, rather than just using the built-in CanvasBitmap save APIs?

Thank you, I try use this

**Comment by Survivon** [comment]
Thank you, by Canvas API it works
