### ISSUE TITLE
Question: Win2D on Raspberry Pi performance

### ISSUE THREAD

**Issue by BubblegumYeti** [Microsoft/Win2D#451]
Just for fun, I installed my win2D game to the Pi 3 and performance was really bad. Probably Pi 3 is not really your target device, but why is performance so bad? I assume it is because everything is emulated in software? Any pointers on how the get the most out of the Pi? I was actually thinking of writing some graphical things on Pi to visualize IoT data.

**Comment by shawnhar** [comment]
Afraid I don't know enough about the Pi to have anything useful to say here...  You might get more useful replies asking this on a Pi forum?  (level of my ignorance is I don't even know where/what that would be)

**Comment by JohnnyWestlake** [comment]
AFAIK, (and I haven't followed this in a couple of months), there isn't a proper GPU driver for Pi 3 yet on IoT? It's just using the Microsoft Basic Display Driver which probably isn't doing it any favours.

**Comment by BubblegumYeti** [comment]
Yeah that is what I assume. So I guess atm, we cannot use the Pi for any meaningful Win2D stuff. Pity :S 
I could think of some very cool applications.

**Comment by enghch** [comment]
Has anyone tried this again since the Creators Update of IoT?

**Comment by JohnnyWestlake** [comment]
@enghch according to https://developer.microsoft.com/en-us/windows/iot/explore/deviceoptions , no Raspberry Pi devices feature DirectX acceleration yet. If you need an IoT board that does, best to go with either an Intel or Qualcomm based device, as they have graphics drivers already developed and supported (from big Windows and Windows Mobile respectively)
