### ISSUE TITLE
Stride for CanvasRenderTarget.SetPixelBytes?

### ISSUE THREAD

**Issue by rndfax** [Microsoft/Win2D#453]
Hello everyone!

I encountered a problem in rendering textures. Consider this code:
```
var data = new byte[64 * 64 * 4];
var cd = CanvasDevice.GetSharedDevice();
var offscreen = new CanvasRenderTarget(cd, 640, 480, 96)
```

I fill `data` with some data and then I need to map it to the `offscreen`. I do it like this:
```
offscreen.SetPixelBytes(data, 0, 0, 64, 64);
```

But the problem is that I need it to map to different locations of the `offscreen`.
For example, if I'm trying to map the `data` at X = 600 (near the end of the `offscreen` X-bound, the `data` array of 64x64 can't fit):
```
offscreen.SetPixelBytes(data, 600, 0, 64, 64);
```
I get an ArgumentException.

1) Am I doing something wrong? Is there something I must do to map it? Copying into smaller array is forbidden by performance constraints.
2) I can clamp the `data` and call `SetPixelBytes` with appropriate sizes like this:
```
offscreen.SetPixelBytes(data, 600, 0, 40, 64);
```
but I must say what stride is for the `data` (the stride is 64 * 4) and I can't do this because there is no such method in Win2D.
Original Direct2D method `CopyFromMemory` for ID2D1Bitmap has a parameter `pitch` which is what I need, but it's encapsulated in Win2D.

Any help?

**Comment by shawnhar** [comment]
The data consumed by SetPixelBytes is always tightly packed.  You can provide a larger array than is needed by the call, in which case it will ignore the extra data, but this API cannot do a gather operation from different regions of a larger input array.

If you cannot arrange for your source data to be tightly packed, you have two options:

1) Interop and use native Direct2D APIs for this operation
2) Rearrange your data to pack it before calling SetPixelBytes

I'm skeptical about your assumption that copying this data into a smaller array first would not meet performance goals.  Do you have measurements on that?  Doing this kind of CPU -> GPU update at all is a very expensive path for hardware accelerated rendering APIs such as Win2D.  Compared to that, I would be amazed if the cost of rearranging a few thousand bytes on the CPU was enough to even clear the profiling noise floor...

**Comment by rndfax** [comment]
@shawnhar Thank you for fast reply!

> I'm skeptical about your assumption that copying this data into a smaller array first would not meet performance goals. Do you have measurements on that?

Totally right question, but no I didn't. Here some new information about my concernings. I have a screen of 1920x1080 pixels and I need to map 64x64 `data` buffers along all vertical edges of the screen. And that's kinda like 1080 / 64 * 2 =~ 33 copies of (in the worst case) 63 * 64 * 4 bytes = 16182 bytes. So in total it will be 33 * 16182 = 534006 bytes =~ 521KB. But there should be at least 24fps, so 521KB * 24 = 12MB per second - this number is scared me, because this is not the only task that CPU will do during mapping `data` at 24fps - that's the problem... And if Direct2D is supported this out-of-box why to do an additional job?

> but this API cannot do a gather operation from different regions of a larger input array.

Yes `Interop and use native Direct2D APIs for this operation` is an answer, but...
Say, is there any chance for new overload in Win2D: SetPixelBytes(byte[] valueElements, int left, int top, int width, int height, int pitch) which passes `pitch` to CopyFromMemory:
```
void SetPixelBytesImpl(
...
        ThrowIfFailed(d2dBitmap->CopyFromMemory(&subRectangle, valueElements, pitch));
...
```
?

From docs of Direct2D (https://msdn.microsoft.com/en-us/library/windows/desktop/dd371155(v=vs.85).aspx):
```
The stride, or pitch, of the source bitmap stored in srcData. The stride is the byte count of a scanline (one row of pixels in memory). The stride can be computed from the following formula: pixel width * bytes per pixel + memory padding.
```
As I understand that's exactly what I need!

**Comment by shawnhar** [comment]
Are these images changing every frame and all different, or can you cache and reuse them?

I think you are right to be concerned about performance, but not about the cost of CPU side rearranging this data.  Sending so much fresh bitmap data from CPU to GPU every frame is indeed going to tax performance, and is really not what Win2D, D2D, or D3D itself for that matter are optimized for.  By far the biggest cost here will be inside the SetPixelBytes call itself.

For best performance I recommend looking into ways to cache and reuse these buffers on the GPU, or if it is possible to generate the data entirely on the GPU in the first place.

Win2D doesn't expose a stride parameter on this API mostly just because of complexity.  There is a cost to every API we add, and this option isn't something we've seen much need for.

**Comment by rndfax** [comment]
> Are these images changing every frame and all different, or can you cache and reuse them?

They are changing every frame. No caching is possible.

Thank you, @shawnhar for your help! It seems interop is the only way...
