### ISSUE TITLE
Support for Geometry mini language for creating CanvasGeometry 

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/Win2D#456]
Hi,

I am not sure if this question  has been asked before.
Is there any plan to support the WPF style or SVG style geometry mini language to create CanvasGeometry?

**Comment by shawnhar** [comment]
This has come up before (#186) at which time we didn't feel it was something that really fit as part of Win2D itself.

There is an SVG implementation on github: https://github.com/mntone/SvgForXaml but I haven't used this myself so can't vouch for it one way or the other.

Damyan (one of the Win2D team) started prototyping a different SVG implementation at one point.  That is also on github: https://github.com/damyanp/SvgWin2D.  It is very incomplete and not being maintained, but might be a useful starting point if you're just looking for some pieces of code to reuse.

**Comment by ratishphilip** [comment]
@shawnhar Thank you.

**Comment by ratishphilip** [comment]
@shawnhar I have implemented my own parser for the SVG/XAML path data and it now successfully  converts the mini language to appropriate **CanvasPathBuilder** commands.

It would be great if you could have a look at my implementation. Any suggestions/comments are welcome.

You will find more details [here](https://wpfspark.wordpress.com/2016/12/24/compositionprotoolkit-v0-5-0-holiday-edition-released/).

**Comment by shawnhar** [comment]
Cool project!  I saw this on Twitter earlier today.
