### ISSUE TITLE
Draw image on CanvasControl from URI

### ISSUE THREAD

**Issue by mister-giga** [Microsoft/Win2D#457]
I have to show many images on CanvasControl at a time. I have image links and how can I draw all that images? 
I try to draw it on the Draw event, but after it downloads from internet at the moment of drawing it via CanvasDrawingSession I get ObjectDisposedException because CanvasDrawingSession is already disposed...

**Comment by shawnhar** [comment]
You have to finish all your drawing work directly inside the Draw event handler.  If you later want to redraw in response to changing data or state, call CanvasControl.Invalidate.

**Comment by mister-giga** [comment]
Thank you.
