### ISSUE TITLE
How to catch mouse hover

### ISSUE THREAD

**Issue by mister-giga** [Microsoft/Win2D#458]
I have many images drawn on canvas. How can I catch the mouse hover event for each image to blur the image which is hovered?

**Comment by shawnhar** [comment]
Win2D does not directly provide any input processing functionality.  It is up to you to hook XAML input events (such as PointerMoved or PointerPressed), do whatever processing you need in response to these, and redraw your Win2D graphics in response.

**Comment by mister-giga** [comment]
And how can I detect which image is pressed??
All images are on one CanvasControl

**Comment by shawnhar** [comment]
This is code you will have to write yourself.  Input handling and hit testing is not a built-in feature of Win2D.

The input events tell you what point was pressed, and you already know where each image is positioned (because it was your code that drew them there).

**Comment by mister-giga** [comment]
Ok I understand. Thank you very much 😊

**Comment by iiroloukkalahti** [comment]
So we need to keep the 'drawing instructions' save for later analysis.

So far I've been reading thru the documentation. I'm thinking about drawing geometrical shapes. If I've undestood correctly - I'd draw each shape to it's own `CanvasGeometry`. `CanvasGeometry.ComputeBounds()` should return a rectangle reaching from the most outer drawn pixels, right? So basically that rectangle could be used for a really basic hit-testing?

**Comment by shawnhar** [comment]
Yes, you can use the bounding rectangle as an approximation for hit-testing.  CanvasGeometry has a number of other methods to support more accurate testing against complex shapes.

**Comment by iiroloukkalahti** [comment]
I did some more demoing and found out more really useful features for hit-testing: `CanvasGeometry.FillContainsPoint(Vector2 point)`. Great.
