### ISSUE TITLE
Guess the size before draw

### ISSUE THREAD

**Issue by mister-giga** [Microsoft/Win2D#460]
For example I want to draw text by CanvasDrawingSession.DrawText method, and I want to align it center. 
How do I get the required size before drawing, so I can set its position.

**Comment by clandrew** [comment]
You could use CanvasTextLayout.LayoutBounds. Although, there's some logic in CanvasTextLayout to do the centering for you- then you don't need to bother with size estimates at all.

To do it:
- Create a CanvasTextLayout object for your text, setting *requestedWidth* and *requestedHeight* to the width and height of your layout box
- Set the text layout's HorizontalAlignment to Center
- Use CanvasDrawingSession.DrawTextLayout to draw the text at the top-left corner of your layout box

**Comment by mister-giga** [comment]
@clandrew  thanks for reply but sorry for bad question. It is not only about texts.
I want to make something like StackPanel (StackLayout, LinearLayout...) So I will draw unknown shapes and objects under each other, when I draw first, I must know what size will it take or will it need to be drawn well, to put right coordinates for seconds object, How to do it?

**Comment by shawnhar** [comment]
A general purpose way to measure the size of any graphics is to draw them into a command list, then call GetBounds on the command list.

That can be quite expensive compared to more specialized approaches for specific types of drawing, though.  For instance querying CanvasTextLayout.LayoutBounds will be much faster than drawing the text layout into a command list first.
