### ISSUE TITLE
Render prepared resources.

### ISSUE THREAD

**Issue by p69** [Microsoft/Win2D#461]
I encountered with quite strange behavior.
You can find sample for reproduce [here](https://github.com/p69/Win2dRresourceCreation)

The main goal is to draw some geometries with opacity mask.
The best way to do it that I have found is to use `CanvasActiveLayer`
First I need to create opacity brush, which is `CanvasImageBrush`. I'm not sure that I'm doing it right, but I haven't found better solution other then offscreen drawing:

```c#
        private ICanvasImage CreateOpacityMask(ICanvasResourceCreator resourceCreator, double width, double height)
        {
            var device = CanvasDevice.GetSharedDevice();
            var target = new CanvasRenderTarget(device, (float)width, (float)height, 96);
            using (var session = target.CreateDrawingSession())
            {
                session.Clear(Colors.Transparent);
                foreach(var geometry in _maskGeometry)
                {
                    session.FillGeometry(geometry, Colors.White);
                }
            }
            return target;
        }
```
And then I create `CanvasImageBrush` and `CanvasActiveLayer` like this
```c#
        private void Canvas_Draw(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args)
        {
            var opacityMask = CreateOpacityMask(sender, 800, 800);
            var brush = new CanvasImageBrush(sender, opacityMask);
            using (var layer = args.DrawingSession.CreateLayer(brush))
            {
                args.DrawingSession.FillRectangle(new Rect(100, 0, 500, 350), Colors.BlueViolet);
            }
        }
```
And this approach works fine with `CanvasControl` but fails with exception when I tried it with `AnimatedCanvasControl`
![Exception](http://puu.sh/soV9i/8aba77b288.png)
I understand the error. It can't render geometry on offscreen canvas, because those geometries were created using resources creator from UI canvas control. 
And my first question why does it work with `CanvasControl` and doesn't with `AnimatedCanvasControl` ?

Ok, I've tried to fix it. I create geometries for mask using resources creator from offscreen canvas. And..... Still gettting error while trying to create brush.
![Exception2](http://puu.sh/soVxm/418e5b26ef.png)
Ok, got it,
The best solution that I have found is to copy all pixels into memory and create new bitmap.
```c#
var opacityMask = CreateOpacityMask(sender, 800, 800);
            var bytes = opacityMask.GetPixelBytes();
            var bmp = CanvasBitmap.CreateFromBytes(sender.Device, bytes, 800, 800, Windows.Graphics.DirectX.DirectXPixelFormat.B8G8R8A8UIntNormalized);
            var brush = new CanvasImageBrush(sender, bmp);
```
And finally... It works.
But I don't understand. Why the behavior of `CanvasControl` and `AnimatedCanvasControl` is different? 
And actually, because of this particular qualities of `AnimatedCanvasControl` I can't use it. The only one solution for my concrete case is to create custom timing logic for `CanvasControl`.
Any suggestions? Did I miss something?
Thank you.

**Comment by shawnhar** [comment]
The problem is in your use of CanvasDevice.GetSharedDevice.  Unless you change that setting, CanvasControl will use the shared device, but CanvasAnimatedControl uses a different device of its own (see the UseSharedDevice property to control that).

Remove the call to GetSharedDevice, and instead use the sender object that is passed into your Draw event as the resource creator for your rendertarget, brush, etc. - then this code will work with either type of control.

There is an easier and perhaps more efficient way to do this, though - you can pass a CanvasGeometry directly to CreateLayer to use it as the clip region.  No need to bother drawing the geometry into a temporary rendertarget first.

**Comment by p69** [comment]
Thank you for reply.
Didn't know about `UseShareDevice` property. But I changed my code as you advised (removed GetSharedDevice) and everything works fine. Just curios. Are there any disadvantages to set `UseShareDevice` to true? (In general and if I have many instances of `AnimatedCanvasControl` on UI).

One more question about clipping. Is it faster then opacity mask brush?
Actually it's not the same operation, and I did it in my project previously. I do implementation of SVG rendering based on Win2d using custom SVG engine. But when I have many not connected geometries with different transformation it doesn't work. Can I achieve the same result using clipping?
Thanks a lot.

**Comment by shawnhar** [comment]
Sharing a single device across multiple controls can reduce memory usage and allow more reuse of intermediate resources, but it can also cause more thread contention, and makes thread safety more complicated if you interop to graphics APIs other than Win2D (Win2D APIs are threadsafe, but native D2D or D3D are not entirely).

Note that it is not usually a good idea to have many instances of CanvasAnimatedControl.  Each such control creates a separate swapchain and game loop thread, which are quite heavyweight.  Fine to have 2 or 3 of these but if you are talking 10s or 100s, CanvasControl would be a better choice.

Clipping against a geometry should always be able to produce the same result as drawing that geometry into an opacity mask which is then used as a brush.  I'm not sure which will be faster - I would guess geometry clipping but haven't actually timed this to see.

**Comment by p69** [comment]
Thanks again.
In my case it can be many instances of AnimatedCanvasControl (from 1 to 20). But all of them should be paused (except maximum one at a time). Is it bad idea? I'd like to use CanvasControl, but I need similar update\draw cycle logic. Could you give me any advice how to achieve this?

**Comment by shawnhar** [comment]
20 animated controls will be pushing it.  You might be ok depending on your target device etc. but my instinct would be to go with CanvasControl if you need this many.

You can call Invalidate on a CanvasControl when you want to redraw it.

**Comment by p69** [comment]
Thank you for the help.
