### ISSUE TITLE
How can I draw my long-time waveform in Win2D with a scrollviewer?

### ISSUE THREAD

**Issue by LinJianping** [Microsoft/Win2D#463]
In my UWP application, I need to read a large binary file and convert it into a long-time waveform, and then I need to draw this waveform. As I cann't display this waveform in one window, so I guess I need use a scrollviewer to display. My idea is to load this file and then generate a very large CanvasVirtualBitmap, and diaplay this CanvasVirtualBitmap by CanvasVirtualControl in a ScrollViewer but I didn't know how can I draw this CanvasVirtualBitmap. Does anyone have any idea about this or have a better solution for this problem? thx~

**Comment by shawnhar** [comment]
You don't draw to a CanvasVirtualBitmap.  Virtual bitmaps are for on-demand paging only the necessary pieces of an already-existing bitmap into video memory from the file system.

If you want to on-demand draw only parts of a very large image, look at CanvasVirtualControl.

**Comment by LinJianping** [comment]
Thanks for your reply. I need to have a canvas where I can draw my waveform by myself using drawlines method but not to draw only parts of a very large image.  So I guess I need to draw my waveform according to the position of ScrollViewer vertical bar(I don't want to diaplay a horizontal bar). I'm really a newbie for UWP development, and I have no idea about how can I update the CanvasVirtualControl with ScrollViewer. I have try to place a CanvasVirtualControl in a ScrollViewer, and draw the waveform when RegionsInvalidated event occurs. But the ScrollViewer bar doesn't display so I can't get the position of ScrollViewer vertical bar. Can you give me hints? Thank you very much!!! @shawnhar

**Comment by LinJianping** [comment]
I have found an ugly solution for this problem. Now I calculate the height of CanvasVirtualControl according to the count of points I want to draw when CreateResources event occured. And then I draw the waveform by myself when the RegionsInvaliated event occured. But I don't want to re-draw every time， can I buffer what I have drawn? Or can I just generate a very big image once time in CreateResources event handle and then attach it to the CanvasVirtualControl so that the computation will be only one time? @shawnhar

**Comment by LinJianping** [comment]
Now I would create a CanvasRenderTarget when CreateResources event occured. The height of CanvasRenderTarget is calculated according to the count of points(There is a limitation 16384). And then I draw the corresponding region of CanvasRenderTarget to the CanvasVirtualControl by method DrawImage.
What's your opnion about this solution? Do you have any better solution? Thank you very mush!!! @shawnhar

**Comment by shawnhar** [comment]
No need to make this so complicated.  Handling on-demand drawing of big images is exactly what the virtual control handles for you automatically.  Put a CanvasVirtualControl inside a XAML scroll viewer, draw whatever pieces you are asked to when the regions invalidated event is raised, and you are done.

**Comment by LinJianping** [comment]
Thanks! As the long-time waveform is drew in lines and each line have a fixed height as the following image shown. I have no idea about how can I just draw a piece and achieve a very smooth effect when I drag the scroll bar.
<img width="960" alt="waveform" src="https://cloud.githubusercontent.com/assets/7122373/20887696/bc3f74f6-bb36-11e6-9247-11e6ea235abb.PNG">

Now my solution is  to generate a CanvasRenderTarget firstly , and then draw the corresponding region by the following code:
```
private void FlashRecordDisplayCanvas_RegionsInvalidated(CanvasVirtualControl sender, CanvasRegionsInvalidatedEventArgs args)
 {            
       foreach (var region in args.InvalidatedRegions)
       {
           using (var ds = FlashRecordDisplayCanvas.CreateDrawingSession(region))
           {
                ds.DrawImage(canvasRenderTarget, region, region);
           }
      }
}
```
This solution can achieve a very smooth effect but it's a memory-consumed operation.

**Comment by shawnhar** [comment]
I'm afraid I do not understand your problem here.  There is no need for an intermediate rendertarget here - just draw whatever set of lines are needed to cover the invalidated region directly onto the CanvasVirtualControl.

**Comment by LinJianping** [comment]
Cause my waveform is store in an one-dimensional array to represent the magnitude, so I need to draw a line for every two adjacent dots to display the waveform. Suppose I can draw 5 lines of waveform in the invalidated region, the first and last line may be incomplete because several points may be outside of the invalidated region. I have no idea about how to draw the incomplete first line and last line. The following image is for demonstration. Hope I have clarified my problem, thanks for your concern.
<img width="960" alt="waveform1" src="https://cloud.githubusercontent.com/assets/7122373/20910187/f723cffe-bb9a-11e6-9008-7f3547ef31a9.PNG">

**Comment by LinJianping** [comment]
@shawnhar Sorry for bothering you so much. I have encountered another problem. I have defined  a variable canvasRenderTarget  to represent the CanvasRenderTarget object. And when I load a new waveform, firstly I dispose the old CanvasRenderTarget object and then I new a new CanvasRenderTarget. Code as following:
```
canvasRenderTarget?.Dispose();
canvasRenderTarget = null;                
CanvasDevice device = FlashRecordDisplayCanvas.Device;                
canvasRenderTarget = new CanvasRenderTarget(device, (float)FlashRecordDisplayCanvas.Width, (float)FlashRecordDisplayCanvas.Height, FlashRecordDisplayCanvas.Dpi);
using (var ds = canvasRenderTarget.CreateDrawingSession())
{                    
    var graphDrawer = new GraphDrawer((float)FlashRecordDisplayCanvas.Width, (float)FlashRecordDisplayCanvas.Height, SysToWin2DScaleRatioX, SysToWin2DScaleRatioY, ComGp.SAMPLE_RATE, ComGp.SECOND_PER_MM, ComGp.MV_PER_MM);
    graphDrawer.DrawRecord(ds, ecgData);
    FlashRecordDisplayCanvas.Invalidate();
}
```
But sometime this doesn't work correctly, the CanvasRenderTarget may overlap with the previous waveform as the following image shown. It seems that the Dispose method doesn't release correctly.
<img width="960" alt="overlap" src="https://cloud.githubusercontent.com/assets/7122373/20911841/2c11a6f4-bba6-11e6-954d-817bbc690c5b.PNG">

**Comment by shawnhar** [comment]
Win2D will clip if you draw outside the target region.  Just draw all the lines that intersect the area you are interested in.

For your second bug, it looks like you aren't clearing everything that you previously drew onto the control.

**Comment by LinJianping** [comment]
Hi, I have draw my waveform as you advised. But now I encountered another problem, there are some breaks in the canvas just as shown below. The reason may be that I use drawline to draw lines at every two adjacent points, but sometimes the two points may be in different invalid regions. Do you have any idea about this?@shawnhar
<img width="888" alt="break" src="https://cloud.githubusercontent.com/assets/7122373/21636307/337bdcee-d29d-11e6-8792-788e110ccd29.PNG">

**Comment by shawnhar** [comment]
If a line intersects more than one region, you'll need to draw that line more than once.  Each time you draw a region, you must draw all shapes that intersect with it.

**Comment by LinJianping** [comment]
Hi, now I placed a CanvasVirtualControl in ScrollViewer to display my long-time waveform, and the width of CanvasVirtualControl is calculated according to the length of waveform data. But now I encontered another problem: when the waveform is very long, the width of CanvasVirtualControl may be very large which would cause my app crashed. Can I just place a CanvasControl in ScrollViewer, and manually set the scrollable width of ScrollViewer rather than set the width of CanvasControl, and draw relative waveform according to the offset of ScrollViewer?

**Comment by shawnhar** [comment]
You can't use CanvasControl inside a ScrollViewer that way, because the ScrollViewer will automatically scroll its contents.  I guess you could not use ScrollViewer at all and just do all your own manipulation logic on top of a regular CanvasControl, but that's not the path I would recommend.

I would start by understanding why did your app crash?  CanvasVirtualControl does have a max size, but that is /very/ large.  How big are you trying to set it?

**Comment by LinJianping** [comment]
App crashed when the size is (1260,4.337942E+07).
@shawnhar

**Comment by LinJianping** [comment]
I have make a test, the app will crash exactly when set either width or height of CanvasVirtualControl  a   value larger than 11184811 in my machine.
@shawnhar

**Comment by shawnhar** [comment]
You are running up against an internal DComp size limit here.  Although virtual controls can be very large, they can't go bigger than around 2^24 pixels along either axis.

You will need to either change your design to not need such very large surfaces, or implement your own scrolling and virtualization / tile management system not using ScrollViewer etc.  Note that rendering graphics from a virtualized region bigger than 2^24 will also start to run into floating point precision artifacts, which you will need great care and special techniques to avoid.
