### ISSUE TITLE
CanvasFontSet throws exception when using URI from ms-appdata://

### ISSUE THREAD

**Issue by OvestLabs** [Microsoft/Win2D#464]
I'm trying to load a font from my UWP application local storage like this:

`var uri = new Uri("ms-appdata:///myfont.ttf");`
`var fontSet = new CanvasFontSet(uri);`

but it throws an `ArgumentException` with message _"Value does not fall within the expected range."_

Using a font from the apps installation directory `ms-appx:///myfont.ttf` works fine, but not the `ms-appdata://`. This format also silently fails when using it as the string value of the `CanvasTextFormat.FontFamily`.

Am I missing something?

**Comment by shawnhar** [comment]
"ms-appdata:///myfont.ttf" is not a valid path.   I suspect you want "ms-appdata:///local/myfont.ttf".

See https://msdn.microsoft.com/en-us/windows.storage.applicationdata.localfolder and https://blogs.windows.com/buildingapps/2014/06/19/common-questions-and-answers-about-files-and-app-data-part-1-app-data/#MRL6z68Zlbc9AKss.97

**Comment by OvestLabs** [comment]
Thanks Shawn,

This fixes the `CanvasFontSet`, thanks! However, it still doesn't draw using that font. If I use the path like this

`CanvasTextFormat.FontFamily = "ms-appdata:///local/myfont.ttf"`
or
`CanvasTextFormat.FontFamily = "ms-appdata:///local/myfont.ttf#Regular"`

it always falls back to Segoe. The `CanvasFontSet` finds it ok, but can't use it in a format. Any tips?

**Comment by shawnhar** [comment]
Is "Regular" the correct family name for the font you are trying to use?

**Comment by OvestLabs** [comment]
Yes, at least that's what `CanvasFontSet` tells me. To replicate:

1. Go to Control Panel > Fonts
2. Find Wingdings (something obvious ;)
3. Select, copy, and paste into the LocalState directory of your app
4. Try to use it. 

Shouldn't the FontFamily be "ms-appdata:///local/wingding.ttf#Regular" ?

**Comment by shawnhar** [comment]
The font family name for Wingdings is "Wingdings", not "Regular".

**Comment by OvestLabs** [comment]
How did you find that out? In this specific example, we have access to the font file, but if the font is loaded from an unknown source, how can I determine the full FontFamily string programmatically?

**Comment by shawnhar** [comment]
CanvasFontSet.Fonts, then look at the FamilyNames property.

**Comment by OvestLabs** [comment]
Ok that works. Thanks Shawn!
