### ISSUE TITLE
Bug in EffectExample.xaml.cs

### ISSUE THREAD

**Issue by oduis** [Microsoft/Win2D#466]
Hello,
Thanks for this great library! Writing an app leveraging some samples, I think I found a bug:
In EffectExample.xaml.cs in Canvas_Draw(), the last line is sender.Invalidate();
It seems like this will re-trigger Canvas_Draw. The examples works anyway, just the CPU is higher since Canvas_Draw gets called in an endless loop.
Regards
Oliver

**Comment by shawnhar** [comment]
The Invalidate call is necessary to animate the effect examples.  Without it you would get just a single static image that never moves.

**Comment by oduis** [comment]
Thanks for clarification. I observed the problem in the color management part, where the Invalidate() is not helpful, but did not check the other samples like animation.
Sorry for bothering.
