### ISSUE TITLE
How to load resources for CanvasControl on demand

### ISSUE THREAD

**Issue by maliroteh** [Microsoft/Win2D#468]
In my UWP app I'm designing a control that exposes a few properties such as foreground and background images. At runtime the user can pick values from two lists and these values are assigned to these properties.

At that point I'd like my control (which uses a CanvasControl to draw content) to be able to create resources based on the updated property values. But I'm not sure what is the right approach here.

Here is a partial pseudo-code for what I have right now:

```
bool _imagePropertyUpdated = false;
CanvasBitmap _myCanvasBitmap;
CanvasControl _myCanvasControl;
Stream _defaultImageStream = stream for a default image to be used

public Stream ImageStream
{
    get { ....... }
    set
    {
        ........
        _imagePropertyUpdated = true;
        _myCanvasControl.Invalidate();
    }
}

private void CanvasControl_CreateResources(CanvasControl sender, CanvasCreateResourcesEventArgs args)
{
    args.TrackAsyncAction(OnCreateResourcesAsync(sender).AsAsyncAction());
}

private async Task OnCreateResourcesAsync(CanvasControl sender)
{
    if (ImageStream != null)
        _myCanvasBitmap = await CanvasBitmap.LoadAsync(sender, ImageStream.AsRandomAccessStream());
    else
        _myCanvasBitmap = await CanvasBitmap.LoadAsync(sender, _defaultImageStream.AsRandomAccessStream());
    ........
}

private async void CanvasControl_Draw(CanvasControl sender, CanvasDrawEventArgs args)
{
    if (_imagePropertyUpdated)
    {
        await OnCreateResourcesAsync(sender);
        _imagePropertyUpdated = false;
    }
    ........
    args.DrawingSession.DrawImage(_myCanvasBitmap);
}
```

But the call to DrawImage throws the following exception:

The object has been closed. (Exception from HRESULT: 0x80000013)

**Comment by shawnhar** [comment]
Hi,

You may find this article useful:  https://microsoft.github.io/Win2D/html/LoadingResourcesOutsideCreateResources.htm

**Comment by maliroteh** [comment]
Thanks that did the trick.
