### ISSUE TITLE
How to draw a segment of a CanvasGeometry?

### ISSUE THREAD

**Issue by JEsword** [Microsoft/Win2D#469]
I need to implement a "drawing animation" for a complex geometry in UWP, which means the geometry can show up as someone is "drawing" it.
It's easy to realize in iOS (with "strokeStart" and "strokeEnd" properties of CAShapeLayer) and Android (PathMeasurer.getSegment).
But in Win2D, I can't find a way to do it with CanvasGeometry. Considering it's a common requirement, have I missed something?

**Comment by shawnhar** [comment]
Hi,

Win2D doesn't have an API for doing this in a single step, but there are a couple of approaches that I believe should work.

One would be to use the CanvasGeometry ComputePathLength and ComputePointOnPath methods to look up the current 'pen' position as the geometry is being drawn (like the Example Gallery Geometry Operations demo does when you turn on Contour Tracing Animation) - but extend this to draw a line segment connecting the current and previous pen positions.

Another approach would be to call Simplify(CanvasGeometrySimplification.Lines) followed by CanvasGeometry.SendPathTo, which will give you the geometry data as a series of straight line segments that can be added to the scene one-by-one.

**Comment by JEsword** [comment]
@shawnhar 
Really appreciate for your solutions! I think the 2nd one is more efficient to implement.
I've also just figured out another more tricky solution with CanvasGeometry.CustomDashStyle. Because what I want is only drawing the stroke of that geometry, so I can use a float[4] to represent the stroke range which need to be drawn. Maybe this one is the most efficient way?

**Comment by shawnhar** [comment]
Oh, that's a cool idea!  Yes, I think using a custom stroke style for this would work well.
