### ISSUE TITLE
WinRT information: Cannot create instance of type 'Microsoft.Graphics.Canvas.CanvasControl'

### ISSUE THREAD

**Issue by spareilleux** [Microsoft/Win2D#47]
I've tried to follow the instructions from http://microsoft.github.io/Win2D/html/Introduction.htm, but I'm getting the following error:

An exception of type 'Windows.UI.Xaml.Markup.XamlParseException' occurred in Win2d.Windows.exe but was not handled in user code

WinRT information: Cannot create instance of type 'Microsoft.Graphics.Canvas.CanvasControl' [Line: 12 Position: 31]

Additional information: The text associated with this error code could not be found.

**Comment by spareilleux** [comment]
I finally got it working.

**Comment by shawnhar** [comment]
Glad to hear you got this working.  Could you share what the issue was, so we can update the docs to help other people avoid this problem in future?   Thanks!

**Comment by spareilleux** [comment]
Initially, I had changed the Platform target to "x86" in the application .csproj, everything was compiling OK but failing at runtime.
Then, I changed the platform target for the same project from Configuration Properties | Properties page (I probably had to apply "Clean Solution" as well before re-compiling), it fixed the issue.

PS: Shawn, thanks to you and your team for the awesome work!

**Comment by janvarga94** [comment]
I Fixed it by changing x86 to x64..
