### ISSUE TITLE
CanvasStrokeStyle.CustomDashStyle is not rendered as described

### ISSUE THREAD

**Issue by JEsword** [Microsoft/Win2D#470]
As this [doc](https://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_Geometry_CanvasStrokeStyle_CustomDashStyle.htm) describes, CanvasStrokeStyle.CustomDashStyle is something very similar to [Windows.UI.Xaml.Shape.StrokeDashArray](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.shapes.shape.strokedasharray):

> A custom dash style is an array whose elements specify the length of each dash and space in the pattern. The first element sets the length of a dash, the second element sets the length of a space, the third element sets the length of a dash, and so on. The length of each dash and space in the dash pattern is the product of the element value in the array and the stroke width.

As above described, the dash and space element value seem use the same unit. But just try to run below test code to verify it, and the render result is very confusing:

**XAML**
```
<Page
    x:Class="UWPTest1.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UWPTest1"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid x:Name="root"  Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        
    </Grid>
</Page>
```

**C#**

```
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.Graphics.Canvas.UI.Xaml;
using Windows.UI;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Shapes;

namespace UWPTest1 {
    public sealed partial class MainPage : Page {
        public MainPage() {
            this.InitializeComponent();

            // Line1 with Windows.UI.Xaml.Shapes.Line
            root.Children.Add(new Line {
                X1 = 100,
                Y1 = 50,
                X2 = 300,
                Y2 = 50,
                StrokeThickness = 10,
                Stroke = new SolidColorBrush(Colors.Black),
                StrokeDashArray = new DoubleCollection() { 5, 5 }
            });

            // Line2 with Win2D
            var canvas = new CanvasControl();
            canvas.Draw += (sender, args) => {
                CanvasStrokeStyle style = new CanvasStrokeStyle();
                style.CustomDashStyle = new float[] { 5f, 5f };
                args.DrawingSession.DrawLine(100, 100, 300, 100, Colors.Black, 10, style);
            };
            root.Children.Add(canvas);
        }
    }
}
```

Line2 has a different render result from Line1.
But the critical issue is that the rendered dash and space width in Line2 are different, althought they are both declared as "5f" in CustomeDashStyle. 
So is there something I misunderstand or it's just a bug?

**Comment by shawnhar** [comment]
Win2D and XAML rendering aren't expected to be the same.  The two APIs have similar concepts in some places, but are fundamentally different rendering technologies and were not designed to always produce identical outputs.

The wider-than-expected dashes you are seeing is because you don't set the CanvasStrokeStyle.DashCap property, which means you get its default value of Square.  In order for dashes and the gaps between them to be the same size, you want this set to Flat.

The Stroke Styles demo in Example Gallery may be useful for exploring the behavior of the different cap options.

**Comment by JEsword** [comment]
@shawnhar 
Oh really sorry for not reading the doc carefully enough! I just thought the default value of CanvasStrokeStyle.DashCap is Flat. 
Do you think using Flat as the default value which consists with [XAML](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.shapes.shape.strokedashcap.aspx) will be more intuitive?

**Comment by shawnhar** [comment]
Flat is not a good default because when using flat caps, dots become zero size so disappear entirely (only the dashes are visible).  This would be very confusing for people who use dots as well as dashes.

**Comment by shawnhar** [comment]
Closing issue as this has been answered.
