### ISSUE TITLE
Question regarding CanvasFilledRegionDetermination

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/Win2D#471]
Is the **CanvasFilledRegionDetermination** enum similar to the [**System.Windows.Media.FillRule**](https://msdn.microsoft.com/en-us/library/system.windows.media.fillrule(v=vs.110).aspx) enumeration?

If yes, then the **CanvasFilledRegionDetermination.Alternate** maps to which of the FillRule value - **EvenOdd** or **NonZero**?

While creating a CanvasGeometry using PathBuilder, if the CanvasFilledRegionDetermination is not set explicitly (by calling the **PathBuilder.SetFilledRegionDetermination** method), then which is the default value set for the FilledRegionDetermination.

**Comment by shawnhar** [comment]
Yes, these are the same thing.  Looks like the docs even copied some of the same wording!

https://msdn.microsoft.com/en-us/library/windows/desktop/dd368110%28v=vs.85%29.aspx

https://msdn.microsoft.com/en-us/library/system.windows.media.fillrule(v=vs.110).aspx

**Comment by ratishphilip** [comment]
Thanks. So the default is **CanvasFilledRegionDetermination.Alternate**, right?

**Comment by shawnhar** [comment]
I believe so.

**Comment by ratishphilip** [comment]
Thanks.
