### ISSUE TITLE
Testing for Type Availability using ApiInformation?

### ISSUE THREAD

**Issue by mscherotter** [Microsoft/Win2D#473]
Can I use the ApiInformation class to test for the availability of classes that are only available in later versions of Windows 10, like the OpacityEffect class?  
http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Effects_OpacityEffect.htm

**Comment by shawnhar** [comment]
Use the IsSupported property to check whether OpacityEffect is available on the current OS:  http://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_Effects_OpacityEffect_IsSupported.htm

**Comment by CMay** [comment]
Is there an active list anywhere that shows what parts of Win2D rely on certain versions of Windows?  It would almost be nice to see a timeline that shows Windows versions that were particularly important for Win2D in some way.  Like, I know there are a couple Direct2D/OS bugs that were manifesting for Win2D users, then there was a regression, etc.  To have a quick reference for that to just see the status of Win2D for different Windows versions would be cool.

**Comment by shawnhar** [comment]
Hi,

We don't have a single list mapping OS updates to Win2D features, but the docs for every Win2D API are tagged if it has specific OS requirements.

There are some significant deltas between 8.1 and UWP feature set, which are hard to get wrong as the unsupported APIs simply aren't there when building for 8.1 (that's a different project type using a different Win2D NuGet package).

Across the different versions of Win10, there are only a few Win2D features that require a particular update.  [This release](https://blogs.msdn.microsoft.com/win2d/2015/12/07/win2d-1-10-0-sprite-batches-windows-ui-composition-canvasvirtualbitmap-more-text-features-and-effect-rectangle-mapping/
) added sprite batch and composition integration, and [this one](https://blogs.msdn.microsoft.com/win2d/2016/08/09/win2d-1-19-0-windows-10-anniversary-edition-support-new-image-effects-doc-improvements-and-bugfixes/) added 4 new helper image effects.

**Comment by shawnhar** [comment]
Closing issue as this has been answered.
