### ISSUE TITLE
ExampleGallery.uap unhandled exception

### ISSUE THREAD

**Issue by gettf** [Microsoft/Win2D#478]
ExampleGallery.uap.exe”exit, return code -1073741819 (0xc0000005) 'Access violation'
vs cant break load and another debugger.

**Comment by shawnhar** [comment]
Please give more information.  What exactly are you doing to trigger this problem?  What version of Win2D, operating system, and device?  How do you run Example Gallery?  etc.

**Comment by gettf** [comment]
get newest win2d version, in vs debug mode run app then exception, os: win10 14986. vs2015 and vs2017 rc

**Comment by gettf** [comment]
Found solution: in Debug Option, disable UI Debugging tools for XAML. Default setting trigger exception  in windows.ui.xaml.dll

**Comment by shawnhar** [comment]
Odd - VS works fine for me with or without the XAML debugging stuff enabled.

Anyway, I'm going to close this issue as there doesn't seem to be any Win2D bug here.
