### ISSUE TITLE
Possible to render to a brush?

### ISSUE THREAD

**Issue by factormystic** [Microsoft/Win2D#48]
It would be interesting to set up an animation, and be able to use it as a control background. Is this possible? Could it be possible in the future?

**Comment by shawnhar** [comment]
Do you mean a XAML brush, or a Win2D brush?

Both are possible, but done in quite different ways.

**Comment by factormystic** [comment]
XAML brush I guess, unless Win2D brush could accomplish the same thing. But I'm thinking about how to integrate Win2D into an existing XAML app.

**Comment by shawnhar** [comment]
The most common approach for integrating Win2D into XAML is to add one or more CanvasControls to your page.  For instance to draw other XAML content with Win2D rendering as a background, I would normally just put those other XAML controls in a grid panel over the top of a CanvasControl.   You don't need a brush for that.

If you do need to get Win2D content into a XAML brush, use the CanvasImageSource class.  You can draw to that with Win2D, then use it anywhere XAML accepts an ImageSource (for instance with an ImageBrush).
