### ISSUE TITLE
Using CanvasAnimatedControl in custom control

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/Win2D#480]
I am trying to create a custom control which has a **CanvasAnimatedControl** in its background.

In #476 you mentioned the following

>CanvasAnimatedControl is not a great choice if you have many of them active at the same time.

Now in my app there will be many instances of the custom control (say 5-10). 

Will there be performance issues having so many instances of the custom control (i.e. **CanvasAnimatedControl**) active at the same time?

**Comment by shawnhar** [comment]
You will probably be better off with CanvasControl than CanvasAnimatedControl for something like that.

Generally, if you have more than one of something, animated control is probably not the best place to start.

**Comment by ratishphilip** [comment]
Thanks for your reply.

However, in my case, the custom control animates the content based on user interaction and mobile sensor input. What would you suggest in this scenario?

**Comment by shawnhar** [comment]
I would start with CanvasControl.

**Comment by ratishphilip** [comment]
Thank you.
