### ISSUE TITLE
Touch keyboard input

### ISSUE THREAD

**Issue by murrayLuke** [Microsoft/Win2D#481]
Is there a way to bring the touch keyboard up so that the user can input text on a win2d application without accessing a xaml textbox? The workaround we are currently trying to implement is a full touch keyboard written in win2d, but this is obviously not ideal for many reasons...

**Comment by shawnhar** [comment]
Take a look at the InputPane API, which is used by the Win2D Keyboard Input Example.

**Comment by murrayLuke** [comment]
thanks so much. I should take a better look at those examples next time.

**Comment by tdgreen** [comment]
I tried the keyboard input example on multiple machines  (after unplugging keyboards and mice) and I still couldn't get the touch-keyboard to appear.  When debugging, the InputPane.TryShow() is called and event handlers added correctly.  The keyboard still doesn't appear and the eventHandler doesn't get called.  When I manually opened the touch keyboard from the taskbar, the eventHandler was correctly fired.  Any ideas?

**Comment by damyanp** [comment]
I'm afraid I don't know the definitive answer.  I'm asking around to see if I can find out more, but my initial search suggests that there may not be a way for apps to expose the touch keyboard programmatically on devices that are in desktop (as opposed to tablet) mode.
