### ISSUE TITLE
unauthorized access exception in drawingsession.DrawTextLayout

### ISSUE THREAD

**Issue by murrayLuke** [Microsoft/Win2D#482]
We have a canvas text layout that we are using to draw richly formatted text that has been converted from markdown. Because the text changes often, we sometimes need to recreate the canvas text layout in our update call. Occasionally we get unauthorized access exception in the call to DrawTextLayout. Here are 5 separate examples of the call stacks that I see when the exception is raised.

(1) Memory Access Violation Exception 	

	msvcrt.dll!_memcpy()	Unknown
 	d2d1.dll!BatchedGlyphRun::BatchedGlyphRun(class CReferenceHolder *,struct DWRITE_GLYPH_RUN const *,unsigned short *,float *,struct DWRITE_GLYPH_OFFSET *,bool,struct DWRITE_GLYPH_RUN_DESCRIPTION const *)	Unknown
 	d2d1.dll!BatchedGlyphRun::CreateInBatchMemory(class CReferenceHolder *,unsigned char *,unsigned int,struct DWRITE_GLYPH_RUN const *,struct DWRITE_GLYPH_RUN_DESCRIPTION const *,bool,unsigned int,class BatchedGlyphRun * *)	Unknown
 	d2d1.dll!DrawingContext::DrawGlyphRun(struct D2D_POINT_2F,struct DWRITE_GLYPH_RUN const *,struct DWRITE_GLYPH_RUN_DESCRIPTION const *,struct ID2D1Brush *,enum DWRITE_MEASURING_MODE)	Unknown
 	d2d1.dll!TextRenderer::DrawGlyphRun(void *,float,float,enum DWRITE_GLYPH_ORIENTATION_ANGLE,enum DWRITE_MEASURING_MODE,struct DWRITE_GLYPH_RUN const *,struct DWRITE_GLYPH_RUN_DESCRIPTION const *,struct IUnknown *)	Unknown
 	DWrite.dll!TextLayout::DrawGlyphRuns()	Unknown
 	DWrite.dll!TextLayout::Draw()	Unknown
 	DWrite.dll!DWriteTextLayout::Draw()	Unknown
 	d2d1.dll!DrawingContext::DrawTextLayoutCommon(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,struct ID2D1SvgGlyphStyle *,unsigned int,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	d2d1.dll!DrawingContext::DrawTextLayout(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,struct ID2D1SvgGlyphStyle *,unsigned int,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	d2d1.dll!D2DDeviceContextBase<struct ID2D1DeviceContext4,struct ID2D1DeviceContext4,class null_type>::DrawTextLayout(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	Microsoft.Graphics.Canvas.dll!ABI::Microsoft::Graphics::Canvas::CanvasDrawingSession::DrawTextLayoutAtCoordsWithColor(struct ABI::Microsoft::Graphics::Canvas::Text::ICanvasTextLayout *,float,float,struct ABI::Windows::UI::Color)	Unknown
 	Microsoft.Graphics.Canvas.dll!ExceptionBoundary<class <lambda_54ccf02bb3ac838233c025124668ed65> >(class <lambda_54ccf02bb3ac838233c025124668ed65> &&)	Unknown
 	Microsoft.Graphics.Canvas.dll!ABI::Microsoft::Graphics::Canvas::CanvasDrawingSession::DrawTextLayoutAtCoordsWithColor(struct ABI::Microsoft::Graphics::Canvas::Text::ICanvasTextLayout *,float,float,struct ABI::Windows::UI::Color)	Unknown

(2) Memory Access Violation Exception

 	DWrite.dll!TextLayout::DrawGlyphRuns()	Unknown
 	DWrite.dll!TextLayout::Draw()	Unknown
 	DWrite.dll!DWriteTextLayout::Draw()	Unknown
 	d2d1.dll!DrawingContext::DrawTextLayoutCommon(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,struct ID2D1SvgGlyphStyle *,unsigned int,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	d2d1.dll!DrawingContext::DrawTextLayout(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,struct ID2D1SvgGlyphStyle *,unsigned int,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	d2d1.dll!D2DDeviceContextBase<struct ID2D1DeviceContext4,struct ID2D1DeviceContext4,class null_type>::DrawTextLayout(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	Microsoft.Graphics.Canvas.dll!ABI::Microsoft::Graphics::Canvas::CanvasDrawingSession::DrawTextLayoutAtCoordsWithColor(struct ABI::Microsoft::Graphics::Canvas::Text::ICanvasTextLayout *,float,float,struct ABI::Windows::UI::Color)	Unknown
 	Microsoft.Graphics.Canvas.dll!ExceptionBoundary<class <lambda_54ccf02bb3ac838233c025124668ed65> >(class <lambda_54ccf02bb3ac838233c025124668ed65> &&)	Unknown
 	Microsoft.Graphics.Canvas.dll!ABI::Microsoft::Graphics::Canvas::CanvasDrawingSession::DrawTextLayoutAtCoordsWithColor(struct ABI::Microsoft::Graphics::Canvas::Text::ICanvasTextLayout *,float,float,struct ABI::Windows::UI::Color)	Unknown

Could it be that the drawbounds in the CanvasTextLayout are DrawBounds = {-0.2539063,34.05664,728.5107,NaN}

(3) Exception thrown at 0x66FD43FD (DWrite.dll) in NuSysApp.exe: 0xC0000005: Access violation reading location 0x18934000.

 	DWrite.dll!TextLayout::DrawUnderlines()	Unknown
 	DWrite.dll!TextLayout::Draw()	Unknown
 	DWrite.dll!DWriteTextLayout::Draw()	Unknown
 	d2d1.dll!DrawingContext::DrawTextLayoutCommon(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,struct ID2D1SvgGlyphStyle *,unsigned int,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	d2d1.dll!DrawingContext::DrawTextLayout(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,struct ID2D1SvgGlyphStyle *,unsigned int,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	d2d1.dll!D2DDeviceContextBase<struct ID2D1DeviceContext4,struct ID2D1DeviceContext4,class null_type>::DrawTextLayout(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	Microsoft.Graphics.Canvas.dll!ABI::Microsoft::Graphics::Canvas::CanvasDrawingSession::DrawTextLayoutAtCoordsWithColor(struct ABI::Microsoft::Graphics::Canvas::Text::ICanvasTextLayout *,float,float,struct ABI::Windows::UI::Color)	Unknown
 	Microsoft.Graphics.Canvas.dll!ExceptionBoundary<class <lambda_54ccf02bb3ac838233c025124668ed65> >(class <lambda_54ccf02bb3ac838233c025124668ed65> &&)	Unknown
 	Microsoft.Graphics.Canvas.dll!ABI::Microsoft::Graphics::Canvas::CanvasDrawingSession::DrawTextLayoutAtCoordsWithColor(struct ABI::Microsoft::Graphics::Canvas::Text::ICanvasTextLayout *,float,float,struct ABI::Windows::UI::Color)	Unknown

(4) Exception thrown at 0x66FD46C0 (DWrite.dll) in NuSysApp.exe: 0xC0000005: Access violation reading location 0x1B3C6938.

 	DWrite.dll!TextLayout::DrawGlyphRuns()	Unknown
 	DWrite.dll!TextLayout::Draw()	Unknown
 	DWrite.dll!DWriteTextLayout::Draw()	Unknown
 	d2d1.dll!DrawingContext::DrawTextLayoutCommon(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,struct ID2D1SvgGlyphStyle *,unsigned int,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	d2d1.dll!DrawingContext::DrawTextLayout(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,struct ID2D1SvgGlyphStyle *,unsigned int,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	d2d1.dll!D2DDeviceContextBase<struct ID2D1DeviceContext4,struct ID2D1DeviceContext4,class null_type>::DrawTextLayout(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	Microsoft.Graphics.Canvas.dll!ABI::Microsoft::Graphics::Canvas::CanvasDrawingSession::DrawTextLayoutAtCoordsWithColor(struct ABI::Microsoft::Graphics::Canvas::Text::ICanvasTextLayout *,float,float,struct ABI::Windows::UI::Color)	Unknown
 	Microsoft.Graphics.Canvas.dll!ExceptionBoundary<class <lambda_54ccf02bb3ac838233c025124668ed65> >(class <lambda_54ccf02bb3ac838233c025124668ed65> &&)	Unknown
 	Microsoft.Graphics.Canvas.dll!ABI::Microsoft::Graphics::Canvas::CanvasDrawingSession::DrawTextLayoutAtCoordsWithColor(struct ABI::Microsoft::Graphics::Canvas::Text::ICanvasTextLayout *,float,float,struct ABI::Windows::UI::Color)	Unknown

(5) Exception thrown at 0x66FD46A3 (DWrite.dll) in NuSysApp.exe: 0xC0000005: Access violation reading location 0x00003B20.

 	DWrite.dll!TextLayout::DrawGlyphRuns()	Unknown
 	DWrite.dll!TextLayout::Draw()	Unknown
 	DWrite.dll!DWriteTextLayout::Draw()	Unknown
 	d2d1.dll!DrawingContext::DrawTextLayoutCommon(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,struct ID2D1SvgGlyphStyle *,unsigned int,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	d2d1.dll!DrawingContext::DrawTextLayout(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,struct ID2D1SvgGlyphStyle *,unsigned int,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	d2d1.dll!D2DDeviceContextBase<struct ID2D1DeviceContext4,struct ID2D1DeviceContext4,class null_type>::DrawTextLayout(struct D2D_POINT_2F,struct IDWriteTextLayout *,struct ID2D1Brush *,enum D2D1_DRAW_TEXT_OPTIONS)	Unknown
 	Microsoft.Graphics.Canvas.dll!ABI::Microsoft::Graphics::Canvas::CanvasDrawingSession::DrawTextLayoutAtCoordsWithColor(struct ABI::Microsoft::Graphics::Canvas::Text::ICanvasTextLayout *,float,float,struct ABI::Windows::UI::Color)	Unknown
 	Microsoft.Graphics.Canvas.dll!ExceptionBoundary<class <lambda_54ccf02bb3ac838233c025124668ed65> >(class <lambda_54ccf02bb3ac838233c025124668ed65> &&)	Unknown
 	Microsoft.Graphics.Canvas.dll!ABI::Microsoft::Graphics::Canvas::CanvasDrawingSession::DrawTextLayoutAtCoordsWithColor(struct ABI::Microsoft::Graphics::Canvas::Text::ICanvasTextLayout *,float,float,struct ABI::Windows::UI::Color)	Unknown

**Comment by murrayLuke** [comment]
Could it be that we are recreating a canvas text layout in the update call? Another thing we are doing which may be contributing to this issue, is setting the height of the CanvasTextLayout to float.MaxValue. We want the text to wrap within a certain with, but do not mind it extending to an arbitrary height as needed. Using float.MaxValue seemed to allow this behavior to occur, but it may not be the best way to go about it.

**Comment by shawnhar** [comment]
Hi,

Are you able to provide a repro that shows this crash?  Ideally simplified as far as possible from your full app.

**Comment by murrayLuke** [comment]
thank you for your prompt responses. The issue has been resolved. We found that someone had made an extraneous call to the Update function.
