### ISSUE TITLE
How do I render DrawInk repositioned at (0,0)?

### ISSUE THREAD

**Issue by Tam66662** [Microsoft/Win2D#484]
I have some InkStrokes that I would like to render, but I want to only capture the BoundingRect of the  InkStrokes as a clipped bitmap.  The problem I'm having is that the only way I know how to render the strokes at the moment is to give the width+height of my canvas when I create the CanvasRenderTarget, then perform DrawInk to capture the strokes relative to the full canvas as a bitmap.  But I don't want the absolute (x,y) position to play a role in the final bitmap, I just want the bounding rectangle of the InkStrokes to be my bitmap (i.e. I want the bitmap to be clipped).  How can I do this?

```
private async Task DrawInkStrokes(List<InkStroke> strokes)
{
	var rect = Rect.Empty;
	foreach (var stroke in strokes)
	{
		rect.Union(stroke.BoundingRect);
	}

	using (var device = CanvasDevice.GetSharedDevice())
	{
		using (var renderTarget = new CanvasRenderTarget(device, (float)rect.Width, (float)rect.Height, 96f))
		{
			using (var ds = renderTarget.CreateDrawingSession())
			{
				ds.Clear(Colors.White);

				// NOT WORKING.  How do I reposition the 'ds' to draw the ink strokes at (0,0) instead of at the (x,y) of the 'rect' variable?
				ds.DrawInk(strokes);
			}

			using (var stream = new InMemoryRandomAccessStream())
			{
				await renderTarget.SaveAsync(stream, CanvasBitmapFileFormat.Png);

				// Code here has been redacted that post processes the stream
			}
		}
	}
}

```

**Comment by shawnhar** [comment]
Before you call DrawInk:

    ds.Transform = Matrix3x2.CreateTranslation(...);

**Comment by Tam66662** [comment]
Ahh, that's it!  Thanks!
