### ISSUE TITLE
CanvasPathBuilder.AddArc() method : radiusX and radiusY parameters

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/Win2D#485]
I am trying to create a shape like this
![cpb_arc](https://cloud.githubusercontent.com/assets/7021835/22274334/b9830430-e25a-11e6-9fed-4619df0e3277.png)

I use the following **CanvasPathBuilder** commands

```C#
pathBuilder.BeginFigure(new Vector2(100, 100));
pathBuilder.AddArc(new Vector2(160, 280), 60, 180, (float)Math.PI / 2f, CanvasSweepDirection.Clockwise, CanvasArcSize.Small);
pathBuilder.AddLine(new Vector2(100, 280));
```

This however gives me the following shape
![cpb_arc2](https://cloud.githubusercontent.com/assets/7021835/22274383/1496e94a-e25b-11e6-8322-fbc1de5ce981.png)

If I interchange the **radiusX** and **radiusY** values in the **CanvasPathBuilder.AddArc()** method, then I get the desired shape.

```C#
pathBuilder.AddArc(new Vector2(160, 280), 180, 60, Float.PiByTwo, CanvasSweepDirection.Clockwise, CanvasArcSize.Small);
```

Isn't **radiusX** parameter supposed to be the width of the arc on the X-axis and **radiusY** parameter the height of the arc on the Y-axis?

**Comment by shawnhar** [comment]
AddArc has a couple of overloads which are quite different in how they specify the shape.  The one you are here using (https://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Geometry_CanvasPathBuilder_AddArc.htm) is sometimes useful but also can be very confusing to understand how the parameters affect the final shape.  The alternative version (https://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Geometry_CanvasPathBuilder_AddArc_1.htm) is in my opinion much more straightforward and should be ideal for what you are wanting here.

Take a look at the Arc demo in Example Gallery - we added that mostly to help people figure out how the parameters to the first overload behave!

**Comment by ratishphilip** [comment]
Yes. The second one is simpler than the first one. 
However, could you point to any documentation which describes the first method in more detail? I wish to know how the radiusX and radiusY parameters affect the shape and the calculation behind it.

**Comment by shawnhar** [comment]
The Win2D docs (https://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Geometry_CanvasPathBuilder_AddArc.htm) have slightly more detail than the corresponding Direct2D docs (https://msdn.microsoft.com/en-us/library/windows/desktop/dd368065(v=vs.85).aspx) but the interactive Example Gallery is the best way I know to understand how these parameters behave.

**Comment by ratishphilip** [comment]
Thank you.
