### ISSUE TITLE
ComputeHistogram does not seem to take into account the SourceRectangle.

### ISSUE THREAD

**Issue by rolandsmeenk** [Microsoft/Win2D#487]
I ran into an issue where I wanted to calculate a histogram of only a part of a CanvasImage, but it looks like the SourceRectangle is not taken into account. If I set it to something different than the rectangle returned by GetBounds the results look always the same. Is this expected behaviour?

I the meantime I will render the parts of interest to a separate rendertarget so their histograms can be calculated separately.

**Comment by shawnhar** [comment]
The source rectangle parameter to ComputeHistogram works as expected in my tests.

Please provide a repro app that shows the problem you are seeing.

**Comment by rolandsmeenk** [comment]
Ok, here's a little UWP app. Use the slider to scale the SourceRectangle and notice that the drawn histograms do not change.
[HistogramTest.zip](https://github.com/Microsoft/Win2D/files/740642/HistogramTest.zip)

**Comment by shawnhar** [comment]
Thanks for the repro - we'll take a look.

**Comment by shawnhar** [comment]
Confirmed this is a bug in Win2D.

As a workaround until we are able to get this fixed, you can feed your image through a CropEffect to specify what region you want, then pass that CropEffect into ComputeHistogram.

**Comment by rolandsmeenk** [comment]
Ok, thanks for the confirmation.

**Comment by shawnhar** [comment]
This is fixed in Win2D 1.21.0 (released today)
