### ISSUE TITLE
CanvasControl pass through events

### ISSUE THREAD

**Issue by shannah** [Microsoft/Win2D#488]
I have a CanvasControl with sections of it transparent so that I can see the view that is behind it (I have a WebView behind it).

I'm trying to be able to pass pointer events through to the WebView in parts where the WebView is visible through the CanvasControl, but so far I have not had success.

Some observations.

If I set `myCanvasControl.Opacity = 0`, then events are correctly passed to the webview behind it.  However, if I have opacity > 0, I can't seem to do anything to get the events to pass through.  I have tried:

`myCanvas.IsHitTestVisible=false`

`myCanvas.Background.Opacity=0`

`myCanvas.Enabled=false`

And none of these seem to have any effect WRT passing events through to the webview behind it.  (They do work, for disabling the CanvasControl though).

Is there any way to pass events through a CanvasControl?

I'm using UWP.

**Comment by shawnhar** [comment]
Afraid this is beyond the limits of how much I know about XAML (event routing is not my area, and this behavior is not specific to Win2D).

Looking at answers to similar questions about WPF in the past (eg. http://stackoverflow.com/questions/7554967/how-can-i-make-my-scrollviewer-pass-click-events-through-to-the-control-behind-i) it seems like this may not be possible unless you are able to rework your visual tree to have one control be a child of the other.

**Comment by shannah** [comment]
Thanks for the reply.  Upon further investigation it looks like the issue only occurs when a web view is the element behind the canvas.  If I place a button there, I can get the events to pass through.

So it appears that this is not Win2D-related.
