### ISSUE TITLE
Allow brush mapping mode?

### ISSUE THREAD

**Issue by amerkoleci** [Microsoft/Win2D#49]
WPF Linear/Radial brush has mapping mode which can be Absolute or RelativeToBoundingBox, in this way user can specify values in range 0..1 and apply the custom brush transform calculated related to the shape rendering bounds (IE: Rect bounds, Ellipse, Shape bounds).

**Comment by clandrew** [comment]
Hi, amerkoleci. That sounds like an interesting feature idea! 

Currently, Win2D supports gradient brush co-ordinates that are absolute only. 

However, the content to which brushes can be applied (geometry, text, opacity masks) tends to be bounded in some way, and each of these types of bounds can be queried by the app. So it is possibly something that could be introduced in Win2D. There are corner cases where infinite-bound content is being filled with a brush, and for these we would define some specific behavior.

Do you find this functionality blocking your app? Or more of a 'nice to have'?

**Comment by amerkoleci** [comment]
Was just an idea and nice to have, users comming from wpf would find this useful

**Comment by clandrew** [comment]
I added this item to our internal backlog, and our backlog wiki page, for us to visit in a future sprint. Thanks so much for bringing this up! This type of feedback is very helpful for our planning. I'll mark this issue Closed.

**Comment by shawnhar** [comment]
Hi, I wanted to follow up on this issue and let you know we've decided not to implement this mode in Win2D.  Unlike a retained mode API such as WPF, Direct2D (on which Win2D is based) does not automatically track bounding information for every shape in a scene, so this would be a surprisingly expensive thing to apply at the low level drawing API layer.
