### ISSUE TITLE
CanvasBitmap.LoadAsync failed silently under BackgroundTask

### ISSUE THREAD

**Issue by tgckpg** [Microsoft/Win2D#490]
I called it like this:
```C#
CanvasBitmap CoverImage = await CanvasBitmap.LoadAsync( new CanvasDevice(), s.AsRandomAccessStream() );
```

I would like to know how to do it properly. Thanks!

**Comment by shawnhar** [comment]
What exactly do you mean by "failed silently"?  Does the operation never complete?  Process exit?  Crash?

Are you following the steps to use a deferral described at https://msdn.microsoft.com/en-us/windows/uwp/launch-resume/create-and-register-a-background-task?

**Comment by tgckpg** [comment]
I was trying to create a dummy project for this case but this time it worked.

I guess this was a problem with my other code. Will investigate more. Thanks!
