### ISSUE TITLE
[Question] CanvasAnimatedControl Update as fast as possible?

### ISSUE THREAD

**Issue by chuckries** [Microsoft/Win2D#494]
I would like to have a CanvasAnimatedControl that calls Update as many times as possible between draws, but still Draws at 60 fps. Is this possible to do automatically, or do I need my own logic in the update handler?

**Comment by shawnhar** [comment]
Win2D does not provide any built in mechanism for doing that.

Repeating things as many times as possible without waiting for any kind of timer, input event, etc, is not generally a great idea for battery life or CPU thermal throttling!  So we deliberately avoided designs that would encourage apps down a just-run-flat-out-no-matter-what path.

**Comment by chuckries** [comment]
Makes sense. I'm curious if you have any thoughts given what I'm trying to do. Essentially I want to enable a "turbo mode" on my CanvasAnimatedControl that disables rate limiting. When in standard mode, the controls run in fixed time step mode aimed at 60 fps. When put into this "turbo mode", the goal is just to animate as fast as possible. Today I am simply setting the target elapsed time to 120 fps, but I'm not sure if this is the right approach.

**Comment by shawnhar** [comment]
What exactly are you trying to achieve here?   If you just want the animation to run faster, changing TargetElapsedTime is a good approach.  Or, you could just alter the contents of your Update handler to advance the state of things by a larger amount.

**Comment by chuckries** [comment]
I am using a CanvasAnimatedControl to run a legacy bitmap generator. Update gets the next frame bitmap. Draw applies effects to the bitmap and draws it. The correct speed for the legacy component is 60 fps, so the default CanvasAnimatedControl is perfect. For this "turbo mode" idea, the goal is to drop any rate limiting on getting the next frame, but still drawing the control at 60 fps. This will cause the animation to appear much faster than 60 fps, which is the goal. Does this make sense?

**Comment by chuckries** [comment]
My fear is that setting target elapsed time too small will cause draw event to get dropped and the control itself won't animate smoothly. I'm not sure if this is the case.

**Comment by 13thsymphony** [comment]
Are you saying that it isn't practical to modify this legacy bitmap generator, for example to double the time step? What about calling the generator twice per update and discarding the first result - this wastes half of your computation but is morally the same as running the loop at a faster speed, as you will be restricted to 60Hz VSync in most cases.

**Comment by shawnhar** [comment]
I'm suspicious of the goal to just drop any rate limiting at all.  That means you will get completely unpredictable speed across different systems, and may even change speed from one moment to the next as clock rates change power state etc.  Are you sure this is really what you want as opposed to just running a fixed amount faster than wall clock speed?

> My fear is that setting target elapsed time too small will cause draw event to get dropped and the control itself won't animate smoothly. 

Yes indeed, that can happen if you are trying to do more work than there is time available to do it in.  I call this situation the "black pit of despair": https://blogs.msdn.microsoft.com/shawnhar/2011/03/25/technical-term-that-should-exist-black-pit-of-despair/

There is no good solution for such a problem - you fundamentally can't hope to update something at a higher rate than the machine is capable of keeping up with.

**Comment by chuckries** [comment]
I think the most correct thing to do is have "turbo mode" just advance a certain number of frames in Update and make this number user configurable. With this I can leave targetelapsedtime at its default and everybody should be happy.

**Comment by shawnhar** [comment]
Changing TargetElapsedTime vs. advancing multiple frames inside Update are equivalent.  This just moves where the "repeat N times" loop happens between Win2D and your own code.

**Comment by chuckries** [comment]
Thanks for the info!
