### ISSUE TITLE
Crash in Microsoft_Graphics_Canvas RegisteredEvent::Release

### ISSUE THREAD

**Issue by eriadel** [Microsoft/Win2D#496]
Hi Guys,

Please check. Not critical, however, something went wrong in Microsoft_Graphics_Canvas

Here goes the stack, if you have any ideas, please be welcome to fix it. (we usually know what's wrong when we see the stack and compare it to our code)

We cannot reproduce it. It's exception from the market.

0
KERNELBASE
RaiseException
0x62
1
VCRUNTIME140_APP
_CxxThrowException
0x65
2
Microsoft_Graphics_Canvas
ThrowHR
0x1E
3
Microsoft_Graphics_Canvas
RegisteredEvent::Release
0xF
4
Microsoft_Graphics_Canvas
ABI::Microsoft::Graphics::Canvas::UI::Xaml::ImageControlMixIn::~ImageControlMixIn
0x42
5
Microsoft_Graphics_Canvas
ABI::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl::`scalar deleting destructor'
0x57
6
Microsoft_Graphics_Canvas
Microsoft::WRL::Details::RuntimeClass_Microsoft::WRL::Details::InterfaceList_Microsoft::WRL::MixIn_ABI::Microsoft::Graphics::Canvas::UI::Xaml::CanvasAnimatedControl,ABI::Microsoft::Graphics::Canvas::UI::Xaml::BaseControlWithDrawHandler_ABI::Microsoft::Gra
0x56
7
Windows_UI_Xaml
ctl::ComObject_DirectUI::UserControl_::Release
0x23
8
Windows_UI_Xaml
ctl::release_interface_DirectUI::DependencyObject_
0x2E
9
Windows_UI_Xaml
DirectUI::DependencyObject::ReleaseForPeerReferenceHelper
0x63
10
Windows_UI_Xaml
DirectUI::DependencyObject::DisconnectFrameworkPeerCore
0x611
11
Windows_UI_Xaml
DirectUI::DependencyObject::DisconnectFrameworkPeer
0x47
12
Windows_UI_Xaml
DirectUI::DXamlCore::ShutdownAllPeers
0x66
13
Windows_UI_Xaml
DirectUI::DXamlCore::DeinitializeInstance
0x289
14
Windows_UI_Xaml
DirectUI::DXamlCore::Deinitialize
0x6C
15
Windows_UI_Xaml
DirectUI::FrameworkView::Uninitialize
0x53
16
twinapi_appcore
Windows::ApplicationModel::Core::CoreApplicationView::Uninitialize
0x5B
17
twinapi_appcore
_lambda_9b41d69926023e09ea69cf7275f119de_::_helper_func_stdcall_
0x1D5C1
18
SHCore
_WrapperThreadProc
0xCA
19
kernel32
BaseThreadInitThunk
0x24
20
ntdll
__RtlUserThreadStart
0x2B
21
ntdll
_RtlUserThreadStart

Best Regards,
Carl

**Comment by damyanp** [comment]
I'm wondering if RegisteredEvent's destructor maybe shouldn't throw if it fails to unregister the event.  An assert in debug builds might be helpful, but not much we could do in response to the exception.

**Comment by eriadel** [comment]
Please do not crash in the release build when destructor fails to unregister the event, if possible. Thanks.

**Comment by shawnhar** [comment]
This is fixed in Win2D 1.21.0 (released today)
