### ISSUE TITLE
Offscreen rendering - performance issue

### ISSUE THREAD

**Issue by weny** [Microsoft/Win2D#497]
I'm trying to implement an offscreen rendering mechanism for my map control, but I'm facing some performance issue.

It takes about 200 ms to render geometries directly to CanvasControl. That's fine.
```
// this code takes +- 200 ms
void MoGfxControl::OnDraw(CanvasControl ^sender, CanvasDrawEventArgs ^args) {
	MeasureElapsedTime et;
	
	args->DrawingSession->Clear(Windows::UI::Colors::Brown);

	m_RendererCanvas->Canvas()->SetDrawingSession(args->DrawingSession);

	// render map
	m_Renderer.BeginRenderByCentre (m_CenterX, m_CenterY, m_Scale, NULL, NULL, 0);
	m_Renderer.RenderLegend(m_VisibleLegendEntries);
	m_Renderer.EndRender();

	TRACE(L"Rendering map: %d\n", et.Duration());
}
```

But if I try to create offscreen render target, the rendering takes 1100 ms.
```
// this code takes +- 1100 ms if m_Invalidate is true
void MoGfxControl::OnDraw(CanvasControl ^sender, CanvasDrawEventArgs ^args) {
	if (m_BitmapBuffer == nullptr || m_Invalidate) {
		m_Invalidate = false;
		m_BitmapBuffer = ref new CanvasRenderTarget(sender, this->ActualWidth, this->ActualHeight, 96*m_Zoom);

		auto drawing = m_BitmapBuffer->CreateDrawingSession();
		drawing->Clear(Windows::UI::Colors::Brown);

		m_RendererCanvas->Canvas()->SetDrawingSession(drawing);

		// render map
		m_Renderer.BeginRenderByCentre (m_CenterX, m_CenterY, m_Scale, NULL, NULL, 0);
		m_Renderer.RenderLegend(m_VisibleLegendEntries);
		m_Renderer.EndRender();

		drawing->Flush();
	}
	
	args->DrawingSession->DrawImage(m_BitmapBuffer);
}
```

I also tried to create aligned offscreen bitmap `CanvasRenderTarget(sender, 1024, 1024, 96)`. But it had no inpact on performance and render stilltakse around 1100 ms.

Am I doing something wrong or the hardware acceleration is not supported for offscreen target?

Testing device Lumia 650 (Windows 10.0.14393.0)

**Comment by shawnhar** [comment]
Actually I suspect the longer time is correct for both cases - the difference is just that you aren't measuring time correctly in the first example.  Most drawing APIs just queue up commands for later execution.  It is not until the rendering is flushed that Direct2D carries out any CPU intensive geometry computations, and then the GPU carries out the actual rendering work.  Your offscreen example includes an explicit call to Flush, which means you are including that time in your measurement, but the CanvasControl example does not call Flush, which means that work will happen automatically later on, after your time measurement has completed.

**Comment by weny** [comment]
You're right. It takes the same time, if I call Flush() in CanvasControl example.

Thank you
