### ISSUE TITLE
CanvasGradientMesh TensorPatch Colors documented incorrectly.

### ISSUE THREAD

**Issue by mscherotter** [Microsoft/Win2D#498]
Creating a gradient mesh with the CanvasGradientMesh.CreateTensorPatch() API, the order of colors documented in the images on http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Geometry_CanvasGradientMesh_CreateTensorPatch.htm are incorrect.  The order of the colors should be documented as [Upper left, Upper right, Lower left, Lower right] but that is not reflected in the image.  Either the API is incorrect or the documentation is incorrect.
The CanvasGradientMesh.CreateCoonsPatch() API color order is as documented, correctly.

**Comment by clandrew** [comment]
Looks like this is a problem in the diagram in the documentation. The field colors[2] should be in the lower left, and colors[3] should be in the lower right.

Thanks for catching this!

**Comment by shawnhar** [comment]
This is fixed in Win2D 1.21.0 (released today)
