### ISSUE TITLE
Is it possible to send a "Draw" command outside the "Draw" envent?

### ISSUE THREAD

**Issue by getangar** [Microsoft/Win2D#499]
Hi there,
thanks for this nice library.

I was wandering if it's possible to send a draw command, like DrawCircle, to a CanvasControl but outside the Draw Event handler.

Thanks in advance!
gennaro

**Comment by damyanp** [comment]
No directly, no.  You can trigger a redraw with the Invalidate() method.  Or you can draw to an offscreen render target (see http://microsoft.github.io/Win2D/html/Offscreen.htm) and then in the control's Draw event handler draw that render target to the control.

**Comment by getangar** [comment]
Hi Damyan,
thank you so much for the hits ... this fits perfectly my Needs!

Regards,
ge

**Comment by damyanp** [comment]
No problem at all, I'm glad to be able to help!
