### ISSUE TITLE
Draw event not fired when CanvasControl is placed inside a XAML Canvas

### ISSUE THREAD

**Issue by ejcarp** [Microsoft/Win2D#500]
<Canvas>
    <canvas:CanvasControl
         Draw="OnDraw"
         CreateResources="OnCreateResources" />
</Canvas>

Draw is not fired in the above scenario. It will fire if you remove the Canvas.

**Comment by shawnhar** [comment]
It's impossible to say what you are doing wrong without some more details, ideally a repro app.

Wild guess - perhaps you are not setting a size on your control so it is ending up with zero dimensions?

**Comment by ejcarp** [comment]
Yes, that was the issue, sorry I didn't update before!

**Comment by ratishphilip** [comment]
@shawnhar Why is it required to explicitly specify the size of the CanvasControl? 
Couldn't it just stretch itself to fill the parent control and set its size automatically?

**Comment by shawnhar** [comment]
Layout behavior is determined by whatever control is doing the layout.  Stack panels and grids will stretch their children if configured to do so, but XAML Canvas just positions children on top of each other without any stretch behaviors.

**Comment by ratishphilip** [comment]
Sorry, my bad. I didn't notice that it was placed in a Canvas.
