### ISSUE TITLE
Is CanvasStrokeStyle's CustomDashStyle dependant on StrokeWidth?

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/Win2D#501]
Hi,
Consider the following code
```C#
private void OnCanvasDraw(ICanvasAnimatedControl sender, CanvasAnimatedDrawEventArgs args)
{
    var geom1 = CanvasGeometry.CreateRectangle(sender, new Rect(100, 100, 200, 100));
    var css = new CanvasStrokeStyle()
    {
        CustomDashStyle = new float[] { 10, 10 }
    };

    var geom2 = CanvasGeometry.CreateRectangle(sender, new Rect(400, 100, 200, 100));

    args.DrawingSession.DrawGeometry(geom1, Colors.Black, 2, css);
    args.DrawingSession.DrawGeometry(geom2, Colors.Black, 4, css);
}
```

This produces the following result
![win2d_cds](https://cloud.githubusercontent.com/assets/7021835/23533454/b62031d6-ff66-11e6-9abe-7d79e323aed0.png)

The number of dashes is reduced when the stroke width is increased.  Is this the expected behavior? 

I was under the impression that the number of dashes would remain the same and only their thickness would vary.

**Comment by damyanp** [comment]
Yes, this is expected - the length of the dash is relative to the value in the CustomDashStyle and the line stroke width.

Recall that Win2D is built on top of Direct2D, so there's some more details here: https://msdn.microsoft.com/en-us/library/windows/desktop/dd371301(v=vs.85).aspx

When you think about how different line caps and line joins work, I think it makes sense for the stroke width to be factored into this.

**Comment by ratishphilip** [comment]
Thanks for the clarification.
So due to this reason, the DashOffset is also dependant on the stroke width, right?

**Comment by damyanp** [comment]
That's right, yes.

**Comment by ratishphilip** [comment]
Thanks.
