### ISSUE TITLE
Run Win2D at full resolution on Mobile

### ISSUE THREAD

**Issue by ZodmanPerth** [Microsoft/Win2D#502]
I'd like to use CanvasAnimatedControl at full physical resolution on Mobile, but I can't turn off the automatic scaling in UWP.  According to [the MS docs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationviewscaling#Windows_UI_ViewManagement_ApplicationViewScaling_DisableLayoutScaling), it's simply a matter of using `Windows.UI.ViewManagement.ApplicationViewScaling.TrySetDisableLayoutScaling(true);` when the app starts if your mobile device is on or above v10.0.14388.0, but this isn't working for me.

[My sample app](https://1drv.ms/u/s!Aj0ttYc6Owxpi-0DRLXa2VMVCYTgEw)

My only option appears to be to wrap the canvas in a ViewBox; surely that can't be true?

**Comment by shawnhar** [comment]
This article explains how DPI and DIPs are handled in Win2D:  https://microsoft.github.io/Win2D/html/DPI.htm

**Comment by ZodmanPerth** [comment]
The article states the CanvasAnimatedControl uses the same DPI as the display app it is running on, in this case a UWP app.  I am trying to stop the automatic scaling of my UWP app on mobile so my CanvasAnimatedControl gets to use the full 1080x1920 at 100% scaling instead of 360x640 at 300% that is automatically set.
The docs point to using `Windows.UI.ViewManagement.ApplicationViewScaling.TrySetDisableLayoutScaling(true);` to turn off the automatic scaling but it doesn't seem to work.
Am I missing something?

**Comment by shawnhar** [comment]
I'm not all that familiar with how the various scaling options work on the XAML side of things, sorry.

If you want to do your Win2D drawing in pixels rather than DIPs, I suggest just changing your drawing session Units to operate in pixels.

**Comment by ZodmanPerth** [comment]
I had a moment to try your suggestion and to my surprise it does what I want. I had thought the drawing of pixels would also be scaled by Windows (the impression I had from the article), but apparently not.

This leads me to some other questions:
* Do I need to set the units in each Draw event or is there a global setting?
* Does Win2d apply a scaling transform that is tied to the Windows scaling setting when working with DPI?

Also, I'm using Win2d to draw some text in the bottom right of my viewport, however it isn't positioning correctly when in pixel units mode. I haven't had a chance to investigate yet so it may be my bad; I'll follow this up on my end when I get some time.

**Comment by ZodmanPerth** [comment]
For those of you following along at home, I've logged the issue with Microsoft [here](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/a7071c65-1983-4656-abd5-fa8111095a7d/uwptrysetdisablelayoutscaling-not-working?forum=wpdevelop).

@shawnhar, technically this question can be closed since the original question has concluded.  I'd still like answers to the above followup questions (if you can).

**Comment by ZodmanPerth** [comment]
Response from Microsoft is that while `Windows.UI.ViewManagement.ApplicationViewScaling.TrySetDisableLayoutScaling(true);` is available on multiple UWP devices, it is only writable on XBox.  As such, the best way to use the real resolution of your UWP device in Win2D is to use `args.DrawingSession.Units = CanvasUnits.Pixels;` in each Draw event.
