### ISSUE TITLE
Issue with SaveAsync

### ISSUE THREAD

**Issue by getangar** [Microsoft/Win2D#503]
Hi all,
I have a UWP Desktop application in which I have a page with a CanvasControl. I have the following method:

public async void SaveImage()
        {
            //CanvasDevice device = CanvasDevice.GetSharedDevice();
            CanvasDevice device = Canvas1.Device;

            var picker = new FileSavePicker();
            picker.FileTypeChoices.Add("Jpegs", new List<string>() { ".jpg" });

            var file = await picker.PickSaveFileAsync();
            if (file == null)
                return;

            using (var stream = await file.OpenAsync(FileAccessMode.ReadWrite))
            {
                var renderTarget = new CanvasRenderTarget(device, (float)Canvas1.ActualWidth, (float)Canvas1.ActualHeight, 96);
                await renderTarget.SaveAsync(file.Path, CanvasBitmapFileFormat.Jpeg);                
            }
        }

which raise an exception when the "SaveAsync" is called:
System.UnauthorizedAccessException: "Zugriff verweigert (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))"

Access denied basically.

Any Suggestion?

**Comment by shawnhar** [comment]
You need to pass the stream directly into SaveAsync, not just the path as a string.

**Comment by getangar** [comment]
Hi Shawn,
thanks for your prompt Feedback! I'm a bit confused because I see that this methods is expecting in sequence the filename and the file Format:

![image](https://cloud.githubusercontent.com/assets/12617186/24261708/23bcd3ce-0ff8-11e7-9766-c0185aaf1dfb.png)

**Comment by shawnhar** [comment]
Look at the other overloads of SaveAsync.

**Comment by 13thsymphony** [comment]
In general you can't pass around paths in the user's filesystem (as opposed to special folders like the app package directory) because of the UWP security model:
https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions
