### ISSUE TITLE
Is it possible to use Win2D without InkCanvas for drawing ink?

### ISSUE THREAD

**Issue by Ponant** [Microsoft/Win2D#506]
Hi,
I have been using InkCanvas so far until I realized the existence of Win2D, which seems more powerful. I am thus wondering if I can get rid off InkCanvas altogether or if Win2D needs it the UWP InkCanvas in some way to draw ink with all the basic features such as load, save, draw, erase, and changing attributes such as color etc? Thanks

**Comment by shawnhar** [comment]
Hello,

Win2D ink functionality is typically used alongside InkCanvas to implement custom drying.  InkCanvas is responsible for gathering ink input and displaying low latency wet ink, after which your Win2D code takes over when the ink is dried.  This article explains more about the difference between wet and dry ink (Win2D enters the picture where it talks about "custom dry" functionality):

https://msdn.microsoft.com/en-us/magazine/mt590975.aspx

**Comment by Ponant** [comment]
So I think the answer to the question is a no? Thanks for the link.

**Comment by shawnhar** [comment]
> So I think the answer to the question is a no?

Strictly speaking I think it would be possible to do ink without InkCanvas, but not using purely Win2D as you'd need a bunch of the other platform ink APIs.  This is unlikely to be a good idea though.

**Comment by Ponant** [comment]
OK thanks for the clarification. I came up with this question after our discussion around the bounds or the `StrokeContainer`, where I lost trust in it and had to resort to Win2D's `CanvasGeometry`.
