### ISSUE TITLE
Unable to create CanvasBitmap from png bytes ...

### ISSUE THREAD

**Issue by Tom-Cuthill** [Microsoft/Win2D#507]
There apparently is some aspect to working with bitmaps that I am not understanding.  I have a very simple .png file which is just a blue tile representing a view of the ocean.  It's just 103 bytes long and properly formed. See attached:
![osmtilefrombitmap](https://cloud.githubusercontent.com/assets/24502866/24893072/b026d67e-1eb3-11e7-9ee2-4a862097be11.png)

I can create the CanvasBitmap asynchronously using this:
![image](https://cloud.githubusercontent.com/assets/24502866/24893135/405a18fa-1eb4-11e7-90d8-d9c3fcde11d5.png)

I can then draw the image in the CanvasControl_Draw method without any problem: 
![image](https://cloud.githubusercontent.com/assets/24502866/24893188/a97699bc-1eb4-11e7-926b-ee330b888385.png)

My problem is that I already have the .png bitmap as a byte array.  If I try to create the CanvasBitmap from the byte array, like this:
![image](https://cloud.githubusercontent.com/assets/24502866/24893263/2c82be62-1eb5-11e7-8088-d528dd9b021f.png)

I consistently get an args exception being thrown, saying argument values do not fall within the expected range.  I'm not sure if I have the incorrect DirectXPixelFormats value and if that is the problem.  I found a clue, when after I load the image asynchronously, I request its bytes:
![image](https://cloud.githubusercontent.com/assets/24502866/24893445/3de45caa-1eb6-11e7-8c9e-793492a821a8.png)

When I look at the bytes I can see they no longer represent a png, but have been expanded to an uncompressed bitmap.  Do I manually have to decompress each png bitmap before it can be used?

This was not necessary in a pure XAML approach.  It worked like this:
![image](https://cloud.githubusercontent.com/assets/24502866/24893631/69c9c69c-1eb7-11e7-8a90-296d8796bf2b.png)

I am new to Win2D so apologies if I've missed something obvious or fundamental.  Asynchronously calling loaders isn't an option for me, as I am just writing one module in a large solution, where the interface only provides the raw png bytes.

Any insights that you can offer would be greatly appreciated.

Cheers,
Tom Cuthill

**Comment by 13thsymphony** [comment]
Hi Tom,

CanvasBitmap.CreateFromBytes is intended to initialize a CanvasBitmap from an already decoded array of pixels. In your case, it sounds like you have a PNG (an actual file) that happens to be contained within a byte array. The easiest way to get that into CanvasBitmap is to first create an IRandomAccessStream over that byte array e.g. using an [InMemoryRandomAccessStream](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.inmemoryrandomaccessstream), and then call the appropriate [LoadAsync overload](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasBitmap_LoadAsync_6.htm).

You note that you want to avoid asynchronous calls. However, it is a well established WinRT design pattern that APIs could block the UI thread -- creating a CanvasBitmap from a file potentially requires accessing the disk (or even the network) and spinning up the codec -- should be asynchronous.

**Comment by Tom-Cuthill** [comment]
Hi,

Thanks for your help with this!  I just found the article 'Loading resources outside of CreateResources' so I guess that is my best option.  There is alot of data flowing into my CanvasControl_Draw handler.  It is organized into multiple layers, some of which contain bitmaps, but most of which contain geometries.  The bitmaps are all loaded in multiple threads in the subsystem which calls into my module.  The bitmaps and geometries come wrapped in objects, and I should be able to attach CanvasBitmaps to those which hold the bitmap bytes.  Just before the CanvasControl gets invalidated, I can set some code up to await the loading of the CanvasBitmaps, as is mentioned in the article.

The only thing I am unclear about is the sequencing of events and the releasing of resources.  The invalidate on the CanvasControl triggers the draw.  The draw sees that the required CanvasBitmaps have not yet been created, so it spawns off tasks to load them in, and just returns to the main thread with no drawing happening.  What triggers the drawing when all the bitmaps have been loaded?  Am I meant to watch the loading progress, and once all the bitmaps are loaded, then call an invalidate on the CanvasControl?  When the bitmaps fall out of the extent of the viewport, and the objects holding the CanvasBitmaps are detached, will the garbage collection just clean things up properly, or is there something I have to do to ensure the resources are completely freed up?

If someone could point me in the right direction for this last bit, I should have it.

Much appreciated,
Tom

**Comment by shawnhar** [comment]
> What triggers the drawing when all the bitmaps have been loaded?

That's up to you.  Win2D will invalidate the control for you automatically when it knows a reason to draw it (for instance the control was first loaded, or an async load registered through CanvasCreateResourcesEventArgs.TrackAsyncAction has completed).  If you need to redraw it at some other time for reasons of your own, you are responsible for calling invalidate at the right time.

> will the garbage collection just clean things up properly

.NET GC will eventually clean up any objects that are no longer referenced.  With potentially big things like GPU bitmaps, though, it can often be a good idea to make sure this happens earlier by explicitly calling Dispose on whatever resources you no longer need.

**Comment by Tom-Cuthill** [comment]
Parts of this are still confusing to me.  The 'Loading Resources outside of Create resources' article suggests putting an IsLoadInProgress function call inside the draw handler, see below:

![image](https://cloud.githubusercontent.com/assets/24502866/24995111/1ce22da6-2060-11e7-8d5a-7c17b997acf7.png)

I assume that the CanvasControl_Draw handler is running on the GUI thread (is this so?).  The suggested IsLoadInProgress function is as follows:

![image](https://cloud.githubusercontent.com/assets/24502866/24995185/671ed4e6-2060-11e7-9445-b27323df5fc5.png)

Everything starts off with the LoadNewLevel function:

![image](https://cloud.githubusercontent.com/assets/24502866/24995790/b2e50358-2062-11e7-9140-f359a5732e78.png)

The LoadNewLevel function assigns the levelLoadTask, but does not start it running.  So when entering the IsLoadInProgress function, it will pass the first test because levelLoadTask is assigned, and will pass the second test, because levelLoadTask hasn't started yet. (Or if the task hasn't started, and so is flagged not complete, when does the LoadNewLevel function ever start?)  It then calls levelLoadTask.Wait().  This will start the task on the current thread, which is the GUI thread and wait for it to complete.  Doesn't this just block the GUI thread which is the opposite of what is desired?

I am trying to marry together two asynchronous systems, one which is providing the bitmaps in png byte format, and another which is asynchronously converting them into CanvasBitmaps.  Ideally there would have been a notification event on the CanvasBitmap.LoadAsync to know when it is done so that I could track the progress asynchronously.  As it stands, the only option I can see is to try to wrap the asynchronous call to CanvasBitmap.LoadAsync in a synchronous wrapper (so that I know when it is done) and attach this to a background task, which is running on a worker thread.

Please let me know if I am missing something here!!

Tom

**Comment by shawnhar** [comment]
> I assume that the CanvasControl_Draw handler is running on the GUI thread (is this so?)

Yes.  In fact all the code in this example runs on the GUI thread, using the C# async model to switch control back and forth - there are no background threads involved at all.

This article may be useful if you are new to how C# approaches async: https://msdn.microsoft.com/en-us/library/mt674882.aspx


> The LoadNewLevel function assigns the levelLoadTask, but does not start it running. 

LoadResourceForLevelAsync starts running the moment LoadNewLevel calls it.  This will execute until it reaches the first await, at which point it will yield control with the rest of its code registered as an async continuation, to be resumed after the awaited operation has completed.


> This will start the task on the current thread, which is the GUI thread and wait for it to complete

The Wait call in IsLoadInProgress is only used to retrieve any error state from the load operation.  This will never actually block because the Wait only happens after the task IsCompleted property has become true.


> Ideally there would have been a notification event on the CanvasBitmap.LoadAsync

There are a ton of different ways to wait on async operations or have code execute once they have completed (see the .NET Task and Task<T> classes) but that is typically handled for you by the C# compiler when you use the await keyword, so it is rarely necessary to deal with the underlying plumbing directly in app code.

**Comment by Tom-Cuthill** [comment]
Thanks for the explanation! I'll do some more research to get more up to speed.
