### ISSUE TITLE
Win2D SVG for D2d1svg

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Win2D#509]
I have began to need some SVG functionality and would be great if the recent classes from D2d1svg were available from Win2D, it will allow to create really interesting scenarios.

Thank you, I know is recent and could need long time to be implemented.

**Comment by clandrew** [comment]
Exposure of SVG is definitely on our radar, and we have work planned for it. So I can affirmatively say it's something you can look forward to seeing in Win2D. Thank you for this feedback!

**Comment by juanpaexpedite** [comment]
Hello, first thank you for the answer. I have began to analyze in depth the SVG format and methods. I've seen there is one method in the specification called getBBox. 

(At the moment I am implementing all the logic I cannot do natively using a webview and javascript).

That method get's a bounding box without considering the stroke-width and more. (according to the SVG specification is right). I have not seen anything like that in D2d1svg, would be possible to get the real boundary of an SVG group or document in Win2D. Please consider that in case is on time to develop that.

Thank you again.

**Comment by shawnhar** [comment]
This is addressed in Win2D 1.21.0 (released today)
