### ISSUE TITLE
Error in Visual Studio 2015 CTP6

### ISSUE THREAD

**Issue by venetasoft** [Microsoft/Win2D#51]
The Nuget Win2D package install successfully, but compile fails (even an empty project) with the error:

'Could not find SDK "Microsoft.VCLibs, Versio=12.0"'

**Comment by shawnhar** [comment]
Thanks for the report!   We'll take a look.

**Comment by damyanp** [comment]
Hi David - can you confirm that you chose to install the “Window 8.1 and Windows Phone 8.1 Tools” when you installed Visual Studio?

Also, what type of empty project are you trying to install the nuget package to?

**Comment by venetasoft** [comment]
Hi Damyanp,
 I'm using latest Visual Studio 2015 and Tools (Windows 10 sdk preview).

Thanks,
David

**Comment by damyanp** [comment]
The current release of Win2D does not support building against the Windows 10 SDK.  This is something we'll be adding support for in the near future.

In the mean time you'll need to build against the Windows 8.1 SDK.

**Comment by venetasoft** [comment]
Thank you.
