### ISSUE TITLE
CanvasImages flash using DrawImage in Win2D.Win81 ...

### ISSUE THREAD

**Issue by Tom-Cuthill** [Microsoft/Win2D#510]
Hi,

I am using the advice given in the "Loading resources outside of CreateResources" article and loading in series of raster tiles as CanvasBitmaps.  The tiles come in sporadically, at about a third of a second apart.  What I am seeing is that as each tile is displayed, the whole canvas flashes.  The exact same code using the Win2D.uwp library draws the tiles with no flashing.

The raster tiles are held in a growing list.  Here is how I convert them into CanvasBitmaps.

![image](https://cloud.githubusercontent.com/assets/24502866/25062384/dd99deb0-21fd-11e7-98c0-47a52c5ae751.png)

Note that the list is growing while this Task executes, so that is the reasoning behind the loop.  Only stop when we have been through the raster list and we have not had to create a canvasBitmap from a raster tile.  When the loop exists, the canvas is invalidated to cause a repaint.

Here is my draw handler:

![image](https://cloud.githubusercontent.com/assets/24502866/25062305/b1442d8a-21fc-11e7-8ddd-b86acf97f27a.png)

Again, the list of Rasters could still be growing, so I check to see if a raster has a connected canvasBitmap before drawing.

I have no idea how to stop the canvas to stop flashing as the tiles come in.  The tiles come in one or two at a time, and there is a flash as the screen clears itself and then repaints the old tiles as well as the new.  Unfortunately the project I am working on is stuck with a Windows 8.1 target.  Are a third of a second updates too frequent for the Win2D.Win81 library?  Is this something to do with Blending or using an ImageBrush?  Interestingly, if I use an imageBrush like in the commented code, nothing gets displayed.

Any insight into what is going on would be greatly appreciated.

Best regards,
Tom Cuthill

**Comment by shawnhar** [comment]
You don't show the implementation of the IsLoadInProgress() method, but my guess would be the flickers are caused by this sometimes returning true, in which case CanvasControl_Draw will skip actually drawing anything...

**Comment by Tom-Cuthill** [comment]
Hi Shawnhar,

Thanks so much for pointing this out!  I was under the mistaken impression that what was on the canvas would stay on the canvas, unless CanvasControl_Draw actually drew something.  I now understand that it is not just the CanvasDrawingSession's clear method which wipes the screen, it is entering the CanvasControl_Draw method itself which effectively names the drawing activities that are submitted to the GPU.  If no drawing activities are within the CanvasControl_Draw method, then an empty screen results.

It is interesting that there wasn't any flashing using the UWP library.  I guess its refresh must be a bit faster, so your eyes don't catch it.

Thanks for setting me straight on a pretty basic misunderstanding of how the system works.  Your help is very much appreciated.  I've got everything working correctly now and I'll meet a deadline for a demo next week.

Have a great holiday!
Tom
