### ISSUE TITLE
Custom Dash Style and Geometry rotation

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/Win2D#512]
I am trying to create a custom border around a rectangle. Each side has border rendered for only 25% of its length, the rest is blank. For this purpose I am using the CustomDash property of the CanvasStrokeStyle. The rectangle looks like this

![rect0](https://cloud.githubusercontent.com/assets/7021835/25145200/54d082ee-2425-11e7-9390-91de0351591d.png)

Here is the code I am using to render the custom border.

```C#
private float _dashFactor = 0.25f;
private float _strokeWidth = 8f;
private CanvasStrokeStyle _style;

Vector2 _rectSize = new Vector2(600, 400);
Vector2 _rectOffset = new Vector2(300, 200);
private float _angle = 0;

private void CanvasControl_OnDraw(CanvasControl sender, CanvasDrawEventArgs args)
{
    var transform = Matrix3x2.CreateRotation(_angle,
        new Vector2(_rectOffset.X + _rectSize.X / 2f, _rectOffset.Y + _rectSize.Y / 2f));

    var rectGeometry = CanvasGeometry.CreateRectangle(sender, 
                                                      new Rect(_rectOffset.X, 
                                                               _rectOffset.Y, 
                                                               _rectSize.X, 
                                                               _rectSize.Y))
                                     .Transform(transform);

    var width = _rectSize.X / _strokeWidth;
    var height = _rectSize.Y / _strokeWidth;

    var dash1 = width * _dashFactor;
    var dashGap1 = width - dash1;
    var dash2 = height * _dashFactor;
    var dashGap2 = height - dash2;

    _style = new CanvasStrokeStyle()
    {
        CustomDashStyle = new[] { dash1, dashGap1, dash2, dashGap2 }
    };
    args.DrawingSession.FillGeometry(rectGeometry, Colors.BurlyWood);
    args.DrawingSession.DrawGeometry(rectGeometry, Colors.Black, _strokeWidth, _style);
}

private void RangeBase_OnValueChanged(object sender, RangeBaseValueChangedEventArgs e)
{
    _angle = (float)(e.NewValue * Math.PI / 180f);
    CanvasCtrl.Invalidate();
}
```

The problem is if the geometry is rotated to 90 degrees or 270 degrees (or similar multiples), the dashes are not rendered correctly. For the rest of the angles it renders properly.
Here is what the rectangle looks like when it is rotated 90 degrees.

![rect90](https://cloud.githubusercontent.com/assets/7021835/25145208/5f126a9c-2425-11e7-9e07-6c815537dbab.png)

Here is what the rect looks at 89 degrees rotation

![rect89](https://cloud.githubusercontent.com/assets/7021835/25145344/ca31333a-2425-11e7-90ef-3aa3db5867a5.png)

Could you please let me know if this is the correct behaviour of custom dashes or am I implementing it incorrectly?

I have attached a sample project which reproduces this behaviour.

[CustomDashTest.zip](https://github.com/Microsoft/Win2D/files/930610/CustomDashTest.zip)

**Comment by shawnhar** [comment]
I think you are seeing a consequence of Direct2D being arguably a bit too smart for its own good.  It is optimizing 90 degree rotations of a rectangle simply by modifying the coordinates of the rectangle, rather than creating a (more complex to evaluate) arbitrarily transformed geometry.  This affects which corner the dash pattern starts from.

One way to bypass this optimization is to specify your rotation via CanvasDrawingSession.Transform, rather than using the CanvasGeometry.Transform method.

**Comment by ratishphilip** [comment]
@shawnhar  Thanks a lot for the clarification. 
Specifying the rotation via CanvasDrawingSession.Transform works indeed!
