### ISSUE TITLE
Do we need to Dispose created bitmaps?

### ISSUE THREAD

**Issue by apollyonbob** [Microsoft/Win2D#514]
I know we need to dispose created drawing sessions, usually by putting them in a using block. However, we create a tremendous number of objects during resource creation - like a hundred little gamer pics - and there was some concern that leaving all these IDisposable objects referenced in a dictionary on the control could result in memory leaks.

So we called Dispose on them in AnimatedCanvasControl.Unloaded. This apparently breaks things. It caused all kinds of strange issues, from enumeration issues on the dictionary to deadlocks on the UI thread.

I commented out all those dispose calls and the issues went away.

I don't see anywhere in the documentation about whether or not you need to dispose of your own resources, so I thought I'd see if you could just confirm - call Dispose() or leave it for GC?

Thanks

**Comment by shawnhar** [comment]
This really depends on your situation.  GC will eventually reclaim objects that are unreferenced.  Explicitly calling Dispose is useful if

a) You want to control exactly when big objects get cleaned up
b) Or your objects never actually become unreferenced for whatever reason

Calling Dispose will work barring bugs in the way you use it.  Perhaps you had a race condition, if you didn't do anything to synchronize UI thread event handlers with the animated control game thread?  (remember that animated control is inherently multithreaded...)

**Comment by apollyonbob** [comment]
Maybe it was where we were doing it.

We had, in Control Unloaded a call to AnimatedCanvas.RemoveFromVisualTree. Then in AnimatedCanvas.Unloaded is when we were calling dispose because that way we know that the Update/Draw methods aren't being called anymore. 

It seemed that putting the Dispose in there resulted in problems. 

They seem to be getting cleaned up yes, as right now they're just being stored as properties on the control, which means that the control is the only thing referencing them. So I assume after we leave the page, and call RemoveFromVisualTree, that the control gets cleaned up, and then all the objects that don't have any other references get cleaned up. I just wanted to clarify that Win2D itself isn't keeping some kind of reference to these objects.
