### ISSUE TITLE
Server side

### ISSUE THREAD

**Issue by terraslate** [Microsoft/Win2D#516]
Hello. If i have a server with a gpu or two that renders real-time video and needs to manipulate video stills (drawing text on top of bitmaps, but they'll never be displayed in the server as they will be sent to a client ) is this library a good fit and would it still use the GPU hardware. If i have 300 users sending 25 frames a second which i need to process by drawing text on then any help i can get from the GPU to spare the cpu some effort is golden . The images are not large , say 320x240 or 640x480, but there are lots per second. Currently the cpu alone using system.drawing can handle all of this work (well there are 28 CPUs in it) but i am looking to offload some or all of that work instead.of having the gpu sat idle. You.can imagine the servers running pretty warm, though i can t help feel that there is a gpu in there sat idle that could be helping out. If so then next question is would it work better with even more GPUs, and if the GPUs can't cope will it grwcefully still use cpu or does it just give up and say the GPU is maxed out?

Thanks

**Comment by shawnhar** [comment]
Win2D is a WinRT API, for use by UWP applications.  It's probably not a good choice (in fact I'm not sure if it would be possible to use at all?) in a server environment.

Depending what kind of GPU hardware is available (if any?) on your servers, the underlying Direct2D C++ API might be worth investigating.

**Comment by terraslate** [comment]
Thank you Shawn.

I had been reading around and came across this on msdn which suggests it would be the better choice (though this article suggests software rendering, another msdn article points out that hardware in session 0 is also supported)  hence my discovery of your framework .

Many thanks


https://msdn.microsoft.com/en-us/library/windows/desktop/ff485857(v=vs.85).aspx


Sent from my Samsung Galaxy smartphone.


-------- Original message --------
