### ISSUE TITLE
Aliased not being applied when using shaders

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Win2D#518]
I have created a new issue instead continuing the closed because apparently are not connected:

1.- Suppose you create a low res canvas like 320x200 if you draw something without using any shader with the following options:

       session.Antialiasing = CanvasAntialiasing.Aliased;

The result is like the following (perfect aliased):

![image](https://cloud.githubusercontent.com/assets/5947026/25540855/6cb90b2a-2c44-11e7-932f-d1de40a35b62.png)

2.- Now If a create a do nothing shader:

    #define D2D_INPUT_COUNT 1 
    #define D2D_INPUT0_COMPLEX

    #include "d2d1effecthelpers.hlsli"

    D2D_PS_ENTRY(D2D_ENTRY)
    {
        float4 color = D2DGetInput(0);
        return color;
    }

And I set the shader session also aliased like the following where session is Aliased:

     CanvasCommandList cl = new CanvasCommandList(session.Device);
    using (CanvasDrawingSession clds = cl.CreateDrawingSession())
    {
        clds.Antialiasing = session.Antialiasing;
        clds.FillGeometry(geometry2, pen, opacityBrush);
    }
    GradientShaderEffect.Source1 = cl;
    session.DrawImage(GradientShaderEffect);
    
I have the following result:

![shaderinout](https://cloud.githubusercontent.com/assets/5947026/25540991/f052c372-2c44-11e7-9f39-b2e3f1bfac54.PNG)

The border has antialiasing instead being like the first one. 

I have tried to change the behavior with:

     GradientShaderEffect.Source1Interpolation = CanvasImageInterpolation.NearestNeighbor;

With the same result, May I have missed an step on creating the shader?

Thank you

**Comment by shawnhar** [comment]
Are you 100% sure what the value of session.Antialiasing is in that second code?  My first guess would be that maybe the drawing of your geometry into the command list is still getting antialiased.

A good way to debug things like this is draw the intermediate into a rendertarget rather than commandlist, then save the rendertarget out to .png so you can inspect what values were written there to narrow down whether it is this drawing or the later DrawImage that is differing from what you intended.

**Comment by juanpaexpedite** [comment]
Yes I have checked and also forced that to be sure, 

![image](https://cloud.githubusercontent.com/assets/5947026/25547091/8ceddb0a-2c5d-11e7-82b4-44778738f11d.png)

Tomorrow I will implement the rendertarget to save that. thank you.

**Comment by juanpaexpedite** [comment]
I've tried to reproduce the issue in another clean test project but I have no issues at all, I'll follow your advice to figure out what's happening.
