### ISSUE TITLE
Problem with CanvasBitmap.GetPixelColors

### ISSUE THREAD

**Issue by BubblegumYeti** [Microsoft/Win2D#519]
I am trying to apply some Perlin noise algorithm to the existing colors of a bitmap.

CanvasBitmap.GetPixelColors always returns RGB(0,0,0) colors. 

var demoBitmap=new CanvasRenderTarget(sender, 100, 100, 96, Windows.Graphics.DirectX.DirectXPixelFormat.B8G8R8A8UIntNormalized, CanvasAlphaMode.Premultiplied);

This is how I create it... 

Then i draw a bit in it

using (var ds = demoBitmap.CreateDrawingSession())
            {
                ds.DrawCircle(new Vector2(50, 50), 45, Colors.Blue, 3);

                ... snip snip

                var colorsOut = planetBitmap.GetPixelColors();
           }

colorsOut always seem to be 0 colors... what am I doing wrong?

**Comment by shawnhar** [comment]
You haven't finished drawing to the bitmap yet when you call GetPixelColors, because this is inside the using drawing session block.

**Comment by BubblegumYeti** [comment]
Oh... what a noob mistake. Thanx!
