### ISSUE TITLE
TrackAsyncAction for Draw

### ISSUE THREAD

**Issue by hamjoe** [Microsoft/Win2D#52]
Are there plans to have a `TrackAsyncAction()` method on `CanvasDrawEventArgs` like there is on `CanvasCreateResourcesEventArgs`?

**Comment by clandrew** [comment]
Hi, hamjoe. There aren't currently any plans to have a TrackAsyncAction on the Draw event. One reason being, the Draw handler isn't prone to the same types of synchronization problems as the CreateResources handler. TrackAsyncAction, among other things, works to inform the control about asynchronous work issued from a handler. It is unlikely (and often inadvisable) that costly asynchronous work, such as loading resources from disk, occur in the Draw handler. 

If you're curious about the rationale behind TrackAsyncAction and the history behind it, it's explained more in [this blog post](http://blogs.msdn.com/b/win2d/archive/2014/12/05/async-resource-loading-in-win2d.aspx).
