### ISSUE TITLE
Direct Pixel Manipulation

### ISSUE THREAD

**Issue by thecobblersfather** [Microsoft/Win2D#520]
I have a UWP app that generates an array of (say 500) x,y coordinate values and displays them on an Xaml Image.

Currently I am using a ComPtr to get direct access to the byte array of a SoftwareBitmap and individually changing the value of each pixel. This method works, but seems resource intensive.

Does Win2D offer better methods for something like this?

**Comment by shawnhar** [comment]
Usually the best answer to "how do I set individual pixel values using the CPU" is "don't do that" :-)

Setting individual pixel values via the CPU is not an efficient way to drive a modern GPU based rendering API like Win2D.  If you absolutely have no other choice, try CanvasBitmap.SetPixelBytes, but it is far more efficient if you can find a way to do all your rendering work on the GPU rather than CPU.

**Comment by thecobblersfather** [comment]
I'm not sure I have no other choice, I just do not know a better way to draw individual points on a 250x250 section of screen, given x,y values.

Since it is not covered by Win2d, what direction would you advise me to take regarding minor GPU rendering on the UWP?

**Comment by shawnhar** [comment]
Depending on what you are trying to draw, I would start by looking at using GPU rendering APIs such as DrawLine, FillRect, or perhaps CanvasSpriteBatch.  For more advanced scenarios, a custom pixel shader opens up more sophisticated possibilities.

Setting pixels on the CPU might be fast enough if there aren't too many of them and you aren't doing this too often, but GPU rendering is far more efficient.

**Comment by thecobblersfather** [comment]
Since my question was answered I closed the issue, but will I gain much by moving to Win2d SetPixelBytes vs the Comptr Softwarebitmap method I am using currently?

**Comment by shawnhar** [comment]
> will I gain much by moving to Win2d SetPixelBytes vs the Comptr Softwarebitmap method I am using currently?

I don't have a good instinct about that, sorry.   Both approaches involve a CPU to GPU data transfer, but I'm not sure how the details would compare.  If this is important for your app, maybe try both and measure it?

**Comment by thecobblersfather** [comment]
Good idea. Thanks.
