### ISSUE TITLE
Rendering text along the edge of a curved path

### ISSUE THREAD

**Issue by Tom-Cuthill** [Microsoft/Win2D#521]
Hi,

I just wanted to make sure that I am on the right path in doing this.  In order to write a series of glyphs along a curved path I can first get a list of equidistant points along the curve and record the slope at each one.  Then in order to draw each glyph, I rotate the canvas 90 degrees counterclockwise from the slope and draw the glyph.

Is this the best approach to take?  Unless I've missed something I haven't found a way to rotate characters any other way.

Any insights would be greatly appreciated,

Cheers,
Tom Cuthill

**Comment by Tom-Cuthill** [comment]
Correction:
I meant to say I rotate the canvas to the slope, and draw the glyph.

**Comment by shawnhar** [comment]
Yes, that sounds like a reasonable approach to me.
