### ISSUE TITLE
Suggestion for implementing a scrolling canvas surface

### ISSUE THREAD

**Issue by BillHenning** [Microsoft/Win2D#524]
Hello, I'm about to start some work on building a multiline text editor control that I want to render with Win2D.  Before I get too deep, I wanted to get your suggestion on the best way to implement this.  

Consider:
1) The main text area will be scrollable horizontally and vertically.
2) I want this scrollable text area to support smooth animated rendering if flick scrolling was performed.
3) There will be margins, like a line number that are rendered in the canvas but scroll vertically only.

I would prefer to not have to repaint the entire control each time something like the caret blinks.  If I used CanvasControl, it seems like that would have to be the case.

Is the CanvasVirtualControl the right control to use for this scenario?  It seems like for a blinking caret for example, I could just invalidate the small rectangle that contains the caret.  But if I want to then scroll the text area down a line, is there a way I could blit copy the existing rendered text area, and repaint the portion that is still visible after the scroll?  Then just render the bottom area that is brand new?  I might be missing things but I'm not seeing a way to blit copy a region.

Also consider the fact that the end user might have multiple instances (sometimes a lot) of this control active at any given time, and I don't want to cause memory issues.

What approach would you take building a multiline text editor control with margins if you were to start on one?  Any input would be highly appreciated!

**Comment by shawnhar** [comment]
Before you put a lot of effort into building a system that lets you repaint just part of your control, I would start by challenging your assumption that this is necessary.  How expensive is it to always just repaint the whole thing?  Are you sure you really need to do more work to avoid that?

**Comment by BillHenning** [comment]
Hi Shawn,

I haven't implemented anything just yet so it's hard to say if there is a full repaint cost or not.  I'm just bringing this up based on remembering back in the good old WinForms days, there seemed to be an impact of fully redrawing everything and not being efficient around how we did it.  

I wanted to see how I would do the blit copy if I ran into perf issues when working in Win2D in a similar way.  I suppose the render target bitmap would be a way of caching all that.  Is using a secondary render target bitmap going to be very memory intensive if I have this control fullscreen, and there could be multiple instances of it in other tabs?

**Comment by shawnhar** [comment]
Rendertargets can chew a lot of memory if you have many and/or they are big, yes.  This is a classic caching tradeoff (speed vs. size).

**Comment by BillHenning** [comment]
Thanks for the feedback.  I'll give it a go soon and will circle around if I have any other followup questions.

**Comment by BillHenning** [comment]
One more quick question before I forget.  If I'm using CanvasControl to render a very large (size-wise) control (again could be many instances), am I using much memory doing so if I am NOT backing it with a render target bitmap and am just using the CanvasControl's Draw method to render everything?  

I guess another way to rephrase the question... would CanvasControl be considered a "rendertarget" that you said chews a lot of memory?

**Comment by shawnhar** [comment]
Yes, more or less.  Strictly speaking CanvasControl is backed by a DComp surface rather than a D2D or D3D rendertarget, but these are just different versions of "some GPU memory that can be drawn onto".  The bigger the control is, the more memory that will take.

It's totally normal that you need to allocate video memory in order to draw big things onto the screen.  Only reason for concern if you have many layers on top of each other each of which is a separate surface, or if your surfaces are for some reason much larger than the screen itself.

**Comment by Sundarcj** [comment]
finally how did u solve it??
