### ISSUE TITLE
Class not registered issue in a windows runtime component

### ISSUE THREAD

**Issue by dannyfarwin** [Microsoft/Win2D#528]
I added the Win2Duwp from NuGet to a windows c++ runtime component I am working on.  It was added correctly, and I can reference and compile the program fine, but any time a call is made to a Canvas function, I get the "Class not registered" message.  Currently the only line of code using it is Canvas::GetSharedDevice(true);.  I tried it on Visual Studio 2015 and Visual Studio 2017 with the same issue on both.  It is compiled as a x64 component, not sure if this will make a difference with the Win2D runtime or not.

Exception thrown at 0x00007FFF6C099E08 in ViewVaultLC.exe: Microsoft C++ exception: Platform::ClassNotRegisteredException ^ at memory location 0x0000006D6B4FE9F0. HRESULT:0x80040154 Class not registered

WinRT information: Class not registered

Stack trace:
[External Code]
CompositionEffectLibrary.dll!CompositionEffectLibrary::CompositionEffect::[Windows::Media::Effects::IBasicVideoEffect]::SetEncodingProperties(Windows::Media::MediaProperties::VideoEncodingProperties ^ encodingProperties, Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice ^ device) Line 122
[External Code]

**Comment by shawnhar** [comment]
You will also need to add the Win2D package to the app that uses this runtime component.

**Comment by dannyfarwin** [comment]
That was it, thanks
