### ISSUE TITLE
Unable to draw to a framebuffer

### ISSUE THREAD

**Issue by dannyfarwin** [Microsoft/Win2D#529]
I am trying to utilize Win2D in a mediacapture effect library.  Everything seems to be correct, but my output turns out all black and it seems the drawing session is not having any effect.  If I copy the input software bitmap directly into the buffer, it shows up, but anything done via the draw session is not there.  Not sure what I am not understanding.  I first have to convert the YUY2 image over to BGRA, do the processing, then convert back into YUY2 using the softwarebitmap convert methods.

```			CanvasDevice^ device = ref new CanvasDevice();
		auto inputFrameBitmap = context->InputFrame->SoftwareBitmap;
		auto newBitmap = SoftwareBitmap::Convert(inputFrameBitmap, BitmapPixelFormat::Bgra8);
		auto inputBitmap = CanvasBitmap::CreateFromSoftwareBitmap(device, newBitmap);
		auto frameSize = inputBitmap->SizeInPixels.Width * inputBitmap->SizeInPixels.Height * 4;
		auto frameBuffer = ref new Windows::Storage::Streams::Buffer((unsigned int)frameSize);

		auto renderTarget = ref new CanvasRenderTarget(device, inputBitmap->SizeInPixels.Width, inputBitmap->SizeInPixels.Height, inputBitmap->Dpi);

		auto ds = renderTarget->CreateDrawingSession();
		ds->Clear(Colors::AntiqueWhite);
		renderTarget->GetPixelBytes(frameBuffer);

		SoftwareBitmap^ nxtBitmap = ref new SoftwareBitmap(BitmapPixelFormat::Bgra8, newBitmap->PixelWidth, newBitmap->PixelHeight);
		nxtBitmap->CopyFromBuffer(frameBuffer);
		SoftwareBitmap^ anBitmap = SoftwareBitmap::Convert(nxtBitmap, BitmapPixelFormat::Yuy2);
		anBitmap->CopyToBuffer(frameBuffer);
		// Copy the modified frame data to the output frame.
		context->OutputFrame->SoftwareBitmap->CopyFromBuffer(frameBuffer);

**Comment by damyanp** [comment]
You need to close the drawing session in order for it to be actually executed.  In C++/CX you close it using the "delete" keyword.  So if you modify your code to be more like this, then you should find that frameBuffer gets cleared to AntiqueWhite:

```
auto ds = renderTarget->CreateDrawingSession();
ds->Clear(Colors::AntiqueWhite);
delete ds;
renderTarget->GetPixelBytes(frameBuffer);
```

**Comment by dannyfarwin** [comment]
You are correct, and I did add that, but I still get a black frame.

**Comment by damyanp** [comment]
Can you inspect the contents of framebuffer after the call to GetPixelBytes (eg in a debugger) to confirm that GetPixelBytes did actually populate it correctly?  I'm afraid I'm having trouble following everything else that's going on in the code snippet without a more complete example to look at.

**Comment by dannyfarwin** [comment]
OK, the code I included is the entire processframe routine of the effect.

**Comment by dannyfarwin** [comment]
Ok, it is working now.  I had to force a rebuild on the entire project for some reason before the lib go updated.

Thanks
