### ISSUE TITLE
Difference between CanvasRenderTarget and CanvasCommandList

### ISSUE THREAD

**Issue by HIETE** [Microsoft/Win2D#530]
I find it hard to tell whether to use a CanvasRenderTarget or a CanvasCommandList.
I modified the documentation example (that uses a CanvasCommandList) to use a CanvasRenderTarget instead with the same output:

private void cac_CreateResources(Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
{
float width =(float) this.ActualWidth;
float height =(float) this.ActualHeight;

CanvasRenderTarget offscreen = new CanvasRenderTarget(sender, width, height, 96);
CanvasCommandList cl = new CanvasCommandList(sender);

using (CanvasDrawingSession ds = offscreen.CreateDrawingSession())
{
using (CanvasDrawingSession clds = cl.CreateDrawingSession())
{
for (int i = 0; i < 100; i++)
{

Vector2 position = RndPosition();
Color color = RndColor();

clds.DrawText("Hello, World!", position, color);
ds.DrawText("Hello, World!", position, color);
}
}
}

blur = new GaussianBlurEffect();
blur.Source = offscreen; //if we here use cl instead of offscreen the result is the same
blur.BlurAmount = 10.0f;
}

private void cac_Draw(Microsoft.Graphics.Canvas.UI.Xaml.ICanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedDrawEventArgs args)
{
float radius = (float)(1 + Math.Sin(args.Timing.TotalTime.TotalSeconds)) * 10f;
blur.BlurAmount = radius;
args.DrawingSession.DrawImage(blur);
}

**Comment by shawnhar** [comment]
The difference is that a rendertarget stores the pixel values which result from executing drawing commands, while a command list stores the original drawing commands and executes them on-demand whenever pixel values are needed.

A command list would be a better choice to reduce memory usage if the image dimensions are large, or if you don't yet know what resolution to draw the image at (perhaps you want to reuse it multiple times at a different resolution each time).

A rendertarget would be a better choice if you want to reuse the image many times without paying the cost of redrawing it every time.

**Comment by HIETE** [comment]
thank you for the explanation.
I'd like to understand better the "on-demand drawing of commands" for the specific example above please.
Here's what I've understood from your explanation:
(pseudo code summary of createresources):


using
{ 
drawtext etc
}
/*at this point the canvasrendertarget knows its pixel values, the command list doesn't know pixel values but remembers the commands*/

blur.Source = cl;  /*it is at this point that we have the on-demand execution of the command list and get its pixels.   Correct?*/




Or is it that the on-demand execution takes place in the draw method in the args.DrawingSession.DrawImage(blur);  line?

**Comment by shawnhar** [comment]
Conceptually you can imagine that command list rasterization takes place when you call DrawImage (assuming the thing you draw onto is itself some form of bitmap rather than another command list).

There are multiple levels of deferred execution beyond that (Direct2D queues up work until the drawing session is closed or flushed, and even after that, all GPU work is queued up for asynchronous execution that typically takes place long after the CPU has finished specifying it), but unless you are getting deep into GPU performance optimization, these details are not important to how you use a graphics API like Win2D.

**Comment by HIETE** [comment]
Thanks again.
I have two more questions, they are small and simple. Should I open a new issue or ask here?

**Comment by shawnhar** [comment]
Please create a separate issue per issue.  That way we can easily keep track of which questions have been answered vs. are still active etc.
