### ISSUE TITLE
Offscreen drawing with RenderTarget as effect source..

### ISSUE THREAD

**Issue by markmnl** [Microsoft/Win2D#531]
I am trying draw offscreen to a `CanvasRenderTarget `using another `CanvasRenderTarget `(which was drawn to from the previous draw call) as the input to a `PixelShaderEffect`. So similar to GaussianBlurEffect example in the documentation article: [Offscreen drawing](http://microsoft.github.io/Win2D/html/Offscreen.htm). However instead of newing up a `PixelShaderEffect `each draw I have the same effect created once because I am using a `CanvasAnimatedControl` with game loop.. 

So inside my Draw handler something like:

```
            myEffect.Source1 = myGraphicsEffectSource;
            using (var ds = myRenderTarget.CreateDrawingSession())
            {
                ds.DrawImage(myEffect, Vector2.Zero);
            }

            // re-assign effect source for next draw..
            myGraphicsEffectSource = myRenderTarget; 
```

On the second draw call I get the exception: 

> 'Cannot draw with a bitmap that is currently bound as the target bitmap. (Exception from HRESULT: 0x88990025)'

Is what I am trying to do possible? If so how?

I am guessing I need to copy the render target into another `CanvasBitmap `and use that one as the source on subsequent draw instead... I am worried of the performance implications of that as wouldn't that involve copying the bitmap from GPU memory to main memory only to be copied back again?

Thanks for any help in advance.

**Comment by shawnhar** [comment]
That error means you are trying to draw using the rendertarget as source image at the same time as you are in the middle of drawing onto it as the destination.  You can only do one of these things at a time.  Perhaps you are scoping your drawing sessions in such a way that they overlap?

**Comment by markmnl** [comment]
Yup that was it, and the code was like in my example, where the source is the render target on second invocation, duh!

Solution was to create two render targets, on tick draw to target1 using target2 as effect source (which is initialised) as effect source, then vice-versa on tock.
