### ISSUE TITLE
Question regarding the use of float versus double

### ISSUE THREAD

**Issue by HIETE** [Microsoft/Win2D#532]
I remember not long ago we used float where possible instead of double in our codes because at that time using float offered performance advantages.
But in modern computers double is at least as fast as float operations.

Win2D prefers float values. This forces us to have many double to float casts in our codes, as double is what we usually get from Math methods or even from properties such as this.ActualWidth

My question is why do most Win2D methods take float values instead of double.
Thank you.

**Comment by shawnhar** [comment]
The main reason Win2D uses float rather than doubles is that it is a hardware accelerated rendering API, and GPU hardware does not generally support double precision (or if it does, that comes with a major performance penalty).

**Comment by HIETE** [comment]
Thank you, I had no idea that GPUs are not double-friendly. I'm now reading that new GPUs have just 1 DP FPU for every 8 SP FPU (or 1 for every 2 in some cases).
Apparently all those double-float casts are unavoidable then :(
