### ISSUE TITLE
How to get current Mouse Position? 

### ISSUE THREAD

**Issue by DongkunLee** [Microsoft/Win2D#534]
I want to get current mouse positon(relative to screen), and Find out whether mouse is pointing Character. 

In win2D samples, The SpriteSheet Sample shows Absolute mouse positon. 

``` csharp 
var point = e.GetCurrentPoint((UIElement)sender).Position.ToVector2(); 
 ```

But, I have no Idea how to get reletive mouse position. 

I have made this code. But it doesn't work. 

``` csharp
            var rpoint = e.GetCurrentPoint(canvas).Position.ToVector2();
            

            // 사각형 길을 보여주기  
            if ((rpoint.X > wizardPosition.X - 64) && (rpoint.X < wizardPosition.X + 64) && (rpoint.Y > wizardPosition.Y - 150) && (rpoint.Y < wizardPosition.Y + 42) )
            {
                if (ShowBorder == true) { ShowBorder = false; }
                    
                 else if (ShowBorder == false)
                    ShowBorder = true; 
            }
```

Is there other way to get current position?

**Comment by DongkunLee** [comment]
I have solved myself. Thanks anyway

``' csharp
            var rpoint = e.GetCurrentPoint(this).Position.ToVector2();


            // Invert the display transform, to convert pointer positions into simulation rendertarget space.
            Matrix3x2 Mtransform;
            Matrix3x2.Invert(transform, out Mtransform);

            var xpoint = Vector2.Transform(rpoint, Mtransform);

            // 사각형 길을 보여주기  
            if ((xpoint.X > wizardPosition.X - 64) && (xpoint.X < wizardPosition.X + 64) && (xpoint.Y > wizardPosition.Y - 150) && (xpoint.Y < wizardPosition.Y + 42) )
            {
                if (ShowBorder == true) { ShowBorder = false; }
                    
                 else if (ShowBorder == false)
                    ShowBorder = true; 
            }

'''

**Comment by shawnhar** [comment]
Glad to hear you were able to figure this out.
