### ISSUE TITLE
Windows App Certification Kit fails with "Supported APIs"

### ISSUE THREAD

**Issue by choung** [Microsoft/Win2D#536]
App Target Windows Version:
10.0 Build 14393 (Anniversary Update)
Win2D Version:
1.21
Kit Version: 
10.0.14393.33

------------------
Supported API test

FAILED       Supported APIs

Error Found: The supported APIs test detected the following errors:
API GlobalLock in api-ms-win-core-heap-obsolete-l1-1-0.dll is not supported for this application type. Microsoft.Graphics.Canvas.dll calls this API.
API GlobalSize in api-ms-win-core-heap-obsolete-l1-1-0.dll is not supported for this application type. Microsoft.Graphics.Canvas.dll calls this API.
API GlobalUnlock in api-ms-win-core-heap-obsolete-l1-1-0.dll is not supported for this application type. Microsoft.Graphics.Canvas.dll calls this API.

Impact if not fixed: Using an API that is not part of the Windows SDK for Windows Store apps violates the Windows Store certification requirements. 

------------------

It seems Win2D is indeed using GlobalLock/GlobalSize/GlobalUnlock in "CanvasSvgDocument.cpp".
Any workaround? I don't need to use CanvasSvg* classes.

Thanks.

**Comment by shawnhar** [comment]
What version of the app certification kit are you using?  I published an updated Example Gallery to the Store (both 8.1 and 10 versions) at the same time as we released the latest Win2D update, and that passed cert without any trouble.  For the Win10 version this was using Visual Studio Tools for Universal Windows Apps version 15.0.26430.06.

**Comment by choung** [comment]
My Windows App Certification Kit version is 10.0.14393.33 and still using Visual Studio 2015 Community (Version 14.0.25431.01 Update 3); Visual Studio Tools for Universal Windows Apps version 14.0.25527.01.

Anyhow, according to GlobalLock and others doc (ex. https://msdn.microsoft.com/en-us/library/windows/desktop/aa366584(v=vs.85).aspx)

They're "desktop apps only" API's. Hence shouldn't those be ultimately removed from Win2D?

**Comment by shawnhar** [comment]
The APIs GlobalLock, GlobalUnlock, and GlobalSize are now valid for use in UWP, but it looks like the MSDN docs have not yet been updated to indicate that.

Upgrading to a more recent version of the App Certification Kit will get rid of the error you are seeing.

**Comment by choung** [comment]
Awesome! I was just worry about the compatibility issues related to using those APIs in Win2D. :-)
Thanks.
