### ISSUE TITLE
Rotate group of sprites and Matrix decompose

### ISSUE THREAD

**Issue by SeriousGeorge** [Microsoft/Win2D#538]
I know, the following is not directly a Win2D question, more a mathematically one, but maybe you can help anyway (and maybe also an integration of XNA’s Matrix3x2 decompose would be good too?)

I’m trying to rotate a group of sprites.
Easiest example would be a tank, rotating itself and its turret, also rotating itself.
_Expected Result:_ The turret should “sit” on its origin on top of it’s parent sprite (aka the tank) and rotate individually from it.

I first tried to get the localMatrix for each of the two sprites like this:
`  public Matrix3x2 LocalTransform(Sprite sp)
        {
            {
                // Transform = -Origin * Scale * Rotation * Translation
                return Matrix3x2.CreateTranslation((float)-sp.SpriteRect.Width / 2f,(float)-sp.SpriteRect.Height / 2f) *
                       Matrix3x2.CreateScale(sp.Scale) *
                       Matrix3x2.CreateRotation(sp.Rotation/60) *
                       Matrix3x2.CreateTranslation(sp.Position);
            }
        }
`

Then I thought I could multiply these both matrices like this:
`Matrix3x2 globalTransform = turret.Matrix*tank.Matrix;`

Finally I try to draw in a spritebatch like this:
` spriteBatch.DrawFromSpriteSheet(Bitmap, matrix, spriteRect, tint);`

But something is awfully off 😉

I saw an example with XNA here: [https://gamedev.stackexchange.com/questions/23034/is-there-a-simple-way-to-group-two-or-more-sprites-so-all-of-them-will-be-depen](url)
The solution was to decompose the matrix like this:
`public static void DecomposeMatrix(ref Matrix3x2 matrix, out Vector2 position, out float rotation, out Vector2 scale)
        {
            Vector2 position3, scale3;
            Quaternion rotationQ;
            matrix.Decompose(out scale3, out rotationQ, out position3);
            Vector2 direction = Vector2.Transform(Vector2.UnitX, rotationQ);
            rotation = (float)Math.Atan2(direction.Y, direction.X);
            position = new Vector2(position3.X, position3.Y);
            scale = new Vector2(scale3.X, scale3.Y);
        }
`

To cite from this ([https://gamedev.stackexchange.com/questions/4453/how-to-rotate-stacked-sprites-in-xna](https://gamedev.stackexchange.com/questions/4453/how-to-rotate-stacked-sprites-in-xna) ) thread:

> “… and when drawing the sprite you need to get the global transform by multiplying the current sprite's transform by its parents' (which I'm passing as a parameter), then decompose that transform into values that SpriteBatch can understand, and finally draw the children… “

There’s a decompose for a 4x4 Matrix, but none for 3x2. Is this intented? If yes, do I have to change all 3x2 matrices to 4x4 matrices?
I know it’s just a mathematically problem but maybe you have a hint of some.

Best regards
Andy

**Comment by shawnhar** [comment]
You could use the 4x4 matrix decompose for this, but I'm confused why that would be necessary.  Typically in a hierarchical object system you will only ever concatenate matrices, but never need to decompose them.  The trick is to store your child objects (like the turret of the tank) relative to the coordinate system of their parent, rather than in absolute world coordinate system.  So if you have one transform matrix for the tank, and another for the turret, you draw the turret using (turretMatrix*tankMatrix).   That way if you leave the turretMatrix set to identity and only change the tankMatrix, both tank and turret move together.  Add a rotation into the turretMatrix, and the turret turns while remaining attached to the tank. etc.

**Comment by SeriousGeorge** [comment]
Thanks for the hint with the matrix multiplication. I used that before, but the mistake I made, was adding up an offset to the parentsprite in each frame, which caused the whole matrix multiplication to go sideways.

I fixed that now and like in your example, the multiplication now behaves correctly.

Thanks for pointing in the right direction!
