### ISSUE TITLE
Incorrect picture in CanvasTextLayout.DrawBounds documentation

### ISSUE THREAD

**Issue by pleaseking** [Microsoft/Win2D#54]
The picture in http://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_CanvasTextLayout_DrawBounds.htm seems not aligned with the text and illustrates something different.

**Comment by pleaseking** [comment]
Same for LayoutBounds: http://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_CanvasTextLayout_LayoutBounds.htm

**Comment by clandrew** [comment]
Thanks for opening this issue. This is an unusual one! I've opened an internal issue and we should be able to get to it soon.

**Comment by shawnhar** [comment]
This is fixed in 0.0.16, which we released today.

Thanks for the report!
