### ISSUE TITLE
CompositionSurfaceBrush isn't DPI aware and doesn't render at the right size

### ISSUE THREAD

**Issue by Sergio0694** [Microsoft/Win2D#540]
Hello, I wrote my own implementation of the acrylic brush so that it runs on the Creator's Update, and I'm having some issues with the `BorderEffect` (used for the noise layer on top) and the `CompositionSurfaceBrush` used for each tile (the noise texture) on high-DPI screens.

[**This is the source code**](https://github.com/Sergio0694/UICompositionAnimations/blob/master/UICompositionAnimations/Helpers/Win2DImageHelper.cs#L99) for the method that loads the image into a `CompositionSurfaceBrush`.

I'm using a 600\*600 texture loaded into a `CanvasBitmap` image with the same DPI setting as the current screen (I'm using `DisplayInformation.LogicalDpi` for that), then I create a `CompositionDrawingSurface` with the same pixel size (600\*600) and a `CanvasDrawingSession` at 600\*600, with the same DPI as well.

After drawing the bitmap onto the surface, I end up with a nice 600\*600 image, but when I use that surface to create a `CompositionSurfaceBrush`, it seems that composition surface doesn't keep any DPI information, so when I pass that brush to the `BorderEffect` [it effectively renders the brush as 600\*600 DIP instead of 600\*600 pixels.
](http://i.pi.gy/nQdA.png)

I also tried to just set the right DPI value to the source `CanvasBitmap`, but leaving the `CanvasDrawingSession` at the default DPI value results in a [200\*200 DIP surface with the image that's being downscaled to 200\*200 pixels](http://i.pi.gy/wdZ4.png) and then stretched as it's being rendered onto 200\*200 DIP (here the DPI value is 288, I'm on a Lumia 950XL at 300% scaling).

**I've already found a solution**, and that is to scale the brush so that it's matched at a 1:1 size:

```csharp
CompositionSurfaceBrush brush = surface.Compositor.CreateSurfaceBrush(surface);
brush.Stretch = CompositionStretch.None;
double pixels = DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel;
if (pixels > 1)
{
    brush.Scale = new Vector2((float)(1 / pixels));
    brush.BitmapInterpolationMode = CompositionBitmapInterpolationMode.NearestNeighbor;
}
````
And this results in each tile in the `BorderEffect` [**perfectly rendered at 600\*600 pixels**](http://i.pi.gy/0J3d.png), so that the original 600\*600 image is being displayed at its actual size.

### So then what is the question?

Using the `Scale` property on the `CompositionSurfaceBrush` looks like a trick and I'm not sure that's the optimal solution to this problem, **is there another way to actually set the right DPI value to the brush so that it's rendered correctly at its original pixel size?** I've also looked into the `DpiCompensationEffect` that seemed promising, but it isn't supported in the Composition APIs yet so I can't use it in my acrylic effect pipeline.

Thank you for your help! 😄

**Comment by shawnhar** [comment]
The behavior you are seeing is expected.  Unlike XAML or Win2D (and also Direct2D, which Win2D is built on top of), the Windows.UI.Composition APIs such as CompositionSurfaceBrush do not have an explicit concept of DPI as being a different thing from scale and resolution.  It's up to you to scale graphics however you need when using these composition APIs.

**Comment by Sergio0694** [comment]
Hello @shawnhar - thank you for your answer.
I saw the Win2D/Composition docs and I figured that was the reason why that was happening, but I wasn't sure that manually setting the stretch of the `CompositionSurfaceBrush` was the recommended approach in order to fix this problem, thanks!
