### ISSUE TITLE
FromSoftwareBitmap doesn't work with SoftwareBitmap with AlphaMode = Straight

### ISSUE THREAD

**Issue by LanceMcCarthy** [Microsoft/Win2D#544]
The `InputFrame.SoftwareBitmap` and `OutputFrame.SoftwareBitmap` on an `IBasicVideoEffect` ProcessFrame() method are not compatible with `RenderTargetBitmap.FromSoftwareBitmap`, it throws an invalid pixel format exception.

My suspicion is because of the SoftwareBitmap's Alpha is set to `Straight` instead of `PreMultiplied`, preventing a DirectXPixelFormat match.

To help you reproduce it, start with [the Win2D demo I contributed to the example](https://github.com/Microsoft/Win2D/blob/master/samples/ExampleGallery/Effects/DynamicBlurVideoEffect.cs)s, but force `SoftwareBitmap` frames by setting `SupportedMediaMemoryType` to `Cpu` instead of `Gpu`.

In RenderFrame, use my current workaround code to get it up and running:

```
if (context.InputFrame.Direct3DSurface == null)
{
        // InputFrame's raw pixels
    byte[] inputFrameBytes = new byte[4 * context.InputFrame.SoftwareBitmap.PixelWidth * context.InputFrame.SoftwareBitmap.PixelHeight];
    context.InputFrame.SoftwareBitmap.CopyToBuffer(inputFrameBytes.AsBuffer());

    using (var inputBitmap = CanvasBitmap.CreateFromBytes(
        _canvasDevice,
        inputFrameBytes,
        context.InputFrame.SoftwareBitmap.PixelWidth,
        context.InputFrame.SoftwareBitmap.PixelHeight,
        DirectXPixelFormat.B8G8R8A8UIntNormalized))
    using (var renderTarget = new CanvasRenderTarget(
        _canvasDevice,
        context.OutputFrame.SoftwareBitmap.PixelWidth,
        context.OutputFrame.SoftwareBitmap.PixelHeight,
        (float)context.OutputFrame.SoftwareBitmap.DpiX,
        DirectXPixelFormat.B8G8R8A8UIntNormalized,
        CanvasAlphaMode.Premultiplied))
	{
		using (var ds = renderTarget.CreateDrawingSession())
        {
            var effect = new GaussianBlurEffect
            {
                Source = inputBitmap,
                BlurAmount = Amount,
                Optimization = EffectOptimization.Speed
            };

            ds.DrawImage(effect);
        }
		
  
	}
}
```

After seeing that this works, try this instead of `CreateFromBytes`:

`using (var inputBitmap = CanvasBitmap.FromSoftwareBitmap(_canvasDevice, context.OutputFrame.SoftwareBitmap)`

You will see the exception occur.

[Edited on 8-17-2017: Removed copy to OutputFrame, it's unneccesary]

**Comment by damyanp** [comment]
Yes, CanvasRenderTargets do not support Straight alpha. See http://microsoft.github.io/Win2D/html/PixelFormats.htm for a list of supported pixel formats.

I'll get in touch with the owners of the video effects APIs to see if they have any other suggestions.

**Comment by damyanp** [comment]
There are plans to improve the interaction between Media Capture, Software Bitmap and Win2D in a future release of Windows, but in the meantime you can use your workaround or the SoftwareBitmap.Convert method.

**Comment by LanceMcCarthy** [comment]
Thanks for circling back Damyan! I wasn't aware of the `SoftwareBitmap.Convert` method. I'll try that and see if it offers better performance.

**Comment by LanceMcCarthy** [comment]
It turns out that the same problem occurs with `SoftwareBitmap.Convert`, [here's a screenshot of the Exception at run-time](https://www.screencast.com/t/G2Pfzq3RBJ).

I'll stick with copying out the pixels into a `byte[]` and use `CanvasBitmap.CreateFromBytes` until there is a built-in fix. I'm just concerned when this is used on different devices with different cameras that supply different pixel formats.
