### ISSUE TITLE
Memory Leak using Win2D CanvasDrawingSession

### ISSUE THREAD

**Issue by dannyfarwin** [Microsoft/Win2D#545]
I am working on overlaying a time stamp on an image, but am running into a memory leak issue whenever I try to use DrawImage or DrawText in a CanvasDrawingSession.  This leak becomes significant over time, and if I comment out the DrawImage and DrawText, the leaks disappears.  I must be missing some aspect of resource releasing but am not seeing it.

		virtual void ProcessFrame(ProcessVideoFrameContext^ context)
		{
			time_t curtime = time(0);
			char buffer[16];
			struct tm info;
			localtime_s(&info, &curtime);
			strftime(buffer, sizeof(buffer), "%H:%M:%S", &info);
			std::string stime = std::string(buffer);
			std::wstring w_str = std::wstring(stime.begin(), stime.end());
			String^ sTime = ref new String(w_str.c_str());
			CanvasDevice^ device = ref new CanvasDevice();
			auto newBitmap = SoftwareBitmap::Convert(context->InputFrame->SoftwareBitmap, BitmapPixelFormat::Bgra8);

			auto inputBitmap = CanvasBitmap::CreateFromSoftwareBitmap(device, newBitmap);
			auto frameSize = inputBitmap->SizeInPixels.Width * inputBitmap->SizeInPixels.Height * 4;
			auto frameBuffer = ref new Windows::Storage::Streams::Buffer((unsigned int)frameSize);

			auto renderTarget = ref new CanvasRenderTarget(device, (float)inputBitmap->SizeInPixels.Width, (float)inputBitmap->SizeInPixels.Height, (float)inputBitmap->Dpi);

			auto ds = renderTarget->CreateDrawingSession();
	//		ds->DrawImage(inputBitmap);

			auto format = ref new CanvasTextFormat();
			format->FontFamily = _fontFamily;
			format->FontSize = (float)_fontSize;
	//		ds->DrawText(sTime, (float)_offsetX, (float)_offsetY, _fontColor, format);
			delete ds;

			renderTarget->GetPixelBytes(frameBuffer);
			
			SoftwareBitmap^ nxtBitmap = ref new SoftwareBitmap(BitmapPixelFormat::Bgra8, newBitmap->PixelWidth, newBitmap->PixelHeight);
			nxtBitmap->CopyFromBuffer(frameBuffer);
			SoftwareBitmap^ anBitmap = SoftwareBitmap::Convert(nxtBitmap, BitmapPixelFormat::Yuy2);
			anBitmap->CopyToBuffer(frameBuffer);

			// Copy the modified frame data to the output frame.
			context->OutputFrame->SoftwareBitmap->CopyFromBuffer(frameBuffer);

			delete format;
			delete nxtBitmap;
			delete anBitmap;

			delete inputBitmap;
			delete frameBuffer;
			delete renderTarget;

			delete sTime;
			delete device;
			delete newBitmap;
		}
``

**Comment by damyanp** [comment]
Hi - I'm afraid that I too am unable to see anything obvious missing here.

I did notice that you're creating a new CanvasDevice each time that this is called.  This is a pretty heavyweight operation and is something you should avoid doing any more than necessary.  You might find that [CanvasDevice.GetSharedDevice](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasDevice_GetSharedDevice.htm) is a better way to do this.  You may find also that this knocks things the right way so that the leak goes away.

Also, does the leak only go away if you comment out both of DrawText and DrawImage?  Or is it one of these in particular that triggers it?

**Comment by dannyfarwin** [comment]
Either DrawImage or DrawText causes the issue.  You were correct, I changed the CanvasDevice to a global created only once and the leak seemed to go away.  I still need to find a way to do this with the hardware device interface instead of the software rendering.
