### ISSUE TITLE
Difficulty running two asynchronous Effects based on Win2d Gpu mode

### ISSUE THREAD

**Issue by dannyfarwin** [Microsoft/Win2D#546]
I have two effects written with Win2d on a UWP app, one a timestamp overlay and the other a composite effect.  The timestamp continuously runs while the composite can be executed at random.  I can do this in cpu software rendering mode, but when I try to utilize Gpu mode, it appears there is interaction between effects corrupting the CanvasDevice of the continuous effect when I remove the transient effect from the result causing an exception.  Is such a usage possible, or am I pushing this too far?

**Comment by damyanp** [comment]
I'm afraid I can't quite follow the scenario you're describing.

I can say that you should avoid multiple threads accessing the same CanvasDevice.  You can either use locking around the device or explicitly use a different device for each thread.  It sounds like in your case you need to use a different device per thread.

I'm not sure if what you're doing involves multiple threads though.

**Comment by dannyfarwin** [comment]
Yes, it is threaded.  I am getting the device in each effect module using: 
	_canvasDevice = CanvasDevice::CreateFromDirect3D11Device(device);
Does this device need some kind of mutex??

**Comment by damyanp** [comment]
Assuming that "device" is the same D3D11Device, then yes, you should avoiding using this device at the same time from multiple threads.

**Comment by dannyfarwin** [comment]
I think I know what the issue is, I need to convert the output of the effect to YUY2 output surface format.  I can use softwarebitmap to do the convert, but how do I get it back to the Direct3DSurface?  The RenderTarget does not support YUY2 as far as I know.

**Comment by shawnhar** [comment]
Win2D cannot render onto YUV2 format surfaces.

**Comment by dannyfarwin** [comment]
Yes, I understand that which is why I specify effect input as bgra8.  This works, but the effect pipeline expects  yuy2 on return it would seem the topology engine in media capture would take care of this

**Comment by 13thsymphony** [comment]
When you say effect pipeline are you talking about implementing a custom IBasicVideoEffect (https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/custom-video-effects)?

The IBasicVideoEffect documentation says that you must explicitly declare what pixel formats you support, and for Win2D/Direct2D you must enter "ARGB32" (which is equivalent to the BGRA32 pixel format).

`public IReadOnlyList<VideoEncodingProperties> SupportedEncodingProperties {
    get
    {
        var encodingProperties = new VideoEncodingProperties();
        encodingProperties.Subtype = "ARGB32";
        return new List<VideoEncodingProperties>() { encodingProperties };
    }
}`

**Comment by dannyfarwin** [comment]
Yes, I am doing that but the system wants yuy2 returned

**Comment by 13thsymphony** [comment]
This goes out of our area of expertise - we'll have to ask the team that owns the media effects API. I wasn't aware of cases where the pipeline requires that the custom effect implementer support YUY2. Do you have a repro project you can share?

**Comment by dannyfarwin** [comment]
I will put together a sample of the issue

**Comment by shawnhar** [comment]
I'm closing this issue due to lack of repro.   Feel free to reactivate if you're able to provide one!
