### ISSUE TITLE
Getting "No such interface supported" on CreateLayer call

### ISSUE THREAD

**Issue by dannyfarwin** [Microsoft/Win2D#547]
I am trying to create a layer with an opacity value to overlay on main image.  When I call drawing Session->CreateLayer(opacity) I get the No such interface supported message at run time.  If I remove this statement, all runs fine.  How am I supposed to implement this?

		virtual void ProcessFrame(ProcessVideoFrameContext^ context)
		{
			IDirect3DSurface^ outputSurface = context->OutputFrame->Direct3DSurface;

			if (outputSurface == nullptr || _overlayBitmap == nullptr)
				return;

			CanvasRenderTarget^ renderTarget = CanvasRenderTarget::CreateFromDirect3D11Surface(_device, outputSurface);
			CanvasDrawingSession^ drawingSession = renderTarget->CreateDrawingSession();
			auto layer = drawingSession->CreateLayer((float)1);
			drawingSession->DrawImage(_overlayBitmap, (float)_offsetX, (float)_offsetY);
			delete layer;
``
Exception thrown at 0x00007FF9DCB49E08 in ViewVaultLC.exe: Microsoft C++ exception: Platform::InvalidCastException ^ at memory location 0x00000089007FEF20. HRESULT:0x80004002 No such interface supported
WinRT information: No such interface supported

**Comment by damyanp** [comment]
I'm afraid I don't see anything obviously wrong from the code snippet you've included.  Can you confirm that the "Layers" example in Example Gallery works on your machine?

Assuming it does, the next step would be to try and send us a more minimal example project that has this issue.

(Alternatively, you could build the Win2D from source yourself and debug into the CreateLayer implementation to see if you can narrow down where the E_NOINTERFACE is coming from).

**Comment by dannyfarwin** [comment]
Ok, I found what the issue was.  I had updated the version of Win2D on the runtime component but failed to upgrade it on the main module so there was a mismatch between them.
