### ISSUE TITLE
Windows App Certification Kit Failure since 1.21.0

### ISSUE THREAD

**Issue by Petititi** [Microsoft/Win2D#549]
Hi,
since the last release (1.21.0), the certification fail on `Supported API test`:
```
◦API GlobalLock in api-ms-win-core-heap-obsolete-l1-1-0.dll is not supported for this application type. Microsoft.Graphics.Canvas.dll calls this API.
◦API GlobalSize in api-ms-win-core-heap-obsolete-l1-1-0.dll is not supported for this application type. Microsoft.Graphics.Canvas.dll calls this API.
◦API GlobalUnlock in api-ms-win-core-heap-obsolete-l1-1-0.dll is not supported for this application type. Microsoft.Graphics.Canvas.dll calls this API.
```

Any idea how to fix this?

Thanks

**Comment by shawnhar** [comment]
You are using an outdated version of the certification kit.

**Comment by Petititi** [comment]
Ok, thanks!

**Comment by Petititi** [comment]
I reopen this as we finally conclude that this is not the solution: if we update the certification kit, we have to move to VS2017 which is not an option for us (app certif doesn't pass if builded with an older winSDK).
So to conclude, we can't publish an app with Win2D 1.21.0 if builded with VS2015... Any hopes that you will change something to get compatibility back to VS2015?

**Comment by shawnhar** [comment]
The latest version of Win2D is compatible with VS2015, just not with older versions of the certification kit.  You could build your app with 2015, then validate it using a newer version of the kit.  Or you could just ignore this error when running the older cert kit - whatever outdated checks you run locally won't block publishing to the store.

**Comment by Petititi** [comment]
OK, thanks!
Our build server doesn't want to validate our package, even with the latest version, but store validation run smoothly! I will inform our integration team to check the validation tool integrity !

Thanks again!
