### ISSUE TITLE
Crash when restarting driver

### ISSUE THREAD

**Issue by Petititi** [Microsoft/Win2D#550]
Hi all!
I try to reduce the crashes we have on windows store, and one of the biggest occurrences seems to be related to Win2D (`NULL_POINTER_READ_c0000005_Microsoft.Graphics.Canvas.dll!std::_Func_impl_class__lambda_491a23a49d7f6483da2a7c68c9e59d89_,class_std::allocator_int_,void,struct_ABI::Microsoft::Graphics::Canvas::ICanvasDevice_*___ptr64,enum_ABI::Microsoft::Graphics::Canvas::UI::Xaml::RunWithDeviceFlags_::_Do_call`).
In order to reproduce this, I created a very simple program which draws line each 100ms, then restart the driver thanks to dxcap (`dxcap.exe -forcetdr`).
It then crash due to a null pointer.

Please tell me if you need more informations.
[SampleCrash.zip](https://github.com/Microsoft/Win2D/files/1260515/SampleCrash.zip)

**Comment by shawnhar** [comment]
hmm, I don't see any crash from this sample app.  With native debugging enabled, there are a bunch of first chance exceptions from inside d3d11.dll and then inside Win2D, which are handled as expected, and then the app recovers and resumes rendering its lines.

What OS, GPU and driver are you using?  (I'm currently running Windows build 15063, on an NVIDIA GTX 950 with driver 22.21.0013.8165).

**Comment by Petititi** [comment]
Thanks for this quick feedback!
I'm using a surface pro 3 (windows 15063.540), Intel HD Graphic 5000 (driver 20.19.15.4568), but from windows store, this problem seems to occurs also on SURFACE PRO 2017, Surface Pro 4, Surface Pro 3, Surface Pro, Galaxy Book 12 LTE, Galaxy Book 10.6 and some other LENOVO and ASUS devices...

**Comment by Petititi** [comment]
Indeed, there is something strange. Today, the sample on the same device run without problems... I'm missing something. Will reopen this once I have a 100% reproduction.
