### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#552]
I am working with Window 10 pro where I have to change V140 to V141. I have changed SDK 10.0.15063.0 but still I am unable to compile.  

Metadata file 'c:\win2d-master\bin\uapx86\debug\winrt.dll.uap\Microsoft.Graphics.Canvas.winmd' could not be found         
Cannot open include file: 'win2d.etw.h': No such file or directorywinrt.dll.uap           
Why I am unable to compile?
I am not working on win phone.

**Comment by shawnhar** [comment]
I need more information to understand what you are doing here.  Are you trying to compile an app using Win2D, or to compile Win2D itself?  Please describe what version of Win2D you are using, and what version of Visual Studio, and what lines of which files you have changed, and how you are attempting to compile it.

**Comment by AghaKhan** [comment]
https://1drv.ms/f/s!AtjIdnVOoJXtoadGL0uCX-09_pd8vA


[https://mwhq1g-dm2306.files.1drv.com/y4m597y-Bq3QjzljyFHZCewS3x8pr4ULeXApzvNN1kDGZ18mZOo3_tNAg6PRHYPv20XVxTolCafFPZZhHsxsPNYukJLZmhfi2v-z5SZzgdOA-fdtnbni5m5s4Wx9S-5XcsXecyGWxTkirjF0fhv7P0yhfxcj5CU5wTtpluWQNHLMKk]<https://1drv.ms/f/s!AtjIdnVOoJXtoadGL0uCX-09_pd8vA>

[imageData318551]<https://1drv.ms/f/s!AtjIdnVOoJXtoadGL0uCX-09_pd8vA>
MSFTUWP<https://1drv.ms/f/s!AtjIdnVOoJXtoadGL0uCX-09_pd8vA>
Shared via OneDrive



Dear Shawn Hargreaves:

After updating Window 10 pro I am unable to compile.

Kindly look the video.

I didn't change anything in the project. Just download nothing else.

It complains about Window phone sdk, but I am not using it, so it should not effect it.


Best regards

Agha Khan




________________________________

**Comment by shawnhar** [comment]
Please answer my questions:

1. Are you trying to compile an app using Win2D, or to compile Win2D itself?
2. Please describe what version of Win2D you are using
3. and what version of Visual Studio
4. and exactly how you are attempting to compile it

**Comment by AghaKhan** [comment]
1.  Are you trying to compile an app using Win2D, or to compile Win2D itself?
I am compiling Win2D source code.

  1.  Please describe what version of Win2D you are using
I downloaded from https://github.com/microsoft/win2d
And I think this is the latest version.


  1.  and what version of Visual Studio
Visual Studio Community 2017

Microsoft Visual Studio Community 2017
Version 15.3.2
VisualStudio.15.Release/15.3.2+26730.10
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA748
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA748
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA748
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA748
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.8.00712.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30726.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Template Engine 2017   15.0.30726.0
ASP.NET Template Engine 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50601.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30728.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.9000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Data Lake Tools for Visual Studio   2.2.9000.1
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   3.0.17208.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2017.2    Build 109.0.20170824.131346
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure HDInsight Azure Node   2.2.9000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.2.9000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   1.7
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.2.9000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50719.1

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.6.8-pre (ec7034f)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.0.0.0
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2017 ENU   15.0.26712
Microsoft Office Developer Tools for Visual Studio 2017 ENU

Python   3.0.17208.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   3.0.17208.1
Provides templates and integration for the Django web framework.

Python - IronPython support   3.0.17208.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   3.0.17208.1
Profiling support for Python projects.

SQL Server Data Tools   15.1.61707.200
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.3.4.0
TypeScript tools for Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Apache Cordova   15.120.6728.1
Visual Studio Tools for Apache Cordova

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

Visual Studio Tools for Unity   3.3.0.2
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.26730.08
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.
WebJobs Tools v1.0.0   __RESXID_PRODUCTVERSION__
WebJobs Tools v1.0.0
Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.
Xamarin   4.6.0.299 (b63523e27)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
Xamarin.Android SDK   7.4.0.21 (2851083)
Xamarin.Android Reference Assemblies and MSBuild support.
Xamarin.iOS and Xamarin.Mac SDK   10.12.0.20 (80b8487)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

  1.  and exactly how you are attempting to compile it

Please just look the video. Download, update V140 to v141. And hit compile.

Thanks for prompt reply.

Best regards
Agha


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by shawnhar** [comment]
I am confused by these statements:

> I didn't change anything in the project. Just download nothing else.

> Download, update V140 to v141. And hit compile. 

Sounds like you /did/ change the project to use a different set of build tools?

I am guessing you did this from the Visual Studio UI?  That won't do the right thing for the Win2D build system - instead you need to update this by hand in Win2D.cpp.props.  But, switching to different build tools is a significant change that might require other updates to match.  I have not yet tried building Win2D with 141 so don't know for sure.

Rather than changing Win2D to use the 141 build tools, I recommend installing 140 so you can build Win2D the same way it is currently set up for.  According to https://developercommunity.visualstudio.com/content/problem/48806/cant-find-v140-in-visual-studio-2017.html, there is currently a bug in adding the 140 tools to VS 2017 - suggested workaround is to install VS 2015 Update 3 alongside 2017.

**Comment by AghaKhan** [comment]
Thank you for kind reply.

I was not aware that we have to change by hand. I just thought I should change V140 to V141. Does this not obvious?
I think that is the problem.

Best regards
Agha

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
