### ISSUE TITLE
Win2d 1.21.0 for Win8.1 doesn't support SVG?

### ISSUE THREAD

**Issue by omanuke** [Microsoft/Win2D#554]
I read this [this blog](https://blogs.msdn.microsoft.com/win2d/2017/06/26/win2d-1-21-0-svg-improved-hdr-support-and-bugfixes/) and tried to use SVG functionality, but Microsoft.Graphics.Canvas.dll seems it doesn't have SVG namespace.
This feature works in UWP only? Or I did something wrong?

**Comment by shawnhar** [comment]
> This feature works in UWP only? 

Correct.  SVG functionality was added to Direct2D in Windows 10 Creators Update.  It is not available on older versions of Windows 10, let alone 8.1.

**Comment by omanuke** [comment]
I got it.
