### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#555]
It worked well with Visual Studio 2015 (V140) but it stop working with Visual Studio 2017. Visual Studio 2017 provided build in tool where you can update to new version (V141) but after that it doesn't compile. You will also notice it will also complain about Window 8.1 project about SDK, but you may ignore that error, because we are not working with Window 81.1. Here is the link https://1drv.ms/v/s!AtjIdnVOoJXtodVRuSdqWIzLcw7OCQ for the video to see how I tried to build. 
https://1drv.ms/f/s!AtjIdnVOoJXtoadGL0uCX-09_pd8vA (This is link for the folder).
Please also note Visual Studio 2015 is NOT available, even there are may links are available, but at the end they direct back to Visual Studio 2017 download.
Thanks for help
Agha

**Comment by shawnhar** [comment]
This is the same question as your previous issue #552.   A suggested solution was already given there:

> Rather than changing Win2D to use the 141 build tools, I recommend installing 140 so you can build Win2D the same way it is currently set up for. According to https://developercommunity.visualstudio.com/content/problem/48806/cant-find-v140-in-visual-studio-2017.html, there is currently a bug in adding the 140 tools to VS 2017 - suggested workaround is to install VS 2015 Update 3 alongside 2017.

According to a web search I did just now, Visual Studio 2015 is available at https://www.visualstudio.com/vs/older-downloads/

**Comment by AghaKhan** [comment]
Thank you for prompt reply.
https://1drv.ms/f/s!AtjIdnVOoJXtoadGL0uCX-09_pd8vA
Even Installing v140, it does not work with Visual Studio 2017. Please watch the video. 
I installed Visual Studio 2015, but I am unable to compile it, but I received a message that new version of Visual Studio is required.  
Please see the VisualStudio2015Error.png in above  link.
Best regards

**Comment by shawnhar** [comment]
The Win2D.uwp solution compiles with Visual Studio 2017, using the 140 tools.  According to the link I found above, just installing 2017 is not enough to get working 140 tools, so you need to install 2015 as well.  Once you've installed this you should build in 2017 though, not 2015.

**Comment by AghaKhan** [comment]
Thank you shawnhar:
It did work.
Best regards
