### ISSUE TITLE
Problem with CanvasTextAntialiasing

### ISSUE THREAD

**Issue by pleaseking** [Microsoft/Win2D#56]
One more question here: when I try to render text with `CanvasDrawingSession::TextAntialiasing` set to `CanvasTextAntialiasing::ClearType`, I get nothing rendered - at least using CanvasRenderTarget. All other options for `TextAntialiasing` work just fine.

**Comment by clandrew** [comment]
Thanks for letting us know. I just rendered some text in ExampleGallery with the text antialiasing mode set to ClearType, and text shows up normally.

Could you provide a repro, or more information about your code?

**Comment by pleaseking** [comment]
I can try to minimize it just copying-pasting some code:

    m_renderTarget = ref new CanvasRenderTarget(canvasControl, m_nWidth, m_nHeight,
		DirectX::DirectXPixelFormat::B8G8R8A8UIntNormalized, CanvasAlphaMode::Premultiplied, 96);
and then

    auto ds = m_renderTarget ->CreateDrawingSession();
    ds->TextAntialiasing = CanvasTextAntialiasing::Grayscale;
    ds->Clear(Windows::UI::Colors::Transparent);
    ds->DrawTextLayout(pTextLayout, rt.left, rt.top,
		Windows::UI::ColorHelper::FromArgb(opacity, red, green, blue));
    delete ds;

I have actually just found this note - maybe it shades some light - but I am not sure how to invoke the function mentioned in Win2D context: https://msdn.microsoft.com/en-us/library/windows/desktop/dd756766(v=vs.85).aspx#cleartype_and_alpha_modes .

**Comment by shawnhar** [comment]
Odd - like Claire I am not able to repro this issue.

I made a new Windows C# XAML application, added a CanvasControl inside the Grid provided by the template, and put this code in its Draw event handler:

        void CanvasControl_Draw(CanvasControl sender, CanvasDrawEventArgs args)
        {
            var layout = new CanvasTextLayout(sender, "Hello", new CanvasTextFormat(), 200, 200);

            using (var rt = new CanvasRenderTarget(sender, 1024, 1024, DirectXPixelFormat.B8G8R8A8UIntNormalized, CanvasAlphaMode.Premultiplied, 96))
            {
                using (var ds = rt.CreateDrawingSession())
                {
                    ds.TextAntialiasing = CanvasTextAntialiasing.ClearType;
                    ds.Clear(Colors.Transparent);
                    ds.DrawTextLayout(layout, 100, 100, Colors.Red);
                }

                args.DrawingSession.DrawImage(rt);
            }
        }

The text is visible regardless of what antialiasing mode I specify...

**Comment by pleaseking** [comment]
OK I think I traced down the problem: 
   * I am rendering to `CanvasRenderTarget` as I described
   * but THEN instead of using `DrawImage` to render the target somewhere else, I am taking its byte buffer and copying pixel-by-pixel to my BMP565 buffer (as described in #57)
   * it seems from the link I posted before that ClearType and transparent background do not work very well together - and as this particular bitmap contains nothing but text on transparent background - nothing is drawn
    * on the contrary, when using `DrawImage`, the actual font rendering happens on non-transparent surface - and thus ClearType performs well (tried this - it works)

Not sure if it makes sense - my understanding of Direct2D/DirectX is very limited - but this is the only idea making sense for me now.

Not sure if you want to document that or not..

**Comment by shawnhar** [comment]
How do you deal with alpha conversions during this 8888 -> 565 format conversion?   Since the source format has alpha but the dest does not, I don’t understand how that can work if your source image relies on alpha (such as having a transparent background).

**Comment by pleaseking** [comment]
In this particular case I do not _convert_, but I bit-blit 8888 onto 565 preserving transparency. So 565 is assumed to be opaque, and 8888 can be transparently drawn on top. Basically I am trying to emulate text being drawn on top of opaque background - just instead of drawing it directly, I draw text outline "in the vacuum" (and this is the piece that does not seem to work with ClearType) and then apply it to the background. 

I can post the real code... A lot of macro though.

**Comment by clandrew** [comment]
In general, the guidance coming from Direct2D, is:
*...rendering ClearType text to a transparent surface can create unpredictable results.*  [(Source)](https://msdn.microsoft.com/en-us/library/windows/desktop/dd368058%28v=vs.85%29.aspx]). 

A workaround is to use Win2D's CreateLayer with a Clear(someOpaqueColor) inside the layer and then draw your text to the layer. Or, put an opaque FillRectangle behind the text. Do either of these work? If the ClearType-on-a-transparent-background is indeed what's causing your text to disappear, then we might be able to make this more clearly messaged in Win2D.

Although, I'm also interested in Shawn's point about alpha in the format conversion, in the bigger context of your app.

**Comment by shawnhar** [comment]
Win2D uses premultiplied alpha.  Guess – are you assuming straight (linear) alpha during your blending code?

**Comment by pleaseking** [comment]
I think more clear messaging in Win2D docs of ClearType transparent background limitation would be good. FillRectangle approach works very well too, thanks.

As for alpha - yes I was assuming linear it seems, switched to assuming premultiplied, got better results but performance hell, and raised priority to migrate to 8888 buffer - seems the only reasonable choice.

Thanks for the replies!

**Comment by clandrew** [comment]
Glad this fixed your issue. 

I opened an internal issue for us to make the ClearType/transparent background behavior less surprising, either through a code change or doc change.
