### ISSUE TITLE
CanvasRenderTarget question

### ISSUE THREAD

**Issue by VoteForPedro** [Microsoft/Win2D#561]
Hello,  
my question is about drawing inks into CanvasVirtualControl

CanvasRenderTarget init:

```

        private void Canvas_CreateResources(CanvasVirtualControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
        {
            renderTarget = new CanvasRenderTarget(canvas, (float) this.grid.ActualWidth, (float) grid.ActualHeight, canvas.Dpi);
        }

```

Draw function
```
                // draw ink to renderTarget
                using (var s = renderTarget.CreateDrawingSession())
                {
                    s.Clear(Colors.Transparent);
                    s.DrawInk(dry);                    
                }

               // draw renderTarget to canvas
            using (var s =
                canvas.CreateDrawingSession(new Rect(0, 0, renderTarget.Bounds.Width,
                    renderTarget.Bounds.Height)))
            {
              
                s.DrawImage(renderTarget);
            }
```

What is expected: 
ink stroke drawn in the canvas

What i get: 
first stroke drawn as expected, second clears previous one

it seems like canvas and render target shares same 2d surface

changing renderTarget initialization to another CanvasDevice i.e

```
renderTarget = new CanvasRenderTarget(new CanvasDevice(), (float) this.grid.ActualWidth, (float) grid.ActualHeight, canvas.Dpi);
```

causes exception

Objects used together must be created from the same factory instance.

?

**Comment by VoteForPedro** [comment]
Moving drawing code to Canvas_RegionsInvalidated works 
(old was - InkPresenter_StrokesCollected)

```
private void Canvas_RegionsInvalidated(CanvasVirtualControl sender, CanvasRegionsInvalidatedEventArgs args)
        {
            Debug.WriteLine("RegionsInvalidated");

            foreach (var argsInvalidatedRegion in args.InvalidatedRegions)
            {
                using (var session = canvas.CreateDrawingSession(argsInvalidatedRegion))
                {
                    if (pendingDry > 0)
                    {

                        using (var renderTargetSession = renderTarget.CreateDrawingSession())
                        {
                           renderTargetSession.Clear(Colors.Transparent);
                           renderTargetSession.DrawInk(inkManager.GetStrokes());
                        }


                        --pendingDry;
                        inkSynchronizer.EndDry();

                        session.DrawImage(renderTarget);

                        inkManager.DeleteSelected();
                    }
                }

            }
        }
```
But now it looks like this

first ink

![12-1](https://user-images.githubusercontent.com/7259290/30805198-13920b48-a1f9-11e7-8621-f7331708fae8.png)

second

![12](https://user-images.githubusercontent.com/7259290/30805209-213cf67c-a1f9-11e7-8513-87ae43ab40a7.png)


seems like something wrong with clear color

> renderTargetSession.Clear(Colors.Transparent);

**Comment by shawnhar** [comment]
When you draw to a control, you need to draw /all/ the shapes that you want to appear in that control. Each time you draw that is drawing its entire contents from scratch, not just adding new shapes over the top of whatever was previously drawn there.  So if you want to add just one ink stroke over the top of others, you will have to store all the previous ink strokes so that you can draw the full set of them.

The ink demo in Example Gallery might help to see some working code.

**Comment by VoteForPedro** [comment]
**shawnhar**, thank you for your reply!
