### ISSUE TITLE
UWP Virtualized Canvas Memory Leak

### ISSUE THREAD

**Issue by nolanblew** [Microsoft/Win2D#564]
There seems to be a memory leak when using the Virtualized Canvas on a UWP app.

I have created a sample app which you can find at (https://github.com/nolanblew/Win2DVirtualizeLeak)[this repo].

Below you can see a chart of what entering and exiting the page with a normal Win2D Canvas looks like (with the red tics being GC):
![image](https://user-images.githubusercontent.com/1565705/31200490-fdfe5dc2-a90f-11e7-9bc5-f1a155055056.png)

And with the virtualized canvas:
![capture](https://user-images.githubusercontent.com/1565705/31200472-ef137e32-a90f-11e7-877e-08f34f0f6f1c.PNG)

As you can see, the Virtualized canvas takes much longer to release any memory, and never seems to release all of it (still holding about +150MB of memory at the end), while the non-virtualized canvas is only holding about +4MB of memory at the end.

My cleanup code in `Unloaded` is: 
```c#
void Win2DPage_OnUnloaded(object sender, RoutedEventArgs e)
{
    WinCanvas.RemoveFromVisualTree();
    WinCanvas = null;
    _imageBitmap.Dispose(); // This is the CanvasBitmap
    _imageBitmap = null;
}
```

Any idea to what I should be doing or if this is an issue?

**Comment by shawnhar** [comment]
I would only worry about things like this if you see the memory usage grown steadily each time you load and unload a page.  There are many layers in the software stack (including Direct2D and DComp) which have internal memory pools that hang onto previously used resources to optimize future usage, so it is normal that total memory usage will not go all the way back down to zero after some rendering has taken place.  The sign of a leak is that repeated usage leads to repeated increases - you can't tell much at all from how much memory remains allocated after a single use-then-free cycle.

If you are concerned that your XAML page might not be getting unloaded properly, you can check for this by (temporarily) giving it a finalizer method which outputs a debug log message.

**Comment by OvestLabs** [comment]
I have a repo that shows a memory leak in CanvasVirtualImageSource:

https://github.com/OvestLabs/Win2dVirtualMemoryLeak

I understand that memory may not be freed immediately, but this shows how memory is never freed. Here are some screenshots of what happens:

https://github.com/OvestLabs/Win2dVirtualMemoryLeak/blob/master/Screenshots/Exception.png
https://github.com/OvestLabs/Win2dVirtualMemoryLeak/blob/master/Screenshots/MemoryUsage.png

Please have a look when you have time. It's an easy repo to run. I'd really appreciate any assistance here. I'm missing a step somewhere.

**Comment by shawnhar** [comment]
@OvestLabs the problem is that you are creating a fresh graphics device every time.  Devices are expensive objects, and it's rare that an app would want more than one of these.  Either hang onto the CanvasDevice after you've created it the first time, or use CanvasDevice.GetSharedDevice.

**Comment by nolanblew** [comment]
@shawnhar For my issue, yes the memory stack does steadily grow each time I open a new drawing. Apologies for not explaining, but each one of those big step-ups in the graphs is me going back into the XAML page with the canvas. I am attempting to manually call the GC in both, but in the `VirtualizedCanvas` for some reason the GC hangs or doesn't get called.

The real-world application I have is loading 2 very large images into memory (currently on a `CanvasBitmap`) and applying a series of filters on both of them. Each one of these canvasbitmaps ends up increasing the program's memory 150MB - 250MB. The user is most likely going to go out and come back in to the page with the canvasbitmap several times in one session On the virtualized canvas, that memory doesn't seem to free up, so the program easily consumes 8GB+ of memory after a few minutes of navigating the app.

I've also just implemented a Finalizer on both pages, but neither finalizer gets called (even after multiple GC collects).

**Comment by shawnhar** [comment]
Your sample app is leaking both the Win2DPage and Win2DVirtualizedPage instances, because their constructors subscribe to the SystemNavigationManager.BackRequested event but then never remove that event handler.  Your handler delegate references the property this.Frame, which causes it to close over 'this', thus keeping the instance alive as long as SystemNavigationManager exists.

You need to remove that event handler when leaving the page.  Or I guess you could make it global rather than per-page.

**Comment by OvestLabs** [comment]
@shawnhar , thanks! Sharing a device worked. My question now is why would someone ever need to create a new CanvasDevice? Is there a scenario where multiple devices is recommended over sharing one?

**Comment by shawnhar** [comment]
> why would someone ever need to create a new CanvasDevice? 

The two main reasons are if you want different device settings for different purposes (for instance a main rendering device that uses the GPU plus a CPU device that is configured to use the WARP software rasterizer) or for some types of multithreading.

Definitely a rare / cornercasey situation.

**Comment by OvestLabs** [comment]
@shawnhar, what about `CanvasDevice.Lock()`? Since we're sharing the device, should we lock the device when using multiple threads? Or is that done automatically when drawing session is started?

**Comment by shawnhar** [comment]
Only if you are sharing the device with non-Win2D rendering code.  More details at https://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasDevice_Lock.htm
