### ISSUE TITLE
Can the CanvasVirtualControl be tweaked to invalidate smaller regions?

### ISSUE THREAD

**Issue by OvestLabs** [Microsoft/Win2D#565]
Hi Guys. Got a quick question for you about CanvasVirtualControl... I hope you have an answer :)

I've posted it on Stackoverflow but haven't received a response yet. Have a look and let me know if it's possible:

https://stackoverflow.com/questions/46544071/can-the-canvasvirtualcontrol-in-win2d-be-tweaked-to-invalidate-smaller-regions

**Comment by damyanp** [comment]
This isn't supported in Win2D or the underlying VirtualSurfaceImageSource it is built on.

Can you explain a little more why you need this?

**Comment by OvestLabs** [comment]
I'm trying to render a large collection of vector graphics at high DPI, but end up waiting a long time for a large portion of the bitmap to appear. Drawing is done on a separate thread and I figured if I can get smaller regions, I can show the bitmap faster in smaller pieces.

**Comment by damyanp** [comment]
Maybe you could try experimenting with calling CreateDrawingSession(region) just for the regions that you have ready, rather than all the ones that are marked invalid, and then drawing in the other parts as you have it ready?

**Comment by OvestLabs** [comment]
I tried that, but the control didn't like it. When I split a larger region into 4 parts manually and called CreateDrawingRegion(region1) .. (region2) .. etc. It would constantly raise RegionsInvalidated with the same regions again. 

I'll try it again in an isolated environment, in case I messed something up. I'll get back to you...

**Comment by damyanp** [comment]
You may also want to consider using a CanvasVirtualImageSource, which gives some more control over how RegionsInvalidated is raised.

See in particular http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_UI_Xaml_CanvasVirtualImageSource_RaiseRegionsInvalidatedIfAny.htm.

**Comment by OvestLabs** [comment]
Ok. I think I have something working, but now I'm experiencing a new problem. There's a memory leak.

I'm currently using [this example](https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_UI_Xaml_CanvasVirtualImageSource.htm) but when I remove the image from the parent canvas, it disappears from the screen but doesn't reduce memory. If repeated several times, memory goes up to 2GB :/

So, what is the best way to guarantee disposal of the CanvasVirtualImageSource? Here's a snippet of what I'm doing to remove it:

```
panel.Children.Remove(imageControl); // remove the actual xaml image element
imageControl.Source = null; // Clear any reference to the source (just in case)
```

What else do I need to do? There's no Dispose() method on the CanvasVirtualImageSource and I've tried disposing the underlying CanvasDevice.. still no good.

**Comment by damyanp** [comment]
See #564.  It's not necessarily expected that the memory that backs your virtual image source is immediately freed when the image source is unreferenced.

**Comment by OvestLabs** [comment]
I added a comment to #564 with a repo.
