### ISSUE TITLE
CanvasControl never calls draw

### ISSUE THREAD

**Issue by JulienNoble** [Microsoft/Win2D#567]
Hi!

I have a problem with `CanvasControl` : for some reason it just stopped calling the Draw event, even with an `Invalidate()` call. This even applies to `CanvasAnimatedControl`. My app context is kinda special, it's a **react native UWP app**. I was using Win2D for an advanced custom image component, and until just a few hours ago, it worked really fine : rendering was done, I could communicate between react and the native module.

Right now, I can still communicate between my module and react, but `Draw` is never called, not even at instancing. Absolutely nothing changed, the setup is a simple xaml user control with a `CanvasControl` and CreateResources/Draw implemented code side. It just... stopped working.

Platform :

- App is targeting UWP x86 and x64 (both fail)
- Visual Studio 2015 Update 3
- Windows 10 Creators Update 15063.632
- Win2D 1.21.0 from NuGet
- React Native 0.49.0
- React Native Windows 0.49.0rc1

**Comment by shawnhar** [comment]
Please provide a repro that shows the problem you are having (simplified as far as possible from your full app).

**Comment by JulienNoble** [comment]
I made a gist of the minimum setup I used to test and reproduce this : https://gist.github.com/JulienNoble/369f6c61817a4b67d90073e612397c30

To test it, just create a [default React Native Windows app](https://github.com/Microsoft/react-native-windows) and plug a call to ImageView in your main js app container. It wont render anything as is, but you can never step into `canvas_Draw`, whereas the ctor, `canvas_CreateResources` and `UserControl_Unloaded` are correctly called. 

I have to stress out that no change to the code was done, it just stopped working just like that.

**Comment by shawnhar** [comment]
Sorry, I'm not sure what to do with the component in this repo?  Having never used React Native (or even much JS for that matter!) the instruction "plug a call to ImageView" doesn't mean anything to me :-)

Please provide a complete repro that I can just compile and run directly.

**Comment by JulienNoble** [comment]
My bad, I have to admit RN can also be very scary. I did a sample repo of the minimum setup here : https://github.com/JulienNoble/Win2DTest The instructions are in the readme.

I can repro the bug with this setup: Draw is never called.

I tested on VS2017 with the latest updates and frameworks, it does the same. I have another theory but I can't validate it,

**Comment by rozele** [comment]
@JulienNoble you should be able to use `react-native bundle` to produce a build that doesn't require any react-native-cli / NPM installs. That would be most helpful - you can then just force check in `windows/Win2DTest/ReactAssets/index.windows.bundle` and instruct users to run using DebugBundle config.

**Comment by rozele** [comment]
@shawnhar I can attest to this issue as well. I've tried to use Win2D in the past with React Native, but the Draw callback is never invoked. Is there some lifecycle event on Win2D that needs to be called to start the Draw callbacks?

**Comment by shawnhar** [comment]
The most likely reason for Draw not to get called is if the control is not actually visible, either because the entire app is minimized or perhaps it has zero size.  I don't see anything in this repro app to specify the size of the Win2D control (but am not familiar with how this hosting environment works) - is it possible that the XAML layout is collapsing down to nothing?

**Comment by rozele** [comment]
@shawnhar great call on the size. @JulienNoble, when I add explicit size style:
```
        <Win2dImageView style={{width: 100, height: 100}} />
```
Draw is called. But when I add flex props (e.g., flex: 1), Draw is not called because the view gets a `0` height.  I'm digging in now, but it's safe to close the issue here, we'll follow up on RNW.

**Comment by JulienNoble** [comment]
Oh damn yes! Well, thanks to both of you!
