### ISSUE TITLE
InvertEffect crashes VS2017

### ISSUE THREAD

**Issue by deltakosh** [Microsoft/Win2D#568]
Hello!
I use this code in my app:
```
                var effect = new InvertEffect()
                {
                    Name = effectName,
                    Source = new CompositionEffectSourceParameter("source")
                };

                // Create a brush to which I want to apply.
                brush = compositor.CreateEffectFactory(effect).CreateBrush();
                brush.Comment = url;

                UriSurface surfaceUri;

                if (!SurfaceCache.TryGetValue(url, out surfaceUri))
                {
                    var surfaceFactory = SurfaceFactory.GetSharedSurfaceFactoryForCompositor(compositor);
```

the last line crashes VS (not even possible to debug as VS itselt crashes)

I have no problem with 1.20. Problem only appears with 1.21

**Comment by shawnhar** [comment]
What exactly do you mean by crashing VS?  Is this when Intellisense processes the code, or during compilation, or while debugging?

Does "last line" refer to the SurfaceFactory.GetSharedSurfaceFactoryForCompositor call?  I'm not familiar with that API - where does SurfaceFactory come from?

Finally, can you provide a repro app that demonstrates this issue?

**Comment by deltakosh** [comment]
Sorry I was unclear.
So:
1- Crash happens at runtime. If I try to debug with VS, it crashes VS
2- It comes from this nugget:

Here is a repro project (I tried to strip off everything I can)
[UrzaGatherer.zip](https://github.com/Microsoft/Win2D/files/1388267/UrzaGatherer.zip)

The problem can be seen in the BlockPage.xaml file:

![image](https://user-images.githubusercontent.com/1306056/31623363-08df9fe2-b254-11e7-993b-8a15a243b9bd.png)

If you remove the underlined attached property it works. Same if you use win2D 1.20

**Comment by shawnhar** [comment]
I'm not seeing any crash from running this, just a bunch of UI that I'm not sure what to do with?

I'm building the "Debug (Anniversary Update)" config for Any CPU, which for some reason seems to map the actual project to build for Release x64...

**Comment by deltakosh** [comment]
Current computer:
![image](https://user-images.githubusercontent.com/1306056/31633902-8da809fe-b276-11e7-8519-33f7fd7e10db.png)

It is a 100% repro (using the same config as you).
If you see the icons, then you did not hit the issue as the app is supposed to crash

**Comment by shawnhar** [comment]
Yep, I see icons and no crash.   I'm on a somewhat older OS than you (but recent enough to support invert effect), and am using with VS 15.4.0.

**Comment by deltakosh** [comment]
Could it be related to a driver issue? I run on a  1080

**Comment by deltakosh** [comment]
Ok solution found.
I was a problem with Robmikh.CompositionSurfaceFactory nuget. Moving to latest version  (0.7.3) fixed the problem!
