### ISSUE TITLE
Q: Win2D with MVVM?

### ISSUE THREAD

**Issue by MauriciusIO** [Microsoft/Win2D#569]
Hi!
Is it possible to use Win2D.UWP with MVVM (no-code-behind)? I was looking for example code in examples but i haven't found any.

Thanks for sharing any simple example code for CanvasAnimatedControl with MVVM.
It would help many beginners like me :-)

**Comment by shawnhar** [comment]
Win2D is an immediate mode API, which means it just draws whatever it is instructed to whenever a drawing API is called.  If you have no actual code to be calling these drawing APIs, then nothing will ever be drawn.  Unlike a retained mode rendering system like XAML, Win2D doesn't have any persistent state such as a DOM that could participate in data binding.

That said, a common way to use Win2D is by building higher level components on top of it, which could maintain state and expose properties that allow them to participate in XAML style patterns such as data binding.  Such behaviors are a choice of your higher level components, though - Win2D itself sits at a lower level that's all about code issuing immediate API calls.
