### ISSUE TITLE
The beginning and ending characters are truncated for some specific fonts like "Pristina"

### ISSUE THREAD

**Issue by simplyzhao** [Microsoft/Win2D#572]
Here's the code:

	Platform::String^ displayText = L"jjjjjj";
	auto canvasTextFormat = ref new CanvasTextFormat;
	canvasTextFormat->Direction = CanvasTextDirection::LeftToRightThenTopToBottom;
	canvasTextFormat->FontFamily = L"Pristina";
	canvasTextFormat->FontSize = 512;
	auto canvasDevice = CanvasDevice::GetSharedDevice();
	auto canvasTextLayout = ref new CanvasTextLayout(canvasDevice, displayText, canvasTextFormat, FLT_MAX, FLT_MAX);
	auto bounds = canvasTextLayout->LayoutBounds;

	CanvasRenderTarget^ offscreenRenderTarget = ref new CanvasRenderTarget(canvasDevice, bounds.Width, bounds.Height, 96.f);

	CanvasDrawingSession^ drawingSession = offscreenRenderTarget->CreateDrawingSession();
	drawingSession->Clear(Colors::Transparent);
	drawingSession->DrawTextLayout(canvasTextLayout, 0, 0, Colors::Black);
	delete drawingSession;

	auto path = Windows::Storage::ApplicationData::Current->TemporaryFolder->Path;
	path += L"\\test_Pristina.png";
	offscreenRenderTarget->SaveAsync(path);

**Comment by simplyzhao** [comment]
Looks like the truncated part is out of the layout bounds. Any method to avoid this issue? Thanks a lot.

**Comment by shawnhar** [comment]
Sounds like you want to use DrawBounds instead of LayoutBounds.  Also note that you can't assume the top left of the bounds will be zero - you need to take that into account as well as the width and height.  Depending on the font there could be a positive or negative offset from the coordinate you draw at to the precise top left of the bounds.

For more info see 
https://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_Text_CanvasTextLayout_LayoutBounds.htm, and the text layout demo in Example Gallery (use the menu to turn on the different kinds of bounds).

**Comment by simplyzhao** [comment]
Thanks for your response.
I suppose DrawBounds is the right direction. However, the case here is not the same with the example in Example Gallery. That example draw text to a target of a fixed size, here I need to use the bounds to create the CanvasRenderTarget(since I need to render text to an image). With DrawBounds, I cant get it to work even for normal fonts like "Arial"...
The following code is the best I can get, however, I guess it's not correct:

auto bounds = canvasTextLayout->DrawBounds;
CanvasRenderTarget^ offscreenRenderTarget = ref new CanvasRenderTarget(canvasDevice, bounds.Width + abs(bounds.X), bounds.Height + abs(bounds.Y), 96.f);
CanvasDrawingSession^ drawingSession = offscreenRenderTarget->CreateDrawingSession();
drawingSession->Clear(Colors::Transparent);
drawingSession->DrawTextLayout(canvasTextLayout, -bounds.X, -bounds.Y, Colors::Black);
delete drawingSession;

Do you mind explain a bit more about the coordinate system Win2D uses to draw text?

**Comment by shawnhar** [comment]
That's close, but your rendertarget size just needs to be the width and height of the bounds - no need to add abs(x) there.

**Comment by simplyzhao** [comment]
Great, it works. Thanks a lot for your suggestion.
