### ISSUE TITLE
Unable to open SimpleSample solution with Visual Studio 2015.

### ISSUE THREAD

**Issue by Monsok** [Microsoft/Win2D#573]
I tried to open the SimpleSample solution with VS 2015 but it failed to load. Instead in the VS Solution Explorer, it prompted that an update is required but clicking the menu item only forwarded me to MSN or something.

I've already installed the Windows 10 SDK for Fall Creators Update (10.0.16299.15) . When I opened the csproj file I found

```
  <PropertyGroup>
    <TargetPlatformVersion>10.0.15063.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.10240.0</TargetPlatformMinVersion>
  </PropertyGroup>
```

I tried editing 10.0.15063.0 to 10.0.16299.15 but it still won't load.

My PC has not been updated to Windows Fall Creators Update yet as I am still downloading it. I am having bad internet connection for the past few days. But I thought I just need to install to right SDK to compile the project.

Do I need to install VS 2017 to open projects that target 10.0.15063.0? Any help is appreciated. Thanks.

**Comment by shawnhar** [comment]
The project files in the latest version of Win2D are set up for Visual Studio 2017 rather than 2015.  The Win2D NuGet package still supports 2015 as well as 2017, but the sample projects require the newer Visual Studio.
