### ISSUE TITLE
Rotating around y-axis and applying effect causes flickering

### ISSUE THREAD

**Issue by pekspro** [Microsoft/Win2D#575]
The code below creates a square and spin that around the y-axis. If I run the code as it is the square is only drawn in some angles. If I remove the effect the square is drawn in all angles. If I remove the transformation matrix it is also drawn in all angles. But I can't combine all of this. 

It looks like this without and with the effect active:

![image](https://user-images.githubusercontent.com/3163293/32143037-afd05770-bca3-11e7-9b24-5100a54ecb79.png)

I have tried HueEffect, SaturationEffect and GaussianBlurEffect and they all causes the same problem. I'm I doing something wrong? 

To test the code, create a new blank project, add Win2D, and paste the code in OnNavigatedTo in the main page.

            var compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;
            var rootVisual = compositor.CreateContainerVisual();

            // Setup the perspective transform.
            Vector2 panelSize = new Vector2(400, 400);
            Matrix4x4 perspective = new Matrix4x4(
                                        1.0f, 0.0f, 0.0f, 0.0f,
                                        0.0f, 1.0f, 0.0f, 0.0f,
                                        0.0f, 0.0f, 1.0f, -1.0f / panelSize.X,
                                        0.0f, 0.0f, panelSize.X, 1.0f);

            // Removing the following line removes the 3D-perspective and flickering
            rootVisual.TransformMatrix =
                        Matrix4x4.CreateTranslation(-panelSize.X / 2, -panelSize.Y / 2, 0f) *
                            perspective *
                        Matrix4x4.CreateTranslation(panelSize.X / 2, panelSize.Y / 2, 0f);

            ElementCompositionPreview.SetElementChildVisual(this, rootVisual);

            // Setup the square...
            var childVisual = compositor.CreateSpriteVisual();
            childVisual.Brush = compositor.CreateColorBrush(Colors.Green);
            childVisual.Size = new Vector2(100, 100);
            childVisual.AnchorPoint = new Vector2(0.5f, 0.5f);
            childVisual.Offset = new Vector3(50, 50, 0);

            // Create a layer and add the square as a child.
            LayerVisual layerVisual = compositor.CreateLayerVisual();
            layerVisual.Size = new Vector2(100, 100);
            layerVisual.AnchorPoint = new Vector2(0.5f, 0.5f);
            layerVisual.Offset = new Vector3(75, 75, 0);
            layerVisual.RotationAxis = Vector3.UnitY;
            layerVisual.Children.InsertAtTop(childVisual);

            //Add the layer to the root.
            rootVisual.Children.InsertAtTop(layerVisual);

            //Create an effect
            var hueEffect = new HueRotationEffect
            {
                Source = new CompositionEffectSourceParameter("source"),
                Angle = (float)Math.PI
            };

            var factory = compositor.CreateEffectFactory(hueEffect);
            // Removing the following line removes the effect and flickering
            layerVisual.Effect = factory.CreateBrush();

            //Start an animation
            var scaleAnimation = compositor.CreateScalarKeyFrameAnimation();
            scaleAnimation.InsertKeyFrame(0f, 0);
            scaleAnimation.InsertKeyFrame(1f, 360);
            scaleAnimation.Duration = TimeSpan.FromMilliseconds(1200);
            scaleAnimation.IterationBehavior = AnimationIterationBehavior.Forever;
            layerVisual.StartAnimation(nameof(layerVisual.RotationAngleInDegrees), scaleAnimation);

I’m using Visual Studio 2017.4 and Windows Fall Creators Update.

Any help appreciated!

**Comment by shawnhar** [comment]
This looks like an issue with Windows.UI.Composition rather than Win2D.  I have passed it onto the team that owns these compositor APIs.

Thanks for the report!

(for future reference, this is tracked by bug MSFT:14439715)

**Comment by pekspro** [comment]
Thanks! I hope someone finds something :-).

**Comment by shawnhar** [comment]
Hi, I'm closing this issue from the Win2D github project since it is not a problem with Win2D.

If you want to follow up with the composition team, they can be contacted via https://github.com/Microsoft/WindowsUIDevLabs/issues

Thanks!
