### ISSUE TITLE
Making copy of a brush and changing it

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#576]
I have 2 Brushes (CanvasLinearGradientBrush)
The first brush works fine, and it gives me the desired result. Now 2nd brush based on first brush. (Here I want to make a  copy the first brush, but I don’t know how to make a copy of first brush.). In this example, I created a second brush like the first one and did some rotation, translation. 
To see I am on the right path I created a very small SVG file, which works fine but not in Win2D application. I am not sure why it doesn’t work. 
The tiny project is created [https://1drv.ms/f/s!AtjIdnVOoJXtoadGL0uCX-09_pd8vA](url)The SVG file is also included. 
In this application we are rotating, translation and scale. What should be the order. Please have look, and I think I am correct.
Regards

**Comment by AghaKhan** [comment]
I just realized the rotation angle should be in radians and order should be scale, rotation and translation, which worked fine. Now there is only one question how to copy a brush without creating from start.

**Comment by shawnhar** [comment]
Win2D doesn't have a built-in way to clone a brush, so you'll have to do that yourself.  Just copy all the property values over one-by-one.
