### ISSUE TITLE
dynamically selectiong Win2D controls

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#579]
I just need some guidance. 
I have developed some Win2D controls which I could put each control inside a single RuntimeComponent where the user could pick any control from a list box. Kindly recommend me any guidance or how that can be done?   
This implies I could run multiple games in a single window and also I could drop another control without compiling.

**Comment by shawnhar** [comment]
Afraid I don't really understand this question.

Are you asking about how to dynamically select between different pieces of UI based on what the user clicks?  Perhaps something like how Win2D Example Gallery loads different demo controls depending on which icon is selected?

Or are you asking how to implement your own version of something like the XAML designer?

**Comment by AghaKhan** [comment]
Yes, You guessed it correctly, now I have to look those samples again. 
Now if I add another sample (some user control as a DLL or RunTime Component), will the application detect itself? That what I am looking for. As for as I know in Win2D Gallery those samples are the part of whole application, but I am thinking (Dependency injection / common interface) so the application shouldn't know about the control. This implies that application is just container and code is running (inversion of control) inside control. The object is the application shouldn't know about that control at RunTime. Thank for reply.

**Comment by shawnhar** [comment]
How to dynamically load modules is getting quite outside the scope of Win2D :-)

https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.AppExtensions looks like a good place to start for this.

**Comment by AghaKhan** [comment]
It looks like it can't be done. Microsoft has looked how people get inside uwp, but I have no success. Thanks for reply
