### ISSUE TITLE
(Abnormally) High CPU Usage oddities with CanvasAnimatedControl and TargetElapsedTime

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/Win2D#58]
It appears however the CanvasAnimatedControl's render loop is implemented in conjunction with the TargetElapsedTime, it causes very high CPU usage and very, very quick battery drain. The odd thing is, the **larger** you set the TargetElapsedTime on the control, the more CPU usage you sacrifice / the faster the battery drains - to the point where you can use an entire CPU core virtually doing nothing on that thread, bar one simple render / update per second, even though you're intending on doing less work.

For instance, this is what the phone looks like, using the example gallery from the store, on the CanvasAnimatedControl demo with Elapsed time of 1 second - 1 update / draw per second.

![Maximum elapsed time of 1 second] 
(http://i.imgur.com/vNfLtbF.png)
Virtually an entire CPU core being burnt away here constantly.

Now, set this down to the *minimum* elapsed, resulting in over 50+ updates / draws per second:
![Minimum elapsed time] 
(http://i.imgur.com/ID0f5s7.png)
About a third of the CPU usage has disappeared

For comparison, the displacement map effect using the normal canvas control. I know, apples & oranges, but still, a massive difference in CPU usage.
![Displacement Effect] 
(http://i.imgur.com/huU91H9.png)

Furthermore, here are results from a Surface Pro 3:
![Min Elapsed Time]
(http://i.imgur.com/6ZB89Fo.png)

![Max Elapsed Time]
(http://i.imgur.com/za5aKBG.png)

At worst case, I'd expect it to be the other way around. If I'm going from 60+ draw / update calls to just 1 per second, I wouldn't expect such a large resource usage *increase*. or any at all!

I assume it's because the render thread is just spinning around in the background waiting to draw (and constantly attempting to process input?), but surely there has to be some better way of doing this? 

On a tablet or mobile device I do want maximum responsiveness I can get with my limited power, but I also don't too be needlessly draining the users battery life like a crazy person . On a Surface Pro 3, I can lose nearly 1% battery a minute watching this single FPS update, with the device burning up, and the fans kicking into overdrive. Surely reducing the TargetElapsedTime should give us more battery life, and less power usage?

**Comment by shawnhar** [comment]
Figuring out what to do about this is in our [backlog](https://github.com/Microsoft/Win2D/wiki/Backlog) under the title "*Should StepTimer sleep or busy wait, if there are a lot of ticks left?*".

**Comment by shawnhar** [comment]
This is resolved in version 0.0.19, which we released today.
