### ISSUE TITLE
3D Flipping a page

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#580]
I saw your post #187, but as for as I know it is changing the size, but it is not a 3D imitation. Please correct me if I am wrong. I am looking Page flip which is provided in upw where it looks real 3D. Can this be done in Win2D?

**Comment by shawnhar** [comment]
Win2D is primarily a 2D rendering API, but some limited forms of 3D can be achieved using the Transform3DEffect.

**Comment by AghaKhan** [comment]
Thanks for reply.
Kindly guide me how can we flip a plan? 
Any Matrix transformation is one line code. Perhaps you could me a code where I could flip a plan.

**Comment by shawnhar** [comment]
I don't know of a good sample implementation of that effect, sorry.

**Comment by AghaKhan** [comment]
Thanks.
