### ISSUE TITLE
Build-in dragging an object

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#582]
I have a complex object which consists of lines, polygons and other drawing objects. It draws well, but I would like to move that with the mouse (dragging).  Is there build-in support for such operations? Which object have I clicked? I can move that object with Matrix translation, but am I on the correct path? 
How can we clip such object inside a rect? This object is outside the desired window, so how can I clip it with a rect?

**Comment by shawnhar** [comment]
Win2D only deals with immediate mode drawing - it does not have any retained mode concepts such as dragging, or any input processing abilities.  It is up to you to write code to process input events, and then redraw your Win2D graphics in whatever way you like.

**Comment by AghaKhan** [comment]
Thanks for prompt reply.
What about clip a rect?

**Comment by shawnhar** [comment]
Use CreateLayer
