### ISSUE TITLE
Exception from HRESULT: 0x802B0020

### ISSUE THREAD

**Issue by HIETE** [Microsoft/Win2D#584]
The following line gives Exception from HRESULT: 0x802B0020 when you switch via alt+tab to another app and return:
 cds = myCanvasImageSource.CreateDrawingSession(screenColor);

When you do that on Windows Simulator it even makes your pc BSOD!!

**Comment by HIETE** [comment]
here's what i do currently as a temporary workaround but it is far from ideal:

       try
       {
              cds = myCanvasImageSource.CreateDrawingSession(screenColor);                                                                              
        }
        catch
         {
                image.Source = myCanvasImageSource = new CanvasImageSource(CanvasDevice.GetSharedDevice(), (float)imageWidth, (float)imageHeight, 96);
           }

**Comment by shawnhar** [comment]
This sounds like your app is experiencing a lost graphics device, but not handling that situation correctly.

Recommendations on how to handle lost device are documented here:  https://microsoft.github.io/Win2D/html/HandlingDeviceLost.htm

**Comment by HIETE** [comment]
wow, thanks for replying so fast (and on Sunday!).
The Windows Store analytics indicate that it is causing the app to crash on others too.
I will absolutely follow the proper lost device practices tomorrow and keep you posted.

**Comment by HIETE** [comment]
I've been experimenting all morning.
I can't make it indicate a lost device.
This is the code:


   CanvasDrawingSession cds = null;

            try
            {
                cds = _imageSource.CreateDrawingSession(ScreenColor);
            }
            catch (Exception ex)
            {

                if (_canvasDevice.IsDeviceLost(ex.HResult))
                {
                    System.Diagnostics.Debug.WriteLine("yeap, device lost");
                }

                System.Diagnostics.Debug.WriteLine("PROBLEM DUDE: " + ex.Message);

                ReinitializeCanvasImageSource(); //this solves the problem

                cds = _imageSource.CreateDrawingSession(ScreenColor);
            }


and this is the output (the "yeap, device lost" debug message is not displayed):

Window became visible (this is displayed in the Window.Current.VisibilityChanged handler)
'Outlander.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\adapl\Documents\_DEVELOPMENT_\1_Main\Outlander_UWP\Outlander\bin\x64\Debug\AppX\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.Exception' in Outlander.exe
PROBLEM DUDE: Exception from HRESULT: 0x802B0020
just reinitialized CanvasImageSource (this is displayed in the ReinitializeCanvasImageSource method)


PS. I also attached a DeviceLost handler to the _canvasDevice object, that is not triggered either.

**Comment by shawnhar** [comment]
Hi,

We did some digging and it looks like there are some situations where XAML will return this error code when it needs the app to recreate their CanvasImageSource object.  I think you can solve this by responding to the failure code by disposing your old image source, creating a new one, and then repeating the draw operation.

CanvasControl does the same thing automatically: https://github.com/Microsoft/Win2D/blob/master/winrt/lib/xaml/CanvasControl.cpp#L204

(note that HRESULT 0x802B0020 corresponds to E_SURFACE_CONTENTS_LOST)

btw. what Windows version are you using?  This behavior changed in Creators Update, so I'm wondering if you are developing on an older OS?

**Comment by HIETE** [comment]
Hi,
I'm using the Fall Creators Update (16299.64) and Win2D 1.21.0

However I set the minimum platform version for my project to Anniversary Update (14393)  (The target platform version is 16299). Could it have something to do with that?

So if I don't want to use a CanvasControl my try/catch workaround is the only way?

**Comment by shawnhar** [comment]
Do you get the same result if you set the minimum platform to Fall Creators Update?  (not that this will help you fix the issue, but it would be an useful data point)

Yes, recreating the image source in response to this error is exactly what CanvasControl does automatically.

**Comment by HIETE** [comment]
I just checked. Yes setting the minimum version to FCU still gives the same error.

For now I'll stick to the try/catch thing and consider using a CanvasControl at a later time.
Thank you very much :)
