### ISSUE TITLE
Draw image line by line and get  lines as array

### ISSUE THREAD

**Issue by SeriousGeorge** [Microsoft/Win2D#587]
Hi there,

to achive some sort of image effects and manipulation I'm searchin for a method to be able to draw an image line by line and while iterating over the lines, to modify for example their x,y positions.

Back in my good old Atari Days in the 80s ;) I was able to do so in Basic and distorting the image with animations.

As I understand "stride" is not exposed.
Would a for loop with get/setPixels for example  width= imagewidth and height = 1 work - and be efficient?

Or are there any other methods that can be used to dissamble the pictures in bits and pieces (lines to stay with this example)? 

Best regards,
Andy

**Comment by SeriousGeorge** [comment]
Ok, I think I found the answer to myself :)

The correct answer I guess should be using HLSL Shaders like statet in your great explanation here: http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Effects_PixelShaderEffect__ctor.htm and in the files in the examplegallery.

I also found this: https://gamedev.stackexchange.com/questions/54789/how-can-i-use-shaders-to-make-a-square-have-a-waving-effect

That second, waving square is exactly what I was looking for. Well then - I'll dive into HLSL and try my luck ;)

**Comment by shawnhar** [comment]
Exactly right - a custom pixel shader will be the most efficient way to do this kind of distortion effect.

The "Custom Effects" demo in Win2D Example Gallery might be a good place to start learning about these.

**Comment by SeriousGeorge** [comment]
I digged into HLSL and your examples and I got it working wit one little problem remaining.
Here's the code (also if someone else is interested in):

**HLSL Shader**
```
#define D2D_INPUT_COUNT 1
#define D2D_INPUT0_COMPLEX
#define D2D_REQUIRES_SCENE_POSITION
#include "d2d1effecthelpers.hlsli"

float dpi = 96;
float Amplitude = 20;
int Time = 1;
float Width = 250;
float Frequency = 40.0;

D2D_PS_ENTRY(main)
{
	float t = Time / Frequency;

	float2 pos = D2DGetScenePosition().xy;
	int x = pos[0];
	int y = pos[1];

	float sinY = sin((x / Width) + t)*Amplitude;
	float2 inputScenePosition = float2(x, y + sinY);

    return D2DSampleInputAtPosition(0, inputScenePosition);
}
```

C#
```
        public PixelShaderEffect UseSineWave(CanvasBitmap rendertarget, int level)
        {
            var effect = new PixelShaderEffect(File.ReadAllBytes(sineFile.Path))
            {
                Source1 = rendertarget,
                Source1Mapping = SamplerCoordinateMapping.Offset,
                MaxSamplerOffset = 400
            };

            effect.Properties["Time"] = level;
            effect.Properties["Amplitude"] = 20.0f;
            effect.Properties["Frequency"] = 30.0f;
            effect.Properties["Width"] = 150.0f;

            return effect;
        }
```

Which gives a nice and easy, customizable sinus wave from c#.

**Problem**
But obiously the pixels are oscillating "outside" the rect of the bitmap.
How would you achieve that the pixels aren't cut off?

I know I have to use D2DSampleInputAtOffset, plus I do not know exactly what to pass into "MaxSamplerOffset" in the C# code.

**Line by Line?**
Initially I wanted to animate the bitmap line by line. Right now everything is being oscilatted right away - which is nice too, but not my original goal. Can this be achieved with for-loops inside the HLSL Shadercode?

Sorry if I'm bit offtopic here - but it's hard to find HLSL Examples matching to Win2D... most are XNA or GL which are in need to be ported.

**Comment by shawnhar** [comment]
It's really up to you what to do when offset calculations result in sampling from outside the source bitmap.  Depends on what visual effect you are looking for.  By default the effect runtime will fill areas outside of the source image with transparent.  You can wrap the source with a BorderEffect if you want some other behavior, or you could add logic in your shader to clamp coordinates if they go outside the image, or insert some other color there etc. as you see fit.

MaxSamplerOffset should be set to the maximum offset value that your shader will ever pass when calling D2DSampleInputAtOffset.

**Comment by SeriousGeorge** [comment]
Hi Shawn,

thanks. I just wrapped it inside a scaleEffect and in combination with my shader it produces now the desired result. It' scaled a bit tough but that's ok for now.

```
scaleEffect = new ScaleEffect
            {
                Source = sineEffect,
                CenterPoint = new Vector2((float)SourceBitmap.Size.Width / 2f, float)SourceBitmap.Size.Height / 2f),
                Scale = new Vector2(0.9f),
                InterpolationMode = CanvasImageInterpolation.MultiSampleLinear
            };
```

Thank you,
Andy
