### ISSUE TITLE
Unable to find CanvasControl

### ISSUE THREAD

**Issue by jfgossage** [Microsoft/Win2D#589]
I am working on a UWP project and have installed Win2D version 1.21 from NuGet. I am running Windows 10 Professional with the Fall Creators Update and my project is configured with this as the minimum and default version. I have added code as suggested by the README.MD file but when I attempt to build the project I get the following errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The name "CanvasControl" does not exist in the namespace "using:Micosoft.Graphics.Canvas.UI.Xaml".	TrailManager	D:\Visual Studio Solutions\WiseOldBird\TrailManager\MainPage.xaml	20
	
Error		The type 'canvas:CanvasControl' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.	TrailManager	D:\Visual Studio Solutions\WiseOldBird\TrailManager\MainPage.xaml	20	

Error		Unknown type 'CanvasControl' in XML namespace 'using:Micosoft.Graphics.Canvas.UI.Xaml'	TrailManager	D:\Visual Studio Solutions\WiseOldBird\TrailManager\MainPage.xaml	20	

My Xaml file follows:

<Page
    x:Class="TrailManager.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TrailManager"
    xmlns:canvas="using:Micosoft.Graphics.Canvas.UI.Xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">
 
    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <CommandBar>
            <CommandBar.Content>
                <Grid/>
            </CommandBar.Content>
            <AppBarButton Icon="Accept" Label="AppBarButton"/>
            <AppBarButton Icon="Cancel" Label="AppBarButton"/>
        </CommandBar>
        <StackPanel Orientation="Horizontal" HorizontalAlignment="Left" Height="1872" Margin="0,48,0,0" VerticalAlignment="Top" Width="1920">
            <canvas:CanvasControl Draw="CanvasControl_Draw" ClearColor="CornflowerBlue" />
        </StackPanel>
        <StackPanel Orientation="Horizontal" HorizontalAlignment="Left" Height="48" VerticalAlignment="Bottom" Width="1920">
            <TextBlock Text="Status" />
            <TextBlock Text="" Margin="24,0,0,0" Name="StatusBar" />
        </StackPanel>
    </Grid>
</Page>

What do I need to correct this situation? Do I need to install from source to get version 1.22?

**Comment by shawnhar** [comment]
> using:Micosoft.Graphics.Canvas.UI.Xaml

There is a typo in this namespace:  Micosoft vs. Microsoft.
