### ISSUE TITLE
CreateDrawingSurface throws an exception when screen is in power saving mode

### ISSUE THREAD

**Issue by pekspro** [Microsoft/Win2D#591]
Create a new blank UWP application and add the Win2D package. Change the MainPage to this:

    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        protected async override void OnNavigatedTo(NavigationEventArgs e)
        {
            base.OnNavigatedTo(e);

            await Task.Delay(80000);

            Compositor compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;
            CanvasDevice _device = CanvasDevice.GetSharedDevice();
            CompositionGraphicsDevice _compositionGraphicsDevice = CanvasComposition.CreateCompositionGraphicsDevice(compositor, _device);
            CompositionDrawingSurface _drawingSurface = 
                _compositionGraphicsDevice.CreateDrawingSurface(new Size(1, 1), DirectXPixelFormat.B8G8R8A8UIntNormalized, DirectXAlphaMode.Premultiplied);
        }
    }

Setup your computer so the screen is turn off after 1 minute, run the application and then take a break :-). When the application reaches the last line, an exception is thrown with the message:

    Error HRESULT E_FAIL has been returned from a call to a COM component.

I don't expect Win2D to be fully functional in this case :-) But is it possible to detect that the device is in this mode? If I catch the exception everything will be fine, but it would be nice if I could avoid running this code if I know it won't work.

**Comment by shawnhar** [comment]
Hi,

The CompositionGraphicsDevice.CreateDrawingSurface API is not actually a part of Win2D.   I will follow up with the composition team to get an answer to this question.

**Comment by shawnhar** [comment]
Hi, I'm closing this issue from the Win2D github project since it is not a problem with Win2D.

The composition team can be contacted via https://github.com/Microsoft/WindowsUIDevLabs/issues

Thanks!
