### ISSUE TITLE
Font should not jump to next line

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#592]
I like to create an image from outlines which implies when I enlarge the text should look like we have enlarged the image. Because the font is using outlines, so we are drawing vector base text, but for an unknown reason when I enlarge the view the text jumps all over. Kindly guide me to build a text where it should like we are enlarging the image. 
Your help will be very much appreciated.

**Comment by shawnhar** [comment]
Hi,

We'll need more info to understand what you are doing here.  How do you enlarge the text? What does "drawing vector base text" mean?

**Comment by AghaKhan** [comment]
[GlodenClock.zip](https://github.com/Microsoft/Win2D/files/1737926/GlodenClock.zip)
Hi Thank you for prompt reply.
I want to write an application where people can read a book. You will find many such applications with images, but none of them written using dynamically converting text to an image. The images make application very big. 
I am looking the sample (Text Outlines) where text direction is top to bottom. When I enlarge the text few lines disappear from the right-hand side. On another hand when I changed the direction from left to right some text jumps to the next line. As far as I know, outlines fonts are vector base, and we should be able to build an application with a consistent look. I am sending you an application (you may include in your sample) where its look is consistent, but I like to do with text.

**Comment by shawnhar** [comment]
Sorry, I am still not following exactly what your question is.

The Text Outlines sample does layout, then converts the text to geometry and renders it using an outline effect.  If you change the text size before the layout operation, this will result in a different layout.  If that's not what you want, you could scale at the geometry stage, after the layout is fixed.

**Comment by AghaKhan** [comment]
How can we add none English font (Arabic font,  custom font) not installed on client machine. I added Arabic font in text, but it doesn't look as provided image file. ("بِسْمِ ا ه للِّ ال ه رَّحْمَّنِ ال ه رَّحِيمِ").
![arabicfont](https://user-images.githubusercontent.com/5318363/38169363-45f20414-351d-11e8-9d8e-49ce1e0dae64.jpg)
Kindly advise me.
Regards

**Comment by AghaKhan** [comment]
Just adde

d the font which I am using.

**Comment by AghaKhan** [comment]
For some reason it looks like I closed by accident.
