### ISSUE TITLE
Flood fill algorithm in CanvasControl

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/Win2D#594]
Hi,

I am trying to implement a basic flood fill algorithm in CanvasControl.

Could you please provide some pointers on how to efficiently do the GetPixel() and SetPixel() operations within a CanvasControl?

Thanks

**Comment by shawnhar** [comment]
> how to efficiently do the GetPixel() and SetPixel() operations within a CanvasControl?

Simple answer: don't :-)

GPU rendering is not a good fit for algorithms that require get/put of individual pixels.    If you need to do that kind of processing, it will be MUCH faster to read the entire image back to the CPU in one go, then process the data using standard CPU operations without the graphics stack being involved at all.

**Comment by ratishphilip** [comment]
Thank you!
