### ISSUE TITLE
Incorrect matrix multiplication with Windows::Foundation::Numerics::float3x2 struct.

### ISSUE THREAD

**Issue by Escovado** [Microsoft/Win2D#595]
Hello.

I'm working on an SVG rendering engine using Win2D in a C++ UWP Windows Store App.  I've been using the Windows::Foundation::Numerics::float3x2 struct for matrix calculations and I have run into apparent calculation errors when multiplying float3x2 matrices together. An [example](https://www.w3.org/TR/SVG11/coords.html#NestedTransformations) from the Nested Transformations section of the W3C's SVG specification demonstrates this error.

Here's the example from the SVG spec:

![matrixcalculation](https://user-images.githubusercontent.com/13776631/37880252-2ad81db8-303a-11e8-94f6-9150060a27fa.PNG)

Here's some sample C++ code implementing the SVG example using the Numerics library:

```
void NumericsTest::MainPage::Button_Click(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e)
{
	// Given these transforms from the nested transform example in the W3C SVG spec.

	float3x2 transform1 = make_float3x2_translation(50.0f, 90.0f);
	float3x2 transform2 = make_float3x2_rotation(-0.785398f); // -45 degrees in radians.
	float3x2 transform3 = make_float3x2_translation(130.0f, 160.0f);

	// result1 and result2 have the wrong answer.
	// Expected result: m11 = 0.71, m12 = 0.71, m21 = -0.71, m22 = 0.71, m31 = 225.03, m32 = 111.23
	// Actual result:   m11 = 0.71, m12 = -0.71, m21 = 0.71, m22 = 0.71, m31 = 228.99, m32 = 188.28
	float3x2 result1 = float3x2::identity();
	result1 *= transform1;
	result1 *= transform2;
	result1 *= transform3;

	float3x2 result2 = float3x2::identity();
	result2 = transform1 * transform2 * transform3;
}
```

Here is what the correct result should be using an online matrix calculator:

![correctmatrixresult](https://user-images.githubusercontent.com/13776631/37880369-19d08fa8-303c-11e8-9f34-2154edd2f9f7.PNG)

And here is what the MS Numerics library appears to be doing performing the same matrix multiplications:

![wrongmatrixresult](https://user-images.githubusercontent.com/13776631/37880376-385fad8c-303c-11e8-95a0-4c7c06d3567c.PNG)

So, the expected result in the float3x2 matrix should be:

m11 = 0.71, m12 = 0.71, m21 = -0.71, m22 = 0.71, m31 = 225.03, m32 = 111.23

But the actual result is:

m11 = 0.71, m12 = -0.71, m21 = 0.71, m22 = 0.71, m31 = 228.99, m32 = 188.28

Looking at the source code in the WindowsNumerics.inl file, the multiplication operator does this:

```
    inline float3x2 operator *(float3x2 const& value1, float3x2 const& value2)
    {
        return float3x2
        (
            // First row
            value1.m11 * value2.m11 + value1.m12 * value2.m21,
            value1.m11 * value2.m12 + value1.m12 * value2.m22,
            
            // Second row
            value1.m21 * value2.m11 + value1.m22 * value2.m21,
            value1.m21 * value2.m12 + value1.m22 * value2.m22,
            
            // Third row
            value1.m31 * value2.m11 + value1.m32 * value2.m21 + value2.m31,
            value1.m31 * value2.m12 + value1.m32 * value2.m22 + value2.m32
        );
    }

```
The * operator is doing the correct calculations for 3x2 matrices, when treating them like two 3x3 matrices and skipping the arithmetic that produces zeros.  However, it appears the placement of the x,y translation should be calculated in positions m13 and m23 instead of m31 and m32 to concatenate the transforms correctly. I'm also wondering if the make_float3x2_rotation is setting up the rotation values correctly. 

For grins, I multiplied the transforms in the reverse order, which surprisingly produced the correct translation values, but the values for m12 and m21 were wrong.

99 times out of 100, when I run into things like this, I'm the one doing something wrong and the OS code is right. In this case, I'm using the Numerics library to create the transforms and multiply them together with the wrong results.  Anyway, is this a known issue or am I doing something wrong?

Thank you for your time.

Regards,
Don Jordan

**Comment by Escovado** [comment]
P.S. Here's a zip file of the my test project with  the sample code.

[NumericsTest.zip](https://github.com/Microsoft/Win2D/files/1845907/NumericsTest.zip)

**Comment by shawnhar** [comment]
Windows.Numerics uses row major matrix layout.  It looks like the other implementations that you are comparing this with are using column major matrices.  You must transpose when moving between one and the other.

**Comment by Escovado** [comment]
Thanks for your quick response, Shawn! I'll double-check what I was doing again and get back to you.

**Comment by Escovado** [comment]
Yeah, I got the transposition part. We are using the Eigen library with 4x4 matrices to represent the transforms according to the DOM specification, then converting them over to the float3x2 struct when rendering everything with Win2D. Something screwy is going on in the pipeline after the conversion to the float3x2. I've been sitting here scratching my head for a few days. Bah! I'll figure this out eventually.  You can go ahead and delete this thread if you want. Thanks again,
