### ISSUE TITLE
CanvasDrawingSession throw an exception if CompositionVirtualDrawingSurface is more than or equal 18000 

### ISSUE THREAD

**Issue by IbraheemOsama** [Microsoft/Win2D#596]
Hi,

I'm creating an InfiniteCanvas control in C#/UWP and I was using CompositionVirtualDrawingSurface, when I set the width of CompositionVirtualDrawingSurface size(width/height) to more than 18000px I receive an exception.

![canvaserror](https://user-images.githubusercontent.com/6191377/38169148-89707bde-35a5-11e8-8ff4-4e60f4eaaac2.PNG)

Why I'm doing that because I've an InkCanvas that can hold till 1 << 21 px and I want to sync between the CompisitionVirtualDrawingSurface and the InkCanvas.

Am I doing something wrong here ?

Thanks

**Comment by shawnhar** [comment]
Hi,

CompositionVirtualDrawingSurface isn't actually a part of Win2D.   You can get help on this API from the composition team over on https://github.com/Microsoft/WindowsUIDevLabs/issues.

Thanks!
