### ISSUE TITLE
Rotation on a rectangle

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#597]
![transformation](https://user-images.githubusercontent.com/5318363/38184524-13fea33c-35fd-11e8-883b-dc870e4dbf1c.jpg)
I have created a clock, and it works fine, but the second ticks (small rectangles not rotated yet at the center). Before applying any transformation (Except one which changes the size of the image) also works fine. The drawing size changes according to the size of the window.
args.DrawingSession.Transform = GetDisplayTransform(sender.Size.ToVector2(), new Vector2(800f, 800f));
            CanvasDrawingSession ds = args.DrawingSession;
 For an experiment, I want to change only one red rectangle. It brought worst effects. I only changed only one rectangle, but it moved all ticks. I am not sure why? When I change the window size, the ticks have their own mind. They are not where they should be. 
var old matrix = ds.Transform = new Matrix3x2(0.9192f, -0.3938f, 0.3938f, 0.9192f, -34.9217f, 234.1861f); 
            ds.FillRectangle(new Rect(517.8f, 142.9f, 9.4f, 7f), ConvertToColor("#FF0000"));
            ds.Transform = oldMatrix;
Even I put back the old transformation. No luck.
I thought maybe my matrix is wrong, so I put an Identity Matrix3x2 (1,0,0,0,1,0), but it has the same effect, which implies something is fishy with Win2D transformation. (This is my guess). The windows provide Rect matrix transformation with Matrix, but for some unknown reason, Win2D is not accepting.
Kindly guide me how ticks stay at the right place after transformation and when we change the size of the window. 
![transformation](https://user-images.githubusercontent.com/5318363/38184471-d25c1978-35fc-11e8-8fb2-6e4361e88f79.jpg)

**Comment by shawnhar** [comment]
> var old matrix = ds.Transform = new Matrix3x2

This just makes two copies of your new matrix, rather than storing the old one.

**Comment by AghaKhan** [comment]
Bug: After transform on CanvasDrawingSession for the rect, the following drawing doesn’t make any sense. Every drawing is in the wrong place, but rect is at the correct position. 
After spending few days on this problem, I concluded this is a bug belongs to Win2D code.  
I also tried matrix invert to put back the transform, but it didn't work. I can provide the sample code if you would like to fix the problem

**Comment by AghaKhan** [comment]
How to file a bug? I created repro project (very small) to explain it. Can I drop this project?

**Comment by shawnhar** [comment]
You could post code here, or publish the whole project anywhere you like online.

**Comment by AghaKhan** [comment]
Bug in Win2D
[https://1drv.ms/f/s!AtjIdnVOoJXtofEa1kQwUB_g_xBfNw](url)
Above link is for the code.
For some unknown reason, I am unable to use Matrix3x2 Transform on Rectangle. I have provided a small application, where you to try to use Transformation to Rectangle. Now run this application, which runs without any side effects. You may resize it, no problem. We only have to change one line, and the result is unacceptable. 
Please just uncomment line (3552) and run the application and you will find that something is wrong with Rectangle matrix transformation. 
I am not sure if it is only with Rectangle or other shapes as well.

![recrect](https://user-images.githubusercontent.com/5318363/38476479-d57357fa-3b62-11e8-93ef-3d6d0980424c.jpg)

**Comment by AghaKhan** [comment]
I also provide the svg file where I copy the code (SimpleClockUppercase.svg) inside my project.

**Comment by shawnhar** [comment]
Sorry, but that app is more code than I have time to read in detail and debug for you.   I see lots of drawing code there, but can't tell what you are expecting it to do, what the intent of all the commented-out transforms are, etc.

I'm happy to help with Win2D usage questions, but will need you to distill the repro down into a simple app that shows just the specific operation you are having trouble with.

Thanks,

**Comment by AghaKhan** [comment]
Thank you very much for prompt reply.
In my previous project I was asking to change only one line. The rest of the code was to show the effects after applying matrix transformation. 
This code is very small (273 lines of code). I am drawing other object, and without that code you will not see the problem. Once again we are talking only one line (187) of code.
ds.Transform = new Matrix3x2(0.9945f,-0.1046f,0.1046f,0.9945f,-3.5185f,28.8876f);
ds.FillRectangle(new Rect(272.1f, 42.2f, 3.1f, 11.6f), ConvertToColor("#FF0000"));
It works fine (resize) without matrix transformation to rect, but otherwise the rest of the objects change places. 
You will also fine SmallUppercase.svg which I have created. Please unzip Win2DRectBugSmall.zip file.
![small](https://user-images.githubusercontent.com/5318363/38512581-6c0f450c-3be0-11e8-9358-0514d4757ca4.jpg)

**Comment by AghaKhan** [comment]
Bug in Win2D
https://1drv.ms/f/s!AtjIdnVOoJXtofEa1kQwUB_g_xBfNw
Above link is for the code.

**Comment by shawnhar** [comment]
I don't follow where you think is the bug.   What I see is lots of code with commented out calls to set the transform.  When you uncomment one of these lines, the position of everything that is drawn after it changes.  This is the expected behavior when you change the transform matrix.

To help you understand how the transform matrix behaves, I need you to simplify whatever you are trying to do down to just one or two drawing operations.  That way you can explain exactly what you were expecting to happen, so I'll be able to understand whatever about your code is not right to achieve the result you are wanting,

**Comment by AghaKhan** [comment]
Thanks for reply.
The bug is at line 187 as I understand. As you suggested  “This is the expected behavior when you change the transform matrix.”, Well I disagree with respect because of transform with Identity Matrix3x2 (1,0,0,1,0,0), the result should be same, but it is not. Please replace line 186 with ds.Transform = new Matrix3x2(1, 0, 0, 1, 0, 0); and see the result. It messed up rest of drawings. I tried with given matrix and drew the rectangle and put back the inverse matrix but undo transformation, but the result still the same. I think I have experimented with Polygons and it works fine. Why it is so special with rectangle transformation. (I can check it again you would like to). 
My objective is (I have N number of rectangles) to draw all those rectangles and still able to size my drawings just like SVG is drawings. How can this behaver be achieved? Please note if I change those rectangles to polygons it works, but the position is little off.

**Comment by shawnhar** [comment]
Your code never draws with identity matrix - the very first thing it does is to set some other custom matrix.   If you later overwrite that matrix with some other value (eg. identity) that will change what transform the drawing uses.   I suspect you are confusing setting identity matrix vs. setting back to the matrix that you started out using at the top of the draw function.

**Comment by AghaKhan** [comment]
Can you guide me or tell me the solution how we can transform the rect with given matrix and still able to resize it.
Regards

**Comment by AghaKhan** [comment]
I was able to resolve it, by converting rectangles to Polygon and then apply matrix to 
geometry = geometry.Transform(matrix);
It works well.
Thanks for guidance.
