### ISSUE TITLE
Reference to type IGeometrySource2D'claims it is defined in Windows.Foundation.UniversalApiContract but it could not be found

### ISSUE THREAD

**Issue by Ponant** [Microsoft/Win2D#599]
I am getting the error after updating for wind2d  1.21.0 to 1.22.0 on VS 2017 15.7.0 Preview 5. Any idea  if this is a known bug? I had to revert to 1.21.0.
I get errors here for instance
```
   var canvasGeometry = CanvasGeometry.CreateInk(device, strokes);
                var bounds = canvasGeometry.ComputeBounds();
```
or here

```
                var geometry = CanvasGeometry.CreateInk(ds, new InkStroke[] { stroke }).Outline();
                geometry.SendPathTo(streamReader);
```
Impossible to compile.

**Comment by Ponant** [comment]
Answer is here
https://blogs.msdn.microsoft.com/win2d/2018/05/02/win2d-1-22-0-igeometrysource2d-bugfixes-and-removal-of-8-1-support/

**Comment by shawnhar** [comment]
Win2D 1.22.0 requires the April 2018 Update Windows SDK (version 17134).  You're trying to build with an older SDK.

See the release notes for details:  https://blogs.msdn.microsoft.com/win2d/2018/05/02/win2d-1-22-0-igeometrysource2d-bugfixes-and-removal-of-8-1-support/
