### ISSUE TITLE
Why not develop win3d along with win2d?

### ISSUE THREAD

**Issue by ygc369** [Microsoft/Win2D#60]
Many people need official supported win3d, just like previous XNA. When we develop 3D games, more people prefer Microsoft's offical tools, other than third party's.Is there any possibility to restart XNA project?

**Comment by shawnhar** [comment]
Thanks for the suggestion.  We don't currently have any plans to add 3D support to Win2D, so I'm going to close this issue.  That's not to say this might not change at some point in the future, so your input on this is definitely useful!
