### ISSUE TITLE
error win Win 2D

### ISSUE THREAD

**Issue by Folamour** [Microsoft/Win2D#601]
I folks im trying to follow the tutorial about win2D, 

http://microsoft.github.io/Win2D/html/Introduction.htm

i'm using visual studio 2017, i'm wondering that i have done all the necessary step but i got compilation error, can some have a look please ????

thanks a lot

```
<Page
    x:Class="Win2D1.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Win2D1"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:canvas="using:Microsoft.Graphics.Canvas.UI.Xaml"    
    mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <canvas:CanvasControl Draw="CanvasControl_Draw" ClearColor="CornflowerBlue"/>
    </Grid>
</Page>
```

Xmlcanvas and grid is well on where she must be but i've the error 👍 
The name "canvascontrol" does not exist in the namespace "using:Microsoft.Graphics.Canvas.UI.Xam"

??????

**Comment by shawnhar** [comment]
Did you accurately paste that error message, or are there typos in it?   The name "CanvasControl" should not be lower case as "canvascontrol", and the namespace "Microsoft.Graphics.Canvas.UI.Xaml" is missing its final "l".

This means either the error message you posted here is not accurate, or the code you posted before it is not what you are actually compiling.

**Comment by Folamour** [comment]
hi Shawnhar thanks a lot for your help, canvas is well  typed : "CanvasControl" and name space is well : xmlns:canvas="using:Microsoft.Graphics.Canvas.UI.Xaml"  

the code is posted before in thread, i'll get it directly from the tutorial, i'll dont think to have done an error, 

The exact error is (sorry i translate from french)

Error		The name "CanvasControl" does not exist in the namespace  "using:Microsoft.Graphics.Canvas.UI.Xaml". Win2D1	C:\Users\gs\Documents\Visual Studio 2017\Projects\Win2D1\Win2D1\MainPage.xaml	

Thanks a lot if you have any tips  :)

f.

**Comment by Folamour** [comment]
It seem there is compilation error with windows 10 but sadly the info are gone to 404 error, so they ask to put a thread on github

**Comment by shawnhar** [comment]
I'm confused.  That article is about a very old release of Win2D - are you really still using version 0.0.16?

Have you added the Win2D NuGet package to your project?

**Comment by shawnhar** [comment]
I'm going to close this old issue due to lack of followup.
