### ISSUE TITLE
Win2D as an rich word processor

### ISSUE THREAD

**Issue by blods** [Microsoft/Win2D#602]
I was looking for a C# library that would let me create something wordprocessor like, but with richer animations possible on each word (so words that grow slightly as you hover over them, change colour, have boxes round them).
The speed of WIn2D looks good - but is it an appropriate solution where I want each word to be its own object - For example I cant see an easy way to change the text object once its created. So I would need to have hundreds of rendered text objects on the screen and recreate them all as someone scrolls up and down, or when they edit a word. Would Win2D be inefficient for doing that?

My alternative was to use mono game - but the Win2D Font stuff seems brilliant, just may not fit this use case?

**Comment by shawnhar** [comment]
Win2D provides a couple of different levels of text functionality, depending on what balance of features vs. complexity is right for you.

CanvasTextLayout is simple to use and fairly powerful, but can't do everything and is not infinitely scalable.  This would not be a good choice for a large document using eg. a separate CanvasTextLayout for every word or sentence.

The lower level text APIs (as shown in the Win2D Gallery custom text layouts example) provide everything needed to build up your own equivalent of CanvasTextLayout, which gives the option to build in whatever features you desire.  These APIs are very flexible, but also correspondingly more complicated to use.
