### ISSUE TITLE
Unable to compile with new Win2D

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#603]
Dear Sir:
I am unable to use CreatePath function. It worked before. My project doesn't compile with (Wednesday, May 2, 2018 (5/2/2018) new packet. 

geometry = CanvasGeometry.CreatePath(pathBuilder);
Error:
Severity Code	Description Project	File	Line	Suppression State
Error	CS7069	Reference to type 'IGeometrySource2D' claims it is defined in 'Windows.Foundation.UniversalApiContract', but it could not be found

It shows by pressing F12
public static CanvasGeometry CreatePath(CanvasPathBuilder pathBuilder);
	

Description
An easy-to-use Windows Runtime API for immediate mode 2D graphics rendering.
For the Universal Windows Platform (Windows 10).
Version:	1.22.0
Author(s):	Microsoft
License:	http://www.microsoft.com/web/webpi/eula/eula_win2d_10012014.htm
Date published:	Wednesday, May 2, 2018 (5/2/2018)
Project URL:	http://go.microsoft.com/fwlink/?LinklD=519078
Report Abuse:	https://www.nuget.Org/packages/Win2D.uwp/1.22.0/ReportAbuse
Tags:	Direct2D, DirectX, 2D, Windows, graphics, XAML, canvas, drawing, UWP, Universal, UAP, WinRT, C++, C#, Platform
Dependencies

**Comment by shawnhar** [comment]
You need to use a newer Windows SDK.   See the release notes for details:  https://blogs.msdn.microsoft.com/win2d/2018/05/02/win2d-1-22-0-igeometrysource2d-bugfixes-and-removal-of-8-1-support/

**Comment by AghaKhan** [comment]
Thank you very much for kind reply. I have installed Windows 10 April update along with SDK version 10.0.17134.0 but still the same error. 
![installedupdatesdk](https://user-images.githubusercontent.com/5318363/39669142-52e9f2b2-5098-11e8-8e71-9ba3d26c6748.jpg)
As you see the image everything is correct.
Best regards

**Comment by AghaKhan** [comment]
I have to create a new project and update new SDK.
Thanks for reply and it worked.
Best regards
