### ISSUE TITLE
MCG0023:UnresolvableAssemblyReference in v1.22.0

### ISSUE THREAD

**Issue by bbos** [Microsoft/Win2D#605]
After creating a blank UWP project  and adding Win2d v1.22.0 via NuGet, the following error is shown while compiling release builds.

> MCG0023: MCG0023:UnresolvableAssemblyReference Unresolvable assembly reference 'Assembly(Name=Windows.Foundation.UniversalApiContract, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime)' found. Please check the references in your build system. A reference is either missing or an assembly is missing an expected type.

This happens before writing any code at all.  Debug builds do not show the error.  Reverting back to Win2D v.1.21.0 avoids the error.

Microsoft Visual Studio Community 2017 
Version 15.7.1

Microsoft.NETCore.UniversalWindowsPlatform
Version 6.14

Win2D.uwp
Version 1.22.0

**Comment by shawnhar** [comment]
What Windows SDK are you using?  (I suspect it's too old a version)

**Comment by bbos** [comment]
The Visual Studio Installer shows that "Windows 10 SDK (10.0.17134.0)" is installed under the "Universal Windows Platform development" section.

**Comment by shawnhar** [comment]
But which SDK is selected in your project settings?

**Comment by bbos** [comment]
I don't see any setting labeled SDK or SDK version but I guess that's the same as Target Platform.  Changing the target from 10.0; Build 16299 to 10.0; Build 17134 (which I somehow didn't notice when creating the project) fixes the issue.  Thanks!

**Comment by corradocavalli** [comment]
Got the same issue with our app targeting Creators Update, can this be fixed so that i can use latest version instead of sticking with 1.21?
