### ISSUE TITLE
Scrip right to left and start in middle of line

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#608]
![arabictext](https://user-images.githubusercontent.com/5318363/40093495-53a68c74-5877-11e8-9bc4-dcc06b802033.jpg)
I want to write some Arabic writings as shown in the picture. It starts somewhere in the middle of horizontally, but it spills out the page. What I was looking it should rape up to next line.  I am using this syntax 
ds.DrawText(SuraList[25], new Vector2(1000, 200), Colors.Black, new CanvasTextFormat()
            {
                FontSize = 80f,
                FontFamily = "Al Qalam Quran Majeed.ttf#Al Qalam Quran Majeed",
                HorizontalAlignment = CanvasHorizontalAlignment.Left,
                VerticalAlignment = CanvasVerticalAlignment.Top,
                WordWrapping = CanvasWordWrapping.Wrap,
                Direction = CanvasTextDirection.RightToLeftThenTopToBottom,
            });
The text
وَبَشِّرِ الَّذِين آمَنُواْ وَعَمِلُواْ الصَّالِحَاتِ أَنَّ لَهُمْ جَنَّاتٍ تَجْرِي مِن تَحْتِهَا الأَنْهَارُ كُلَّمَا رُزِقُواْ مِنْهَا مِن ثَمَرَةٍ رِّزْقاً قَالُواْ هَـذَا الَّذِي رُزِقْنَا مِن قَبْلُ وَأُتُواْ بِهِ مُتَشَابِهاً وَلَهُمْ فِيهَا أَزْوَاجٌ مُّطَهَّرَةٌ وَهُمْ فِيهَا خَالِدُونَ
I also want to know the area as a Rect array where the text is displayed. In above I can’t use Rect because I will not be able to start at the start of the next line. 
In my opinion, DrawText also should contain Rect Array. 
Kindly advise me how we can achieve such outcome. 
Thanks

**Comment by shawnhar** [comment]
Wrapping text requires you to specify a destination rectangle rather than just a vector position.  With only a position, there is not enough information to know where you want it to wrap.

**Comment by AghaKhan** [comment]
Thank you for prompt reply. 
As you suggested we need a destination rectangle, but how can I start a sentence middle of horizontal line and rest of text start inside the rectangle. A long sentence can start any where. ( As previous sentence ends). 
We need your guidance. 
Best regards

**Comment by shawnhar** [comment]
You can't exactly line up multiple wordwrapped sentences using a separate DrawText call for each one.  Combine all your sentences into a single paragraph, then draw the whole thing in one go.

Alternatively, you could implement your own custom text layout to gain much more flexibility (at the cost of much greater complexity).

**Comment by AghaKhan** [comment]
Thanks for reply.
Please look line 2570 in. I just copied  the line from Microsoft code and sent you.
uint32_t textLength;
auto textBuffer = WindowsGetStringRawBuffer(text, &textLength);
Indeed, it is getting the length. I might be wrong, but I think if the length of the text is grater than where wrapping starts.

**Comment by shawnhar** [comment]
That code is measuring length in Unicode characters, not pixels.  It has nothing to do with layout or wordwrapping.

If you are wanting to implement a custom text layout, I suggest you look at the custom text layouts sample code.

**Comment by AghaKhan** [comment]
Thanks.
