### ISSUE TITLE
FillCircle/FillEllipse with CanvasImageBrush has issues uses canvas coordinates as offset within bitmap for brush

### ISSUE THREAD

**Issue by PaulMouchet** [Microsoft/Win2D#613]
It appears as though the FillCircle/FillEllipse are not behaving correctly when being used with a CanvasImageBrush.  The vector used to identify where the image should be drawn on the canvas are also being used as an offset within the image brush bitmap.  Thus, if you use a bitmap that is 250x220 in size, but try to draw it on the canvas at coordinates 600x600, the image is not successfully drawn at that location.

**Comment by shawnhar** [comment]
This is how all brush operations work, not just image brushes with filled ellipses.   The coordinates of the shape being drawn do not affect the positioning of the brush itself.  If you want to position the brush to match the shape, set a translation matrix as the brush's transform.

**Comment by PaulMouchet** [comment]
I'm not sure if I'm being unclear, but I don't see how this could be 'as intended'.  
If I am going to use a bitmap for my brush image, and I want to draw that image on the canvas at coordinates 600, 600 - I can't do it.  If I replace the imagebrush with a color, the circle/ellipse renders fine.  But, if I load a bitmap into the brush, it will not work.

**Comment by shawnhar** [comment]
Sure you can.  Set the brush transform property to position its image wherever you want (eg. at 600,600).

**Comment by PaulMouchet** [comment]
I tried that, to no effect, but I will try it again.  Could you possibly give me a sample of what you mean?

**Comment by PaulMouchet** [comment]
Here is the basic code I'm using to draw with the brush and with a solid color.  The first bit of code works, but the second bit of code does not.

_drawingSession.FillCircle(new Vector2(600, 600), (float)(25), Colors.Blue);
_drawingSession.FillCircle(new Vector2(600, 600), (float)(25), brush)

**Comment by shawnhar** [comment]
You need to set the transform property on your brush.

**Comment by PaulMouchet** [comment]
Would you be so kind as to provide me with a bit more help?  

I'm not following why the method should be handled completely differently if I'm using a CanvasImageBrush or a solid color.

I can't find anything in the documentation that would suggest that this needs to be handled differently.

**Comment by shawnhar** [comment]
All brushes have a transform property (it's part of the ICanvasBrush interface).   The difference is that solid color brushes are an infinite expanse of that solid color, so it doesn't matter which part of the brush you use.  You can transform them if you want, but picking a different part of that infinite solid color expanse does not alter the output.

For an image or gradient brush, though, different parts of the brush are different colors.  In this case you are drawing entirely outside the area of your image, so you're not getting any image data at all.  Therefore you must move the brush to the same place you intend to draw.  This is done by setting its transform property.

**Comment by PaulMouchet** [comment]
Okay, at least that makes some sense to me now, but that is not well described anywhere.

That being said, can you please give me an idea as to how to set the transform property to get the desired outcome.  I've tried using a CreateTranslation, but it's not working.  Again, I've been trying to find some documentation on how to do this, but I'm not having any luck with that.

**Comment by shawnhar** [comment]
CreateTranslation is the way to do this.  Show your code please.

**Comment by PaulMouchet** [comment]
var brush = new CanvasImageBrush(sender, _tiles[1]);
            brush.Transform = Matrix3x2.CreateTranslation(600, 600);
            _drawingSession.FillCircle(new Vector2(125, 110), (float)(100), brush);

**Comment by PaulMouchet** [comment]
The only way I can get the behaviour I'm looking for is to issue a transform against the actual drawing session.  Surely, this cannot be the correct way to do this!

            _drawingSession.Transform = Matrix3x2.CreateTranslation(600, 600);
            var brush = new CanvasImageBrush(sender, _tiles[(int)TerrainTypes.Badlands]);
            _drawingSession.FillCircle(new Vector2(125, 110), (float)(100), brush);
            _drawingSession.Transform = Matrix3x2.CreateTranslation(0, 0);

**Comment by PaulMouchet** [comment]
Yes, thank you.  That additional bit of info in the Direct2D documentation was quite helpful.  The bit on transforming brushes was particularly meaningful!
