### ISSUE TITLE
Repetable Exception

### ISSUE THREAD

**Issue by eriadel** [Microsoft/Win2D#617]
stowed_exception_delegate_80000013_microsoft.graphics.canvas.dll!microsoft::wrl::details::invokehelper_abi::windows::foundation::ieventhandler_iinspectable_*___ptr64_,_lambda_44ac4028bcd6d9f6fff194ec13157c98_,2,1_::invoke

No dump or stack trace in this case :(
This is the only information we have from the Microsoft Store.

Reported 5x on 2 different devices.

Win2D version 1.21 was used.

Please close, if the data is not sufficient.

Cheers,
Karol

**Comment by shawnhar** [comment]
That's not enough to figure anything out from, sorry  :-(

**Comment by eriadel** [comment]
Ok, understood. We will come back later, if we'll be able to trace more. Cheers, Karol
