### ISSUE TITLE
Adding NuGet package Win2D.uwp 1.23.0 to solution results in an error message

### ISSUE THREAD

**Issue by ghost** [Microsoft/Win2D#618]
error : Designtime build failed for project 'D:\prj\sample.vcxproj' configuration 'Debug|Win32'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.

Visual Studio Community 2017 
Version 15.7.4
Blank Page solution using C++/WinRT VSIX 1.0.180505.2

**Comment by shawnhar** [comment]
Does this problem persist after restarting Visual Studio?

Can you build and run the project?  i.e. is it just an Intellisense failure, or something more pervasive?

**Comment by shawnhar** [comment]
Closing issue due to lack of repro information.
