### ISSUE TITLE
Unable to change font in any provided sample

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#619]
I looked the CustomFont example and changed (line 50) CanvasvasTextFormat and added FontFamily = "KGBlankSpaceSolid.ttf#KGBlankSpaceSolid", Also added the font (No runtime error)
When I run it has no effect on font. I also wrote one line code example  
[CustomFont.zip](https://github.com/Microsoft/Win2D/files/2126520/CustomFont.zip)
This also didn't work. I want to write some text and rotate an angle. Kindly guide us why we are unable to change font and how can we rotate it?
Thanks in advance.

**Comment by shawnhar** [comment]
The font name in that .ttf file is "KG Blank Space Solid", not "KGBlankSpaceSolid".

**Comment by AghaKhan** [comment]
As always, thanks for you guidance.
