### ISSUE TITLE
Converting a RenderTargetBitmap to CanvasBitmap

### ISSUE THREAD

**Issue by CristianKica** [Microsoft/Win2D#621]
I read a comment https://github.com/Microsoft/Win2D/issues/206 

> You could use XAML RenderTargetBitmap to render out the vector graphics into bitmap form, then CanvasBitmap.CreateFromBytes to turn that into a Win2D bitmap.

```
 IBuffer pixels = await renderTargetBitmap.GetPixelsAsync();
            var values = Enum.GetValues(typeof(DirectXPixelFormat));
            //var values = Enum.GetValues(typeof(BitmapPixelFormat));
            CanvasBitmap bitmap=null;
            //StorageFile video2 = await storageFolder.CreateFileAsync("video2" + ".mp4", CreationCollisionOption.ReplaceExisting);
            //foreach(BitmapPixelFormat format in values)
            foreach (DirectXPixelFormat format in values)
            {
                try
                {
                    videoClip = new MediaComposition();
                    bitmap = CanvasBitmap.CreateFromBytes(myWidget.Device, pixels, renderTargetBitmap.PixelWidth, renderTargetBitmap.PixelHeight, format);
                    StorageFile video2 = await storageFolder.CreateFileAsync("video2" + ".mp4", CreationCollisionOption.ReplaceExisting);
                    MediaClip d = MediaClip.CreateFromSurface(bitmap, DateTime.Now - previousFrame + new TimeSpan(100));
                    videoClip.Clips.Add(d);
                    await videoClip.RenderToFileAsync(video2);
                    break;
                }
                catch (Exception e)
                {

                }
            }

```
I always get The bitmap pixel format is unsupported exception

**Comment by shawnhar** [comment]
The formats supported by Win2D are documented here: http://microsoft.github.io/Win2D/html/PixelFormats.htm

I'm not familiar with the MediaClip API, but that probably also has restrictions on what types of data it can handle.

Why are you looping over all the formats?  This seems strange and unlikely to be what you want.  You need to tell Win2D the same pixel format that the byte array you provide as input to CreateFromBytes is using - this isn't going to work if you reinterpret that data as some other format entirely.

**Comment by CristianKica** [comment]
I didnt know the format, so i looped them all to find it.

**Comment by shawnhar** [comment]
That's not how it works.  When you call CreateFromBytes, you tell Win2D what format those bytes represent.  Byte data could be any format, so Win2D can't work that out if you specify some other format by mistake - it will just interpret the data wrongly.  If you don't know what format your data is, you will need to find out before calling CreateFromBytes.
