### ISSUE TITLE
Arabic character count has -ve value.

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#623]
Today I was looking provided sample CustomTextLayout. In this sample (about line 950) an Arabic and English text were provided. I just changed the mixed text with simple Arabic text. The example didn’t work and it breaks in the function GetClusterMapwhere range.CharacterCount is equal -41. How count be -ve?
It works fine with English very well, and there no compiler error.
To isolate this problem, I created stand alone project, and here we have out of range problem with same text. Here we want to create a rectangle, where the text should be justified and wrap to next line. This sample has only Arabic text.
•	CustomTextLayouts.xaml.cs inside zip file. Replacement for sample.
•	Zip file stand alone project.  

[CustomTextLayouts.xaml.zip](https://github.com/Microsoft/Win2D/files/2152560/CustomTextLayouts.xaml.zip)
[JustifyQuarn.zip](https://github.com/Microsoft/Win2D/files/2152561/JustifyQuarn.zip)
Thanks

**Comment by shawnhar** [comment]
Thanks for the report.

To set expectations - I'm not sure at the moment when we will have time to debug this, so if this is urgent you will have to investigate the problem and debug the layout code on your own.

We'd be very happy to accept a pull request to improve the sample if you are able to figure out the problem :-)

**Comment by AghaKhan** [comment]
After debugging the code, I found that if last line have few characters/words the JustifyLine function can’t handle. In real line satiations we don’t justify last line, due to few characters/words. So, the best option is don’t justify last line and change line from 
for (int i=0; i<layoutBoxes.Count; i++)  
to
for (int i=0; i<layoutBoxes.Count - 1; i++)
