### ISSUE TITLE
Dump in the Microsoft.Graphic.Canvas

### ISSUE THREAD

**Issue by eriadel** [Microsoft/Win2D#624]
[DumpInformationPack.zip](https://github.com/Microsoft/Win2D/files/2152877/DumpInformationPack.zip)

Hi Shawn,

As mentioned few days ago, we have this nightmare regarding the dump from the Microsoft Store.
I think now we have like 20 devices affected from all around the globe.
Finally we've got a first dump from the Store for the Win2D 1.21.

What's strange we do not see this issue in our other product, where we use exactly the same Win2D version and the same particle system based on the CanvasControl.
But in the new version we use more tasks and much more threads in the game and I think that might be the reason.

Please find all information attached in the zip file.
This issue is critical and blocks our next, bigger project, where we like to use the same app architecture.

Kind Regards,
Karol Sabat

Software Architect
www.artificialworldsltd.com

**Comment by shawnhar** [comment]
Unfortunately I can't work out the original source of this problem from the dump.  The crash is because something queued to the XAML dispatcher failed with RO_E_CLOSED, which indicates an attempt to use an object that has already been disposed.  But I can't tell what specific object returned this, or what operation the dispatcher was executing when it happened.

Maybe the clue that this is something to do with using an object after it was destroyed will help you narrow down the investigation, though, or give you some ideas where to add extra logging?

**Comment by eriadel** [comment]
Hi Shawn,

True, I've inspected the dump yesterday evening and I saw one object closed already.

I'll visit the studio in the next few days and I will give you potential entry points to Win2D we use in our particle system.

What I'm sure, we use CanvasControl, as you have recommended us few years earlier.

Could you ask .NET Native team, if they could check, if it's possible to extract more information regarding the callstack from the dump ?

I remember we've had similar problem in 2016, where we had problems to firgure our the call stack and Morgan Brown was very helpful regarding the callstack investigation. Maybe it's worth to try to cantact him(if he still works there) ? (I assume you know them much better than I)

What we will do in the next weeks, we will try to create a test that will help to reproduce this case.
But, if someone could say something more reagrding the dump, that could save a lot of resources.

Please do not close this thread, if possible.

Let's stay in touch,
Karol

**Comment by eriadel** [comment]
Ok. Inspected the delta between 2 products.

In product where we have the problem, we call following additional methods :

        private void RemoveCanvasControl()
        {
            try
            {
                CC.Draw -= CC_Draw;
                CC.CreateResources -= CC_CreateResources;

                //CC.Device.Dispose();
                CC.RemoveFromVisualTree();

                CC = null;

                if (bitmap != null)
                {
                    bitmap.Dispose();
                    bitmap = null;
                }
            }
            catch (Exception e)
            {
                Debug_Class.Log(e.Message);
            }
        }

I've decided to comment out the CC.Device.Dispose(); - to check, if this has an impact.

**Do you think Shawn, if that could have an impact ?
Is it safe to dispose the device, when the component will be removed ?**

Additional methods, that could be called after CanvasControl is removed (if the user or dispatcher will decide to remove quickly the Card component, before these methods will invoke), could be..

CC_CreateResources(CanvasControl sender, CanvasCreateResourcesEventArgs args)
{
…

try{
..
bitmap = CanvasBitmap.CreateFromBytes(sender, GlowingMask.PixelBuffer.ToArray(), (int)CC.Width, (int)CC.Height, Windows.Graphics.DirectX.DirectXPixelFormat.B8G8R8A8UIntNormalized);
}
...
}

private void CC_Draw(CanvasControl sender, CanvasDrawEventArgs args)
{
…
try
{
var ds = args.DrawingSession;

CanvasLinearGradientBrush LGB = new CanvasLinearGradientBrush(rc, cgs);

using (ds.CreateLayer(LGB))
                {
                    ds.DrawImage(bitmap, new Rect(0, 0, sender.Width, sender.Height));
                }
}
...
}

We try / catch everything inside, but maybe that's not enough from the Application point of view and the UWP framework dispatches elements in Win2D later and then crashes..

I do not expect the problem is coming from the particle system. Both products use the same system and it works ok so far. Hope that will help you Shawn to figure out, where the problem might be. And this will help us too.

So far, we've updated to Win2D 1.23, commented out the CC.Device's disposal and let's see how the things will be going. If you have any thoughts what else we could improve, your input is very welcome.

Best Regards,
Carl

**Comment by shawnhar** [comment]
Why are you calling Dispose on the device?  You should not generally dispose objects unless you created them yourself (for instance if your controls are all set up to use a custom device that you fully understand the lifespan of).  If your controls are using a shared device (which is the default Win2D behavior), disposing this will interfere with any other controls that might simultaneously or later be using that same device.

I'm also concerned why you think these other methods could be called after your teardown code has been executed?  That seems like a bad idea, and just wrapping them in a try/catch is not a robust solution.  I would recommend making sure you do not execute operations like this after unload.

**Comment by eriadel** [comment]
- As mentioned, we are not calling dispose on the Device anymore. (and basing on Your input, that was most likely the root cause of the problem, this has been done by one of our developers, not by me)

- Rest methods are important to reduce memory leaks for our users. We use a lot of the objects with Canvas Control and we care our apps deliver best possible performance for customers worldwide.

Thanks for your input Shawn. It's valuable.

Please give us one week to verify, if we have corrected this bug this way.

**Comment by eriadel** [comment]
Removal of CC.Device.Dispose(); solved this case. Thanks for support.
