### ISSUE TITLE
Exception thrown on DrawImage with CanvasVirtualBitmap when redering into a small dest rect with non-linear interpolation

### ISSUE THREAD

**Issue by benstevens48** [Microsoft/Win2D#625]
I get the exception 'The graph could not be rendered with the context's current tiling settings.' along with unusually high memory usage when calling DrawImage on a CanvasVirtualBitmap when the destination rect is much smaller than the source (not sure if it's an absolute size thing or a scale factor thing). It occurs for all interpolation modes except linear. For example, Drawing a 5000 * 3000 pixel image into a 10 * 10 rectangle (approximately) throws the error. No error is thrown when using CanvasBitmap instead of CanvasVirtualBitmap. This might be an external bug - I tried it with CanvasControl, CanvasVirtualImageSource and CanvasAnimatedControl with the same results.

**Comment by benstevens48** [comment]
Interestingly, images less than 4K are Ok. This leads me to a possible conjecture of the problem. The CanvasVirtualBitmap is splitting up images > 4K (not sure why because my device supports 16K textures) into pieces internally. When scaling down to a very small size using non-linear interpolation, one pixel in the downsized image maps back to a region which spans the boundaries of more than one piece. More than one piece is then loaded into an intermediate cache and this somehow causes a problem... but I don't really see why because I checked the maximum cache size and it's large enough to contain the whole image. An alternative explanation could be that it's somehow allocating memory to the inverse of every pixel, which could be quite large for high-quality cubic interpolation. But I don't see why it would do that...

**Comment by shawnhar** [comment]
What type of image are you drawing?

DirectImage supports tiling by backpropagating region information through the various effects in a graph - but not all image effects are able to do that calculation for all possible configurations of settings.  This error indicates either that one of the effects in your graph was not able to do the backpropagate calculation (in which case the system has to rasterize the entire image into a single tile) - or possibly that something about your configuration makes even a single destination pixel depend on more than a maximum tile size of source or intermediate data.

**Comment by benstevens48** [comment]
I'm just drawing a JPEG like this
```
session.DrawImage(canvasVirtualBitmapSource, destRect, sourceRect, 1.0f, CanvasImageInterpolation.HighQualityCubic);
```
All I'm doing is successively decreasing the destination rect in order to zoom out and it eventually causes the error. I admit that it is an interesting problem of how to take, say, an image split into 4 pieces, and draw it into, say 1 pixel, but I don't think it should cause an error! Probably it should draw it to an intermediate image first which is not so small and then render that to the 1 pixel.

**Comment by shawnhar** [comment]
How large is your source image, and what size are you reducing it to?

The way large image tiling works in D2D depends on ability to map backward from destination regions to source regions, so it's fundamentally impossible to draw anything where a single pixel of the destination depends on more than max tile size of source data.

**Comment by benstevens48** [comment]
My source image is 5472 by 3648 pixels. The destination size could be arbitrarily small, e.g. 12 by 8 pixels.

If this makes it fundamentally impossible to draw the image then this seems like a bit of a design flaw in D2D which makes CanvasVirtualBitmap (or the underlying D2D type) effectively useless. My use case doesn't seem unreasonable: the user can zoom out on the image. That's the one requirement I have! You might suggest setting a minimum zoom - but then how do I work out what it should be? It seems impossible to allow zooming out without encountering this exception at some point.

**Comment by shawnhar** [comment]
I'd call it a design limitation rather than a design flaw :-)

The solution is pretty simple - don't use HighQualityCubic interpolation mode if you require extreme levels of zoom.   Even if D2D was able to handle such a thing, the performance would be so poor that it wouldn't really be useful in any case.

**Comment by benstevens48** [comment]
Hmm, but why does the implementation not do something sensible like scale down to an intermediate image, then use that? At such a small scale the difference in quality is not going to be noticeable. I could do it myself but the problem is I don't really know what the minimum scale I should start doing this is. It doesn't just occur for HighQualityCubic - it occurs for anything other than Linear, even NearestNeighbor. I realise it would be more effort to handle this well but I kind of expect a high standard from D2D :)

**Comment by shawnhar** [comment]
I suspect it's just never been a priority for D2D to invest in such techniques.

The vast majority of apps use linear interpolation for all their image processing, as that's the one which GPU hardware can handle most directly.  Higher quality filtering modes have their uses, but the intersection of rarely used filtering modes plus large virtual images plus extreme scaling factors starts to look like a corner case that isn't worth spending a ton of development time on.

**Comment by benstevens48** [comment]
Ironically, the only reason I'm using D2D is to have access to the other interpolation modes. If you view 4K+ photo at half-scale e.g. on a HD screen, then it doesn't look very good using linear interpolation (very over-sharp) - high quality cubic is much better. I suppose I'll have to live with CanvasBitmap and hope no one has any 16K+ photos. Is there anywhere to make suggestions to the D2D team?

**Comment by shawnhar** [comment]
I'll pass this on, but realistically it's very unlikely to be something D2D would invest in.

For a photo viewer type app I think you could do just a 2 pass reduction.   If the destination is smaller than say 1/16 the size of the source, scale down by 1/16 into an intermediate render target.  For bonus points, keeping that intermediate around for reuse during subsequent downscales would /dramatically/ improve rendering perf.

**Comment by benstevens48** [comment]
Ok, thanks for your help. I might try that.
