### ISSUE TITLE
Using direct3D directly with Win2D panels

### ISSUE THREAD

**Issue by claudiuslollarius** [Microsoft/Win2D#626]
Is it possible to somehow get access to the Direct3D device Win2D panels use for rendering and use that directly?

CanvasAnimatedPanel and related Win2D panels provide a lot of useful functionality for 3D applications, such as handling resizing of the swapchain based on Xaml layout size/orientation changes, trimming on suspension and a game loop with configurable time step.

It would be nice to take advantage of this functionality when doing 3D rendering too, instead of having to write the platform boilerplate code from scratch every time (or copy/paste from [the sample](https://code.msdn.microsoft.com/windowsapps/XAML-SwapChainPanel-00cb688b)).

If not from CanvasAnimatedPanel itself, would it be possible to subclass it or one of its parent to achieve the same thing?

**Comment by shawnhar** [comment]
Take a look at the Direct3D Interop sample (part of Win2D Example Gallery).
