### ISSUE TITLE
Removing frame 

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#627]
I am working on a control (vector clock) which will display any resolution. The user could size it from bottom right corner. I am not sure why it is display frame. How we can get rid of the frame?
To isolate this problem, I wrote 8 lines of code where my control has size (1216f, 2000f) and background color is Red. When I draw a Green rectangle where my reference point is my control. It works fine. I can resize the control and Green rectangle is at the right location. 
Now I draw a text, where
 HorizontalAlignment = CanvasHorizontalAlignment.Center,
VerticalAlignment = CanvasVerticalAlignment.Center,  

But it is not following suggested location and printing outside (Red Background) the control. 
I need your guidance.
[Win2DTest.zip](https://github.com/Microsoft/Win2D/files/2168783/Win2DTest.zip)

**Comment by shawnhar** [comment]
Sorry, I don't understand this question.  I see a bunch of formatting code that draws various things in various places, but I don't know what you are intending it to do or what problem you are having with it.

**Comment by AghaKhan** [comment]
Thank you. I wanted to enlarge the image same aspect ratio and it has been solved.
