### ISSUE TITLE
CanvasSvgDocument FindElementById method throws System.AccessViolationException

### ISSUE THREAD

**Issue by mobilefringe** [Microsoft/Win2D#628]
When trying to find an element by its ID in a CanvasSvgDocument, it works if the ID exists in the SVG document. However, if you try looking for an ID that does not exist, a System.AccessViolationException will be thrown with the following error message: System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

This is occurring for me on Visual Studio 2017 on a project targeting Windows 10, version 1803 with Win2D 1.23.0.

**Comment by clandrew** [comment]
Thank you for the report. I'll take a look into reproducing the issue on our end.

**Comment by clandrew** [comment]
I reproduce the issue. Fix is in progress.

**Comment by clandrew** [comment]
Fix has been merged with PR #635.
Thank you again for reporting this! I'm closing the issue, seeing no further action required for this, but feel free to get in touch if you need anything else.
