### ISSUE TITLE
UAP recompiling

### ISSUE THREAD

**Issue by venetasoft** [Microsoft/Win2D#63]
Lot of errors (missing thing warnings...) 
Why didn't you simply share a zipped nuget package somewhere...? More easy and fast :)

Thank you

**Comment by shawnhar** [comment]
Please share details of exactly what you did, using what tools, and what errors you are getting.


<http://microsoft.github.io/Win2D/html/UAP.htm> has more info about the current UAP support in Win2D:

> Win2D can now be built to support the Windows universal app platform. As this a preview, we are 
> not shipping binaries in the NuGet package at this time. In order to use Win2D with the universal 
> app platform you'll need to build it from source. This is early work in progress, and some 
> workarounds are required. Further instructions can be found here: README.md
>
> If you want to learn Win2D using something that's more stable and well tested then it may be better 
> to stick with Windows 8.1 / Windows Phone 8.1 version shipped via the NuGet package.

**Comment by shawnhar** [comment]
Closing issue due to lack of info.  Feel free to reactivate if you are able to provide more details.
