### ISSUE TITLE
Draw an open polygon.

### ISSUE THREAD

**Issue by royben** [Microsoft/Win2D#633]
Hi there, great work on this API.

I need to draw an "opened polygon", (the last point is not connected to the first point).
I can do this in WPF with Polyline or in GDI with DrawCurve.

How can I achieve that with Win2D ? (except from drawing it line by line..)

Thanks,

**Comment by clandrew** [comment]
Hello, and thank you!

You can do that using CanvasPathBuilder to create a CanvasGeometry.
There's an example on this manual page: [https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Geometry_CanvasPathBuilder.htm](https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Geometry_CanvasPathBuilder.htm)

To make the polygon open, you'd pass [CanvasFigureLoop.Open](https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Geometry_CanvasFigureLoop.htm) to EndFigure.

**Comment by royben** [comment]
Thanks! that worked.
