### ISSUE TITLE
Xamarin portability

### ISSUE THREAD

**Issue by Ponant** [Microsoft/Win2D#636]
I have built a full UWP app which connects to Azure on a microservice and uses SQL and CosmosDB.
This app uses the inking API of windows and in particular Win2D. Now, I want to port this to Xamarin such that it becomes available on iOS and Android of course. However, it seems that this cannot be done because MS Inking API seems not portable to Xamarin. I really like this app and would like to give it a chance to be available on those platform. I need to collect ink from users, in particular their beziers curves to transform them, and I made the necessary transforms but this relies on the Windows Inking API and Win2D. So my problem is:

1) Can't MS just find a way to make this API on Xamarin?

2) What is the best optimized inking API I could use on droid and iOS in case option 1 is dead?

Let me say that I really hope option 1 will work, because not only it will shorten my app dev-time but also because this API is really really great.

**Comment by shawnhar** [comment]
We don't currently have any plans to support Win2D on Xamarin, sorry.
