### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by fobrs** [microsoft/Win2D#637]
When will there be a Win2d ARM64 build?

**Comment by albertofustinoni** [comment]
Second the request: the Microsoft Community Toolkit depends on Win2D, which means it too is unavailable on ARM64

**Comment by fobrs** [comment]
I've managed to compile an ARM64 version of Win2D. My UWP App, which uses it, now compiles to an ARM64 build successfully too. But because I have no ARM64 device with Win10 on ARM running, I cannot test it.
What could be the best way to submit my changes to this repository? If anyone is interested to test my local nuget package of it, please let me now.

**Comment by shawnhar** [comment]
Cool!  We'd gladly accept a pull request for something like this.  Ideally it would be good to have someone with an ARM64 device try it out before completing the PR though :-)

**Comment by fobrs** [comment]
I would test it, if I could lay my hands on one of those ARM64 devices. I'm located in the Netherlands and neither Lenovo nor Samsung sell their Win10 on ARM products over here. However, Lenovo does sell the 8GB, 128GB SSD version in the US and UK. So, if anyone in the US or UK could help me out on this I would appreciate that very much! :-)

**Comment by MartinRichards23** [comment]
I have an ARM64 laptop I can test on.

**Comment by fobrs** [comment]
Is the nuget package enough for you?

**Comment by MartinRichards23** [comment]
Sure, a nuget package is fine.

**Comment by fobrs** [comment]
Here it is: [Win2D 1.24.0.local win10 x86,x64,ARM,ARM64 Nuget package](https://bigroses.net/Win2D/Win2D.uwp.1.24.0-local.nupkg)

**Comment by fobrs** [comment]
Here is my [ARM64 fork of the Win2D repository](https://github.com/fobrs/Win2D)

**Comment by MartinRichards23** [comment]
Thanks, I built an app and ran in ARM64 with no issues. The app just drew same ellipses and text, is there anything specific you would like me to test?

**Comment by xied75** [comment]
What about this https://www.microsoft.com/store/productId/9NBLGGGXWT9F

**Comment by fobrs** [comment]
The Example Gallery needs to be compiled to ARM64 first... Otherwise you simply test the x86 version.

**Comment by fobrs** [comment]
Ok, just successfully build the Examples Gallery for ARM64, [here](https://bigroses.net/Win2D/ExampleGallery.uap_2.0.2.0_ARM64.appx) is the appx for sideloading.

**Comment by MartinRichards23** [comment]
Installation failed with error:

"App installer failed to install package dependencies. Ask the developer for Microsoft.NET.Native.Runtime.2.2-rel package."

**Comment by fobrs** [comment]
Please try [this one](https://bigroses.net/Win2D/ExampleGallery.uap_2.0.3.0_ARM64.appx). I needed to disable the LiveTileUpdater Backgroundtask to compile this one successfully...

**Comment by MartinRichards23** [comment]
Installed and ran with no issues. thanks

**Comment by xied75** [comment]
All great news, so what is the next step?

**Comment by fobrs** [comment]
You can use the nuget package above for your apps to support ARM64 hardware until this repository will be updated.

**Comment by shawnhar** [comment]
This is great to see!  Please send a pull request with the changes - we'll be delighted to merge this back.

**Comment by fobrs** [comment]
I would make it a separate branch if that is possible, because the minimal OS version is now 1803 (17134). This would make the new  nuget package unusable for older OS versions...

**Comment by shawnhar** [comment]
I would guess ARM64 needs the latest OS?  But we definately don't want to lose the ability to use Win2D with other architectures on older Windows versions.  General policy is that it's ok for Win2D to require the latest SDK in order to build, but apps that use Win2D should work downlevel unless they choose to use specific newer features.

**Comment by fobrs** [comment]
Ok, I will send a pull request, so maybe you can then alter my changes so that the min version goes back to 10240

**Comment by fobrs** [comment]
Pull request done...

**Comment by fobrs** [comment]
I'm just testing my new Asus Novago Windows 10 on ARM64 laptop. I can already report that the ARM versions of the store apps are installed and run fine! So, the Win2D Example Gallery (ARM32 build) runs fine too on build 1709!

**Comment by mobilewares** [comment]
Hi fobrs -

Just wanted to report - I have a Samsung GalaxyBook2 (with Qualcomm ARM64). I am using your ARM64 Nuget Win2d package with a UWP (Win10 1809 + SDK) App as a replacement for the official Win2d package (official one crashes my app when I create a page using the CanvasControl).

Anyhow it's working great (this is a ARM64 specific build - not ARM32/x86 emulation layer) - thanks so much for the hard work!

NG

**Comment by shawnhar** [comment]
Win2D 1.24.0 includes ARM64 support
