### ISSUE TITLE
Can't create software renderer on Phone?

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/Win2D#64]
Hello folks,

I'm wanting to open some large images on WP and rescale them down to something the GPU can actually handle or crop to just parts of them - which I've assumed is something I can purpose the software renderer for. But it seems whenever I try to create a CanvasDevice with hardware acceleration off on a phone device as follows:

`using (CanvasDevice device = new CanvasDevice(CanvasDebugLevel.None, CanvasHardwareAcceleration.Off))`

I get the following error:

{System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Graphics.Canvas.CanvasDevice..ctor(CanvasDebugLevel debugLevel, CanvasHardwareAcceleration hardwareAcceleration)

Am I trying to create the device wrong, or does WARP not ship with Windows Phone?

**Comment by austinkinross** [comment]
You're correct, WARP didn't ship with Windows Phone 8.1. I believe that WARP is available in the Windows 10 Technical Preview for phones though, if that helps you.

**Comment by clandrew** [comment]
Yes- unfortunately, WARP does not ship with WP8.1. I'll close this issue, since that appears to be the answer you were looking for. Feel free to re-open if you need more info, though.
