### ISSUE TITLE
How to draw a color image?

### ISSUE THREAD

**Issue by doghappy** [Microsoft/Win2D#640]
I have a byte array, when I try to use win2d draw bitmap, I got a gray image, how to draw a color image?

```csharp
private unsafe void MainCanvas_Draw(CanvasControl sender, CanvasDrawEventArgs args)
{
    //byte[] data = new byte[] { }
    var bitmap = new SoftwareBitmap(BitmapPixelFormat.Rgba8, 256, 240, BitmapAlphaMode.Premultiplied);
    using (var buffer = bitmap.LockBuffer(BitmapBufferAccessMode.Write))
    using (var reference = buffer.CreateReference())
    {
        var memoryBuffer = reference as IMemoryBufferByteAccess;
        memoryBuffer.GetBuffer(out byte* ptr, out uint capacity);
        var bufferLayout = buffer.GetPlaneDescription(0);
        int index = -1;
        for (int i = 0; i < bufferLayout.Height; i++)
        {
            for (int j = 0; j < bufferLayout.Width; j++)
            {
                index++;
                ptr[bufferLayout.StartIndex + bufferLayout.Stride * i + 4 * j + 0] = data[index];
                ptr[bufferLayout.StartIndex + bufferLayout.Stride * i + 4 * j + 1] = data[index];
                ptr[bufferLayout.StartIndex + bufferLayout.Stride * i + 4 * j + 2] = data[index];
                ptr[bufferLayout.StartIndex + bufferLayout.Stride * i + 4 * j + 3] = 255;
            }
        }
    }
    CanvasBitmap canvasBitmap = CanvasBitmap.CreateFromSoftwareBitmap(args.DrawingSession, bitmap);
    args.DrawingSession.DrawImage(canvasBitmap);
}
```

![image](https://user-images.githubusercontent.com/20038914/46875699-fd86e280-ce6e-11e8-9c02-450f5f4206e6.png)

**Comment by clandrew** [comment]
There is a problem here with the

`
                ptr[bufferLayout.StartIndex + bufferLayout.Stride * i + 4 * j + 0] = data[index];
                ptr[bufferLayout.StartIndex + bufferLayout.Stride * i + 4 * j + 1] = data[index];
                ptr[bufferLayout.StartIndex + bufferLayout.Stride * i + 4 * j + 2] = data[index];
`
Generally these should be assigned to the red, blue, and green channels of the image. Here they are all assigned to the same thing.

**Comment by doghappy** [comment]
Data from one delegate (another class library). it looks like:

```
public Action<byte[]> DrawAction { get; set; }
```

**Comment by clandrew** [comment]
I meant, the format of the data. 

Some possibilities for the format of "data" are
- Some portion of the bytes of the source 'data' refer to red, green, or blue, or
- 'Data' consists of indices into a palette. In that case, you need to work out what the palette is; what colors comprise it.

In the code shared above, the bitmap you're trying to create is BitmapPixelFormat.Rgba8 but "data" is not BitmapPixelFormat.Rgba8. You need to find out what the format of "data" is.

When you initialize an image from a byte array you need to consider how the data is supposed to be interpreted and what do the bytes actually mean.

**Comment by clandrew** [comment]
I don't see any additional actions for us, so I'm going to close this issue. But please feel free to re-open and get in touch if there's anything else we can help with!
