### ISSUE TITLE
CanvasAnimatedControl inside CanvasAnimatedControl ?

### ISSUE THREAD

**Issue by jtorjo** [Microsoft/Win2D#641]
Hi,

This is a newbie question. I have a WPF app that does a LOT of animations. And I have lots of controls inside controls that have pixel shaders tied to them, and they are also rotated and such (I also make heavy use of ClipToBounds=true).

I want to port the app to Win2D, but a brief look at the examples, each uses a single CanvasAnimatedControl.

So, my question is: 
**Can I have several CanvasAnimatedControl inside each-other, and animate them all at once?**

Or am I better off reorganizing my code to do all the animations inside a single CanvasAnimatedControl (this would definitely take some extra work)?

**Comment by clandrew** [comment]
You'd definitely be better off reorganizing your code to do animations inside a single CanvasAnimatedControl, if possible.

As a general guideline, apps aren't encouraged to have more than 1 or 2 CanvasAnimatedControl instances if they can help it. The Direct3D resources that back a CanvasAnimatedControl are designed for very low latency but are very heavyweight.

If you must keep your content organized into multiple controls, you might alternatively consider using CanvasControls. A CanvasControl can be animated; it just doesn't have the same design goal of very low latency. You can have many of them.

**Comment by jtorjo** [comment]
Thanks! 
Just read the following: http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_UI_Xaml_CanvasAnimatedControl.htm

From it, I understand I'm better off with just a lot of CanvasControls, and using WPF to animate them.

**From an efficiency standpoint, is there a big advantage to using the CanvasAnimatedControl over WPF animations for CanvasControls? **
In other words, if it's not at least 10% faster, I'm definitely better with CanvasControls + WPF animations.

**Comment by clandrew** [comment]
Given it'd be significantly easier to adopt your code to CanvasControls, I'd suggest trying it and seeing if the performance is suitable. (I'm assuming 'WPF animations' here means 'XAML animations' in WinRT) 

If you have literally hundreds of controls all animating all the time, it'd be a clear perf win to move that to a single CanvasAnimatedControl if possible. But generally, the actual perf difference depends a lot on the scenario.

**Comment by jtorjo** [comment]
What I mean by wpf animations - is by manually creating 'StoryBoard's.
I will look into the performance, what I start porting - I have a feeling there will be a 20-30% performance gain. I don't have hundreds of controls, but I would have roughly 30-50 controls all the time, and I'm also playing with their visibility .

**Comment by jtorjo** [comment]
First off, many thanks!
It is a bit of future ambition. I do have a other questions , and I will open other ticket(s).

Since it will be risky, I will want to gradually port everything, and, at first, allow turning Win2d-implementation on/off and see what happens.

I do see the big improvements from my point of view, so this is clearly a must for me. At this point, I see this happening in 2-3 months from now.

**Comment by clandrew** [comment]
I understand and can appreciate what's involved. Thank you for reaching out.

**Comment by jtorjo** [comment]
Thanks for helping! :)
