### ISSUE TITLE
Using pixel shaders with win2d

### ISSUE THREAD

**Issue by jtorjo** [Microsoft/Win2D#642]
Hi guys,

I will be porting a wpf app with lots of animations/effects (= pixel shaders) to win2d.
Due to the limitations of wpf, my pixel shaders are all ps_2_0 shaders. Of course, I can easily convert them to ps_3_0 shaders with a fxc.exe switch.

1. Does win2d support older shaders (ps_2_0 and ps_3_0)?
2. What's the max pixel shader version supported by win2d?
3. Assuming I'm using such  a pixel shader (ps_3_0+), can I take screen-captures of a CanvasControl using such a pixel shader?
(there's a limitation of WPF, that for ps_3_0 shaders, RenderTargetBitmap ignored the shader because ps_3_0 does not have a "software rendering fallback"). I'm assuming I would use CanvasRenderTarget - which is totally fine, as long as all the pixel shaders (namely, I will have several child CanvasControls, and some of them will have shaders) are taken into account.

**Comment by shawnhar** [comment]
Hi,

First thing to clarify is that Win2D support for custom shaders is not quite the same as what you may be used to in WPF. Win2D supports shaders indirectly through the effects system, which requires them to be authored and compiled in a specific way and to integrate with how effects operate.  I suggest you start by taking a look at the docs and samples for PixelShaderEffect.

**Comment by jtorjo** [comment]
Thanks for pointing this out! 
Initially, I had thought everything in Microsoft.Graphics.Canvas.Effects were pixel shaders. Apparently, I was wrong.

Having said that, http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Effects_PixelShaderEffect.htm just mentions that I would need to compile the pixel shader and load it.

Also , the PixelShaderEffect.IsSupported seems to only worry about some specific platforms. Since I want Win10 Desktop for start, this should not be of concern. 

So am I correct in assuming ps_2_0/ps_3_0 would be supported?

**Comment by shawnhar** [comment]
See http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Effects_PixelShaderEffect__ctor.htm for more details about how to write and compile these shaders.  The Direct2D image effects system is quite different from WPF pixel shader support you are used to, and you will need to modify your shaders accordingly.

ps_2_0/3_0 are DX9 shader models.  With Win2D you'll be using D3D11 shaders (model 4_0) instead.

**Comment by jtorjo** [comment]
I see... I assumed ps_4_0 would be a superset of ps_3_0. Still, I believe converting a shader from 3.0 to 4.0 should not be very difficult.

1. Having said that, the other effects - aren't they implemented as (Microsoft.Graphics.Canvas.Effects) - aren't they using pixel shaders under the hood?
2. I saw in the samples that you can chain effects. I would assume I could chain pixel shaders?

**Comment by shawnhar** [comment]
The main work here is not 3.0 to 4.0 shader model conversion, but changing a WPF shader to a Direct2D image effects shader.  Image effects are a much higher level construct than raw D3D style rendering, so you will need to use the definitions d2d1effecthelpers.hlsli, compile the shader into a shader library as required by D2d effects, understand how SamplerCoordinateMapping works and make sure you have these set appropriately for each shader input, etc.

This is all doable but it's quite a different system to how shaders work in WPF, so you'll need to start by learning the D2D system and can't expect to just transfer across all your existing knowledge.

**Comment by jtorjo** [comment]
Assuming I would load the image exactly to size (Width and Height of the control), then apply the shader as One-to-One, it seems I would be fine .Or am I missing anything?

Can I assume:
1. that this will be executed on the GPU?
2. that I can get a screenshot of the final CanvasControl, containing all the effects once they've been applied visually (equivalent of RenderTargetBitmap after calling UpdateLayout() on a FrameworkElement)?

**Comment by jtorjo** [comment]
Awesome, thanks!
I assume this would bring pretty awesome benefits to my app. Granted, it'll be quite a bit of porting :)
About testing on high DPI - it's perfect, since I have a 4k laptop, so I'll be testing on high dpi by default.
