### ISSUE TITLE
Make win2d compatible with XAML islands (Draw event of CanvasControl not called)

### ISSUE THREAD

**Issue by lhak** [microsoft/Win2D#643]
I have tested using the win2d library in a XAML Island (winforms .net app). I know this is certainly not a supported configuration (yet?) but I can successfully draw to the screen using the CanvasSwapChainPanel control. However, using the CanvasControl or CanvasAnimatedControl fails because the Draw event is never called. 

Additionally, adding the nuget package directly to the .net project fails (error message about compatibility with .net framework) so I had to manually add the .winmd and .dll file to the project.

**Comment by clandrew** [comment]
Yeah, that's not a supported configuration, but the report is appreciated all the same. Sorry I don't have any theories for what could be happening here. Win2D Draw events are raised from composition events (i.e. Windows.UI.Xaml.Media.CompositionTarget.Rendering) so the first step would be trying to figure out why those are not making it through. 

Not being able to add the package through the Nuget package manager also seems annoying but is likely a separate issue.

**Comment by devsko** [comment]
Fixed in #675
