### ISSUE TITLE
porting to wpf

### ISSUE THREAD

**Issue by jtorjo** [Microsoft/Win2D#645]
I'd like to port this to wpf 
Are there any critical issues I should worry about? 
Thanks!

P.S. The other idea would be to use from a XAML island in my wpf project,but it seems this is something you don't support (#643)

**Comment by shawnhar** [comment]
What mechanism would you use to host D2D content inside WPF?  There are several options, but nothing exactly equivalent to how Win2D integrates with XAML.

**Comment by jtorjo** [comment]
I'm thinking to use what SharpDX uses - since SharpDX also provides a wrapper over D2D.
Clearly, Win2D provides waaay more cool stuff.

Which also brings me to this: why not Win2d for WPF yet? Are there any plans to port it?

**Comment by jtorjo** [comment]
I've just seen #12, so i'm assuming that's simply not happening. Closing
