### ISSUE TITLE
using win2d from a wpf xaml island?

### ISSUE THREAD

**Issue by jtorjo** [Microsoft/Win2D#646]
I see from #643 that you don't plan on supporting xaml islands for winforms.
Would this be supported for wpf, or is this pretty much the same thing for you?

Also, assuming this may not be possible right now, are there any plans to add this in the future?

**Comment by shawnhar** [comment]
We haven't looked at the Win2D + XAML islands combination at all.   It's untested and unknown what might be needed to get this working - although based on reports from people who went ahead and tried this, sounds like at least some parts might already be usable?

We'd be happy to accept pull requests if you are motivated to improve this.

**Comment by jtorjo** [comment]
sounds good.
First off, I will try to port win2d to wpf. If that fails miserably :D, then for sure, I'll work on the xaml island scenario.

**Comment by pcfulife** [comment]
Could you please make the simplest Win2D on WPF using XAML Island project file.
I cannot make it. What package needs to be referenced?

**Comment by shawnhar** [comment]
As of #670 , a sample showing how to this is now available in the xaml_islands branch.
