### ISSUE TITLE
Why the Windows 10 version requirement is set so high?

### ISSUE THREAD

**Issue by xied75** [Microsoft/Win2D#647]
I still have apps at minimum os of 10240, Win2D.uwp nuget package 1.22.0 compiles and works perfectly, why suddenly 1.23.0 would demand 17134? That's a huge jump.

On a side issue, if a nuget package demands 17134, it should fail at nuget install step for a project having earlier version set.

**Comment by shawnhar** [comment]
Win2D requires SDK 17134 to build. but the resulting programs can run on any version of Win10 as long as you check for support before using features that are only available in more recent updates.

**Comment by xied75** [comment]
Thanks for the quick reply. I'm purely from the nuget package end user point of view, I nuget installed 1.23.0 into an earlier app then pressed F5, the nuget task stopped the process by complaining version too old. Thus why I asked this question.
