### ISSUE TITLE
Render XAML content using Win2D?

### ISSUE THREAD

**Issue by SuperJMN** [Microsoft/Win2D#648]
I have this problem [(How to render offscreen content with RenderTargetBitmap in UWP?)](https://stackoverflow.com/questions/53152593/how-to-render-offscreen-content-with-rendertargetbitmap-in-uwp). I wonder if Win2D can be used to cover this scenario.

In a few words, I have a `UserControl` I want to render to a video using Media Composition. The problem is that offscreen content won't render at all.

Is there a way to do this using Win2D?

Thank you.

**Comment by shawnhar** [comment]
Win2D can render to offscreen surfaces, but that won't help if you are trying to render non-Win2D content such as Media Composition.

**Comment by SuperJMN** [comment]
@shawnhar I understand that Win2D cannot render UWP controls to bitmaps. Right? Then, now that I'm asking here, is there any way to perform offscreen rendering of UI objects? If it isn't, then it's a very important flaw in ` RenderTargetBitmap.RenderAsync`

**Comment by jtorjo** [comment]
@SuperJMN Switch to wpf :D I am doing this in WPF even though the contents are offscreen, this works (it's synchronous, but it works).
It's sooo sad that MS keeps win2d on UWP instead of WPF, so you're bound by UWP's limitations everywhere :(

**Comment by shawnhar** [comment]
Closing issue as this question is about XAML rather than Win2D.
