### ISSUE TITLE
CanvasBitmap.LoadAsync doesn't respect Exif Rotation data

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/Win2D#65]
Basically as the title states, it looks like the LoadAsync call doesn't take into account Exif orientation - which is a little bit of a hassle as on a Windows Phone device for example, a lot of photos taken from a users camera won't load in the correct orientation.

(The obvious workaround is to rotate the bitmap ourselves when drawing with a Matrix transform or something, but for the life of me I haven't found out how to read the orientation properly... yet)

**Comment by clandrew** [comment]
LoadAsync calls directly into Windows Imaging Component, without doing much in terms of manipulating the image. WIC should be able to make sense of the rotation specified in the image metadata. And so, there might be some flag that Win2D needs to pass to WIC in order to get the right behavior here. I'll take a look.

**Comment by clandrew** [comment]
I investigated a little, and it'll definitely be possible to pull out the right orientation during LoadAsync, but it requires a non-trivial Win2D code change. I'll file a bug internally. Is this issue blocking you?

**Comment by 13thsymphony** [comment]
JohnnyWestlake, depending on what form your image file is in, you can use either  [ImageProperties](https://msdn.microsoft.com/en-us/library/windows/apps/windows.storage.fileproperties.imageproperties) or [BitmapProperties](https://msdn.microsoft.com/en-us/library/windows/apps/windows.graphics.imaging.bitmapdecoder.bitmapproperties.aspx). For a tutorial on how to read, manipulate and apply EXIF orientation, check out the [SimpleImaging sample](https://code.msdn.microsoft.com/windowsapps/Simple-Imaging-Sample-a2dec2b0/view/SourceCode).

**Comment by shawnhar** [comment]
This is fixed in version 0.0.18.  Thanks for the report!
