### ISSUE TITLE
Canvas.Invalidate inside OnDrawCanvas blocks keyboard events

### ISSUE THREAD

**Issue by PaulMouchet** [Microsoft/Win2D#650]
I've got a canvas control that is drawing a lot of elements each pass through the OnDrawCanvas event.  The drawing works fine and updates quickly but it seems to be blocking keyboard events.

If I remove the Canvas.Invalidate call at the end of the OnDrawCanvas event, the keyboard events come through fine.  If I reduce the amount of draws that are taking place, the keyboard events come through fine.

When the canvas is very busy, it seems like the keyboard events are getting buffered.  In this particular case, I'm using arrow keys to scroll a map.  If I hit up arrow (for instance) several times, the map doesn't scroll.  If I move the mouse, the keyboard events come through and the map scrolls.

**Comment by shawnhar** [comment]
Please share a repro that shows your problem, simplified as far as possible so we can understand just the code that is going wrong.

**Comment by PaulMouchet** [comment]
I'll try and get that to you ASAP.  I'm in the middle of a deadline crunch right now and this is one of the bugs I'm trying to clear up before I go to production.  For now, I'm having to use a workaround (turning off the Invalidate call), but it's not a good answer in the long run.

**Comment by TeamoLJQ** [comment]
Holy shit cut off

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by shawnhar** [comment]
Closing old issue due to lack of repro information.
