### ISSUE TITLE
Question: What's the next plan of Win2D team?

### ISSUE THREAD

**Issue by ygc369** [Microsoft/Win2D#652]
Just want to know what's coming up in the future versions of win2d.
It has been six months since the last blog was published.
Any plan to support 3D?

**Comment by shawnhar** [comment]
No, Win2D is a 2D library - 3D is outside its scope.

Development on Win2D has slowed since it achieved the goals of the project.  At this point it is a mature, stable technology which works well for everything it set out to do, so we are maintaining it as needed but no longer adding new features.
