### ISSUE TITLE
Is there a plan to get rid of WRL and use C++/WinRT instead ?

### ISSUE THREAD

**Issue by anup-das** [Microsoft/Win2D#653]

**Comment by shawnhar** [comment]
No.   If we were starting Win2D from scratch today we might well use C++/WinRT, but it would not be sensible to introduce massive unnecessary churn to something that is already working well.

**Comment by benstevens48** [comment]
@shawnhar Can I just add something extra to this? It might be nice on the page about direct2d interop to have an example of performing the interop using C++/WinRT. I've just been doing this and am happy to provide some same code (it's not too long but it took me a while to work out how to do it).

**Comment by shawnhar** [comment]
We'd be delighted to accept a pull request if you've got this working and are willing to share the details!

**Comment by benstevens48** [comment]
I just submitted a pull request.
