### ISSUE TITLE
Incorrect rendering of 16384x8192 offscreen bitmap on some devices

### ISSUE THREAD

**Issue by mscherotter** [Microsoft/Win2D#656]
I am noticing a problem where offscreen bitmap rendering of 16384x9128 images to JPEG files creates incorrect output on one system but not the other.  Both are fully updated WIn10 systems.  It renders correctly on a Lenovo P40 but incorrectly on a Microsoft Surface Pro 3.  In this example, the blue background is rendered the correctly, but the rectangle renders only its left half.  I get the same effect If I draw to scale or apply the scale transform.
A sample project that demonstrates this is here:
[InkCanvasTest.zip](https://github.com/Microsoft/Win2D/files/2592965/InkCanvasTest.zip)

![large image](https://user-images.githubusercontent.com/641702/48675154-67e41000-eb0a-11e8-99a5-3b3569513a97.jpg)

``            

            CanvasDevice.DebugLevel = CanvasDebugLevel.Information;
            var device = CanvasDevice.GetSharedDevice();

            var width = 16384f;
            var height =8192f;

            using (var offscreen = new CanvasRenderTarget(
                device,
                Convert.ToSingle(width),
                Convert.ToSingle(height),
                96))
            {
                using (var session = offscreen.CreateDrawingSession())
                {
                    session.Clear(Colors.Blue);

                    var scale = width / 2000;

                    session.Transform = Matrix3x2.CreateScale(Convert.ToSingle(scale));            
  
                    session.DrawRectangle(new Rect(10, 10, 1980, 980), Colors.Black, 20f);
                }

                await offscreen.SaveAsync(imageStream, format);
            }
        }

**Comment by shawnhar** [comment]
Hi,  I can't repro this on the laptop I have here, but it sounds likely to be a graphics driver issue.  What driver version are you using in the systems where this does vs. does not repro?  (you can find this info by running dxdiag).

Your repro app is quite a bit more complicated than the code posted here.  Is all that inking stuff necessary to repro the problem?   What width and height are being used in the repro app - that seems to be dynamic rather than hard-coded like the posted code?

**Comment by mscherotter** [comment]
I simplified the sample to have it only render a rectangle - without the inking.
The first button works fine, the second renders only the left half of the rectangle.
[InkCanvasTest.zip](https://github.com/Microsoft/Win2D/files/2650141/InkCanvasTest.zip)
[DxDiag.txt](https://github.com/Microsoft/Win2D/files/2650137/DxDiag.txt)

**Comment by shawnhar** [comment]
Closing issue as this doesn't look like a Win2D bug.  Please let us know if you are still blocked on this and need help reporting as a driver bug.
