### ISSUE TITLE
CanvasSvgDocument.DrawSvg() not working?

### ISSUE THREAD

**Issue by jevansAN** [Microsoft/Win2D#657]
Earlier in November I did some experiments using DrawSvg and had questions about scaling. Having resolved that I find now that DrawSvg is not working at all, and I'm at a loss to understand why.

I am loading about 250 svgs. I first load a storage file object for each, then at CreateResources I refer to that list of StorageFile objects, create CanvasSvgDocuments using the resourceCreator passed as sender in the CreateResources call, and store the svgs for reference, all from inside an AsyncAction method. Looks like this:

`nextSvg = CanvasSvgDocument(resourceCreator.Device());
auto fileStream = co_await nextFile.OpenReadAsync();
co_await nextSvg.LoadAsync(resourceCreator.Device(),fileStream);`

This appears to load the svg, but when it is used in the CanvasControl's draw method nothing appears. 
`session.DrawSvg(nextSvg, boxSize, top, left);`

Other things can be drawn: shapes, etc. - just not svgs.

Odd thing is that I had earlier drawn svgs in the Canvas control, and my question was just about scaling. The system has updated since then. Is it possible this capability has been disabled? The svg files have not changed; they are version 1.1 files created by an online pdf converter. All UTF-8.

One thing I notice is that if I call GetXml() on one of these svgs after loading, I receive a short document that contains no drawing information - is this what GetXml() is intended to return? Looks like this:

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"></svg>`

Or could it be the ResourceCreator argument? I've tried using the sender from the CreateResources call, and I've tried loading with the CanvasControl, with CanvasControl.Device(), and with CanvasDevice::GetSharedDevice(), but there is no change in behavior. Is this a bug in the latest release or is there something plain wrongheaded about what I'm doing? Thanks.

**Comment by shawnhar** [comment]
LoadAsync is a static method, not an instance method.  You are ignoring its return value, so throwing away the newly loaded SVG document.

**Comment by shawnhar** [comment]
Are you definately drawing the control after the async load has completed?

Are you drawing the SVG at a location that is on the screen and with transform set to something sensible?

**Comment by jevansAN** [comment]
I can repeat the draw anytime by changing the zoom level, and location is at a default nearby point - other things are drawing fine: I can do shapes, lines, etc.
I'm not touching the transform at the moment. But I notice that if I test, e.g. (if (theSvg)) during the draw the apparently is no svg. I am storing each of these during a for loop in the CreateResources method and then referencing them from an array. As the loading is async I can't see trap results in the debugger - but apparently no svg is being created by each call to CanvasSvgDocument.LoadAsync(resourceCreator, filestream);

**Comment by shawnhar** [comment]
This sounds like a bug somewhere in your loading or resource management code.

**Comment by jevansAN** [comment]
Ah - I see that if I skip the array of StorageFiles (enumerated from the contents of my folder containing the svg files) and just ask for one specific file using GetFileFromApplicationUriAsync() then I can load an svg and even draw it. So there is something about looping through this array of 239 StorageFile objects that the system doesn't like. Maybe the StorageFiles can't be saved for future reference like this. Thanks much.

**Comment by shawnhar** [comment]
Closing issue as this doesn't sound like a Win2D bug.
