### ISSUE TITLE
Win2D in WPF with .NET Core 3.0

### ISSUE THREAD

**Issue by pcfulife** [Microsoft/Win2D#660]
I found that WPF will be able to use Win2D with .NET Core 3.0 (https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/) by Microsoft staff.

> Yes. You will be able to use Win2D in WPF with .NET Core 3.0.

1. I installed VS 2019 and .NET Core 3.0 SDK Preview 1.
2. Type `dotnet new wpf -o WpfApp1`.
3. Create a empty solution with VS 2019.
4. Load WpfApp1 project into solution.

[WpfApp1.zip](https://github.com/Microsoft/Win2D/files/2670401/Solution1.zip)

But, I cannot install Win2D Nuget package. (by typing `Install-Package Win2D.uwp`)
It seems that it doesn't support .NET Core 3.0 yet.
It is understandable because .NET Core 3.0 is in a preview stage.

So, will this nuget package support .NET Core 3.0 after it released?
If no, I think that it will be good to make a manual how to ready to use Win2D in WPF.

Thanks.

**Comment by jtorjo** [comment]
I would like to know this as well :)

**Comment by shawnhar** [comment]
As of #670 , a sample showing how to this is now available in the xaml_islands branch.
