### ISSUE TITLE
Writing to the buffer

### ISSUE THREAD

**Issue by AghaKhan** [Microsoft/Win2D#661]
I have a complicated drawing, which will never changed once it is build and It looks unnecessary to build again and again in CanvasAnimatedControl.draw function. Is there a way to write in an image/bitmap/buffer so we don't build again and again.

**Comment by shawnhar** [comment]
https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasRenderTarget.htm

**Comment by damyanp** [comment]
Also: http://microsoft.github.io/Win2D/html/Offscreen.htm

**Comment by AghaKhan** [comment]
Sure it worked. But I don't know the location of image. For example ds.DrawImage(offscreen,pt.X, pt.Y);
 Now I like to drag it, but I like to find its location. There is no way to find. The function GetBound return RECT, but location is always gives you 0,0,widh,height. There is no other function. I also saw ICanvasImage.GetBounds(ICanvasResourceCreator, Matrix3x2). What we have to do with Matrix3x2? I like to know the distance when I click that image from its origin.

**Comment by shawnhar** [comment]
Win2D is an immediate mode API, which means it does not know anything about the location or permanent state of objects.  Win2D just draws whatever you tell it to, in whatever location you tell it to.  It is up to you to track whatever information you need to keep track of whatever objects you are working with.

**Comment by AghaKhan** [comment]
Thanks for reply. I understand what you are suggesting. Win2D is an immediate mode API, which means it does not know anything about the location or permanent state of objects. Now we are talking about the implementation of the bound as a Rect, which always returns 0,0,width,Height. If that is the case then it should not return Rect, rather Size. Rect gives you Left, Top, Width ,Height. Here we are getting 0, 0, for Left, Top.
Regards
