### ISSUE TITLE
Could not find Windows Runtime type 'Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedControl'.

### ISSUE THREAD

**Issue by pcfulife** [Microsoft/Win2D#667]
Hi, I am making a WPF application with .NET Core 3.0 Preview (Exactly, I am maintenancing old .NET Framework WPF application to .NET Core)
I want to use Win2D in WPF. And, .NET Core 3.0 will support Win2D in WPF with .NET Core 3.0
But, when I create a .NET Core WPF Project, and instant CanvasAnimatedControl, It shows this exception message.

My MainWindow.xaml is
```
<Viewbox Stretch="Fill">
  <Canvas Width="1280" Height="720">
  <xamlhost:WindowsXamlHost ChildChanged="CanvasChanged" InitialTypeName="Windows.UI.Xaml.Controls.Viewbox" Width="1280" Height="720" />
  </Canvas>
</Viewbox>
```

and MainWindow.xaml.cs is

```
void CanvasChanged(object sender, EventArgs e)
{
  var vMainView = (Windows.UI.Xaml.Controls.Viewbox)((WindowsXamlHost)sender).Child;
  vMainView.Stretch = Windows.UI.Xaml.Media.Stretch.Fill;
  var canvas = new Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedControl();
  vMainView.Child = canvas;
}
```

and Exception is
System.TypeLoadException: 'Could not find Windows Runtime type 'Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedControl'.'

I referenced "Microsoft.Graphics.Canvas.winmd", "Microsoft.Toolkit.Wpf.UI.XamlHost", "C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.17763.0\Windows.winmd" file.
And, installed System.Runtime.WindowsRuntime NuGet package.

Will this issue be solved after .NET Core 3.0 released?

**Comment by lhak** [comment]
In order to use the win2d library, you need to package your application with a desktop bridge project. You also have to make sure, that the types of the library are correctly referenced in the generated app manifest file. When I started using win2d some time ago, this worked automatically by copying the win2d .dll and .winmd to the project itself and then refering the local copy of the winmd file. 

I am also not sure if CanvasAnimatedControl currently works. I know that the CanvasSwapChainPanel control together with a CanvasSwapChain definitely works, but CanvasControl does not.

**Comment by pcfulife** [comment]
I created WAP Project in solution. But, it says that Project 'WpfApp1' must specify 'RuntimeIdentifiers' in the project file when 'SelfContained' is true. I specify RuntimeIdentifiers in WpfApp1.csproj

```
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
  </PropertyGroup>
```

But, it doesn't solve this error message.

**Comment by pcfulife** [comment]
Oh, it solved. I didn't do anything. But, it was built successful today. Hmm, but the exception is showing yet. (Could not find Windows Runtime type ICanvasBrush or CanvasAnimatedControl).

**Comment by shawnhar** [comment]
I'm going to close this issue as a duplicate, since #646 is already tracking the request for a sample Win2D + XAML islands project.
