### ISSUE TITLE
Windows.UI.Xaml.Window.Current.Visible always returns false in XamlIsland

### ISSUE THREAD

**Issue by devsko** [Microsoft/Win2D#668]
CanvasControl stops rendering (and even stops hooking for rendering) when the current XAML window is not visible. Unfortunately the current window seems to always be invisible inside a XAML island. When I set BaseControl.m_isVisible to true (while debugging) at least my basic test with CanvasControl works as expected (both events CreateResources and Draw are raised).
Maybe a possible workaround is to make the detection of invisible windows overridable. 
Will send a PR with complete sample soon.

**Comment by shawnhar** [comment]
Thanks for reporting.  This is already being tracked via #643.

**Comment by pcfulife** [comment]
@devsko Could you please upload a sample Xaml Island Win2D project? I cannot run my Win2D Xaml Island project. It always throw exception (TypeLoadException, COMException).

**Comment by devsko** [comment]
@pcfulife will try next week

**Comment by pcfulife** [comment]
@devsko Thank you very much!
