### ISSUE TITLE
Creating height maps from perlin noise?

### ISSUE THREAD

**Issue by chuckries** [microsoft/Win2D#672]
Just looking for general advice. I'm learning some pretty basic 3D rendering techniques, and several tutorials talk about height maps generated from perlin noise. The TurbulenceEffect outputs configurable perlin noise, but I haven't been able to find a way to raise the output to an exponent power, which is helpful for controlling height map output. 

Is there a Win2D effect I'm missing that would help raise the output of the perlin noise function to a power? Is the idea of generating height maps on the GPU itself a problem? Should I just be processing a cpu based noise function?

**Comment by shawnhar** [comment]
Unless I'm missing something there's no direct way to do this, but you could get a close approximation using LinearTransferEffect.
