### ISSUE TITLE
Support DirectWrite ColorGlyphRuns

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/Win2D#678]
So I believe this was a feature added rather recently to DW, but with more and more options for color fonts appearing, being able to expose this at the Win2D level would be rather helpful. 

This would include exposing 

```
DWRITE_GLYPH_IMAGE_FORMATS 
IDWriteFactory2::TranslateColorGlyphRun
ID2D1DeviceContext4::DrawColorBitmapGlyphRun
ID2D1DeviceContext4::DrawSvgGlyphRun
ID2D1DeviceContext4::GetColorBitmapGlyphImage
ID2D1DeviceContext4::GetSvgGlyphImage
```

... and all the related methods and types around them.

**Comment by shawnhar** [comment]
We actually already have an item tracking this possibility - it's #274 "Expose color fonts"
