### ISSUE TITLE
How to draw on a virtual canvas ?

### ISSUE THREAD

**Issue by ankohanse** [Microsoft/Win2D#68]
Trying to generate a Live Tile in a timer background task. As a result, I do not have access to a CanvasControl in a xaml (there is no xaml in such a background task, it is a RunTime component called by the framework).

Documentation suggests it is possible to create a 'virtual canvas' and use Win2D in background tasks, but does not give specific examples.
I've tried several strategies of creating a CanvasControl, CanvasImageSource or CanvasRenderTarget in memory, but ran into issues on each attempt.

Here is an outline of what I try to do and have tried so far:

        protected async Task TestVirtualCanvas()  
        {
            // This code is intended to run in a timer background task, 
            // so no access to a canvas in a xaml !!!

            // Attempt 1: Gives an error similar to: canvas has no device
            // CanvasControl        canvas  = new CanvasControl();
            // CanvasRenderTarget   target  = new CanvasRenderTarget(canvas, 100, 100, 96);
            // CanvasDrawingSession session = target.CreateDrawingSession();
            // canvas.Draw = OnDraw;
            // canvas.Invalidate();
            // // How do I know that drawing has finished?
            // target.SaveAsync("c:\\tmp\\icon.png", CanvasBitmapFileFormat.Png);

            // Attempt 2: Could not figure out how to get from here to SaveAsync...
            // CanvasDevice         device  = new CanvasDevice();
            // CanvasImageSource    source  = new CanvasImageSource(device, 100, 100, 96);
            // CanvasDrawingSession session = source.CreateDrawingSession( Colors.Transparent ); 

            // Attempt 3
            CanvasDevice         device  = new CanvasDevice();
            CanvasRenderTarget   target  = new CanvasRenderTarget(device, 100, 100, 96);
            CanvasDrawingSession session = target.CreateDrawingSession();

            session.Clear(Colors.Black);
            session.DrawLine(10.0f, 10.0f, 90.0f, 90.0f, Colors.Blue, 1.0f);
            session.DrawLine(10.0f, 90.0f, 90.0f, 10.0f, Colors.Blue, 1.0f);
            session.DrawCircle(50.0f, 50.0f, 30.0f, Colors.Red);

            // Would have expected something like:
            // target.FinalizeDrawingSession(session);

            await target.SaveAsync("c:\\tmp\\icon.png", CanvasBitmapFileFormat.Png).AsTask();
        }

        // Leftover from attempt 1
        private void OnDraw(CanvasControl sender, CanvasDrawEventArgs args)
        {
            CanvasDrawingSession session = args.DrawingSession;

            session.Clear(Colors.Black);
            session.DrawLine(10.0f, 10.0f, 90.0f, 90.0f, Colors.Blue, 1.0f);
            session.DrawLine(10.0f, 90.0f, 90.0f, 10.0f, Colors.Blue, 1.0f);
            session.DrawCircle(50.0f, 50.0f, 30.0f, Colors.Red);

        }

**Comment by clandrew** [comment]
Thanks for opening this issue. By 'virtual canvas', I'm assuming you mean offscreen rendering- drawing some content that isn't meant to appear on the screen, or anything like that. This definitely doable in Win2D, and perhaps we can improve the documentation in this.

You can draw directly to a CanvasRenderTarget by using its CreateDrawingSession method. This works without any XAML control. 

How about something like this?
`

        async void DrawMyIconToVirtualCanvasAndSaveToDisk()
        {
            CanvasDevice myDevice = new CanvasDevice();

            // 100 x 100 sized icon at 96 DPI
            CanvasRenderTarget target = new CanvasRenderTarget(myDevice, 100.0f, 100.0f, 96);

            using (CanvasDrawingSession session = target.CreateDrawingSession())
            {
                session.Clear(Colors.Black);
                session.DrawLine(10.0f, 10.0f, 90.0f, 90.0f, Colors.Blue, 1.0f);
                session.DrawLine(10.0f, 90.0f, 90.0f, 10.0f, Colors.Blue, 1.0f);
                session.DrawCircle(50.0f, 50.0f, 30.0f, Colors.Red);
            }

           string folderName = Windows.Storage.ApplicationData.Current.LocalFolder.Path;
           await target.SaveAsync(folderName + "\\" + "icon.png", CanvasBitmapFileFormat.Png).AsTask();
        }
`

**Comment by ankohanse** [comment]
Thank you so much !

 

Disposing of the DrawingSession was exactly the one step that I had missed to start the actual render….

Below is a screendump of the preliminary result.

 

Cheers,

Anko

**Comment by clandrew** [comment]
Glad this helped!

**Comment by ankohanse** [comment]
One minor adjustment: the CanvasRenderTarget will also need a dispose to prevent memory issues when called frequently. So improved solution would be:

    async void DrawMyIconToVirtualCanvasAndSaveToDisk()
    {
        CanvasDevice myDevice = new CanvasDevice();

        // 100 x 100 sized icon at 96 DPI
        using (CanvasRenderTarget target = new CanvasRenderTarget(myDevice, 100.0f, 100.0f, 96))
        using (CanvasDrawingSession session = target.CreateDrawingSession())
        {
            session.Clear(Colors.Black);
            session.DrawLine(10.0f, 10.0f, 90.0f, 90.0f, Colors.Blue, 1.0f);
            session.DrawLine(10.0f, 90.0f, 90.0f, 10.0f, Colors.Blue, 1.0f);
            session.DrawCircle(50.0f, 50.0f, 30.0f, Colors.Red);
        }

       string folderName = Windows.Storage.ApplicationData.Current.LocalFolder.Path;
       await target.SaveAsync(folderName + "\\" + "icon.png", CanvasBitmapFileFormat.Png).AsTask();
    }

**Comment by clandrew** [comment]
Definitely. This improves that code sample, so it's good you pointed that out. It may also be worthwhile to either scope the CanvasDevice or ensure the same one is used across calls.
