### ISSUE TITLE
Must I package my program to appx for using Win2D in XAML islands?

### ISSUE THREAD

**Issue by pcfulife** [Microsoft/Win2D#680]
My program is distributing at my own website in public. Anyone can download and install my program in their Windows PC. But, I need to enhance my program by using Win2D. And, I realized that I must package my program to appx which means that I must upload my program in Microsoft Store.

At past, I used NSIS software to make installer. But, after appx packaging, I need to let people register my certification (I don't have expansive code-signing certification), and change their developing settings even they are not a developer.

I hope that it will not need appx packaging anymore after .NET Core 3.0 and Windows 10 19H1 released.

**Comment by shawnhar** [comment]
This isn't really a Win2D question, but maybe someone here happens to know the answer anyway?

**Comment by pcfulife** [comment]
@shawnhar Yes, this is because using WinRT C++ API to managed process technology needs appx packaging. But, I minunderstood this limitation can be controlled by Win2D (or other WinRT controls which uses that technology). I should have reported this at StackOverflow.

**Comment by cherepets** [comment]
@pcfulife There are public deployment APIs so you can ship an .exe installer that will download (or already contain) .appx and automatically deploy it.
You can also try to implement some kind of auto-update system.
https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.addpackageasync

**Comment by pcfulife** [comment]
@cherepets Oh, interesting API. But, I think that it needs valid code-signing certification and changing developer settings. I will test this API.

**Comment by cherepets** [comment]
@pcfulife There are basically three modes: "_Microsoft Store apps_", "_Sideload apps_" and "_Developer mode_". Deployment API doesn't work only "_Microsoft Store apps_" mode and default one in Windows is "_Sideload apps_".

The certificate can be created and imported in runtime.
There's a good example here: https://github.com/aL3891/AppxInstaller/blob/master/AppxInstaller/MainWindow.xaml

**Comment by pcfulife** [comment]
@cherepets Wow, It works! Thank you!
