### ISSUE TITLE
Create a magnify effect using a backdropbrush.

### ISSUE THREAD

**Issue by brentafis** [microsoft/Win2D#681]
I've been working on an app that will have the ability to magnify a certain portion of itself based on where the user is touching/pointing.  The app uses Windows.UI.Composition in conjunction with Win2D.  I've been trying to use a CompositionBackdropBrush with a ScaleEffect or Transform2DEffect to achieve a magnifying effect.  The app throws whenever the backdrop brush is assigned as the source parameter in either of these cases.  ScaleEffect clearly states it's not available for composition [NoComposition] but it seems like Transform2DEffect should work.

I have 2 questions:

1. Is what I'm trying to do (magnify the contents of a backdrop brush) possible?  And if so, what's the best approach?

2. I'm curious why a ScaleEffect isn't available for use in Composition.  Is this because you would normally scale the visual itself?  Are there any plans to make ScaleEffect available in the future?

Thanks.

**Comment by krenner** [comment]
Hi brentafis 
CompositionBackdropBrush does not support Transform2D, we have a specific solution for optimizing BackdropBrush and could not guarantee good results with transforms. You can use Transform2D with an EffectBrush if you are not concerned with effects drawn on contents underneath another visual.

Composition uses the scale property on [Visual]() for scaling so we did not have an immediate need for this type of effect.  I understand your feedback, it would be convenient.  Over time we add more and more Win2D effects as needed, I can add ScaleEffect to the our backlog.   For your scenario, if you’re not already using interaction tracker (which lets input drive the experience) you may want to.  See [Doc]() and/or [Sample code]() (sample uses scale and input).

**Comment by brentafis** [comment]
Hi krenner
Thanks for the feedback, I'll check out the interaction tracker sample to get a better understanding.  

Can you elaborate a bit on what you mean by:
> You can use Transform2D with an EffectBrush if you are not concerned with effects drawn on contents underneath another visual.  
Are you referring to my particular scenario or just in general?

**Comment by krenner** [comment]
Wow I don't know how I managed to paste the links in so horribly!  I'm adding here again for correctness and double checking in preview.   Sorry about that.
Scale property of[ Visual ](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Composition.Visual)
 [Doc](https://docs.microsoft.com/en-us/windows/uwp/composition/interaction-tracker-manipulations) and/or [Sample code](https://github.com/Microsoft/WindowsCompositionSamples/tree/master/SampleGallery/Samples/SDK%2014393/SwipeScroller).  
My comment around Transform2D support with EffectBrush was a general remark.

**Comment by brentafis** [comment]
Thanks for the update.  I've taken a look at the docs/samples.  I can see how the interaction tracker might help me determine where someone wants the magnifying effect to occur.  I'm not following or understanding how to actually achieve the magnifying effect using the samples.  Do you have any tips or suggestions for how I might be able to achieve my desired scenario?  Thanks.

**Comment by krenner** [comment]
I was thinking if it is as simple as scaling the visual with user input.  In the swipe scroller sample, a visual scales up to reveal more information about a photo when the user clicks on the visual on top of it that contains the image.  You can see the sample in action if you download our [sample app ](https://www.microsoft.com/en-us/p/windows-composition-samples/9n1h8czhbpxb?activetab=pivot:overviewtab)and navigate to Motion>Swipe Scroller.
