### ISSUE TITLE
Half width sampler

### ISSUE THREAD

**Issue by valdirSalgueiro** [Microsoft/Win2D#685]
Hello I am trying to port one shader to win2D, namely this one that converts YUV420 to RGB

https://gist.github.com/roxlu/9329339#file-yuv420p_player-h

my problem is that the shader mapping appear to be only 1:1? in the case of U and V the width and height is half of the frame size... I would expect both textures (UV) to stretch and fill the screen.

this is my current output:

![picturemessage_vqi12qtu xdm](https://user-images.githubusercontent.com/858374/54357917-e1fe4e80-463d-11e9-8e00-dc4b3eb8ae2d.png)

thanks!

**Comment by shawnhar** [comment]
Choice of texture coordinate is up to your shader code.  Depends whether you use D2DGetInput, D2DSampleInputAtOffset, or D2DSampleInputAtPosition.  There's some info about this and the SamplerCoordinateMapping properties at https://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Effects_PixelShaderEffect__ctor.htm
