### ISSUE TITLE
UWP Win2D CanvasControl keyboard input not detected

### ISSUE THREAD

**Issue by Daniel10106** [microsoft/Win2D#686]
I am trying to make a simple game engine of a moving bitmap of an orb, which moves when arrow keys are pressed. However, I`ve been continuously failing on implementing the KeyDown event.

I am using CanvasControl and UWP.
I am updating the canvas with the Invalidate() method.

Whenever I debug the game with breakpoint at the KeyDown event of the canvas, nothing happens and it doesn't fire the event at all.

I've read about focus and I've tried setting the focus to the canvas. When in Debug mode, setting the focus works but the GotFocus event isn`t fired so I am not very sure if it actually does something.

I have also read about CoreWindow but I don't quite understand it.
I will be glad if anyone give me an advice on this issue!

**Comment by spookygraveyard** [comment]
Try adding `IsTabStop="True"` to the CanvasControl XAML. 

You'll still need to get keybord focus to the CanvasControl (using `YourCanvasControl.Focus(FocusState.Keyboard)` or whatever) but it should now hold the focus, and fire your key events.

**Comment by Daniel10106** [comment]
**Thank you for the answer**
It worked instantly. I am really grateful for your answer as I`ve been struggling with this problem for months. 😅
