### ISSUE TITLE
XAML islands again

### ISSUE THREAD

**Issue by devsko** [microsoft/Win2D#688]
With #675 the CanvasControl got usable in XAML islands. This works very well but now i figured out how the visibility detection of XAML islands will work in Windows 19H1. I think the best solution is to detect visibility by default but leave the `VisibilityMode` as is. I would create a PR but it would be the first time that i am writing C++ in the last 20 years so maybe somebody else has the time to do this - what would be very nice. In C# it would look like this:
``` C#
        public void RegisterEventHandlers()
        {
            // XamlRoot exists in 19H1 and above
            if (ApiInformation.IsTypePresent(typeof(XamlRoot).FullName))
            {
                this.XamlRoot.Changed += XamlRoot_Changed;
            }
            else
            {
                Window.Current.VisibilityChanged += Window_VisibilityChanged;
            }
        }

        private void Window_VisibilityChanged(object sender, VisibilityChangedEventArgs e)
        {
            m_isVisible = e.Visible;
            WindowVisibilityChanged();
        }

        private void XamlRoot_Changed(XamlRoot sender, XamlRootChangedEventArgs args)
        {
            // This get fired for all changes (like size), not only when visibility changed
            var isVisible = this.XamlRoot.IsHostVisible;
            if (m_isVisible != isVisible)
            {
                m_isVisible = isVisible;
                WindowVisibilityChanged();
            }
        }
```
cc @lhak

**Comment by lhak** [comment]
My C++ skills are also quite basic, but I will take a look at implementing this. Should we define a new visibility mode (something like UseXamlRootHostVisibility)? This would fall back to ForceVisible if the xaml root APIs are not present and allow an application to support XAML islands on Windows 1809 and newer versions in the same way.

**Comment by devsko** [comment]
Thanks a lot. I would think, there is no need to support XAML islands prior 19H1 because there is not even a Win2D release working in this scenario (and you can still set ForceVisible manually). I wouldn't make it too complex. Just my thoughts.

**Comment by lhak** [comment]
Ok, I got something working. However, it seems that the API always returns true in XAML island scenarios even if the host window is minimized. Additionally, for UWP apps the result seems to be equal to the visibility property of the Window apps, but I am not sure if there are cases where the result might be different.

**Comment by jasonwurzel** [comment]
Hi, 
any updates on this? we are still using our own build of win2d containing devsko's fix/workaround.

**Comment by shawnhar** [comment]
There's an active pull request containing XAML island support, but still a few issues with that which need addressing before it can be merged to master.

**Comment by shawnhar** [comment]
XAML Islands is now officially supported by Win2D release 1.25.0
