### ISSUE TITLE
Issues while recreating strokes in Win2D

### ISSUE THREAD

**Issue by valdirSalgueiro** [Microsoft/Win2D#689]
I am trying to draw an InkStroke iterating each point and adding to an Vector2 list, like this:

```
var geometry = CanvasGeometry.CreatePolygon(canvasDevice, vectorPoints.ToArray());
dsOffscreen.FillGeometry(geometry, color);
```
the problem is that when there is intersection between the "path" it doesnt cannot very well as you can see. Any tips to improve this? thanks :)

![bug](https://user-images.githubusercontent.com/858374/54751264-2b5c1a00-4bb9-11e9-9d2d-73ff7671d01c.png)

**Comment by shawnhar** [comment]
If you want to preserve the original ink stroking, use https://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Geometry_CanvasGeometry_CreateInk.htm?

**Comment by valdirSalgueiro** [comment]
Yes, I use that for not animated strokes, but I need a feature like a replay, and when I use InkstrokeBuilder to build a stroke from just a handful of points + IBasicVideoEffectDefinition I get a crash.. I can try and get a minimal reproduction example if necessary, so I am trying another ways to build an stroke (without inkstrokebuilder). Another requirement is the stroke has different thickness depending on the angle (like calligraphy pen)

**Comment by shawnhar** [comment]
Doing your own stroke computations to turn points + thickness into a geometry region is certainly possible (this is what the ink system does internally after all) but it's going to be a lot of math and unlikely to 100% exactly match what you'd get from the built-in inking.
