### ISSUE TITLE
WPF Support

### ISSUE THREAD

**Issue by ButchersBoy** [Microsoft/Win2D#69]
Just watched the Build ch9 video; looks awesome.

What's the current plans for WPF support?  We write financial trading applications where the screen is busy and moving fast.  We are continually striving to improve performance, and this would be a great tool.

**Comment by clandrew** [comment]
Glad you enjoyed our talk at Build! 

Performance is important to this API. For scenarios which need to be animated quickly and smoothly, CanvasAnimatedControl is geared toward that. 

We've had some questions about WPF support before. For more information, here's Issue #12. Although WPF support is not in the plans, Win2D is designed to be a rich drawing API with many familiar semantics, and the hope is you can develop your app using Win2D without sacrificing much of anything. If you come across something that's missing, definitely let us know.
