### ISSUE TITLE
How to improve performance of CanvasAnimatedControl

### ISSUE THREAD

**Issue by MuziburRahman** [microsoft/Win2D#690]
I have a project which is a CAD software. I am expecting to draw an average of 10000 shapes per frame at 60 FPS. But I can hardly get upto 2000 shapes.

I have created the simplest repro of my app:
```
int upd;
long elapsed_time;

private void CanvasAnimatedControl_Draw(ICanvasAnimatedControl sender, CanvasAnimatedDrawEventArgs args)
{
    int i = upd;
    
    for (; i < upd+ 200; i++)
    {
        for (int j = 100; j < 140; j++)
        {
            args.DrawingSession.DrawCircle(new Vector2(i, j), 15, Colors.DodgerBlue);
        }
    }

    if (upd % 20 == 0)
    {
        double fps = 2e8 / elapsed_time;   /// 20 / (elapsed_time / 10_000_000 )
        args.DrawingSession.DrawText(fps.ToString(), new Vector2(500, 400), Colors.Red);
        elapsed_time = 0;
    }

    upd++;
    if (upd + 200 > 1000)
        upd = 0;
}

private void CanvasAnimatedControl_Update(ICanvasAnimatedControl sender, CanvasAnimatedUpdateEventArgs args)
{
    elapsed_time += args.Timing.ElapsedTime.Ticks;
}
```
As you can see, I am showing the FPS value on the screen.
And for 200 * 40 = 8000 shapes, I get 20 fps only  😐😐.

The XAML is this:

```
<xaml:CanvasAnimatedControl 
    Draw="CanvasAnimatedControl_Draw" 
    Update="CanvasAnimatedControl_Update"
    ClearColor="Black"
    IsFixedTimeStep="True"
    TargetElapsedTime="0:0:0.01667"/>
```

What should I do to boost performance?

**Comment by MuziburRahman** [comment]
By the way, if I use a Rectangle(15 width, 15 height), the FPS rises to 45, but still not 60

**Comment by shawnhar** [comment]
Start by taking a look at CanvasCachedGeometry.

For very complex scenes, you may also want to cache intermediate results in a CanvasRenderTarget that can be reused across multiple frames rather than re-rasterizing every component from scratch each time.
