### ISSUE TITLE
Docs issue for CanvasPrint

### ISSUE THREAD

**Issue by jevansAN** [Microsoft/Win2D#691]
The page at https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Printing_CanvasPrintDocument.htm
is missing the end of a sentence that I was hoping would tell me how to know which page is being requested in the Print event. The sentence as it stands reads,

"The application can then draw each page in turn using"

**Comment by damyanp** [comment]
That's meant to be a link to CanvasDrawingSession.

Here's the source for the documentation:

`
        <p>
          When the user chooses to print the <see
          cref="E:Microsoft.Graphics.Canvas.Printing.CanvasPrintDocument.Print"/>
          event is raised.  The application can then draw each page in turn
          using <cee
          cref="M:Microsoft.Graphics.Canvas.Printing.CanvasPrintEventArgs.CreateDrawingSession"/>
        </p>`
`

Note the `<cee` that should actually be `<see`!

**Comment by jevansAN** [comment]
Thanks very much. I still wonder if there is any parallel to the PageNumber property provided in the CanvasPreviewEventArgs. For some reason CanvasPrintEventArgs does not have such a property so it's not clear how the app will know which page is requested.

**Comment by damyanp** [comment]
This is elaborated a little here: https://microsoft.github.io/Win2D/html/E_Microsoft_Graphics_Canvas_Printing_CanvasPrintDocument_Print.htm

You need to loop through all the pages you want to print.  Each CanvasDrawingSession you create from the be for a single page.  You can use PrintTaskOptions to figure out which pages you should print, and what the size of that page is.

You can see some of this in action in ExampleGallery: 

https://github.com/Microsoft/Win2D/blob/61159ccfa0b7022e367212ad5ca381b8c34d150a/samples/ExampleGallery/PrintingExample.xaml.cs#L218

**Comment by jevansAN** [comment]
I appreciate that quick response! This ought to help.

Jeff


On Apr 8, 2019, at 2:16 PM, Damyan Pepper <notifications@github.com> wrote:

This is elaborated a little here: https://microsoft.github.io/Win2D/html/E_Microsoft_Graphics_Canvas_Printing_CanvasPrintDocument_Print.htm <https://microsoft.github.io/Win2D/html/E_Microsoft_Graphics_Canvas_Printing_CanvasPrintDocument_Print.htm>
You need to loop through all the pages you want to print. Each CanvasDrawingSession you create from the be for a single page. You can use PrintTaskOptions to figure out which pages you should print, and what the size of that page is.

You can see some of this in action in ExampleGallery:

https://github.com/Microsoft/Win2D/blob/61159ccfa0b7022e367212ad5ca381b8c34d150a/samples/ExampleGallery/PrintingExample.xaml.cs#L218 <https://github.com/Microsoft/Win2D/blob/61159ccfa0b7022e367212ad5ca381b8c34d150a/samples/ExampleGallery/PrintingExample.xaml.cs#L218>
