### ISSUE TITLE
Loading resources outside of CreateResources

### ISSUE THREAD

**Issue by bitviper** [Microsoft/Win2D#693]
Please correct the code entitled above at the link: https://microsoft.github.io/Win2D/html/LoadingResourcesOutsideCreateResources.htm

I'm using VS 2019 Comm. Ed Win10 Build 10 (17763) - (15063), Win2d 1.23 and the code no longer works! 
At code:         
async Task LoadResourcesForLevelAsync(ICanvasAnimatedControl resourceCreator, int level)
        {
            return GameLoopSynchronizationContext.RunOnGameLoopThreadAsync(resourceCreator, async () =>
            {
               // levelBackground = await CanvasBitmap.LoadAsync(resourceCreator, ...);
              //  levelThingie = await CanvasBitmap.LoadAsync(resourceCreator, ...);
                // etc.
            }
        }

I get error: "The name GameLoopSynchronizationContext does nor exist in the current context."
Thanks in advance.

**Comment by shawnhar** [comment]
You need this code as well:

https://github.com/Microsoft/Win2D-Samples/blob/master/ExampleGallery/Infrastructure/GameLoopSynchronizationContext.cs

(there's a comment about that at the bottom of the article)

**Comment by bitviper** [comment]
Thanks

**Comment by bitviper** [comment]
Thanks so much!!! But now I have another error with the async Task:
        async Task LoadResourcesForLevelAsync(ICanvasAnimatedControl resourceCreator, int level)
        {
            return GameLoopSynchronizationContext.RunOnGameLoopThreadAsync(resourceCreator, async () =>
            {
                levelBackground = await CanvasBitmap.LoadAsync(resourceCreator, "msappx:///Assets/Backgrounds/set1_1.png");
            }
        }

At the return statement I get Error: This is an async method that returns a Task, a return keyword must not be followed by an object expression!!!!
