### ISSUE TITLE
Need a good way to store "freehand" drawing.

### ISSUE THREAD

**Issue by Ulucai** [microsoft/Win2D#696]
I am trying to create a map-maker for tabletop RPGs.

Right now I am trying to make a "freehand" drawing feature.
Basically what I did was:
Load some texture in a `CanvasBitmap`. 
Use it to create a `CanvasImageBrush`.
Then, whenever the mouse is pressed, the app saves its location into a `List<Vector2>`.

On the drawing Loop It just go through the list and use each item to `Draw.FillCircle()`

I wonder if Win2d has: 
Some kind of container to store the "painted" area.
A feature that would aid me into checking if an area is already painted by said texture to avoid waste.

**Comment by shawnhar** [comment]
If you want to store a region in vector format, look into CanvasGeometry and its associated set of manipulation methods.  Win2D has very rich functionality for geometry operations such as intersection and hit testing.

If you want to store in bitmap format, look at CanvasRenderTarget.
