### ISSUE TITLE
Semi-transparent Bitmaps are not being rendered correctly

### ISSUE THREAD

**Issue by EngineLessCC** [microsoft/Win2D#697]
Issue:
Not being rendered correctly

Example:
[example.zip](https://github.com/Microsoft/Win2D/files/3142352/example.zip)

How to reproduce it:
Use CanvasBitmap.LoadAsync/.CreateFromXXXX or open it using Win2D example -> Virtual Bitmap

**Comment by shawnhar** [comment]
Win2D (like the Windows Imaging Codec that it is built on top of) has only very partial support for the DirectX .dds file format.  This is mostly only useful for loading block compressed BC format texture data (see http://microsoft.github.io/Win2D/html/BlockCompression.htm).

For more general purpose usage and non-BC texture formats, you should use a standard image format like .png

**Comment by EngineLessCC** [comment]
I was parsing dds manually aswell(loaded texture raw without header and with correct pixelformat) and formats like ARGB32/A8R8G8B8 and rgba32 have those issues aswell, while compared to other render engines/tools like unity using the same parse-lib, results are as expected.
Im not sure if it is a dds-only issue (tga is affected aswell)

**Comment by shawnhar** [comment]
Alpha blending definately works correctly in Win2D, so you must not be loading the data correctly.  It's impossible to tell from the info in this bug report, but wild guess maybe you are using the wrong premultiplied alpha format?
