### ISSUE TITLE
Eraser without using InkCanvas

### ISSUE THREAD

**Issue by vas2** [microsoft/Win2D#698]
Im trying to erase the strokes or bitmaps drawn in my CanvasControl, the solution that was found was to draw the same color as the background but that seems a problem when I add a background image to my canvas. It is possible to remove only the Strokes drawn and saved in the Drawing Session?

**Comment by shawnhar** [comment]
I don't understand what you mean by saving things in a drawing session?  Win2D is an immediate mode drawing API, so it just draws whatever you tell it to - there's no saving of anything other than if you explicitly tell it to store things into a CanvasCommandList or CanvasRenderTarget.

If you want to get rid of something you previously drew, you could either redraw everything except for the specific thing you want to remove, or you could redraw everything including the bit you want to erase, then draw whatever the background to the erased part was over the top of (which produces the same result as if you didn't draw that bit in the first place).
