### ISSUE TITLE
CreateResources event vs Page ctor/OnNavigatedTo/Loaded Event

### ISSUE THREAD

**Issue by suprak** [Microsoft/Win2D#70]
It's not very clear why the animated canvas has a dedicated event for loading resources when there are already established methods for object initialization.

**Comment by shawnhar** [comment]
Damyan wrote a series of articles that walk through the rationale and history of this design:

http://blogs.msdn.com/b/win2d/archive/2014/12/01/handling-lost-devices-in-win2d.aspx
http://blogs.msdn.com/b/win2d/archive/2014/12/02/resource-creation-in-win2d.aspx
http://blogs.msdn.com/b/win2d/archive/2014/12/03/async-loading-is-harder-than-it-looks.aspx
http://blogs.msdn.com/b/win2d/archive/2014/12/04/rejected-designs-for-async-loading.aspx
http://blogs.msdn.com/b/win2d/archive/2014/12/05/async-resource-loading-in-win2d.aspx
