### ISSUE TITLE
Cant get an array with points and graph it drawcurve()

### ISSUE THREAD

**Issue by krlos9500** [microsoft/Win2D#701]
I have a problem filling an array with points that I get from 1 temperature variable. for example that "x" is the sampling time for example 10 seconds and that it saves 1 sampling per second then I would like

(x, Temperature variable) example (1, 24.6) (2,24.5) (3,25.3) (4, 26.5) ........... (10,28.5)
then these 10 results graph them with "drawcurve"
Here is an example of the code.
Private Sub chart()
    Dim j As Integer
    Dim pen As New Pen(Color.Black, 1)
    Dim g As Graphics
    g = PictureBox1.CreateGraphics
    g.SmoothingMode = Drawing2D.SmoothingMode.AntiAlias
    g.Clear(Color.White)
    Dim myPointsArray As New List(Of PointF)
    myPointsArray.Clear()

    For j = 1 To 10 Step 1
    myPointsArray(j) = New PointF(k, LDR_1L)
    NEXT

g.drawcurve(pen, myPointsArray.ToArray, 1.5F)

End Sub

HELP PLEASEEEE :(

**Comment by shawnhar** [comment]
I think you asked this question in the wrong place, as from the code shown above it doesn't look like you are using Win2D at all.
