### ISSUE TITLE
Unexpected clipping behavior when using RenderTransform on CanvasControl

### ISSUE THREAD

**Issue by jefffhaynes** [microsoft/Win2D#708]
I'm working on a deep zoom capability wherein the outer control is being scaled up while individual tiles are being scaled down as they are loaded.  This somewhat works when the tiles are Image controls.  However, I would like to use a CanvasControl for the tiles.  Unfortunately when I do that, the RenderTransforms don't superimpose the way I would expect and I get a clipping region around the tile like this:

![image](https://user-images.githubusercontent.com/9734727/60440376-b306eb00-9be2-11e9-99ab-c71bf6392064.png)

You can see the canvas control is scaled to the correct amount but the underlying graphic is not.

I'm scaling the tile like this:

```c#
canvas.Scale = new Vector3((float) scale);
```

and the entire control like this:

```c#
var transform = (CompositeTransform) RenderTransform;

var scale = Math.Pow(2, zoom - 1);

var scaleDelta = scale - transform.ScaleX;

transform.TranslateX += -point.Position.X * scaleDelta;
transform.TranslateY += -point.Position.Y * scaleDelta;
transform.ScaleX = scale;
transform.ScaleY = scale;
```

If I do the same thing with an Image control it works but then I run into trouble when the control size is less than one pixel (despite having layout rounding disabled).

**Comment by shawnhar** [comment]
I don't completely follow what you are doing here, but it looks like you are purely using XAML transform properties rather than any Win2D APIs?   In that case the CanvasControl will rasterize whatever Win2D contents you draw into it at whatever size the control currently has, after which the XAML compositor will apply bitmap image scaling to that Win2D result based on these XAML transform properties.

When doing this kind of thing you need to pay careful attention to how pixel density of the Win2D control corresponds with pixel density of the final output (i.e. how much your image is being bitmap scaled) and also be careful that the XAML tree isn't set up in such a way that it will automatically resize the WIn2D control every time you change these properties.

For a likely easier way to implement zoom, have you looked at the Mandelbrot example?

**Comment by jefffhaynes** [comment]
Sorry, I'm using a CanvasControl as the basis for the tiles.  Hence, Win2D.

I'm not sure the Mandelbrot approach will work since this is primarily for a map, which is arranged into logical tiles.

Here is the repo and the line where I create a CanvasControl [https://github.com/jefffhaynes/LocalMap/blob/master/LocalMap/MapPanel.cs#L231](url)

**Comment by jefffhaynes** [comment]
As to pixel density, I don't think that's a problem.  As the panel is scaled up the tiles are correspondingly scaled down.  You can see from the image shown that there is little degradation due to scaling.  I believe the main issue is the clipping.  You'll note in my code I'm wrapping the CanvasControl in a Viewbox to solve the problem for now but I would rather not if possible.

**Comment by shawnhar** [comment]
I think you will get better results using the virtual control approach shown in the Mandelbrot example, and drawing your tiles as needed within a single larger control.  Using a separate canvas control per tile is going to be a lot of overhead.

With your current approach I suspect you are rasterizing intermediates at excessively high resolution.  This may work for a while, but is likely to run out of video memory at some point.  That said I don't fully understand your current design.

**Comment by jefffhaynes** [comment]
Ah, ok I misunderstood.  Let me try that approach.

**Comment by jefffhaynes** [comment]
I got this working with the map.  Unfortunately if you zoom in far enough in the Mandelbrot example, you'll see everything go black (or become extremely blocky).  I'm experiencing the same thing with the map.  Any idea why this happens with the Mandelbrot?

**Comment by shawnhar** [comment]
You're likely running into floating point precision issues.  For high levels of zoom, a 24 bit mantissa runs out surprisingly quickly!   Floats just aren't enough to zoom smoothly from eg. viewing a whole planet to street map level of detail.  To handle such scales you'll need to adopt some more hierarchical system where rendering switches to entirely different data sets using different coordinate systems per region of zoom.

**Comment by jefffhaynes** [comment]
That was my first thought but I don't think that's what it is.  I treat each tile in the hierarchy as a "full size" tile and it is only in the session transform that scaling occurs.  Take a look here:

![image](https://user-images.githubusercontent.com/9734727/60528998-a1494480-9cc3-11e9-9da2-f20f8da9a0e8.png)

Have you tried the Mandelbrot example?  You don't have to zoom very far for things to go sideways and I don't immediately see why that example would suffer from the mantissa issue.

**Comment by jefffhaynes** [comment]
It's worth noting that at this point the rect width and height is 1.0.  Interestingly, this was the same place the Image control failed as well.  It's not clear to me why there would be anything magic about a rect with dimension 1.0 though.

**Comment by shawnhar** [comment]
Are you aware of the difference between logical and physical coordinate systems?  When you zoom by adjusting DpiScale, these become /extremely/ different!

Zooms of more than a few orders of magnitude (which looks like what you are doing here) require more sophisticated techniques than just applying scale transforms within a single 32 bit float coordinate system.

**Comment by jefffhaynes** [comment]
The problem occurs at 10x zoom.

**Comment by jefffhaynes** [comment]
So just to be clear, the Mandelbrot example specifies a max zoom of 8000 but does not function past 1000.  Is that your intention?

**Comment by shawnhar** [comment]
The Mandelbrot example does not attempt to deal with precision at extreme zoom factors, so yes, it will happily let you zoom past where the math actually works right.

**Comment by jefffhaynes** [comment]
Ok, it sounds like the CanvasVirtualControl won't actually work for my use case then.  Thanks for your help.
