### ISSUE TITLE
CanvasBitmap created from SoftwareBitmap has incorrect Size

### ISSUE THREAD

**Issue by Dragonwood23** [microsoft/Win2D#710]
Hi,
I am having the following problem using Win2D: I am reading an image file into a SoftwareBitmap, which I then use to create a CanvasBitmap using CanvasBitmap.CreateFromSoftwareBitmap(). I then alter the image (in the CanvasBitmap) using effects from Microsoft.Graphics.Canvas.Effects. After applying the effect(s) I want to write the processed image back to a file. However, in the test case I am using, I have a JPEG file with a resolution of 2288x1712, which I read into a SoftwareBitmap. The CanvasBitmap returned by the static CreateFromSoftwareBitmap method (using this SoftwareBitmap) has a Size property of 732.16 x 547.84 and a SizeInPixels property of 2288 x 1712 (same as the source file). Thus, the JPEG file I write has a resolution of 732x548. I am using C#/XAML to do all of this. I have been trying, and failing, to create a CanvasBitmap that has Size and SizeInPixels to be the same so that my output file does not get scaled down.

I create the initial SoftwareBitmap this way:
StorageFile imageFile; // returned by a FileOpenPicker, typical code, not shown

// I then do this:
SoftwareBitmap softwareBitmap = null;
using (IRandomAccessStream stream = await imageFile.OpenAsync(FileAccessMode.Read))
 {
    BitmapDecoder decoder = await BitmapDecoder.CreateAsync(stream);
    softwareBitmap = await decoder.GetSoftwareBitmapAsync();
}

// so far so good, typical stuff... later I do this:
CanvasBitmap canvasBitmap = CanvasBitmap.CreateFromSoftwareBitmap(myCanvas.Device, softwareBitmap);
// "myCanvas" is the Name of a CanvasControl created using XAML

The canvasBitmap has the incorrect Size (but not SizeInPixels) as described above, and I haven't been able to figure out why. This is before I even alter the image using Canvas Effects, which are actually working fine. The problem is that the image is "downsized" right from the start. I have seen other code that does this by loading the image directly into the CanvasControl like this:

StorageFile file // from FileOpenPicker
CanvasBitmap canvasBitmap = null;
using (var stream = await file.OpenReadAsync())
{
   canvasBitmap = await CanvasBitmap.LoadAsync(myCanvas.Device, stream);
}
And this works fine, Size and SizeInPixels are the same when this is done.
But in my case I need my image in a SoftwareBitmap so I can do other processing of the image data using non-Win2D techniques. I am fairly new to Win2D and still trying to work through these things, and I have been unable find any post any where that addresses this particular issue.

Any suggestion that somebody who is Win2D savvy has will be greatly appreciated.
Thanks in Advance,
Robert

**Comment by Dragonwood23** [comment]
I have found an alternative way of creating a CanvasBitmap that has the correct 'Size' member and works as expected.

For Those It May Concern (if any):
// Instead of:
CanvasBitmap canvasBitmap = CanvasBitmap.CreateFromSoftwareBitmap(myCanvas.Device, softwareBitmap);

The following code produces the expected result:
// Create the CanvasBitmap this way...
byte[] imageBytes = new byte[4 * softwareBitmap.PixelWidth * softwareBitmap.PixelHeight];
softwareBitmap.CopyToBuffer(imageBytes.AsBuffer());
DirectXPixelFormat format = DirectXPixelFormat.B8G8R8A8UIntNormalized;
CanvasBitmap canvasBitmap = CanvasBitmap.CreateFromBytes(myCanvas.Device, imageBytes, softwareBitmap.PixelWidth, softwareBitmap.PixelHeight, format);

Notes:
1. AsBuffer() requires: using System.Runtime.InteropServices.WindowsRuntime;
2. Assumes SoftwareBitmap has format BGRA8, hence you will need to make sure to use the appropriate pixel fomat for the SoftwareBitmap used, this may also require a different number of bytes/pixel than 4 when the byte[] is created.

Regards,
Robert

**Comment by shawnhar** [comment]
This is a DPI issue, so start by reading http://microsoft.github.io/Win2D/html/DPI.htm

Size being different from SizeInBytes indicates that your bitmap has a DPI other than 96.   The Size isn't incorrect, it's just measured in DIPs rather than pixels.

Options are to make your Win2D code handle non-96 DPI correctly, or if you want to assume DPI = 96, make sure your incoming bitmap has that expected DPI.
