### ISSUE TITLE
Applying ChromaKey To UI Elements in real-time

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Win2D#713]
I'm trying to apply a chroma key to a UWP UIElement. It can be anything, a webview, or media element. In case you are coming from the old days of Silverlight :) it was possible to do it with HLSL PixelShared. 

Taking a rendering of the element, applying the effect and drawing it back to the screen is possible, but pretty low FPS and high overhead for real-time use. Any suggestions?

**Comment by shawnhar** [comment]
The efficient way to do such things for realtime use is via the Windows.UI.Composition functionality rather than directly using Win2D.  Unfortunately, though, Windows.UI.Composition does not support ChromaKeyEffect, so I think there's no option other than to go the slow readback route.
