### ISSUE TITLE
Suggestion: API to know if CanvasGeometry intersect

### ISSUE THREAD

**Issue by adrientetar** [microsoft/Win2D#715]
There are boolean operation APIs in Win2D, but afaict no API to tell if a given set of paths intersect e.g. bool CanvasGeometry::Intersects(CanvasGeometry other). That would be nice to have for UI applications where when doing a boolean operation:
1. You want to know if paths intersect so you can skip adding to the undo stack if they don't
2. You want to grey out the boolean operations button if it has no effect.

**Comment by shawnhar** [comment]
See http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Geometry_CanvasGeometry_CompareWith.htm

**Comment by adrientetar** [comment]
@shawnhar, thanks Shawn. How would I go about checking for intersections within a given CanvasGeometry? like if I have multiple subpaths. Trivially I could take out each subpath one after the other and compare with that but would there be a way that doesn't require multiple calls?

**Comment by shawnhar** [comment]
You can only intersect at the geometry level.

**Comment by adrientetar** [comment]
I understand you mean Direct2D cannot check for self-intersections, in which case I'll put up a feature request for that.

**Comment by shawnhar** [comment]
You need to break each thing you want to intersect with out into a separate geometry object.

**Comment by adrientetar** [comment]
![image](https://user-images.githubusercontent.com/1250894/62722873-a494c600-ba0f-11e9-9983-8d44d075e858.png)


How about checking if a given path self-intersects? There's no way to detect that it seems, even though doing a boolean union on such a path would effectively change its geometry.

**Comment by clandrew** [comment]
You might be able to take an Outlined version of your geometry, subtract-combine your original geometry, and test that area is nonzero.
