### ISSUE TITLE
CanvasControl position changed when applying the effect?

### ISSUE THREAD

**Issue by SanthiyaArulsamy** [microsoft/Win2D#717]
Hi,

I am trying to draw the image over the image with blur effect, but the CanvasControl size is less than the existing Image control.

Sample: https://github.com/SanthiyaArulsamy/Win2DSample/tree/master/CanvasControl_DrawingSession

Refer my code:
` <Grid x:Name="imageGrid">
            <Image x:Name="image" Source="Flower1.jpg" HorizontalAlignment="Left" VerticalAlignment="Top"
                   Height="500" Width="500"/>
            <canvas:CanvasControl x:Name="canvas" Draw="Canv_Draw" Height="500" Width="500"
                                  HorizontalAlignment="Left" VerticalAlignment="Top"
                                  CreateResources="Canv_CreateResources" Visibility="Collapsed"/>
        </Grid>
        
 private void Canv_Draw(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args)
        {
            args.DrawingSession.Units = CanvasUnits.Pixels;
            args.DrawingSession.DrawImage(canvasEffect);
        }
        private void Canv_CreateResources(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
        {
            args.TrackAsyncAction(CreateResourcesAsync(sender).AsAsyncAction());
        }
        async Task CreateResourcesAsync(CanvasControl sender)
        {
            CanvasBitmap = await CanvasBitmap.LoadAsync(sender, "Flower1.jpg");
            canvasEffect = new HueRotationEffect();
            canvasEffect.Source = CanvasBitmap;
            canvasEffect.Angle = 250;
        }`

Input Image:
![image](https://user-images.githubusercontent.com/28334651/63419828-1c58ec80-c423-11e9-81af-51742852d88e.png)

Output Image:
![image](https://user-images.githubusercontent.com/28334651/63419773-02b7a500-c423-11e9-8e43-2fc7856dd66e.png)

My question is:
How to apply the effect for the image over the existing image size?

I am missing something in this sample. Could help me to draw the image?

**Comment by shawnhar** [comment]
This looks like a DPI issue.  Why are you specifying CanvasUnits.Pixels?  That's unlikely to be the right thing as it then requires you to manually be aware of different coordinate systems and apply all the necessary dip/pixel conversions.

More info: http://microsoft.github.io/Win2D/html/DPI.htm

**Comment by SanthiyaArulsamy** [comment]
Yes it is DPI issue. I don't know how to calculate the DPI value of the drawing session. Could please help me to find out the DPI of the drawing session? I prepared the sample. Sample: https://github.com/SanthiyaArulsamy/Win2DSample/tree/master/FilterUWP_Mod

**Comment by shawnhar** [comment]
Is there a reason you are not operating in DIPs?  That's usually the better way to go with Win2D, as the system is designed to handle all these things for you.

If you want to control DPI manually yourself, please start by reading the article I linked to above.

**Comment by SanthiyaArulsamy** [comment]
No reason.. Can you explain me how to use the DIPs to apply the effect for image?
