### ISSUE TITLE
Jitter in sample app

### ISSUE THREAD

**Issue by JRehn** [Microsoft/Win2D#72]
Hi,
Testing the Win2D sample app on Windows 8.1 (desktop). When I run the "Animated Control" and "Layers" samples I experience jitter every 5-10th second. Is this a known issue?
I work with performance critical video streaming applications where jitter is a big problem and I have high hopes for Win2D!

Best regards
/JRehn

**Comment by shawnhar** [comment]
This is not a known issue and I don't see the problem on either of my machines.

Is the jitter purely visual, or do you also see dropped frames in the scrolling updates-per-draw graph (at the bottom right of the animated control example).

**Comment by JRehn** [comment]
Thanks for your reply! It is purely visual, there is no indication in the graph for the default TargetElapsedTime. There is a small jack in the update every 5-10 seconds or so.
We have observed the same problem with CompositionTarget.Rendering event.

**Comment by shawnhar** [comment]
Interesting, so the software timing is all happening as expected which implies the issue you see is happening at some lower level in the stack.

What hardware is this on?   In particular what type of display, and what refresh rate is it running at?  Do you see the same issue on a range of machines or just one type?

**Comment by JRehn** [comment]
We have seen this on several types of hardware. I'm running dual monitors Dell U2412M and Samsung SyncMaster 2443, both at 59 Herz with a nVidia GT 640 card 2gb dedicated video memory.

**Comment by shawnhar** [comment]
I'm closing this issue as I don't think there is anything actionable for Win2D to fix here.  I don't see the described symptoms on any of the machines I have here to test, which makes me think it's a hardware or driver problem on your machine.  Especially since you see the same problem when using CompositionTarget.Rendering, I'm confident this is not a Win2D bug.
