### ISSUE TITLE
The PDF rendering component; hyperlinks; text retrieval

### ISSUE THREAD

**Issue by verelpode** [microsoft/Win2D#720]
Hello, I'm having a hard time trying to determine which repo is right for this issue.  Is [Windows.Data.Pdf.PdfDocument](https://docs.microsoft.com/en-us/uwp/api/windows.data.pdf.pdfdocument) internally implemented as a wrapper around some PDF rendering component in Win2D, or DirectX, or WinUI, or ...?

The users of our app have reported the following as a bug:  When a PDF page contains a clickable underlined hyperlink, it renders correctly but does nothing when clicked.  Our users expected a webpage to open when they clicked on a hyperlink, in the same manner as how clickable links work in other PDF viewers such as Adobe Reader, and the built-in PDF viewers in MS Edge and Google Chrome.

Thus I'd like to suggest the following solution to this problem.  I suggest that [Windows.Data.Pdf.PdfPage](https://docs.microsoft.com/en-us/uwp/api/windows.data.pdf.pdfpage) support a way of retrieving the text (plus bounding rectangles) in the `PdfPage` in the same manner as how the PDF viewer in the Microsoft Edge app operates.  Multiple reasons exist to explain why this functionality is needed:

1. To solve the aforementioned problem where users send bug reports saying that clickable hyperlinks fail to work when clicked.
2. To support the ability to select text and copy to clipboard.
3. To support a PDF search/find function that allows users to search for text inside PDF pages or documents (the same as the "Find" textbox in Edge's PDF viewer).

To clarify, I don't mean that `Windows.Data.Pdf.PdfPage` should directly support the above 3 functions, rather I mean that it should provide the minimum functionality necessary in order to allow app developers to create the above 3 functions in their own apps by extending the basic functionality provided by `Windows.Data.Pdf.PdfPage`.

The API could be like this:

```
public class PdfPage
{
    ...
    public PdfTextElement[] GetTextElements(Windows.Data.Pdf.PdfPageRenderOptions renderOptions);
    ...
}

public class PdfTextElement
{
    public string Text { get; }

    // CultureInfo is the culture/language associated with the text element, if known, otherwise null.
    public System.Globalization.CultureInfo CultureInfo { get; }

    // If the PdfTextElement instance represents a clickable hyperlink, then DestinationUri is 
    // the URI that should be opened when the link is clicked.
    // Otherwise if the PdfTextElement instance is not a hyperlink, then DestinationUri is null.
    public string DestinationUri { get; }

    // The smallest rectangle that fully encloses/contains the text element.
    public Windows.Foundation.Rect Bounds { get; }

    // GetSubstringBounds gets the bounding rectangle of the specified substring of the text element.
    // The parameters of GetSubstringBounds are the same as System.String.Substring(int, int).
    public Windows.Foundation.Rect GetSubstringBounds(int startIndex, int length);

} // class PdfTextElement
```

**Comment by vrgadekar** [comment]
Windows.Data.Pdf API functionality is currently limited to only the rendering of PDF documents. Interaction with content, like activating links in your case, is not supported. We do plan to enhance these APIs to have this functionality in future but it is not in our short term roadmap. For now, you may have to try other PDF SDKs available that support interactive features. 
- (PM @ Microsoft)

**Comment by verelpode** [comment]
Hello @vrgadekar

Our end-users view it as a bug, despite the fact that technically it's not a bug.  i.e. from the perspective of end-users, they see hyperlinks with underline and a bright color (usually blue), and so they cannot understand why it's not a bug when nothing happens when they click these hyperlinks.

Obviously what you said is correct and technically this is a case of unsupported functionality, not a bug, but our end-users are not software engineers, therefore they cannot understand this engineering distinction.  I don't blame them; it's not their job area.

It would be great to have this functionality in the next or future version.
Thanks for your reply -- it helped us with planning.

**Comment by vrgadekar** [comment]
@verelpode I understand that accessing links is something that users would expect. We will plan and add the support. But no timeline clarity as of now.

**Comment by verelpode** [comment]
@vrgadekar -- Thanks for letting me know.  Aside from the aforementioned issue, my colleagues and I really appreciate having the `Windows.Data.Pdf` component available -- it's great!  It's very useful especially considering how PDF documents are so very commonly used nowadays (and critically essential in some enterprise workflows).  

I don't know whether your job/department covers the topic of PDF creation or only PDF viewing, but if creation is applicable for you, then here is a link to an issue that might interest you:
[API to generate PDF (or XPS) documents #672](https://github.com/microsoft/microsoft-ui-xaml/issues/672)

**Comment by shawnhar** [comment]
I'm closing this issue out as it is not about Win2D.
