### ISSUE TITLE
Drawing quality of XAML Islands is lower than pure UWP.

### ISSUE THREAD

**Issue by pcfulife** [microsoft/Win2D#725]
Thanks to developers of Win2D xaml_islands branch, I can use Win2D in WPF. But, there is a problem in XAML islands scenario. Drawing quality of Win2D in XAML Islands is lower than pure UWP. Let's see the image.

![WPF on Win2D](https://raw.githubusercontent.com/pcfulife/win2dtestimage/master/WPF720p.png)
![UWP on Win2D](https://raw.githubusercontent.com/pcfulife/win2dtestimage/master/UWP720p.png)

It is hard to recognize in GitHub issue page. I recommend to click images or download Win2DTestImages.zip file.
https://github.com/pcfulife/win2dtestimage/raw/master/Win2DTestImages.zip

I uploaded reproducible project file. This project uses VS 2019 16.2.4, .NET Core 3.0.100-rc2-014194.
https://github.com/pcfulife/win2dtestimage/raw/master/Win2DTest.zip

**Comment by shawnhar** [comment]
This should be solved in the official release which now properly supports XAML Islands
