### ISSUE TITLE
draw image+shapes, then blur. Can i do it without CanvasRenderTarget?

### ISSUE THREAD

**Issue by jtorjo** [microsoft/Win2D#732]
I need to draw an image, then some shapes on top of it, then apply a blur effect on all of them.
Right now, I'm doing this by drawing the image + shapes on a CanvasRenderTarget, and applying the blur on the CanvasRenderTarget, which I then draw on a CanvasControl.

Can I do the above without using CanvasRenderTarget?

**Comment by shawnhar** [comment]
You could alternatively use a CanvasCommandList.

**Comment by jtorjo** [comment]
Thanks! Will it be faster, or it's the same thing, under the hood?

**Comment by shawnhar** [comment]
The image needs to be rasterized either way.  It's a question of whether you want to control when that happens (perhaps reusing cached intermediates?) or just let the system manage it for you.

**Comment by jtorjo** [comment]
If I'm reading this correctly, CanvasRenderTarget could help me do some caching if/when I need it (since I can actually save it to a bitmap), while CanvasCommandList is just playable. 

Assuming I don't want to cache the contents of CanvasRenderTarget, they do have the same speed under the hood.

Is my assumption correct?

**Comment by shawnhar** [comment]
'Same' is a big word.  Ultimately these approaches will be similar (both end up rasterizing pixels internally) so I would choose based on what semantics you prefer rather than expecting a big performance difference.

**Comment by jtorjo** [comment]
@shawnhar Thanks for replying. I did get similar results indeed.

I've actually created a flag to choose between the two. 

Diffs I found:
1. CanvasCommandList doesn't need a width / height
2. CanvasCommandList needs to be recreated on each new draw (if you change anything)
