### ISSUE TITLE
pixel shader limits

### ISSUE THREAD

**Issue by jtorjo** [microsoft/Win2D#733]
I have to create some custom pixel shaders that will basically need access to **all** the image they are applied to. Such an example is a zoom_blur.

I've managed to work with MaxSamplerOffset property - basically, I set it to Max(image_size.Width, image_size.Height).

But, when the image is too big, I still get the "The graph could not be rendered with the context's current tiling settings." exception. Are there some known (or reasonable) limits I could rely on?
(if so, I could just resize the image to the biggest possible image I can use the shader on)

**Comment by shawnhar** [comment]
SamplerCoordinateMapping.Unknown would be a more direct way to describe this behavior.  Note though that this disables the ability of the implementation to split large operations up into multiple tiles, so you'll no longer be able to process large images.   Consider whether something like a zoom blur could be implemented in multiple stages instead, for instance a downscale that filters anisotropically along the blur axis, followed by the full zoom blur filter applied to that lower resolution generated image?

You may be able to adjust the limit by changing CanvasDrawingSession.EffectTileSize, but will always be limited to the max GPU bitmap size unless you're able to implement the effect in a way that is compatible with tiling.

**Comment by jtorjo** [comment]
Hi Shawn,
Thanks for the reply!
You're right - I've played around with whether to use .Unknown and .Offset - and they do offer pretty much the same thing for my needs.

I will definitely take a look at EffectTileSize - it seems to be what I need.

I am working on a video editor.
My need for this is only when saving the final video (basically, when editing the video, I will always use smaller images/videos so that everything is fast. But when saving,  i want to use images/videos as close to their original size.

For a bit of background - I'm porting my WPF app to UWP - and I've previously used some 2.0 pixel shaders. I'm porting them to what win2d uses - and clearly the first step is to just make them work. After that, I may improve on it.
