### ISSUE TITLE
When building a bundled  x86, x64, ARM store App receive unsupported API in Microsoft.Graphics.Canvas

### ISSUE THREAD

**Issue by Jeff4rr** [microsoft/Win2D#738]
From App certification test 18362:
post_process_trace_SupportedApis_12112019_124231.txt: 
-----------------------------------------------------------------------------------------------------------
te.processhost.exe Information: 0 : 12/11/2019 12:42:31 PM INFO:SupportedApis Using allow list SupportedAPIs-x64.xml
te.processhost.exe Information: 0 : 12/11/2019 12:42:31 PM INFO:SupportedApis Using allow list SupportedAPIs-x86.xml
te.processhost.exe Information: 0 : 12/11/2019 12:42:31 PM INFO:SupportedApis Using allow list SupportedAPIs-arm.xml
te.processhost.exe Information: 0 : 12/11/2019 12:42:31 PM INFO:SupportedApis Checking file C:\Program Files\WindowsApps\EFMAgency.SDX-Holiday-5Audio_6.3.9.0_x64__5bh7qh30d2jy2\Microsoft.Graphics.Canvas.dll
te.processhost.exe Information: 0 : 12/11/2019 12:42:32 PM ERROR[Test]: Method name: "CheckImportsAgainstWhiteList"
	Error: SupportedApis API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported. Microsoft.Graphics.Canvas.dll calls this API.
	Comment: N/A
te.processhost.exe Information: 0 : 12/11/2019 12:42:32 PM INFO:SupportedApis Checking file C:\Program Files\WindowsApps\EFMAgency.SDX-Holiday-5Audio_6.3.9.0_x64__5bh7qh30d2jy2\SurfaceHeadphoneDemo2.dll
te.processhost.exe Information: 0 : 12/11/2019 12:42:34 PM INFO:SupportedApis Checking file C:\Program Files\WindowsApps\EFMAgency.SDX-Holiday-5Audio_6.3.9.0_x64__5bh7qh30d2jy2\MetroLog.WinRT.winmd
te.processhost.exe Information: 0 : 12/11/2019 12:42:34 PM INFO:Check Win8P for: C:\Program Files\WindowsApps\EFMAgency.SDX-Holiday-5Audio_6.3.9.0_x64__5bh7qh30d2jy2\MetroLog.WinRT.winmd
te.processhost.exe Information: 0 : 12/11/2019 12:42:34 PM INFO:Using whitelist file C:\Program Files (x86)\Windows Kits\10\App Certification Kit\netwtlst.vwl
te.processhost.exe Information: 0 : 12/11/2019 12:42:34 PM INFO:SupportedApis Checking file C:\Program Files\WindowsApps\EFMAgency.SDX-Holiday-5Audio_6.3.9.0_x64__5bh7qh30d2jy2\SurfaceHeadphoneDemo2.exe
te.processhost.exe Information: 0 : 12/11/2019 12:42:34 PM INFO:SupportedApis Checking file C:\Program Files\WindowsApps\EFMAgency.SDX-Holiday-5Audio_6.3.9.0_x64__5bh7qh30d2jy2\Microsoft.Graphics.Canvas.winmd
te.processhost.exe Information: 0 : 12/11/2019 12:42:34 PM INFO:Check Win8P for: C:\Program Files\WindowsApps\EFMAgency.SDX-Holiday-5Audio_6.3.9.0_x64__5bh7qh30d2jy2\Microsoft.Graphics.Canvas.winmd
te.processhost.exe Information: 0 : 12/11/2019 12:42:34 PM INFO:Using whitelist file C:\Program Files (x86)\Windows Kits\10\App Certification Kit\netwtlst.vwl
te.processhost.exe Information: 0 : 12/11/2019 12:42:34 PM INFO:SupportedApis Checking file C:\Program Files\WindowsApps\EFMAgency.SDX-Holiday-5Audio_6.3.9.0_x64__5bh7qh30d2jy2\clrcompression.dll
te.processhost.exe Information: 0 : 12/11/2019 12:42:34 PM INFO:SupportedApis failed!
te.processhost.exe Information: 0 : 12/11/2019 12:42:34 PM ERROR[Test]: Method name: "ExecuteSharedTests"
	Error: SupportedApis Task failed.
	Comment: N/A
----------------------------------------------------------------------------------------------------
API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. Microsoft.Graphics.Canvas.dll calls this API.

Microsoft.Graphics.Canvas.dll is buried within Win2d.uwp.dll v1.24

1.25 is not available from NuGet yet, did it fix the __CxxFrameHandler4 ?

Thanks for your help.

**Comment by Jeff4rr** [comment]
Attached is a zip file containing the App Certification test results:
[Laptop315_AppCertFolder.zip](https://github.com/microsoft/Win2D/files/3956204/Laptop315_AppCertFolder.zip)

**Comment by shawnhar** [comment]
This looks to be the same as https://github.com/microsoft/microsoft-ui-xaml/issues/1446.  From notes in that issue, it's a Store issue that has already been fixed (but will continue to fail when you run the validation locally, until you next get an updated Insider SDK).

**Comment by Jeff4rr** [comment]
Thanks @shawnhar, that is the same issue.
