### ISSUE TITLE
WACK Supported API test Failed

### ISSUE THREAD

**Issue by mscherotter** [microsoft/Win2D#739]
Using Win2D 1.24.0 in a UWP App, I get this error when running the WACK tool:
 
Error Found: The supported APIs test detected the following errors:
API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. Microsoft.Graphics.Canvas.dll calls this API.
Impact if not fixed: Using an API that is not part of the Windows SDK for Microsoft Store apps violates the Microsoft Store certification requirements.

**Comment by shawnhar** [comment]
This is a Store issue: see microsoft/microsoft-ui-xaml#1446  for details.
