### ISSUE TITLE
Support for drawArc and fillArc methods

### ISSUE THREAD

**Issue by FabricioCabeca** [Microsoft/Win2D#74]
Thanks for this nice library, I've been playing with it in a new project and the only feature I miss right now is the possibility to draw elliptical arcs, is it in the roadmap ?

Best regards,

Fabrício

**Comment by shawnhar** [comment]
In Win2D, complex shapes such as arcs are provided by the [CanvasGeometry](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Geometry_CanvasGeometry.htm) class.   You can add them to a [CanvasPathBuilder](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Geometry_CanvasPathBuilder.htm) via the [AddArc method](http://microsoft.github.io/Win2D/html/Overload_Microsoft_Graphics_Canvas_Geometry_CanvasPathBuilder_AddArc.htm).
