### ISSUE TITLE
Elliptic arc - problem with sweep angle

### ISSUE THREAD

**Issue by MuziburRahman** [microsoft/Win2D#740]
What does the sweep angle mean in an arc whose RadiusX and RadiusY aren't same?
Notice the arc below: 

![snapshot (3)](https://user-images.githubusercontent.com/21083609/70863426-2d99ac00-1f72-11ea-9d72-0adaa5e072e3.png)

It's RadiusX = 4, RadiusY = 3, SweepAngle = 45<sup>0</sup>
Isn't it supposed to end at the straight line?
If not how do I specify the angle that I am trying to use?

**Comment by MuziburRahman** [comment]
Oh, I figured it out. SweepAngle isn't exactly the internal angle.
To draw the elliptic arc according to internal angle, sweep angle should be:
`SweepAngle = Math.Atan2((RadiusY * Math.Sin(theta), RadiusX * Math.Cos(theta));`
where, `theta` is the expected angle.
https://math.stackexchange.com/a/2463242/349919

**Comment by MuziburRahman** [comment]
Same with the `StartAngle`. How to specify these properties in normal angle?

**Comment by shawnhar** [comment]
The angles apply to a circle, which is then stretched depending on the aspect ratio of the ellipse.

See the exact computations here: https://github.com/microsoft/Win2D/blob/master/winrt/lib/geometry/CanvasPathBuilder.cpp#L162
