### ISSUE TITLE
CanvasBitmap.LoadAsync != CanvasBitmap.CreateFromSoftwareBitmap. I don't understand why?

### ISSUE THREAD

**Issue by jtorjo** [microsoft/Win2D#741]
I'm modifying my code to not be dependent of loading bitmaps in the main thread. 
CanvasBitmap.LoadAsync seems to be very slow, and I wanted to use CanvasBitmap.CreateFromSoftwareBitmap.

For some strange reason, the behavior is different:

`bitmap_ = await CanvasBitmap.LoadAsync(canvas_device_, unique_name);`

![image](https://user-images.githubusercontent.com/13891601/71353487-de5f0700-2581-11ea-961f-f63cf0ffb36d.png)

`bitmap_ = await uwp_bmp_util.load_canvas_bitmap(unique_name, canvas_device_);`

![image](https://user-images.githubusercontent.com/13891601/71353538-08b0c480-2582-11ea-9dbc-0c5a2370a269.png)

(the load_canvas_bitmap code below)

        public static async  Task<SoftwareBitmap> load_soft_bitmap(string file_name) {
            try {
                var file = await StorageFile.GetFileFromPathAsync(file_name);
                using (IRandomAccessStream stream = await file.OpenAsync(FileAccessMode.Read)) {
                    BitmapDecoder decoder = await BitmapDecoder.CreateAsync(stream);
                    // Get the SoftwareBitmap representation of the file
                    var bmp = await decoder.GetSoftwareBitmapAsync(BitmapPixelFormat.Bgra8, BitmapAlphaMode.Premultiplied);
                    return bmp;
                }
            } catch (Exception e) {
                logger.Error("can't load bitmap " + file_name + " : " + e.Message);
                return null;
            }
        }

        public static async Task<CanvasBitmap> load_canvas_bitmap(string file_name, CanvasDevice device) {
            var soft_bmp = await load_soft_bitmap(file_name);
            if (soft_bmp == null)
                return null;
            var canvas = CanvasBitmap.CreateFromSoftwareBitmap(device, soft_bmp);
            soft_bmp.Dispose();
            return canvas;
        }

Is this a bug?

**Comment by shawnhar** [comment]
These operations are not at all the same thing.  CanvasBitmap.LoadAsync does IO to read image data from a stream, plus runs a codec to decode from whatever file format the source image is using (jpeg, png, etc.).   On the other hand, CanvasBitmap.CreateFromSoftwareBitmap just takes raw pixel data that has already been loaded into memory and decoded into a SoftwareBitmap object.  In that second case Win2D is not doing any file format decoding or stream IO.

**Comment by jtorjo** [comment]
I see... I would happily use CanvasBitmap.LoadAsync myself, but it's insanely slow.
This is why I converted my code to use CanvasBitmap.CreateFromSoftwareBitmap. 

Long story short, I think somehow CanvasBitmap.LoadAsync ends up executing on the main thread, doing the decoding because of WinRT "greatness". The only way I found to circumvent that (and not force loading of the bitmap to happen on the UI thread) was with the implementation above.

Just asking - is my assumption correct? And could you improve on CanvasBitmap.LoadAsync?
(Namely, I need to load hundreds of bitmaps, and I can't wait for them to load sequencially on the main thread)

**Comment by shawnhar** [comment]
Win2D does that async work on the system threadpool (using Windows::System::Threading::ThreadPool, see https://github.com/Microsoft/Win2D/blob/master/winrt/inc/AsyncOperation.h for details).  I have no idea why this would be taking a long time in your app, sorry!

**Comment by jtorjo** [comment]
I see... My take is that somehow that it will somehow call an API that will queue the load in the UI thread... Oh well...

I believe I asked this on another issue - is it possible to load it synchronously? Then I wouldn't have to do so many workarounds...

**Comment by shawnhar** [comment]
I don't see anything in the loading code that would synchronize with the UI thread - it's a pretty straightforward threadpool dispatch up until the calling code waits for the async operation to complete.

There are no synchronous file IO APIs in Win2D (following WinRT design guidelines).

**Comment by jtorjo** [comment]
> I don't see anything in the loading code that would synchronize with the UI thread - it's a pretty straightforward threadpool dispatch up until the calling code waits for the async operation to complete.

In my tests, loading this AFTER the initial LoadResources, for a single image, took about 5 seconds - that is simply insane.

> 
> There are no synchronous file IO APIs in Win2D (following WinRT design guidelines).

I'm not going to say anything about the WinRT design guidelines here, other than I simply hate them. It's sad that there are no synchronous calls; async calls can simply block somewhere waiting for who knows what resource/execute sequentially/or who knows and you don't know anything about when/how they are executed.

**Comment by shawnhar** [comment]
5 seconds is definitely excessive, and orders of magnitude slower than anything I've seen!   Do you have a repro for this behavior?

**Comment by jtorjo** [comment]
Unfortunately, it's very complicated to isolate. By that, I mean I have a whole framework built around win2d, and a lot of code calling it doing animations.
Long story short, I ported my app from wpf to uwp and the drawing part is just a module, so there's a lot of other code involved.

**But what I can say for sure is this: it's happening when I have a CanvasAnimatedControl, and inside its _Draw function, I call CanvasBitmap.LoadAsync()**
