### ISSUE TITLE
achieve something similar to DropShadowPanel

### ISSUE THREAD

**Issue by jtorjo** [microsoft/Win2D#742]
I'd like to achieve something similar to https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/dropshadowpanel using effects.

Right now, I can't set offsets (x,y,z) if I were to use ShadowEffect. How could I do it?

**Comment by shawnhar** [comment]
You can combine the shadow effect with a 2D translation (eg. using Transform2DEffect)

**Comment by jtorjo** [comment]
thanks, makes sense!
