### ISSUE TITLE
"Simultaneous" drawing of 7 ECG channels using CanvasAnimatedControl

### ISSUE THREAD

**Issue by rauliordache** [microsoft/Win2D#744]
Hello. Happy New Year!

Last year I asked a question: [issue](https://github.com/microsoft/Win2D/issues/706) , and your team helped me using a good Win2D approach.

Now, I want to draw 7 ECG channels (**simultaneous**). For a single channel, I have followed @damyanp suggestion, with some mods:

- I have a queue of amplitudes(byte), protected by a lock (enqueuing when new amplitudes arrive from one thread, and dequeuing from a CanvasAnimatedContainer.Draw event handler - OnDraw)
- I have a list of points (to be shown on screen as a polyline). This list is used only in OnDraw.

I am using an additional queue, because I should not keep the entire list of points locked while I am drawing (in OnDraw I just dequeue the additional queue, adding the amplitudes in my list, then I am releasing the lock ... and then I draw).

Now, I need to draw 7 CanvasAnimatedControl (7 ECG channels) but I have to guarantee that they are drawn simultaneously. [photo]. After 4-5-10 minutes of running they are out of sync, if the containers are unrelated to each other. Then, I ask you:

1. **Should I rely on calling 7 (seven) ->  c[i].Invalidate() <-** when receiving the amplitudes for each ECG channel OR
2. Should I model somehow that **one OnDraw event handler modify each CanvasAnimatedControl** ?
Later edit: OR
3. Should I not use OnDraw event handler, instead, creating custom DrawingSession
`using(..) {//draw }`

It would be more elegant to call 7 .Invalidate(), but I don't know if the channel[index].OnDraw() is called immediately (and most important: **simultaneous**).

Thanks!
![execg](https://user-images.githubusercontent.com/11799801/71755006-5c2fe600-2e91-11ea-9a2a-9179cf81c819.png)

**Comment by shawnhar** [comment]
CanvasAnimatedControl is not a good choice if you need many separate controls, and especially not if you need to synchronize their updates.  It's main purpose is to provide drawing that can happen independently of the main UI refresh, and it doesn't scale well to more than a few such controls at a time.

Suggest investigating use of a regular CanvasControl, or possibly just a single larger CanvasAnimatedControl and then draw your different graphics onto the appropriate parts of this larger surface.

**Comment by rauliordache** [comment]
Thank you @shawnhar for you answer.

Yep, I have tried investigating regular CanvasControl and it seems better. (using 7 consecutive .Invalide() for each canvas)

The idea is that I do not think that this is a good approach (since .Invalidate() is not equal with "Draw" - it just schedules a Draw, so I should not rely on the scheduled timing: 10ms delay now, 20ms later, etc...).

I need something (Win2D) equivalent for :

`for(int i=0; i<7<channel_numbers>; i++) { //..// channel[i].Draw();}`

`public void Draw() { // ... // c.MoveTo(x1,y1); c.LineTo(x2,y2); }`

The C++ approach guarantees that each canvas (or let's say an area) is drawn "simultaneously" (improperly said, but the idea was understood).

**Comment by shawnhar** [comment]
CanvasControl drawing is triggered by the XAML UI redraw, so it's not just arbitrarily later.  This is probably reasonable for your purposes.
