### ISSUE TITLE
Thread safety of Close methods

### ISSUE THREAD

**Issue by benstevens48** [microsoft/Win2D#752]
I would expect the IClosable implementation to be thread-safe. However, for example, looking at `ResourceWrapper::Close`, this doesn't seem to be thread-safe to me. Am I missing something?

**Comment by shawnhar** [comment]
Close does not need to be threadsafe, because Close must always be the last method called on an object.  It's undefined behavior if an application is calling Close from one thread at the same time as some other thread is still executing a method of that object.

**Comment by benstevens48** [comment]
@shawnhar - I don't think that's correct. According to the docs, IDisposable.Dispose must be safe to call multiple times, and since IClosable.Close is projected in .net as IDisposable.Dispose, the same should apply to IClosable.Close.

Here is the quote from the IDisposable docs - <https://docs.microsoft.com/en-us/dotnet/api/system.idisposable.dispose?view=dotnet-uwp-10.0>

```
If an object's Dispose method is called more than once, the object must ignore all calls after the first one. The object must not throw an exception if its Dispose method is called multiple times. Instance methods other than Dispose can throw an ObjectDisposedException when resources are already disposed.
```
