### ISSUE TITLE
CanvasBitmap.CreateFromDirect3D11Surface throws Operation not supported

### ISSUE THREAD

**Issue by jtorjo** [microsoft/Win2D#756]
I have a Direct3D surface, obtained from a VideoFrame (from MediaComposition).
Trying to convert it to a CanvasBitmap throws:

![image](https://user-images.githubusercontent.com/13891601/73467057-6f987900-438b-11ea-8773-88c39a6efacb.png)

I tried all overloads, even: `bmp = CanvasBitmap.CreateFromDirect3D11Surface(canvas_device_, frame.Direct3DSurface, 96, CanvasAlphaMode.Premultiplied);`

They all throw. Not sure what I'm doing wrong?

**Comment by shawnhar** [comment]
What format is your incoming surface?  The most likely reason for a failure here is that it isn't one of http://microsoft.github.io/Win2D/html/PixelFormats.htm

**Comment by jtorjo** [comment]
I don't know how to find this out. It's the input frame from a video from MediaComposition:

	clip.VideoEffectDefinitions.Add(new VideoEffectDefinition(typeof(VideoFrameCallback).FullName, set));

	var composition = new MediaComposition();
	composition.Clips.Add(clip);
	var  encoding_profile =  MediaEncodingProfile.CreateMp4( quality(frame_size));
	encoding_profile.Video.Width = (uint)desired_size_.Width;
	encoding_profile.Video.Height = (uint)desired_size_.Height;
	encoding_profile.Video.FrameRate.Numerator = ...;
	encoding_profile.Video.FrameRate.Denominator = ...;

Then, when processing each frame:

	public void ProcessFrame(ProcessVideoFrameContext context) {
		var frame  = context.InputFrame;
		on_frame?.Invoke(this, frame);
	}

This is the `frame` from which I get the `.Direct3DSurface` from

I don't see any way to get the format of that surface.

Clearly, the workaround is this:

	var soft = SoftwareBitmap.CreateCopyFromSurfaceAsync(frame.Direct3DSurface, BitmapAlphaMode.Premultiplied);
	var task = soft.AsTask();
	task.Wait();
	var soft_bmp = soft.GetResults();
	var bmp = CanvasBitmap.CreateFromSoftwareBitmap(canvas_device_, soft_bmp);
	soft_bmp.Dispose();

but I'm pretty sure this makes 2-3 times slower than copying stuff directly

**Comment by shawnhar** [comment]
CanvasBitmap.CreateFromDirect3D11Surface doesn't copy anything, it just wraps an existing D3D object for use with D2D/Win2D.  That's only possible if the underlying object is in a format that D2D supports.

Format is one of the properties of IDirect3DSurface.

**Comment by jtorjo** [comment]
There's no such a property called "Format"

![image](https://user-images.githubusercontent.com/13891601/73477075-3b798400-439c-11ea-9fac-e96aedd827cb.png)

**Comment by damyanp** [comment]
It's part of the Description property: https://docs.microsoft.com/en-us/uwp/api/windows.graphics.directx.direct3d11.direct3dsurfacedescription

**Comment by jtorjo** [comment]
Got it, thanks!

So, the frame's format is:

![image](https://user-images.githubusercontent.com/13891601/73487558-ecd5e500-43af-11ea-87a6-696f437a161e.png)

which seems to be the default

**Comment by shawnhar** [comment]
My next guess: perhaps the incoming bitmap was allocated from a different D3D device than the CanvasDevice instance you are using here?  Have you taken steps to make sure these devices are the same?

**Comment by jtorjo** [comment]
I'm not really sure how I can do that. Since the frame comes from MediaComposition, I don't know how I can grab (or if it's possible) to get the right canvas device from that.

What I did try are the following:
1. initially, I used CanvasDevice.GetSharedDevice()
2. then, I created a CanvasControl, and used the device from there.

Having said that, assuming I can't use CanvasBitmap.CreateFromDirect3D11Surface, is there a faster way to create a canvas bitmap than:

	var soft = SoftwareBitmap.CreateCopyFromSurfaceAsync(frame.Direct3DSurface, BitmapAlphaMode.Premultiplied);
	var task = soft.AsTask();
	task.Wait();
	var soft_bmp = soft.GetResults();
	var bmp = CanvasBitmap.CreateFromSoftwareBitmap(canvas_device_, soft_bmp);
	soft_bmp.Dispose();

?

**Comment by shawnhar** [comment]
CanvasDevice.GetSharedDevice will definitely not work here - that gives you back a device that is unique to Win2D.  You will need to find if MediaComposition exposes some way to query what underlying D3D device that system is using (sorry I don't know this API) then wrap a Win2D device around that existing device.

If you can't make the devices match, your only option is to perform a slow copy of the data.

**Comment by jtorjo** [comment]
So, I've done my magic and found how to get the Direct3dDevice, create a canvas device, and rock on:

	var bmp_src = CanvasBitmap.CreateFromDirect3D11Surface(frame_temp_device_, frame.Direct3DSurface, 96, CanvasAlphaMode.Premultiplied);
	var bmp = CanvasBitmap.CreateFromBytes(canvas_device_, dummy_bytes_, (int)bmp_src.SizeInPixels.Width, (int)bmp_src.SizeInPixels.Height, bmp_src.Format);
	bmp.CopyPixelsFromBitmap(bmp_src);
	bmp_src.Dispose();

I was a bit surprised that the speed gains are only 20% or so. Am I doing anything wrong?

**Comment by shawnhar** [comment]
This path is still copying all the bits from one graphics device to another, just doing that in a slightly faster way than before.

For really good performance, you need to avoid doing any copy at all, which requires all your code to be using the same graphics device.  You can either make all your Win2D code use the device provided by this other API, or (if the other API supports it) tell that to use your Win2D device.

**Comment by jtorjo** [comment]
Agreed, but I actually want to copy everything to a new bitmap - it's because I need to cache several video frames and then draw them later. 

Initially i was using the CavasBitmap.CreateFromDirect3d11Surface directly, but realized I only ended up with the last frame.

Having said that, is there a faster way to do the above?

**Comment by shawnhar** [comment]
Copying large amounts of data is always expensive (a huge amount of the work involved in maximizing GPU perf boils down to finding ways not to copy things).  If you really can't avoid this, copying between bitmaps on the same device is much faster than across devices.

**Comment by jtorjo** [comment]
Thanks for the pointers. It makes a lot of sense. I thought pretty much about it - if I were to copy it this way, I'd later need to create a new bitmap for my other device - so I'd just postpone the inevitable ;)

**Comment by jtorjo** [comment]
p.s. seems I could have squeezed about 5-6% speed improvement by pre-creating the destination bitmaps, but I decided it's not worth the complication, for now
