### ISSUE TITLE
FPS drop on XBOX one Fat

### ISSUE THREAD

**Issue by brunotrevisan** [microsoft/Win2D#757]
hello good morning everyone, my game on the computer is running beautiful at 60fps but when i send it to xbox one fat it has a drop in fps running around 35 to 40 frames, is that normal? has how to solve? and why does this happen? I already changed it to a game in dev mode because I was entering it as an app but I changed it.

has anyone been through this and got a solution?

**Comment by shawnhar** [comment]
Sorry, this Win2D project is not the place to get technical support specific to Xbox One development.
