### ISSUE TITLE
ColorManagementEffect.AlphaMode docs disagree

### ISSUE THREAD

**Issue by benstevens48** [microsoft/Win2D#758]
The Win2D docs differ from the Direct2D docs on what ColorManagementEffect.AlphaMode means. The Direct2D docs say 

> How to interpret alpha data that is contained in the input image.

The Win2D docs say
> Effect inputs and outputs are assumed to be in premultiplied alpha format, so when this property is set to Premultiplied, color management is applied directly to the input values with no extra conversions.
> 
> If AlphaMode set to Straight, input values will be unpremultiplied, then the color management applied, and finally the result converted back to premultiplied format.

I also found this comment in a sample [here](https://github.com/microsoft/VCSamples/blob/master/VC2012Samples/Windows%208%20samples/C%2B%2B/Windows%208%20app%20samples/Direct2D%20effects%20photo%20adjustment%20app%20sample%20(Windows%208)/C%2B%2B/Lesson4.ColorManagement/PhotoRenderer.cpp) which agrees with and expands upon the Direct2D definition. This is in direct conflict with the Win2D definition.

```
    // Lesson 4:
    // We know the source image used in this scenario is opaque (JPEG does not support alpha).
    // ColorManagement internally operates on straight alpha data, so we can avoid a premultiply/
    // un-premultiply operation by setting the effect's alpha mode to Straight.
    DX::ThrowIfFailed(
        m_colorManagementEffectWorkingSpace->SetValue(
            D2D1_COLORMANAGEMENT_PROP_ALPHA_MODE,
            D2D1_COLORMANAGEMENT_ALPHA_MODE_STRAIGHT
            )
        );
```

Can you clarify which is correct? I have to say that it makes sense for color management to operate on unpremultiplied data, which agrees with the comment ('Lesson 4') above.

**Comment by shawnhar** [comment]
The Win2D docs are correct (to the best of my knowledge)

**Comment by benstevens48** [comment]
Hmm... I'm fairly sure the Win2D docs are wrong, and the Direct2D docs, along with the comment from the code sample above, are correct.

By the way, the docs also directly disagree for the color matrix effect. The [Direct2D docs](https://docs.microsoft.com/en-us/windows/win32/direct2d/color-matrix) say this
```
D2D1_COLORMATRIX_ALPHA_MODE_PREMULTIPLIED | The effect un-premultiplies the input, applies the color matrix, and premultiplies the output.
-- | --
D2D1_COLORMATRIX_ALPHA_MODE_STRAIGHT | The effect applies the color matrix directly to the input, and doesn't premultiply the output.
```
whereas the Win2D ones say 
```
Effect inputs and outputs are assumed to be in premultiplied alpha format, so when this property is set to Premultiplied, the color matrix is applied directly to the input values with no extra conversions.

If AlphaMode set to Straight, input values will be unpremultiplied, then the color matrix applied, and finally the result converted back to premultiplied format.
```
The behavior that Direct2D describes makes much more sense, hence I'm inclined to believe those docs over the Win2D ones.

I'm assuming that the Win2D effects map pretty much directly to Direct2D ones.

**Comment by shawnhar** [comment]
Unfortunately you can't decide which docs to believe just based on which seems to make the most sense :-)

I'm quite confident that the Win2D docs are correct in the places where they differ from older and less carefully reviewed D2D documentation.

**Comment by benstevens48** [comment]
I'll try and do a test at some point with a minimal example to be sure, then I'll post the results back here. I don't have time to do a test right now though.
