### ISSUE TITLE
GPU Device Suspended (0x887A0005 - DXGI_ERROR_DEVICE_REMOVED) even with DeviceLost handling

### ISSUE THREAD

**Issue by stefangabrielgavrilas** [microsoft/Win2D#760]
Hi there,
We have a control that contains 2 SwapChains as follows : 
![image](https://user-images.githubusercontent.com/26504867/76304817-ec3c4280-62bb-11ea-88a4-c28f06df0e6b.png)

SwapChain initialization :
![image](https://user-images.githubusercontent.com/26504867/76304758-d464be80-62bb-11ea-931e-3f9abe48c45d.png)

DeviceLost handling :
![image](https://user-images.githubusercontent.com/26504867/76304874-08d87a80-62bc-11ea-808c-66dff279bba6.png)

The problematic function is the drawing one :
![image](https://user-images.githubusercontent.com/26504867/76304973-36252880-62bc-11ea-8160-d2abd1e7eb93.png)

AppCenter report :
![image](https://user-images.githubusercontent.com/26504867/76305163-8a300d00-62bc-11ea-92f8-74f63ed33595.png)

We followed the documentation from [here](https://microsoft.github.io/Win2D/html/HandlingDeviceLost.htm) to handle a lost device but this issue is still occurring. Do you have any ideas?

Thank you kindly.

System info (machine on which crash occurred on) :
- Device : HP EliteDesk 800 G5 Desktop Mini
- Windows version : 1809

UWP app info :
- App version : 1803
- Win2D version : 1.23.0

**Comment by shawnhar** [comment]
Afraid I don't have any useful ideas about this.  The callstack you show does not make sense when the code shows that any exception coming from those calls would be caught and handled.   The only thing I can imagine is that somehow the IsDeviceLost test is failing, which would only occur if your cached _device field somehow got set to a different device from the one the actual drawing code is using?

**Comment by stefangabrielgavrilas** [comment]
Thank you very much for your prompt answer Shawn !

This is indeed a weird issue, therefore - what do you think if we add the following code (to see if we can avoid this problem) ?

![image](https://user-images.githubusercontent.com/26504867/76413786-fa5a9380-638d-11ea-83aa-f163eb753131.png)
> This is to prevent multiple Initialize events (just in case)


![image](https://user-images.githubusercontent.com/26504867/76413997-5f15ee00-638e-11ea-9326-0d9d20bc669e.png)
> One of our working theories is maybe the device in the SwapChain gets re-created/re-initialized automatically by the framework maybe and that is somehow what's causing the issue? 

What do you think?

All theories at this point, just trying to avoid the issue from occurring without having a repro :)

**Comment by shawnhar** [comment]
The framework won't ever automatically recreate a device that you created explicitly like this.

Is there any multithreading in your app?  If you are doing any of this work on background threads, that could explain why other threads see inconsistent / seemingly impossible states.

Otherwise, do you have any way to add logging to this code?  If it's possible to augment the crash callstack with additional data, logging when calls to each of these methods occur and the associated key states (eg. of IsDeviceLost) would be informative.

**Comment by stefangabrielgavrilas** [comment]
Thank you very much - this definitely got me going in the right direction I think.
I've discovered that the Redraw() calls (which in my case call DrawElements()) are called from different threads in different situations (even Device_Lost calls Initialize again which in turn calls Redraw at the end).
I will dispatch all these calls to the UI thread and/or make sure they are on the same thread and also add more logging.
If this issue comes back with more details (via enhanced logging) I shall re-open the ticket and provide some more info.
Thank you very much for your assistance, you're one in a million !
