### ISSUE TITLE
System.UnauthorizedAccessException for CanvasBitmap.LoadAsync(ICanvasResourceCreator, String)

### ISSUE THREAD

**Issue by myokeeh** [microsoft/Win2D#763]
How can I feed filepaths to `LoadAsync` without getting `System.UnauthorizedAccessException`? I've attempted adding `broadFileSystemAccess` to the UWP app manifest, but still getting the exception.

**Comment by jtorjo** [comment]
I can tell you from the get go - this is NOT win2d related. It's more like "welcome to the world of UWP".

If you have some spare time, read this: https://github.com/microsoft/microsoft-ui-xaml/issues/1856

Look at "The broadSystemAccess API" section - and you'll see what extra stuff you need to do

**Comment by myokeeh** [comment]
Right. I found some sample code that helped and got this working with `broadFileSystemAccess`
