### ISSUE TITLE
ColorSourceEffect only works on 8bit colors

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/Win2D#77]
The D2D Flood Effect takes a 4vector of floats as its color. But the ColorSourceEffect only takes a Windows.UI.Color, i.e. 8bits per value.

(I'm doing a mandelbrot calculator using effects, and I want to initialize all values in my R32G32B32 surface to exactly 0.5, but I'm not sure if that would be 127 or 128 in bytes. I'd rather do it direct with floats).

**Comment by shawnhar** [comment]
I'll take this as an upvote for [backlog](https://github.com/Microsoft/Win2D/wiki/Backlog) item "Draw using floating point high precision color values (unlike WinRT color which is only 8 bit per channel)".

We're aware of that issue but don't yet have a design for how to solve it.  Likely we will end up giving every type that has a Color property an equivalent of type Vector3 or Vector4 called something like ColorHdr - that seems kinda ugly but we didn't want to just use Vector4 to represent colors everywhere (using the standard WinRT color type is just too dang convenient).

(untested) options for how to work around this limitation for now:

1) Create a 32 bit float format bitmap sized 1x1 and containing the desired color value - use that in place of the ColorSourceEffect

2) Create a ColorSourceEffect set to Colors.White, then feed it through an ArithmeticCompositeEffect or LinearTransferEffect which can scale the incoming 1.0 to generate any desired value.

**Comment by ljw1004** [comment]
If you do create a ColorHdr -- I think I'd appreciate methods to help me stick it into surfaces. Maybe add "GetPixelColors / SetPixelColors" overloads that work with it.

I wanted to read and write R32G32B32A32 "float" pixels, and also to read and write R16G16B16A16 "half-float" pixels. The code for "float" was easy to get correct (but the way I did has atrocious perf so I'd prefer if lengthier more efficient code could be written by someone else...) The code for "half-float" was hard. I based my code on this:
http://stackoverflow.com/questions/6162651/half-precision-floating-point-in-java/6162687#6162687


Here's my half-float:
```vb
Public Structure ColorH
    Public R, G, B, A As Single
    Function GetBytes() As Byte()
        Dim buf = New Byte(7) {}
        Array.Copy(ToHalfFloat(R), 0, buf, 0, 2)
        Array.Copy(ToHalfFloat(G), 0, buf, 2, 2)
        Array.Copy(ToHalfFloat(B), 0, buf, 4, 2)
        Array.Copy(ToHalfFloat(A), 0, buf, 6, 2)
        Return buf
    End Function

    Public Shared Function ToHalfFloat(value As Single) As Byte()
        If value < 0 Then Throw New ArgumentOutOfRangeException(NameOf(value), "negatives not implemented")
        Dim fbits = BitConverter.ToUInt32(BitConverter.GetBytes(CSng(value)), 0)
        Dim val = (fbits And &H7FFFFFFFUI) + &H1000
        If val >= &H47800000 Then Throw New ArgumentOutOfRangeException(NameOf(value), "NaN/Inf/overflow not implemented")
        If val >= &H38800000 Then Return BitConverter.GetBytes(CUShort((val - &H38000000) >> 13))
        If val < &H33000000 Then Return {0, 0}
        Throw New ArgumentOutOfRangeException(NameOf(value), "subnormals not implemented")
    End Function

End Structure
```

And here are some of the GetPixelColors/SetPixelColors overloads that I wanted...

```vb
Public Structure ColorF 
    Public R, G, B, A As Single 
End Structure 

    <Extension>
    Function GetPixelColorFs(bmp As CanvasBitmap) As ColorF()
        Dim buf = bmp.GetPixelBytes()
        Dim c = New ColorF(buf.Length \ 16) {}
        For i = 0 To buf.Length - 1 Step 16
            c(i).R = BitConverter.ToSingle(buf, i * 16 + 0)
            c(i).G = BitConverter.ToSingle(buf, i * 16 + 4)
            c(i).B = BitConverter.ToSingle(buf, i * 16 + 8)
            c(i).A = BitConverter.ToSingle(buf, i * 16 + 12)
        Next
        Return c
    End Function

    <Extension>
    Sub SetPixelColorFs(bmp As CanvasBitmap, colors As IEnumerable(Of ColorF), left As Integer, top As Integer, width As Integer, height As Integer)
        Dim buf = From c In colors From b In c.GetBytes Select b
        bmp.SetPixelBytes(buf.ToArray, left, top, width, height)
    End Sub
```

**Comment by ljw1004** [comment]
Ouch! I just got bitten by this. My app is running fine on Win10Desktop. But when I tried running it on a Win10Mobile device, it failed with an UnsupportedPixelFormat exception. It turns out there is only one single "float" pixel formats supported on a Lumia635, R16G16B16A16Float. And SurfacePro1 supports only one additional "float" pixel format, R32G32B32A32Float.

So I have to rewrite my app to use the lowest-common-denominator R16G16B16A16Float.

This makes it crucial to have good support in win2d for "half precision float" format!

```
Supported on Lumia635

A8UIntNormalized [Straight | Premultiplied]
B8G8R8A8UIntNormalized [Ignore | Premultiplied]
R8G8B8A8UIntNormalized [Ignore | Premultiplied]
R16G16B16A16Float [Ignore | Premultiplied]

Supported on SurfacePro1: all the above, plus

B8G8R8A8UIntNormalizerSrgb [Ignore | Premultiplied]
R8G8B8A8UIntNormalizedSrgb [Ignore | Premultiplied]
R16G16B16A16UIntNormalized [Ignore | Premultiplied]
R32G32B32A32Float [Ignore | Premultiplied]
```

**Comment by shawnhar** [comment]
Win2D 1.9.0 (released today) adds ColorHdr properties alongside all the existing Color properties, which allow use of full range 32 bit IEEE float values.
