### ISSUE TITLE
Exception 0x8899000C on CanvasBitmap.CreateFromBytes - how to avoid, how to recover?

### ISSUE THREAD

**Issue by jtorjo** [microsoft/Win2D#770]
Hi,

It's quite hard to repro, but every now and then, I get this exception:

	System.Exception
	  HResult=0x8899000C
	  Message=There has been a presentation error that may be recoverable. The caller needs to recreate, rerender the entire frame, and reattempt present. (Exception from HRESULT: 0x8899000C)
	  Source=<Cannot evaluate the exception source>
	  StackTrace:
	<Cannot evaluate the exception stack trace>

It happens while I'm doing this:

	var bmp = CanvasBitmap.CreateFromBytes(bitmap_canvas_device, byte_buffer, (int) bmp_src.SizeInPixels.Width, (int) bmp_src.SizeInPixels.Height, bmp_src.Format);

as part of the following:

	var bmp_src = CanvasBitmap.CreateFromDirect3D11Surface(temp_canvas_device, temp_render, 96, CanvasAlphaMode.Premultiplied);
	var bmp = CanvasBitmap.CreateFromBytes(bitmap_canvas_device, byte_buffer, (int) bmp_src.SizeInPixels.Width, (int) bmp_src.SizeInPixels.Height, bmp_src.Format);
	bmp.CopyPixelsFromBitmap(bmp_src);
	bmp_src.Dispose();

To put it in context, I have a MediaPlayer on server mode, and I'm grabbing video frames. The catch is I actually have several MediaPlayers (thus, I'm grabbing from several videos at once) all the while I'm also drawing on the `bitmap_canvas_device`.

I always assumed I the `CanvasDevice` class is thread-safe, and I can create resources any time, on any thread. Is this not the case? Should I do a lock on `CanvasBitmap.CreateFromBytes` ?

Also, I've tested catching the exception, sleeping a bit and retrying - this does not work. So I'm surprised - if I encounter this, how do I truly recover?

**Comment by shawnhar** [comment]
Win2D is threadsafe as long as you only access resources through Win2D APIs, but there are additional concerns if you interop GPU resources across multiple different APIs that don't all use the same threading model.   Details here:  https://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasDevice_Lock.htm

That error code indicates a device lost state, which could be due to a threading problem or unrelated GPU fault.  To recover, you must destroy all GPU devices and resources, then recreate a fresh set  (https://microsoft.github.io/Win2D/html/HandlingDeviceLost.htm).

**Comment by jtorjo** [comment]
Thanks for pointing out the .Lock() method!

My code is like this:

	MediaPlayer sender;
	...

	var temp_canvas_device = new CanvasDevice();
	var temp_render = new CanvasRenderTarget(temp_canvas_device, size.Width, size.Height, 96);
	var byte_buffer = new byte[4 * size.Width * size.Height];

	using (temp_render.CreateDrawingSession())
		sender.CopyFrameToVideoSurface(temp_render);

	var bmp_src = CanvasBitmap.CreateFromDirect3D11Surface(temp_canvas_device, temp_render, 96, CanvasAlphaMode.Premultiplied);
	var bmp = CanvasBitmap.CreateFromBytes(bitmap_canvas_device, byte_buffer, (int) bmp_src.SizeInPixels.Width, (int) bmp_src.SizeInPixels.Height, bmp_src.Format);
	bmp.CopyPixelsFromBitmap(bmp_src);
	bmp_src.Dispose();

The only place I'm using something outside win2d is `sender.CopyFrameToVideoSurface(temp_render);`

`bitmap_canvas_device` is the device from a control (`CanvasAnimatedControl`) that I draw on.

I just don't see how anything would need locking. Am I missing anything?

**Comment by jtorjo** [comment]
One more question: I assume `CanvasBitmap.CreateFromSoftwareBitmap` doesn't need any locking, right?

**Comment by shawnhar** [comment]
CopyFrameToVideoSurface and CreateFromSoftwareBitmap both might need locking, depending on what the threading rules are for whatever other components implemented the source video surface and software bitmap objects for these operations.   Sorry I'm not familiar with the threading behavior of the MediaPlayer you mentioned.

**Comment by shawnhar** [comment]
Closing out old issue
