### ISSUE TITLE
Which control is the right one?

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/Win2D#771]
Hello, I'm using Win2D together with Samsung's rlottie to render Lottie animations in my app.
The app is a messaging client, and animations are stickers that users can send to each other.
As of stickers nature the users might end up with 50 of them playing simultaneously on the screen. 

I originally build my control ([LottieView.cs](https://github.com/UnigramDev/Unigram/blob/develop/Unigram/Unigram/Controls/LottieView.cs)) on top of `CanvasAnimatedControl` and everything is pretty fine while having a few stickers on the screen, the problem starts when having dozens of them: when all the threads are running there are major frames drops that can't be ignored as the app is barely usable.
Now I'm looking into different possibilities but I'm not sure about which one is the right one:
- `CanvasControl` can only be invalidated on the UI thread, and this doesn't sound like a good idea
- `CanvasVirtualControl` documentation states "use it if you want to control what thread the drawing happens on", but it still requires to be invalidated on the UI thread

Any suggestion and help would be highly appreciated,
Thanks!

**Comment by FrayxRulez** [comment]
I ended up by using CanvasSwapChainPanel and a single “game-loop” shared across all controls. To improve the performances I made a cool down system to avoid creating too many CanvasDevices all together. 
Since this is probably the “low level” approach when talking about Win2D I wonder if I should handle any specific case here, such as DPI changes, device loss and so on.

**Comment by shawnhar** [comment]
I'd recommend a regular CanvasControl for this scenario.  Swapchains are optimal for one at a time, maybe a couple, but won't scale well to as many as 50.

**Comment by FrayxRulez** [comment]
But using a `CanvasControl` would require having the render loop on the UI thread, won’t this affect performances as well?
Also I won’t be able to handle the CanvasDevice creation and from what I seen on my tests this kicks on the performances pretty bad...

**Comment by shawnhar** [comment]
Ideally you should be using the same CanvasDevice for all of these controls.  Using CanvasControl will handle that for you automaticaly.   I expect you'll get much better performance that way rather than pushing high numbers of swapchain panels.

**Comment by FrayxRulez** [comment]
Using the same `CanvasDevice` decreased the frame rate drastically in my tests. 
Multiple CanvasSwapChainPanels have problems on not-so-powerful PCs, but this leads to “slow-motion” animations, while the rest of the app is still fluid enough. 

I’d like to rephrase my question to: is there any way on Windows platform, by using Win2D or some other way, to achieve background rendering without using SwapChains?

Thanks for your help so far 😊

**Comment by shawnhar** [comment]
> I’d like to rephrase my question to: is there any way on UWP platform, by using Win2D or some other API, to achieve background rendering without using SwapChains?

Answering this narrowly, no.  But I think a broader answer is more useful here.  I really think you are going down a wrong path here by using SwapChain rather than CanvasControl, and definitely by using more than one CanvasDevice.

I recommend separating out the expensive part of whatever work you are doing (which needs to by asynchronous, and might even benefit from more than one thread working on different pieces in parallel) from the display part (which should be cheap, and for which CanvasControl is the right solution if you have more controls than you can count on the fingers of one hand).  For instance, if you are populating new image data into a bitmap and then drawing that to the control, run the bitmap creation part asynchronously and then post back to the UI thread to draw the bitmap once you've populated it.  If you need more complex rendering code, cache intermediates in rendertargets which can be created asynchronously for later display.

**Comment by FrayxRulez** [comment]
I was so much into “or black or white” that I completely ignored this option, that actually makes a lot of sense. 
White this seems to use more CPU on my laptop (with my previous solution it was basically idle) it works way better on low end devices, even displaying 50 animations all together. 
Thank you for enlightening me into this.

**Comment by FrayxRulez** [comment]
Hello @shawnhar, resurrecting this thread. 
Some users noticed (my eyes seem not to be good enough 😄) that stickers aren't actually being animated "smoothly". I enabled the frame counter (by using App's `DebugSettings.EnableFrameRateCounter`) and it actually turns out that the window is drawing only 25 fps, while the `DispatcherTimer` I'm using actually ticks every 1000/60 ms. The timer actually calls `CanvasControl.Invalidate()` method, and I guess that this is the bottleneck?

**Comment by shawnhar** [comment]
If you want to animate on every redraw, you'll get better results calling Invalidate from the end of the previous draw handler, rather than from a timer.
