### ISSUE TITLE
CanvasVirtualControl stops drawing inside ContentDialog

### ISSUE THREAD

**Issue by rosca** [microsoft/Win2D#774]
When you create a [CanvasVirtualControl ](https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_UI_Xaml_CanvasVirtualControl.htm) inside a [ContentDialog ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog?view=winrt-19041) container, the canvas is cleared up and doesn't draw anymore after changing the visibility state of the app, or after calling Invalidate.

Demo app:
https://github.com/rosca/demo-win2d-canvas-in-dialog

**Comment by shawnhar** [comment]
Looking at the repro app, it looks like you are never closing the CanvasDrawingSession instances?  When using C++/CX, that is done via the 'delete' keyword  (whereas in C# it would be a Dispose call or 'using' keyword).

**Comment by rosca** [comment]
@shawnhar, per my knowledge, in C++/CX the variable will get destroyed immediately after you go out of scope. I still tried your suggestion, but the behavior is the same: https://github.com/rosca/demo-win2d-canvas-in-dialog/blob/master/Win2DInDialog/MainPage.xaml.cpp#L90

**Comment by shawnhar** [comment]
That's very strange.  I can repro this behavior using your sample app, and spent a while trying to debug it, but I have no idea what is causing the problem.

**Comment by rosca** [comment]
Thank you for trying it out. Do you think it may be a platform bug, or a Win2D bug?

I'm trying to find a workaround to this issue, mainly replacing CanvasVirtualControl with CanvasControl where possible.
In my use case, the user is able to create canvases of different sizes to render various parts of the app (svg, text, border, background), and they can control the size of each object. The size can be within the [maximum bitmap size](https://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_CanvasDevice_MaximumBitmapSizeInPixels.htm), or it can dynamically exceed this limit (e.g. border inside a scroll view). What would be the best approach here?
1) Use CanvasVirtualControl for everything. Is CanvasVirtualControl more expensive than a CanvasControl?
2) Use CanvasControl as much as possible, move to CanvasVirtualControl the first time the size exceeds the limits.

**Comment by rosca** [comment]
I managed to reproduce this with a simple Imaging::VirtualSurfaceImageSource - so the issue seem to be in the runtime. The small surfaces are not rendered at all, but if the virtual canvas is big, it usually renders, but the update rects are not always correct.
@shawnhar , is anyone at Microsoft tracking this bug, or I need to file a bug via other channels?

**Comment by shawnhar** [comment]
I followed up with the XAML team, who said:

> We're not aware of any issues with VSIS in a ContentDialog.  My best guess is that maybe the Popup involved in showing the ContentDialog somehow interferes with the VSIS calculations about what parts are visible, but we don't know why that would be.

> If the customer could port the bug to the WinUI repo, that would be great.

That repository is at https://github.com/microsoft/microsoft-ui-xaml

Thanks!
