### ISSUE TITLE
Direct2D bug - rendering 16-bit FP image to 8-bit uint swap chain with effects and scale transform results in grayed-out blocks

### ISSUE THREAD

**Issue by benstevens48** [microsoft/Win2D#776]
I'm trying to render a 16-bit floating point JPEG-XR image to an 8-bit unit swap chain. The image is loaded as as CanvasVirtualBitmap. However, whenever I apply an effect in combination with a scale transform, and set the interpolation mode to Hight Quality Cubic, Anisotropic, and to a certain extent Multi-Sample Linear, I get large blocks of grey-tinted content, or sometimes the inverse pattern. I guess these blocks correspond to the tiles that Direct2D uses. See the image below for an example.

![image](https://user-images.githubusercontent.com/10088503/85956696-6d106e80-b97f-11ea-99ca-41edb37efc7e.png)

Could you pass this bug on to the Direct2D team, or else let me know of a better place to post it (e.g. WinUI, Project Reunion)? Interestingly, rendering to a 16-bit FP swap chain does not have this issue. Also, loading the image as a CanvasBitmap instead does not have this issue, but then very large images can't be handled.

**Comment by shawnhar** [comment]
Thanks for the report!  I have passed this on, and will let you know what I hear back.

**Comment by benstevens48** [comment]
I found another easier workaround that can be used when rendering to a 16-bit swap-chain. Set DrawingSession.EffectBufferPrecision = CanvasBufferPrecision.Precision16Float. It's strange that this makes a difference because I was setting the buffer precision on every single effect to Precision16Float anyway. Evidently there is some extra buffering going on somewhere, or else the individual effect buffer precisions are being ignored.

However, I can't see any way of applying this particular workaround to my export pipeline, which uses [IWICImageEncoder::WriteFrame](https://docs.microsoft.com/en-us/windows/win32/api/wincodec/nf-wincodec-iwicimageencoder-writeframe). Is there any way to set the default buffer precision on the device rather than device context using Direct2D, or force the buffer precision when using the IWICImageEncoder::WriteFrame API? If not, it seems that that's a bit of a feature gap when using the IWICImageEncoder::WriteFrame API, which could do with being filled. If there's no workaround using this method, I guess I'll have to use the other workaround of loading a CanvasBitmap, then falling back to software rendering for very large bitmaps.

**Comment by adadi-MS** [comment]
Would it be possible to share your app with us, or the source for a narrowed-down repro?

**Comment by benstevens48** [comment]
@adadi-MS - here is a repro. Run the solution then try resizing the window (especially make it small) to see the block artefacts. In the sample I'm providing, it seems like the block artefacts are directly as a result of 8-bit uint buffer precision being used for some parts of the image instead of 16-bit floating point. Perhaps there is some buffering during the transform effect that doesn't correctly use the effect's buffer precision. Ideally, it should default to 16-bit anyway because the image is 16-bits per channel, but maybe it doesn't because CanvasVirtualBitmap (or the underlying Direct2D type) doesn't have an explicit pixel format?

[VirtualBitmapRenderTest.zip](https://github.com/microsoft/Win2D/files/4914142/VirtualBitmapRenderTest.zip)

**Comment by adadi-MS** [comment]
Thanks @benstevens48 , we're able to repro the issue and are investigating.

**Comment by MilesCohen-MS** [comment]
@benstevens48 I've been looking into this issue and can confirm that you are hitting a bug in Direct2D. As a workaround, your proposed solution to use a CanvasBitmap to render the image prior to encoding it sounds like it would work.

Another idea would be to to use change the pixel format you use in the IWICImageEncoder::WriteFrame. The idea for this workaround is to remove the color management effect in your export pipeline and instead set the pixel format to DXGI_FORMAT_R16G16B16A16_FLOAT via https://docs.microsoft.com/en-us/windows/win32/api/wincodec/ns-wincodec-wicimageparameters. This will cause color management to be done in software by the encoder instead of on the GPU, but it should keep the rest of your effect pipeline running in 16-bit precision.

**Comment by benstevens48** [comment]
@MilesCohen-MS - thanks for letting me know. I thought about that other workaround but I decided the CanvasBitmap one was easier (especially if the output color space is not sRGB, e.g. Adobe RGB).

Any idea if/when the bug will be fixed? I assume it will be the next Windows feature update at the earliest, which I guess is May next year.

**Comment by MilesCohen-MS** [comment]
The fix will be in the next release of Windows. Thanks for reporting the issue!
