### ISSUE TITLE
EnableColorFont does nothing when using DrawTextLayout

### ISSUE THREAD

**Issue by MarkIvanDev** [microsoft/Win2D#783]
When using the `CanvasDrawingSession.DrawText`, it respects the EnableColorFont option set in `CanvasTextFormat` but not in `CanvasDrawingSession.DrawTextLayout` with EnableColorFont also enabled.

**Comment by JohnnyWestlake** [comment]
Further information for this - it will respect it, but **only** if you set it after the CanvasTextLayout initializer in C#. If you set it during initialization, i.e.
```
var layout = new CanvasTextLayout(...) {  Options = CanvasDrawTextOptions.EnableColorFont }
```
then it gets ignored.

If you do this instead, it will correctly render colour glyphs
```
var layout = new CanvasTextLayout(...);
layout.Options = CanvasDrawTextOptions.EnableColorFont;
```

so presumably something during object construction is overwriting the value, or the value gets set before it's meant too.

**Comment by MarkIvanDev** [comment]
Thank you for the workaround. 😊
