### ISSUE TITLE
Question: Should I create a separate device for rendering on a background thread?

### ISSUE THREAD

**Issue by benstevens48** [microsoft/Win2D#785]
(Note - there's actually a separate issue that I'm going to create about not being able to render to two CanvasVirtualControls simultaneously, once I've investigated more). This question is about performance/best practice. Currently in my app I have a swap chain, which I draw to on a background thread. I also have some CanvasVirtualControls that I'm drawing to on the UI thread. Currently I'm using CanvasDevice.GetSharedDevice to render both. However, I'm thinking that maybe it would be better to use CanvasDevice.GetSharedDevice for UI thread drawing only, and create a separate device for rendering to my swap chain on a background thread. This is based on my observation that if I try to render to the swap chain at the same time as rendering on the foreground thread with the same device, the time taken for the foreground rendering increases from 0.4ms to sometimes as much as 20ms. I guess this might be because of locking that occurs on the device, for example when the swap chain creates a drawing session. With separate devices, the foreground rendering time remains at around 0.4ms.

So is having separate dedicated devices for foreground and background rendering (as long as they don't need to share resources) actually a good application design in general? I'm sorry for asking this question, but all the examples using Win2D normally use the shared device, so it would be nice just to have a sanity check. Also, maybe it's possible to mention this in the docs somewhere if it's a good idea?

**Comment by shawnhar** [comment]
This is a nuanced topic so I can't give a definitive answer.  On the one hand, D3D11 is not really capable of parallel rendering work submission, so simultaneous usage of a single device across multiple threads will result in lock contention.  But on the other hand, D3D11 devices are heavyweight so you don't want to be creating a lot of them.  2 is probably fine but stay well away from things like a separate device per control!

**Comment by benstevens48** [comment]
OK, thanks for confirming that behavior. 2 devices seems like a good number - one for UI rendering and one for everything else, ensuring the UI remains as responsive as possible.
