### ISSUE TITLE
Please let windows store demo and windows phone store demo support more language

### ISSUE THREAD

**Issue by h82258652** [Microsoft/Win2D#79]
Now, the demo only support english. If I want to download the demo, I must change my region setting.
现在，demo仅仅支持英文。如果我想下载这个demo，我得先换个区域。
Thanks the Win2D team!

**Comment by h82258652** [comment]
Oh sorry, it is my misstake. I use the win10 store beta, so I can not find the demo.
Use the old store is ok.

**Comment by clandrew** [comment]
我们有时候试试使用不同的区域试试demo，不只英文。但是，我们有很多的英文的tests。那么，我很开心这是没有bug。谢谢您这个问题！

**Comment by h82258652** [comment]
谢谢Win2D开发组的回复。祝Win2D这个项目越来越好。等Win10SDK正式版发布迁移应用时应该会用上这个项目，火焰字那个效果太赞了。
另外有些小建议：
1、是没做贝塞尔曲线吗？demo里好像找不到，这个我觉得相当重要的说。
2、如果可以的话（时间、人力充足的情况下），我希望粒子系统里的爆炸特效不仅仅就像现在这样，而是可以应用到其它元素上，例如可以给图片爆炸、给文字爆炸，感觉挺炫酷的说。

**Comment by clandrew** [comment]
谢谢您这条评论。我也觉得火焰文字很好玩。

1、您可以使用Win2D画画贝塞尔曲线。请看一看[这里](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Geometry_CanvasPathBuilder.htm)。CanvasPathBuilder有个method叫AddCubicBezier。我们应该加一个贝塞尔曲线在Geometry Operations demo中，然后大家能看到。

2、我也觉得粒子系统是很有意思的demo。那个demo使用很多[Effects](http://microsoft.github.io/Win2D/html/N_Microsoft_Graphics_Canvas_Effects.htm)，给一个“烟／火"的图片爆炸。能使用Effect在两个都图片和文字上。可是，如果我们有时间够了，可能我们可以加一个built-in爆炸的Effect。

我要加一条评论我们的Backlog item叫Future Ambitions－“Create Custom Imaging Effects“。
