### ISSUE TITLE
Link problem with Win2D

### ISSUE THREAD

**Issue by fwmiller** [microsoft/Win2D#797]
Greetings,
I'm writing a C++/UWP app and trying to use Win2D.   I have everything in from the example and it compiles fine, but I'm getting an unresolved external error I don't know how to fix:

`1>XamlTypeInfo.g.obj : error LNK2019: unresolved external symbol "private: void __cdecl GNC::MainPage::CanvasControl_Draw(class Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl ^,class Microsoft::Graphics::Canvas::UI::Xaml::CanvasDrawEventArgs ^)" (?CanvasControl_Draw@MainPage@GNC@@A$AAAXP$AAVCanvasControl@Xaml@UI@Canvas@Graphics@Microsoft@@P$AAVCanvasDrawEventArgs@45678@@Z) referenced in function "public: virtual void __cdecl GNC::MainPage::[Windows::UI::Xaml::Markup::IComponentConnector]::Connect(int,class Platform::Object ^)" (?Connect@?QIComponentConnector@Markup@Xaml@UI@Windows@@MainPage@GNC@@U$AAAXHP$AAVObject@Platform@@@Z)
1>C:\Users\Frank W. Miller\source\repos\GNC\Debug\GNC\GNC.exe : fatal error LNK1120: 1 unresolved externals`

Maybe I didnt install Win2D correctly?

I'm using VS2019 Community.
Thanks

**Comment by shawnhar** [comment]
The GNC::MainPage::CanvasControl_Draw method is part of your application code, not a Win2D thing.  Are you sure you really did define that method?

**Comment by fwmiller** [comment]
Ah, simple fix.  I had defined CanvasControl_Draw  but not inthe GNC::Mainpage XAML page context.  Thanks so much!
