### ISSUE TITLE
VS2013 not responding on opening of solution

### ISSUE THREAD

**Issue by limefrogyank** [Microsoft/Win2D#8]
This is probably due to my limited experience with this type of solution, but I can't get past the "Initializing Projects... (0 of 38) - winrt.text.external.Windows" stage of opening the solution.  I've tried downloading a zip of the solution and cloning the repository.  I've waited hours for it to finish loading and it won't finish.  I've reset setting and disabled a few extensions so that it doesn't lock up VS anymore, but it will never finish the "Initializing Projects" status.

Does anyone have a quick solution to this?  Thanks.

**Comment by protegesolutions** [comment]
@clandrew Unfortunately this didn't work for me. A very frustrating and time-consuming bug.
