### ISSUE TITLE
CanvasBitmap.LoadAsync fails on some image files

### ISSUE THREAD

**Issue by nlIsotools** [Microsoft/Win2D#80]
For example, with the attached file, the function returns an exception with code 0x88982f8E (WINCODEC_ERR_PROPERTYUNEXPECTEDTYPE).
How to know which is the property that causes this problem?
The same file associated with a XAML Image element  is displayed correctly.

**Comment by nlIsotools** [comment]
![1447](https://cloud.githubusercontent.com/assets/2253979/7678177/57eeaa56-fd52-11e4-936c-51a50ff06737.jpg)

**Comment by clandrew** [comment]
This looks like Win2D is being too strict about which attributes are allowed when decoding images. I'll take a look.

**Comment by clandrew** [comment]
Looks like your change fd62f225db67192314ea2d831ef66a71b6425b4e fixed this issue. I verified this in my test environment. Thank you so much for your contribution.
