### ISSUE TITLE
Win2D Gallery App crashes and is unable to recover from TDR for Direct3D Interop

### ISSUE THREAD

**Issue by anup-das** [microsoft/Win2D#808]
Steps to repro
Install Win2D Gallery App form Microsoft store
Click Direct3D Interop on main page
Open cmd prompt as administrator and issue the cmd >  dxcap -forcetdr

Win2D app crashes and closes without any error message.
Note this happens ONLY for "Direct3D Interop" all other options / pages seems to handle TDR well. Probably Device Lost and Recovered events are not being handled properly to work with C++ code ?

**Comment by ChewWorker** [comment]
Thanks for the bug report.  We'll prioritize this appropriately.
