### ISSUE TITLE
Calling CanvasGeometry.Transform repeatedly can trigger a StackOverflowException

### ISSUE THREAD

**Issue by Decimation23** [microsoft/Win2D#811]
In my application, I have the ability for users to move objects they have drawn with their finger or mouse, and those objects are represented by a CanvasGeometry object. To handle moving the CanvasGeometry, I use the Transform method and create a simple translation. After a short while of moving the object, I receive a StackOverflowException in d2d1.dll. This does not occur if I recreate the geometry with each movement of their finger or mouse, so I believe the issue is specific to using the Transform method. I have created a sample project that draws a line and when the mouse is moved around in the window, the line follows the mouse. If you quickly move the mouse around in circles in the center of the window, you should encounter the StackOverflowException shortly after. Let me know if any additional information is required.

[CanvasGeometryException.zip](https://github.com/microsoft/Win2D/files/6125167/CanvasGeometryException.zip)

**Comment by shawnhar** [comment]
Every call to Transform creates a new CanvasGeometry instance, wrapping the input with additional processing applied.  It doesn't destructively edit the original geometry.  It sounds like you are adding an ever-growing chain of transforms, each one around the previous, which will become increasingly inefficient and then fail entirely as the chain depth grows excessive.  Instead, suggest wrapping a fresh transform around your original geometry instance for each step in the motion, so the chain never needs to grow more than 2 deep.

**Comment by Decimation23** [comment]
I call Dispose on the original geometry after calling Transform, and only saved the new geometry. Is this not a valid approach?

**Comment by shawnhar** [comment]
Your new geometry is just a thin wrapper around the original.  Every time you do this, you're creating another wrapper around the previous wrapper.  Not a good approach.

**Comment by Decimation23** [comment]
Okay, thank you for the explanation. I did not realize that is how it is implemented under the covers. I will avoid using Transform then for what I'm trying to do.

**Comment by shawnhar** [comment]
Using Transform is fine, just don't keep chaining one Transform on top of another Transform growing forever.
