### ISSUE TITLE
CanvasControl/CanvasAnimatedControl Width/Height limits?

### ISSUE THREAD

**Issue by jtorjo** [microsoft/Win2D#814]
I have a CanvasControl of 960 x 540 size where I draw controls. Some of them are drawn outside its area, thus not visible.
 
I want to implement a smart zoom to be able to show them as well. I would like to go up to zoom=5.
That would mean a control of size 4800 * 2700. 

On my machine, this works. I'd like to know if this will work on *all* machines, or will I be limited by some DirectX limitation or something like that?

**Comment by shawnhar** [comment]
Rather than drawing a very big image and then scaling down the resulting bitmap, you'll get dramatically better performance and lower memory usage if you implement zoom by scaling down your original vector shapes and always drawing at the final output size.

**Comment by jtorjo** [comment]
@shawnhar I 100% agree. Unfortunately, I have a rather complex app, with some legacy code, and it's far from trivial to do it as you say. Long term, I will do it exactly as you say, for for the short term, I'd like to have a large control - I think the max size will seldom be reached, since the user will zoom with the mouse scroll wheel, start from zoom=1.

Having said that, are there any limitations to this (Width/Height)? Is this size feasible (4800 x 2700)?

**Comment by ChewWorker** [comment]
@jtorjo I suspect you will hit problems on some old 9_1 level hardware.  That hardware has texture limits of 2k = 2048 < 2700.  If you want this to be reliable you would need to force it to be software in GetSharedDevice or require a feature level >= 10_0 through one of the device creation functions.

**Comment by jtorjo** [comment]
@ChewWorker Thanks! I will refactor my code to scale the controls themselves, but it's not a very easy task
