### ISSUE TITLE
question: are CanvasBitmaps held in the GPU video RAM?

### ISSUE THREAD

**Issue by jtorjo** [microsoft/Win2D#819]
This might be a silly question, but it's very important to me.

My take is the the CanvasBitmaps are actually help in the video RAM, so long story short, when allocating/caching CanvasBitmaps, I'm limited by the RAM of the video card, not the actual RAM.

Is my assumption correct?

**Comment by ChewWorker** [comment]
CanvasBitmaps are considered GPU (video) memory, but that memory is virtualized by the D3D/DXGI runtime so it will page memory out of your GPU into system memory and bring it back when it's required.  So you aren't limited by the RAM of the video card, but you will see performance improvements if you can keep everything resident.

**Comment by jtorjo** [comment]
@ChewWorker  Awesome, thanks!
