### ISSUE TITLE
Exception when attaching to CreateResources

### ISSUE THREAD

**Issue by t-sch** [Microsoft/Win2D#82]
Hi,
in a new prototype I'm testing how to create a UserControl that contains a CanvasConttrol as Content. My code works at runtime, but in the designer I get an exception if I attach to CreateResources in my UserControl's ctor:

   public class ActiveMapControl : UserControl
      {
      private CanvasControl canvas;

      public ActiveMapControl()
         {
         Content = canvas = new CanvasControl();
         canvas.CreateResources += canvas_CreateResources; // crashes if this line is enabled
         canvas.Draw += canvas_Draw;
         }

      void canvas_CreateResources(CanvasControl sender, CanvasCreateResourcesEventArgs args)
         {
         //if (Layers != null)
         //   Layers.CreateResources(sender, args);
         }
I got an exception message in XAML designer (a message format I never before saw there!):
![xaml_exception](https://cloud.githubusercontent.com/assets/8858830/7697112/9343e2e4-fe04-11e4-85a9-88d251aa8686.png)
Attaching draw works, I get a preview in Designer. Here's my corresponding XAML code:

   <Page.Resources>
      <am:Map x:Key="dplz" Source="DPLZ1503.LTG"/>
      <am:Map x:Key="topo" Source="DTopo1503.LTG"/>
   </Page.Resources>

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
      <am:ActiveMapControl Background="CornflowerBlue">
         <am:ActiveMapControl.Layers>
            <am:AreaLayer Map="{StaticResource dplz}" Ebene="3"/>
         </am:ActiveMapControl.Layers>
      </am:ActiveMapControl>
    </Grid>
</Page>
Any ideas?
Thomas

**Comment by damyanp** [comment]
Thanks for the report - the issue here is that CanvasControl's code to handle adding the CreateResources handler does a check to ensure that it is running on the UI thread. However, this check crashes when in design mode.  We'll work on getting this fixed.

In the meantime, you can add a check for design mode to work around this:

            if (!Windows.ApplicationModel.DesignMode.DesignModeEnabled)
            {
                canvas.CreateResources += canvas_CreateResources;
            }

**Comment by clandrew** [comment]
This was fixed in release 0.0.20.
