### ISSUE TITLE
question: CanvasAnimatedControl.Draw - what happens if a Draw event takes too long?

### ISSUE THREAD

**Issue by jtorjo** [microsoft/Win2D#820]
Lets say, for various reasons, every now and then, my `CanvasAnimatedControl.Draw` event takes 100ms.

I assume, the drawing routine will just wait for the event to end, then draw everything on screen, then continue firing events at 60 fps.

Is my assumption correct, or could that `.Draw` event be dropped and new events continue to fire at 60 fps?

LATER EDIT: 
https://microsoft.github.io/Win2D/WinUI2/html/T_Microsoft_Graphics_Canvas_UI_Xaml_CanvasAnimatedControl.htm

I see that even when `IsFixedTimeStep=True` I'm guessing unless .Draw takes an insane amount of time (which for me, is not the case), I should be fine. **Is this correct?**

**Comment by ChewWorker** [comment]
I believe you're asking if you Draw event takes too long will the current frame draw without your draw event completing?  After that's complete will it continue calling back every frame at a rate of 60fps?  Or will it drop to 10fps automatically.  Is that what you're asking?

**Comment by jtorjo** [comment]
> I believe you're asking if you Draw event takes too long will the current frame draw without your draw event completing? 

Yes. My current assumption is the system will wait for the Draw() function to compete. As I correct?

> After that's complete will it continue calling back every frame at a rate of 60fps? Or will it drop to 10fps automatically.

Yes. Basically, assuming it's a very rare event that will take roughly 100ms, I would assume once that completes, the Draw() event will continue to fire at 60fps. Am I correct?

**Comment by ChewWorker** [comment]
While I haven't had a chance to confirm I believe this is correct: the system will wait for the Draw function to complete.  And after a long frame the draw event should continue to fire at 60fps.

**Comment by jtorjo** [comment]
Awesome, thanks!
