### ISSUE TITLE
WinUI3: CanvasControl fills up system and gpu memory when continously resized

### ISSUE THREAD

**Issue by lhak** [microsoft/Win2D#821]
I think this is the same issue as https://github.com/microsoft/microsoft-ui-xaml/issues/3665. When comparing the SimpleSample from the UWP and WinUI branch, the WinUI version fills up the system and gpu memory when its window is continously resized. Only when it is competely filled, a large part is immediately freed.

**Comment by ChewWorker** [comment]
It does appear to be the same issue.

**Comment by lhak** [comment]
This is fixed when using winappsdk 1.3
