### ISSUE TITLE
Microsoft.Graphics.Canvas.Effects.dll missing?

### ISSUE THREAD

**Issue by Marv51** [microsoft/Win2D#829]
Hi, I'm only starting with Win2d, so please forgive me if this is a silly question:

Is there a DLL missing from the nuget package? I'm using the 0.5.0.14 "Microsoft.Graphics.Win2D" package.

This code triggers a DllNotFoundException for me:
```csharp
// using Microsoft.Graphics.Canvas.Effects;
var a = new GrayscaleEffect()
{
    Name = "Grayscale",
    Source = new CompositionEffectSourceParameter("Backdrop")
};
```

The exact exception is:
```
System.DllNotFoundException: 'Unable to load DLL 'Microsoft.Graphics.Canvas.Effects.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)'
```
I have confirmed that the nuget package does not contain a dll with that name and my project build output/appx also does not contain that dll.

I'm trying this from WinUI3(desktop) 0.5.7 with dotnet 5.

**Comment by Marv51** [comment]
Is no one else seeing this exception?

**Comment by getrou** [comment]
This is a limitation of Win2D using manifest-free activation, which we hope to fix in the future.  Microsoft.Graphics.Canvas.Effects.dll doesn't exist, but Microsoft.Graphics.Canvas.dll does, and it will find that dll successfuly if you continue past this debug break.

For a workaround, you can either f5 (continue) through this exception, change your debugging settings to not break when this exception is thrown, or you can manually add the following line to your appxmanifest.xml, which will explicitly tell your app how to activate these classes:

<Extension Category="windows.activatableClass.inProcessServer"> 
    <InProcessServer>
        <Path>Microsoft.Graphics.Canvas.dll</Path>
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.GrayscaleEffect" ThreadingModel="both" />
    </InProcessServer>
</Extension>

**Comment by Marv51** [comment]
@getrou Thank you very much for your pointers in the right direction! Even though Github did not post your suggestion correctly, with some additional research I came up with this solution: 
```xml
<Extensions>
	<Extension Category="windows.activatableClass.inProcessServer">
		<InProcessServer>
			<Path>MyApp\Microsoft.Graphics.Canvas.dll</Path>
			<ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.GrayscaleEffect" ThreadingModel="both"></ActivatableClass>
			<ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.ICanvasEffect" ThreadingModel="both"></ActivatableClass>
			<ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.ColorSourceEffect" ThreadingModel="both"></ActivatableClass>
			<ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.BorderEffect" ThreadingModel="both"></ActivatableClass>
			<ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.CanvasEdgeBehavior" ThreadingModel="both"></ActivatableClass>
			<ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.CrossFadeEffect" ThreadingModel="both"></ActivatableClass>

			<ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.UI.Composition.CanvasComposition" ThreadingModel="both"></ActivatableClass>
		</InProcessServer>
	</Extension>
</Extensions>
```

Especially because I'm using the Windows Community Toolkit, finding all the touched classes was a bit of a struggle. However, at least subjectively this seems to fix some of the performance issues I was seeing when adding effects to my WinUI 3 project.
