### ISSUE TITLE
The [NoComposition] tag on effects page means?

### ISSUE THREAD

**Issue by fantasyz** [microsoft/Win2D#843]
On this page ( https://microsoft.github.io/Win2D/WinUI2/html/N_Microsoft_Graphics_Canvas_Effects.htm ), some effects are tagged [NoComposition]. Does it means those effects need to be the last one in a composition pipeline (No further composition)? Or does it mean I simply should not put it in the CompositeEffect?

**Comment by lmadhavan** [comment]
If you look at the documentation for one of those effects, you'll see:

> *Supported by Win2D but not Windows.UI.Composition.*

This refers to the [UWP composition layer](https://docs.microsoft.com/en-us/windows/uwp/composition/visual-layer), and any effects marked `[NoComposition]` cannot be used with this framework. It has no impact on raw Win2D, you can compose them in any manner as long as you are rendering it by yourself.
