### ISSUE TITLE
Wrap all text, CanvasTextLayout

### ISSUE THREAD

**Issue by Hibees** [Microsoft/Win2D#86]
I need to Wrap all the text on a CanvasTextLayout, the text shouldn't trim just resize to fit the canvastextlayout

My Workaround is to reduce the font size till the layoutbound is equal or less than RequestedSize.
But can hurt performance.

I am not very fluent on C++, but can try implementing this if I have some guidance on where to modify to have this feature.

Thanks for the help

**Comment by clandrew** [comment]
Sure, this is doable. 
Did you set the CanvasWordWrapping property of the CanvasTextLayout to Wrap? 
Does the RequestedSize match the bounds that you are trying to wrap against?

**Comment by clandrew** [comment]
Closing this, but feel free to re-activate if the above isn't sufficient, or if you need more information.

**Comment by Hibees** [comment]
Did you set the CanvasWordWrapping property of the CanvasTextLayout to Wrap?
yes
Does the RequestedSize match the bounds that you are trying to wrap against?
No.
the layoutbound grows according to the characters* fontsize of the Text
So to fit correctly I need to found the perfect FontSize
Currently don't have my code with me.
But works something like this:
FontDesiredSize = 0.18f
Textformat.FontSize=FontDesiredSize;
Canvastextlayout  canvastext = new //this line Initialize Canvastextlayout for the firsttime
While(canvastext .Layoutbound.height> canvastext.RequestedSize.height)
{
FontDesiredSize -=.01;
Textformat.FontSize=FontDesiredSize;
canvastext = //Recreate Canvastextlayout with new text format
}

Did I explained myself correctly?

**Comment by clandrew** [comment]
Oh, so more what this is asking for, is:

"How to I look up the biggest font size I can use, such that all my text will fit inside a given rectangle?" Without experimenting with different font sizes. Is that right?

**Comment by Hibees** [comment]
Yes, that is what i was trying to ask

**Comment by shawnhar** [comment]
If word wrapping is not enabled, you could do this by creating a text layout using a very large requested size and arbitrary fixed font size, read back whatever the resulting layout bounds are, then use the CanvasDrawingSession.Transform property when you render this text layout to resize it from however big it ended up to the actual size you want it to be.  This will give high quality scaling without having to make a new text layout.

If you are also wanting to word wrap the text, things get much more complicated as there are now several independent ways that changing font size can affect the resulting layout, so a simple post-scale is no longer sufficient.  In this case I think the only option is to do a binary search, trying layouts with different font sizes to see which ones fit vs. which do not.

**Comment by Hibees** [comment]
I need to use Word wrapping, so the second solution is the one to go.
Because a capitalized letter took more space, I added the FirstLineCharactersToUpper method to the equation.
In case of songs I will need to get the best font for all the verses per song.
Is there any other way to do this? it's taking like 100ms to do this calculation. 
This is my code:
String NewText = String.Empty;
            NewText = FirstLineCharactersToUpper(canvastext.GetCharacterRegions(0, Original.Length), Original);
             canvastext = new CanvasTextLayout(resourceCreator, NewText, textFormat, canvasWidth, canvasHeight);
            while (canvastext.LayoutBounds.Width > canvasWidth || canvastext.LayoutBounds.Height > canvasHeight )
            {
                decrement -= .01f;
                textFormat.FontSize = sizeDim * decrement;
                 NewText = FirstLineCharactersToUpper(canvastext.GetCharacterRegions(0, Original.Length), Original);
                canvastext = new CanvasTextLayout(resourceCreator, NewText, textFormat, canvasWidth, canvasHeight);
            }
             NewText = FirstLineCharactersToUpper(canvastext.GetCharacterRegions(0, Original.Length), Original);
            canvastext = new CanvasTextLayout(resourceCreator, NewText, textFormat, canvasWidth, canvasHeight);
Thanks for the help.

**Comment by shawnhar** [comment]
You could do this much more quickly by using a binary search as opposed to linear algorithm.

This design is always going to require some form of search, because it's too complex a problem to solve with a single layout pass.  If either one of font size or layout were fixed, it could be done with just one operation (either compute a layout for text using a known font size, or start with a known layout, and then scale it to fill whatever region you have available for the output).  But when both these factors can vary, the problem becomes extremely complex and non-linear, so I think there is no choice but repeatedly trying different layouts until you identify the size that only just fits.

You can optimize that by using an O(log(N)) as opposed to O(N) search algorithm, but some form of search will always be required given what you are trying to do.

**Comment by Hibees** [comment]
Thanks, I will try to do a binary search, however this can be more expensive in most cases as the "default desired value" is .18 and minimum value is .01, and in most cases it is .02~.03 below the "default desired value".

Also what fontsize value means? is it the percentage of the screen the CharacterRegion takes? being 1 all the LayoutBound per character?
