### ISSUE TITLE
CanvasImageSource disappears upon minimize / screen lock - UWP

### ISSUE THREAD

**Issue by tonyhallett** [microsoft/Win2D#864]
This occurs when drawn with text, CanvasGeometry, CanvasSvgDocument and ink strokes.

For instance - Xamarin forms uses the CanvasImageSource for font icons. https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Platform.UAP/FontImageSourceHandler.cs#L39

https://github.com/xamarin/Xamarin.Forms/issues/8293
https://github.com/xamarin/Xamarin.Forms/issues/14323

**Comment by juan-** [comment]
Hi Tony! Thanks for bringing this to our attention. Could we get more information? Are you seeing Xamarin content disappear or is this your own usage of CanvasImageSource that is the problem?

**Comment by tonyhallett** [comment]
It occurs in a regular UWP app without Xamarin Forms in addition to Xamarin Forms.

**Comment by JohnnyWestlake** [comment]
I would assume this would be because the Xamarin codebase isn't handling DeviceLost at any point? https://microsoft.github.io/Win2D/WinUI2/html/HandlingDeviceLost.htm

Would be something that would have to be manually implemented on the Xamarin side.

**Comment by tonyhallett** [comment]
@JohnnyWestlake 

> "Device lost" refers to a situation where the GPU graphics device becomes unusable for further rendering. This can occur due to GPU hardware malfunction, driver bugs, driver software updates, or switching the app from one GPU to another.

Doesn't sound like something that should happen when an app ( including UWP without Xamarin ) is minimized.

**Comment by juan-** [comment]
@tonyhallett, On minimize the system will try to reclaim resources, but may not trigger a device lost. Could you debug to see if IsDeviceLost or a similar event is being raised?

**Comment by shawnhar** [comment]
I'm not familiar with the Xamarin codebase, but the described symptom sounds like CompositionTarget.SurfaceContentsLost event was raised but the implementation didn't redraw the image source in response.

**Comment by tonyhallett** [comment]
@shawnhar 

It occurs in a UWP app with no connection to Xamarin too.

**Comment by tonyhallett** [comment]
@juan- 
I will when I get the opportunity.

**Comment by tonyhallett** [comment]
DeviceLost event does not get raised

```
public static class FontCanvasImageSourceProvider
    {
        static readonly float _minimumDpi = 300;
        public static event EventHandler DeviceLost;

        public static CanvasImageSource Provide(string fontFamily, float fontSize, string glyph, Windows.UI.Color iconColor)
        {
            var device = CanvasDevice.GetSharedDevice();
            device.DeviceLost += Device_DeviceLost;
            var dpi = Math.Max(_minimumDpi, Windows.Graphics.Display.DisplayInformation.GetForCurrentView().LogicalDpi);

            var textFormat = new CanvasTextFormat
            {
                FontFamily = fontFamily,
                FontSize = fontSize,
                HorizontalAlignment = CanvasHorizontalAlignment.Left,
                VerticalAlignment = CanvasVerticalAlignment.Center,
                Options = CanvasDrawTextOptions.Default
            };

            using (var layout = new CanvasTextLayout(device, glyph, textFormat, fontSize, fontSize))
            {
                var canvasWidth = (float)layout.LayoutBounds.Width + 2;
                var canvasHeight = (float)layout.LayoutBounds.Height + 2;

                var imageSource = new CanvasImageSource(device, canvasWidth, canvasHeight, dpi);
                using (var ds = imageSource.CreateDrawingSession(Windows.UI.Colors.Transparent))
                {
                    // offset by 1 as we added a 1 inset
                    ds.DrawTextLayout(layout, 1f, 1f, iconColor);
                }

                return imageSource;
            }
        }

        private static void Device_DeviceLost(CanvasDevice sender, object args)
        {
            DeviceLost?.Invoke(sender, EventArgs.Empty);
        }
    }

```

UWP repo https://github.com/tonyhallett/DemoCanvasImageSourceDisappears

![image](https://user-images.githubusercontent.com/11292998/156442766-0cc4dac1-6009-410c-b164-fb43a90e3e72.png)

Minimize and the maximize

![image](https://user-images.githubusercontent.com/11292998/156442859-c7d7f7ae-c239-4f6e-a282-6734b2ca57df.png)

**Comment by shawnhar** [comment]
I would expect this scenario to raise CompositionTarget.SurfaceContentsLost but not device lost.

**Comment by tonyhallett** [comment]
@shawnhar 
Yes that is the case.

**Comment by shawnhar** [comment]
In that case this is an app bug, as SurfaceContentsLost needs to be handled.

If you prefer a higher level programming interface that does not require attention to such details, I'd recommend using the more abstracted CanvasControl in place of the lower level CanvasImageSource.

**Comment by tonyhallett** [comment]
@shawnhar Thanks.
