### ISSUE TITLE
Draw image with color

### ISSUE THREAD

**Issue by lukerayman** [Microsoft/Win2D#87]
CanvasDrawingSession.DrawImage() method allows to draw an image, but I can't find any way to do this with color, like you do it with textures. I guess white color is just set as default. Is there any way to change it and use any other color for drawing images? 

I wish I could use one grayscale image to be drawn in different colors, but I can't figure out how to do this with Win2D.

**Comment by damyanp** [comment]
Currently the only way to do this is using ColorMatrixEffect.  Some sample code:

    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        ColorMatrixEffect red;
        ColorMatrixEffect green;
        ColorMatrixEffect blue;
        CanvasBitmap bitmap;

        private void CanvasControl_Draw(CanvasControl sender, CanvasDrawEventArgs args)
        {
            var ds = args.DrawingSession;

            ds.DrawImage(bitmap, 0, 100);
            ds.DrawImage(red, 100, 100);
            ds.DrawImage(green, 200, 100);
            ds.DrawImage(blue, 300, 100);
        }

        private void CanvasControl_CreateResources(CanvasControl sender, CanvasCreateResourcesEventArgs args)
        {
            var rt = new CanvasRenderTarget(sender, 64f, 64f);
            using (var ds = rt.CreateDrawingSession())
            {
                ds.Clear(Colors.Transparent);
                ds.DrawCircle(32, 32, 32, Color.FromArgb(255, 128, 128, 128), 1);
            }

            bitmap = rt;
            red = new ColorMatrixEffect { Source = rt, ColorMatrix = MakeColorMatrix(Colors.Red) };
            green = new ColorMatrixEffect { Source = rt, ColorMatrix = MakeColorMatrix(Colors.Green) };
            blue = new ColorMatrixEffect { Source = rt, ColorMatrix = MakeColorMatrix(Colors.Blue) };
        }

        private Matrix5x4 MakeColorMatrix(Color color)
        {
            var m = new Matrix5x4()
            {
                M11 = color.R, M12 = 0,       M13 = 0,       M14 = 0,
                M21 = 0,       M22 = color.G, M23 = 0,       M24 = 0,
                M31 = 0,       M32 = 0,       M33 = color.B, M34 = 0,
                M41 = 0,       M42 = 0,       M43 = 0,       M44 = color.A,
                M51 = 0,       M52 = 0,       M53 = 0,       M54 = 0,
            };
         
            return m;
        }
    }

**Comment by lukerayman** [comment]
Thank you for the response. Your cod will be very useful for me.

**Comment by tushargoyal1309** [comment]
If I have to show only Red component then what should I do?

**Comment by shawnhar** [comment]
You can transform colors in any way you like by changing the color matrix.  The docs for ColorMatrixEffect (http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Effects_ColorMatrixEffect.htm) explain how this works.

**Comment by tushargoyal1309** [comment]
Can you please give me an example with sample code on what to put in Canvas_draw method.I'll be very thankful to you.

**Comment by 13thsymphony** [comment]
@tushargoyal1309, Damyan's sample code above already shows everything you need. The "red" matrix only applies colors from the red channel.

**Comment by tushargoyal1309** [comment]
@13thsymphony ,I meant to say what values of the components like for grayscale we have like this kind of Matrix:
var matrix = new Matrix5x4();

                matrix.M11 = (float)0.299;
                matrix.M21 = (float)0.587;
                matrix.M31 = (float)0.114;
                matrix.M41 = (float)Math.Sin(0);
                matrix.M51 = (float)Math.Sin(0);

                matrix.M12 = (float)0.299;
                matrix.M22 = (float)0.587;
                matrix.M32 = (float)0.114;
                matrix.M42 = (float)Math.Sin(0);
                matrix.M52 = (float)Math.Sin(0);

                matrix.M13 = (float)0.299;
                matrix.M23 = (float)0.587;
                matrix.M33 = (float)0.114;
                matrix.M43 = (float)Math.Sin(0);
                matrix.M53 = (float)Math.Sin(0);

                matrix.M14 = (float)Math.Sin(0);
                matrix.M24 = (float)Math.Sin(0);
                matrix.M34 = (float)Math.Sin(0);
                matrix.M44 = (float)1;
                matrix.M54 = (float)Math.Sin(0);

Like this for Red also we'll be having some values.Just I wanted to know that.

**Comment by 13thsymphony** [comment]
`private Matrix5x4 MakeColorMatrix(Color color)` defines the color matrix you would use.

**Comment by JranZu** [comment]
In case anyone else finds this and can't get MakeColorMatrix(Color color) to work, your need to divide all the Color properties (RGBA) by 255 to get a float.
