### ISSUE TITLE
Question: Memory Leaks when change 'CanvasCachedGeometry' dynamically

### ISSUE THREAD

**Issue by ifgotmoney** [microsoft/Win2D#871]
hi,

```
C++/WinRT, 
Windows App Sdk 1.0 (winui3), 
Win2D
```

I'm trying to cache the `CanvasGeometry `into `CanvasCachedGeometry `using below code in a use class. but when I change `CanvasGeometry `and `CanvasCachedGeometry`, seems there are significant memory leaks, 

class.h
```
	win2D::Geometry::CanvasGeometry m_uncachedgeometry{ nullptr };
	win2D::Geometry::CanvasCachedGeometry m_stroke{ nullptr };
	win2D::Geometry::CanvasCachedGeometry m_fill{ nullptr };
```

class.cpp
```
auto _shareddevice = win2D::CanvasDevice::GetSharedDevice();
float radius=50;
m_uncachedgeometry =win2D::Geometry::CanvasGeometry::CreateCircle(_shareddevice,m_CenterPoint, radius);
m_stroke = win2D::Geometry::CanvasCachedGeometry::CreateStroke(m_uncachedgeometry,2);
m_fill = win2D::Geometry::CanvasCachedGeometry::CreateFill(m_uncachedgeometry);
```

`m_CenterPoint `is to be changed dynamically, so that the `CanvasGeometry `and `CanvasCachedGeometry `need to be re-generate from time to time. but seems this causes memory leaks every time. do I miss something important here?

**Comment by ifgotmoney** [comment]
I have just tested the code with `CanvasRenderTarget`, no leaks,  and performance much better, only higher memory consumptions.

**Comment by shawnhar** [comment]
My guess is you're probably not disposing the old objects before creating new ones?

If all you're doing is moving the position of an object, there's no need to recreate the geometry though.  Just cache it once, then change the transform when drawing it to a different position.

**Comment by ifgotmoney** [comment]
@shawnhar , thanks for your reply. 
Indeed I have tried disposing the old object but using below code, but seems still leaks.
```
if (m_stroke){m_stoke.close(); m_stroke=nullptr;}
```
is this the right way to dispose objects such as CanvasRenderTarget CanvasCachedGeometry CanvasGeometry, etc.?

**Comment by ifgotmoney** [comment]
Solved.
