### ISSUE TITLE
Hybrid CRT

### ISSUE THREAD

**Issue by Marv51** [microsoft/Win2D#874]
Hi, I just listened to the latest WinUI 3 Community Call. Scott Jones presented on Hybrid CRT. I looked a bit into my app after I updated to WinAppSDK 1.0.3. It seems to me that only reason that I need to worry about the VC redistributable at all is Win2D/Microsoft.Graphics.Canvas.

Are you looking into also adopting Hybrid CRT? 

Information on Hybrid CRT can be [found here](https://github.com/microsoft/WindowsAppSDK/blob/main/docs/Coding-Guidelines/HybridCRT.md).

**Comment by getrou** [comment]
We are looking into adopting Hybrid CRT! We will update this issue once we have more information about how soon that will be ready.

**Comment by Marv51** [comment]
While I haven't really been able to build an MSIX package of my app without VC redistributable (see also microsoft/WindowsAppSDK#2425), analyzing all the binaries with `dumpbin /dependents` shows that the redistributable is no longer needed for my app. 🥳🥳🥳

One less thing to worry about, thank you.
