### ISSUE TITLE
CanvasControl inside UserControl seems to lose DataContext/Binding when ina scrooling Listview

### ISSUE THREAD

**Issue by mibuehrer** [microsoft/Win2D#877]
Question:
What I want to do is to have some (~200) Win2D CanvasControl's in a scrollable ListView. Since I know that I have to RemoveFromVisualtree each of the controls, I encapsulated them in a UserControl. but when the ListView scrolls the bindings seem to get weird I reduced the problem to the following:
 The Model has a List of 500 ModelItems (just a property Label) I've created two UserControls both with Binding the label; both report this label in two lines; Win2DCtrl1 is a WinUI only solution (both lines bind Label to a TextBox), Win2DCtrl2 is close to the desired solution: the first line is a textbox (as above), the second line is drawn in a CanvasControl

Now, what's happening is: when the listview starts scrolling, line1 and line 2 show different values in Win2DCtrl2!

The simple TestApp shows is on [github.com/mibuehrer](https://github.com/mibuehrer/testapp)
Q: What am I doing wrong 
Q: Will this ever work with large lists?

**Comment by getrou** [comment]
Hello, we are looking into this! But for starters, it seems to be a problem with how items in the list views are virtualized, and then your app isn't re-rendering your CanvasControls when the information is lazily populated.  I expect we'll have to hook in to some event and have the CanvasControl re-render when that triggers.

**Comment by getrou** [comment]
I took another look at this, and it seems like the easiest solution is to hook into the DataContextChanged event handler on your Win2DCtrl2 and when that happens, simply call Canvas.Invalidate(). This will redraw your canvases whenever they get realized in the ListView. Hope this helps!

**Comment by mibuehrer** [comment]
This seems too help.
Thanks a lot
