### ISSUE TITLE
Win2D with NVIDIA Reflex?

### ISSUE THREAD

**Issue by pcfulife** [microsoft/Win2D#878]
I am implementing NVIDIA Reflex technology on my Win2D based game app.
NVIDIA Reflex C API requires Direct3DDevice object.

(Win32 C++)
```
ID3D11Device* GetD3D11(IDXGIDevice* dxgi) {
	ID3D11Device* pvObject = nullptr;
	handle->QueryInterface(__uuidof(ID3D11Device), (void**)&dxgi);

	return pvObject;
}
```

(C#)
```
    IntPtr dxgi = Marshal.GetComInterfaceForObject(MyCanvasDevice, typeof(IDirect3DDevice));
    IntPtr d3d11 = GetD3D11(d3d);
```

`dxgi` has a valid address, But, `d3d11` is nullptr.

How can I get a Direct3D11Device object from Win2D CanvasDevice with P/Invoke?

**Comment by getrou** [comment]
Hi! For my own information in reproducing this, are you using Win2D with WinUI3 (Microsoft.Graphics.Canvas.nupkg) or Win2D for UWP (Win2d.uwp.nupkg)?

**Comment by pcfulife** [comment]
@getrou I uses Win2D for UWP

**Comment by pcfulife** [comment]
I implemented it. If someone wants to implement this. Open issue.
