### ISSUE TITLE
Gallery app crashes with screen rotation on Win10 build 10122

### ISSUE THREAD

**Issue by adammarks** [Microsoft/Win2D#88]
Environment:
Using Win10 Build 10122  ( also seen in 10074 ) on a HP X360 from Build.
We are also seeing this on Surface Pro 3's with Build 10074

Steps:
1. Download the Win2D Gallery App
2. Open the app and select a image effect
3. Rotate the app

Results:
Crash that appears to be video driver related.

Expected:
Rotate should work as expected.

Other Info:
The HP X360 has Intel HD5500 internal graphics
The Surface Pro 3's have Intel HD5000 internal graphics

We are seeing this same crash with internally developed Win10 UWP code when there is a Win2D canvas on the screen.

**Comment by shawnhar** [comment]
Thanks for the report; we'll take a look.

**Comment by clandrew** [comment]
We reproed this crash on an Intel 4400 laptop, and it appears to be an Intel driver bug. It happened on build 10130. However, it did not repro on newer builds. Tried 10140, 10152. 

I will close this as a non-repro, given it doesn't happen in the latest. Something in the OS has changed to fix it. Of course, feel free to re-open if it something happens again on new builds.
