### ISSUE TITLE
Multiple canvascontrols in an app?

### ISSUE THREAD

**Issue by dlr2** [Microsoft/Win2D#89]
When I try to use more than one canvas control in an app, during debug runs, I get the error:
IN ROUTINE:
       public void InitializeComponent()
IN LINE:
#if DEBUG && !DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
where e >>>
     Message = "Objects used together must be created from the same factory instance.\r\n"

Am I allowed to use multiple canvas controls in an app? If so how?

**Comment by shawnhar** [comment]
You can use more than one CanvasControl, but currently each control will have a separate CanvasDevice.  Graphics resources are specific to the device they were created by, so this means you cannot share resources created by one control and then use them with a different control.  You need to make a separate set of resources per control  (typically using the CreateResources event of each control to do so).

We are working on an optimization to share graphics devices between multiple CanvasControl instances, at which point resources will also be able to be shared.
