### ISSUE TITLE
Outline Text

### ISSUE THREAD

**Issue by tpoint75** [microsoft/Win2D#892]
Hello I try to draw outlined text in WIN UI 3 winrt/c++ wint WIN2D 1.0.4

I modified the example like this:

 void MainWindow::canvasControl_Draw(CanvasControl const& sender, anvasDrawEventArgs const& args)
    {
       args.DrawingSession().TextRenderingParameters(
                CanvasTextRenderingParameters(CanvasTextRenderingMode::Outline, CanvasTextGridFit::Default) ); //outline
        args.DrawingSession().DrawText(L"Hello, world!", 100, 100, Colors::Yellow()));
    }

But i can't see the outline over the background. So the text is difficult to read!

**Comment by getrou** [comment]
Hello! Could you give me some more information? It looks like you're drawing yellow text over a white (I assume?) background. You could do a few things here: you could change the color of the text to be a slightly darker color, darken the background, or you could try something like this to modify the stroke if it is too thin: http://microsoft.github.io/Win2D/WinUI3/html/M_Microsoft_Graphics_Canvas_Geometry_CanvasGeometry_CreateText.htm
