### ISSUE TITLE
Getting high gpu usage with canvas swapchain

### ISSUE THREAD

**Issue by quantgames** [microsoft/Win2D#895]
I'm getting high GPU usage (>30-40%) on the following code using the canvas swap chain:

```
while (true)
  {
      using (CanvasDrawingSession drawingSession = swapChain.CreateDrawingSession(Colors.White))
      {
             drawingSession.FillCircle(1, 1, 5, Colors.Red);
      }
      swapChain.Present();
      swapChain.WaitForVerticalBlank();   // same GPU usage with or without this line
  }
```

**Comment by getrou** [comment]
Hm, I'm not seeing this on my end. Some follow-up questions to help diagnose:
- Are you seeing this on WinUI3 or UWP? 
- Can you log how many times per second Present() is getting called, and if that matches the refresh rate of the monitor?

**Comment by quantgames** [comment]
It is UWP. I went with a different approach with CanvasDrawEventArgs instead and using a timer to invalidate CanvasControl every 10 ms which is around my refresh rate. And I get better GPU usage (25-30%) but its still pretty high.
It may be due to the canvas being really large (3000x2000 pixels). Is there a way to invalidate the regions where I am drawing instead of redrawing the whole canvas?

**Comment by getrou** [comment]
Not for CanvasControl, but you could use CanvasVirtualControl, which would give you this functionality:
https://microsoft.github.io/Win2D/WinUI2/html/M_Microsoft_Graphics_Canvas_UI_Xaml_CanvasVirtualControl_Invalidate_1.htm

**Comment by kmgallahan** [comment]
Compare the current GPU clock speed while rendering to the max GPU speed. The % usage is relative to the current speed, not the max. If you have 30% usage while GPU is at 10% max, then that translates to ~3% utilization.

**Comment by quantgames** [comment]
Okay so my clock speed is about 25% of max speed and GPU is at 40% on average, so its roughly 10% actually GPU utilization. Which is still pretty high. I looked into CanvasVirtualControl, it does not allow me create a drawing session anywhere, only the regions I am invalidating.

If I draw circle at 100,100 and invalidate that region, how can I draw the same circle at 200,200 using CanvasVirtualControl?

**Comment by kmgallahan** [comment]
I'd haven't used it, but I'd presume you'd have to invalidate the region containing the old circle to 'delete' it (e.g., draw over with background color), then invalidate the region containing the new circle to draw it there. Alternatively, you'd calculate the bounds containing both, paint over it all, then draw second location.
