### ISSUE TITLE
CanvasBitmap is not registered

### ISSUE THREAD

**Issue by lukerayman** [Microsoft/Win2D#90]
I have no idea what's happened. It worked perfectly yesterday. But today I'm getting crash on loading CanvasBitmap.
> Requested Windows Runtime type 'Microsoft.Graphics.Canvas.CanvasBitmap' is not registered. 

I didn't change my code where the Win2D Canvas control is. Didn't touch assets with my textures. Here's where I'm getting the crash:

```c#
private async void OnCreateResources(CanvasAnimatedControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
{
    virusBitmap = await CanvasBitmap.LoadAsync(sender, @"Assets/Textures/Virus.png");
}
````

When I remove this code and don't use CanvasBitmap, it works.

**Comment by lukerayman** [comment]
OK, I found the cause. It's a Microsoft.Advertising.Mobile.UI. App started crashing when added this library. But anyway, I want ads in my app and still be able to use CanvasBitmap.

**Comment by shawnhar** [comment]
Is this the same as issue #59?

That was due to a bug in VS2013 Update 4, which is fixed in VS2013 Update 5 (and VS2015).

**Comment by damyanp** [comment]
I can confirm that I can reproduce this issue just by adding the advertising SDK to a modified SimpleSample that activates a CanvasBitmap instance and building/deploying with VS2013 Update 4.

The exact same project and code rebuilt and deployed with [VS2015](https://www.visualstudio.com/en-us/downloads/visual-studio-2015-downloads-vs) works fine.

**Comment by lukerayman** [comment]
Confirmed. Works fine with VS2015. Thank you.
