### ISSUE TITLE
CS8002	Referenced assembly 'Microsoft.Graphics.Canvas.Interop, Version=1.0.26.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.	

### ISSUE THREAD

**Issue by testalino** [microsoft/Win2D#907]
I would appreciate if the next Nuget release would have a PublicKeyToken.
The current version 1.0.4 of Microsoft.Graphics.Win2D does not have one.
Thanks.

**Comment by getrou** [comment]
Thanks for bringing this to our attention! I'll look into fixing this for our next release.

**Comment by Sergio0694** [comment]
This is fixed internally and will be included in 1.1.0-preview1, closing this. Thank you @testalino! 🙂
