### ISSUE TITLE
Support for color emojis in win2d text

### ISSUE THREAD

**Issue by FrozenAssassine** [microsoft/Win2D#909]
Please support colored emojis when drawing text using DrawTextLayout

**Comment by getrou** [comment]
Definitely in favor of doing this work, I'll look at what this would take to implement.

**Comment by JohnnyWestlake** [comment]
This is already supported, just set CanvasTextLayout/Format.Options to EnableColorFont

**Comment by FrozenAssassine** [comment]
@JohnnyWestlake Thank you very much, this worked perfectly.
