### ISSUE TITLE
Canvas.Numerics Types missing common operators

### ISSUE THREAD

**Issue by markmnl** [Microsoft/Win2D#91]
e.g. Vector2 and Vector3 missing multiply operator

**Comment by shawnhar** [comment]
Please share more details of what version of Win2D you are using, what platform you build for, and what code is not working.

If you are building for Windows or Phone 8.1, this operator is provided as part of Win2D:  http://microsoft.github.io/Win2D/html/M_System_Numerics_Vector2_op_Multiply.htm

If you are building for Windows 10, it is provided by the System.Numerics.Vectors NuGet package: https://msdn.microsoft.com/en-us/library/dn877600%28v=vs.111%29.aspx

**Comment by markmnl** [comment]
Apologies, I am using Windows 8.1 NuGet package 0.0.19.

I see now I have somehow ended using a `Microsoft.Graphics.Canvas.Numerics.Vector2` instead of a `System.Numerics.Vector2`. 

Nonetheless I cannot seem to get `System.Numerics.Vector2` - the one and only NuGet package I see: Win2D is added to my Windows 8.1: Class Library (Windows Apps type) and Blank Universal App, and System.Numerics only defines the two types: `BigInteger` and `Complex`...

**Comment by markmnl** [comment]
That said I can see `System.Numerics.Vector2` in the object browser from the assembly: `Win2D.0.0.19\build\win\..\..\bin\Windows\x86\Microsoft.Graphics.Canvas.Numerics.dll`...

**Comment by markmnl** [comment]
(I guess anyone creating a new Windows 8.1 app today will observe the same)

**Comment by shawnhar** [comment]
This is working as it should be.  The 8.1 version of Win2D includes the System.Numerics.Vectors types - you just need to change your namespace to use these instead of the WinRT structs from Microsoft.Graphic.Canvas.Numerics.

More info:

blogs.msdn.com/b/win2d/archive/2014/09/15/why-does-win2d-include-three-different-sets-of-vector-and-matrix-types.aspx
http://microsoft.github.io/Win2D/html/N_Microsoft_Graphics_Canvas_Numerics.htm
http://microsoft.github.io/Win2D/html/N_System_Numerics.htm

**Comment by markmnl** [comment]
Understood, but adding `using System.Numerics` does not give me `Vector2` it only gives me `BigInteger and Complex`, it is as if I need to add ref to another assembly?

**Comment by shawnhar** [comment]
System.Numerics namespace does include the Vector2 type if you have added the Win2D NuGet package.

What project type are you trying to use this from?

**Comment by markmnl** [comment]
Just tried in a brand new Store Apps > Universal Apps > Blank App (Universal Apps) project adding Win2D 0.0.19 from NuGet and same result (VS 2013 Ultimate Update 4).

**Comment by shawnhar** [comment]
Are you trying to build for AnyCPU target, by any chance?

**Comment by markmnl** [comment]
Nope x86

Aha! it seems to be a Visual Studio issue - compiling actually works it just shows up in red with cannot resolve symbol Vector2() even after rebuild all and running..

**Comment by markmnl** [comment]
Aha! Was Resharper - turning that off all OK! 

Sorry for hassle - when I see red in IDE with cannot resolve symbol I believe it!

**Comment by shawnhar** [comment]
Interesting - I'll have to try installing Resharper and see what we're doing that could be messing that up.

Anyway, glad to hear you got this unblocked!

**Comment by markmnl** [comment]
Please do - was using the latest Resharper, I suspect it might have something to be with their being two assemblies containing the System.Numerics namespace and Resharper was only pulling in the Types from one.. Just a guess.
