### ISSUE TITLE
Mixing Win2D with XNA/MonoGame

### ISSUE THREAD

**Issue by ronnycsharp** [Microsoft/Win2D#92]
Hi,
I've created a universalapp with monogame and added the Win2D Nuget Package.
It works great. I want to make the UI with Win2D and need a BlurEffect over my XNA/MonoGame Screen-Output. Is there a way to do this?

Regards
Thx

Ronny

**Comment by shawnhar** [comment]
Win2D can interop with native D2D or D3D - see the "Direct3D Interop" sample (part of the Example Gallery app) for an example of how to do this.

If MonoGame provides a similar ability, you should be able to connect the two via a double-hop interop approach, MonoGame -> D3D -> Win2D  (or vice versa).   I'm not familiar enough with MonoGame to know if it provides such an ability, though.  The original Microsoft XNA product definitely did not  (it was a walled garden type implementation with no option to mix with other rendering technologies).

**Comment by ronnycsharp** [comment]
thx, I will check it.
