### ISSUE TITLE
Direct2D (Win2D) Stutters on RTX 40 graphics card

### ISSUE THREAD

**Issue by pcfulife** [Microsoft/Win2D#926]
I posted it on NVIDIA developer forum (https://forums.developer.nvidia.com/t/performance-of-direct2d-is-too-low-on-rtx-40-series-gpu/259997)

To recap, Direct2D (Win2D) performance drops significantly only on RTX 40 series graphics cards.

The highest frame rate is fine, but the low 1% frame rate drops dramatically. After debugging, there were cases where severe stalls occurred when various Win2D APIs (DrawTextLayout, DrawImage, etc.) were executed on the RTX 40 graphics card.

**Comment by getrou** [comment]
@ChewWorker this seems like it might be a D2D issue more than a Win2D issue (although I could be wrong)

**Comment by pcfulife** [comment]
@getrou You're right. This is not a problem of Win2D, I think it is a problem of Direct2D, but anyway, I raised an issue since it is the same Microsoft product

**Comment by pcfulife** [comment]
I manually fixed it by chaning method of copying frame buffers.
