### ISSUE TITLE
Rendering delay in loading the font from the "ms-appdata"?

### ISSUE THREAD

**Issue by pavan709** [Microsoft/Win2D#928]
I have requirement of loading the text on scroll, each text will be having different font and such texts are in 100's, while scrolling i will be fetching the fonts from the ms-appdata://, which is causing delay in rendering, is there any way to cache these font for the first load and then use them afterwards instead of fetching again by ms-appdata:// 
```[tasklist]
### Tasks
```

**Comment by getrou** [comment]
How are you loading your fonts currently? Are you using the CanvasFontSet constructor?

Win2D won't cache these fonts internally, you'd have to cache the loaded objects yourself.

**Comment by pavan709** [comment]
@getrou  I am not using the CanvasFontSet Constructor, i am doing it like this
 `new CanvasTextFormat{ FontFamily = "ms-appdata:///Assets/Fonts/Artifika.ttf"};
`

**Comment by getrou** [comment]
I see. with that API you'd also still have to cache that object on the app's side, otherwise Win2D would reload that from file every time that is called.

**Comment by pavan709** [comment]
@getrou  as from this [documentation](https://microsoft.github.io/Win2D/WinUI2/html/P_Microsoft_Graphics_Canvas_Text_CanvasTextFormat_FontFamily.htm) there are only two ways to provide the font family, with font family name and with uri, i did not find the caching any where, it would be helpful if you elaborate on how font file caching be done.

**Comment by pavan709** [comment]
@getrou any update?

**Comment by getrou** [comment]
Hm, sorry I may be misunderstanding your scenario. Are you able to just cache and reuse the CanvasTextFormat object? Looking at the CanvasTextFormat code I would think that if you just reuse the same CanvasTextFormat object it will not reload the font from file, as it caches the IDWriteTextFormat1 internally, but let me know if you think I'm missing something.
