### ISSUE TITLE
Microsoft Authenticator

### ISSUE THREAD

**Issue by JoseIvanHernandez** [Microsoft/Win2D#929]
Cannot find my codes to reset. Cannot log into my outlook account that gets me into my Microsoft Subscription. Hence, I have had to learn code to find my way back in since I cannot manage to get Microsoft to help me. I could use some help from you, the experts.

**Comment by getrou** [comment]
Hi, sorry, Authenticator and Microsoft Subscriptions are outside the purview of Win2D, I think you'll need to contact Microsoft support.
