### ISSUE TITLE
Create CanvasRendertarget without any UI

### ISSUE THREAD

**Issue by SeriousGeorge** [Microsoft/Win2D#93]
Hi there,

I moved this topic from the comments here:http://blogs.msdn.com/b/win2d/archive/2015/05/11/win2d-0-0-18-vacations-doc-improvements-and-exif-rotation-support.aspx

**Case**
I'm trying to create Text as Bitmap in a backgroundprocess, so I'm not allowed to use any UI of course. 

I think I'm just a inch before my goal but are struggling now with the fact that I can't set a device manually to a CanvasControl created programmatically because it's device property is read-only.

**My code:**
```c#
CanvasControl canvasControl = new CanvasControl();
CanvasDevice device = new CanvasDevice();
//canvasControl.Device = device; //does not work, read only

CanvasRenderTarget renderTarget;
renderTarget = new CanvasRenderTarget(canvasControl, 400, 400, 96);
```

So is there another way to attach that manually created device or may the Device-Property of CanvasControl has to be set to "get;set;" ?

Best regards

**Comment by clandrew** [comment]
Currently, Win2D's controls have a device assigned to them at creation time and it cannot be changed. For now, the only workaround is to avoid using the controls, and use lower-level objects like CanvasImageSource directly instead.

However, it just so happens that this sprint (and possibly next) we are doing some work to change this. It goes hand-in-hand with the backlog item "Multiple Controls should share a single CanvasDevice". This will be available in an upcoming release, so look forward to it!

I have updated the backlog to call this item out explicitly.

**Comment by SeriousGeorge** [comment]
Ah, that pointed me in the right direction. If you just enter a new Device() as Resource it works splendid. So no need to throw a CanvasControl or CanvasImageSource to the rendertarget.

```c#
CanvasDevice device = new CanvasDevice();
CanvasRenderTarget renderTarget;
renderTarget = new CanvasRenderTarget(device, 400, 400, 96);
```

I then go further on, creating a drawing session and save the pixels as a bytearray to a png. Just fine.

**Comment by clandrew** [comment]
Looks like your scenario didn't actually require a control, after all. Glad to hear everything worked out.
