### ISSUE TITLE
Changelog for Win2D.uwp 1.27.0 (stable)?

### ISSUE THREAD

**Issue by MagicAndre1981** [Microsoft/Win2D#931]
What is the changelog for version 1.27.0? Same as [Win2D 1.27.0-preview3](https://github.com/microsoft/Win2D/blob/8c6cca56e45ee4ec91f7c7e33ef5593e7fec7969/CHANGELOG.md#win2d-1270-preview3)?

**Comment by getrou** [comment]
It is! It is just the public release of preview3 with a couple small internal fixes. You caught us in the middle of deciding whether to move the changelog to MSLearn, but I've pushed the changelog update to github now.

**Comment by MagicAndre1981** [comment]
thanks for publishing the changelog 👍

**Comment by MagicAndre1981** [comment]
@getrou what is the changelog for 1.27.1?

**Comment by getrou** [comment]
Changelog has been pushed!
