### ISSUE TITLE
Use non-version-specific RID folders in NuGet package

### ISSUE THREAD

**Issue by elinor-fung** [Microsoft/Win2D#935]
The `Microsoft.Graphics.Win2D` package includes native assets in `win10-<arch>` directories:
https://github.com/microsoft/Win2D/blob/e63db04e358855beb33a6d4c78aef11c6a733bee/build/nuget/Microsoft.Graphics.Win2D.nuspec#L52-L54

Starting with .NET 8, [the .NET Runtime will not respect these directories](https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/8.0/rid-asset-list) and will only look in non-version-specific directories (`win-<arch>`). As a result, the assets under `win10-<arch>` will not be found.

The recommendation is to switch the package to using `win-<arch>` directories.

The .NET 8 SDK is also [using a smaller simplified RID graph by default](https://learn.microsoft.com/dotnet/core/compatibility/sdk/8.0/rid-graph). When building for a specific RID, a non-version-specific `win-<arch>` should be used.

Related: https://github.com/microsoft/WindowsAppSDK/issues/3783

**Comment by Sergio0694** [comment]
Just to provide an update for this here as well — we merged the fix for this already in the internal repo (Win2D on GitHub is just an upstream mirror of that one), and it will be included in the next feature release (1.1.1), to be released soon 🙂

**Comment by Sergio0694** [comment]
A fix for this is now available, in version 1.1.1 of [Microsoft.Graphics.Win2D](https://www.nuget.org/packages/Microsoft.Graphics.Win2D) 🙂
