### ISSUE TITLE
Upgrade to v1.1.0 causes compiler error

### ISSUE THREAD

**Issue by JonPerkinsOldGit** [Microsoft/Win2D#936]
This morning I allowed a general NuGet update of my Win App SDK project. Once I cleaned out obj and bin folders I ran a full solution rebuild and it failed with the error: 

"A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in order to reference this assembly."

Fortunately I had a full backup so I was able to progressively re-apply NuGet updates at an individual level and found that Microsoft.Graphics.Win2D was the component that caused the error. NB As part of my diagnostic I did run the latest Visual Studio update to 17.7.4 and tried rebuilding again, with no joy.

**Comment by lgBlog** [comment]
`<TargetFramework>net7.0-windows10.0.22621.0</TargetFramework>`

**Comment by JonPerkinsOldGit** [comment]
Thanks for the info. Live and learn :-)

**Comment by vash72** [comment]
> `<TargetFramework>net7.0-windows10.0.22621.0</TargetFramework>`

@lgBlog  by upgrading the windows version in the tfm, do i need to upgrade the TargetPlatformMinVersion accordingly? if this is true it's a big problem, new version of win2d are not compatible with the same tfm of windows app sdk

**Comment by getrou** [comment]
You do not need to change your TargetPlatformMinVersion, that has not changed with the new Win2D release.
