### ISSUE TITLE
A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll

### ISSUE THREAD

**Issue by steam3d** [Microsoft/Win2D#938]
HI. I created a new WinUI3 project with some nuget packages

![image](https://github.com/microsoft/Win2D/assets/30986874/a555ebf2-9d03-4eef-ab63-d8bceeb26c6f)

After adding the Microsoft.Graphics.Win2D I got the error:

```
NETSDK1148 A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll
```

When I remove the Microsoft.Graphics.Win2D  everything fine.

What's wrong?  I have everything updated.

**Comment by getrou** [comment]
Looks like your TargetFramework in your csproj file just needs to be updated to net6.0-windows10.0.22621.0
