### ISSUE TITLE
DrawText() with BorderColor + BorderWidth

### ISSUE THREAD

**Issue by sonnemaf** [Microsoft/Win2D#94]
Hi,

Is it possible or can you add an option (overload) to draw a text with a BorderColor and BorderWidth?

I would like to use it to create a MEME app.

Thanks,

Fons

**Comment by shawnhar** [comment]
Borders, glows, drop shadows, and suchlike effects can be achieved using image effects.  Draw the text into a command list, use that as input for MorphologyEffect in dilate mode, then use a ShadowEffect to color and/or blur the result.

Here are some examples:  http://expediteapps.com/blog/more-texteffects-in-win2d/

**Comment by sonnemaf** [comment]
@shawnhar  Thanks for the tip. I used the following code to write a MEME text.

private void CanvasControl_Draw(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args) {

    var text = "HELLO WORLD";
    var pos = new Vector2((float)(sender.ActualWidth / 2), 100);
    var format = new CanvasTextFormat() {
        FontSize = 100,
        FontFamily = "Impact",
        WordWrapping = CanvasWordWrapping.Wrap,
        HorizontalAlignment = CanvasHorizontalAlignment.Center,
    };

    var renderTarget = new CanvasRenderTarget(sender, (float)sender.ActualWidth, (float)sender.ActualHeight);

    using (var ds = renderTarget.CreateDrawingSession()) {
        ds.Clear(Colors.Transparent);
        ds.DrawText(text, pos, Colors.Black, format);
    }

    var effect = new MorphologyEffect {
        Source = renderTarget,
        Mode = MorphologyEffectMode.Dilate,
        Height = 8,
        Width = 8
    };

    args.DrawingSession.DrawImage(effect, 0, 0);

    args.DrawingSession.DrawText(text, pos, Colors.White, format);
}

**Comment by shawnhar** [comment]
Glad to hear you got this working!
