### ISSUE TITLE
Changelog for Win2D.uwp 1.27.1

### ISSUE THREAD

**Issue by MagicAndre1981** [Microsoft/Win2D#940]
What is the changelog for version 1.27.1?

I see no new commit in the [uwp/main tree](https://github.com/microsoft/Win2D/commits/uwp/main), but a [new version was released on nuget](https://www.nuget.org/packages/Win2D.uwp/1.27.1)

**Comment by Sergio0694** [comment]
We haven't merged from upstream just yet. The changes for UWP are just a small fix in the `Microsoft.Graphics.Canvas.native.h` header that's bundled with Win2D, which was causing a build error in some cases before 🙂

**Comment by MagicAndre1981** [comment]
thanks, next time please push changes first, build it from this repository and provide the PDBs (#836) (with Source Link support to this public repository)

**Comment by Sergio0694** [comment]
We cannot build from this repository, as the way our pipelines are setup is that they get triggered from changes to the internal mirror, not from GitHub. As for PDBs, they should all be available now through the Microsoft symbols server I believe, @getrou can confirm. As for source link, I'm not really sure how that works exactly for C++ myself, but Geoffrey can probably comment on that too 🙂
