### ISSUE TITLE
Microsoft.Graphics.Win2D fail to work with winui after 1.1.0

### ISSUE THREAD

**Issue by ReneeGA2020** [Microsoft/Win2D#943]
The latest working Microsoft.Graphics.Win2D NuGet version is 1.0.5.1

After I upgrade to 1.1.x, it gave me error says 

**Package 'Microsoft.Graphics.Win2D 1.1.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net6.0-windows10.0.19041'. This package may not be fully compatible with your project.**

It looks like it is targeting NETFramework now. And I can no long build my project.

**Comment by getrou** [comment]
This looks an outdated TargetFramework I think. In your project file, it's likely set to "net6.0-windows10.0.19041.0" or something similar. Try updating that to "net6.0-windows10.0.22621.0"

**Comment by ReneeGA2020** [comment]
OK, it worked. But that is weird... as you will need win 11 22H2 to make the latest win2d work.

**Comment by getrou** [comment]
Only the TargetFramework was updated to get the latest 22H2 improvements, the MinPlatformVersion is still 17763 to ensure that Win2D still runs downlevel.
