### ISSUE TITLE
Creating a CanvasRenderTarget with PixelFormat other than B8G8R8A8UIntNormalized crashes

### ISSUE THREAD

**Issue by blelem** [Microsoft/Win2D#95]
Hi,
I am trying to create a YUV render target, NV12 would be my weapon of choice, but any YUV format would be faster than RGB.

On my devbox, calling the following constructor:
`var tt = new CanvasRenderTarget(_canvasDevice, w, h, 96.0f, Windows.Graphics.DirectX.DirectXPixelFormat.B8G8R8A8UIntNormalized, CanvasAlphaMode.Ignore);`
with any other format than `B8G8R8A8UIntNormalized`crashes deep down: the app can't recover. `An unhandled win32 exception occured in ...exe [5968]`
Visual studio (2015 RC) wants to launch another instance of itself to debug the crash, I can't find a way to get any crash data.

This problem has also [been reported by someone else](http://mtaulty.com/CommunityServer/blogs/mike_taultys_blog/archive/2014/10/15/win2d-drawing-infrared-frames-from-the-kinect-for-windows-v2-sensor-in-a-windows-8-1-app.aspx).

I am running Win10 in a VM, I don't know if it matters.

**Comment by blelem** [comment]
Small update: On my other machine, running Win10 directly, and a newer OS build,  I get an exception "bitmap pixel format not supported" instead of a crash.
Is there a way to render a YUV buffer using Win2D?

**Comment by shawnhar** [comment]
Win2D  (and D2D on top of which it is built) do not support rendering to any kind of YUV surfaces.   In fact the set of support formats is quite small:

https://msdn.microsoft.com/en-us/library/windows/desktop/dd756766%28v=vs.85%29.aspx

I've created a backlog item that we should include this info in the Win2D docs.

**Comment by ljw1004** [comment]
I found that MSDN page really hard to read. Here's my restatement of the supported pixel formats: #77 

```
Supported on Lumia635

A8UIntNormalized [Straight | Premultiplied]
B8G8R8A8UIntNormalized [Ignore | Premultiplied]
R8G8B8A8UIntNormalized [Ignore | Premultiplied]
R16G16B16A16Float [Ignore | Premultiplied]

Supported on SurfacePro1: all the above, plus

B8G8R8A8UIntNormalizerSrgb [Ignore | Premultiplied]
R8G8B8A8UIntNormalizedSrgb [Ignore | Premultiplied]
R16G16B16A16UIntNormalized [Ignore | Premultiplied]
R32G32B32A32Float [Ignore | Premultiplied]
```

**Comment by shawnhar** [comment]
I'm closing this issue as the exception is expected due to that format not being supported.

I've created a separate backlog item to track improving the Win2D docs in this area.
