### ISSUE TITLE
Error installing Win2D NuGet in WinUI3 app

### ISSUE THREAD

**Issue by FraserElectronics** [Microsoft/Win2D#951]
I have created a simple WinUI3 application using the standard template in Visual Studio 2022. However, when I try install Win2D 1.1.1 from the Nuget package, I get the following error:

```
Warning	NU1701	Package 'Microsoft.Graphics.Win2D 1.1.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net6.0-windows10.0.19041'. This package may not be fully compatible with your project.
```

What am I doing wrong?

Andy

**Comment by getrou** [comment]
You'll need to update your TargetFramework in your project file from
\<TargetFramework>net6.0-windows10.0.19041.0\</TargetFramework> (or similar) to
\<TargetFramework>net6.0-windows10.0.22621.0\</TargetFramework>

Apologies for the inconvenience, Win2D's next release should be more in line with the current WinUI3 project templates and won't have this issue.

**Comment by FraserElectronics** [comment]
@getrou 
Thanks for the quick answer - that solved my problem 👍

Many thanks.

Andy
