### ISSUE TITLE
“Microsoft.UI.Composition.h”: No such file or directory

### ISSUE THREAD

**Issue by lgztx96** [Microsoft/Win2D#966]
![Image](https://github.com/user-attachments/assets/e651d0ff-7214-4e7f-a3b1-f6009ed4082e)
![Image](https://github.com/user-attachments/assets/12bc9f00-d005-4280-a922-709fc1adbf35)

**Comment by getrou** [comment]
Hello, thanks for your interest in Win2D's interop APIs!

Looks like you're using C++/WinRT. Use "winrt/Microsoft.Graphics.Canvas.h" instead of "Microsoft.Graphics.Canvas.h" and you should be off to the races!

**Comment by lgztx96** [comment]
> Hello, thanks for your interest in Win2D's interop APIs!
> 
> Looks like you're using C++/WinRT. Use "winrt/Microsoft.Graphics.Canvas.h" instead of "Microsoft.Graphics.Canvas.h" and you should be off to the races!


This doesn't work, the compiler is giving an error C2027: use of undefined type 'ABI::Microsoft::Graphics::Canvas::ICanvasDevice', it seems to be defined in <Microsoft.Graphics.Canvas.h>.
![Image](https://github.com/user-attachments/assets/27bab889-7e08-41a0-b0fe-c2fe513f87c6)
![Image](https://github.com/user-attachments/assets/4abec66f-f311-4b25-bd7e-ecb81d7fb807)
