### ISSUE TITLE
Suggestion: make PixelShaderEffect more efficient

### ISSUE THREAD

**Issue by benstevens48** [Microsoft/Win2D#969]
As far as I can tell, whenever an instance of the PixelShaderEffect is created, it makes a new copy of the shader bytes, computes the hash of it, and reflects over it to determine its properties. This really only needs to be done once. I would like to propose the following solution. Add an additional constructor for PixelShaderEffect with an additional Guid parameter which will be a unique ID for the shader effect. Cache a copy of the bytes and properties discovered during reflection by using the Guid as the key. On subsequent initializations, reuse the shared cache (and do not create a copy of it). I think the ShaderDescription class could be used as the cached state, with some additional state from SharedShaderState moved to ShaderDescription. Finally, optionally add a static method on PixelShaderEffect to clear the cache for a given Guid.

Although, having said, all that, I think maybe [ID2D1EffectContext::LoadPixelShader](https://learn.microsoft.com/en-us/windows/win32/api/d2d1effectauthor/nf-d2d1effectauthor-id2d1effectcontext-loadpixelshader) will be called for each effect instance anyway, and I guess this creates a new copy of the shader each time? But I'm not sure. So perhaps the time spent here would negate most of the benefit of speeding up the PixelShaderEffect constructor. Probably requires some timing testing/someone with more knowledge to comment.

**Comment by Sergio0694** [comment]
`PixelShaderEffect` is a legacy effect and has a whole lot of limitations, and we have no plans to change it. If you're using C#, the recommended path to having custom shaders using Win2D is to [use `PixelShaderEffect<T>` from ComputeSharp](https://learn.microsoft.com/en-us/windows/apps/develop/win2d/custom-effects#custom-effects-in-c-using-computesharp) (see linked docs). That includes all kinds of improvements, bug fixes, and new features, and doesn't have the limitations that the Win2D effect has 🙂

**Comment by benstevens48** [comment]
OK, I guess this suggestion might not help much because I think each instance of the effect probably has to copy the shader bytes to the GPU anyway (not sure because I don't have a deep understanding of DirectX). However I kind of disagree with the PixelShaderEffect in Win2D being classed as legacy. I'm using it from C++ and I don't see an easy alternative. Also, it works very well in most cases and has surprisingly few limitations and no bugs that I've come across - the only limitation I've come across myself is when wanting to customise the source bounds to output bounds mapping. Nice to have a good option in C# though. I may have used C# if interop had been easier back when I started the project.

**Comment by Sergio0694** [comment]
You need to use `LoadPixelShader` in each instance, yes, however the GPU driver should cache the compiled bytecode for you. Yeah `PixelShaderEffect` does work (it's not like it's flat out broken, it's just not great), but it has some issues and limitations such as:
- No support for D2D resource textures
- No support for custom transform mapping
- Limited to PS4.0
- Uses reflection to set constant buffer values individually
- There might be more I can't remember right now

**Comment by benstevens48** [comment]
Actually, I think I'm going to implement my suggestion in my own Win2D fork, since I think it will not be too difficult. I will also submit a pull request here. I expect you won't merge it, but just in case you want to merge it at some point in the future, do you have any objection to the proposed, hopefully self-explanatory, API?
```C#
static void PixelShaderEffect.RegisterEffect(UInt8[] shaderCode, Guid id, Int32 maxSamplerOffset, SamplerCoordinateMapping[] coordinateMappings, EffectBorderMode[] borderModes, CanvasImageInterpolation[] sourceInterpolations);
static PixelShaderEffect PixelShaderEffect.CreateEffect(Guid id);
static PixelShaderEffect PixelShaderEffect.RegisterAndCreateEffect(UInt8[] shaderCode, Guid id, Int32 maxSamplerOffset, SamplerCoordinateMapping[] coordinateMappings, EffectBorderMode[] borderModes, CanvasImageInterpolation[] sourceInterpolations);
static Boolean PixelShaderEffect.IsEffectRegistered(Guid id);
static void PixelShaderEffect.UnregisterEffect(Guid id);
```
