### ISSUE TITLE
invalidate specific area

### ISSUE THREAD

**Issue by FabricioCabeca** [Microsoft/Win2D#98]
Hi, I wonder if it is possible to invalidate a specific area of the CanvasControl, so it does not need to repaint it all, it could improve performance in such cases. It would work like android's invalidate:

http://developer.android.com/reference/android/view/View.html#invalidate%28android.graphics.Rect%29

**Comment by damyanp** [comment]
This certainly is possible.  I've added this to the backlog.  I suspect that it would be quite rare to get any actual noticeable performance increase in this, unless the scene was extremely complex.

If you run into a problem where you think that you would benefit from being update to do partial updates then you can use CanvasImageSource directly. See the [ImageSourceUpdateRegion](https://github.com/Microsoft/Win2D-Samples/blob/master/ExampleGallery/Shared/ImageSourceUpdateRegion.xaml.cs) sample in ExampleGallery to see this in action.

**Comment by FabricioCabeca** [comment]
Thanks ! I will take a look at this.

Anyway, it would be extremely helpful in my project, the scene may become quite complex in some cases and the android version of this project does use it a lot.

**Comment by FabricioCabeca** [comment]
Hi again, about the project I am working on, the relevant part is the async painter: https://github.com/Pmovil/CN1WindowsPort/blob/master/src/com/codename1/impl/WindowsAsyncView.cs
It is a compatibility layer to draw using a swing like approach, it works pretty well except for a few issues I am working on. I believe there is still a lot of room for improvements in the rendering pipeline besides this invalidate suggestion, any wisdom here would be welcome

**Comment by damyanp** [comment]
Hi - as of Win2D version 1.3.0 we've added the [CanvasVirtualControl](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_UI_Xaml_CanvasVirtualControl.htm).  I believe that this is a better fit for scenarios where subregions of the control need to be updated and would recommend using it in these cases.

I'm going to close this issue since we have no plans to add invalidate region to CanvasControl now that we have CanvasVirtualControl instead.

**Comment by FabricioCabeca** [comment]
Thanks ! This seems like it'll do the job, I had a problem with certain clip sizes, I'll open a separate issue for that.
