### ISSUE TITLE
CanvasBitmap.LoadAsync() for changing texture during runtime does not work in latest builds (for me)

### ISSUE THREAD

**Issue by pret83** [Microsoft/Win2D#99]
Hi guys. I used to change texture during runtime for example from a button event handler like:
```C#
CanvasBitmap oldBitmap = Texture;
Texture = await CanvasBitmap.LoadAsync(canvas, newTexturePath);
infiniteEffect.Source = Texture;
if (oldBitmap != null)
    oldBitmap.Dispose();
canvas.Invalidate();
```
I've updated the Win2D nuget pckage in my sollution, and since this method does not work for me. The LoadAsync method just won't return. Any hints what's wrong with my code and how to accomplish the texture change?

**Comment by shawnhar** [comment]
We will need a repro to investigate this issue.  Can you isolate the code that isn't working into a standalone app, then either upload that somewhere or (if you can get the code fragment that isn't working small enough) post it here so we can paste into a new project of our own?

Thanks,

**Comment by pret83** [comment]
Hi Shawn. In a simple project it works, I've found the method in my code, which causes the bug, so you can close the issue. It's my fault.

**Comment by shawnhar** [comment]
Glad you got this working!
